### ISSUE TITLE
Private packages should be fetchable

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/berry#10]
**Describe the user story**

I'm an application author and I want to add a dependency to a private package.

**Describe the solution you'd like**

We should add new configuration settings to plugin-npm: `npmUser`, `npmToken`, and `npmAlwaysAuth`.

We probably should add a new configuration type called `SECRET` that wouldn't appear when running `yarn config` but would appear when running `yarn config -v`. This would be helpful for CI systems that want to validate that the configuration is correctly set.

**Describe the drawbacks of your solution**

It adds some complexity, especially since it's not clear when the token should or shouldn't be sent.

Our test infrastructure doesn't support private packages at the moment, and emulating this behavior might be relatively complex since we would have to reverse-engineer what the npm registry is doing.

**Describe alternatives you've considered**

We could decide not to support private packages by default, but the maintenance cost seem low enough that it seems worthwhile.

**Comment by bgotink** [comment]
Should we only support token auth?

NPM and yarn currently support three ways of configuring authentication:

- `username` and `_password`, where the password is base64-encoded
- `_auth`, which is `base64(username + ':' + _password)`
- `_authToken`

The first two methods are basically the same, the `username` + `_password` combination gets transformed into the corresponding `_auth` value, this `_auth` value gets sent via the `Basic` header. The token gets sent via `Bearer`.

I understand wanting to remove the duplication between `username`+`_password` and `_auth`, but I personally would still support at least one of the two options for authentication. Not every private registry supports tokens, e.g. SonaType Nexus 2.

https://github.com/yarnpkg/yarn/blob/723fc3ef7fb36e01bf0c9ccd713979fac87796cc/src/registries/npm-registry.js#L359-L378

**Comment by arcanis** [comment]
Good point - I've never used private packages myself so I'm a bit rusty there 😄

I'm fine with having both `_auth` and `_authToken` (we'll need a `login` command to be added to the npm plugin, though). I think `_auth` should be made more explicit though: `npmAuthIdent` and `npmAuthToken`?

There might also be the question of 2FA - I don't remember whether that also affects private packages pulled from the registry, or only those which are pushed to it. Implementation was there:

https://github.com/yarnpkg/yarn/pull/6555/files

**Comment by arcanis** [comment]
Closing, it got implemented in #95 and #119 👌
