### ISSUE TITLE
[Feature] Bulk upgrade dependencies across a single workspace or workset

### ISSUE THREAD

**Issue by Robula** [yarnpkg/berry#1009]
- [x] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**
- We would like the ability to upgrade all dependencies within a workspace.
- We would like the ability to upgrade all dependencies within a workset.

**Describe the solution you'd like**
Much like `yarn@1` where we could use `yarn upgrade` or `yarn upgrade --latest` to upgrade packages in bulk; a similar feature would be appreciated for Berry. 

For worksets this could be simply `yarn upgrade` or `yarn up all`.
For individual workspaces: 
`yarn workspace <workspace> upgrade` or `yarn workspace <workspace> up all` 

**Describe the drawbacks of your solution**
The primary risk is that blindly upgrading all your packages could break project tests and these would need to be fixed to accommodate new dependency versions. Arguably, not updating dependencies frequently only adds more debt to the project. 

**Describe alternatives you've considered**
I have already successfully used `@yarnpkg/plugin-interactive-tools` to manually select every single package for upgrade, however this already feels tedious to use on a large workset.

**Additional context**
Given the nature of the awesome PnP system and the strict package boundaries; `package.json` dependencies lists are going to be bigger than ever so this further increases the desire for this feature.

**Comment by arcanis** [comment]
I think this is typically something that you'd implement as a plugin. The exact details of "upgrade everything" are tricky to get right for every workflow (upgrade EVERYTHING? only direct dependencies? only dev dependencies? exclude dependencies X, Y, Z? only up to the next major? etc), so I'd prefer to let you decide and implement the exact logic you want.

**Comment by Robula** [comment]
Thanks @arcanis. For arguments sake let's say I wanted to check what direct dependencies were out of date in my workset. Firstly how would I identify what packages are out of date? Secondly how would I go about upgrading these dependencies without calling `yarn up dep1 && yarn up dep2 && yarn up dep3 ...` repeatedly?

In Yarn@1, we could upgrade all direct dependencies and descendent packages simply by using `yarn upgrade`.

Thanks in adva

**Comment by arcanis** [comment]
You'd write a [plugin](https://yarnpkg.com/advanced/plugin-tutorial). As for "what would the code look like", check [up.ts](https://github.com/yarnpkg/berry/blob/master/packages/plugin-essentials/sources/commands/up.ts) - if you remove the interactive part, it's only about a hundred lines of significant code.

Basically, the idea is that you instantiate a `Project`, iterate over the workspaces' dependencies, call `suggestUtils.getSuggestedDescriptors` for each one, update the descriptors in the workspaces instances, then call `project.install` which will persist everything on disk.

**Comment by wesrice** [comment]
@arcanis Do you have any insight why this wasn't implemented as part of Yarn v2, although it is a feature of Yarn v1? I understand that this _can_ be a plugin, but I'm wondering if it _should_ be a first-party plugin.

**Comment by arcanis** [comment]
I answered this in my first comment:

> I think this is typically something that you'd implement as a plugin. The exact details of "upgrade everything" are tricky to get right for every workflow (upgrade EVERYTHING? only direct dependencies? only dev dependencies? exclude dependencies X, Y, Z? only up to the next major? etc), so I'd prefer to let you decide and implement the exact logic you want.

**Comment by wesrice** [comment]
@arcanis Forgive my persistence. I just want a better understanding of this. 

I see what you're saying, but I'm still having a hard time reconciling that Yarn 1 is capable of upgrading all dependencies, which seems contrary to the position you stated for Yarn v2.

I fear that there might be an underlying sentiment that I'm failing to recognize that can help me, and perhaps others, understand what is expected of the users of Yarn v2.

Is the removal of `yarn upgrade` due to a philosophical shift with Yarn 2 that I need to better understand? Is the Yarn organization implicitly advising against updating all packages at once or perhaps just fails to see the need to do so?

Thanks for your time.

**Comment by arcanis** [comment]
> Is the Yarn organization implicitly advising against updating all packages at once or perhaps just fails to see the need to do so?

My message explicitly points out that there are many ways to "update all packages at once", all subtly different. This suggests that the Yarn core isn't the right place where we should implement this solution, at least not unless an active maintainer decides to take ownership of it and design a battle plan to address all the concerns. I personally have other areas of interest 🙂

**Comment by Robula** [comment]
I would have thought that a package manager such as Yarn; at it's core would have the capability to update the packages it manages. It's just as an essential feature for a package manager as `add`/`remove` is.

If `yarn remove` wasn't a feature you could argue that to remove a package you just remove the relevant line in `package.json` and then run `yarn`, if you wanted a command `yarn remove` to save time then a third party should write and maintain a plugin.

Most users migrating to Berry from Yarn 1 you would expect the same ~basic~ **core functionality** that they have been using for years. 😄

**Comment by arcanis** [comment]
> I would have thought that a package manager such as Yarn; at it's core would have the capability to update the packages it manages. It's just as an essential feature for a package manager as `add`/`remove` is.

It does have the ability to upgrade the packages it manages: it's the `yarn up` command you mention. Your issue is specifically about *bulk upgrade*. This is a vastly different problem.

> Most users migrating to Berry from Yarn 1 you would expect the same ~basic~ **core functionality** that they have been using for years. 😄

Most users migrating to Berry aren't the ones who are going to maintain Berry for the years to come. Fortunately, they can easily implement their own solution and prove us that it should be integrated into the core. We're talking about a hundred lines, here 🙂

**Comment by CodeDead** [comment]
We wrote a plugin to address this by the way:
https://github.com/e5mode/yarn-up-all

**Comment by merceyz** [comment]
You can already update everything in one by by running `yarn up "**"` (careful with git dependencies), the up command supports glob patterns so you can be as picky as you want

**Comment by djmarland** [comment]
Sadly `yarn up "**"` doesn't respect semantic ranges in the package.json like `yarn upgrade` used to. It's equivalent to `yarn upgrade --latest` so jumps major versions

**Comment by ridem** [comment]
@djmarland I believe the closest to the former `yarn upgrade` is `yarn up '**' -R`, which is only available since v3 (see https://github.com/yarnpkg/berry/blob/master/CHANGELOG.md#300-rc1).
Running `-R` doesn't touch your manifest, but resolves all ranges again.
