### ISSUE TITLE
[Feature] .yarn/{plugins, releases} stored compressed/minified

### ISSUE THREAD

**Issue by jacogr** [yarnpkg/berry#1013]
**Describe the user story**

So, this may be a "wontfix", but asking anyway... Currently we are required (or rather recommended) to check in the `.yarn/{plugin. releases}` folders. The negative side effect of this is -

- we are adding a lot of lines on each single commit (90K+ when adding berry + 2 plugins in my case)
- it hurts my OCD since my nice TypeScript-only repos are now showing up as "JS" due to the large number of lines of code (all caused by the plugins)

**Describe the solution you'd like**

There are 2 things that can happen -

- like the `.yarn/cache` these files can be added compressed (execution can uncompress with a small step)
- at the very least the massive plugins can be minified, they show up with something like this -

```js
/* eslint-disable*/
module.exports = {
  name: "@yarnpkg/plugin-interactive-tools",
  factory: function (require) {
                          var plugin =
  /******/ (function(modules) { // webpackBootstrap
  /******/ 	// The module cache
  /******/ 	var installedModules = {};
  /******/
  /******/ 	// The require function
  /******/ 	function __webpack_require__(moduleId) {
  /******/
  /******/ 		// Check if module is in cache
  /******/ 		if(installedModules[moduleId]) {
  /******/ 			return installedModules[moduleId].exports;
...
```

**Describe the drawbacks of your solution**

For compression, I see drawbacks in that it will add a slight delay in execution, and the actual engine may not support it out of the box.

When looking at just minifying the plugins, I don't see drawbacks - `.yarn/releases/yarn-berry.js` is nicely cleaned up from all the import gunk.

**Describe alternatives you've considered**

No alternative that I thought of, 2 approaches mentioned here. As a manual work-around have minified the plugins myself. (And then tested if they still work - some normality restored. Not scalable to all users, but solves my immediate issue)

**Additional context**

None.

**Comment by arcanis** [comment]
The reason they aren't minified is that plugins are meant to be fairly small compared to the core (a few kilobytes), so it wasn't that important (and not minifying them can be handy for debug purposes).

It's not entirely true for plugins that have rich UIs due to their dependency on React, unfortunately, but I'm not sure it's worth minifying them... 🤔 Maybe the solution to this would be to make `libui` a dynamic lib, this way plugins wouldn't have to ship it. We'd have to see the size impact of this.

> * it hurts my OCD since my nice TypeScript-only repos are now showing up as "JS" due to the large number of lines of code (all caused by the plugins)

We need to open a PR on [Linguist](https://github.com/github/linguist) to flag `.yarn` as being a vendored folder, and thus exclude its content from the repo stats. Care to open a PR there?

**Comment by jacogr** [comment]
https://github.com/github/linguist/pull/4810

**Comment by jonaskuske** [comment]
@jacogr 


> - we are adding a lot of lines on each single commit (90K+ when adding berry + 2 plugins in my case)  
> - it hurts my OCD since my nice TypeScript-only repos are now showing up as "JS" due to the large number of lines of code (all caused by the plugins)

For a), are you changing your yarn version and plugins all the time or why are you adding them to every single commit?

For b), you could add a `.gitattributes` file containing `.yarn/ linguist-vendored` (until the PR is merged) and your stats should be clean and full of TypeScript again 😄

**Comment by jacogr** [comment]
I am not adding them each commit - they are just added once. (It only changes when actually updated, which is manual)

Thanks for the tip on `.gitattributes`, was not aware of that.
