### ISSUE TITLE
Does not use globally installed node-gyp

### ISSUE THREAD

**Issue by jeffrson** [yarnpkg/berry#1016]
**Describe the bug**

I'm trying to install "argon2" (`yarn add argon2`) with node 13.9.0 - there's no prebuilt binary yet, so it needs to be built.

First there is a YN0032 warning - I've read https://yarnpkg.com/advanced/error-codes#yn0032---node_gyp_injected and I could fix the issue by `yarn add node-gyp`. I thought about reporting a bug against argon2 - such that the should need to declare a peerDependency or dependency.

However, I was wondering why yarn does not use the node-gyp version I had installed previously by `npm i -g node-gyp`.

Should it use an existing node-gyp (like yarn1 does)?

**Comment by arcanis** [comment]
> However, I was wondering why yarn does not use the node-gyp version I had installed previously by npm i -g node-gyp.

Because Yarn aims to provide reproducible builds, and relying on global binaries would necessarily goes against this goal (you'd have a different `node-gyp` version from one install to another, causing different issues to appear).
