### ISSUE TITLE
[Question] How to handle @babel/runtime

### ISSUE THREAD

**Issue by Js-Brecht** [yarnpkg/berry#1017]
I am looking for advice on how to move forward with a project I am working on.

The issue I am having is how `@babel/plugin-transform-runtime` inserts `require()` statements to `@babel/runtime` like `@babel/runtime/helpers/interopRequireDefault`.  Basically, unless the user has `@babel/runtime` installed in their project, running babel will fail.

I understand that to make it work, it's as easy as installing `@babel/runtime` in the project.  However, what I am developing is a plugin which is going to be doing transformations on some of the user's source files so that they can be consumed.  I am trying to make this plugin's usage as straightforward as possible, and requiring the user to install new dependencies that they aren't even going to use is just bad DX.

There are a couple of options that are apparent to me so far:

1. Additional documentation to say, "hey, if you're using yarn2, you _**might**_ need to install this other package.  Don't worry, you won't need it, but the plugin **MIGHT**"
   * This is definitely not foolproof, because not everybody reads documentation.  And then there's plenty of frustration when things don't work how they should, then research (maybe) to figure out why... or it just gets abandoned.
2. Hard fail in the plugin if that particular package is not installed, maybe with a helpful error message.

Both of these options are rather poor, IMO.  I would very much prefer to install `@babel/runtime` in the plugin, and have it be available to the user's project automatically.  Can't seem to get that to work, however.

What would be great is if there were a way to define the resolution location of some kind of transitive dependency like this one, but maybe I'm just missing the real solution.

I would be grateful for any advice.

---

You can find an example reproduction here: https://github.com/Js-Brecht/babel-transform-runtime-issue

The folder `source` is basically the "user's project", while `register` is the "plugin".  In source, you can run `yarn start`, and it will show the error.  Obviously, running everything from the context of that project, it would make sense to install `@babel/runtime`.  

Running `yarn exec` will kind of replicate the process I'm looking for.  Having a dependency execute `@babel/register`, and then execute one of the user's scripts.  I do have `@babel/runtime` installed in the "plugin", but that doesn't help any.

Running `yarn exec2` will replicate another type of processing that will be done.  There will be a runtime path for the plugin that will do ahead-of-time transpiling using babel, so that the scripts can be executed normally later on.  Same problems.

**Comment by Js-Brecht** [comment]
Not really a case study, but I wasn't sure what other type of issue to create.  Not really requesting a feature, or reporting a bug :man_shrugging:

**Comment by larixer** [comment]
@Js-Brecht Yarn supports peerDependencies with with defaults, e.g. you can declare in your plugins `package.json:`
```
{
  "dependencies": {
    "@babel/register": "^7"
  },
  "peerDependencies": {
    "@babel/register": "^7"
  }
}
```
and this will install `@babel/register` to the user project automatically, without action needed from the user. And the same time if user already has `@babel/register` in his project, user's version of `@babel/register` will be used.

I wonder is this the thing you are looking for?
For more details:
https://github.com/yarnpkg/berry/issues/1001

**Comment by Js-Brecht** [comment]
@larixer I thought about that, because that's worked for me in the past.  Not so with this particular package.  That package does not operate the same way most commonly do, with a main entry point.  Each of the utilities in it are required directly... so, maybe this is what causes it to fail... ?

For example, if I try to run `require.resolve('@babel/runtime')` from within `yarn node`, it will throw an error: module not found.  However, if I run `require.resolve('@babel/runtime/helpers/interopDefaultRequire')`, it will return the path.

Regardless, adding that package as a peer dependency does not work for this one.

**Comment by Js-Brecht** [comment]
One thing that is interesting.... 

Of course, I cannot resolve `@babel/runtime` utilities from the calling project; however, if I resolve the path from within the plugin and replace the required utility with the resolved path, it works.

So, say I have two typescript files that look like this:
```ts
// test.ts
export default () => console.log('test');

// index.ts
import testLogger from './test';
testLogger();
```

They transpile to:
```js
// test.js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;

var _default = function _default() {
  return console.log('test');
};

exports["default"] = _default;
```

```js
// index.js
"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");

var _test = _interopRequireDefault(require("./test"));

(0, _test["default"])();
```

Now, when I go to the plugin, manually resolve the path, and replace the require path:
```diff
- var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");
+ var _interopRequireDefault = require("/home/jeremy/.yarncache/berry/cache/@babel-runtime-npm-7.8.4-e3028a5d42-2.zip/node_modules/@babel/runtime/helpers/interopRequireDefault.js");
```

I can then execute the plugin from the source project, making it call that `index.js`, and it will work correctly

**Comment by larixer** [comment]
@Js-Brecht I think default peerDependencies should really work in this case, @arcanis I think it is the problem with `workspaces + peers`, which should be fixed, correct me if I'm wrong.

**Comment by Js-Brecht** [comment]
> I think it is the problem with `workspaces + peers`, which should be fixed

Perhaps my configuration is wrong?  I've have `@babel/runtime` set up as a peer dependency, and as a production dependency as well.

> I think default peerDependencies should really work in this case

I would like very much for it to.  Is that feature still WIP?  I see the RFC you linked to is pretty new.

**Comment by arcanis** [comment]
I'm not sure peer dependencies would be the fix - if I understand correctly in your case you'd have Foo depends on MyTranspiler, and you'd want Foo to access Runtime without listing it inside its dependencies - somehow accessing it only because MyTranspiler happens to depend on it. Peer dependencies can only go the other way, with Foo giving access to something to MyTranspiler.

I think this issue is fixed if you set the `absoluteRuntime` flag with `plugin-transform-runtime` (which is basically what you mentioned by manually resolving the path):
https://babeljs.io/docs/en/babel-plugin-transform-runtime#absoluteruntime

If absolute paths are too much of a problem, there's a PR to implement relative support; I never got around to finish it but if you're interested to give it a shot I think the Babel maintainers would be happy to land it once ready: https://github.com/babel/babel/pull/10378

Another option (more generic, outside of Babel-land) would be to transform your imports to turn this following code:

```ts
const {foo} = require('runtime');
```

Into:

```ts
const {foo} = require('transpiler/runtime');
```

With `transpiler/runtime.js` being:

```ts
module.exports = require(`runtime`);
```

Of course it doesn't work very well if the runtime has many individual entry points (like it's the case for `babel/runtime`) because then you'd have to create indirections for every single file ...

**Comment by Js-Brecht** [comment]
> I'm not sure peer dependencies would be the fix - if I understand correctly in your case you'd have Foo depends on MyTranspiler, and you'd want Foo to access Runtime without listing it inside its dependencies - somehow accessing it only because MyTranspiler happens to depend on it. Peer dependencies can only go the other way, with Foo giving access to something to MyTranspiler.

Thank you for the explanation.  It makes more sense to me now.

I was considering writing a babel plugin that I could hook into the transformation from the transpiler plugin's context to resolve certain paths as they are encountered.  Kind of like `babel-plugin-module-resolver` but... not exactly.

> I think this issue is fixed if you set the `absoluteRuntime` flag with `plugin-transform-runtime` (which is basically what you mentioned by manually resolving the path)

I think this should actually be perfect.  These files are transpiled specific to the runtime, so using absolute paths should definitely work.

I have been rather disappointed in the quality of the babel documentation to date, and it rarely (if ever) answers my questions.  So, I admit, I didn't read the documentation thoroughly for that plugin.  Thank you very much for the direction 🙏.

---

After a brief examination of the code for that option, I'm pretty certain it will work.  I am closing this issue now.  Thanks again!

**Comment by Js-Brecht** [comment]
Btw, using that option worked perfectly.
