### ISSUE TITLE
[Feature] Do not overwrite .yarnrc.yml ufter install yarn2

### ISSUE THREAD

**Issue by zdm** [yarnpkg/berry#1026]
After install yarn2 with `yarn set version berry` config file `.yarnrc.yml` is always overwritten.
Is it possible to do not touch it if it is already exists?
Or overwrite only `yarnPath` line?

**Comment by arcanis** [comment]
`js-yaml` doesn't generate an AST, so we can't change `yarnPath` without erasing the comments at the moment. I'm not sure what it would take to give it this ability.

**Comment by zdm** [comment]
So, it should not overwrite this file, because settings like `packageExtensions` become lost.

**Comment by zdm** [comment]
By the way, I think you do no need AST. You can just patch file using regexp. This is yaml, file structure is known and always the same.

**Comment by mekwall** [comment]
@arcanis Why not switch to [`yaml`](https://github.com/eemeli/yaml) instead? It has AST and a very intuitive API to manipulate the document, including comments.

**Comment by paul-soporan** [comment]
Going to close this in favor of #1463, which tracks the same thing. I'll post a status update on this there.
