### ISSUE TITLE
[Bug] Wrong link in the documentation

### ISSUE THREAD

**Issue by arznaar** [yarnpkg/berry#1029]
- [ ] I'd be willing to implement a fix

There is a link to `#npmServer` section, but there is no such section in docs

**Additional context**

Here is the line with an error https://github.com/yarnpkg/berry/blob/572775e2adc8b342b33c349218c1a9b290e31bee/packages/gatsby/src/pages/configuration/yarnrc.js#L178

**Comment by arznaar** [comment]
I'd fixed it, but I'm still trying to get my head around possible yarn configs and I'm not sure what `npmServer` means in this context. Is it called `npmRegistries` now?

**Comment by arcanis** [comment]
Yep. However the architecture of this page should change heavily with #1008, so maybe we can wait until then before fixing it, to avoid conflicts? cc @paul-soporan

**Comment by paul-soporan** [comment]
I applied the changes @arcanis suggested in #1008, so that PR should be ready. :+1:
