### ISSUE TITLE
[Feature] package.json vars

### ISSUE THREAD

**Issue by alejalapeno** [yarnpkg/berry#1033]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Yarn 1.X and npm attach package.json fields to `process.env` with a prefix of `npm_package_`. For access by code: https://docs.npmjs.com/misc/scripts#packagejson-vars 

Missing these values in Yarn 2/Berry causes breaks for scripts/code that relies on them.

**Describe the solution you'd like**

Replicate the original behavior.

**Describe the drawbacks of your solution**

Possibly causes a slight increase in runtime/memory usage.

**Describe alternatives you've considered**

I could write my own script to parse the package.json, but this has been an existing feature that is now missing.

**Comment by DeedleFake** [comment]
Just ran into this today. Was quite surprised to see that it wasn't supported.

**Comment by merceyz** [comment]
Closing in favour of https://github.com/yarnpkg/berry/issues/1659
