### ISSUE TITLE
`yarn add` does nothing with node>=13.10.0

### ISSUE THREAD

**Issue by jeffrson** [yarnpkg/berry#1041]
**Describe the bug**

`yarn2 add <package>` does not appear to do anything when run from nodejs 13.10.0/13.10.1

**To Reproduce**

Have nodejs 13.10 active, then inside an empty folder

yarn set version berry
yarn init
yarn add -D typescript

=> nothing happens (no change to package.json, no output)

**Environment if relevant (please complete the following information):**

 - OS: [e.g. OSX, Linux, Windows, ...] Windows 10
 - Node version [e.g. 8.15.0, 10.15.1, ...] 13.10.0
 - Yarn version [e.g. 2.0.0-rc1, ...] 2.0.0-rc29

**Additional context**

13.9.0 does not have this issue

**Comment by arcanis** [comment]
Node 13.10 shipped with a regression that kills `got`: https://github.com/sindresorhus/got/issues/1107

I believe it should be fixed in the next Node release: https://github.com/nodejs/node/issues/32105 / https://github.com/nodejs/node/pull/32110
