### ISSUE TITLE
[Feature] Lerna-like symlinking with plugin-node-modules

### ISSUE THREAD

**Issue by elmpp** [yarnpkg/berry#1048]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Given i have enabled the nodeLinker via `.yarnrc.yml` and run an install
I see that all packages are installed to the root `node_modules`. (I was expecting to 
see some nested `node_modules` however?)
I also see that this root `node_modules` contains symlinks to dependent workspaces

**Describe the solution you'd like**

I would like to see these symlinks created in a nested `node_modules` within the workspace declaring dependencies on other workspaces. This would operate similar to [lerna link](https://github.com/lerna/lerna/tree/master/commands/link). 
This would forcibly surface undeclared dependencies in other workspaces

**Describe the drawbacks of your solution**

It would be more complex to collate existing installed state across the project

**Describe alternatives you've considered**

My use case is for non-dynamic configuration files (e.g. `tsconfig.json`) that reference resources published externally (e.g. a types package). Although I could use an relative ancestor link, I am `git subtree split` this package which will then fail outside the monorepo context

**Comment by arcanis** [comment]
If I understand correctly you'd like to prevent hoisting the workspace symlinks? If that's the case I don't think we really want to do that. If you use the node_modules linker then the assumption is that your app relies on the hoisting in some way, and if you want to surface undeclared dependencies then you should use the default PnP linker.

**Comment by larixer** [comment]
@elmpp My comment to the similar issue might be relevant for this issue as well:
https://github.com/yarnpkg/berry/issues/1050#issuecomment-596659082
E.g. you can have all your workspaces to be installed independently if you want by creating empty `yarn.lock` in each of them prior to running `yarn` in each workspace directory.

**Comment by elmpp** [comment]
> If I understand correctly you'd like to prevent hoisting the workspace symlinks? If that's the case I don't think we really want to do that. If you use the node_modules linker then the assumption is that your app relies on the hoisting in some way, and if you want to surface undeclared dependencies then you should use the default PnP linker.

That is correct - to not hoist workspace symlinks. When `lerna link` creates these symlinks they're reliably within the workspace's n_m. 

This is necessary in some `json` configuration files that do not do resolving. e.g.
```
// tsconfig.json
{
  ...
  "include": ["src/**/*", "./typings/", "./node_modules/utility-types"],
  "exclude": [
    "**/dist",
  ]
}
```

**Comment by larixer** [comment]
@elmpp Not hoisting workspaces will mean breaking compatibility with `yarn 1`, we cannot do this, at least, not by default. And it is unclear how hoisting workspaces can be implemented, someone should come up with proposal how to do that while still maintaining compatibility with yarn 1, then we can discuss the proposal and decide on plan of action.

**Comment by elmpp** [comment]
> @elmpp Not hoisting workspaces will mean breaking compatibility with `yarn 1`, we cannot do this, at least, not by default. And it is unclear how not hoisting workspaces can be implemented, someone should come up with proposal how to do that while still maintaining compatibility with yarn 1, then we can discuss the proposal and decide on plan of action.

To be clear this would be specifically for the workspace symlinks and not the packages themselves. 

I guess i'm trying to emulate `lerna link` behaviour here so it'd probably fall under the realm of a custom plugin i should imagine.

Out of interest what would be the behaviour if a workspace was declared as a dependency like so:

```
// packages/a/package.json
  ...
  version: "0.0.2"
```
// packages/b/package.json
  ...
  dependencies: {
    packageA: "0.0.1",
}
```

```
// packages/c/package.json
  ...
  dependencies: {
    packageA: "^0.0.1",
}
```

Would `packages/b/node_modules` contain a symlink to `packageA`?

**Comment by larixer** [comment]
@elmpp In this case, please clarify your request, I don't know what is `lerna link`

**Comment by larixer** [comment]
I'm closing this issue as invalid, because it states false information. Yarn 2 creates symlinks for workspaces while issue states otherwise.
