### ISSUE TITLE
[Bug] buildNodeModulesTree not respecting package aliases

### ISSUE THREAD

**Issue by Baune8D** [yarnpkg/berry#1065]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I want to migrate a project to Yarn 2, but it uses tools that is incompatible with PNP, so i want to use ```nodeLinker: node-modules```, the only problem we have is that a project is using aliasing to install two version of the same package, but Yarn 2 does not seem to respect the alias.

**To Reproduce**

https://github.com/Baune8D/yarn-berry-aliasing
Run ```yarn install```, node_modules only contains 1 folder named bootstrap containing version 3.4.1

**Environment if relevant (please complete the following information):**

 - OS: macOS Catalina
 - Node version 12.14.1
 - Yarn version 2.0.0-rc29

**Comment by larixer** [comment]
@Baune8D Should be implemented via: #1499. Could you give it a try and report back?
`yarn set version from sources --branch 1499`

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/1499
