### ISSUE TITLE
[Bug] NpmTagResolver is too strict for tag names

### ISSUE THREAD

**Issue by ckniffen** [yarnpkg/berry#1075]
- [x] I'd be willing to implement a fix

**Describe the bug**

npm allows tags to use any character as long as the first character is not a "v" or number.

**To Reproduce**

```
{
  "name": "tag-test",
  "description": "Test tags with hyphens and numbers",
  "dependencies": {
    "puppeteer": "chrome-72"
  }
}
```

Error thrown

`Error: puppeteer@chrome-72 isn't supported by any available resolver`

**Additional context**

This line needs to be changed to a regex that is more permissive. https://github.com/yarnpkg/berry/blob/4dd93bfe79a51d65ee68ae629dcfb2a36b26013a/packages/plugin-npm/sources/NpmTagResolver.ts#L9

npm documentation: https://docs.npmjs.com/cli/dist-tag#caveats

**Comment by arcanis** [comment]
Sounds reasonable 👍
