### ISSUE TITLE
[Bug] pnpMode: loose fails to resolve a package from a workspace

### ISSUE THREAD

**Issue by sebastian-nowak** [yarnpkg/berry#1076]
**Bug description:**

I have a monorepo with packages A and B:
- package A depends on `eslint-plugin-react`
- package B depends on package A

Yarn is configured to set up pnp in the 'loose' mode.

Running `yarn node` inside package B followed by `require('eslint-plugin-react')` triggers an error.

```
Uncaught:
Error: Qualified path resolution failed - none of the candidates can be found on the disk.

Source path: /private/tmp/yarn-loose-mode-bug
Rejected candidate: /private/tmp/yarn-loose-mode-bug
Rejected candidate: /private/tmp/yarn-loose-mode-bug.js
Rejected candidate: /private/tmp/yarn-loose-mode-bug.json
Rejected candidate: /private/tmp/yarn-loose-mode-bug.node
Rejected candidate: /private/tmp/yarn-loose-mode-bug/index.js
Rejected candidate: /private/tmp/yarn-loose-mode-bug/index.json
Rejected candidate: /private/tmp/yarn-loose-mode-bug/index.node`
```

**Repro steps:**

I created a tiny repo you can just clone and check yourself.

https://github.com/sebastian-nowak/yarn-loose-mode-bug-repro

1. Go to the `library/js/lib1`
2. Run `yarn node`
3. Try to run `require('eslint-plugin-react')`

**Environment:**

 - OS: macOS
 - Node version: v13.11.0
 - Yarn version: 2.0.0-rc.30

**Additional context:**

I raised the issue on Discord earlier today. @arcanis pointed out that the corresponding entry inside `fallbackPool` looks wrong:

```
[
        "eslint-plugin-react",
        [
          "yarn-loose-mode-bug",
          "workspace:."
        ]
      ],
```

**Comment by arcanis** [comment]
Thanks for the issue! Seems like the problem is that the virtual path is lost in `entry.target`, so Yarn mistakenly thinks that the locator is different from what it really is. Will fix that 👍
