### ISSUE TITLE
[Bug] website advertises yarn 2 as a usable product when it is actually in heavy development on github

### ISSUE THREAD

**Issue by fredmenez** [yarnpkg/berry#1080]
I want to start using yarn, so i visit https://yarnpkg.com. By the look of https://yarnpkg.com/getting-started/install it seems that using latest yarn (v2) is advised. I read on the topic, try to migrate an existing project, no luck. I read more on yarn 2, I setup a hello world that imports lodash (like the one presented in webpack getting started). No luck : Module not found: Error: Can't resolve 'lodash'.
I setup this same minimalist project to use yarn 1 and it works : webpack manages to generate the bundle.

So what is the point of directing users to use yarn 2 when it's under active development and not working for basic use cases ? 

Recommended fix : The website should direct users to use v1 and have a small banner at the top "If you like living dangerously check out yarn 2" with a link to http://berry.yarnpkg.com.

Thanks

**Comment by arcanis** [comment]
Addressed by https://github.com/yarnpkg/berry/issues/766#issuecomment-580658470
