### ISSUE TITLE
[Bug] publish: bad error message

### ISSUE THREAD

**Issue by bertho-zero** [yarnpkg/berry#1088]
`yarn npm publish` give me a `No authentication configured for request` or `No authentication configured for request` error instead of `You cannot publish over the previously published versions: 1.1.2` (given by npm)

With latest node and berry.

**Comment by arcanis** [comment]
You haven't configured your tokens. Check the [documentation](https://yarnpkg.com/configuration/yarnrc#npmAuthToken).
