### ISSUE TITLE
[Bug] Cant get Berry on a Project

### ISSUE THREAD

**Issue by NotMoni** [yarnpkg/berry#1130]
- [ YES ] I'd be willing to implement a fix

**Cant get Berry**

**To Reproduce**

![Screen Shot 2020-03-29 at 10 49 32 AM](https://user-images.githubusercontent.com/40552237/77852207-50f80800-71ab-11ea-9e5e-2a0bd94df572.png)
![Screen Shot 2020-03-29 at 10 49 23 AM](https://user-images.githubusercontent.com/40552237/77852208-52293500-71ab-11ea-828b-5bd5e601a0d6.png)

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: [MAC]
 - Node version [13.x]
 - Yarn version [NaN]

**Additional context**

**Comment by paul-soporan** [comment]
#1114 removed the ability to use ranges with `yarn set version`. You can still use the latest version by doing `yarn set version latest`. I guess we should update the documentation so there's no confusion.

**Comment by NotMoni** [comment]
Yea. I see. I will make a PR with the docs updated.

**Comment by NotMoni** [comment]
@paul-soporan take a look at the PR

**Comment by NotMoni** [comment]
Should we include both commands just in case one doesn't work?

**Comment by paul-soporan** [comment]
There's no need to, `yarn set version latest` also worked before #1114.

**Comment by NotMoni** [comment]
Ok. I see. 👍
