### ISSUE TITLE
[Bug] Failed when installing yarn dependencies. 

### ISSUE THREAD

**Issue by NotMoni** [yarnpkg/berry#1135]
- [ x] I'd be willing to implement a fix

**Describe the bug**

Failed when doing ``yarn``` on this repo.

**To Reproduce**

```yarn```

**Screenshots**

![Screen Shot 2020-03-30 at 9 01 09 PM](https://user-images.githubusercontent.com/40552237/77976024-d07bf900-72c9-11ea-84c6-5202a66fae5a.png)

**Environment if relevant (please complete the following information):**

 - OS: [macOS Catalina]
 - Node version [v13.0.1]
 - Yarn version [2.0.0-rc.31]

**Additional context**
NaN

**Comment by arcanis** [comment]
The logs show that `sharp` failed to build, probably for machine-specific reasons.
