### ISSUE TITLE
[FIX] Plugin Tutorial need to be reworked

### ISSUE THREAD

**Issue by NotMoni** [yarnpkg/berry#1137]
I am new to yarn and I wanted to make my own plugin https://github.com/yarnpkg/berry/issues/1136

I was following the Plugin Tutorial and I couldn't follow the steps.
 Like this line ```Open in a text editor a new file called plugin-hello-world.js, and type the following code:``` is very vague.
Do i make a new folder and create it or in the berry repo clone on my machine?

**We need more In-depth Documentation that is easy to understand for beginners.**

**Comment by arcanis** [comment]
I'll close this for now since it's not directly actionable.
