### ISSUE TITLE
[Bug] YN0018 in github actions when using TypeScript

### ISSUE THREAD

**Issue by eps1lon** [yarnpkg/berry#1142]
**Describe the bug**

yarn install fails with on GitHub actions but not locally with YN0018

- yarn cache clean --all did not help
- updating yarn to latest did not help
- updating yarn to sources did not help

Also tried:

```bash
/D/p/m/typescript-to-proptypes (master|✔) $ yarn -v
2.0.0-rc.31.git.20200327.c2902096
~/D/p/m/typescript-to-proptypes (master|✔) $ yarn cache clean --all
➤ YN0000: Done in 0.07s
~/D/p/m/typescript-to-proptypes (master|✔) $ set -x YARN_CHECKSUM_BEHAVIOR update
~/D/p/m/typescript-to-proptypes (master|✔) $ yarn
```

which did not change anything. The install did take quite a while though. It seemed to be frozen after it downloaded everything.

**To Reproduce**

1. Clone https://github.com/merceyz/typescript-to-proptypes
2. yarn install
3. works fine
4. same commit fails in github actions: https://github.com/merceyz/typescript-to-proptypes/runs/547813870

**Screenshots**

https://github.com/merceyz/typescript-to-proptypes/runs/550247915#step:5:3273

**Environment if relevant (please complete the following information):**

- GitHub runner version 2.165.2 using ubuntu-latest

**Additional context**

Seems related to typescript 3.5.2

**Comment by NotMoni** [comment]
You have to install yarn berry on the CI Cd

**Comment by NotMoni** [comment]
See if that helps you

**Comment by eps1lon** [comment]
> You have to install yarn berry on the CI Cd

Why would I need to do this? Yarn v1 is already installed in the github runner and berry is checked in to version control.

**Comment by paul-soporan** [comment]
There's no need to install Berry on GitHub actions if it's checked in to version control. Also, the logs clearly show that Berry is the version that's used.

**Comment by vhiairrassary** [comment]
I have the exact same issue (works locally but not in Github Actions). During the installation we can see checksum mismatches such as https://github.com/merceyz/typescript-to-proptypes/runs/547813870#step:5:1204 (see following screenshot) but not sure if it is linked.

I use:
- Node: v12.16.1
- Yarn: 2.0.0-rc.31

<img width="1555" alt="Screenshot 2020-04-01 at 12 58 29" src="https://user-images.githubusercontent.com/6972399/78129923-a422c280-7418-11ea-8043-3c772a57cc52.png">

**Comment by arcanis** [comment]
On the bright side, it seems I can reproduce those errors locally:

![image](https://user-images.githubusercontent.com/1037931/78138466-3c27a880-7427-11ea-9658-f940546b1cca.png)

@eps1lon @merceyz Can you send me the archives you have in your cache that mismatch the ones in my screenshot? I'll diff them and see what might cause the difference.

**Comment by merceyz** [comment]
@arcanis Sent on discord

**Comment by arcanis** [comment]
My best guess is that this is due to this change, committed a few weeks ago:
https://github.com/yarnpkg/berry/blob/master/packages/plugin-patch/sources/patchUtils.ts#L143

It slightly changed the patch mechanism with regard to line endings to make it more consistent, but unfortunately it was already too late and I should have bumped the cache version since the old one wasn't compatible with the new one anymore.

To workaround this, try the following:
- `yarn cache clean --all`

At this point, running `yarn install` should start to fail. Then run this:
- `YARN_CHECKSUM_BEHAVIOR=update yarn`

It'll update the lockfile with the new cache checksums.

**Comment by eps1lon** [comment]
@arcanis I tried this two times with no luck

**Comment by missing1984** [comment]
run into the same issue. the workaround works. delete and regenerate yarn.lock also works for me @eps1lon

**Comment by arcanis** [comment]
Good news! I've isolated the problem to an unstable mtime generated in the zip archives when using the patch protocol (hence why it failed for fsevents, resolve, and typescript only). The fix is #1155, it'll land in master shortly and I'll make a release not long after.

**Comment by missing1984** [comment]
awesome!

**Comment by AlexandreBonaventure** [comment]
@arcanis any workaround till this is released ?

**Comment by eps1lon** [comment]
Fix confirmed: https://github.com/merceyz/typescript-to-proptypes/commit/d51439966c0c5607bde5c3f8eb99f94e68bd99aa

Thanks @arcanis :+1:

**Comment by niklaskorz** [comment]
Still broken for me unfortunately :(

Repository: https://gitlab.com/niklaskorz/nkchat
Failing pipeline: https://gitlab.com/niklaskorz/nkchat/-/jobs/526714686

**Comment by micaelmbagira** [comment]
Same here

**Comment by niklaskorz** [comment]
It's working now after forcing git to treat `*.zip` as binary files in my `.gitattributes`:

```
*.zip binary
```

Before that, git's `autocrlf` would convert all occurences of CRLF line endings in the zip files to LF, eventhough they probably weren't meant as line endings in a binary file.

**Comment by joshhansen** [comment]
I get this with Yarn 2 on Github CI but only with a git repo dependency:

https://github.com/LearnSomethingTeam/mathjs.git#commit=3c3048bedb39db7352bec75846ed6e8a04b9f862

"The remote archive doesn't match the expected checksum"

I do use Typescript

When I set YARN_CHECKSUM_BEHAVIOR=update the CI build succeeds, but I'd really rather not use that.

**Comment by joshhansen** [comment]
Sorry to spam, but I learned that this is also occurring for us on macOS. The same workaround (YARN_CHECKSUM_BEHAVIOR=update) applies.

**Comment by nick-at-work** [comment]
> I get this with Yarn 2 on Github CI but only with a git repo dependency:
> 
> https://github.com/LearnSomethingTeam/mathjs.git#commit=3c3048bedb39db7352bec75846ed6e8a04b9f862
> 
> "The remote archive doesn't match the expected checksum"
> 
> I do use Typescript
> 
> When I set YARN_CHECKSUM_BEHAVIOR=update the CI build succeeds, but I'd really rather not use that.

We had one dependency pulled from GitHub just like that. It used npm. It had the same error above, only during CI builds. It also had an earlier error though:

```
Using npm for bootstrap. Reason: found npm's "package-lock.json" lockfile
  ➤ YN0000: │ /tmp/xfs-c6375050 STDOUT 
  ➤ YN0000: │ /tmp/xfs-c6375050 STDERR npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

It looks like the workflow was using an older version of Node/npm. I couldn't update that, but luckily for us this was an internal dependency, so I switched the dependent package to yarn (v1.22) and now the the CI build works.

**Comment by pierre-lehnen-rc** [comment]
I'm also having this with dependencies pulled from github. On my local computer the checksums don't match the CI's and everyone else's local.

I compared the package files between my PC and a coworker's and noticed that for them, yarn adds a "packageManager" attribute to the dependencies' package.json file, but for me it doesn't. That's why the checksum on my PC doesn't match anyone else's.

**Comment by pierre-lehnen-rc** [comment]
The `packageManager` attribute I mentioned was only the case in one specific package, others had just whitespace differences.

It was casued by an invalid `GITHUB_TOKEN` envvar that I for some reason had in my `.bashrc`. It was causing github downloads to fail and yarn to fallback to downloading stuff via git, which worked but resulted in a different checksum.

**Comment by davwheat** [comment]
I'm also having a similar issue, most likely related to my use of `resolutions`? I develop on Windows, but CI runs on Linux, so I _assume_ the checksum fails because one uses CRLF and the other uses LF?

**Comment by carlgieringer** [comment]
I am using Yarn berry in my monorepo (Howdju/howdju) where I was experiencing this problem. 

My monorepo depends on a project I forked (Howdju/react-native-share-menu). I depend on it like:

```
yarn add 'react-native-share-menu@https://github.com/Howdju/react-native-share-menu.git#commit=6e90a6ea626cb709393998864cec558e4db6f12e'
```

I noticed this in the output from the Github action:

```
...
| ➤ YN0000: │ /tmp/xfs-610072ed STDOUT Packing react-native-share-menu@https://github.com/Howdju/react-native-share-menu.git#commit=6e90a6ea626cb709393998864cec558e4db6f12e from sources
| ➤ YN0000: │ /tmp/xfs-610072ed STDOUT Using Yarn Classic for bootstrap. Reason: "__metadata" key not found in yarn.lock, must be a Yarn classic lockfile
...

| ➤ YN0018: │ react-native-share-menu@https://github.com/Howdju/react-native-share-menu.git#commit=6e90a6ea626cb709393998864cec558e4db6f12e: The remote archive doesn't match the expected checksum
```

Seeing `Using Yarn Classic for bootstrap` and Inspired by the [comment above](https://github.com/yarnpkg/berry/issues/1142#issuecomment-1017624835), I upgrade Yarn in the forked project (and update the commit hash of my monorepo dependency), and now my Github action works without prefixing the `yarn install` command with the env var to ignore checksums (`YARN_CHECKSUM_BEHAVIOR=ignore yarn install` => `yarn install`).

**Comment by trusktr** [comment]
I just started using Yarn for the first time in a project (Berry, not Classic) and I'm now having this issue in GitHub Actions, but not locally.

Here's the job that failed:

https://github.com/lume/lume/actions/runs/6538252764/job/17753779120

The relevant output there:

```
➤ YN0000: ┌ Fetch step
Fetch step
➤ YN0018: docsify-cli@https://github.com/trusktr/docsify-cli.git#commit=6f78abeee273c7641e964fb5f9397b6b72e6753b: The remote archive doesn't match the expected checksum
➤ YN0058: three@https://github.com/trusktr/three.js.git#commit=d2fbde04e079890747e318adb2b3b88f8c556d38: Packing the package failed (exit code 1, logs can be found here: C:\Users\RUNNER~1\AppData\Local\Temp\xfs-8ba5194c\pack.log)
➤ YN0000: └ Completed in 9m 1s
➤ YN0000: Failed with errors in 9m 2s
```

The package `docsify-cli` is being installed from git, from `github.com/trusktr/docsify-cli`. Does this have anything to do with it perhaps?

I wonder if it is CRLFs...

**Comment by trusktr** [comment]
I tried putting `.gitattributes` with `eol=lf` in the `trusktr/docsify-cli` repo (its the `add-cors` branch), and I also added `git config core.eol lf && git config core.autocrlf input` to the beginning of my GitHub Actions before it runs the yarn install, but no luck.

No idea why the checksum fails, and what to fix.

Is this a known issue with packages installed from git?

**Comment by AlijaHodzicRe** [comment]
> I get this with Yarn 2 on Github CI but only with a git repo dependency:
> 
> https://github.com/LearnSomethingTeam/mathjs.git#commit=3c3048bedb39db7352bec75846ed6e8a04b9f862
> 
> "The remote archive doesn't match the expected checksum"
> 
> I do use Typescript
> 
> When I set YARN_CHECKSUM_BEHAVIOR=update the CI build succeeds, but I'd really rather not use that.

@joshhansen could you please explain why you didn't want to set this flag to update? We faced similar issue for the first time in our application and I found a different way to fix it: https://www.reddit.com/r/learnjavascript/comments/qsr87e/yarn_checksum_failures/

It does fix it, but I don't like leaving this flag in .yarnrc.yml file at all. Your comment goes in favor of my opinion but I would like to know why is that. Thank you.

**Comment by Philzen** [comment]
We're experiencing exactly this problem on a non-npm (github repo dependency) with Yarn 4.3 via corepack.

Works fine locally on linux, but fails on Gitlab CI runner. Problem seems to be that the referenced repo has a v1 `yarn.lock`, which makes yarn then start a subprocess to build it with yarn 1.x:

```shell
Fetch step
01:17
➤ YN0000: │ /tmp/xfs-4053915f STDOUT Packing @uselessdev/datepicker@https://github.com/Philzen/datepicker.git#commit=097e011ed9df0febb2f219ea8c18f8b5d303c143 from sources
➤ YN0000: │ /tmp/xfs-4053915f STDOUT Using Yarn Classic for bootstrap. Reason: "__metadata" key not found in yarn.lock, must be a Yarn classic lockfile
➤ YN0000: │ /tmp/xfs-4053915f STDOUT 
➤ YN0000: │ /tmp/xfs-4053915f STDOUT ➤ YN0000: Downloading https://classic.yarnpkg.com/latest.js
➤ YN0000: │ /tmp/xfs-4053915f STDOUT ➤ YN0000: Saving the new release in .yarn/releases/yarn-classic.cjs
➤ YN0000: │ /tmp/xfs-4053915f STDOUT ➤ YN0000: Done in 1s 126ms
➤ YN0000: │ /tmp/xfs-4053915f STDOUT 
➤ YN0000: │ /tmp/xfs-4053915f STDERR ! Corepack is about to download https://registry.yarnpkg.com/yarn/-/yarn-1.22.22.tgz
➤ YN0000: │ /tmp/xfs-4053915f STDERR ! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc[61](https://gitlab.com/interviewtool/interviewtool/-/jobs/7477322559#L61)80534e98d17432037ff6fd140556e2bb3137e.
➤ YN0000: │ /tmp/xfs-4053915f STDERR ! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager
➤ YN0000: │ /tmp/xfs-4053915f STDERR 
➤ YN0000: │ /tmp/xfs-4053915f STDOUT yarn install v1.22.22
➤ YN0000: │ /tmp/xfs-4053915f STDOUT [1/4] Resolving packages...
➤ YN0000: │ /tmp/xfs-4053915f STDOUT [2/4] Fetching packages...
➤ YN0000: │ /tmp/xfs-4053915f STDOUT [3/4] Linking dependencies...
➤ YN0000: │ /tmp/xfs-4053915f STDERR warning " > @chakra-ui/icons@1.1.7" has unmet peer dependency "@chakra-ui/system@>=1.0.0".
➤ YN0000: │ /tmp/xfs-4053915f STDERR warning "@chakra-ui/icons > @chakra-ui/icon@2.0.5" has unmet peer dependency "@chakra-ui/system@>=1.0.0".
➤ YN0000: │ /tmp/xfs-4053915f STDERR warning " > @chakra-ui/storybook-addon@1.0.3" has unmet peer dependency "@storybook/addons@6.x".
➤ YN0000: │ /tmp/xfs-4053915f STDERR warning "@storybook/addon-essentials > @storybook/addon-docs > babel-loader@8.2.5" has unmet peer dependency "webpack@>=2".
➤ YN0000: │ /tmp/xfs-4053915f STDERR warning " > @storybook/react@6.5.8" has unmet peer dependency "require-from-string@^2.0.2".
➤ YN0000: │ /tmp/xfs-4053915f STDERR warning " > eslint-plugin-prettier@4.0.0" has unmet peer dependency "prettier@>=2.0.0".
➤ YN0000: │ /tmp/xfs-4053915f STDOUT [4/4] Building fresh packages...
➤ YN0000: │ /tmp/xfs-4053915f STDOUT $ yarn build
➤ YN0000: │ /tmp/xfs-4053915f STDOUT yarn run v1.22.22
➤ YN0000: │ /tmp/xfs-4053915f STDOUT $ preconstruct build
➤ YN0000: │ /tmp/xfs-4053915f STDOUT 🎁 info building bundles!
➤ YN0000: │ /tmp/xfs-4053915f STDOUT 🎁 success built bundles!
➤ YN0000: │ /tmp/xfs-4053915f STDOUT Done in 6.04s.
➤ YN0000: │ /tmp/xfs-4053915f STDOUT Done in 46.04s.
➤ YN0000: │ /tmp/xfs-4053915f STDOUT 
➤ YN0000: │ /tmp/xfs-4053915f STDOUT yarn pack v1.22.22
➤ YN0000: │ /tmp/xfs-4053915f STDOUT success Wrote tarball to "/tmp/xfs-4053915f/package.tgz".
➤ YN0000: │ /tmp/xfs-4053915f STDOUT Done in 0.12s.
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT Packing @uselessdev/datepicker@https://github.com/Philzen/datepicker.git#commit=097e011ed9df0febb2f219ea8c18f8b5d303c143 from sources
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT Using Yarn Classic for bootstrap. Reason: "__metadata" key not found in yarn.lock, must be a Yarn classic lockfile
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT 
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT ➤ YN0000: Downloading https://classic.yarnpkg.com/latest.js
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT ➤ YN0000: Saving the new release in .yarn/releases/yarn-classic.cjs
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT ➤ YN0000: Done in 0s 923ms
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT 
➤ YN0000: │ /tmp/xfs-52021b19 STDERR ! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad[64](https://gitlab.com/interviewtool/interviewtool/-/jobs/7477322559#L64)c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e.
➤ YN0000: │ /tmp/xfs-52021b19 STDERR ! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager
➤ YN0000: │ /tmp/xfs-52021b19 STDERR 
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT yarn install v1.22.22
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT [1/4] Resolving packages...
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT [2/4] Fetching packages...
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT [3/4] Linking dependencies...
➤ YN0000: │ /tmp/xfs-52021b19 STDERR warning " > @chakra-ui/icons@1.1.7" has unmet peer dependency "@chakra-ui/system@>=1.0.0".
➤ YN0000: │ /tmp/xfs-52021b19 STDERR warning "@chakra-ui/icons > @chakra-ui/icon@2.0.5" has unmet peer dependency "@chakra-ui/system@>=1.0.0".
➤ YN0000: │ /tmp/xfs-52021b19 STDERR warning " > @chakra-ui/storybook-addon@1.0.3" has unmet peer dependency "@storybook/addons@6.x".
➤ YN0000: │ /tmp/xfs-52021b19 STDERR warning "@storybook/addon-essentials > @storybook/addon-docs > babel-loader@8.2.5" has unmet peer dependency "webpack@>=2".
➤ YN0000: │ /tmp/xfs-52021b19 STDERR warning " > @storybook/react@6.5.8" has unmet peer dependency "require-from-string@^2.0.2".
➤ YN0000: │ /tmp/xfs-52021b19 STDERR warning " > eslint-plugin-prettier@4.0.0" has unmet peer dependency "prettier@>=2.0.0".
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT [4/4] Building fresh packages...
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT $ yarn build
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT yarn run v1.22.22
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT $ preconstruct build
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT 🎁 info building bundles!
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT 🎁 success built bundles!
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT Done in 6.15s.
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT Done in 18.18s.
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT 
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT yarn pack v1.22.22
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT success Wrote tarball to "/tmp/xfs-52021b19/package.tgz".
➤ YN0000: │ /tmp/xfs-52021b19 STDOUT Done in 0.13s.
➤ YN0018: │ @uselessdev/datepicker@https://github.com/Philzen/datepicker.git#commit=097e011ed9df0febb2f219ea8c18f8b5d303c143: The remote archive doesn't match the expected checksum
➤ YN0018: @uselessdev/datepicker@https://github.com/Philzen/datepicker.git#commit=097e011ed9df0febb2f219ea8c18f8b5d303c143: The remote archive doesn't match the expected checksum
➤ YN0000: └ Completed in 1m 17s
➤ YN0000: · Failed with errors in 1m 18s
```

Still i wonder:
- shouldn't (theoretically) the checksum be the same, independent of the yarn version it is build with?
- is there a flag that could be applied to advise `yarn install` to build the repo dependency with it's currently running version instead of falling back to v1? 
   Reason is this is a bugfix branch in a fork of a project that i'm hoping will get merged at some point anyway, and updating that project's `yarn.lock`, respectively the yarn version in its stack would be completely out of scope for that bugfix branch.
