### ISSUE TITLE
[Bug] Upgrade command from documentation does not work

### ISSUE THREAD

**Issue by vhiairrassary** [yarnpkg/berry#1144]
Upgrade command (`yarn set version 2`) from https://yarnpkg.com/getting-started/usage does not seem to work:

```
Usage Error: Support for ranges got removed - please use the exact version you want to install, or 'latest' to get the latest build available

$ yarn set version <version>
```

But `yarn set version latest` works.

**Comment by NotMoni** [comment]
See  #1130

**Comment by NotMoni** [comment]
Also take a look at https://github.com/yarnpkg/berry/pull/1133

**Comment by vhiairrassary** [comment]
@NotMoni Thanks, closing as a duplicate

**Comment by NotMoni** [comment]
@vhiairrassary No problem, just helping close dups.
:D
