### ISSUE TITLE
Importing Less file into component throws package not declared in dependencies error

### ISSUE THREAD

**Issue by Kinbaum** [yarnpkg/berry#1145]
This doesn't really fit a bug template, I am just looking for guidance on this issue I'm facing. I am using a Next.js application and in my webpack config I have the following alias defined:

```js
module.exports = {
    webpack(config) {
        // Setting up alias for absolute imports
        config.resolve.alias['@Components'] = path.join(__dirname, 'components');
        return config;
    }
};
```

This allows me to import components anywhere in my application from that folder like so:

```js
import Button from '@Component/Button`
```

When using Yarn 2, I get the following error message:

```sh
./components/Button/index.js
Module not found: Something that got detected as your top-level application (because it doesn't seem to belong to any package) tried to access a package that is not declared in your dependencies
```

Any suggestion on how to resolve this issue? Prior to switching to Yarn 2, it was working well. Thanks.

**Comment by jonaskuske** [comment]
Yep, webpack aliases (and e.g. `moduleNameMapper` configs for jest) don't work with Yarn 2 afaik – but you can use the `link:` protocol in your `package.json` instead: https://yarnpkg.com/features/protocols#whats-the-difference-between-link-and-portal

**Comment by Kinbaum** [comment]
@jonaskuske So I've added the following to my `package.json` based on what I just read. It doesn't seem to work. Am I adding this correctly?

I've tried:

```js
"dependencies": {
    "@Components": "link:./components",
    // ...more dependencies
}
```

as well as

```js
"dependencies": {
    "@Components/Button": "link:./components/Button",
    // ...more dependencies
}
```

**Comment by jonaskuske** [comment]
Just tried it myself and only got it to work when using the exact module name specified in dependencies, not when "digging deeper" into folders that are inside the linked directory.

So `import '@components'` works with `"@components": "link:./components"` but `import '@components/Button'` doesn't:
![image](https://user-images.githubusercontent.com/30421456/78297155-52b92700-752f-11ea-898e-de1324ff0529.png)

@arcanis are we missing something here? 🤔

**Comment by jonaskuske** [comment]
@Kinbaum Update: it works for me if I choose a "plain" dependency name instead of starting with "@".

```
{
  "dependencies": {
    "components": "link:./components"
  }
}
```

Now `require('components/Button')` works from everywhere. If I change that to `@components` I get the error from the comment above. I guess the "@" breaks it because it is usually meant for scoped packages?

**Comment by arcanis** [comment]
Aliases are actually supported now (since https://github.com/arcanis/pnp-webpack-plugin/pull/17) - it didn't get backported into Webpack 5, but last time I checked Webpack 5 had aliases working anyway due to a slightly different implementation. However some notes:

- Using `@components` as package name is invalid. You should at least include the local name, so make it `@app/components` or something.

- Using `@components/Button` is probably valid, but quite weird. The link protocol is meant to be used with folders, so using it with a file can cause weirdness, especially with the extension resolutions.

**Comment by Kinbaum** [comment]
So it doesn't seem to make a difference in terms of how I name this alias. Here is my file structure:
```
/components
    /core
        /Button
            index.js
```
Here is my package.json now:
```js
// package.json
{
  "dependencies": {
    "my-app": "link:./components/core"
  }
}
```

Then I try to import a component from that alias:
```js
import Button from 'my-app/Button';
```

Still produces the same error.

**Comment by merceyz** [comment]
Just to make sure, did you run yarn after adding it?

**Comment by Kinbaum** [comment]
@arcanis Ok after pulling apart my app I believe I have come across the problem child here. Just as a note, I was able to name my alias anything, with and without the `@` prefix. Adding a link protocol to `package.json` was no longer needed after what I discovered. 

Here's the issue though. In my button component, I am importing a `.less` file at the top like so:

```js
// Button/index.js
import './main.less';
```

<details>
    <summary>next.config.js</summary>

```js
// next.config.js
const withCSS = require('@zeit/next-css');
const withLess = require('@zeit/next-less');
const path = require('path');
const PnpWebpackPlugin = require(`pnp-webpack-plugin`);
const FilterWarningsPlugin = require('webpack-filter-warnings-plugin');
const { version } = require('./package.json');

module.exports = withCSS(withLess({
    lessLoaderOptions: {
        javascriptEnabled: true
    },
    publicRuntimeConfig: {
        env: process.env.ENV
    },
    generateBuildId: async () => version,
    webpack(config) {
        // Setting up alias for absolute imports, changed to `my-app` from `@Components`
        config.resolve.alias['my-app'] = path.join(__dirname, 'components', 'core');

        config.resolve.plugins.push(PnpWebpackPlugin);
        config.resolveLoader.plugins.push(PnpWebpackPlugin.moduleLoader(module));
        
        return config;
    }
}));
```
</details>

When I comment out the `.less` import, then everything resolves (obviously left with un-styled component). Is there something I need to add to my next config to handle the .less import for Yarn 2? The config I provided above was enough for Yarn 1 / npm

**Comment by Kinbaum** [comment]
@arcanis, Do you have any suggestions on how to handle the above described?

**Comment by Kinbaum** [comment]
Update, so I forked the `next-css` and `next-less` repos and updated their loaders to use `require.resolve`. That seems to have resolved the issue.
