### ISSUE TITLE
[Bug] Yarn scripts work with $PWD but not $(pwd)

### ISSUE THREAD

**Issue by bertho-zero** [yarnpkg/berry#1148]
I added 2 simple scripts that do:

```json
"foo": "echo $(pwd)"
"bar": "echo $PWD"
```

The first does not work as with Yarn 1 or directly from the terminal:

```
foo: /home/bertho/oa/node_modules/@openagenda/agenda-docx
bar: /home/bertho/oa/packages/agenda-docx
```

**Comment by arcanis** [comment]
Please include a reproduction, I don't know what I'm looking for (in particular Yarn 2 doesn't have n_m folders by default, so the `node_modules/@openagenda` you have is highly suspicious).

Closing for now, but feel free to reopen once the reproduction is provided.

**Comment by bertho-zero** [comment]
I have `nodeLinker: "node-modules"`. I can't take the time to make a repro at the moment.
