### ISSUE TITLE
[Feature]use proxy when we use `yarn set version berry`

### ISSUE THREAD

**Issue by hanhan9449** [yarnpkg/berry#1160]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

In Chinese, `yarn set version berry` is too snow.
could we add a Command line parameters to enable use proxy once?

**Describe the solution you'd like**

use command line parameters to get a temp proxy.

**Describe alternatives you've considered**

use global proxy of system

**Comment by DaneTheory** [comment]
Could you elaborate a bit further please? `.yarnrc.yml` files are currently configured to offer multiple solutions for enabling proxy-based configurations. The only restriction as of now is all proxy configs only support `http` based protocols. The docs do mention that support for `https` is actively in the works.

**Comment by iron9light** [comment]
I'm following https://yarnpkg.com/getting-started/install to install yarn 2

After `npm install -g yarn`,
I ran `yarn policies set-version berry --proxy=http://localhost:1081` in the project folder with no problem.

Then I edited the `./.yarnrc.yml` file as below:
```yaml
yarnPath: ".yarn/releases/yarn-berry.js"

httpProxy: "http://localhost:1081"
```
and ran `yarn set version berry`.
It still got network issue.

The proxy is http proxy.

**Comment by iron9light** [comment]
I tried `httpsProxy: "http://localhost:1081"` in `.yarnrc.yml` this time.
It works.
Wired.
Not sure if it's a bug.

**Comment by merceyz** [comment]
> could we add a Command line parameters to enable use proxy once?

@hanhan9449 For one time use you can do `YARN_HTTPS_PROXY=my-proxy yarn set version berry`

> I tried httpsProxy: "http://localhost:1081" in .yarnrc.yml this time.
> It works.
> Wired.
> Not sure if it's a bug.

`httpProxy` is for http traffic, `httpsProxy` is for https traffic, so this is not a bug
