### ISSUE TITLE
[Feature] portal links should always be in unix path format and work cross platform

### ISSUE THREAD

**Issue by molst** [yarnpkg/berry#1168]
Currently, on Windows, I have to use backslashes like this:

`"portal:..\\my_other_lib"`

This makes my project work only on Windows.

It would be better to use unix paths only and have yarn converting them to Windows style when needed.

**Comment by arcanis** [comment]
That should already be the case. Can you share error logs if not?

**Comment by molst** [comment]
You're correct. I got it working now. Sorry for the false alarm.
