### ISSUE TITLE
[Bug] Wrong per-project installation path on Windows

### ISSUE THREAD

**Issue by jlkiri** [yarnpkg/berry#1178]
- [ ] I'd be willing to implement a fix

**Describe the bug**

```
yarn policies set-version berry
yarn set version berry
```

Either command installs per-project `yarn` in a parent directory on Windows instead of a directory where the command was invoked.

**To Reproduce**

```
yarn policies set-version berry
yarn set version berry
```

Use one of these commands on Windows and see where yarn is downloaded.

IMPORTANT: We strongly prefer reproductions that use Sherlock. Please check our documentation for more information: https://yarnpkg.com/advanced/sherlock

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: Windows
 - Node version 12.15.0
 - Yarn version 1.22.4

**Additional context**

**Comment by larixer** [comment]
@jlkiri Please check whether you have `yarn.lock` in the parent dir, it should not be there.

**Comment by jlkiri** [comment]
Yep, that was the problem. Thanks.
