### ISSUE TITLE
[Bug] vscode tsserver crashed when using typescript in a monorepo

### ISSUE THREAD

**Issue by missing1984** [yarnpkg/berry#1189]
- [] I'd be willing to implement a fix

**Describe the bug**

vscode tsserver crashed when having tsconfig.json and typescript installed in a monorepo package (not project root)

error trace.
```
    Cannot destructure property 'name' of 'object null' as it is null.

    TypeError: Cannot destructure property 'name' of 'object null' as it is null.
        at getPackageInformation (/Users/mluo/workspace/gitlab/monorepo/projects/example/.pnp.js:30630:5)
        at Object.getPackageInformation (/Users/mluo/workspace/gitlab/monorepo/projects/example/.pnp.js:30973:20)
        at getPnpTypeRoots (/Users/mluo/workspace/gitlab/monorepo/projects/example/.yarn/cache/typescript-patch-50eb28f081-2.zip/node_modules/typescript/lib/tsserver.js:28763:42)
```

**To Reproduce**

I've created a minimal project that can reproduce this issue.

[tsserver_crash.zip](https://github.com/yarnpkg/berry/files/4465716/tsserver_crash.zip)

switch to use workspace tsc will soon found it crashed.

**Environment if relevant (please complete the following information):**

 - OS: [e.g. OSX, Linux, Windows, ...]
OSX
 - Node version [e.g. 8.15.0, 10.15.1, ...]
```
node -v
v10.16.2
```
 - Yarn version [e.g. 2.0.0-rc1, ...]
```
yarn -v
2.0.0-rc.31
```
**Additional context**

Looks like tsc assume tsconfig.json and typescript installed at repo root?

**Comment by missing1984** [comment]
Also, In my case yarn root is not the repo root.

For example:
```
.vscode
web/.yarnrc.yml
web/.pnp.js
```

**Comment by missing1984** [comment]
@arcanis looks like you maintain a typescript patch for this. Can you share some light? I would be happy to help out whatever I can.

**Comment by ojkelly** [comment]
Theres a linked issue in the tsc repo https://github.com/microsoft/TypeScript/issues/37477

I'm also getting this, but my yarn is the root of the repo.

**Comment by Seally** [comment]
I believe the relevant patches are linked to this PR: https://github.com/microsoft/TypeScript/pull/35206

**Comment by arcanis** [comment]
The problem is that the TS type roots are supposed to be loaded based on the current directory. In the case you describe, since the repo root isn't the Yarn root, the cwd TS is spawned with isn't part of the project, causing the error you see.

For what it's worth, my own solution is to always configure the editor-typescript at the root of the repository, and write small tsconfig.json in each workspace that extend the editor one. That requires to make Yarn the repo root, however.

**Comment by missing1984** [comment]
Verified. One constraint is our sdk plugin require `typescript` `prettier` and `eslint` declared in yarn root package.json

If you have those packages declare in child workspaces it's not gonna work. I am going to update our docs
