### ISSUE TITLE
[Bug] Version plugin throws internal error for files not in a workspacce

### ISSUE THREAD

**Issue by fggrimshaw** [yarnpkg/berry#1194]
- [x] I'd be willing to implement a fix

**Describe the bug**

When running `yarn version check` (with or without the interactive flag), an internal error is thrown if any changed file is detected outside of a workspace

**To Reproduce**

Repro repo: https://github.com/fggrimshaw/versioning-bug-berry

1. Checkout the `my-feature` branch (this is one commit ahead of master, which contains a file outside any workspace)
2. Go into the `worktree` directory and run `yarn version check`

You should see the following error:
```
➤ YN0001: Error: Workspace not found (/home/finn/work/versioning-bug-berry/new-file)
    at T.getWorkspaceByFilePath (/home/finn/work/versioning-bug-berry/worktree/.yarn/releases/yarn-sources.js:42:100346)
    at changedFiles.map.file (/home/finn/work/versioning-bug-berry/worktree/.yarn/plugins/@yarnpkg/plugin-version.js:454:72)
    at Array.map (<anonymous>)
    at Object.openVersionFile (/home/finn/work/versioning-bug-berry/worktree/.yarn/plugins/@yarnpkg/plugin-version.js:454:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)
➤ YN0000: Failed with errors in 0.04s
```

**Screenshots**

N/A

**Environment if relevant (please complete the following information):**

 - OS: Linux
 - Node version: 10.16.3
 - Yarn version: 2.0.0-rc31 (also tested 2.0.0-rc.31.git.20200412.a701edd2)

**Additional context**

Presumably this line needs some extra filtering/error handling for files not contained in a workspace: https://github.com/yarnpkg/berry/blob/master/packages/plugin-version/sources/versionUtils.ts#L210

**Comment by arcanis** [comment]
Oh interesting, we should probably just do a filter using `tryWorkspaceByFilePath` (which doesn't exist at the moment, it needs to be added in the `Project` class), indeed!
