### ISSUE TITLE
[Feature] version plugin: Support non-master bases

### ISSUE THREAD

**Issue by fggrimshaw** [yarnpkg/berry#1195]
- [x] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

My team's workflow involves merges to target branches outside of master, and we would like to make use of the versioning plugin. Unfortunately it has `master` as a [hardcoded base](https://github.com/yarnpkg/berry/blob/master/packages/plugin-version/sources/versionUtils.ts#L23), so comparisons outside of master are not currently possible.

**Describe the solution you'd like**

The version CLI should have an optional argument to the version plugin for setting a base outside of master. Ideally branches, tags, or commit hashes should all be supported bases; my use-case would use tags, but  `git merge-base` supports all 3 so this shouldn't cause any difficulties. 

**Describe the drawbacks of your solution**

It would be best to sanitize the passed branch/tag/hash as this user input is being passed into the spawned process that runs  `git merge-base`. I'm not sure if this sort of sanitization is a concern, and I'm not sure if it has already been encountered/addressed in berry.

Also, this would make it more difficult if there was interest to make the version plugin not rely on git. 

**Describe alternatives you've considered**

The alternative is to basically write a new version plugin with this support, or otherwise script our use-case

**Additional context**

N/A

**Comment by arcanis** [comment]
Sounds good to me! As far as the naming goes, maybe `changesetBaseBranch`? I'm considering renaming the `yarn version check` command to `yarn changeset`.

**Comment by fggrimshaw** [comment]
Thanks for the response.

Could you clarify your vision here: What are you suggesting gets named `changesetBaseBranch`? Also, the base could be a tag or commit hash, so maybe `changesetBaseCommit` or is more accurate?

If it's easier I can submit a PR now and we can figure out these details in review

**Comment by arcanis** [comment]
> Could you clarify your vision here: What are you suggesting gets named changesetBaseBranch?

The new configuration setting (which will be added to [this page](https://yarnpkg.com/configuration/yarnrc)).

> Also, the base could be a tag or commit hash, so maybe changesetBaseCommit or is more accurate?

True, although I'm worried this might obfuscate a bit the meaning for most users (I suspect most will use a branch and won't expect a commit setting to work) - what about "commitish"? Or even better, "ref"? It's a common git concept.

**Comment by fggrimshaw** [comment]
> The new configuration setting (which will be added to this page).

Ah, my vision was something that could be passed through the CLI, not a saved configuration, e.g. `yarn version check --baseRef 'my-base-ref'`. That would be ideal for my team since this "base ref" can be different for a given branch. 

I do see the benefit of it coming from a saved configuration, other users might get good use out of that. I would prefer to have my way implemented but I'm also willing to implement it as a configuration setting, is this acceptable?

> True, although I'm worried this might obfuscate a bit the meaning for most users (I suspect most will use a branch and won't expect a commit setting to work) - what about "commitish"? Or even better, "ref"? It's a common git concept.

Using "ref" makes a lot of sense to me.

**Comment by arcanis** [comment]
> I do see the benefit of it coming from a saved configuration, other users might get good use out of that. I would prefer to have my way implemented but I'm also willing to implement it as a configuration setting, is this acceptable?

You can still set this kind of thing through the command line using the environment variables. It's a bit less elegant than command line flags, but the following would work (and you can easily alias it using your shell):

```
YARN_CHANGESET_BASE_REF=my-base yarn changeset -i
```

**Comment by fggrimshaw** [comment]
Ah, good point, I'm happy to use it myself through environment variables. 

Although, if it's only done through configuration (and by extension environment variables), that makes it less obvious for other users since `yarn version check --help` would not mention this at all; to know that this is possible they would need to look at the configuration doc and make the connection themselves. You can decide if this matters.

Thank you for the discussion, I'll submit a PR later today or tomorrow
