### ISSUE TITLE
[Question] How to resolve a file from the zip cache?

### ISSUE THREAD

**Issue by robations** [yarnpkg/berry#1198]
Not sure if this is the best place for questions — I searched to see if there was a better place for support questions but didn't find anything.

I spent some time today to see what potential issues would be involved in upgrading to use yarn2 and PnP. The problem I'm currently stuck on is a direct reference to a SCSS file within a dependency (`bootstrap-sass`). I found I could write a custom importer for `node-sass` so using `request.resolve()` I resolved the reference to something like:

```
.../.yarn/cache/bootstrap-sass-npm-3.4.1-30da3a8661-2.zip/node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss
```

Unfortunately, this is not a reference to the filesystem, but a file within the zip cache. If this was a JS module I could use `require()` directly to load the data (but it's a SCSS file). I spent about an hour searching on Google and through the issue log but can't find anything illuminating.

Is there a function somewhere that will mount/load from the resolved path, or should I be finding extracting the zip file and loading from this manually?

**Comment by arcanis** [comment]
If running within a Yarn context, you can call `readFile` just fine (we add a zip-capable overlay to the `fs` module).

**Comment by larixer** [comment]
@robations `node-sass` has native C code that tries to read files directly on the fs, it does not run within JS runtime. You can use JS sass implementation, the npm package called just `sass` (also known as Dart sass). `sass` works with pnp out of the box. If you happen to use `webpack`, then you need to configure `sass-loader` accordingly, to point it to `sass`:
https://github.com/webpack-contrib/sass-loader#sassoptions

**Comment by robations** [comment]
@arcanis thanks, I have that working now*. Possible worth adding something to documentation/FAQs?

@larixer thanks, probably would be a better way to go. I'm trying to upgrade what is largely a "legacy" project with minimum effort, but using sass within context of webpack would be a smoother path.

\* at least I'm able to resolve the file from the zip, but now I see that sass has a complicated file resolution algorithm that I need to implement...

**Comment by RiZKiT** [comment]
@larixer "sass works with pnp out of the box." At least It does not for me, after switching to yarn, the sass imports do not work any longer, the related package I want to import from exists in `.yarn/cache` as a zip file. I'm using sass directly in a npm script. Imports in JavaScript files handled by webpack/babel do work.

Maybe I do something wrong?

**Comment by larixer** [comment]
@RiZKiT Please note, that your excerpt from my comment is incorrect. I have not told that sass technology in any form of its implementation works out of the box with npm, I have told that `sass` npm package works (also known as Dart sass) out of the box with pnp:
https://www.npmjs.com/package/sass
