### ISSUE TITLE
[Bug]Not able to install yarn 2

### ISSUE THREAD

**Issue by krave1986** [yarnpkg/berry#1208]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I have an empty directory called project under c: disk.
Followed installation instruction but not able to build yarn2 by command:
`yarn set version from sources`

But reported:
Usage Error: No project found in /C:/project

**To Reproduce**

The _minimal_ information needed to reproduce your issue (ideally a package.json with a single dep). Note that bugs without minimal reproductions might be closed.

IMPORTANT: We strongly prefer reproductions that use Sherlock. Please check our documentation for more information: https://yarnpkg.com/advanced/sherlock

1. install global yarn 1.22.4
2. yarn set version berry
3. yarn set version from sources

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: Windows
 - Node version 12.16.2
 - Yarn version 2.0.0-rc.31

**Additional context**

**Comment by arcanis** [comment]
The error sounds about right.

```
Usage Error: No project found in /C:/project
```

You have no project in `C:\project`. Initialize it first.
