### ISSUE TITLE
[Feature] can we use this using Deno

### ISSUE THREAD

**Issue by mobop** [yarnpkg/berry#1216]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Deno 🎉

**Describe the solution you'd like**

run on Deno 

**Describe the drawbacks of your solution**

don't need to install node when using deno

**Describe alternatives you've considered**
....

**Comment by mobop** [comment]
your template sucks . your suggestions should be commented

**Comment by arcanis** [comment]
> don't need to install node when using deno

That's the weirdest argument ever. No need to install Node, but you need to install Deno ...

> your template sucks . your suggestions should be commented

Way to be taken seriously 🙄

Closing this issue, it's not something I expect we'll be looking at. Feel free to experiment by yourself if you're so inclined.
