### ISSUE TITLE
[Feature] (Re)create Docker Official Image

### ISSUE THREAD

**Issue by nschonni** [yarnpkg/berry#1226]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Paralleling the discussion from the docker-node repo about removing Yarn from the 14 image https://github.com/nodejs/docker-node/issues/1238

**Describe the solution you'd like**

Suggesting the previous image be revived https://hub.docker.com/r/yarnpkg/node-yarn, although maybe a simpler "yarn" name would be easier. The existing infrastructure using by docker-node could be used for you to create images with stronger versioning of the Yarn component.

**Describe the drawbacks of your solution**

You'd need to re-setup the repo and configure the stackbrew scripts used to publish the official images.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by nschonni** [comment]
Aside: But I just got to odd GitHub Actions failure emails for your "Sherlock" jobs https://github.com/yarnpkg/berry/actions/runs/83447298/workflow https://github.com/yarnpkg/berry/runs/603933410?check_suite_focus=true

**Comment by arcanis** [comment]
As I previously mentioned, we won't start any efforts in this direction before a resolution is found in https://github.com/nodejs/node/issues/15244#issuecomment-613512550.

Our team already supports the Node ecosystem through our work on Yarn itself, I see absolutely no benefit for anyone at adding extra maintenance cost for what seems to be political reasons.

**Comment by merceyz** [comment]
Closing as it doesn't seem like the Yarn binary will be removed from the docker image anytime soon, if it is I think we'd rather document using `npm install yarn -g` or using per-project installs and invoking that using node directly instead of maintaining a docker image
