### ISSUE TITLE
[Feature] Clean/delete dist before building

### ISSUE THREAD

**Issue by Vivek205** [yarnpkg/berry#1227]
- [x] I'd be willing to implement this feature
- [x] This feature can already be implemented through a plugin - rimraf

**Describe the user story**

Everytime I have to manually clear the `dist` folder before running the build script. Else, the old files sitting already in the dist folder are causing trouble by polluting imports.

**Describe the solution you'd like**

I want a script to clear the existing dist file before building the package. So it could be automated. And I won't run into the issue of old files again. It will be somewhat similar to `yarn autoclean` but autoclean remove files only inside the node_modules.

**Describe the drawbacks of your solution**

I can't think of any at this moment

**Describe alternatives you've considered**

I considered using rimraf that is the only cross-platform alternative as per my knowledge.

**Comment by merceyz** [comment]
> I considered using rimraf that is the only cross-platform alternative as per my knowledge.

Yarn has built-in support for `rm -rf` in scripts

**Comment by Vivek205** [comment]
> > I considered using rimraf that is the only cross-platform alternative as per my knowledge.
> 
> Yarn has built-in support for `rm -rf` in scripts

Yh. but that works only for the `linux` machines. In `windows` machine it will not work. That's why I'm looking for a cross platform solution

**Comment by arcanis** [comment]
You want `git clean -df`, probably. In any case, I don't think that's something Yarn should do.

**Comment by merceyz** [comment]
> Yh. but that works only for the linux machines. In windows machine it will not work. That's why I'm looking for a cross platform solution

That's just not correct, Yarn has a built-in shell that supports `rm -rf` on Windows, Linux, and MacOS.(Which is why I said `Yarn has built-in support for rm -rf in scripts`)

**Comment by paul-soporan** [comment]
Closing this as it's outside the scope of Yarn. Also, we don't know which scripts create build folders when run and we can't magically extract the folder path from them.
