### ISSUE TITLE
[Feature] Separate auth credentials into a separate file

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [yarnpkg/berry#1240]
In order to authenticate with a private repo, the user has to configure `.yarnrc.yml` with an `npmRegistryServer` entry and an `npmAuthToken` entry. Putting `npmAuthToken` in `.yarnrc.yml` doesn't seem ideal, because `.yarnrc.yml` is meant to be added to source control, and we don't want user secrets ending up in source control.

A good solution to this might be to add support for a second file (e.g. `.yarnrc.user.yrml`) that stores user-specific settings and should always be ignored via a `.gitignore` file. In this case, the setup on a user's computer should be something like this:

In `.yarnrc.user.yml`:
```
npmRegistryServer: https://....
```

In `.yarnrc.user.yml`:
```
npmAuthToken: "ffffffff-ffff-ffff-ffff-ffffffffffff"
```

Does this sounds like a reasonable approach? This would also open the door for specifying the user's email address, supporting a new version of the old `npm yarn login` command, etc.

Thanks :)

**Comment by deini** [comment]
You can use a config in your home directory `~/.yarnrc.yml` and set your tokens there. 

This is your global config and will be merged with your project’s config.

**Comment by Bosch-Eli-Black** [comment]
@deini Ah, good to know; thanks!

Is this documented anywhere?

**Comment by deini** [comment]
I don't think we do 🤔, PRs welcome!
