### ISSUE TITLE
[Bug] vscode editor sdk apply fs patch multiple times.

### ISSUE THREAD

**Issue by missing1984** [yarnpkg/berry#1243]
- [] I'd be willing to implement a fix

**Describe the bug**

When turning on vscode eslint/prettier/typescript vscode SDK by `yarn pnpify --sdk`. VSCode became slower and slower.

per the discussion with @larixer , it's possible that we apply fs patch multiple times as vscode extension can require the target library multiple times given different sets of files. (eslint clearly does this, https://github.com/microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L734)

@larixer did a great perf testing here

https://discordapp.com/channels/226791405589233664/654372321225605128/702328108044517416

Is there any way we can avoid this double patching?

 - OS: OSX
 - Node version 10.16
 - Yarn version rc-32

**Comment by paul-soporan** [comment]
Fixed by #1309.
