### ISSUE TITLE
[Bug] `yarn set version latest` fails

### ISSUE THREAD

**Issue by Dbuggerx** [yarnpkg/berry#1248]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Unable to update to the latest version.
After executing `yarn set version latest`, I get:

```
$ yarn set version latest
➤ YN0000: Downloading https://github.com/yarnpkg/berry/raw/master/packages/yarnpkg-cli/bin/yarn.js
➤ YN0001: Error: Invalid semver version
```

**To Reproduce**

Execute `yarn set version latest`

**Environment if relevant (please complete the following information):**

 - OS: Windows 10
 - Node version: 12.16.2
 - Yarn version: both `2.0.0-rc.32` and `2.0.0-rc.32.git.20200423.c93181f8`

**Comment by paul-soporan** [comment]
🤔 Interesting. I can reproduce this on Windows, but I can't reproduce it on Linux ([Playground Link](https://yarnpkg.com/playground?code=YXdhaXQgeWFybihgaW5pdGApOwoKYXdhaXQgZXhwZWN0KAogICAgeWFybihgc2V0YCwgYHZlcnNpb25gLCAgYGxhdGVzdGApCikucmVzb2x2ZXMudG9CZVRydXRoeSgpOw%3D%3D) - runs in a Linux Container). I'm going to investigate later.

**Comment by Dbuggerx** [comment]
Thanks @paul-soporan
