### ISSUE TITLE
[Bug] Installation instructions missing a step

### ISSUE THREAD

**Issue by lukeabbott** [yarnpkg/berry#1258]
- [x ] I'd be willing to implement a fix

**Describe the bug**

Following the instructions [here](https://yarnpkg.com/getting-started/install). Once yarn is installed globally you should be able to run `yarn set version berry` or `yarn policies set-version berry` depending on your yarn version.

But yarn classic has no set command or policies command. So both options fail.

There must be some missing step to access yarn 2's set command at this point.

**To Reproduce**

Start with no yarn installed on your machine. Follow the global installation instructions. Then move to the next step. Attempt to run the command appropriate for your version of yarn (mine is showing 1.5.1) so the command I tried first was yarn set version berry.

Receive the following error:
`(node:19288) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

`(Use "node --trace-deprecation ..." to show where the warning was created)`

`error An unexpected error occurred: "Command \"set\" not found.".`

`info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\Luke\\code\\moneyplan\\yarn-error.log".`

`info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Screenshots**

![image](https://user-images.githubusercontent.com/5643368/80288392-bf29df00-8705-11ea-9bf4-ce29a4c376b7.png)

**Environment if relevant (please complete the following information):**

 - OS: Windows 10
 - Node version 14.0.0
 - Yarn version 1.5.1

**Comment by arcanis** [comment]
If you get 1.5, then you didn't start with no Yarn. The latest release is 1.22, meaning that you have a global Yarn somewhere you forgot about. Using `which yarn` to find out where it is, and remove it.

**Comment by lukeabbott** [comment]
I've attempted to install yarn@berry locally using npm but that seems... wrong.
I don't want to install yarn@berry globally because that goes against the installation instructions.

npm install yarn@berry
then
./node_modules/.bin/yarn set version berry

appears to work... but that can't be right...

**Comment by lukeabbott** [comment]
> If you get 1.5, then you didn't start with no Yarn. The latest release is 1.22, meaning that you have a global Yarn somewhere you forgot about. Using `which yarn` to find out where it is, and remove it.

5 is less than 22.. gah. I'll try to figure out how to get rid of it.

**Comment by lukeabbott** [comment]
Thanks for the help @arcanis. Looks like I installed yarn in 2018 using a windows msi. No amount of npm global install would override it. When I saw npm installing 1.22 and the yarn version showing 1.5 my brain said 5 is bigger than 2, they must have a higher version number that actually get installed...
