### ISSUE TITLE
[question] postinstall

### ISSUE THREAD

**Issue by Thomazella** [yarnpkg/berry#1262]
Hey everyone. I'm excited to be using berry. :D

One of the main differences I'm noticing is that `postinstall` seems to be called much less often. I took a look here `https://yarnpkg.com/advanced/lifecycle-scripts` and it seems to be supported. I can run my own postinstall doing `yarn run postinstall` but cant get yarn to run it as part of the install process (`yarn`) Maybe because it caches things and detects no changes and then it doesn't postinstall again? Just to be clear, I believe it is working, but I'm expecting to call `yarn` `yarn` and see postinstall running, which isn't happening. :)

**Comment by arcanis** [comment]
> Maybe because it caches things and detects no changes and then it doesn't postinstall again?

That's the case, yes. To execute some code each time you run Yarn, you need to setup a custom plugin on the `afterAllInstalls` hook. The hooks aren't very well documented yet, unfortunately 🤔

**Comment by Thomazella** [comment]
@arcanis thanks for the explanation!

**Comment by GfxKai** [comment]
Just in case anyone lands here with the same issue, I created a plugin to solve this issue: https://github.com/GravitywellUK/yarn-plugin-postinstall

**Comment by merceyz** [comment]
> Under the zero install model, cloning a repo with cached dependencies for the first time and running yarn does not trigger the standard postinstall hook.
> https://github.com/GravitywellUK/yarn-plugin-postinstall/tree/d548fc3982e0988a137b92c7bdf90a53ee3e8dec

As long as you're not committing the build state (which you shouldn't), it will run the install in that case

**Comment by GfxKai** [comment]
Readme updated, thanks!
