### ISSUE TITLE
Broken PnP link in README

### ISSUE THREAD

**Issue by yhoiseth** [yarnpkg/berry#127]
In the [Generic packages](https://github.com/yarnpkg/berry#generic-packages) section, the link [Plug'n'Play-compatible](https://github.com/yarnpkg/berry/blob/master) returns _404 Page not found_.

It's not obvious to me what the link target should be. Maybe https://yarnpkg.com/en/docs/pnp?

**Comment by arcanis** [comment]
Fixed! The right link was https://yarnpkg.github.io/berry/features/pnp 👍
