### ISSUE TITLE
yarn set version not working for 2.0.0-rc.32, latest, berry etc.

### ISSUE THREAD

**Issue by suedama1756** [yarnpkg/berry#1270]
I installed yarn 1.22.4 and followed the instructions using yarn policies to install berry. This was successful and yarn --version reported 2.0.0-rc.32. If I then use 

```bash
yarn set version berry
```

Error: Invalid version descriptor

```bash
yarn set version 2.0.0-rc.32
```

Error: Invalid semver version

```bash
yarn set version ^2.0.0
```

Error: Support for ranges got removed - please use an exact version you want to install, or 'latest'

```bash
yarn set version latest
```

Error: Invalid semver version

How is this supposed to work?

**Comment by aaaldhaheri91** [comment]
I am having the same issue as well. I was just about to submit an issue.

**Comment by aaaldhaheri91** [comment]
Actually this issue has been fixed here https://github.com/yarnpkg/berry/issues/1248 . This was only happening for windows, my docker image it was working fine. 
To upgrade I did the following:
`yarn set version from sources`
`yarn set version latest`
and commited the files

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/1249
