### ISSUE TITLE
[Bug] cant access scoped package `@emotion/styled-base`

### ISSUE THREAD

**Issue by njj** [yarnpkg/berry#1275]
**Describe the bug**

`Your application tried to access @emotion/styled-base, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.`

My jest tests cannot access this scoped package, and I'm not sure how I would update the `moduleNameMapper` to reference where it is since `node_modules` doesn't exist.

**To Reproduce**

Reference a scoped package in tests.

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Yarn version 2.0.0-rc.32

**Comment by arcanis** [comment]
Repro? As it is, it simply looks like you forgot to list `@emotion/styled-base` in your deps.

**Comment by njj** [comment]
@arcanis Doh.  You're right, I could have sworn it was there but it was about 3-4 other `@emotion` packages...
