### ISSUE TITLE
[Feature] Timeout on HTTP requests

### ISSUE THREAD

**Issue by missing1984** [yarnpkg/berry#1284]
- [*] I'd be willing to implement a fix

**Describe the bug**

yarn does not timeout on HTTP request.

**To Reproduce**

set `npmRegistryServer: 'https://foo.bar.com'` in yarmrc.yml and run `yarn`

it will hangs forever as got does not have default timeout https://github.com/sindresorhus/got#timeout

**Environment if relevant (please complete the following information):**

 - OS:OSX
 - Node version 12
 - Yarn version rc32

I will file a pull request to add  timeout and retry configuration.

**Comment by arcanis** [comment]
Would make sense 👍 It should also be [configurable](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/sources/Configuration.ts#L308) and be high enough by default (1mn?).

**Comment by missing1984** [comment]
https://github.com/yarnpkg/berry/issues/720 is somewhat related
