### ISSUE TITLE
[Feature] Programmatic use

### ISSUE THREAD

**Issue by npenin** [yarnpkg/berry#1293]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

I would like to use yarn commands from my project, but they are not accessible and typescript compiler complains about missing properties when trying to run a command.

**Describe the solution you'd like**

From plugins, I believe commands should be exported as at least an interface to be able to strongly type commands, or even better, to export command classes directly.

**Describe the drawbacks of your solution**

Forces the yarnpkg team to update all plugins to export all commands (in addition to plugin export)

**Describe alternatives you've considered**

I do not see how else yarn allows for programmatic usage.

**Additional context**

Here is a small sample on how it just fails:
```
import * as fslib from '@yarnpkg/fslib'
import EssentialPlugin from '@yarnpkg/plugin-essentials';
import yarn from '@yarnpkg/cli';
import clipanion from 'clipanion'

            var cli = clipanion.Cli.from(EssentialPlugin.commands)
            var AddCommand = EssentialPlugin.commands.find(c => c.name == 'add');
            var add = new AddCommand();
            add.packages = [packageName];
            await cli.run(add, { ...clipanion.Cli.defaultContext, cwd: fslib.npath.toPortablePath(process.cwd()), quiet: false, plugins: yarn.getPluginConfiguration() });     
```

There, typescript complains about the missing packages property while it is definitely defined on the AddCommand. But since the command is not strongly typed, it will never work

**Comment by arcanis** [comment]
It's a CLI, so you'd pass it CLI arguments. Pseudo-code:

```ts
const cli = clipanion.Cli.from(EssentialPlugin.commands);

await cli.run([`add`, `foo`, `bar`], {
  ...clipanion.Cli.defaultContext,
  cwd: fslib.npath.toPortablePath(process.cwd()),
  plugins: yarn.getPluginConfiguration(),
  quiet: false,
});  
```
