### ISSUE TITLE
[Case Study] provide type definition in pnpapi virtual package

### ISSUE THREAD

**Issue by npenin** [yarnpkg/berry#1301]
**What package is covered by this investigations?**

pnpapi

**Describe the goal of the investigation**

pnpapi does not provide any type definition, so typescript does not provide any intellisense on using this api.

**Investigation report**

**Comment by arcanis** [comment]
The types are provided in `@types/pnpapi`. They are slightly out of date, I have a PR in progress, will close this issue in the meantime: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38800
