### ISSUE TITLE
README.md Its not all green.

### ISSUE THREAD

**Issue by NotMoni** [yarnpkg/berry#1304]
![image](https://user-images.githubusercontent.com/40552237/81212166-78a87000-8fa2-11ea-8f74-daed309814c3.png)
It's not all green, so I'm guessing that a fix is being worked on, if it is, that's great.
I just wanted to alert the team. 🦄

**Comment by arcanis** [comment]
Thanks for the tip - I receive email alerts when one of those gets red though 😉

**Comment by NotMoni** [comment]
Oh, i didn't know that. 🦄
