### ISSUE TITLE
[Bug]I can't install Yarn V2

### ISSUE THREAD

**Issue by joesdu** [yarnpkg/berry#1308]
PS C:\Users\myname\Documents\GitHub\myprojectname> yarn --version
1.22.4
PS C:\Users\myname\Documents\GitHub\myprojectname> yarn set version berry
Resolving berry to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
error An unexpected error occurred: "https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js: getaddrinfo ENOENT raw.githubusercontent.com".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\myname\\Documents\\GitHub\\myprojectname\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/policies for documentation about this command.

**Comment by joesdu** [comment]
when i use VPN
the problem is still the same.

**Comment by arcanis** [comment]
That's a network error, the problem is on your side (or GitHub's one, but unlikely).

**Comment by LvChengbin** [comment]
I encountered the same issue, it happened frequently, but I can open the URL from browser when I got `error An unexpected error occurred` from `yarn set version berry`.

**Comment by rxliuli** [comment]
> I encountered the same issue, it happened frequently, but I can open the URL from browser when I got `error An unexpected error occurred` from `yarn set version berry`.

I also encountered this problem, is there any solution? (The strange thing is that I observed yarn in Proxifier that the transparent proxy is gone, but it still throws an error)

**Comment by xgsong** [comment]
i have the same problem, and ask for help!

**Comment by xgsong** [comment]
when i run the command: yarn set version stable

error An unexpected error occurred: "https://github.com/yarnpkg/berry/raw/master/packages/yarnpkg-cli/bin/yarn.js: connect ECONNREFUSED :::443".

**Comment by joesdu** [comment]
> when i run the command: yarn set version stable
> 
> error An unexpected error occurred: "https://github.com/yarnpkg/berry/raw/master/packages/yarnpkg-cli/bin/yarn.js: connect ECONNREFUSED :::443".

cross firewall
