### ISSUE TITLE
[Question] Plans for Yarn 2 release date

### ISSUE THREAD

**Issue by strelga** [yarnpkg/berry#1316]
I'd like to use Berry features in my project but do not find in docs and github issues any planned release date.
I've read discussion in https://github.com/yarnpkg/berry/issues/766 and could not understand whether Yarn team had plans to release "stable" version of berry before switching default package from v1 to v2.
By "stable" I mean version that would be considered by Yarn team reliable enough to be used as a primary package manager in large project: stable API, releases with minimal breaks and so on.
I see all current releases are marked as `rc`, so they seem "not stable" in some sense.

Could you please clarify your plans?

**Comment by arcanis** [comment]
2.0.0 stable was actually 2.0.0-rc.27. I forgot to bump it outside of prerelease, and now it's a bit late so I'll wait until the 2.1.0 to make the fix. Consider that all CLI prereleases since 2.0.0-rc.27 are actually 2.1.0-rc.something 🙂
