### ISSUE TITLE
[Feature] Global .yarnrc.yml?

### ISSUE THREAD

**Issue by kevin-lindsay-1** [yarnpkg/berry#1319]
Trying to specify that a package should go to a private npm registry, but don't want to include the access token in the repository, because that's per-user.

Normally, I'd try to set up a global configuration file in my `~/` directory or an environment variable, but I'm having trouble finding such an option documented.

Does this feature exist already, or should I be setting an environment variable or something?

**Comment by arcanis** [comment]
Using `~/.yarnrc.yml` is supported (that's actually what `yarn npm login` will use, not the per-project configuration file). Note however that the settings are currently replaced, not merged (ie you can't define different `npmScopes` in both files). We'll likely fix that in the future.

**Comment by kevin-lindsay-1** [comment]
Good to know, thanks!

**Comment by JounQin** [comment]
I think this should be re-opened...
