### ISSUE TITLE
[Feature] install --prod

### ISSUE THREAD

**Issue by marudor** [yarnpkg/berry#1320]
**Describe the user story**

I would like to only install production dependencies for a smaller docker container again.

**Describe the solution you'd like**

Basically exactly like classic yarn. Especially as I still need node_modules.

**Describe alternatives you've considered**

I had a workaround using `npm prune --prod` But I now use workspaces more and npm doesn't understand them => removes packages that are used by some workspaces.

**Comment by arcanis** [comment]
Next version will feature [`yarn workspaces focus --production`](https://yarnpkg.com/cli/workspaces/focus) for this use case.

**Comment by kingdaro** [comment]
> Next version will feature [`yarn workspaces focus --production`](https://yarnpkg.com/cli/workspaces/focus) for this use case.

This doesn't seem like an exact equivalent to `install --prod`. Would one be able to use this to install production-only dependencies for _multiple_ workspaces, including root?
