### ISSUE TITLE
[Feature] Better way to link, only for development?

### ISSUE THREAD

**Issue by kevin-lindsay-1** [yarnpkg/berry#1325]
Wondering if there's a way to link packages during local development that doesn't update the `package.json`, so that I could `.gitignore` it, preferably without affecting the existing lockfile.

I'd prefer not to break CI by accidentally having anyone modify `resolutions`, but there's also the fact that if it the file is ignored by git, it may end up making it hard to know whether or not you're using a linked instance or the published instance.

Maybe this option already exists, but my intuition tells me that a `.yarnlinks.yml` or something would be easy enough to add to `.gitignore`, and a command like `yarn link list` would make it easy to tell what's linked right now, perhaps hiding the workspace links by default.

**Comment by brunomacf** [comment]
@kevin-lindsay-1 Any progress/idea on this? I have the exact same problem here. Want to link just for development, but having resolutions hard set to a local folder in package.json breaks `yarn install` in other environments different than dev env. Maybe it should be a way to “ignore” resolutions or having a way to conditionally set the resolution (if the the folder in `portal:/path/to/local/folder` exists).

**Comment by 4847832013056622** [comment]
npm init @shopify/app@latest

**Comment by mbrowne** [comment]
The only solution I found was this yarn plugin:
https://github.com/Venryx/yarn-vtools

As mentioned here:
https://github.com/yarnpkg/berry/issues/90#issuecomment-894637000

I have updated the plugin to work with yarn 4:
https://github.com/Venryx/yarn-vtools/pull/4
