### ISSUE TITLE
[Bug] Custom registry server dns lookup fails

### ISSUE THREAD

**Issue by mpaneghel** [yarnpkg/berry#1328]
- [ ] I'd be willing to implement a fix

**Describe the bug**

This is a follow-up to #1327, thanks for the help on that one!

I managed to enable the timeout through `yarn set version from sources`.

I can now see the actual error:
```
YN0001: │ RequestError: ENOTFOUND my-registry.com
    at ClientRequest.<anonymous> (/Users/mpaneghel/Projects/test/.yarn/releases/yarn-sources.js:10:287248)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.e.emit (/Users/mpaneghel/Projects/test/.yarn/releases/yarn-sources.js:16:317084)
    at TLSSocket.socketErrorListener (_http_client.js:463:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at d.lookupAsync (/Users/mpaneghel/Projects/test/.yarn/releases/yarn-sources.js:10:398199)
```
The root cause seems to be a bug in `cacheable-lookup`, one of the dependencies of `got`. `yarnpkg-core` uses `got@^11.0.0-beta.1` which, in turn, had `cacheable-lookup@^4.1.1` as one of its dependencies. This version has the problem mentioned above.

Interestingly, if I pull `got@^11.0.0-beta.1` locally, the `cacheable-lookup` dependency is resolved to `4.3.0`, which doesn't seem to show the problem.

Maybe the `got` version could be installed again with the correct version of `cacheable-lookup`, or a package extension could be added for the `got` package, which I saw in .yarnrc already has some extensions declared?

Thanks again for the help 🙂  

**To Reproduce**

- Link to a custom registry server (I suspect the problem only shows up with registries behind a VPN) in .yarnrc.yml, this is how mine looks like:

```
yarnPath: .yarn/releases/yarn-sources.js
npmRegistryServer: https://my-registry.com
```

- Try adding any package or installing existing ones.

**Environment if relevant (please complete the following information):**

 - OS: macOS
 - Node version: 10.16.3
 - Yarn version: 2.0.0-rc.33

**Comment by mpaneghel** [comment]
Might also worth, instead of tinkering with the package dependencies and extensions, to upgrade to `got@11.1.2`, which [seems to address the DNS caching issues](https://github.com/sindresorhus/got/releases/tag/11.1.2). It also uses the correct version of `cacheable-lookup` (`^4.0.3`).

**Comment by arcanis** [comment]
Can you check whether it's fixed with `yarn set version from sources`? We already use got 11 in master.

**Comment by mpaneghel** [comment]
Thanks for looking into this!

It looks like the locked version in master is `got@11.0.0-beta.1`, which has the problematic version of `cacheable-lookup`: https://github.com/yarnpkg/berry/blob/526947260dae29475ff69561c2cdb45024bbed04/yarn.lock#L6075

I think ideally it would need `got@11.1.2` to include the fix for the dns 🙂
