### ISSUE TITLE
[Bug] Yarn 2 breaks GitLab CI

### ISSUE THREAD

**Issue by benwainwright** [yarnpkg/berry#1333]
- [x] I'd be willing to implement a fix (maybe; with pointers of what to do)

**Describe the bug**

Unable to perform yarn install on GitLab CI if there are plugins installed.

**To Reproduce**

- Create a new yarn package
- `yarn set version berry`
- `yarn plugin import workspace-tools # any plugin will do`
- Create .gitlab-ci.yml file that performs `yarn install`
- Push to gitlab

Please see https://gitlab.com/benwainwright/yarn-repro for a minimal repro

The result is the GitLab build failing with the following error log during install:

```
➤ YN0019: │ install-state.gz appears to be unused - removing
➤ YN0019: │ plugins appears to be unused - removing
➤ YN0001: │ Error: EISDIR: illegal operation on a directory, unlink '/builds/benwainwright/yarn-repro/.yarn/plugins'
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 0.01s
```

Note that I *cannot repro this issue locally*. When I googled `YN0001`, your website tells me that 

> This error typically should never happen (it should instead point to a different error message from this page so that it can be properly documented), so it should be considered a bug in Yarn. Feel free to open an issue or, even better, a pull request aiming to fix it.

So here I am!

**Comment by benwainwright** [comment]
Ok, it seems the problem isn't just with plugins. I removed all references to the plugins and I'm now getting this :(

```
 ➤ YN0013: │ 347 packages were already cached, 1214 had to be fetched
 ➤ YN0019: │ build-state.yml appears to be unused - removing
 ➤ YN0019: │ releases appears to be unused - removing
 ➤ YN0001: │ Error: EISDIR: illegal operation on a directory, unlink '/builds/benwainwright/planv7/.yarn/releases'
 ➤ YN0000: └ Completed in 1.2m
 ➤ YN0000: Failed with errors in 1.21m
```

**Comment by larixer** [comment]
@benwainwright The cache folder is set incorrectly, instead of this:
```
  YARN_CACHE_FOLDER: $CI_PROJECT_DIR/.yarn
```
it should rather be this:
```
  YARN_CACHE_FOLDER: $CI_PROJECT_DIR/.yarn/cache
```

**Comment by benwainwright** [comment]
Sounds plausible. But I added:

`cacheFolder: .yarn/cache`

To my `.yarnrc.yml`

And the issue still persists...

**Comment by benwainwright** [comment]
Admittedly this is taken from my local machine, but:

![image](https://user-images.githubusercontent.com/3321885/81501421-3c418080-92d0-11ea-83aa-76783ee32b01.png)

**Comment by benwainwright** [comment]
OH. You meant in the Gitlab-CI file

**Comment by benwainwright** [comment]
Ok, that solved it. Thanks... was a hangover from a yarn 1 config.

**Comment by csprocket777** [comment]
I'm running into this right now. Can you please post your resolution for this issue?

**Comment by merceyz** [comment]
@csprocket777 See https://github.com/yarnpkg/berry/issues/1333#issuecomment-626332416
