### ISSUE TITLE
[Feature] Need a CLI flag for cache clean to remove zip(s) from global cache

### ISSUE THREAD

**Issue by AlexLeung** [yarnpkg/berry#1337]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

I have a situation where I have 2 projects. Project 2 depends on Project 1, but I don't want to keep them in the same monorepo, so I reference Project 1 in Project 2's package.json via `file://` protocol.
The issue is that when I `yarn install` for Project 2, this caches a version of Project 1 in the global cache and local cache as a zip, and after updating Project 1, I'm not able to consume those updates in Project 2 even after a `yarn remove project-1-package-name`, followed by `yarn remove project-1-package-name@file://path/to/project-1` because on the install the local cache is missed, but then the zip is just fetched from the global cache, which doesn't contain the updates I've persisted to Project 1's actual source location on the local filesystem.

**Describe the solution you'd like**

Add a `-g`, `--global` flag to the CLI command `yarn cache clean`, and allow `yarn cache clean` to be used on specific dependencies.

So this would clear the entry within the local cache for all versions of package 1:

```
yarn cache clean project-1-package-name
```

this would locally clear the zip for package 1 specifically the version at the given file location

```
yarn cache clean project-1-package-name@file://path/to/project-1
```

and this would do the same but in the global cache

```
yarn cache clean --global project-1-package-name@file://path/to/project-1
```

So that once `yarn install` is run again, yarn reconstructs the zip by going to the actual location on the local filesystem then repopulates the global and local cache.

**Describe the drawbacks of your solution**

Someone might use the `-g` flag without providing a specific module by mistake, which would delete the entire cache by mistake. This isn't a huge concern though because it doesn't lead to unrecoverable work, they just need to wait sometime until `yarn install` repopulates the global cache again. Also this is the current functionality where there is only the option to clear the entire cache rather than specific entries, so likely users will not be surprised by this behavior.

**Describe alternatives you've considered**

Perhaps when `yarn install` is run, for all dependencies with a local file system remote, yarn should first invalidate the local and global cache for this dependency, that way the most up-to-date code is always fetched from the local file system. The downside here is that we'd be adding a special rule for a particular remote that doesn't apply to other remotes, which makes Yarn messier.

**Additional context**

I would be willing to make a demo repo if that would help with comprehension.

**Comment by paul-soporan** [comment]
1) You are doing this wrong. The `file:` protocol just tells Yarn to copy the contents of a folder inside the cache. The correct way to do this would be to use the `portal:` protocol (or even the `link:` protocol, see [this](https://yarnpkg.com/features/protocols#whats-the-difference-between-link-and-portal) for the difference). Those protocols tell Yarn to link a folder directly, without having it go through the cache.
2) `yarn cache clean` has both a `--mirror` flag which cleans only the global mirror,  and an `--all` flag which cleans both the local cache and the global mirror. The ability to only clean specific packages could be easily implemented, but I'm not sure it's if it's worth it. @arcanis What do you think?
3) If you want to temporarily/permanently disable the global mirror, you can use the  [`enableMirror`](https://yarnpkg.com/configuration/yarnrc#enableMirror) configuration setting.

Note: We could make the locators using the `file:` protocol also include the checksum of the archive as one of their parameters (so the cache would be automatically updated when there are changes), just like we do with the `patch:` and `exec:` protocol, but I'm not sure if the current behavior is intended or not (I believe that if it wasn't intended, it would have been fixed much earlier).

**Comment by AlexLeung** [comment]
Thanks for this clarification. The current documentation doesn’t explain the —mirror and —all flags, just mentions they exist.
My bad for not reading up on those other protocols of link: and portal:

**Comment by arcanis** [comment]
I've updated the wording, should be clearer now 👍

**Comment by AlexLeung** [comment]
I'm running into a similar scenario now where I want to use a tgz file as a dependency so I'm trying 

```
"dep": "file:./path/to/package.tgz"
```

in the package.json dependencies section

However, when the tar file contents change, the installed dependency is not being updated.
I'm wondering if there are examples of how to use `exec` here? Perhaps I could write a node script which just prints the raw contents of the tar file and then yarn will understand when the tar file changes.

**Comment by AlexLeung** [comment]
Looks like the last example here documents the use-case pretty well.

**Comment by AlexLeung** [comment]
It appears that when the output of an exec run changes, the original output is cached and used. I'll be opening a new issue for this.
