### ISSUE TITLE
Why is `yarn node` so long?

### ISSUE THREAD

**Issue by bertho-zero** [yarnpkg/berry#1338]
A simple command like that takes a lot more time using yarn than directly node:

```shell
yarn node -e "console.log(process.env)"
# 1,70s user 0,11s system 129% cpu 1,392 total

node -e "console.log(process.env)"
# 0,04s user 0,00s system 92% cpu 0,039 total
```

I suspect the creation of the temporary folder `/tmp/xfs-*` which is different for each run.

Wouldn't it be possible to use a reusable folder?

**Comment by arcanis** [comment]
The temporary folder creation isn't very heavy. What takes most of the time is actually the Node bootstrap (the parsing time itself is very significant, to which we need to add the time for the Node libraries to be ready. Overall it's at least 200ms). I doesn't seem much, but consider that we actually need to do it multiple times: once for the global Yarn, once for the local one, plus the parsing time for the `.pnp.js` file.

I think it'll get better (especially if Node implements primitive we can leverage, such as precompiled code), but at the moment `yarn node` is unfortunately a bit slow. You can workaround it somewhat by running `node -r ./.pnp.js ...` directly.

**Comment by bertho-zero** [comment]
Thank you for your reply.

In my project I have `nodeLinker: node-modules`, so I don't have a `.pnp.js` to load but I still go from 0.04s to 1.70s. It also takes 0.91s for a simple `yarn -v`.
