### ISSUE TITLE
[Bug] - Workspaces Focus Issue

### ISSUE THREAD

**Issue by athielen2** [yarnpkg/berry#1364]
- [ x] I'd be willing to implement a fix

**Describe the bug**

I have been attempting to convert our CICD process to utilize the workspaces focus command. This has worked great for about 95% of our workspace packages. However, we have a few packages that run into issues when we attempt to run yarn scripts after the focused install. 

An example of an error message we receive can be seen below:

```
$ yarn lint
Usage Error: Couldn't find ts-jest@npm:25.1.0 [79258] in the currently installed node_modules map - running an install might help

```

The same error message occurs, no matter the script run. The package specification can be seen below:

```
{
    "name": "@xxxx/client-utils",
    "version": "1.0.0",
    "description": "xxxx xxxx",
    "license": "UNLICENSED",
    "author": "xxxxxx",
    "main": "build/index.js",
    "types": "build/index.d.ts",
    "scripts": {
        "compile": "tsc",
        "test": "jest --passWithNoTests",
        "lint": "tslint --project ."
    },
    "dependencies": {
        "@xxxxx/postgres-utils": "1.0.0",
        "@xxxxx/quovo-utils": "1.0.0",
    },
    "devDependencies": {
        "@xxxxx/shared-config": "1.0.0",
        "@types/jest": "25.1.5",
        "@types/node": "^12.0.0",
        "@types/node-fetch": "2.5.4",
        "jest": "25.1.0",
        "jest-junit": "10.0.0",
        "prettier": "1.19.1",
        "ts-jest": "25.1.0",
        "tslint": "5.12.0",
        "tslint-plugin-prettier": "2.3.0",
        "typescript": "3.7.5"
    }
}
```
As you can see, ts-jest@25.1.0 is specified, and it is present in the root node_modules, but yarn still is not able to see it. If I perform a normal install, everything works fine.

Not 100% sure if this is a bug or an issue with our project configuration. Looking for some advice on how to troubleshoot if you think it is on our end. 

Thank you for all the work you do on yarn!

**Environment if relevant (please complete the following information):**

 - OS: OSX Catalina
 - Node version: v12.14.1
 - Yarn version: 2.0.0-rc.33

**Additional context**

The project is using the nodeLinker, not PnP.

**Comment by dannycoates** [comment]
I believe I'm having the same issue. I managed to reproduce it in this example: https://github.com/dannycoates/yarnbug. Run `showbug.sh` to see the problem.

It appears that when `yarn workspaces focus bugger` is run yarn puts `ts-node` in a different virtual package from when run with `yarn install`. When `yarn workspace bugger bin` is run it tries to find `ts-node` using the wrong virtual package reference.
