### ISSUE TITLE
[Feature] Feature parity with "yarn init" from yarn classic

### ISSUE THREAD

**Issue by TimonLukas** [yarnpkg/berry#1374]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

When I try to initialize the `package.json` for a new project, I expect fields like `author` and `repository` to be automatically set, as was the case with yarn classic. This is no longer the case, and the documentation doesn't mention anything in this regard.

**Describe the solution you'd like**

Feature parity with the yarn classic `init` command, at least through CLI flags.

**Describe the drawbacks of your solution**

I don't believe that there is really a way to break this.

**Describe alternatives you've considered**

The best alternative I see is to use yarn classic or npm, both solutions that shouldn't be necessary.

**Additional context**

Since the documentation is kinda confusing, is it possible that the feature is unfinished?

**Comment by arcanis** [comment]
Time is a resource, so if you want it please PR it 🙂 I actually think we could do better than the v1 by encoding the default fields in the settings (leveraging yaml, essentially):

```yaml
initFields:
  license: MIT
  author: "..."
  repository: "..."
```

**Comment by TimonLukas** [comment]
Are you talking about the per-project `.yarnrc.yml`? I'd assume most people use the command to set up a normal new project, in which case this wouldn't help.

I'd love to help and I'll see if I have some spare time over the next days. Still, it would be nice to add a disclaimer to the documentation, I don't think most people would expect these kind of "basic" features to be dropped silently.

**Comment by arcanis** [comment]
> Are you talking about the per-project .yarnrc.yml?

Yarn also uses the home folder `.yarnrc.yml` when possible (unless the local one redefines the fields).

**Comment by TimonLukas** [comment]
That's really good to know and actually really helpful - I implemented a custom registry a few days ago, and this will really help the DX for my team.

Is it possible that that fact is not documented? It makes sense for an RC file to also be read from the home folder, but the documentation doesn't mention anything in that regard, which made me assume this doesn't work: https://yarnpkg.com/configuration/yarnrc

**Comment by binary-koan** [comment]
I was also surprised by the new behaviour and came across this. I really like the idea of `initFields` and had a go at implementing it.

For me, because you can set it in the `.yarnrc.yml` of a monorepo, I'd use it to make sure all child packages are created with the same basic configuration. For example, we use the same Jest configuration for unit tests in a bunch of packages and it would be super cool to initialize that immediately for any new packages (and kinda formalize that it's the standard for testing across the project)
