### ISSUE TITLE
[Feature] yarn dlx could consider npmScopes in the current working directory .yarnrc.yml

### ISSUE THREAD

**Issue by TimonLukas** [yarnpkg/berry#1380]
- [x] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Currently, `yarn dlx` does not consider the current directories' `.yarnrc.yml`, only the one in the user directory. This behavior definitely makes sense in many cases, but it does complicate some scenarios:
- For CI tools (e. g. Travis CI) to pick up on custom scopes, `.yarnrc.yml` first has to be copied to `~`
- A developer that joins a project first has to copy the scope definition into their own `.yarnrc.yml` before they can use `yarn dlx` to execute custom tools (where sharing isn't really an option once #1374 is implemented)
- Switching registries per-project is not possible if scopes overlap

**Describe the solution you'd like**

If a `.yarnrc.yml` is present in the folder in which `yarn dlx` is executed, it should be read, and scopes (and probably other options as well?) should be considered and merged with the config from the home directory. Values from the local directory should IMO take precedence.

**Describe the drawbacks of your solution**

This could lead to some confusion, since resolution might be different depending on which project /folder you are in when executing the command. But this holds true as well for commands like `yarn add`.

**Describe alternatives you've considered**

The only alternative I can come up with would be to add a switch to specify which `.yarnrc.yml` file should be loaded. This is definitely possible, but feels less intuitive (although I'm not set on either solution, both would fix my specific problem at least very well).

**Comment by arcanis** [comment]
Generally speaking I have the feeling you're trying to use `dlx` for something it isn't intended for, but let's see.

> For CI tools (e. g. Travis CI) to pick up on custom scopes, `.yarnrc.yml` first has to be copied to `~`

We don't recommend using `dlx` for CIs. All your dependencies should be part of your lockfile, meaning that `dlx` is an anti-pattern (its dependencies aren't locked).

> A developer that joins a project first has to copy the scope definition into their own `.yarnrc.yml` before they can use `yarn dlx` to execute custom tools (where sharing isn't really an option once #1374 is implemented)

Similarly, standard workflows shouldn't rely on `dlx`. They would otherwise have consistency and security issues (consistency because your developers would use different dependency trees, security because they would be one typo away from running untrusted code).

> Switching registries per-project is not possible if scopes overlap

Not sure I understand this one 🤔

--- 

The two first use cases are intended to be solved by using `yarn run`, which makes sure all your dependencies are part of your lockfile and that you always run exactly what you intend to run. On top of it, you get to share the configuration file 🙂 Would that work for you?

Note that we have an FAQ explaining [how to share scripts in a monorepo](https://yarnpkg.com/advanced/qa#how-to-share-scripts-between-workspaces).

**Comment by TimonLukas** [comment]
It's definitely possible I'm kind of abusing it. It's probably best if I describe my use case a bit more:

I implemented a custom NPM registry which uses a Github Enterprise instance as its' backend. This is mostly meant for some internal tooling for my team, and it works surprisingly well (and is the best way for us to get private packages set up). Basically it exposes tagged releases as package versions.

**CI**: Now, in a different repository we have some documentation which we want to build with a custom static site generator. The way I've set it up now is for Travis to copy the documentation projects' `.yarnrc.yml` to `~`, which then means I can execute the static generator using `yarn dlx`. I could of course also initialize a project, add it as a dependency and then execute it, but this feels like a use-case which dlx is better-suited for. I am aware of the dangers not pinning our dependencies could have in this case, but since it's just internal documentation and we have CI set up on the generator this is a nice way for us to auto-generate our static doc files. Additionally I would really like not cluttering the repository with more non-documentation related files if possible. Right now it's just `.yarn/` and `.yarnrc.yml`. If I declare the generator as a dependency, I'd additionally have `package.json`, `yarn.lock` (and maybe `.pnp.js`). This makes the DX worse when using Github to browse the documentation.

**Developers using `dlx`**: This is actually kind of similar to the previous point. There are some more internal tools that I'd like to develop, which aren't really part of the projects, so I don't want to add them as (dev-)dependencies. For `add`ing packages or similar operations, other developers won't have to change anything on their system, since the custom scope is registered through the local configuration file. But they won't be able to access the same scope they were just `add`ing a package from, because the one command does read the local file, while the other doesn't. The more I think about it, the less intuitive this part feels to me.

**Switching registries**: Sorry, that part wasn't very clear. This is **not** a scenario I have encountered, and one I'll heavily fight against if it should come up in my team - but I don't think it's impossible for one development team to use the same scope name for different registries in different projects (again, I think this is a terrible idea, won't do it myself). All "local" commands such as `add` will work with this no problem, just `dlx` won't. This feels like an artificial limitation that kinda just doesn't have to be there.

I know that this is a kind of strange use-case, and I appreciate you taking the time to discuss it. But I do think that even apart from my specific situation this feature would be useful for people. It seems like some folks wanted the same [for npx](https://github.com/zkat/npx/issues/200), and it seems to [have been implemented](https://github.com/zkat/npx/issues/133). I really like `yarn`, and I like what you and the other contributors been doing with `berry`. I'd really prefer continuing using it instead of switching back, even if it means I have to implement some features myself.

**Comment by arcanis** [comment]
Thanks for explaining, that makes sense.

I think it would be fine to modify `dlx` to simply copy the current `.yarnrc.yml`, if it exists (for this iteration we would only take `projectCwd` into account, no traversal of the ancestor hierarchy; I think it would be overkill).

The one tricky part I can foresee is the plugin definition, which would need to be remapped using absolute paths (since otherwise the plugins wouldn't be found). We can't just ignore them, because otherwise Yarn would throw when finding plugin-specific configuration fields.

Would also need some tests, of course 😜

**Comment by TimonLukas** [comment]
> no traversal of the ancestor hierarchy; I think it would be overkill

I definitely agree, only the current directory should be considered. I wouldn't expect parent config files to be considered, it could even lead to some strange bugs.

> The one tricky part I can foresee is the plugin definition, which would need to be remapped using absolute paths

That's a good point. Is there a plugin that needs specific configuration? Then I can try to figure that out during implementation.

> Would also need some tests, of course 😜

And yeah, the tests are the part I'm most afraid of, but I'm sure I'll somehow be able to figure it out :)

**Comment by arcanis** [comment]
> That's a good point. Is there a plugin that needs specific configuration? Then I can try to figure that out during implementation.

Not one in particular - it's just that all plugins are allowed to define their own configuration settings (and they usually do), and Yarn would report unknown configuration values if it was to find those without the right plugin.

> And yeah, the tests are the part I'm most afraid of, but I'm sure I'll somehow be able to figure it out :)

The [contributing guide](https://yarnpkg.com/advanced/contributing#testing-your-code) should help!

**Comment by TimonLukas** [comment]
> Not one in particular - it's just that all plugins are allowed to define their own configuration settings

I'm mainly asking because none of the READMEs for the optional plugins linked in the main README talk about configuration values, and I want to make sure that I test this case before I submit a PR. Do you have a specific example for a plugin that specifies custom options and could break?

**Comment by paul-soporan** [comment]
- `plugin-constraints`: https://github.com/yarnpkg/berry/blob/5003627b14d9ee082e63d6aa757f3b14e13dff77/packages/plugin-constraints/sources/index.ts#L8
- `plugin-version`: https://github.com/yarnpkg/berry/blob/5003627b14d9ee082e63d6aa757f3b14e13dff77/packages/plugin-version/sources/index.ts#L8

**Comment by TimonLukas** [comment]
Thank you @paul-soporan, that was very helpful.

So I started work on the feature, and it's working nicely (except for tests). I did not encounter a problem with the plugins, and I'd like to make sure that my manual test flow makes sense:
1) Clone my fork of the berry repository & switch to a different branch
2) Implement feature
3) In the cloned repository, execute `yarn install`
4) Add a custom scope to the projects' `.yarnrc.yml`
5) Execute `yarn dlx` with a custom-scoped project with no `~/.yarnrc.yml` present
6) Add the config option `preferDeferredVersions`, which is added by `plugin-versions`
7) Execute the same command as in step 5)

This did not throw an error. Is this the potential error case you saw @arcanis?

**Comment by arcanis** [comment]
That would be the right workflow, but the Berry repository is special: it automatically loads all the plugins straight from the repository sources. As a result, when running `yarn dlx` inside the context of the Berry repo, it will never complain about `preferDeferredVersions`, but it would in the production build (and within the tests).

**Comment by TimonLukas** [comment]
Ah, inside a test I can replicate it! Great, then I'll try to find a way to fix it. :)

**Comment by TimonLukas** [comment]
Fixed by #1387
