### ISSUE TITLE
[Bug] Typescript paths support?

### ISSUE THREAD

**Issue by daihy8759** [yarnpkg/berry#1384]
I have a ts config like this
```json
    "compilerOptions": {
        "baseUrl": "./",
        "paths": {
            "components/*": ["src/components/*"]
        }
    }
```
Use in tsx file:
> import { BasicLayoutProps } from 'components/BasicLayout';

but throw en error on compile

> Cannot find module 'components/BasicLayout' or its corresponding type declarations.  TS2307

**Environment if relevant (please complete the following information):**

 - OS: [OSX]
 - Node version [v12.13.0]
 - Yarn version [2.0.0-rc.33]

**Comment by merceyz** [comment]
You should use the `link` protocol instead, it has the added benefit of making the paths work for any tool you have, not just `tsc`.
https://yarnpkg.com/features/protocols
