### ISSUE TITLE
[Feature] Check file existence rather then throwing in statSync

### ISSUE THREAD

**Issue by ghepesdoru** [yarnpkg/berry#1389]
- [x] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Hello, great work on Yarn 2.

Yarn 2's PnP support is clearly supperior to previous yarn 1 implementations, and most of the issues I had before are history. One problem that remains and gets in the way of a smooth developer experience is the behavior of **zipFs.statPromise**: It throws an error inside statSync when missing a resource. This gets into the way of using **pausing on exceptions** for debugging large builds.

**Describe the solution you'd like**

I would like for zipFs.statPromise to gracefully check the file existence (as it does) and return the errors rather then throwing them. This might be a bit more involved as the error will have to bubble up, but should speed things up (theoretically) and allow debugging of environments heavely tight to PnP.

**Describe the drawbacks of your solution**

Requires bubbling the error up and might require some effort.

**Comment by arcanis** [comment]
Thanks for your words! 👋

I'm not sure I entirely understand though - the FakeFS layer (that ZipFS extends) aims to mimic the Node `fs` interface as much as possible. In this context, *not* throwing an exception would be invalid, wouldn't it?

**Comment by ghepesdoru** [comment]
Hello @arcanis. Thank you for your quick replay.

If the purpose of FakeFS is to mimic the fs interface, then yes: the current behavior is correct. Deviating from the throw in that case would mean breaking contexts relaying on the throw (to handle errors at upper levels for example).

You can safely ignore this issue.
