### ISSUE TITLE
[Docs] Document how package authors can make their packages pnp compatible

### ISSUE THREAD

**Issue by SamChou19815** [yarnpkg/berry#1392]
**Describe the user story**

Recently I am helping [docusaurus](https://github.com/facebook/docusaurus) to make their packages and plugins pnp compatible. However, I couldn't find a lot of information on yarn's website how to achieve that.

There is [some vague mentions](https://yarnpkg.com/advanced/pnpify/#motivation) of the `require` APIs, which seems to suggest that we should try to use them. However, it's not clear from the docs when we should use `require`, `require.resolve` or `createRequire`. I remember that I once had to search `createRequire` in Yarn's discord channel because I happened to remember seeing a use case explanation here. It would be much nicer if it's documented on the website, so that people can get actionable plans to fix their packages for pnp.

**Describe the solution you'd like**

Document on the website with some common scenarios. For example:

- Use `require.resolve` if you want to expose the path of a dependency only you know
- If you are creating a plugin system, recommend user to use `require.resolve` to resolve module path.
- If under some crazy scenarios, use `createRequire`.
- etc

**Describe the drawbacks of your solution**

Don't see any major drawbacks.

**Describe alternatives you've considered**

Upstream the docs to nodejs. But I don't think people may go to nodejs' website when they see their packages not working under yarn pnp.

**Comment by merceyz** [comment]
Documentation around this improved with https://github.com/yarnpkg/berry/pull/1777 so we now have https://yarnpkg.com/advanced/rulebook which should satisfy this
