### ISSUE TITLE
[Question] Can I use require(".pnp.js").setup() instead of "yarn node"?

### ISSUE THREAD

**Issue by MrEfrem** [yarnpkg/berry#1397]
In the google cloud functions I can’t affect on the execution command. I created an issue in their bug tracker but I’m not sure they will resolve it soon. So my question is: can I use `require(".pnp.js).setup()` instead of `yarn node` and what will I have disadvantages?

**Comment by arcanis** [comment]
It should work just the same. One caveat is if  your program spawns child process, since `setup` doesn't affect the environment (whereas `yarn node` sets NODE_OPTIONS).

If you can set environment variables in Google Cloud, I'd suggest to configure NODE_OPTIONS to `--require path/to/pnp.js`.

**Comment by MrEfrem** [comment]
Unfortunately I can’t set the `NODE_OPTIONS` in the cloud functions. However, my source code usually doesn’t spawn child process, only I can’t be sure about it in my dependencies of course. I will refer your answer in my google cloud platform issue. Thank you.
