### ISSUE TITLE
[Bug] Typescript creates wrong output in some project configurations.

### ISSUE THREAD

**Issue by Acerbic** [yarnpkg/berry#1398]
**Describe the bug**

Typescript's `tsc` produces different (wrong) output from what is expected under certain conditions.

**To Reproduce**

I'm too stupid for Sherlock, but I [made a repo](https://github.com/Acerbic/yarn2bugs-tsrootdir) with a demo showcasing the scenario that I consider to be a bug.

**Environment if relevant (please complete the following information):**

Unsure if relevant.

 - OS: Linux Pop!_OS 20.04 LTS (based on Ubuntu 20.04 / focal)
 - Node version: v14.3.0
 - Yarn version: 2.0.0-rc.33 (1.22.4)

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/1472
