### ISSUE TITLE
[Feature] Better error messages on npm publish failed

### ISSUE THREAD

**Issue by thewrath** [yarnpkg/berry#1408]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

I wanted to publish a package on npm via `yarn npm publish` and I got the error: 

> YN0041: Invalid authentification (as undefined)

Actually it's because I haven't changed the version of my package... a better message saves time:

> YN0041: Invalid version number 

This request is not very important but would bring a better user experience. 🙂
Thank you for the work you're doing.

**Comment by arcanis** [comment]
Interesting - we throw this error when the npm registry returns HTTP 401 or 403 (Forbidden / Unauthorized). The `undefined` is whatever a subsequent call to the `/-/whoami` returns (your token username, usually). I'm not sure we can do better, unless you can log the exact return from the API (you can do that by running `yarn set version from sources --no-minify` then adding `console.log` statement in the `httpUtils` module; would be nice to make a switch making that easier).

**Comment by arcanis** [comment]
Closing for now; feel free to reopen with the extra information
