### ISSUE TITLE
[Feature] Improve ZipFS.readSync performance

### ISSUE THREAD

**Issue by markdingram** [yarnpkg/berry#1411]
- [x] I'd be willing to implement this feature

**Describe the user story**

@aws-cdk/aws-s3-deployment has a 10mb Zip file inside it that hashes on each run with 

<https://github.com/aws/aws-cdk/blob/a5c06a3a27b39a5315d0cfd0d34b3c1b25cfc464/packages/%40aws-cdk/core/lib/fs/fingerprint.ts>
 
Currently gets stuck due to https://github.com/yarnpkg/berry/pull/1409, after that the it looks like performance is slow due to `ZipFS.readSync` calling `ZipFS.readFileSync` afresh on each read into the buffer.

There's a test repo to reproduce - https://github.com/markdingram/yarn-zip
 ```
$ yarn run slow
starting
read: 281.731ms 8192 8192
read: 480.655ms 8192 16384
read: 663.234ms 8192 24576
read: 845.223ms 8192 32768
read: 1027.200ms 8192 40960
read: 1210.914ms 8192 49152
read: 1391.626ms 8192 57344
read: 1590.551ms 8192 65536
read: 1764.586ms 8192 73728
read: 1944.802ms 8192 81920
read: 2139.621ms 8192 90112
read: 2333.735ms 8192 98304
read: 2525.436ms 8192 106496
....
```

Ejecting is a workaround.

**Describe the solution you'd like**

Cache the file contents in the `ZipFS.fds` Map on first read to serve subsequent requests.

**Describe the drawbacks of your solution**

Memory pressure if Zip Files aren't closed after use by existing consumers? Or many files are opened concurrently.

**Describe alternatives you've considered**

Store an open native File handle in the ZipFS.fds map on first read. Seems more complicated than the proposed approach?

**Additional context**

Repro - https://github.com/markdingram/yarn-zip

**Comment by merceyz** [comment]
Closing as fixed since https://github.com/yarnpkg/berry/pull/1743 started caching the read results
