### ISSUE TITLE
[Case Study] yarn install latest npm tag

### ISSUE THREAD

**Issue by ChiefORZ** [yarnpkg/berry#1414]
**Describe the goal of the investigation**

We recently switched over in our company for our projects to use yarn berry.
But some workflows are not really convenient to use - or we are missing something.

We have many repositories, which are built and bundled with our CI environment. The daily "snapshots" are released with an **canary** Tag on our npm Registry and the actual releases tagged with "latest".

On a daily basis the projects are re-built and should fetch and use the newest "canary". Thats why we thought we just put **canary** as our dependency resolutions:

```json
// package.json
{
  "name": "@company/project",
  "dependencies": {
    "@company/react-hooks": "canary"
  },
  "version": "0.0.0"
}
```
It locks the dependency `"@company/react-hooks": "0.0.1-canary.1"` in the `yarn.lock` and when reinstalling the project yarn will always fetch version `canary.1` even though `canary.2`  is the tagged npm package.

And we need the yarn.lock to be committed because we need immutable releases for our master branch...

**Questioning**

* What is the recommended way to always fetch the latest tagged npm package?
* Shouldn't it be the default to fetch all new dependencies, that are valid semver and will not harm anything - while using `yarn install --immutable` will hard lock yarn to use the package versions defined in the `yarn.lock`?
* Is there a way to update multiple dependencies, like it was with yarn classic? `yarn update --scope @company` was a great way to update all dependencies on our CI system. And here it should upgrade to the latest valid and compatible semver either.

**Comment by arcanis** [comment]
> What is the recommended way to always fetch the latest tagged npm package?

Running `yarn up @company/react-hooks@canary` before the install (or before you use the project, with zero-install) should do the trick.

> Shouldn't it be the default to fetch all new dependencies, that are valid semver and will not harm anything

No - Yarn guarantees deterministic installs by default, and even if an upgrade *should* be safe per semver rules in practice it should be a conscious action. This is how 1.x worked as well.

> Is there a way to update multiple dependencies, like it was with yarn classic?

I don't think `yarn up` supports glob patterns yet, but it seems a good idea and we'd likely merge a PR to this effect ! Then you'd just run `yarn up @company/*@canary`.

Another more convoluted option is to you `yarn constraints query` to obtain the list of `@company` dependencies, and update them all. It's more flexible (and you ca do it now), but more involved. For example:

```
yarn constraints query "workspace_has_dependency(_, DepName, _, _), atom_concat('@yarnpkg/', _, DepName)"
```

**Comment by ChiefORZ** [comment]
> Running yarn up @company/react-hooks@canary before the install (or before you use the project, with zero-install) should do the trick.

I tried it locally and on our CI system, but it does not seem to work. Can you confirm that it is working with updating to the newest released `latest` package. Would be a viable way to make sure we always require the latest daily snapshot.

> I don't think `yarn up` supports glob patterns yet, but it seems a good idea and we'd likely merge a PR to this effect ! Then you'd just run `yarn up @company/*@canary`.

That would be an great addition! Can you keep track of this feature request somewhere?

> Another more convoluted option is to you `yarn constraints query` to obtain the list of `@company` dependencies, and update them all. It's more flexible (and you ca do it now), but more involved. For example: `yarn constraints query "workspace_has_dependency(_, DepName, _, _), atom_concat('@yarnpkg/', _, DepName)"`

Thats awesome as well, but can you execute something directly with yarn constraints - others with `sed` and `xargs`?

**Comment by arcanis** [comment]
> That would be an great addition! Can you keep track of this feature request somewhere?

Sure, open a dedicated issue 👍

> Thats awesome as well, but can you execute something directly with yarn constraints - others with `sed` and `xargs`?

Not directly, but together with the `--json` flag you get a JSON output which is easier to work with from within scripts.

**Comment by arcanis** [comment]
> I tried it locally and on our CI system, but it does not seem to work.

My bad - running `yarn up foo@canary` will literally set the range of your dependencies to `canary`. Since `canary` is already in the lockfile, it won't get re-locked. I think that should be considered as a bug 🤔

**Comment by ChiefORZ** [comment]
thanks for the help. i opened the corresponding feature request and bug report 🙏

**Comment by donmccurdy** [comment]
> My bad - running yarn up foo@canary will literally set the range of your dependencies to canary. Since canary is already in the lockfile, it won't get re-locked

I'm seeing this same behavior in yarn 3.2.0 I think, despite this bug having been fixed a while ago. Is this expected, and/or should I open a new issue?
