### ISSUE TITLE
[Feature] Support `pnpMode: loose` and `pnpFallbackMode` in child workspace packages

### ISSUE THREAD

**Issue by madjam002** [yarnpkg/berry#1417]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

I've been working on moving a large monorepo over to Yarn 2 / PnP and so far it has been great and it works exceptionally well with my CI pipeline (Nix based).

**Describe the user story**

When using Yarn workspaces it would be very helpful to have the ability to set `pnpMode: loose` on an individual package-by-package basis so that it can be used for packages that don't yet work with PnP.

My entire repo is a Yarn workspace, and one package in the repo is a NextJS project. Unfortunately at the moment, NextJS support for PnP isn't great, along with the multitude of webpack loaders that are being pulled in from a few plugins I'm using. I've already filled up my root `.yarnrc.yml` with various `packageExtensions` to support PnP properly, but when I started migrating the NextJS project, there were _so many_ issues, that I needed a more pragmatic solution for the short-term.

**Describe the solution you'd like**

The ability to specify `pnpMode` on a package by package basis (and `pnpFallbackMode` if necessary).

**Describe the drawbacks of your solution**

I'm not sure of the implications, but perhaps if it could be specified on a package instead of the workspace root then it might be possible for the user to break PnP?

**Describe alternatives you've considered**

Currently, as a workaround, I have removed my NextJS project from the root Yarn workspace, given it its own `.yarnrc.yml`, `yarn.lock`, etc, and am referencing other packages from my parent Yarn workspace using the `portal:` protocol. This appears to work fine, I'm not sure if there are any drawbacks.

There is however an issue now with editor integration. Because pnpify for vscode expects a single `.pnp.js` (I think), Typescript now errors on any file inside of my NextJS project as it has a separate `.pnp.js`. I'm not sure if there is a way around this.

**Comment by arcanis** [comment]
> I'm not sure of the implications, but perhaps if it could be specified on a package instead of the workspace root then it might be possible for the user to break PnP?

To be honest, the main problem is the complexity of adding another configuration settings for a pattern that is intended as a workaround until better days. Features like this tend to coalesce and make the whole harder to maintain for us 😕

Given that this feature seems like something I'd tag as "nice to have" (in that it not existing doesn't prevent anything, you can still enable the loose mode for everything, having this setting would just provide a slightly better protection for workspaces that don't need the loose mode), I'm not convinced the pro out-weight the con 🤔

**Comment by madjam002** [comment]
@arcanis That's fair enough - I guess it is a nice to have. Running it as a separate configuration and referencing the workspace packages with `portal:` seems to be fine anyway.

Regarding the editor issue where pnpify only works with one `.pnp.js`, are there any alternatives or ways that it could work with multiple `.pnp.js`/`.yarnrc.yml` files? If not then it's not a huge deal either, I'll either install another Typescript hook for VScode to pick up and just switch between them, or use a separate Vscode window altogether.

On a separate note, like you mentioned I did switch the whole workspace over to `loose` to give it a go, and while that worked with the NextJS project, some of my other packages started logging dependency warnings even though I had got everything working in strict mode... so I just switched it back to strict. Looking at those issues e.g `Error: debug tried to access supports-color (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.` I can see it is fixed on a version of `debug` (4.2.0) by adding `optional: true` which I haven't yet pulled in, which makes me wonder why I only see this warning in `loose` and not a hard exception when in `strict`! Not too worried about this though as it works in strict mode.

**Comment by arcanis** [comment]
> Regarding the editor issue where pnpify only works with one `.pnp.js`, are there any alternatives or ways that it could work with multiple `.pnp.js`/`.yarnrc.yml` files? If not then it's not a huge deal either, I'll either install another Typescript hook for VScode to pick up and just switch between them, or use a separate Vscode window altogether.

I'm not aware of any - it's likely something that would have to be handled in VSCode itself, since it requires spawning multiple instances of the VSCode server.

> which makes me wonder why I only see this warning in `loose` and not a hard exception when in `strict`!

This is unfortunately expected 🙁 cf the following note: https://yarnpkg.com/features/pnp#caveat.

**Comment by madjam002** [comment]
> I'm not aware of any - it's likely something that would have to be handled in VSCode itself, since it requires spawning multiple instances of the VSCode server.

Ok no worries I will look at the alternatives I mentioned above.

> This is unfortunately expected slightly_frowning_face cf the following note: https://yarnpkg.com/features/pnp#caveat.

Ahh okay makes sense now, thanks for the pointer.

I will carry on with using `portal:` for now then unless something else comes up. Thanks for your work on Yarn 2, PnP has been a great experience so far!
