### ISSUE TITLE
[Bug] Resolve error: unable to load resolver "node" import/named with ESLint configured

### ISSUE THREAD

**Issue by IT-CASADO** [yarnpkg/berry#1427]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I try to use Yarn 2 together with ESLint and Prettier, but I get this error:

Resolve error: unable to load resolver "node"  import/named
Resolve error: unable to load resolver "node"  import/no-extraneous-dependencies
(and five more errors)

**To Reproduce**

Clone this git repository: https://github.com/IT-CASADO/yarn-eslint/tree/yarn-v2
(master branch contains the same configuration with Yarn 1)

Execute following command: **yarn eslint ./src/*.***

**Environment if relevant (please complete the following information):**

 - OS: [Windows]
 - Node version [12.17.0]
 - Yarn version [2.0.0-rc.33]

**Additional context**

I followed this steps here:
- https://yarnpkg.com/getting-started and
- https://yarnpkg.com/advanced/editor-sdks

I'm assuming no configuration errors with ESLint, because it is working with Yarn 1.
Do I miss something special for Yarn 2?

**Comment by markdingram** [comment]
Yarn 2 is stricter - see https://next.yarnpkg.com/features/pnp#pnp-loose-mode

Enabling loose mode temporarily and running outputs:

`(node:34285) [MODULE_NOT_FOUND] Error: eslint-module-utils tried to access eslint-import-resolver-node, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.`

Resolve by adding a hint to `.yarnrc.yml`

```
packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
```

**Comment by alamothe** [comment]
> Resolve by adding a hint to `.yarnrc.yml`
> 
> ```
> packageExtensions:
>   eslint-module-utils@*:
>     dependencies:
>       eslint-import-resolver-node: "*"
> ```

This works for executing `yarn eslint`, but for CRA the error still remains if I try to start the app. It makes it impossible to start. Any solution for CRA?
