### ISSUE TITLE
Proxy certificates support

### ISSUE THREAD

**Issue by danreg** [yarnpkg/berry#1434]
I get the error 

> RequestError: self signed certificate in certificate chain

when running this command for example:
`yarn set version latest`
I'm using the proxy and httpsProxy config options.

Earlier using Yarn V1 it was possible to specify a cafile. But I can't find any configuration like this for berry.

**Comment by arcanis** [comment]
It isn't implemented at the moment. PR welcome 👐

**Comment by skyme5** [comment]
Can I implement a PR for this?

Here is what I've found.

`berry` uses a [tunnel](https://www.npmjs.com/package/tunnel) for proxy, the proxy object in [httpUtils.ts#L22](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/sources/httpUtils.ts#L22) uses only `host` and `port` (and empty `headers` object).

The [tunnel](https://www.npmjs.com/package/tunnel) package accepts following options to construct a proxy,
```js
{
    host: proxyHost, // Defaults to 'localhost'
    port: proxyPort, // Defaults to 443
    localAddress: localAddress, // Local interface if necessary
 
    // Basic authorization for proxy server if necessary
    proxyAuth: 'user:password',
 
    // Header fields for proxy server if necessary
    headers: {
      'User-Agent': 'Node'
    },
 
    // CA for proxy server if necessary
    ca: [ fs.readFileSync('origin-server-ca.pem')],
 
    // Server name for verification if necessary
    servername: 'example.com',
 
    // Client certification for proxy server if necessary
    key: fs.readFileSync('origin-server-key.pem'),
    cert: fs.readFileSync('origin-server-cert.pem'),
  }
```

What should be implemented for this (`ca`, `key`, `cert` as well as `proxyAuth`, `servername`, and `localAddress`) and what should be the options names,

- `proxyCA` for `ca`
- `proxyClientKey` for `key`
- `proxyClientCert` for `cert`
- `proxyHeaders` for `headers` maybe?

And what about other options such as `proxyAuth`, `localAddress`, and `servername`?

**Comment by merceyz** [comment]
Support for `caFilePath` was added in https://github.com/yarnpkg/berry/pull/1934

**Comment by GiladShoham** [comment]
@arcanis @merceyz 

I know it's pretty old (and you already support cafile), but I'm wondering if there is plan to support
[ca](https://docs.npmjs.com/cli/v7/using-npm/config#ca) (not ca file), [cert](https://docs.npmjs.com/cli/v7/using-npm/config#cert), [key](https://docs.npmjs.com/cli/v7/using-npm/config#key) and [no-proxy](https://docs.npmjs.com/cli/v7/using-npm/config#noproxy).
they are all supported in npmrc file (links attached).

Thanks a lot,
Gilad.
