### ISSUE TITLE
🆘 Yarn with GitHub Actions

### ISSUE THREAD

**Issue by TheGrimSilence** [yarnpkg/berry#1451]
When trying to use GitHub Actions, I have to clear the cache and reinstall dependencies. My native builds (`unplugged`) is too heavy to push to the repository because of modules like Puppeteer that ship with large executables. I've tried a handful of commands Actions-side but they all error. I'd have hoped rebuild would work, but it didn't. And `yarn install` (with all variants of flags) only errored as well. So cleaning the cache and then reinstalling them is all that seems to work unless I'm missing something and this seriously slows down testing Actions-side.

Please refer to [my repository](https://github.com/TheGrimSilence/Yarn-2-Webpack-TypeScript) for any source references.

**Comment by TheGrimSilence** [comment]
Specifically, I have my .yarn/cache pushed. But not `build-state.yml` or `install-state.yml` and I get an error saying my versions don't match. So I always end up reinstalling. I'll try pushing the install-state

**Comment by TheGrimSilence** [comment]
Neither build or install state fix the errors, I've read the Q&A as well. This is a snippet of the errors.

```bash
  ➤ YN0018: │ lodash@npm:4.17.15: The remote archive doesn't match the expected checksum
  ➤ YN0018: │ lodash@npm:4.17.15: The remote archive doesn't match the expected checksum
  ➤ YN0018: │ lodash@npm:4.17.15: The remote archive doesn't match the expected checksum
  ➤ YN0018: │ lodash@npm:4.17.15: The remote archive doesn't match the expected checksum
  ➤ YN0018: │ lodash@npm:4.17.15: The remote archive doesn't match the expected checksum
  ➤ YN0018: │ lodash@npm:4.17.15: The remote archive doesn't match the expected checksum
```

**Comment by TheGrimSilence** [comment]
#1142 Solved this problem by using `yarn set version from sources` which works with GitHub Actions now.

**Comment by mvarchdev** [comment]
Hey! Some another solution for this?
