### ISSUE TITLE
[Feature] `yarn workspaces foreach -t --include run` should run for dependencies

### ISSUE THREAD

**Issue by globin** [yarnpkg/berry#1456]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Easily build one specific workspace and prior to that all dependencies.

**Describe the solution you'd like**

Having workspaces `a`, `b`, `dep-c`, where `a` and `b` both depend on `deps-c` I'd expect
```
yarn workspaces foreach -t --include a run build
```
to first build `dep-c` and then `a`, and not build `b`.

**Describe the drawbacks of your solution**

None as of now

**Describe alternatives you've considered**

None as of now

**Additional context**
N/A

**Comment by gntract** [comment]
Is there clarity on how the `yarn workspaces foreach` topological execution works? I thought the above should work given the "topological" flag on `yarn workspaces foreach`. It's similar to a setup which I've been trying that doesn't seem to work on `2.1.1`

If we have:

`~/package.json`
```json
{
  "name": "root",
  "workspaces": [
    "packages/*"
  ]
}
```

`~/packages/a/package.json`:
```json
{
  "name": "a",
  "dependencies": {
    "b": "workspace:*"
  },
  "scripts": {
    "build": "echo 'a'"
  }
}
```

`~/packages/b/package.json`
```json
"name": "b",
  "scripts": {
    "build": "echo 'b'"
  }
```

Running`yarn workspaces foreach -at --exclude a run build` will print out:
```
b
a
```

👍 👍 

whereas running `yarn workspaces foreach -t run build` from within `~/packages/a` will print out:

```
a
```

😞 

Why isn't `b` included? This is basically what as implied during the discussion about `workspaces foreach`:

> Personally the order I value most is a toplogical sort, running through dependencies before dependants. If package foo depends on bar, I don't think it makes sense for yarn workspace foreach test to run the tests in foo first. If the tests in bar fail, chances are the tests in foo will also fail, but it's the failure in bar I want to know about. The same goes for building an entire workspace, e.g. using yarn workspace foreach tsc: dependants need to go first, otherwise the build is broken because foo can't find package bar.

https://github.com/yarnpkg/berry/issues/62#issuecomment-485140589

**Comment by merceyz** [comment]
Implemented in https://github.com/yarnpkg/berry/pull/1986
