### ISSUE TITLE
[Feature] [yarn audit --filter] Filter the exit code based on the provided severity level 

### ISSUE THREAD

**Issue by simonespa** [yarnpkg/berry#1461]
- [ ] I'd be willing to implement this feature
- [x] This feature can already be implemented through a plugin

**Describe the user story**
Re-raising https://github.com/yarnpkg/yarn/issues/7386 here for better visibility and building on top of https://github.com/yarnpkg/berry/issues/1187.

I am a Yarn user and I'd like to be able to use `yarn audit` (described by https://github.com/yarnpkg/berry/issues/1187) with a `--filter` option in a CI environment, so that if I filter at a specific severity level, the command can return with a zero exit code even if there are vulnerabilities with a lower severity and allow the build job to finish with success.

By doing so, the developer can decide which level of severity should stop the build pipeline and which one should not.

Currently, by running `yarn audit` the command exits with a non-zero number that is the sum of found severities:

1 for INFO
2 for LOW
4 for MODERATE
8 for HIGH
16 for CRITICAL

as explained https://github.com/yarnpkg/yarn/pull/6819.

By running `yarn audit --level <LEVEL>` will limit the audit table to vulnerabilities of the corresponding level and above but It will not affect the exit code of the command (as explained https://classic.yarnpkg.com/en/docs/cli/audit/#toc-commands)

**Describe the solution you'd like**
A solution could be to add the `--filter <SEVERITY>` option to `yarn audit` command which exits with code `0` if no vulnerability has been found for the provided severity level and above.

**Example:** if the codebase has 1 vulnerability: 0 high, 0 moderate, 1 low
- `yarn audit` exits with non-zero code - FAILURE
- `yarn audit --filter low` exits with non-zero code - FAILURE
- `yarn audit --filter moderate` exits with code `0` - SUCCESS
- `yarn audit --filter high` exits with code `0` - SUCCESS

Currently, if we want to achieve the same result, we have to run something like:

```
/bin/bash -c 'yarn audit; [[ $? -ge $SEVERITY ]] && exit 1 || exit 0'
```

**Describe the drawbacks of your solution**
This feature is not changing any existing behaviour and it won't impact on any currently existing implementations being used.

**Describe alternatives you've considered**
No other solutions considered.

**Additional context**
Raising this issue of the back of https://github.com/yarnpkg/yarn/issues/7386.

**Comment by cyberfox1** [comment]
Any progress on this?
