### ISSUE TITLE
[Bug] Can't require yarn-resolved path (PNP)

### ISSUE THREAD

**Issue by samtstern** [yarnpkg/berry#1467]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Requiring a module like this throws an error:
```js
require(require.resolve(<name>, { paths: [ <working_directory> ] }))
```

**To Reproduce**

<details>
  <summary>Reproduction</summary>

With yarn2 and PNP `require.resolve()` returns some funny paths, which I know is expected:

```js
function requireLocal(frb: FunctionsRuntimeBundle, name: string) {
  const path = require.resolve(name, { paths: [frb.cwd] });
  console.log(`requireLocal: ${path}`);
  return require(path);
}
```

I get the following error:
```
>  requireLocal: /Users/samstern/Scratch/firebase-functions-yarn-2/.yarn/$$virtual/firebase-functions-virtual-5ee8699f73/0/cache/firebase-functions-npm-3.7.0-5eb6b20443-1.zip/node_modules/firebase-functions/lib/index.js
⚠  functions: Cannot find module '/Users/samstern/Scratch/firebase-functions-yarn-2/.yarn/$$virtual/firebase-functions-virtual-5ee8699f73/0/cache/firebase-functions-npm-3.7.0-5eb6b20443-1.zip/node_modules/firebase-functions/lib/index.js'
Require stack:
```

Seems like `require.resolve` is working fine but then `require` on the resulting path causes an error.  I need to require this specific path to make sure I am picking up the dependency from the developer's functions directory.

</details>

**Screenshots**

N/A

**Environment if relevant (please complete the following information):**

 - OS: macOS
 - Node version: v10.19.0
 - Yarn version: 2.0.0-rc.27

**Additional context**

N/A

**Comment by arcanis** [comment]
Please make a Sherlock repro; this case is covered by tests and supposed to work, so there's something particular about your environment.

**Comment by samtstern** [comment]
Wow sherlock is ... not fun.  But you're right I can't reproduce in that environment.  Leaving this here for myself while I go off and try to spot the difference in the Firebase emulator.

[Playground](https://yarnpkg.com/playground?code=Y29uc3QgZnMgPSByZXF1aXJlKCdmcycpOwoKZnMud3JpdGVGaWxlU3luYygnbXlzY3JpcHQuanMnLCBgCiAgY29uc3QgcmVzb2x1dGlvbiA9IHJlcXVpcmUucmVzb2x2ZSgnZmlyZWJhc2UtZnVuY3Rpb25zJywgeyBwYXRoczogWyIuIl0gfSk7CiAgY29uc3QgZnVuY3Rpb25zID0gcmVxdWlyZShyZXNvbHV0aW9uKTsKICBjb25zb2xlLmxvZyhyZXNvbHV0aW9uKTsKYCkKCmFzeW5jIGZ1bmN0aW9uIHJlcHJvKCkgewogICAgYXdhaXQgcGFja2FnZUpzb25BbmRJbnN0YWxsKHsKICAgICAgICBkZXBlbmRlbmNpZXM6IHsKICAgICAgICAgICAgW2BmaXJlYmFzZS1mdW5jdGlvbnNgXTogYF4zLjYuMWAsCiAgICAgICAgICAgIFtgZmlyZWJhc2UtYWRtaW5gXTogYF44LjkuMGAsCiAgICAgICAgfQogICAgfSk7CiAgICAvLyBjb25zdCBwYXRoID0gcmVxdWlyZS5yZXNvbHZlKCdmaXJlYmFzZS1mdW5jdGlvbnMnLCB7IHBhdGhzOiBbJy4nXSB9KTsKICAgIC8vIGNvbnN0IHBhdGggPSByZXF1aXJlLnJlc29sdmUoImZpcmViYXNlLWZ1bmN0aW9ucyIpOwoKICAgIGNvbnN0IHJlcyA9IGF3YWl0IHlhcm4oJ25vZGUnLCAnLi9teXNjcmlwdC5qcycpOwogICAgY29uc29sZS5sb2cocmVzKTsKCiAgICBleHBlY3QocmVzKS50b0NvbnRhaW4oImJhbmFuYSIpCgp9Cgphd2FpdCByZXBybygp)

**Comment by arcanis** [comment]
If that can help, `Cannot find module` suggests that the call goes to the native Node resolution (our resolver throws different error messages with more details). Perhaps the require call, in your case, somehow occurs outside of the Yarn-managed context?

**Comment by samtstern** [comment]
That is helpful!  I agree I am somehow getting native Node resolution.  I am in a reallllly weird situation now:

```
  console.log("PNP", process.versions.pnp);  // <-- Works prints 3
  const pnpapi = require('pnpapi');  // <-- Fails
```

I am running `node` in a subprocess pointing at a JS file (`functionsEmulatorRuntime`) and manually passing the `--require` flag with the user's `.pnp.js` file:
```
/Users/samstern/.nvm/versions/node/v10.19.0/bin/node \
  --require=/Users/samstern/Scratch/firebase-functions-yarn-2/.pnp.js \
  /Users/samstern/Projects/firebase-tools/lib/emulator/functionsEmulatorRuntime
```

**Comment by arcanis** [comment]
Is `<firebase-tools installation path>` inside the project you installed with Yarn? Something to know is that Yarn tries its best to satisfy multi-tree scenarios (when a file from a project requires a file from another one), which I think is what happens here: the file being executed isn't part of the project managed through PnP, so it cannot access the `pnpapi` module. However, since `process.versions.pnp` is a global, it still sees it (we cannot "hide" it from specific modules only).

I believe it should work better if you try something like this:

```ts
const pnpapi = require(require.resolve('pnpapi', {
  paths: [userProjectPath],
}));
```

In this situation, the resolution is done "on behalf" of the user project (thanks to `paths`), so the PnP runtime should understand what to load.

**Comment by samtstern** [comment]
@arcanis aha!  That worked.  I think that really sets me on a path to where I want to go.  Thank you for your patience and help.

**Comment by samtstern** [comment]
Actually one last thing:
```js
    const pnpapi = require(require.resolve('pnpapi', {
      paths: [frb.cwd]
    }));

    console.log("pnpapi");
    console.log(pnpapi);

    const resolved = pnpapi.resolveRequest(`firebase-functions`, frb.cwd);
    console.log(resolved);
    require(resolved); // <-- still fails here
```

It looks like I need `createRequire` but I can't get this bit to work:
```js
const {createRequire, findPnpApi} = require(`module`);
```

Even when I do this
```js
const {createRequire, findPnpApi} = require(require.resolve('module', { paths: [frb.cwd] }));
```

I still can't get `createRequire` to be defined.  Is there some way to work my way there from `pnpapi`?

**Comment by merceyz** [comment]
`createRequire` was added in Node v12.2.0, you can use `createRequireFromPath` as a fallback which was added in v10.12.0, if you need to support even earlier versions you can use something like this https://github.com/cstoddart/gatsby/blob/ef323e03d4e52094f9f7975c1bbaf12bc324a204/packages/gatsby/src/utils/create-require-from-path.js

**Comment by paul-soporan** [comment]
The Nuxt folks put `createRequire` (+ polyfills) into the [`create-require`](https://yarnpkg.com/package/create-require) module, so you can just use that.

**Comment by samtstern** [comment]
Oooooh I thought `createRequire` was something that `pnp` was patching on to `module` just like how it's modifying the base `fs` package.  I didn't even consider that it might be built in to Node.

**Comment by samtstern** [comment]
And it's all finally working.  For the curious:
https://github.com/firebase/firebase-tools/pull/2356

Thanks again to everyone who pointed me in the right direction(s).
