### ISSUE TITLE
[Bug] Crash rendering progressbar on certain terminals

### ISSUE THREAD

**Issue by stephank** [yarnpkg/berry#1479]
- [x] I'd be willing to implement a fix

**Describe the bug**

`stdout.columns` can be undefined even with `isTTY`, causing `StreamReport` to crash in a call to `String.repeat` while rendering the progressbar.

In very small terminals, `maxWidth` in `StreamReport` may also become negative, causing a similar crash.

**To Reproduce**

Easiest repro is to resize a terminal window to less than 12 characters wide. My own repro is from running Yarn within a [Nix](https://nixos.org) builder, which apparently doesn't report a width at all (undefined).

No idea how to reproduce this in Sherlock, or how to write a StreamReport test. (There don't seem to be existing StreamReport tests. I need to create a Configuration apparently, which just seems like I'll be copy-pasting from other unit tests? Is that bad?)

**Screenshots**

This is the result of running in a very narrow terminal, then scaling it back up to view the error message:

<img width="920" alt="Screenshot 2020-06-14 at 11 01 00" src="https://user-images.githubusercontent.com/89950/84589408-98974300-ae2e-11ea-90c3-ab2c753272f6.png">

**Environment:**

 - OS: macOS 10.15.5
 - Node version 14.4.0
 - Yarn version 2.0.0-rc.34

**Additional context**

Maybe something like this will fix Yarn at least? https://github.com/yarnpkg/berry/compare/master...stephank:fix-nix-build

For Nix, this is easily worked around by setting CI=1, and I'm not sure if maybe the solution there is to simply declare Nix as a CI environment. Without CI=1 and fixing this specific crash only, output is still ugly, because the Nix builder also logs separate progressbar lines for every update.

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/1485
