### ISSUE TITLE
[Bug] missing types in workspace tho they are installed in vscode

### ISSUE THREAD

**Issue by chrisands** [yarnpkg/berry#1488]
- [ ] I'd be willing to implement a fix

**Describe the bug**

VSCode show error that `@types/node` types are missing, but they installed as devDependency in workspace.

```
Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i @types/node`.ts(2580)
```

**To Reproduce**

1. Create a project with yarn workspaces
2. Install `@types/node` to one of a workspaces
3. Use `require` in workspace.
4. ...
5. Get an error in vscode

[Example repository 
](https://github.com/chrisands/issue-berry-1488)
**Environment if relevant (please complete the following information):**

 - OS: OSX 10.15.5 (19F101
 - Node version 14.4.0
 - Yarn version 2.0.0-rc.35

**Comment by chrisands** [comment]
Not if this `@yarnpkg/pnpify` or `vscode`/`typescript` issue.

**Comment by merceyz** [comment]
Pretty sure this is you not having VSCode configured to support PnP. This page explains how to do that https://yarnpkg.com/advanced/editor-sdks

If i'm wrong, please let us know and we'll re-open.

**Comment by chrisands** [comment]
@merceyz I did configuration using this guide. Please check the repository I attached.

**Comment by merceyz** [comment]
I did, which is how I got to my conclusion. Your repository doesn't contain a .vscode folder so I assume you haven't setup the VSCode config.

**Comment by chrisands** [comment]
I didn't commit `.vscode` files (they are globally ignored), updated repository.

**Comment by merceyz** [comment]
Confirmed, as a workaround you can add `@types/node` to the root.

**Comment by rizkyramadhan** [comment]
I also got this error,

I already did:

> Pretty sure this is you not having VSCode configured to support PnP. This page explains how to do that https://yarnpkg.com/advanced/editor-sdks
> 
> If i'm wrong, please let us know and we'll re-open.


And also this:

> Confirmed, as a workaround you can add `@types/node` to the root.

**Comment by rizkyramadhan** [comment]
The only thing that worked are this: 

![image](https://user-images.githubusercontent.com/126301/96139805-67886580-0f29-11eb-8a38-90fadc99ea12.png)


When I click Install all missing packages, vscode creates node_modules under my workspace, and then vscode recognize the typings. But that node_modules are gone when I update my dependency using `yarn`.

So....

**Comment by merceyz** [comment]
Looked into it again now and the root of the issue is that you don't have a `tsconfig.json` in your `packages/main` workspace, this causes typescript to ask for all `@types/` packages from the root where you don't have any so it can't find any. 

So there are two solutions here, either add `@types/node` to the project root as I mentioned in https://github.com/yarnpkg/berry/issues/1488#issuecomment-645996937, or add a `tsconfig.json` to `packages/main`
