### ISSUE TITLE
Change our default branch from master to something like main ?

### ISSUE THREAD

**Issue by NotMoni** [yarnpkg/berry#1496]

**Comment by rpearce** [comment]
Relevant:
* _Replacing master with main in Github _ https://dev.to/afrodevgirl/replacing-master-with-main-in-github-2fjf
* _GitHub abandons 'master' term to avoid slavery row_ https://www.bbc.com/news/technology-53050955
* _GitHub to replace "master" with alternative term to avoid slavery references_ https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

**Comment by NotMoni** [comment]
+ Lots of other projects are making the move such as moment.js and more.

**Comment by arcanis** [comment]
While I understand the endeavour in general, and I'm not attached to `master` in general (I'm myself experimenting with it on a separate repo, to see how fast muscular memory kicks in), we'll not be doing this here for technical reasons.

Both `yarn set version` and `yarn plugin import` are hardcoded to retrieve versions and plugins from our repository, and in particular from the master branch. In this situation we would still need to keep it on top of having a separate main branch, and they'd have to be kept in sync at all times. While not impossible, I don't think it provides enough value to be worth the operational complexity.
