### ISSUE TITLE
[Bug] $$virtual karma unit tests

### ISSUE THREAD

**Issue by acls** [yarnpkg/berry#1508]
- [X] I'd be willing to implement a fix

**Describe the bug**

After upgrading to the latest yarn berry and updating my package dependencies my karma unit tests no longer run. The issue seems to be caused by #630 which changed `virtual` to `$$virtual`.

For some reason karma changes `$$virtual` to `$virtual`. Possibly some type of escaping bug/feature. This seems like a bug in karma, but it works using node_modules, so I would think yarn would want to correct it.

The packageLocation in the .pnp.js file is:
.yarn/$$virtual/karma-jasmine-virtual-d5e825a809/0/cache/karma-jasmine-npm-3.3.1-3b2922b99a-5eda66e5ce.zip/node_modules/karma-jasmine/

But karma ends up requesting:
.yarn/$virtual/karma-jasmine-virtual-d5e825a809/0/cache/karma-jasmine-npm-3.3.1-3b2922b99a-5eda66e5ce.zip/node_modules/karma-jasmine/lib/boot.js

**To Reproduce**

I created this [repo](https://github.com/acls/karma-berry-virtual) that demonstrates the issue.

**Environment if relevant (please complete the following information):**

 - OS: Linux
 - Node version 10.21.0
 - Yarn version 2.0.0-rc.36

**Additional context**

Previous version was 2.0.0-rc.6

**Comment by merceyz** [comment]
Upstream issue: https://github.com/karma-runner/karma/issues/3530
Upstream fix: https://github.com/karma-runner/karma/pull/3531

**Comment by acls** [comment]
That was quick. Thanks @merceyz!
