### ISSUE TITLE
[Feature] Optional Transitive Binary Hoisting

### ISSUE THREAD

**Issue by darthtrevino** [yarnpkg/berry#1518]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Yarn v2 does not hoist binaries from transitive dependencies. Because of this, shell-based utility packages cannot use Yarn v2 without either ejecting out of plug-n-play, pushing the build system into JavaScript, or switching to slower (and flakier) dynamic utilities like `npx` or `yarn dlx`.

My team has a [shell-script based centralized build system](https://github.com/microsoft/essex-alpha-build-infra) that depends on transitive binary hoisting.

[My Library] --> [Build System] --> [eslint, babel, webpack, etc..]
`buildsys lint`     `spawn('eslint', '...)`

**Describe the solution you'd like**

Binaries for direct dependencies are already hoisted (e.g. installing `eslint` as a dependency makes it available in the shell). It would be nice to have an option to hoist binaries from transitive dependencies, or if this option .

```yaml
binhoist: <local (default> | <transitive>
```

**Describe the drawbacks of your solution**

If a client declared the same dependency (e.g. eslint), or if there were multiple packages that used the same shell tooling, there could be conflicts that would necessitate using resolutions. 

**Describe alternatives you've considered**

Some alternatives were briefly discussed in the problem statement.

**Additional context**

**Comment by arcanis** [comment]
Transitive hoisting is unpredictable, so we won't do it (for example, consider the case where you depend on A and B, which both depend on different version of C. Which one would be available at the top?).

That being said, we have a section explaining how to safely share scripts between all your workspaces, which you can leverage to declare your workflows in a single "tooling" workspace, and reuse them across the whole project:

https://yarnpkg.com/advanced/qa#how-to-share-scripts-between-workspaces

**Comment by darthtrevino** [comment]
That's a reasonable solution for a single project, but it doesn't really scale to several repositories. I think ultimately this means my team can't reasonably use Yarn v2 yet until we invest heavily in refactoring our build system from using shell scripts to JS APIs. 

I hope you'll keep considering solutions to this - perhaps JS binaries like `eslint` can have their dependencies sandboxed and they're not affected by ambient dependencies.

**Comment by merceyz** [comment]
> can't reasonably use Yarn v2 yet until we invest heavily in refactoring our build system from using shell scripts to JS APIs. 

You can always use the node_modules linker, then flip the switch to pnp when you're done with the refactoring / when you find a solution

**Comment by darthtrevino** [comment]
That's fair - and it's probably worth a shot

**Comment by merceyz** [comment]
I removed my comment because I thought I misunderstood the issue, but since it seems I didn't i'll add it again:

> can't reasonably use Yarn v2 yet until we invest heavily in refactoring
 our build system from using shell scripts to JS APIs.

 You can always use the node_modules linker, then flip the switch to pnp
 when you're done with the refactoring / when you find a solution

**Comment by darthtrevino** [comment]
No worries, I think what you're describing can work as a stopgap. It means none of our projects using the shared build system can use PnP, but they would gain the benefit of more deterministic module resolution. 

Thinking about this more: 
Something like `yarn dlx` could work, but it would need to be independently deployed from Yarn so I could use it to sandbox commands in projects still using v1. I would also need a way of augmenting the modules that a command could depend on. 

For example, the `pretty-quick` tool can be run in npx with the following:

`npx -p prettier -p pretty-quick pretty-quick`  <-- prettier is necessary in the scope of this command

I know dlx can use a separate package for the binary, but it would be cool if it could describe a small sandbox

Perhaps

## Basic Sandbox
`dlx --packages prettier,pretty-quick pretty-quick`

## Sandbox with augmentation
`dlx --sandbox lint-sandbox.json --packages eslint-config-derpco eslint`

```json
{
  "dependencies": {  
      "eslint": "...",
      "eslint-config-airbnb-or-whatever": "...",
      "@typescript-eslint/parser": "..."
  }
}
```

**Comment by darthtrevino** [comment]
Thinking this through more, `dlx` would also be an API you could use to write these kinds of things and avoid needing to have dlx hoisted.

```
import { dlx } from 'dlx'

const execution = await dlx('eslint', { dependencies: [...] })
```

**Comment by darthtrevino** [comment]
@arcanis are you open to these kinds of features in `dlx` as a separate feature request issue?
