### ISSUE TITLE
[Bug] Unable to install @babel/core

### ISSUE THREAD

**Issue by Cospoi** [yarnpkg/berry#1525]
# This file contains the result of Yarn building a package (root-workspace-0b6124@workspace:.)
# Script name: postinstall

@babel/register tried to access @babel/core (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: @babel/core (via "@babel/core")
Required by: @babel/register@virtual:94c3729aec53d946ebe3848f9f7433d01049872f60b24a1884a2ee4e43763715fb4a39a7ee69c8752cabdc72c134f58c7286258408579227f558fcbd94d83bfc#npm:7.9.0 (via /C:/Users/Axx/Desktop/dd/.yarn/$$virtual/@babel-register-virtual-046c46bda5/0/cache/@babel-register-npm-7.9.0-76e7cdb189-8d1924e084.zip/node_modules/@babel/register/lib/)
Ancestor breaking the chain: @umijs/utils@npm:3.2.5

Require stack:
- C:\Users\Axx\Desktop\dd\.yarn\$$virtual\@babel-register-virtual-046c46bda5\0\cache\@babel-register-npm-7.9.0-76e7cdb189-8d1924e084.zip\node_modules\@babel\register\lib\cache.js
- C:\Users\Axx\Desktop\dd\.yarn\$$virtual\@babel-register-virtual-046c46bda5\0\cache\@babel-register-npm-7.9.0-76e7cdb189-8d1924e084.zip\node_modules\@babel\register\lib\node.js
- C:\Users\Axx\Desktop\dd\.yarn\$$virtual\@babel-register-virtual-046c46bda5\0\cache\@babel-register-npm-7.9.0-76e7cdb189-8d1924e084.zip\node_modules\@babel\register\lib\index.js
- C:\Users\Axx\Desktop\dd\.yarn\cache\@umijs-utils-npm-3.2.5-94c3729aec-f5524cc8ff.zip\node_modules\@umijs\utils\lib\BabelRegister\BabelRegister.js
- C:\Users\Axx\Desktop\dd\.yarn\cache\@umijs-utils-npm-3.2.5-94c3729aec-f5524cc8ff.zip\node_modules\@umijs\utils\lib\index.js
- C:\Users\Axx\Desktop\dd\.yarn\cache\@umijs-core-npm-3.2.5-c5aa30fe60-f42c507aa3.zip\node_modules\@umijs\core\lib\Config\Config.js
- C:\Users\Axx\Desktop\dd\.yarn\cache\@umijs-core-npm-3.2.5-c5aa30fe60-f42c507aa3.zip\node_modules\@umijs\core\lib\index.js
- C:\Users\Axx\Desktop\dd\.yarn\cache\umi-npm-3.2.5-60e0405020-3a79652ce9.zip\node_modules\umi\lib\ServiceWithBuiltIn.js
- C:\Users\Axx\Desktop\dd\.yarn\cache\umi-npm-3.2.5-60e0405020-3a79652ce9.zip\node_modules\umi\lib\cli.js
- C:\Users\Axx\Desktop\dd\.yarn\cache\umi-npm-3.2.5-60e0405020-3a79652ce9.zip\node_modules\umi\bin\umi.js
Error: @babel/register tried to access @babel/core (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: @babel/core (via "@babel/core")
Required by: @babel/register@virtual:94c3729aec53d946ebe3848f9f7433d01049872f60b24a1884a2ee4e43763715fb4a39a7ee69c8752cabdc72c134f58c7286258408579227f558fcbd94d83bfc#npm:7.9.0 (via /C:/Users/Axx/Desktop/dd/.yarn/$$virtual/@babel-register-virtual-046c46bda5/0/cache/@babel-register-npm-7.9.0-76e7cdb189-8d1924e084.zip/node_modules/@babel/register/lib/)
Ancestor breaking the chain: @umijs/utils@npm:3.2.5

Require stack:
- C:\Users\Axx\Desktop\dd\.yarn\$$virtual\@babel-register-virtual-046c46bda5\0\cache\@babel-register-npm-7.9.0-76e7cdb189-8d1924e084.zip\node_modules\@babel\register\lib\cache.js
- C:\Users\Axx\Desktop\dd\.yarn\$$virtual\@babel-register-virtual-046c46bda5\0\cache\@babel-register-npm-7.9.0-76e7cdb189-8d1924e084.zip\node_modules\@babel\register\lib\node.js
- C:\Users\Axx\Desktop\dd\.yarn\$$virtual\@babel-register-virtual-046c46bda5\0\cache\@babel-register-npm-7.9.0-76e7cdb189-8d1924e084.zip\node_modules\@babel\register\lib\index.js
- C:\Users\Axx\Desktop\dd\.yarn\cache\@umijs-utils-npm-3.2.5-94c3729aec-f5524cc8ff.zip\node_modules\@umijs\utils\lib\BabelRegister\BabelRegister.js
- C:\Users\Axx\Desktop\dd\.yarn\cache\@umijs-utils-npm-3.2.5-94c3729aec-f5524cc8ff.zip\node_modules\@umijs\utils\lib\index.js
- C:\Users\Axx\Desktop\dd\.yarn\cache\@umijs-core-npm-3.2.5-c5aa30fe60-f42c507aa3.zip\node_modules\@umijs\core\lib\Config\Config.js
- C:\Users\Axx\Desktop\dd\.yarn\cache\@umijs-core-npm-3.2.5-c5aa30fe60-f42c507aa3.zip\node_modules\@umijs\core\lib\index.js
- C:\Users\Axx\Desktop\dd\.yarn\cache\umi-npm-3.2.5-60e0405020-3a79652ce9.zip\node_modules\umi\lib\ServiceWithBuiltIn.js
- C:\Users\Axx\Desktop\dd\.yarn\cache\umi-npm-3.2.5-60e0405020-3a79652ce9.zip\node_modules\umi\lib\cli.js
- C:\Users\Axx\Desktop\dd\.yarn\cache\umi-npm-3.2.5-60e0405020-3a79652ce9.zip\node_modules\umi\bin\umi.js
    at internalTools_makeError (C:\Users\Axx\Desktop\dd\.pnp.js:27718:34)
    at resolveToUnqualified (C:\Users\Axx\Desktop\dd\.pnp.js:28627:23)
    at resolveRequest (C:\Users\Axx\Desktop\dd\.pnp.js:28730:29)
    at Object.resolveRequest (C:\Users\Axx\Desktop\dd\.pnp.js:28796:26)
    at Function.external_module_.Module._resolveFilename (C:\Users\Axx\Desktop\dd\.pnp.js:27950:34)
    at Function.external_module_.Module._load (C:\Users\Axx\Desktop\dd\.pnp.js:27814:51)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Axx\Desktop\dd\.yarn\$$virtual\@babel-register-virtual-046c46bda5\0\cache\@babel-register-npm-7.9.0-76e7cdb189-8d1924e084.zip\node_modules\@babel\register\lib\cache.js:19:37)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)

**Comment by paul-soporan** [comment]
https://dev.to/arcanis/implicit-transitive-peer-dependencies-ed0

`@babel/register` has a peer dependency on `@babel/core`, but `@umijs/utils` depends on `@babel/register` without satisfying its peer dependency. You probably want to forward `@babel/core` (by adding it as a peer dependency to `@umijs/utils`), in case the consumer of `@umijs/utils` should provide it. Otherwise, it can be marked as a regular dependency.
You can use `packageExtensions` to fix this issue:
```yml
packageExtensions:
  '@umijs/utils@*':
    peerDependencies:
      '@babel/core': '*'
```

**Comment by Cospoi** [comment]
@paul-soporan 
There are more errors.
Or is my configuration incorrect, please advise.

The following is my configuration and error message, prompting me to install these packages, but these are not packages.

you can use `yarn create @umijs/umi-app` create this project,There is no problem using yarn1.x.


{
  "private": true,
  "scripts": {
    "start": "umi dev",
    "build": "umi build",
    "postinstall": "umi generate tmp",
    "prettier": "prettier --write '**/*.{js,jsx,tsx,ts,less,md,json}'",
    "test": "umi-test",
    "test:coverage": "umi-test --coverage"
  },
  "gitHooks": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*.{js,jsx,less,md,json}": [
      "prettier --write"
    ],
    "*.ts?(x)": [
      "prettier --parser=typescript --write"
    ]
  },
  "dependencies": {
    "@ant-design/pro-layout": "^5.0.12",
    "@babel/core": "^7.10.3",
    "@umijs/babel-preset-umi": "^3.2.6",
    "@umijs/core": "^3.2.6",
    "@umijs/preset-react": "1.x",
    "@umijs/test": "^3.2.6",
    "@umijs/utils": "^3.2.6",
    "antd": "^4.3.5",
    "es5-imcompatible-versions": "^0.1.62",
    "lint-staged": "^10.0.7",
    "prettier": "^1.19.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "umi": "^3.2.6",
    "yorkie": "^2.0.0"
  },
  "peerDependencies": {
    "@babel/core": "^7.10.3",
    "@umijs/babel-preset-umi": "^3.2.6",
    "@umijs/core": "^3.2.6",
    "@umijs/utils": "^3.2.6",
    "es5-imcompatible-versions": "^0.1.62"
  }
}



× Webpack
  Compiled with some errors in 8.64s

 ERROR  Failed to compile with 33 errors                                                                              11:22:47 ├F10: PM┤
These dependencies were not found:

* @babel/runtime/helpers/esm/extends in ./.yarn/$$virtual/react-router-dom-virtual-a9697bdc7e/0/cache/react-router-dom-npm-5.1.2-7a7ab4790f-d09e55a5d5.zip/node_modules/react-router-dom/esm/react-router-dom.js, ./.yarn/$$virtual/react-router-virtual-5da67aa093/0/cache/react-router-npm-5.1.2-e30b2ba46e-534e43eaaf.zip/node_modules/react-router/esm/react-router.js and 1 other
* @babel/runtime/helpers/esm/inheritsLoose in ./.yarn/$$virtual/react-router-dom-virtual-a9697bdc7e/0/cache/react-router-dom-npm-5.1.2-7a7ab4790f-d09e55a5d5.zip/node_modules/react-router-dom/esm/react-router-dom.js, ./.yarn/$$virtual/react-router-virtual-5da67aa093/0/cache/react-router-npm-5.1.2-e30b2ba46e-534e43eaaf.zip/node_modules/react-router/esm/react-router.js
* @babel/runtime/helpers/esm/objectWithoutPropertiesLoose in ./.yarn/$$virtual/react-router-dom-virtual-a9697bdc7e/0/cache/react-router-dom-npm-5.1.2-7a7ab4790f-d09e55a5d5.zip/node_modules/react-router-dom/esm/react-router-dom.js, ./.yarn/$$virtual/react-router-virtual-5da67aa093/0/cache/react-router-npm-5.1.2-e30b2ba46e-534e43eaaf.zip/node_modules/react-router/esm/react-router.js
* @umijs/runtime in ./.yarn/cache/@umijs-renderer-react-npm-3.2.6-41892b071d-644f7ac92d.zip/node_modules/@umijs/renderer-react/dist/index.js
* history-with-query in ./.yarn/$$virtual/@umijs-runtime-virtual-2caf6b4b77/0/cache/@umijs-runtime-npm-3.2.6-2a3800cbea-9ba13ed70e.zip/node_modules/@umijs/runtime/dist/index.esm.js
* hoist-non-react-statics in ./.yarn/$$virtual/react-router-virtual-5da67aa093/0/cache/react-router-npm-5.1.2-e30b2ba46e-534e43eaaf.zip/node_modules/react-router/esm/react-router.js
* mini-create-react-context in ./.yarn/$$virtual/react-router-virtual-5da67aa093/0/cache/react-router-npm-5.1.2-e30b2ba46e-534e43eaaf.zip/node_modules/react-router/esm/react-router.js
* normalize-url in ./.yarn/$$virtual/mini-css-extract-plugin-virtual-f03bfe72dc/0/cache/mini-css-extract-plugin-npm-0.9.0-f8c8899095-654be33368.zip/node_modules/mini-css-extract-plugin/dist/hmr/hotModuleReplacement.js
* object-assign in ./.yarn/$$virtual/react-dom-virtual-ba024d53f9/0/cache/react-dom-npm-16.13.1-b0abd8a83a-fb5c3ad413.zip/node_modules/react-dom/cjs/react-dom.development.js, ./.yarn/cache/react-npm-16.13.1-56d408860d-13dcc9ba8a.zip/node_modules/react/cjs/react.development.js
* path-to-regexp in ./.yarn/$$virtual/react-router-virtual-5da67aa093/0/cache/react-router-npm-5.1.2-e30b2ba46e-534e43eaaf.zip/node_modules/react-router/esm/react-router.js
* prop-types in ./.yarn/$$virtual/react-router-dom-virtual-a9697bdc7e/0/cache/react-router-dom-npm-5.1.2-7a7ab4790f-d09e55a5d5.zip/node_modules/react-router-dom/esm/react-router-dom.js, ./.yarn/$$virtual/react-router-virtual-5da67aa093/0/cache/react-router-npm-5.1.2-e30b2ba46e-534e43eaaf.zip/node_modules/react-router/esm/react-router.js
* prop-types/checkPropTypes in ./.yarn/$$virtual/react-dom-virtual-ba024d53f9/0/cache/react-dom-npm-16.13.1-b0abd8a83a-fb5c3ad413.zip/node_modules/react-dom/cjs/react-dom.development.js, ./.yarn/cache/react-npm-16.13.1-56d408860d-13dcc9ba8a.zip/node_modules/react/cjs/react.development.js
* query-string in ./.yarn/cache/history-with-query-npm-4.10.3-ae214aa1bd-019ec0ba26.zip/node_modules/history-with-query/esm/history.js  
* react-is in ./.yarn/$$virtual/react-router-virtual-5da67aa093/0/cache/react-router-npm-5.1.2-e30b2ba46e-534e43eaaf.zip/node_modules/react-router/esm/react-router.js
* react-router-config in ./.yarn/cache/@umijs-renderer-react-npm-3.2.6-41892b071d-644f7ac92d.zip/node_modules/@umijs/renderer-react/dist/index.js
* resolve-pathname in ./.yarn/cache/history-with-query-npm-4.10.3-ae214aa1bd-019ec0ba26.zip/node_modules/history-with-query/esm/history.js
* scheduler in ./.yarn/$$virtual/react-dom-virtual-ba024d53f9/0/cache/react-dom-npm-16.13.1-b0abd8a83a-fb5c3ad413.zip/node_modules/react-dom/cjs/react-dom.development.js
* scheduler/tracing in ./.yarn/$$virtual/react-dom-virtual-ba024d53f9/0/cache/react-dom-npm-16.13.1-b0abd8a83a-fb5c3ad413.zip/node_modules/react-dom/cjs/react-dom.development.js
* tiny-invariant in ./.yarn/$$virtual/react-router-dom-virtual-a9697bdc7e/0/cache/react-router-dom-npm-5.1.2-7a7ab4790f-d09e55a5d5.zip/node_modules/react-router-dom/esm/react-router-dom.js, ./.yarn/$$virtual/react-router-virtual-5da67aa093/0/cache/react-router-npm-5.1.2-e30b2ba46e-534e43eaaf.zip/node_modules/react-router/esm/react-router.js and 1 other
* tiny-warning in ./.yarn/$$virtual/react-router-dom-virtual-a9697bdc7e/0/cache/react-router-dom-npm-5.1.2-7a7ab4790f-d09e55a5d5.zip/node_modules/react-router-dom/esm/react-router-dom.js, ./.yarn/$$virtual/react-router-virtual-5da67aa093/0/cache/react-router-npm-5.1.2-e30b2ba46e-534e43eaaf.zip/node_modules/react-router/esm/react-router.js and 1 other
* use-subscription in ./.yarn/$$virtual/@umijs-runtime-virtual-2caf6b4b77/0/cache/@umijs-runtime-npm-3.2.6-2a3800cbea-9ba13ed70e.zip/node_modules/@umijs/runtime/dist/index.esm.js
* value-equal in ./.yarn/cache/history-with-query-npm-4.10.3-ae214aa1bd-019ec0ba26.zip/node_modules/history-with-query/esm/history.js

To install them, you can run: npm install --save @babel/runtime/helpers/esm/extends @babel/runtime/helpers/esm/inheritsLoose @babel/runtime/helpers/esm/objectWithoutPropertiesLoose @umijs/runtime history-with-query hoist-non-react-statics mini-create-react-context normalize-url object-assign path-to-regexp prop-types prop-types/checkPropTypes query-string react-is react-router-config resolve-pathname scheduler scheduler/tracing tiny-invariant tiny-warning use-subscription value-equal
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
