### ISSUE TITLE
Confusing behavior when using different nodeLinker in workspaces

### ISSUE THREAD

**Issue by dilame** [yarnpkg/berry#1526]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Not sure if it's a bug, but it's definitely confusing.

Let's pretend I have workspaces with git submodules. 
I have top-level `.yarnrc.yml`, and child (git-submodule)  `.yarnrc.yml`. 
At the top level I use PnP, but git-submodule (being workspace at the same time) `.yarnrc.yml` declares `nodeLinker: node-modules`.
And when I run `yarn install` - at the top level I got `pnp.js`, but child workspace uses node-modules.

I expect yarn to respect the only root `.yarnrc.yml`, because I'm the root owner, but workspaces could be third-party provided.

**Comment by arcanis** [comment]
The linker is global to the project (as are all the settings, in fact), they can't be different per-project. Keeping yarnrc files within workspaces (rather than just the root) is likely a bad pattern.

**Comment by dilame** [comment]
Unfortunately, i am not the owner of git-submodule, so i cant remove nested yarnrc.

Could you, please, advice on how to work with workspaces in docker? 
The problem is that even if I move my root `yarn.lock` that contains all the dependencies including nested workspace dependencies, yarn doesn't respect it until I `COPY` all the `package.json` files of all workspaces. Coping it manually is very annoying because I got 10+ workspaces. If I copy the whole project then I lose docker caching mechanism. I'm unable to use PnP (i swear i tried hard) because of inconsistency. 
Would be nice if yarn could build my `node_modules` based only on `yarn.lock`
is it possible?
Or any other advice on how to work with workspaces and docker?

**Comment by Fibs7000** [comment]
@arcanis I don't agree that this is a bad pattern... like i had recently a project where there is one ui workspace which required the node-modules linker... all the other workspaces where fine with the pnp linker which was a huuuuuge time saver!
