### ISSUE TITLE
[Feature] Automate NPM Login

### ISSUE THREAD

**Issue by grrizzly** [yarnpkg/berry#1537]
- [X] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

I am trying to publish packages to a private registry using yarn 2 as part of our CI/CD process. 

Our current pipeline scripts use [Basic Auth from Artifactory](https://www.jfrog.com/confluence/display/JFROG/npm+Registry#npmRegistry-UsingBasicAuthentication)  to get credentials to write into an `.npmrc` file. 

This gets picked up in yarn 1 / npm, and is able to be used as the auth mechanism for publishing. However, it doesn't appear that `.npmrc` credentials are recognized when running `yarn npm publish` in Berry.

The only way I am able to make this work in yarn 2 is to do one of two things:

- Use regex to parse the auth token from [`npm-ci-login`](https://www.npmjs.com/package/npm-ci-login), then write it to a `~/.yarnrc.yml` file
- Use [`expect`](https://linux.die.net/man/1/expect) to automate `yarn npm login`

We are using the latter for now; however, this is less than ideal, and requires us to build a custom docker image with `expect` on it to drive our publishing step.

**Describe the solution you'd like**

We'd like to see environment variables or CLI params that can be used to set the login settings when running `yarn npm publish` or `yarn npm login`.

When `YARN_NPM_USERNAME`, `YARN_NPM_PASSWORD`, etc. are detected, these vars would be used to obtain a token via Berry that is then used as part of the publish or login process, obviating the need for a prompt.

Similarly, 

**Describe the drawbacks of your solution**

- Temporarily setting passwords via environment variables may not be considered acceptable security for some use cases
- Using environment variables to drive CLI behavior seems to stand in contrast to named parameters the yarn CLI typically supports

**Describe alternatives you've considered**

**Support .npmrc**

I don't have the backstory, but I'm guessing `.npmrc` isn't supported intentionally? Or maybe we're doing something wrong, and I'm missing the section in the docs where we can enable support?

**Setting token out-of-band**

We could try manually generating the token locally, and storing it as a secret in our CI system.

However, we would still have no known way to provide the token when running `yarn npm publish`.

**Comment by paul-soporan** [comment]
https://yarnpkg.com/configuration/yarnrc

We already offer quite a few options for this (should be enough for what you want to achieve):

- All simple configuration options can be set using `YARN_` environment variables (e.g. `YARN_NPM_AUTH_TOKEN`)
- `.yarnrc.yml` files also support environment variables - `npmAuthToken: ${MY_NPM_AUTH_TOKEN}`
- [`yarn config set`](https://yarnpkg.com/cli/config/set) updates the `.yarnrc.yml` file - `yarn config set npmAuthToken my-secret-token`

`.npmrc` files are ignored intentionally - see https://yarnpkg.com/advanced/migration#dont-use-npmrc-files
