### ISSUE TITLE
[Case Study] How to select node modules for an individual app deployment within a multi-app monorepo?

### ISSUE THREAD

**Issue by ivawzh** [yarnpkg/berry#1540]
Hi, firstly thanks for the great work at Yarn. 

As I understand, authors of Yarn V2 has mentioned a lot of times that you have no intentions to support `nohoist` in V2.

I wonder if there is an alternative way to support multi-app monorepo deployment, especially on node module management?

Say, a monorepo structure like 👇 

- package.json
- apps
  - web-service-a
    - package.json
    - Dockerfile
  - search-service-b
    - package.json
    - Dockerfile
  - admin-service-c
    - package.json
    - Dockerfile
  
- shared-modules
  - lib-a
    - package.json
  - lib-b
    - package.json

As a typical multi-app monorepo pattern, each of the apps is an individual deployable HTTP server. Monorepo benefits us for cross-API type checking, lib sharing, deployment order management, etc. Having this, an essential requirement is to deploy one app like `web-service-a` with only its required node modules. 

Previously, we were able to use Yarn V1 `"nohoist": ["**"]` to achieve node module separation during Docker image build-time. 

**Describe the goal of the investigation**

Investigate if Yarn V2 suits multi-app monorepos. 

**Investigation report**

Ideally, we would want Yarn V2 to be able to separate or assist us to separate node modules for individual packages. We don't mind using hoisting as it is at development-time. But for production deployment, we will need to avoid bloat node modules across apps and minimize Docker images' size.

I could be missing something from the doc. Any clues, corrections, or future plans sharing will be appreciated. Thanks in advanced =]

**Comment by larixer** [comment]
@ivawzh Yarn 2 has much better way to support multi-app workflow than fragile and confusing `nohoist`. You can use `yarn workspaces focus` command inside `apps/web-service-a` when you are going to install it inside Docker. This will install `apps/web-service-a` dependencies and shared modules dependencies it depends on and will NOT install `search-service-b` and `admin-service-c` dependencies. The subset of installed dependencies will be properly deduplicated and hoisted into root `node_modules` dir if you are using `node-modules` linker. This same `yarn workspaces focus` approach works for multi-app pnp projects as well. The relevant docs are here:
https://yarnpkg.com/cli/workspaces/focus

**Comment by ivawzh** [comment]
@larixer this, is, so, elegant! 🔥 

Regarding `node-module-linker`, I can't find much information except [your PR](https://github.com/yarnpkg/berry/pull/470) and [the doc for `yarn link`](https://yarnpkg.com/cli/link) (I am even not sure if `yarn link` is related to `node-module-linker`).

Is it going to be out-of-the-box? Do I need to explicitly install, configure, or invoke it?

**Comment by larixer** [comment]
@ivawzh 
The `node-modules` linker is available out of the box in Yarn 2. Here is the docs how to enable it
https://yarnpkg.com/advanced/migration#if-required-enable-the-node-modules-plugin
The purpose of `node-modules` linker is to allow easier migration from Yarn 1 to Yarn 2 for those projects that have find it difficult to migrate straight to default PnP linker.

**Comment by ivawzh** [comment]
I see. So `nodeLinker: node-modules` is effectively `nohoist: ["**"]` for the purpose of easy migration? 🤫

**Comment by larixer** [comment]
No, `nodeLinker: node-modules` responsible for installing into `node_modules`, the same as was in Yarn 1. The default mode for Yarn 2 is to install the dependencies into zip archives and creating `.pnp.js` map for resolving them strictly.

**Comment by ivawzh** [comment]
Got it. Thanks for answering everything nicely 🙂

**Comment by LvChengbin** [comment]
What if I want to remove unrelated workspaces at the same time?
