### ISSUE TITLE
Ambiguous import resolution

### ISSUE THREAD

**Issue by TheGrimSilence** [yarnpkg/berry#1541]
Is there a way to bypass the ambiguity error when using dynamic imports? I'm trying to have my application import a custom config script located in the root directory. for example ".example.ts", from ''packages/example-core/sources/requireConfig.ts". Yarn marks this ambiguous because it's not a dependency. I could read and eval the config, but I was wondering if there's a direct approach or if maybe Yarn could provider a special require() function from it's API so that it's not ambiguous and directly approved by Yarn's internals?

**Comment by TheGrimSilence** [comment]
Nevermind, I looked right over "pnpMode: 'loose'", but can Yarn be more programmatic by offering some of its internals? Say I wanted to resolve workspaces and their "main" fields, I currently have custom logic but since Yarn does this faster, it'd be nice if I could just `import { getWorkspaces} from '@yarnpkg/core'` for example.

**Comment by arcanis** [comment]
We want to avoid programs from relying too much on Yarn-specific API (precisely because we want to avoid vendor lock-in, even if we're the vendor in this case), so I'd rather recommend to use the standard `createRequire` function when possible. This will allow you to make require calls on behalf of any other file.

**Comment by TheGrimSilence** [comment]
I think I saw that when looking into how ESLint was able to do so under Yarn's watch. I'll settle for that implementation then.

**Comment by TheGrimSilence** [comment]
I fixed this by using some Yarn pnpify logic that isn't talked about anywhere in the documentation, probably because it's internal.

```typescript
import { createRequire, createRequireFromPath } from 'module';
require(path.resolve(__dirname, `../../../.pnp.js`)).setup();

const requireAbs = (createRequire || createRequireFromPath)(
  path.resolve(__dirname, './ProjectConfiguration.js')
);

async function requireConfig() {
   const rootDir = await this.findProjectCwd(process.cwd(), true);
   let reqConfig = requireAbs(`${rootDir}\\.noderalis.js`);

   if (reqConfig.default) {
     reqConfig = reqConfig.default;
   }

   return reqConfig;
}
```

This probably could be cleaner, but given I just catch on quick but never fully understand due to being too curios on a timeframe, I think it's fine. Compiling to JavaScript and calling everything like normal works perfectly, but I think this should be added to the FAQ on Yarn's website for future reference.
