### ISSUE TITLE
[Bug] "Maximum call stack size exceeded" in `findBrokenPeerDependencies` in `.pnp.js`

### ISSUE THREAD

**Issue by phryneas** [yarnpkg/berry#1549]
- [X] I'd be willing to implement a fix

**Describe the bug**

Somehow we have encountered the situation where the `traversal` method in `findBrokenPeerDependencies`  in `.pnp.js` keeps calling itself in an endless loop until the call stack limit is reached.

I've added a `console.log` in there and in our case it seems to be flipping in a circle between

> @nestjs/core
@nestjs/microservices
@nestjs/common
@nestjs/core
@nestjs/microservices
@nestjs/common
@nestjs/core
@nestjs/microservices

**To Reproduce**

I can provide our faulty `.yarn.pnp`, but I'd prefer to do so over a private channel. I am phryneas#4779 on Reactiflux.

**Fix** 

I could submit a PR like

```diff
 function findBrokenPeerDependencies(dependency, initialPackage) {
    const brokenPackages = new Map();

+    let visited = new Set();

    const traversal = currentPackage => {
+      const ident = currentPackage.name + currentPackage.reference;
+      if (visited.has(ident)) {
+        return;
+      }
+      visited.add(ident);

      const dependents = findPackageDependents(currentPackage);
```

that should prevent an endless loop there if that is welcome.

**Comment by arcanis** [comment]
> I could submit a PR like

That seems a good fix 👍 One suggestion is to use `JSON.stringify(currentPackage)` rather than concatenating them, but apart from that it should be all good.

**Comment by phryneas** [comment]
Okay, I'll open a PR then :)
