### ISSUE TITLE
[Bug] Unexpected behavior on TypeScript declaration emitting

### ISSUE THREAD

**Issue by cometkim** [yarnpkg/berry#1565]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Hi :wave: 

I'm using Yarn 2 workspace for [my personal libs](https://github.com/cometkim/cometjs).

After updating the library recently, type declarations went wrong.

This is what I expected:
```
  lib
├──   common.d.ts
├──   common.js
├──   common.js.map
├──   common.mjs
├──   common.mjs.map
├──   index.d.ts
├──   index.js
├──   index.js.map
├──   index.mjs
├──   index.mjs.map
├──   index.umd.js
├──   index.umd.js.map
├──   intrinsic.d.ts
├──   intrinsic.js
├──   intrinsic.js.map
├──   intrinsic.mjs
└──   intrinsic.mjs.map
```

And this is what actually I get:
```
  lib
├──   common.js
├──   common.js.map
├──   common.mjs
├──   common.mjs.map
├──   core
│  └──   src
│     ├──   common.d.ts
│     ├──   index.d.ts
│     ├──   map.d.ts
│     └──   option.d.ts
├──   index.js
├──   index.js.map
├──   index.mjs
├──   index.mjs.map
├──   index.umd.js
├──   index.umd.js.map
├──   intrinsic.js
├──   intrinsic.js.map
├──   intrinsic.mjs
├──   intrinsic.mjs.map
└──   react-utils
   └──   src
      ├──   common.d.ts
      ├──   index.d.ts
      └──   intrinsic.d.ts
```

**To Reproduce**

```bash
git clone https://github.com/cometkim/cometjs.git
cd cometjs/packages/react-utils
yarn build
```

This was working as I expected in tag `@cometjs/react-utils/0.0.3` and not working in master.

~~https://github.com/cometkim/cometjs/compare/@cometjs/react-utils/0.0.3...@cometjs/react-utils/0.1.0~~

~~I'm not sure which of these changes would be affected, but It is probably around the core package because it is reproduced in any packages with workspace dependencies but not in the core.~~

EDIT: I did try bisect to catch the exact point and I found the problem caused by https://github.com/cometkim/cometjs/commit/f079f901c69b3f3dc7dd0b39720d1489c801f44a

works fine in other package managers (Yarn 1, Pnpm).

**Environment if relevant (please complete the following information):**

 - OS: Ubuntu 18.04
 - Node version: v14.3.0
 - Yarn version v2.0.0-rc.33 and 2.1.1

**Comment by merceyz** [comment]
Reproduces at https://github.com/cometkim/cometjs/commit/32b756faac1f5ec918881eca26ae17eeac34e065 but not after https://github.com/cometkim/cometjs/commit/57fe1791c6db78057e145a8c6a4df39577afa3a8 so seems we've fixed this
