### ISSUE TITLE
Failed in Link step for @ampproject/toolbox-optimizer@npm:2.4.0

### ISSUE THREAD

**Issue by robertwt7** [yarnpkg/berry#1573]
**Describe the bug**

Hey Guys, today i decided to try yarn v2 on my new project with nextjs. However I can't seem to get it work, it was fine to install with yarn 1 and npm (node v12.18.1).

Its pretty easy to reproduce and i'm not really sure what is happening

**To Reproduce**

Follow this [template](https://github.com/vercel/next.js/tree/canary/examples/with-tailwindcss) to setup nextjs with tailwind

Follow [this](https://yarnpkg.com/getting-started/install) to upgrade yarn to v2 only for the project

```
yarn create next-app --example with-tailwindcss with-tailwindcss-app

cd with-tailwindcss
yarn policies set-version berry # below v1.22
yarn set version berry    
yarn
```

Then you got the error

**Screenshots**

<img width="1679" alt="Screen Shot 2020-07-10 at 9 00 09 pm" src="https://user-images.githubusercontent.com/15647967/87147938-d9309200-c2f0-11ea-808a-162ef04df8ab.png">

<img width="1677" alt="Screen Shot 2020-07-10 at 9 02 01 pm" src="https://user-images.githubusercontent.com/15647967/87147968-e483bd80-c2f0-11ea-99e2-c584cb587d2a.png">

**Environment if relevant (please complete the following information):**

 - OS: OSX 10.15.5
 - Node version 12.18.1
 - Yarn version 2.1.1

Can anyone please help?

I'm pretty excited in using yarn v2

Thanks everyone

**Comment by merceyz** [comment]
It has been fixed in the canary version of next
