### ISSUE TITLE
[Bug] Terminate batch job (Y/N)?

### ISSUE THREAD

**Issue by skywalker512** [yarnpkg/berry#1592]
- [ ] I'd be willing to implement a fix

**Describe the bug**

”Terminate batch jobs (Y / N)“ will be encountered multiple times when ending a script on Microsoft Windows. but npm run can end immediately

**To Reproduce**

```
$ yarn create vite-app <project-name>
$ cd <project-name>
$ yarn
$ yarn dev
```

ctrl+c

```
❯ yarn dev
vite v1.0.0-beta.11

  Dev server running at:
  > Local:    http://localhost:3000/

^CTerminate batch job (Y/N)? Y
Terminate batch job (Y/N)? Y
```

**Environment if relevant (please complete the following information):**

 - OS: Windows
 - Node version: v14.4.0
 - Yarn version 2.1.1

**Additional context**

**Comment by merceyz** [comment]
Yarn waits for the underlying process to exit gracefully instead of killing it. This is to allow it to clean up its resources, if it doesn't exit by itself you can force it by replying yes to that prompt

**Comment by merceyz** [comment]
Reopening as this can be improved for scripts run by Yarn

**Comment by arcanis** [comment]
Related: https://github.com/microsoft/terminal/issues/217
