### ISSUE TITLE
[Bug] RequestError: 140476416780160:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record

### ISSUE THREAD

**Issue by numToStr** [yarnpkg/berry#1600]
**Describe the bug**
So today I upgrade a project from v1.22.4 to v2.1.1 and enabled the `node_modules` linker in the `.yarnrc.yml` which was autogenerated after the upgrade. After that, I ran `yarn` in the project folder and I got this issue. Also, It hangs in the end and I need to force quite by pressing
 <kbd>Ctrl</kbd>+<kbd>C</kbd>.

```
❯ yarn          
➤ YN0000: ┌ Resolution step
➤ YN0001: │ RequestError: 140476416780160:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:../deps/openssl/openssl/ssl/record/ssl3_record.c:677:

    at ClientRequest.<anonymous> (/home/hello/Documents/code/cricuru/.yarn/releases/yarn-berry.js:23:51765)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.e.emit (/home/hello/Documents/code/cricuru/.yarn/releases/yarn-berry.js:2:468464)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._emitTLSError (_tls_wrap.js:892:10)
    at TLSWrap.onerror (_tls_wrap.js:413:11)
➤ YN0000: └ Completed in 14.06s
➤ YN0000: Failed with errors in 14.07s
```

**To Reproduce**
1. Upgrade from `1.22.4` to `2.1.1`
2. Enable [node_modules](https://yarnpkg.com/configuration/yarnrc#nodeLinker) linker
3. Run `yarn`

**Screenshots**
![Screenshot_20200718_203440](https://user-images.githubusercontent.com/24727447/87855456-25ee1b80-c936-11ea-9b28-8d70fef428b2.png)

**Environment if relevant (please complete the following information):**

 - OS: Linux
 - Node version: 12.18.2
 - Yarn version: 2.1.1

**Comment by merceyz** [comment]
I'm afraid this isn't enough information to reproduce, please provide either a sherlock reproduction or a GitHub repository.

Based on the limited information i'd guess that this is most likely an issue with your machine and not Yarn, try testing on a different machine to check.

**Comment by kivervinicius** [comment]
+1 same problem here

**Comment by merceyz** [comment]
Please provide a reproduction.

As far as I can tell this seems to be https://github.com/sindresorhus/got/issues/850, are you using a custom proxy or registry without specifying the protocol?

**Comment by kivervinicius** [comment]
@merceyz Well, I'm using nexus as a private repository, if I remove my dependency from the repository it works, when I come back, the error appears again.

My **.yarnrc.yml** 
```
yarnPath: .yarn/releases/yarn-2.1.1.cjs
npmRegistryServer: https://192.168.5.90:8083/repository/npm-public/
npmAlwaysAuth: true
npmAuthIdent: ${AUTH_GITLAB_NEXUS}
unsafeHttpWhitelist: "*192.168.5.90*"
```

**Comment by kivervinicius** [comment]
In the same private repository I can't use yarn add after the error:
![image](https://user-images.githubusercontent.com/4115328/88301643-e1b2a080-ccd2-11ea-8ac8-9beebe7ed4fa.png)
If I add directly to the package.json it works.
