### ISSUE TITLE
[Bug] committing copies of large yarn artifacts to git

### ISSUE THREAD

**Issue by mzedeler** [yarnpkg/berry#1607]
In the next version of yarn ("berry") the manual states that one should just commit the directory created called .yarn, but if you use the multi-version setup for yarn, this directory contains the file releases/yarn-berry.js which seems to be the entire berry version of yarn, taking up more than 2MB of disk.

This just seems really wrong - why should I commit a package manager to git, just to get it to work?

**Comment by merceyz** [comment]
The package manager is essentially your first dependency, checking it into the repository ensures that everyone that works on that project has the exact same version of the CLI, this isn't V2 specific though, you can and should do the same for V1 projects.

Check here for a explainer for the different things to gitignore https://yarnpkg.com/advanced/qa/#which-files-should-be-gitignored

**Comment by mzedeler** [comment]
So any project using yarn should have an initial 2+MB large commit containing a verbatim copy of yarn? You can't be serious...

**Comment by arcanis** [comment]
@mzedeler there are other ways that we are exploring but that require support from other projects from the ecosystem. In the meantime, you can either do as we suggest, or instead put the binary in your home folder and reference it from there.

Please also be aware that sentences like "You can't be serious" don't really make us want to help you. We're doing the effort to understand your position and provide context, but that should go both ways.

**Comment by mzedeler** [comment]
Sorry - it just seems really excessive to copy a file of this size into the git repository. I am really curious what caused all other options to be ruled out. Wouldn't it be possible to keep yarn out of the repository and just output an error if it is incompatible with the one required by the code?
