### ISSUE TITLE
[Bug] Docs: unplug docs refer to virtualFolder; should be pnpUnpluggedFolder

### ISSUE THREAD

**Issue by cspotcode** [yarnpkg/berry#1613]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Just a small docs typo, as far as I can tell.

The unplug docs say that packages will be unplugged into `virtualDirectory`.
https://yarnpkg.com/cli/unplug

The .yarnrc docs list a second config option, `pnpUnpluggedFolder`.
https://yarnpkg.com/configuration/yarnrc#pnpUnpluggedFolder

Does the unplug doc need to be updated to refer to `pnpUnpluggedFolder`?

**To Reproduce**

N/A

**Screenshots**

N/A

**Environment if relevant (please complete the following information):**

N/A

**Additional context**

N/A

**Comment by paul-soporan** [comment]
Will be fixed by https://github.com/yarnpkg/berry/pull/1430.
