### ISSUE TITLE
yarn tsc --init works while yarn dlx tsc --init returns error TS5023: Unknown compiler option 'init'.

### ISSUE THREAD

**Issue by desmap** [yarnpkg/berry#1618]
- [x] I'd be willing to implement a fix

**Describe the bug**

`yarn tsc --init` works while `yarn dlx tsc --init` returns `error TS5023: Unknown compiler option 'init'.`

**To Reproduce**

`yarn dlx yawn --init`

(fwiw, I did this in a dir with `typescript` already installed)

**Environment if relevant (please complete the following information):**

 - OS: 18:04
 - Node version: v12.17.0
 - Yarn version: 2.1.1

**Comment by arcanis** [comment]
You need to run `yarn dlx -p typescript tsc --init`, because that's the problem with `dlx`/`npx`: it's easy to get into package squatting situations like this: https://yarnpkg.com/package/tsc
