### ISSUE TITLE
[Question] node_modules folder

### ISSUE THREAD

**Issue by kivervinicius** [yarnpkg/berry#1619]
Can I still use some modules in the node_modules folder? I ask because I have a project that copies files from the node_modules folder before making the build, I also have sass files using tilde example ~ bootstrap

**Comment by merceyz** [comment]
You can use the `node-modules` linker to have Yarn produce the `node_modules` folder if that's what you're asking, https://yarnpkg.com/configuration/yarnrc#nodeLinker

**Comment by kivervinicius** [comment]
However if I use this way all content will go back to node_modules I would like only one module in the case in "dependencies" to go there, or another way that I can make node-sass compile again using tilde,

**Comment by merceyz** [comment]
You can unplug it, it wont go into the `node_modules` folder though.
https://yarnpkg.com/cli/unplug

**Comment by kivervinicius** [comment]
tnks
