### ISSUE TITLE
[Bug] yarn workspaces foreach doesn't handle signals correctly

### ISSUE THREAD

**Issue by bgotink** [yarnpkg/berry#1622]
- [x] I'd be willing to implement a fix

**Describe the bug**

https://github.com/yarnpkg/berry/issues/1443#issuecomment-663375548

Yarn doesn't handle SIGINT signals itself when it's executing another process, instead counting on the signal to pass on to the child process and ending that with an error code.
This doesn't work well for `yarn workspaces foreach`, where `^C` will kill the running commands but yarn will start new commands in other workspaces.

**To Reproduce**

```bash
yarn worksapces foreach exec bash -c 'sleep 5 && pwd'
```

Try hitting ctrl-c, notice yarn doesn't exit. Hit ctrl-c a couple of times (= number of to do workspaces / how many processes run in parallel) and suddenly yarn does exit.

**Comment by dbousamra** [comment]
Hi. 

This is still occurring for me. Unsure if I have the right version (3.5.1)?
