### ISSUE TITLE
[Bug] Yarn still on 1.23.x, despite successfully running `yarn set version berry`

### ISSUE THREAD

**Issue by ecbrodie** [yarnpkg/berry#1635]
**Describe the bug**

I have installed Yarn according to [Berry's official instructions](https://yarnpkg.com/getting-started/install) and attempted to upgrade my local project to v2/Berry. However, my yarn version is _still stuck on v 1.23.x!_

I'm sure you've seen this issue a thousand times already. Hopefully there is a feel good moment in helping person thousand-and-one with this simple problem :)

**To Reproduce**

```
$ cd ~/my-project
$ npm -v
6.14.4
$ node -v
12.16.2
$ npm install -g yarn
$ yarn -v
1.23.0-20200615.1917
$ which yarn
/Users/evanbrodie/.nvm/versions/node/v12.16.2/bin/yarn
$ yarn set version berry
Resolving berry to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
Saving it into /Users/evanbrodie/my-project/.yarn/releases/yarn-berry.cjs...
Updating /Users/evanbrodie/my-project/.yarnrc.yml...
Done!
$ yarn -v
1.23.0-20200615.1917
```

Ruh roh....shouldn't the yarn version be "2.x" at this point?

Also, I noticed that `node_modules` wasn't deleted at this point. Should it have been?

**Environment:**

 - Mac OS 10.15.5
 - See above for Node, NPM and Yarn versions

**Comment by merceyz** [comment]
> $ npm install -g yarn
$ yarn -v
1.23.0-20200615.1917

You're running a nightly build so all bets are off and npm wouldn't have produced that version, you might have a `~/.yarnrc` or `~/.yarnrc.yml` file overwriting the local one somehow

**Comment by ecbrodie** [comment]
@merceyz as you can see from the link in my post, I followed the yarn installation instructions as stated on the Yarn Berry installation page: https://yarnpkg.com/getting-started/install. That page tells you to use `npm install -g yarn`.

I want to also note that I had first tried installing Yarn Berry on my project while using a Homebrew-installed version of Yarn (ie, `brew install yarn`). I also ran into the same issue with that installation of Yarn. So, this make me feel like this issue exists nonetheless of how I install Yarn Classic.

Is there something else I'm supposed to be doing to not use a nightly build of Yarn Classic? And even if I was using a nightly build, shouldn't it still be working (assuming this build is the latest version of the `main` branch)?

**Comment by ecbrodie** [comment]
It appears that some pesky hidden files in my home directory, such as ~/.yarn/.yarnrc.yml file, led to the yarn 1.23 nightly version being used globally on my computer.
