### ISSUE TITLE
[Feature] Print Version

### ISSUE THREAD

**Issue by olingern** [yarnpkg/berry#164]
- [x] I'd be willing to implement this feature
- [x] This feature can already be implemented through a plugin

**Describe the user story**

As a user I'd like to know my current version of yarn

**Describe the solution you'd like**

- Ergonomics should be consistent with previous yarn version: `yarn -v`

**Additional context**

![image](https://user-images.githubusercontent.com/1470297/57742998-4a30e580-76fe-11e9-9fb1-c0e9bf614f77.png)

**Comment by arcanis** [comment]
We just need to add an entry here:

https://github.com/yarnpkg/berry/blob/master/packages/plugin-essentials/sources/commands/_entry.ts#L13

Wanna submit a PR? 😃

**Comment by olingern** [comment]
Sure!
