### ISSUE TITLE
[Case Study] How can you create a 'node_modules' folder for a single project in a workspace for a CLI app?

### ISSUE THREAD

**Issue by davewthompson** [yarnpkg/berry#1640]
**What package is covered by this investigations?**

Yarn, Yarn Workspaces

**Describe the goal of the investigation**

We've got a Yarn 2 workspaces project set up with multiple components as well as a command-line app.

We'd like to publish the command-line app to our NPM repo as well as the `node_modules` folder so the CLI app can run standalone in any recent version of node, without the PnP aspect of Yarn 2.

However, we want to only generate a `node_modules` folder for one project in our workspace, not the entire workspace.

**Investigation report**

Take a simple Yarn 2 workspace project:

```
- root
- - packages
- - - simple-component
- - - cli
```

Obviously, right now trying to run a simple JS script with an import fails, as the node runtime cannot find the Pnp-ified dependency out of the box.

We would like the `cli` component to have its own copy of `node_modules` (essentially outside of the PnP-ified Yarn 2 workspace logic) so we can easily distribute it - but all of the other workspace projects to work inside the Pnp system.

We've tried to add a `.yarnrc.yml` file inside of the `cli` directory containing `nodeLinker: node-modules`, but Yarn just uses that config for the entire project.

In addition, we've set `preferUnplugged` to true inside the `cli` project's `package.json` file, but it doesn't seem to make any difference to the install process.

Is the only way to do this by switching off Pnp for the entire project, or just not using Yarn 2?

**Comment by davewthompson** [comment]
In addition, it should be noted that running ` yarn workspaces focus @root/cli --production` does nothing at all.

**Comment by davewthompson** [comment]
After reviewing the source code in the Yarn 2.0 repository, it appears the route the Yarn developers have pursued is to use Webpack to build out the command line tools (and the Node runtime that invokes Webpack is configured to use the Pnp-ified module loader) - so that the command line tools don't actually have any external dependencies. 

I would appreciate it if this could be confirmed as best practice by any of the Yarn developers.

**Comment by larixer** [comment]
@davewthompson Yes, we recommend using bundlers to distribute standalone tools (we do not recommend distributing pnp or node_modules dependencies for this purpose it is much less efficient approach and is prone to various complications)

**Comment by xenoterracide** [comment]
hmm... I was just about to raise this same problem... perhaps there is an opportunity somehow for providing an autoconfigured bundler? `package.json` `{ yarn: { bundle: true } }`, `yarn workspaces focus myworkspace --production --bundle

**Comment by merceyz** [comment]
Closing as this seems to boil down to wanting to use `bundleDependencies` which [we do not support](https://yarnpkg.com/getting-started/migration/#dont-use-bundledependencies).

To quote the docs:
> If you need to ship a package to your customers as a standalone (no dependencies), bundle it yourself using Webpack, Rollup, or similar tools.
