### ISSUE TITLE
[Documentation] "Per-project install" should mention "project" refer to a yarn project 

### ISSUE THREAD

**Issue by paseaf** [yarnpkg/berry#1644]
* [x] I'd be willing to implement this feature

**Describe the user story**
* **Why I read the docs:**
I wanted to install `yarn` for my project today, therefore read yarn v2 docs for the first time. (I'm an almost new user of yarn)

* **Problem I found about the docs:**
Yarn v2 installation document's [Per-project install section](https://yarnpkg.com/getting-started/install#per-project-install) doesn't mention that the `yarn set version berry` command should be used for an **already `yarn init`ed yarn** project. Therefore I understood the "project" in the title "Per-project install" as a general software project instead of a `yarn init`ed project.

* **Why it's a problem:**
Running `yarn set version berry` before running `yarn init` has caused `yarn init` to not ask any questions while creating a lot of files and turning the directory into a new git repo. I actually have run the commands in a subproject in an already existing git repo, which has made git not work properly. And it took me a while to realize that the subproject has been turned into another git repo.

**Example:**
``` bash
$  mkdir test_project
$  cd test_project
$  yarn set version berry
Resolving berry to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
Saving it into /Users/paseaf/Projects/courses/test/.yarn/releases/yarn-berry.js...
Updating /Users/paseaf/Projects/courses/test/.yarnrc.yml...
Done!
$  yarn init
{
  name: 'test_project'
}
$ la                                                           (master|…)
total 48
-rw-r--r--  1 user  staff   135B Jul 29 16:06 .editorconfig
drwxr-xr-x  9 user  staff   288B Jul 29 16:06 .git
-rw-r--r--  1 user  staff    28B Jul 29 16:06 .gitattributes
-rw-r--r--  1 user  staff   226B Jul 29 16:06 .gitignore
drwxr-xr-x  3 user  staff    96B Jul 29 16:05 .yarn
-rw-r--r--  1 user  staff    41B Jul 29 16:05 .yarnrc.yml
-rw-r--r--  1 user  staff     7B Jul 29 16:06 README.md
-rw-r--r--  1 user  staff    21B Jul 29 16:06 package.json
-rw-r--r--  1 user  staff     0B Jul 29 16:06 yarn.lock
```

**Describe the solution you'd like**
Add a note in the "Per-project install" section mentioning that the instructions are used for a `yarn init`ed project. Or use a specific term for "yarn project" instead of using "project". Or add a check to the `yarn set` command checking if the directory is a yarn project.

**Comment by paseaf** [comment]
Just tried it again. The problem seems solved: `yarn set version berry` doesn't initialized a new Git repo anymore.
Closing the issue.

**Comment by merceyz** [comment]
> yarn set version berry doesn't initialized a new Git repo anymore.

It never did, `yarn init` does

**Comment by paseaf** [comment]
> > yarn set version berry doesn't initialized a new Git repo anymore.
> 
> It never did, `yarn init` does

Thanks for your input. I can not remember which step did that.
I have updated my comment.
