### ISSUE TITLE
[Bug] It's impossible to install packages from private Github repos (git+ssh protocol)

### ISSUE THREAD

**Issue by MrEfrem** [yarnpkg/berry#1647]
My dependencies look like:
```
"@someorg/somepackage": "git+ssh://git@github.com:someorg/somepackage.git"
```

I follow this article to set up my MacOS: https://docs.github.com/en/enterprise/2.15/user/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

In `Yarn 1` it works well.

But in `Yarn 2` I see so error:
```
aleksandr@iMac someproject % yarn
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @someorg/somepackage@git+ssh://git@github.com:someorg/somepackage.git: Listing the refs for git+ssh://git@github.com:someorg/somepackage.git failed
    at ChildProcess.h.on.n (/Users/aleksandr/WebProjects/someproject/.yarn/releases/yarn-berry.js:2:325427)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
➤ YN0000: └ Completed in 5.89s
➤ YN0000: Failed with errors in 5.9s
```

I.e. `Yarn 1` requests my keychain and uses SSH private key but `Yarn 2` doesn't do it.

**Comment by LvChengbin** [comment]
Are there any way to resolve this temporarily?

**Comment by MrEfrem** [comment]
> Are there any way to resolve this temporarily?

https://yarnpkg.com/configuration/yarnrc#npmRegistries

**Comment by arcanis** [comment]
Generally speaking, if a problem isn't reproducible, it's likely it'll eventually get auto-closed. Git dependencies are working fine for us, so your best shot is to investigate a bit to figure out what might be the difference between 1 and 2, if any. For example:

- Try master (`yarn set version from sources` then retry the command)
- Run `git ls-remote git@github.com:someorg/somepackage.git` to make sure the git repo is available
- Add console.log statements around the place we do the clone (`yarn set version from sources --no-minify` then edit the resulting file; don't forget to revert once you're done)

**Comment by MrEfrem** [comment]
Yarn 2 works only so:
```
"@someorg/somepackage": "git@github.com:someorg/somepackage.git"
```

but Yarn 1 works only so:
```
"@someorg/somepackage": "git+ssh://git@github.com:someorg/somepackage.git"
```

Is it correct behavior?

**Comment by LvChengbin** [comment]
@MrEfrem The "git+ssh://" format can still be used in Yarn 2, but others reasons caused this issue.

Thank you so much @arcanis. It's not a bug of Yarn 2, but I think Yarn 2 may need to help to resolve this problem.
While using `git+ssh://git@github.com:someorg/somepackage.git` Yarn 2 will run `git ls-remote --refs ssh://git@github.com:someorg/somepackage.git` to list remote refs, but `git` cannot parse the host correctly, it seems to regard `github.com:someorg` as the host like `hostname + port`, and will output the error message:

```sh
ssh: Could not resolve hostname github.com:someorg: nodename nor servname provided, or not known
fatal: Could not read from remote repository.
```

Adding a slash after the colon(:) can resolve this problem:

```sh
`git ls-remote --refs ssh://git@github.com:/someorg/somepackage.git`
```

So, we need to use `git+ssh://git@github.com:/someorg/somepackage.git` instead the old version.

But I think Yarn 2 need to help users to resolve this problem because:

- Both github and gitlab display the `error` format on there webpages, it's convenient to copy the URL directly by clicking the `copy` button.
- Both Yarn 1 and NPM support the format without slash after colon, so, I cannot install some other packages which are using this format in there `package.json` files.

**Comment by MrEfrem** [comment]
@LvChengbin 
Yes, I saw that Yarn 2 executes: `git ls-remote --refs ssh://git@github.com:someorg/somepackage.git` but it's incorrect.
URL should be adjusted to `git@github.com:someorg/somepackage.git` or `ssh://git@github.com/someorg/somepackage.git`.

**Comment by LvChengbin** [comment]
I found this code in Yarn 1

```js
    // Special case in npm, where ssh:// prefix is stripped to pass scp-like syntax
    // which in git works as remote path only if there are no slashes before ':'.
    // See #3146.
    if (
      parsed.protocol === SSH_PROTOCOL &&
      parsed.hostname &&
      parsed.path &&
      parsed.path.startsWith(SCP_PATH_PREFIX) &&
      parsed.port === null
    ) {
      const auth = parsed.auth ? parsed.auth + '@' : '';
      const pathname = parsed.path.slice(SCP_PATH_PREFIX.length);
      return {
        hostname: parsed.hostname,
        protocol: parsed.protocol,
        repository: `${auth}${parsed.hostname}:${pathname}`,
      };
    }
```

https://github.com/yarnpkg/yarn/blob/5682d5531b11d472bb390c028f18d20a4fa6e217/src/util/git.js#L103

I think it should be remained in Yarn 2.

**Comment by MrEfrem** [comment]
I think problem not in this logic because URL looks correct `ssh://git@github.com:someorg/somepackage.git` except for they shouldn't add `ssh://`.
I.e. if you will search `ls-remote` in that file you will see that they use only `repository` to build a git url:
```javascript
stdout = await spawnGit(['ls-remote', '--symref', this.gitUrl.repository, 'HEAD']);
```

**Comment by MrEfrem** [comment]
@arcanis this problem is reproducible. 
This command works:
```
yarn add @shadow1349/test-math-package@git@github.com:shadow1349/test-math-package.git
```
but already this command throws the error:
```
yarn add @shadow1349/test-math-package@git+ssh://git@github.com:shadow1349/test-math-package.git
```

The error:
```
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @shadow1349/test-math-package@git+ssh://git@github.com:shadow1349/test-math-package.git: Listing the refs for git+ssh://git@github.com:shadow1349/test-math-package.git failed
```

I created a PR linked to this issue to fix it.

**Comment by MichaelBaySAP** [comment]
It turns out, for my yarn it works best, if I run `yarn install` with the following `package.json` configuration:

`"name": "https://github.com/org/repository"`

However, I found this out after running `git ls-remote https://github.com/org/repository' yielded the refs.
