### ISSUE TITLE
[Bug]Webpack 4.44.1 is not able to resolve modules with `yarn 2.1.1`

### ISSUE THREAD

**Issue by NazimAli2017** [yarnpkg/berry#1653]
- [x] I'd be willing to implement a fix (just point me in the right direction)

**Describe the bug**

Webpack 4.44.1 is not able to resolve modules using `yarn 2.1.1`. Running into this issue with a larger project, but minimal and reproducible example below.

**To Reproduce**

Using the basic setup from https://v4.webpack.js.org/guides/getting-started/#basic-setup

Minimal `package.json`
```json
{
  "name": "yarn-berry-bug",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "webpack": "^4.44.1",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0"
  },
  "dependencies": {
    "lodash": "^4.17.19"
  },
  "scripts": {
  	"dev": "webpack --config webpack.config.js"
  }
}
```
Minimal `webpack.config.js`
```javascript
const path = require('path');

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'main.js'
  }
};
```
Minimal `src/index.js`
```javascript
import _ from 'lodash';

  function component() {
    const element = document.createElement('div');

   // Lodash, now imported by this script
    element.innerHTML = _.join(['Hello', 'webpack'], ' ');

    return element;
  }

  document.body.appendChild(component());
```

**Environment if relevant (please complete the following information):**

 - OS: Arch Linux 
 - Node versionv 12.13.1
 - Yarn version 2.1.1

**Comment by merceyz** [comment]
Webpack 4 requires a plugin to support PnP https://yarnpkg.com/advanced/migration/#enable-the-pnp-plugin-when-using-webpack-4 https://github.com/arcanis/pnp-webpack-plugin
Webpack 5 supports it by default

**Comment by NazimAli2017** [comment]
Just figured it out, used advanced configuration from https://yarnpkg.com/advanced/migration#if-required-enable-the-node-modules-plugin

Solution:

1. Added `nodeLinker: node-modules` to `.yarnrc.yml`
2. Fresh `yarn install`

To make it easier for migrations, should we have this enabled by default? Otherwise everyone will run into this and it would still be a config

**Comment by merceyz** [comment]
No, this was one of the main breaking changes in the v2 release.

**Comment by NazimAli2017** [comment]
@merceyz understood, thank you!
