### ISSUE TITLE
[Bug] Playground link in documentation is dead

### ISSUE THREAD

**Issue by wojtekmaj** [yarnpkg/berry#1656]
- [ ] I'd be willing to implement a fix

**Describe the bug**

On this page:

https://yarnpkg.com/advanced/sherlock#developing-your-reproduction

there's a link to Playground:

https://yarnpkg.com/playground

which is dead.

**To Reproduce**

Open the page, click the link that says "Playground".

**Screenshots**

![image](https://user-images.githubusercontent.com/5426427/89028949-9bda8580-d32d-11ea-9c49-5a6356a9e912.png)

**Comment by arcanis** [comment]
Working fine here 🤔
