### ISSUE TITLE
[Bug]`yarn npm login`: TypeError: Cannot read property 'https://registry.yarnpkg.com' of null

### ISSUE THREAD

**Issue by justjake** [yarnpkg/berry#1663]
- [ ] I'd be willing to implement a fix

**Describe the bug**

After logging out with `yarn npm logout`, `yarn npm login` will crash until ~/.yarnrc.yml is deleted.

**To Reproduce**

1. `yarn npm login`, then authenticate successfully
1. `yarn npm logout`
1. `yarn npm login`. After authenticating, yarn will fail to update ~/.yarnrc.yml, and will crash with an error

**Screenshots**

![image](https://user-images.githubusercontent.com/296279/89116835-501efd80-d44d-11ea-9c3a-65f78b4825e1.png)

**Environment if relevant (please complete the following information):**

 - OS: macOS 10.14.6 (18G103)
 - Node version: v10.21.0
 - Yarn version: 2.1.1-git.20200801.088403dd

**Comment by paul-soporan** [comment]
Fixed in #1670.
