### ISSUE TITLE
[Feature] Add flag to `yarn upgrade-interactive` to just show new packages

### ISSUE THREAD

**Issue by schickling** [yarnpkg/berry#1673]
**Describe the user story**

Currently when running `yarn upgrade-interactive` it lists **all** installed packages and lazily displays new packages. When working on a project that has many dependencies (>20) this can get out of hand easily where you're scrolling for a while until you've "found" the first package with a new available version.

**Describe the solution you'd like**

I suggest to add a new flag (e.g. `--new-only` or make it the default behavior) to filter the list of packages to only show packages that have a new version available.

**Describe the drawbacks of your solution**

Currently the command instantly renders all packages and lazily renders the available new packages. When displaying only the new available upgrades, the rendering would need to be delayed until the required information has been loaded which delays the time to output (but I'd be fine with that).

**Describe alternatives you've considered**

**Additional context**

Example screenshot:

![image](https://user-images.githubusercontent.com/1567498/89305642-30ffb600-d66f-11ea-8532-e401d4b3e390.png)

**Comment by darthtrevino** [comment]
Also nice would be some dots to help indicate what package/version you have selected. The large gap between the pkg name and the version options cause some "i picked the wrong line" errors. This probably has some a11y implications for users who are partially sighted.

**Comment by arcanis** [comment]
I agree it could be improved - if someone wants to give a PR a try, go for it!

**Comment by chooban** [comment]
I decided to try and give this a go, as I'd like the feature, too!
