### ISSUE TITLE
[Feature] Reconsider hoisting strategy in node-modules linker mode

### ISSUE THREAD

**Issue by darthtrevino** [yarnpkg/berry#1676]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

When yarn workspaces were introduced, dependency hoisting was a strategy used to minimize linker time and make yarn faster. By using the node module resolution mechanisms, you could put all of the modules for a project at the top level and require() calls will work.

But there were some issues. There were poisonous TypeScript typings that were not meant to be shared at the top level (*cough*@types/react-native*cough*). And there are npm package types that need their dependencies localized (create-react-app, azure/aws functions). The `nohoist` mechanism in Yarn1 provided a workaround by either allowing individual workspaces or problematic dependencies to be localized where they are declared.

In yarn v2, security seems to be a higher priority than being as fast as possible, and this makes Yarn v2 a fantastic choice for deterministic dependency resolution, but the hoisting mechanism of Yarn v1 is still present, and there's no nohoist setting to opt out of it. 

IMO, nohoisting all dependencies in `nodeLinker: node-modules` mode seems to make the most sense and to fit with the Yarn v2 design. This would prevent dependencies from being used accidentally in neighboring workspaces, and it would prevent poison pill packages and having to come up with a workaround for packages that _need_ localized deps.

**Describe the solution you'd like**

Option 1: nohoist everything. Packages are linked in workspaces they are declared as required.
Option 2: Add nohoist config setting to `.yarnrc.yml`
```yaml
  nohoist:
     workspaces:
      - `./packages/my-cra-app`
     packages:
      - react-native
```

**Describe the drawbacks of your solution**

* Hoisting is kind of the expected behavior at this point because of Yarn v1.

Note:
I'm backpacking this weekend starting tomorrow morning, but I'd be glad to chat more about this next week. I apologize if this seems overly critical. I'm just excited about migrating to Yarn 2, and it's frustrating running into weird edge cases and snags where I simply cannot yet without a goofy workaround.

**Comment by arcanis** [comment]
The main point of the nm linker is to make the migration from Yarn 1 to Yarn 2 easier, for people who can't switch to PnP yet. For this to be true, we cannot make semi-large changes like this... for now.

Yarn will keep having major releases (more frequently than before, likely one per year), so I'm open to revisit this in one of them, depending how far in the migration process we are.

For now, however, the nm linker must be as low friction as possible.

**Comment by arcanis** [comment]
On a separate note, if you want safety in linking nm, I think you're looking for a similar algorithm to the one used by pnpm - not nohoist. I'd be very interested to see that implemented in Yarn, although someone would have to take ownership of its implementation.

**Comment by larixer** [comment]
To nohoist with v2 one can place `yarn.lock` into the workspace that should be really an independent project, in your example , you can place `yarn.lock` into `./packages/my-cra-app/yarn.lock` and remove `my-cra-app` from monorepo's `package.json -> workspaces`. From the standpoint of yarn the monorepo and the my-cra-app will be two independent projects, but you still can glue them via `postinstall` hook and shell commands inside scripts. This strategy should work well with Docker layer caching mechanisms too

**Comment by darthtrevino** [comment]
That sounds fair - thanks for your thoughts on this @arcanis
