### ISSUE TITLE
Quick question regarding "--ignore-scripts"

### ISSUE THREAD

**Issue by radical-edo** [yarnpkg/berry#1679]
Hi,

I've tried to use the new version of `yarn` with the `--ignore-scripts`. This flag has been removed from the v2. Why though? I've always found it to be a little bit of a security layer when installing any script/package. Is this on purpose? Will it ever come back again? Or it's something that has been deemed as unnecessary and no longer will be supported?

Would love to know about this, when you have the time. All-in-all keep up the good work! 💪

**Comment by arcanis** [comment]
Generally speaking, a lot of command line flags have been moved to the configuration settings. For example, `--ignore-scripts` is now available as [`enableScripts`](https://yarnpkg.com/configuration/yarnrc#enableScripts).

The reason for this is that those flags were defining persistent behaviors (ie things that you want to apply to every install, not just a single one), so they were ill-suited to CLI options (for example, running `yarn add` would also trigger an install, so you had to remember to add the `--ignore-scripts` flag ... who did it?).

**Comment by radical-edo** [comment]
Ah, see your point, thanks a lot.

Side note: I always did remember :)

**Comment by merceyz** [comment]
Just to note, because of how our configs work you can technically do it without changing the config
```sh
YARN_ENABLE_SCRIPTS=false yarn install
```

**Comment by radical-edo** [comment]
oh, good to know as well. Might use it, for now I've just created the `.yarnrc.yml` and went with that. Also, my instinct tells me that this "env variable" option is not something I should rely on... kinda feels like an access to a private property on a class :D

**Comment by merceyz** [comment]
It's actually a documented feature https://yarnpkg.com/configuration/yarnrc

> Finally, note that most settings can also be defined through environment variables (at least for the simpler ones; arrays and objects aren't supported yet). To do this, just prefix the names and write them in snake case: YARN_CACHE_FOLDER will set the cache folder (such values will overwrite any that might have been defined in the RC files - use them sparingly).
