### ISSUE TITLE
[Feature/Bug] Support for `yarn check`

### ISSUE THREAD

**Issue by pam-** [yarnpkg/berry#1689]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Is there an alternative to v1's `yarn check`? My team has done the v2 upgrade but is reliant on `yarn check` to confirm whether all the modules have been installed as expected.

Note: we are supporting `node_modules` on v2 and not using the zero install approach (yet).

**Comment by arcanis** [comment]
This command was deprecated a long time ago due to being largely pointless. More details: https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-remove-yarn-check.md
