### ISSUE TITLE
[Case Study] Vim and NeoVim support

### ISSUE THREAD

**Issue by TrySound** [yarnpkg/berry#170]
**What tool is covered by this investigations?**

Vim and NeoVim

**Describe the goal of the investigation**

Non node.js tools cannot be plugged with pnp. A lot of vim plugins already work with existing patterns which are globally installed packages and `node_modules/.bin`. We need a way to adopt pnp to existing non node.js tools.

**Investigation report**

The idea comes from `esy` package manager. `esy vim` command creates a sandbox, exports all bins to `path` variable and runs vim in this environment. Vim plugins are able to consume packages as globally installed.

https://esy.sh/docs/en/environment.html

**Comment by arcanis** [comment]
We discussed it a bit on Discord, but I'll copy it here to keep a track for future reference:

> You can just declare `"vim": "vim"` in your scripts field from your package.json. Running `yarn vim` will then run the linked script (ie vim) in an environment where all your available binaries are in the path

**Comment by meatwallace** [comment]
I've been trying to get Neovim with [`coc.nvim`](https://github.com/neoclide/coc.nvim) working with no luck. As it's core & language server integrations are node packages, running it with PnP results in a pretty straight forward error:

```js
[coc.nvim] error: /home/meatwallace/projects/x/.pnp.js:44171
        throw firstError;
        ^
Error: Cannot find module 'semver'
Require stack:
- /home/meatwallace/.vim/plugged/coc.nvim/bin/server.js
```
Running it without PnP results in it unable to resolve *my* modules ex. eslint/prettier configs, as expected.

Am I missing something obvious or is their architecture incompatible with PnP in it's current state? If so, what does a potential solution look like & is it in Yarn or their architecture?

**Comment by jeysal** [comment]
Bit of an old issue to revive, and obviously a lot has changed since then - https://yarnpkg.com/advanced/editor-sdks#vim--cocnvim works perfectly - but I'm wondering if it would make sense for `yarn pnpify --sdk` to also create `.vim/coc-settings.json` automatically? If creating a `.vscode` in the repo that is hopefully ignored is okay, the same with `.vim` should be fine?

**Comment by arcanis** [comment]
I think it would be fine, but in that case I'd prefer to make the SDK generator a bit more powerful so that we can account for different environments:

```
yarn dlx pnpify --sdk=vscode
yarn dlx pnpify --sdk=vim
...
```

**Comment by jeysal** [comment]
:+1: shall we repurpose this issue or (preference) close and create a new one?

**Comment by arcanis** [comment]
This one can be closed now that there are instructions in the documentation, yep!

**Comment by non25** [comment]
In case anyone using neovim + built-in lsp stumbles upon this.
I end up using the opposite of `yarn vim`, because it wasn't resolving `node_modules` es imports, but this resolves:

```lua
local lspconfig = require('lspconfig')

lspconfig.tsserver.setup{
  cmd = { "yarn", "typescript-language-server", "--stdio" };
}
  
lspconfig.svelte.setup{
  cmd = { "yarn", "svelteserver", "--stdio" };
}
```

Cool part is I don't need sdks or anything else. Any import will work.

**Comment by tstelzer** [comment]
> In case anyone using neovim + built-in lsp stumbles upon this.
> I end up using the opposite of `yarn vim`, because it wasn't resolving `node_modules` es imports, but this resolves:
> 
> ```lua
> local lspconfig = require('lspconfig')
> 
> lspconfig.tsserver.setup{
>   cmd = { "yarn", "typescript-language-server", "--stdio" };
> }
>   
> lspconfig.svelte.setup{
>   cmd = { "yarn", "svelteserver", "--stdio" };
> }
> ```
> 
> Cool part is I don't need sdks or anything else. Any import will work.

Can you elaborate a little more on your setup?

**Comment by non25** [comment]
@tstelzer
I have following packages installed on per-project basis:

```json
{
    "@typescript-eslint/eslint-plugin": "^4.15.2",
    "@typescript-eslint/parser": "^4.15.2",
    "eslint": "^7.21.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint_d": "^10.0.4",
    "typescript": "4.1.5",
    "typescript-language-server": "^0.5.1"
}
```

I use global cache to save space.

Here's LSP config:

```lua
local lspconfig = require('lspconfig')
local util = require('lspconfig/util')
local on_attach = function(client, bufnr)
  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { noremap=true, silent=true }
  buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
  buf_set_keymap('n', 'ga', '<Cmd>lua vim.lsp.buf.code_action()<CR>', opts)
  buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
  buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
  buf_set_keymap('n', 'gR', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
  buf_set_keymap('n', 'gc', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
end

lspconfig.tsserver.setup{
  cmd = { "yarn", "typescript-language-server", "--stdio" };
  on_attach = on_attach;
}

local eslint = {
  lintCommand = "yarn eslint_d -f unix --stdin --stdin-filename ${INPUT}",
  lintStdin = true,
  lintFormats = {"%f:%l:%c: %m"},
  lintIgnoreExitCode = true,
  formatCommand = "yarn eslint_d --fix-to-stdout --stdin --stdin-filename=${INPUT}",
  formatStdin = true
}

lspconfig.efm.setup {
  init_options = {documentFormatting = true};
  filetypes = {"javascript", "typescript", "svelte"};
  root_dir = function(fname)
    return util.root_pattern("tsconfig.json")(fname) or
    util.root_pattern(".eslintrc.js", ".git")(fname);
  end;
  init_options = {documentFormatting = true};
  settings = {
    rootMarkers = {".eslintrc.js", ".git/"},
    languages = {
      javascript = {eslint},
      typescript = {eslint},
      svelte = {eslint}
    }
  };
  on_attach = on_attach;
}
```

**Comment by tstelzer** [comment]
@non25 Oh, I see, you're installing it as a local dependency, instead of globally. I got it from my system package manager, that one failed to resolve any modules. When I install it locally, and run it via `yarn`, it does work. Big thanks!

**Comment by benwainwright** [comment]
Yeah I'd appreciate a solution for this as well that doesn't rely on local installs - I've just migrated to native LSP and it doesn't work. I need to use my config for work projects that this won't work for as well...

**Comment by airtonix** [comment]
You **should** be using a local install setup. 

You have the option of doing some detection: `what is nodeLinker in .yarnrc.yml ? use yarn : use npx`

**Comment by WillenOLeal** [comment]
I could not make neovim LSP work on Typescript even though I had the typescript-language-server installed globally with npm. What worked for me was going into my local yarn project and running `yarn dlx @yarnpkg/sdks base ` according to the docs here: https://yarnpkg.com/getting-started/editor-sdks

**Comment by devstefancho** [comment]
Both locally installation and `yarn dlx @yarnpkg/sdks base` are work for me

### Option1 - locally installation
install `"typescript-language-server": "^0.5.1"` in each project
then modify lua file of lspconfig as
```lua
-- before
lspconfig.tsserver.setup{
  cmd = { "typescript-language-server", "--stdio" };
  on_attach = on_attach;
}

-- after
lspconfig.tsserver.setup{
  cmd = { "yarn", "typescript-language-server", "--stdio" };
  on_attach = on_attach;
}
```

### Option2 - yarn dlx
run this command in the project
```
yarn dlx @yarnpkg/sdks base
```

after this, go to definition is work well

see demo


https://user-images.githubusercontent.com/61320923/218959334-34197b2d-4535-42e6-98c0-7cb0df878447.mov
