### ISSUE TITLE
[Bug] Links in docs jump too far

### ISSUE THREAD

**Issue by accidentaldeveloper** [yarnpkg/berry#1703]
- [x] I'd be willing to implement a fix (might take a while)

**Describe the bug**

Clicking on a link in the docs commonly takes you too far down the page. Perhaps this is because it doesn't take the header into account

**To Reproduce**

Go to https://yarnpkg.com/advanced/migration#renamed

Expected: "Renamed" header is showing

**Screenshots**

![image](https://user-images.githubusercontent.com/5819232/90322628-8d42bf80-df24-11ea-8231-0f846cf07376.png)

**Environment if relevant (please complete the following information):**

 - OS: MacOS Catalina
 - Browser: Chrome/Edge, maybe others

**Comment by accidentaldeveloper** [comment]
This is a small thing but it is quite disorienting

**Comment by arcanis** [comment]
Yep, totally agree, it's annoying 😅

**Comment by accidentaldeveloper** [comment]
Thank you! 👏
