### ISSUE TITLE
[Bug] pnpify isn't generating SDKs properly

### ISSUE THREAD

**Issue by Eduardogbg** [yarnpkg/berry#1713]
**Describe the bug**

When running pnpify on a workspace with Create React App generated a certain way, it won't create the `typescript` folder inside either `.yarn/sdks` or `.vscode/pnpify`.

**To Reproduce**

I described the steps necessary to reproduce this bug on [this issue at vscode](https://github.com/microsoft/vscode/issues/104963) 

**Environment if relevant (please complete the following information):**

 - OS: Manjaro Linux
 - Node version 14.3.0
 - Yarn berry (the current resolve of `yarn set version berry`)

**Comment by Eduardogbg** [comment]
It seems to work when I add typescript as a dependency of the workspace. Not sure if it's still a bug or something that I missed in the documentations.

**Comment by arcanis** [comment]
That's expected - quoting the [documentation](https://yarnpkg.com/advanced/editor-sdks#tools-currently-supported):

> Note: When using the --sdk flag, be aware that only the SDKs for the tools present in your root package.json will be installed (the tool won't look at the dependencies from your other workspaces). So don't forget to run the command again should you change the set of tools used by your project!

**Comment by richard-lopes-ifood** [comment]
If a workspace package have `typescript` as a `devDependency` on it, do I need to move `typescript` to the root `package.json` to make the integration work?

**Comment by arcanis** [comment]
Yep. Only the top-level counts.
