### ISSUE TITLE
https://yarnpkg.com/playground returns 404

### ISSUE THREAD

**Issue by JLHwung** [yarnpkg/berry#1714]
This link is referenced in https://yarnpkg.com/advanced/sherlock#developing-your-reproduction while I am try to develop a reproduction.

**Comment by Haroenv** [comment]
Not sure why the link isn't working, but in the meantime, I think it redirects to here: https://viko0.sse.codesandbox.io

**Comment by merceyz** [comment]
Seems only direct navigations to https://yarnpkg.com/playground work :thinking:

**Comment by arcanis** [comment]
Hmm that's likely Gatsby's routing going in the way

**Comment by ylemkimon** [comment]
https://github.com/yarnpkg/berry/blob/0604dc3d4c67593fe954c6dd349bc963cab8786a/packages/gatsby/gatsby-config.js#L132-L137 doesn't include `playground`.

**Comment by paul-soporan** [comment]
Wanna open a PR? 😀
