### ISSUE TITLE
[Bug] Fix deployment on Google App Engine (GAE)

### ISSUE THREAD

**Issue by MrEfrem** [yarnpkg/berry#1719]
I have the same problem, but already with deployment on GAE, as it was described in the GCF issue  #1646.

When Google Cloud Platform (GCP) deploys an app to GAE it provides another runtime and `FUNCTION_TARGET` there isn't available:
https://cloud.google.com/appengine/docs/standard/nodejs/runtime?hl=ru#environment_variables

But there is `GOOGLE_RUNTIME` environment variable that we can add to `FUNCTION_TARGET` (https://github.com/yarnpkg/berry/blob/master/packages/plugin-essentials/sources/commands/install.ts#L96l):
```javascript 
const isGCP = !!process.env.FUNCTION_TARGET || !!process.env.GOOGLE_RUNTIME;
````

Locally I already fixed Yarn 2 and deployed my app to GAE successfully.

Environment variables available in moment of execution of `yarn install --non-interactive --frozen-lockfile`:
```
  NODE_ENV: 'production'
  GOOGLE_RUNTIME: 'nodejs12',
  GOOGLE_DEBUG: 'true',
  BUILDER_OUTPUT: '/builder/outputs',
  CNB_STACK_ID: 'google.nodejs12',
  HOME: '/builder/home',
  HOSTNAME: '859c762aadd2',
  PATH: '/builder/google-cloud-sdk/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
```

I can create a PR.

**Comment by merceyz** [comment]
> I can create a PR.

Please do :+1:

**Comment by sylvainar** [comment]
Hey, sorry to dig up that old issue, but I can't figure out how to start GAE with yarn 2, it seems that the cloud build job previous to the deploy is stuck after installing my dependencies. Did you manage to successfully run a Yarn2 app on GAE? Did you tweak you CloudBuild config ? I can't find any help on internet.

Thanks a lot.
