### ISSUE TITLE
[Feature] Bring back --registry flag

### ISSUE THREAD

**Issue by prasannamestha** [yarnpkg/berry#1740]
- [ ] I'd be willing to implement this feature
- [x] I'd be willing to help implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

As the number of open-core packages and private registries are rapidly increasing, many projects are now making use of packages from multiple private registries. For example, `@fontawesome/pro` and `remix_run` are common private packages but are hosted under different registries - making it a necessity for the users to use multiple registries in their projects.

**Describe the solution you'd like**

The best solution to this problem is clearly bringing back the `--registry` flag (which was deprecated earlier).

**Describe the drawbacks of your solution**

I don't see any drawbacks of implementing the `--registry` flag as NPM CLI also does the same

**Describe alternatives you've considered**

None

**Additional context**

NPM CLI supports the `--registry` flag

**Comment by merceyz** [comment]
I'll close this as you can do this from the settings https://yarnpkg.com/configuration/yarnrc#npmScopes.npmRegistryServer
If we were to add a flag for this, given enough time, we'd get requests to add other settings as flags as well which we don't want to do.
