### ISSUE TITLE
[Bug] Unable to catch signals using Docker

### ISSUE THREAD

**Issue by DRoet** [yarnpkg/berry#1741]
- [ ] I'd be willing to implement a fix

**Describe the bug**

To perform a graceful shutdown of containers we need a way to catch the signals (SIGTERM/SIGINT) that Docker sends when shutting down a container.  In yarn v1 the workaround was to use `node <script>` directly instead of `yarn run`. However I can't seem to get this to work using `yarn node <script>` or `yarn run` in v2 with PnP enabled.

**To Reproduce**

Use a minimal Dockerfile:

```Dockerfile
FROM node:12.18.3

WORKDIR /opt/app

COPY . /opt/app

RUN yarn install

CMD ["yarn", "node", "./src"]
```

Inside src/index.js, listen for signals
```js
const signals = [SIGHUP, SIGINT, SIGTERM]
for (const signal of signals) {
   process.on(signal, () => {
      console.log(`process received a ${signal} signal`)
   })
}
```

Then when the container kill it using:
```sh
docker kill -s SIGTERM <container name>
```

**Environment if relevant (please complete the following information):**

 - OS: Docker
 - Node version 12.18.3
 - Yarn version 2.1.1

**Additional context**

I also tried using `docker-init/tini` to play around the PID 1 restriction after reading https://github.com/yarnpkg/berry/issues/991 but that doesn't seem to work either. It would be nice if there is some way to forward signals to the child processes so that yarn v2 works nicely with Docker.

**Comment by kevin-lindsay-1** [comment]
Was this ever fixed? I'm using `yarn node ./script.js` and I'm not seeing `SIGTERM`, but when I run `node -r ./.pnp.cjs ./script.js` it works. Wish the docs would have mentioned this if it was never fixed.

**Comment by merceyz** [comment]
Yes, see https://github.com/yarnpkg/berry/pull/2347#issuecomment-771502152

**Comment by kevin-lindsay-1** [comment]
@merceyz so then, no, it wasn't fixed? That, or it's not planned to be fixed.

**Comment by merceyz** [comment]
Not sure how you interpreted my "Yes" to mean "no" but to be specific:
The issue was fixed and released in 3.0.0 and 1.22.11, your global Yarn version must satisfy `>=1.22.11` and your local version `>=3.0.0`

**Comment by kevin-lindsay-1** [comment]
@merceyz I interpreted it as "no" because you pointed me to a specific comment that doesn't say it's fixed, it calls out a workaround, and the comments afterwards state they're still having issues. /shrug

**Comment by merceyz** [comment]
It was this part of that comment that was of interest
> If you use yarn 1 to spawn yarn 2, note that bumping just v2 to sources isn't enough, because v1 has the same problem:
yarnpkg/yarn#8543

Following that leads you to https://github.com/yarnpkg/yarn/pull/8543#issuecomment-887066918

**Comment by bertho-zero** [comment]
@merceyz I have this issue with Yarn v4.0.0 + Yarn 1.22.19
