### ISSUE TITLE
[Feature] Yarn unplug Xxx without adding any "dependenciesMeta"

### ISSUE THREAD

**Issue by GaoxinHuang** [yarnpkg/berry#1769]
I very appreciated the effort in  https://yarnpkg.com/advanced/editor-sdks#caveat. That helps me "Go to Definition" in VS code, which is huge help for me 👍  

However, when I run the command as following _yarn unplug Xxx_

It will generate **dependenciesMeta** section in **package.json**. I considered it might be necessary for VS code to local .d.ts files. But it is not necessary  as I removed the **dependenciesMeta** section and it still works very well. (Please correct me, if I am wrong)

Thus, if  _yarn unplug Xxx_ does **not** generate any section in package.json as well as .png.js with yarn.lock, it will be great. I am sorry about being picky.

**Comment by merceyz** [comment]
> But it is not necessary as I removed the dependenciesMeta section and it still works very well. (Please correct me, if I am wrong)

When you remove it then on the next `yarn install` it wont be unplugged anymore

**Comment by arcanis** [comment]
> Thus, if _yarn unplug Xxx_ does **not** generate any section in package.json as well as .png.js with yarn.lock, it will be great. I am sorry about being picky.

That's something on my roadmap (local-only install settings), but there are some tricky parts that needs to be figured out, so it won't be the case for at least a few months.

**Comment by GaoxinHuang** [comment]
Thank you very much for your comment @merceyz and @arcanis . 

I got a brief idea what dependenciesMeta is doing. Thank you again. I am happy to close it as I have some idea to explain it to our team. :) 

By the way, I am enjoying Yarn 2 with helpful document in official website . Thank you and your team for all effort.
