### ISSUE TITLE
[Feature] Install Yarn 2 globally (server or user)

### ISSUE THREAD

**Issue by szepeviktor** [yarnpkg/berry#1779]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Currenty I install Yarn 1 from dl.yarnpkg.com and it seems that there is no way to store Yarn 2 binary (`yarn-berry.cjs`) in the user's home or in `/usr/local/bin`

**Describe the solution you'd like**

Please consider installing Yarn 2 globally.

**Describe the drawbacks of your solution**

None!

**Describe alternatives you've considered**

1. Symlink `.yarn/releases/yarn-berry.cjs`
1. Manually modify `yarnPath:`

**Additional context**

Thank you.

**Comment by arcanis** [comment]
> Please consider installing Yarn 2 globally.

Well, there are some, otherwise we wouldn't have decided to go this way 🙂

**Comment by zardoy** [comment]
@arcanis I didn't get the point. If I've got thousands of repositories (in user acc/org) I have to go and run `yarn set version latest` in each of them??

> Using a single package manager across your system has always been a problem.

NOPE. It was just convenient for me. I really want to see a world where I can use all latest yarn features/plugins (Ex. auto @types/* install) on any repo that I'm working on

**Comment by zardoy** [comment]
actually a duplicate of https://github.com/yarnpkg/berry/issues/821#issuecomment-611569021. Want to know your opinion on this

**Comment by szepeviktor** [comment]
Thank you!
I'm not looking for installing packages globally but installing Yarns 2 itself globally.

**Comment by zardoy** [comment]
I actually meant the same.
I linked the comment with that question not the issue itself. But, here is a https://github.com/yarnpkg/berry/issues/766#issuecomment-580658470 scroll down and you'll see that
> Yarn 2.x will be distributed through yarn set version

Also he says:
> Things are starting to go in circle, so now it’s up to our team to take a decision regarding how we want to handle the project

It seems that you'll never get `yarn2` globally from this maintainers... feelsbad
