### ISSUE TITLE
[Enhancement] Improve CLI build time

### ISSUE THREAD

**Issue by olingern** [yarnpkg/berry#178]
- [x] I'd be willing to implement this feature

**Describe the user story**
As a yarn or plugin developer, I would like each CLI build to finish in under 200ms. I think this is essential to a good developer experience.

**Describe the solution you'd like**

Currently, unsure. On average builds take between 1000 - 2000ms. The variance seems to be due to node module caching or v8 optimizations, i.e. running `yarn build:cli` twice with no time between the commands will execute faster than a space of 1 minute.

Here's the benchmark code I'm testing with:

```javascript
const bm = () => {
  const start = new Date();
  return {
      stop: function() {
        console.log(`${(new Date()).getTime() - start.getTime()}ms`);
      }
  }
};
```
And placed in the code like:
```javascript
const b = bm();
// ..
b.stop();
```

**Notes**:
- Requiring webpack is responsible for ~400 - 600ms of this.
- `compiler.run` accounts for the rest of the time

**Ideas**:
- Optimize webpack config? 
- Learn from [vscode tooling](https://github.com/microsoft/vscode/blob/master/build/lib/compilation.ts) ( maybe a gulp build case study? )

**Comment by arcanis** [comment]
Closing - @vlasenko implemented `DEV=1 yarn <args>` which transpiles the files on the fly! 🙂
