### ISSUE TITLE
[No Feature Request] but wondering why you just haven't implemented a simple --filter globbing feature like pnpm did

### ISSUE THREAD

**Issue by desmap** [yarnpkg/berry#1782]
Just skimmed yarn constraints' docs and a bit clueless about if you wanted to achieve the same effect with constraints like with pnpm's --filter or not? Whatever, pnpm --filter is magic.

**Comment by arcanis** [comment]
Those are two entirely different features

**Comment by desmap** [comment]
Man, I should have read the first lines of the constraints, my apologies.

But still the key questions remains why does yarn doesn't have a stupid simple --filter feature?
