### ISSUE TITLE
[Feature] Output the registry server name/host/address

### ISSUE THREAD

**Issue by dzintars** [yarnpkg/berry#1784]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

As i am trying to set up package consumption from GitHub registry (which is not well documented and not flawless) i came across such error:
```sh
» yarn add @_scope/some-package@0.0.1
➤ YN0000: ┌ Resolution step
➤ YN0001: │ HTTPError: @_scope/some-package@npm:0.0.1: Response code 404 (Not Found)
    at s.<anonymous> (/home/dzintars/code/repo/.yarn/releases/yarn-berry.js:23:36333)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
➤ YN0000: └ Completed in 1.19s
➤ YN0000: Failed with errors in 1.19s
```

The context is that I am trying to consume my own package from GitHub registry. And i have one or other issue to do so. I came across many, many treads with similar issues related to correct `.yarnrc` and/or `.npmrc` syntax to enable access to additional registries like GitHub or Artifactory.

**Describe the solution you'd like**

Because it is not totally clear is my setup correct or not i have no clue, which registry returned that 404. Was it Npmjs? Was it GitHub or mby some other registry? If i would see the host, it would ease my little debugging.

Other solution would be to add `-vvv` verbosity levels to the `yarn add`.

**Question**
Why in the output before the package version number is this `npm:` prefix?

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/2707
