### ISSUE TITLE
[Bug] Internal Error: spawn E2BIG when the glob pattern (**) is in a script definition

### ISSUE THREAD

**Issue by gdorsi** [yarnpkg/berry#1792]
- [x] I'd be willing to implement a fix

**Describe the bug**

When i place a `**` glob in a script a `spawn E2BIG` error is triggered.

**To Reproduce**

package.json
```json
{
  "name": "yarn-e2big",
  "scripts": {
    "test": "jest **"
  },
  "dependencies": {
    "jest": "^26.4.2"
  }
}
```

yarnrc.yml
```yaml
yarnPath: ".yarn/releases/yarn-berry.js"

nodeLinker: node-modules
```

and run `yarn && yarn test`

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/6529568/92123978-7eea1400-edfd-11ea-910f-7c768e19e4df.png)

**Environment**

 - OS: OSX Mojave
 - Node version v12.13.0 
 - Yarn version 2.2.2

**Comment by arcanis** [comment]
That's expected if you have too many files, the command line will simply be too large for your shell. Use `yarn jest '**'` instead of `yarn jest **` if you have this problem, so that the glob is expanded by Jest, not your shell.

**Comment by gdorsi** [comment]
Thanks for the explanation!

Wouldn't it be nice to have the error message explaining the problem like you did?
