### ISSUE TITLE
[Case Study]/[Question] How do I provide build, test, etc scripts in a workspace hierarchy?

### ISSUE THREAD

**Issue by xenoterracide** [yarnpkg/berry#1802]
**Describe the goal of the investigation**

A solution to having `yarn workspace @myorg/package test` when the testing lib is in a higher workspace in the testing lib

**Investigation report**

Just for clarify I have been trying to find an answer on stackoverflow https://stackoverflow.com/q/63731343/206466

For example, in the root `package.json` I have `typescript` defined as a dependency, now in a child workspace when I go to access `tsc` for writing a `yarn workspace child build` script (so that in theory I can run them individually or all at once), it is not available. Is this resolvable in any way? I've tried `yarn run` in the child. jest has a similar problem so I have to assume this affects all `bin`s.

**Comment by arcanis** [comment]
https://yarnpkg.com/advanced/qa#how-to-share-scripts-between-workspaces
