### ISSUE TITLE
[Feature] Glob support should not error on no matched files

### ISSUE THREAD

**Issue by yinzara** [yarnpkg/berry#1813]
- [X] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

The current glob files implementation errors when no files match the glob pattern.  This is not similar to how Bash itself functions and breaks many of my team's existing yarn scripts.

We assume just because a token ends with a "*" that it is a file glob pattern.  That is not a safe assumption.  There are many command flags you could use that seem glob like (because they end with *) but are not actually file globs.  

For example, with Lerna, you may filter a `lerna run` command with a "--scope" parameter that contains a glob pattern but is not for matching against package names, not files.  While I could escape the glob pattern with single quotes, this violates the behavior that bash would have normally and means I have to fix all my scripts that could use a glob like pattern to escape the pattern with single quotes when upgrading to Yarn 2.0.

**Describe the solution you'd like**

If instead of erroring when we find no files that match the glob, we just push the unmatched pattern as it is, this would act more like bash does.

**Describe the drawbacks of your solution**

I don't see any since currently it just errors

**Comment by arcanis** [comment]
> While I could escape the glob pattern with single quotes, this violates the behavior that bash would have normally and means I have to fix all my scripts that could use a glob like pattern to escape the pattern with single quotes when upgrading to Yarn 2.0.

Not escaping them is 'dangerous' and could lead to fairly unexpected results. In general, Yarn's philosophy is to tell you when something might have unpredictable behaviour rather than let it silently succeed, and in this case I think we're in line with this goal. I think I'm personally against loosening the rule, at least if the main interest is to avoid straightening scripts.

> There are many command flags you could use that seem glob like (because they end with *) but are not actually file globs.

Do you have examples? What if this glob pattern that isn't supposed to be a glob pattern actually matches a file?

**Comment by yinzara** [comment]
While I agree not escaping could be "dangerous", it's how bash itself works.  

I really don't like the idea that yarn produces errors when bash would not.  

For example I had "$FOO" environment variables throughout my codebase in scripts making the assumption, as bash does, that if a environment variable is not present when evaluating, it evaluates to empty string.   However when I migrated to Yarn 2.0, my scripts broke everywhere with errors about missing environment variables.  

That makes migrating to Yarn 2.0 extremely error prone and time consuming.

As for an example of what I'm talking about:
`yarn dlx lerna run --scope=@mycompany/* somescript`

That couldn't (or at least shouldn't) ever match a file because I know I don't have any files in my repository that could match that pattern. I use that kind of syntax nearly everywhere.  

While I agree I could have escaped it, bash didn't require it and that Yarn shell did was frustrating to me.

**Comment by paul-soporan** [comment]
> I really don't like the idea that yarn shell produces errors when bash would not. I understand that Yarn's philosophy is to error when the results may be unpredictable, but if the purpose of yarn shell is to be a bash like shell, then it should behave like bash.

> That makes migrating to Yarn 2.0 extremely error prone and time consuming as the assumptions I make about bash shell are not true of yarn shell.
As for an example of what I'm talking about:
yarn dlx lerna run --scope=@mycompany/* somescript

Note that bash is the only shell that silently ignores invalid glob patterns. Both ZSH and Fish throw. I see Yarn's shell not as an exact bash clone, but rather as a bash-like shell that builds on top of the most used bash features (+ a few other useful features from the other shells, like multios and groups that can end without a semicolon - both ZSH features that Bash doesn't support) and is largely compatible with bash, while still discouraging unsafe patterns and having its own small extra features.

**Comment by yinzara** [comment]
Hmmm, well I'm not going to say I 100% agree with you (seeing I'm primarily a bash user), but your reasoning is still sound and you are the maintainer :-).

I already opened another issue (#1814) related to missing documentation about migration to Yarn 2.0 related to script incompatibilities, maybe that could actually just be a special doc page about the differences between Yarn shell and the other well known shells it's designed to imitate and a step in migration guide with a link to that page.

**Comment by arcanis** [comment]
Sounds good, let's close this issue and pursue on #1814 👍
