### ISSUE TITLE
[Feature] Git Plugin

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/berry#182]
**Describe the user story**

I'm a Yarn user and I host my Git repositories my self (not on GitHub). I want to install my packages from there, but I can't.

**Describe the solution you'd like**

We should implement a plugin for Git repositories. We currently only support GitHub via the http endpoint which is simultaneously easier and more performant, but that prevents us from supporting other providers (such as GitLab).

**Describe the drawbacks of your solution**

Contrary to GitHub, this plugin would require `git` in order to work. It would also require to spawn new processes, which would make it slower than the GitHub-specific branch.

**Describe alternatives you've considered**

No real alternative, we don't want to drop support for Git 🙂

**Comment by arcanis** [comment]
I put it as a "good first issue" because it's a very good way to see how both resolvers and fetchers are implemented. They shouldn't be very complex (for the first iteration we can just skip calling the lifecycle hooks on the cloned repository), but give a good overview of the architecture.

**Comment by olingern** [comment]
Yarn v1 already uses tarballs for most providers, so I'm not sure we need `git` right now. I think that would be sort of an edge case. I think [v1's resolvers](https://github.com/yarnpkg/yarn/tree/master/src/resolvers/exotics) just need to be ported to plugins, no?

**Comment by arcanis** [comment]
Yes, but Git was a supported protocol ([hosted-git-resolver](https://github.com/yarnpkg/yarn/blob/master/src/resolvers/exotics/hosted-git-resolver.js)) and it's useful enough that we should keep it that way - supporting it will be needed for people that want to download git packages using their ssh key as credentials (private packages).

**Comment by Bnaya** [comment]
What's the policy regarding using 3rd party code, for example:
https://github.com/IonicaBizau/git-url-parse

**Comment by mollyIV** [comment]
Hey 👋 Can I tackle this one? 🙏 

> I put it as a "good first issue" because it's a very good way to see how both resolvers and fetchers are implemented.

Love that ❤️ I feel like I can learn a lot about the project by doing this issue 🚀

**Comment by arcanis** [comment]
Of course 😊

I realize I forgot to answer the previous question:

> What's the policy regarding using 3rd party code

It really depends on what the package does, what would be the cost to vendor it ourselves, what are the benefits, how reliable are its maintainers, how likely it is it would become an attack vector, ... etc.

For example, with 1.2M monthly downloads and being depended upon by Snyk, git-url-parse seems an acceptable dependency to have for the Git plugin 👍
