### ISSUE TITLE
[Bug] pkg-tests-specs/sources/protocols/git.test.js throws if ssh key is not set

### ISSUE THREAD

**Issue by ylemkimon** [yarnpkg/berry#1824]
- [ ] I'd be willing to implement a fix

**Describe the bug**
```
  ● Protocols › git: › it should resolve a git dependency (git+ssh://git@github.com/TooTallNate/util-deprecate.git#v1.0.1)

    Temporary fixture folder: /tmp/xfs-8aa96703

    Command failed: /usr/bin/node /home/ylemkimon/berry/packages/yarnpkg-cli/bundles/yarn.js install


    ===== stdout:

    ```
    ➤ YN0000: ┌ Resolution step
    ➤ YN0001: │ Error: util-deprecate@git+ssh://git@github.com/TooTallNate/util-deprecate.git#v1.0.1: Listing the refs for git+ssh://git@github.com/TooTallNate/util-deprecate.git failed
```
```
Child "git" exited with exit code 128

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**To Reproduce**
`yarn test:integration pkg-tests-specs/sources/protocols/git.test.js --noStackTrace`

**Comment by arcanis** [comment]
I think I'll close it as wontfix, since this test needs to check that we can access a Git repo through the ssh protocol. Since we don't have the infra to stub this workflow, the ssh key is unfortunately required.
