### ISSUE TITLE
[Case Study] Clarity around managing Webpack (5.x) externals with PNP / Yarn 2.x

### ISSUE THREAD

**Issue by Nickersoft** [yarnpkg/berry#1827]
**What package is covered by this investigations?**

`webpack@5.0.0-beta.29`

**Describe the goal of the investigation**

The goal of this investigation is to solidify a solid understanding of how PNP dependencies should be treated as externals in Webpack builds

**Investigation report**

I'm currently in the process of exploring migrating my Node API from Yarn 1.x to 2.x, and managed to get mostly everything setup, except for my Webpack build. Under Yarn 1.x I used the [webpack-node-externals](https://github.com/liady/webpack-node-externals) library to exclude all `node_modules` dependencies from my production build. However, given that under Yarn 2.x this directory no longer exists, at first pass, Webpack threw a JavaScript Heap Error when I tried to compile due to its attempt to bundle all my dependencies into one file.

So I did some digging into how PNP externals should be handled, if at all, and found virtually no info, except for a couple of Webpack plugins that both came out within the past few months. The first one didn't work at all, and the second again threw a heap error. So I decided to roll my own based on one of the implementations.

I wound up writing an `externals` function that looks like this:

```typescript
import path from 'path';
import pnp from 'pnpapi';

module.exports = {
    externals: [
      ({ context, request }, callback) => {
        try {
          const resolution = pnp.resolveToUnqualified(request, context, {
            considerBuiltins: false,
          });
          
          if (path.relative(topLevelLocation, resolution).startsWith('.yarn')) {
            return callback(null, `commonjs ${request}`);
          }
        } catch (e) {
          // Do nothing
        }

        return callback();
      },
    ],
}
```

Tried building, and it worked! However, then I tried to run it. I received:

```
(node:46069) UnhandledPromiseRejectionWarning: Error: Your application tried to access @babel/runtime, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
```

Figuring it was just a missing peer dependency, I installed `@babel/runtime`. Then I ran it again:

```
(node:46145) UnhandledPromiseRejectionWarning: /Users/tnickerson/base/monaco/.yarn/cache/@babel-runtime-npm-7.11.2-f2cfabd212-2f127ad60a.zip/node_modules/@babel/runtime/helpers/esm/typeof.js:1
export default function _typeof(obj) {
^^^^^^

SyntaxError: Unexpected token 'export'
```

As it is attempting to access an uncompiled ESM module, naturally the program errors and exits. 

Right now I'm at a standstill. I'm curious as to your thoughts on how Webpack externals will be treated going forward, and if this externals function is roughly the right approach to be taking. Until there is more documentation surrounding this I'll probably just stick to 1.x.

**Comment by missing1984** [comment]
One workaround is to only include relative imports.

`externals: [/^[^/.][a-zA-Z\-0-9./]+$/],`

Works great for me.

**Comment by merceyz** [comment]
> As it is attempting to access an uncompiled ESM module, naturally the program errors and exits.

Change your babel config to output commonjs
