### ISSUE TITLE
Document local development and profiling process

### ISSUE THREAD

**Issue by remorses** [yarnpkg/berry#1830]
- [x] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

I want to work on #1829 and #1817 but i can't find any docs about running and profiling yarn locally

**Describe the solution you'd like**

What i would like to know is
- How to use the local version of yarn (now i am using `node /berry/packages/yarnpkg-cli/bin/yarn.js`)
- Document the need of env vars `YARN_IGNORE_PATH=1 YARN_IGNORE_CWD=1` to profile successfully yarn (`node  --inspect yarn.js` will fail because yarn binary forks itself (using execFileSync) if you don't pass the env vars `YARN_IGNORE_PATH`)
- How to run yarn with source maps enabled (when i profile `berry/packages/yarnpkg-cli/bin/yarn.js` i get a lot of webpack minified functions)

**Comment by larixer** [comment]
@remorses These are all valid points and should be added to the Documentation. But the easiest way to contribute is to join our Discord chat, ask quick questions and quickly receive answers to move forward fast.
https://discord.com/invite/yarnpkg

**Comment by arcanis** [comment]
In case someone lands on this issue later:

> How to use the local version of yarn (now i am using `node /berry/packages/yarnpkg-cli/bin/yarn.js`)

Running `yarn build:cli` and executing the generated bundle is the best way to test perfs. Note that the bundle is in the `bundle` directory, not `bin` (the `bin` directory contains a checked-in version that we only use to reference the last formal release).

> How to run yarn with source maps enabled (when i profile `berry/packages/yarnpkg-cli/bin/yarn.js` i get a lot of webpack minified functions)

I don't really trust source maps in general, so I'd recommend to just build an unminified bundle using `yarn build:cli --no-minify`. That should be good enough for most purposes.
