### ISSUE TITLE
[Bug] yarn npm login not storing login details?

### ISSUE THREAD

**Issue by wojtekmaj** [yarnpkg/berry#1831]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I'm would like to run `yarn npm publish`. To do that, I first need to log in using `yarn npm login`. However, this doesn't seem to work: even though I successfully log in, `yarn npm publish` doesn't know about my credentials.

**To Reproduce**

```
yarn npm login
➤ YN0000: Logging in to https://registry.yarnpkg.com

✔ Username: · wojtekmaj
✔ Password: · [redacted]

➤ YN0000: Successfully logged in
➤ YN0000: Done in 10s

yarn npm publish        
➤ YN0000: LICENSE
...
➤ YN0041: Invalid authentication (as undefined)
➤ YN0000: Failed with errors in 0.95s
```

**Environment if relevant (please complete the following information):**

 - OS: [e.g. OSX, Linux, Windows, ...] macOS 11.0
 - Node version [e.g. 8.15.0, 10.15.1, ...] 14.5.0
 - Yarn version [e.g. 2.0.0-rc1, ...] 2.2.2

**Additional context**

adding `--publish` flag to `yarn npm login` doesn't seem to make a difference.

**Comment by merceyz** [comment]
@paul-soporan recently fixed the error message for that (https://github.com/yarnpkg/berry/pull/1809) to include more details, could you try using the version from master (`yarn set version from sources`) and then publish again?
