### ISSUE TITLE
[Bug] `yarn plugin import` throws `__dirname` is not defined

### ISSUE THREAD

**Issue by remorses** [yarnpkg/berry#1837]
- [ ] I'd be willing to implement a fix

**Describe the bug**

running `yarn plugin import` throws `__dirname` is not defined, the plugin works fine when used from a local path

```
$ yarn plugin import https://raw.githubusercontent.com/remorses/light-yarn/master/dist/index.js
➤ YN0000: Downloading https://raw.githubusercontent.com/remorses/light-yarn/master/dist/index.js
➤ YN0001: evalmachine.<anonymous>:74943
/******/        __webpack_require__.ab = __dirname + "/";/************************************************************************/
                                         ^

ReferenceError: __dirname is not defined
    at module.exports (evalmachine.<anonymous>:74943:36)
    at evalmachine.<anonymous>:74948:12
    at Script.runInContext (vm.js:133:20)
    at Script.runInNewContext (vm.js:139:17)
    at runInNewContext (vm.js:322:38)
    at be (/Users/morse/Documents/GitHub/sterblue1/.yarn/releases/yarn-2.2.2.cjs:2:74548)
    at f.Pk.start (/Users/morse/Documents/GitHub/sterblue1/.yarn/releases/yarn-2.2.2.cjs:2:74394)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**To Reproduce**

```
yarn plugin import https://raw.githubusercontent.com/remorses/light-yarn/master/dist/index.js
```

**Comment by remorses** [comment]
I think yarn is trying to evaluate the script with `eval` to check if the script is valid, that doesn't seem a good idea

**Comment by arcanis** [comment]
We're using `vm` in order to evaluate the plugin and obtain its name, necessary to install it on the disk. Presumably the `import` command is expected to interact with third-party code, so it shouldn't be a security issue.

**Comment by remorses** [comment]
Another problem is the `dynamicRequire` function in `packages/yarnpkg-core/sources/miscUtils`, how can i bundle the plugin in one file if it is calling require dynamically?

**Comment by arcanis** [comment]
I don't understand what you mean 🤔 You write the plugin, so you write whatever code you want - nowhere do we mandate that you use a dynamic require.

**Comment by remorses** [comment]
i am reimplementing the run command and need to use functions from `yarnpkg-core`, these are dynamically requiring stuff so i will get an error with `cannot find module @yarnpk/core`

**Comment by arcanis** [comment]
Again, without code, it's very hard to be sure we're talking about the same thing. Yarn plugins have a factory function that takes a special `require` in parameter that can access the `@yarnpkg/core` module built within the Yarn binary. If that's not enough, can you share an minimal repro of what you're trying to do and that doesn't work?

**Comment by remorses** [comment]
Ok, i will use the custom require

**Comment by remorses** [comment]
For reference i managed to use the normal require (which gives access to `@yarnpkg/core` and friends) using

```js
const findUp = require('find-up');
require(findUp.sync('.pnp.js')).setup()
```
