### ISSUE TITLE
[Feature] Better documentation of `patch` and `patch-commit`

### ISSUE THREAD

**Issue by mrtnbroder** [yarnpkg/berry#1852]
- [x] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

I was looking into `patch` and how it works, but the docs didnt give much info. The CLI also didnt. I had to look around to get an idea of it. I thought it worked similar like `patch-package`. However, it works differently.

**Describe the solution you'd like**

I was looking for the docs to make a PR with a better documenation of it but couldn't find it. Maybe its on a CMS or something.

Can we add more info about `patch` and `patch-commit` and how it works? (e.g. there is no mentioning of adding the `patch:` protocol to the `package.json` file)

**Comment by arcanis** [comment]
Doc is currently here https://yarnpkg.com/features/protocols#patch. However, it would be worth to improve the CLI documentation for `patch` and `patch-commit`, help appreciated 😃

**Comment by sanyamgandhak** [comment]
Hi there ,
Please assign it to me

**Comment by arcanis** [comment]
We don't assign issues. Feel free to open PRs if you see a clear improvement.
