### ISSUE TITLE
[Bug] packageName@npm:x.y.z isn't supported by any available linker

### ISSUE THREAD

**Issue by mvasin** [yarnpkg/berry#1855]
- [x] I'd be willing to implement a fix

**Describe the bug**

I try to use Yarn 2 with `nodeLinker: node_modules`:

```
mkdir linker-test &&
cd linker-test &&
yarn init -y &&
yarn set version berry &&
echo "nodeLinker: node_modules" >> .yarnrc.yml &&
yarn add react
```

and get

```
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0.41s
➤ YN0000: ┌ Fetch step
➤ YN0013: │ loose-envify@npm:1.4.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ object-assign@npm:4.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ prop-types@npm:15.7.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ react-is@npm:16.13.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ react@npm:16.13.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0012: │ react@npm:16.13.1 isn't supported by any available linker
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 0.49s
```

**Reproduction with Sherlock**

Unfortunately, I couldn't figure the [Sherlock playground](https://viko0.sse.codesandbox.io/), as even the _templates_ were marked as unreproducible. The reproduction is above, please copy and paste in the terminal.

**Environment if relevant (please complete the following information):**

 - OS: OSX 10.15.6
 - Node version: v12.13.0
 - Yarn version 1.22.4 / 2.2.2

**Comment by larixer** [comment]
@mvasin Its `nodeLinker: node-modules`, not dash, but minus

**Comment by mvasin** [comment]
Thanks, @larixer! It worked indeed.

**Comment by Avasam** [comment]
Yarn's own migration script added `nodeLinker: node_modules`

But indeed looking at https://yarnpkg.com/configuration/yarnrc#nodeLinker it should be `node-modules`
