### ISSUE TITLE
[Bug] Cannot downgrade from v2 to v1 via set-policies

### ISSUE THREAD

**Issue by olingern** [yarnpkg/berry#187]
**Describe the bug**

Once upgraded to the nightly, `yarn policies set-version x.x.x` does not downgrade.

**To Reproduce**

`yarn policies set-version 1.16.0`

**Screenshots**
![image](https://user-images.githubusercontent.com/1470297/57996465-9024e980-7b02-11e9-904a-88998eb7c627.png)

**Environment if relevant (please complete the following information):**

    OS: Ubuntu 18.04.2 LTS
    Node version: 10.1.0
    Yarn version: nightly

**Additional context**

Was attempting to downgrade to check yarn v1 performance vs v2

**Comment by arcanis** [comment]
I just tried on the Berry repository and it worked fine:

```
❯ [PREDATOR?] berry git:(master) ❯ yarn policies set-version 1.16.0

➤ YN0000: Found matching release with 1.16.0
➤ YN0000: Downloading https://github.com/yarnpkg/yarn/releases/download/v1.16.0/yarn-1.16.0.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-1.16.0.js
➤ YN0000: Done in 3.23s

❯ [PREDATOR?] berry git:(master) ✗ ❯ yarn --version

1.16.0
```

Can you investigate? Things to check:

- What is your global Yarn version?
- Where is downloaded the release?
- What path is stored in the `.yarnrc`?
- Is the key called `yarn-path` or `yarnPath`?

**Comment by arcanis** [comment]
Going to close this issue for now, feel free to reopen if it can be repro'ed 🙂

**Comment by talentlessguy** [comment]
I have the same problem
