### ISSUE TITLE
[Feature] make binaries from transitive dependencies available

### ISSUE THREAD

**Issue by trollkotze** [yarnpkg/berry#1875]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Say packageA provides a binary "whatever".
Then if we `yarn add packageA` as a dependency, we can run that binary inside our yarn workspace with `yarn whatever`.
But this does not apply to transitive dependencies at the moment.
If we have packageB which depends on packageA, and we only add packageB as a dependency to our project, then we can't access the binary "whatever", provided by packageA, in a convenient way.

**Describe the solution you'd like**

It would be nice if all the binaries of transitive dependencies could be run with `yarn <binary-name>`.

**Describe the drawbacks of your solution**

There might be conflicting binary names with a huge load of transitive dependencies.

**Describe alternatives you've considered**

I don' really see any.

**Additional context**

When using NPM, one can access all transitive binaries if by adding an alias in the "scripts" part of package.json, i.e. when having a transitive dependency on eslint, one could add ```"scripts": { "eslint": "eslint"}``` to package.json and then `npm run eslint` would work.
It's a bit cumbersome to do this additional step. But it is better than nothing. In yarn, the transitive binaries are simply not available at all, as far as I can see.

**Comment by arcanis** [comment]
This is intended. In npm, while you can access transitive dependencies, there is no way to be sure which ones it is, as multiple packages can depend on conflicting versions, or on no version at all. 

Yarn aims to give you less ways to shoot yourself in the foot when it makes sense, not more, and considering that the fix on your side is simply to list a dependency you really have, it seems an acceptable trade-off.

**Comment by trollkotze** [comment]
Okay. Makes sense.
