### ISSUE TITLE
[Bug] No yarn message when I use ">" to output to a file

### ISSUE THREAD

**Issue by wood1986** [yarnpkg/berry#1877]
- [x] I'd be willing to implement a fix

**Describe the bug**

When I run this script to generate a json file via this command `yarn node sample.js > sample.json` yarn's message will be output to my json as well. Because of it, json file become invalid json

**Screenshots**

```
yarn node v1.22.5 <<<<<<<< I do not want this
{
  "wmpjwe4b": {
    
  },
  "c9xsd1eb": {
  }
}
Done in 0.16s. <<<<<<<< I do not want this

```

**Comment by arcanis** [comment]
As mentioned in the output, you're running an old version of Yarn. New versions don't have these lines.
