### ISSUE TITLE
[Feature] some way to automatedly add packageExtensions to .yarnrc.yml

### ISSUE THREAD

**Issue by osdiab** [yarnpkg/berry#1878]
- [x] I'd be willing to implement this feature
  - maybe, though not really sure how yarn works so might be a struggle
- [ ] This feature can already be implemented through a plugin
  - I don't think so?

**Describe the user story**

I tried to switch to yarn berry at my company but the number of existing dependencies triggering `[MODULE_NOT_FOUND]` `ambiguous and unsound` warnings is deafening - pages and pages of violations from third party code I don't know about.

**Describe the solution you'd like**

Some way to make these errors quiet without needing to copy paste the same package extensions over and over again for like 100 dependencies

**Describe the drawbacks of your solution**

It would make people less rigorous about inspecting all of their dependencies

**Describe alternatives you've considered**

I could just let the errors make our logs impossible to read I guess. Or slog for hours in service of placating yarn berry. Or just not use yarn berry.

**Comment by merceyz** [comment]
That would defeat the whole purpose of enforcing strict dependencies and you could just run `yarn config set nodeLinker node-modules && yarn` and opt out of PnP

**Comment by arcanis** [comment]
First, one important note: **the loose mode triggers too many warnings, and there's nothing we can do about that**. It's explained in the [documentation](https://yarnpkg.com/features/pnp#caveat). Don't use the loose mode for production usage, only use the strict mode, which will report *true* errors.

> Some way to make these errors quiet without needing to copy paste the same package extensions over and over again for like 100 dependencies

We're fine to add them into the [builtin extension list](https://github.com/yarnpkg/berry/blob/master/packages/plugin-compat/sources/extensions.ts) if you open PRs for them on the upstream projects 🙂
