### ISSUE TITLE
https://yarnpkg.com/cli/info is incorrect

### ISSUE THREAD

**Issue by NickHeiner** [yarnpkg/berry#1880]
![image](https://user-images.githubusercontent.com/829827/94320742-873bf780-ff42-11ea-806d-4998e85421e1.png)

Looks like this should be `yarn npm info lodash`, not `yarn info lodash`.

**Comment by arcanis** [comment]
Next release will feature `yarn info`. For technical reasons, the website we deploy documents the master branch (which you can install via `yarn set version from sources`), not the latest stable release.

**Comment by NickHeiner** [comment]
Ok. I humbly provide feedback that it's pretty disorienting to have docs not match the latest stable release, regardless of the technical reasons involved. :smile:
