### ISSUE TITLE
[Bug] `yarn set version berry` names the binary differently on second run

### ISSUE THREAD

**Issue by mattrunyon** [yarnpkg/berry#1881]
- [ ] I'd be willing to implement a fix

**Describe the bug**

When running `yarn set version berry` from yarn 1, it installs .yarn/releases/yarn-berry.cjs
When running `yarn set version berry` again in the same directory, it installs .yarn/releases/yarn-2.2.2.cjs

**To Reproduce**

(Following the official install instructions https://yarnpkg.com/getting-started/install)
1. Install yarn 1 via npm globally.
2. Go to an empty folder
3. `yarn set version berry` will result in yarn-berry.cjs being downloaded and specified in .yarnrc.yml
4. `yarn set version berry` a 2nd time will result in yarn-2.2.2.cjs being downloaded and specified in .yarnrc.yml

**Screenshots**

![image](https://user-images.githubusercontent.com/8619789/94331233-6a2e1580-ff90-11ea-9060-ea7a932820ed.png)

**Environment if relevant (please complete the following information):**

 - OS: OSX 10.15.6
 - Node version 14.12.0
 - Yarn version 1.22.5/2.2.2

**Additional context**

N/A

**Comment by merceyz** [comment]
That's because on the first run V1 performs the install, on the second run V2 does it. They behave differently and V2 is more specific with the filename.
