### ISSUE TITLE
[Bug] Clarify how libraries can access modules that may not be there

### ISSUE THREAD

**Issue by mrtnbroder** [yarnpkg/berry#1895]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I am currently running into an issue with https://github.com/dotansimha/graphql-code-generator on yarn v2, where the implementation of the cli-tool is iterating over an array of possible package names (e.g. trying to `require` a package that eventually starts with a prefix  `@graphql-codegen`). So it tries to `require.resolve` `@graphql-codegen/graphql-codegen-apollo-next-ssr` first, but correct would be `graphql-codegen-apollo-next-ssr`. 

Yarn v2 complains here that ` Your application tried to access @graphql-codegen/graphql-codegen-apollo-next-ssr, but it i
sn't declared in your dependencies; this makes the require call ambiguous and unsound.`

On the homepage I couldn't find much information about this scenario. I did see that libraries should make sure to use `createRequire` [which it now does](https://github.com/dotansimha/graphql-code-generator/commit/398b094b3f7ee6aa93db547a14bef88d39bbf15a) but it still throws this error.

What would be the correct way of accessing possible inexistent packages?

**Comment by merceyz** [comment]
To check if a require failed because the module was not found one should check the error code instead of the error message, regardless if it's PnP or not.

The issue is that `graphql-code-generator` is searching the error message for `Cannot find module '${moduleName}'`, when they should be checking the if the error code is `MODULE_NOT_FOUND`. https://github.com/dotansimha/graphql-code-generator/pull/4818

**Comment by arcanis** [comment]
I've also added an entry inside our [Rulebook](https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies) explaining how to load plugins the safe way:

> If your package is something that automatically loads plugins (for example eslint), peer dependencies obviously aren't an option as you can't reasonably list all plugins. Instead, you should use the createRequire function (or its polyfill) to load plugins on behalf of the configuration file that lists the plugins to load - be it the package.json or a custom one like the .eslintrc.js file.

**Comment by mrtnbroder** [comment]
awesome @arcanis and @merceyz thanks a lot to you two!
