### ISSUE TITLE
[Bug] Installation instructions don't work

### ISSUE THREAD

**Issue by lhorie** [yarnpkg/berry#19]
**Describe the bug**

Following the installation instructions creates a noop script

**To Reproduce**

```
> git clone git@github.com:KwanMan/yarn-pnp-workspaces.git
> cd yarn-pnp-workspaces/with-pnp

> yarn policies set-version nightly # as per docs
> yarn policies set-version berry # as per docs

> cat .yarn/releases/yarn-berry.js
false
```

**Expected behavior**

There should be more code in .yarn/releases/yarn-berry.js and running yarn commands such as `yarn --version` from the project folder should work

**Environment if relevant (please complete the following information):**

 - OS: MacOS Mojave 10.14.3
 - Node version 10.15.2
 - Yarn version 1.13.0

**Additional context**

Following the instructions also causes yarn to stop working altogether within the folder, until the changes in .yarnrc are removed.

**Comment by arcanis** [comment]
I broke the `policies set-version` command by moving the binary location in #18 😨 

Will fix that in a second!

**Comment by arcanis** [comment]
Fixed! The following commands now seem to behave properly:

```
$ git clean -df .
$ yarn policies set-version nightly
$ yarn policies set-version berry
$ cd packages/package-a
$ yarn
$ yarn build
Hello
```

**Comment by lhorie** [comment]
Awesome, thanks for the quick response!
