### ISSUE TITLE
Implement `yarn list` to get all dependencies of a project

### ISSUE THREAD

**Issue by abh1kg** [yarnpkg/berry#1902]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

It would be nice to get `yarn list` implemented via a plugin or natively in berry.

**Describe the solution you'd like**

`yarn list` should list the installed dependencies of the project or the current working directory in the monorepo.

**Describe the drawbacks of your solution**

N/A

**Describe alternatives you've considered**

I don't know an easy way out for this right now.

**Additional context**

None

**Comment by arcanis** [comment]
This feature is already in master under the name [`yarn info`](https://yarnpkg.com/cli/info). It'll be released in the next minor (we don't yet have a way to only print the name - contribution welcome to implement `--name-only`!).
