### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by Krrishdhaneja** [yarnpkg/berry#1904]
- [ ] Want a react native support ...

I just and just don't know why Yarn 2 doesn't support react native. Anyone can please tell me why 

Will the yarnpkg team work on this ?

**Comment by merceyz** [comment]
Yarn 2 supports react native using the node-modules linker, if you're using workspaces that was fixed with https://github.com/yarnpkg/berry/pull/1854

Point 4 here explains react native https://yarnpkg.com/advanced/qa/#how-easy-should-you-expect-the-migration-from-classic-to-modern-to-be
