### ISSUE TITLE
registry.yarnpkg.com is mirroring old unpublished packages

### ISSUE THREAD

**Issue by christoffercarlsson** [yarnpkg/berry#1912]
Hi,

I recently started publishing new versions of my NPM packages to the GitHub Package Registry.

I noticed that the registry at registry.yarnpkg.com is still mirroring old packages that I originally published to registry.npmjs.org but have since unpublished because of the move to GitHub Package Registry.

Is there a way to unpublish all of these packages from the registry at registry.yarnpkg.com?

Thanks!

Chris

**Comment by merceyz** [comment]
`registry.yarnpkg.com` is just a CNAME to `registry.npmjs.org` see https://yarnpkg.com/advanced/qa/#why-registryyarnpkgcom-does-facebook-track-us

**Comment by christoffercarlsson** [comment]
OK, that's good. The old packages are still showing up on the https://yarnpkg.com/package/ website when search for them, though. The same packages cannot be found on the https://npmjs.com website (as expected).

If the registry.yarnpkg.com is essentially a mirror of registry.npmjs.org, then shouldn't the packages listed at https://yarnpkg.com also mirror those listed at the https://npmjs.com website?

**Comment by arcanis** [comment]
The website uses data from the [Algolia index](https://github.com/algolia/npm-search), which we don't control.
