### ISSUE TITLE
[Bug] yarn pack generates a tarball without dependencies

### ISSUE THREAD

**Issue by abh1kg** [yarnpkg/berry#1922]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Running `yarn pack` on a workspace generates a tarball with the sources _only_ but the tarball does not contain the dependencies. Note that I am using the `node_modules` linker in my project.

**Screenshots**

**Environment if relevant (please complete the following information):**

- OS: Mac OS 10.15.7
- Node: 12.14.1
- Yarn: 2.2.2

**Comment by arcanis** [comment]
Yes, that's expected. Your dependencies are described in your package.json.

**Comment by abh1kg** [comment]
@arcanis : Sure. Maybe, let me try to rephrase my question - is there a way I can generate a tarball for a workspace with the installed `node_modules` relevant to the workspace along with the sources?

**Comment by arcanis** [comment]
Not with Yarn. Add the n_m to the packed archive yourself if you need to.
