### ISSUE TITLE
Support keys containing dots in `yarn config` CLI subcommands

### ISSUE THREAD

**Issue by svvac** [yarnpkg/berry#1940]
There actually seems to be no way to reference a key containing dots using `yarn config get` or `yarn config set`.

This makes configuring e.g. registries rather painful, as one needs to override the whole parent object in order to set a specific child key.

Proposal : Don't consider backslash-escaped dots `\.` as depth separators

    yarn config set 'npmRegistries.//npm\.example\.com.npmAuthToken' 'xxxxx'

**Comment by paul-soporan** [comment]
Dot notation can only be used with valid unquoted JS property names. Otherwise, you have to use indexed access:
```sh
yarn config set 'npmRegistries["//npm.example.com"].npmAuthToken' 'xxxxx'
```

**Comment by svvac** [comment]
That's good to know. I actually tried something like that, but without the quotes inside the brackets (which has the same effects as replacing both brackets with a dot).

I'd close, but maybe this is worth adding a note to the docs regarding indexed access syntax ?

**Comment by arcanis** [comment]
That seems a good idea - would you like to contribute an example in `config/set.ts`? It's just a string to add, plus the version file.
