### ISSUE TITLE
Error: Cannot find module 'event-stream'

### ISSUE THREAD

**Issue by NikolayMakhonin** [yarnpkg/berry#1944]
## Environment

- Node Version: `12.17.0`
- Yarn v1 Version: `1.22.10`
- Yarn v2 Version: `2.3.1` (I use the berry version)
- OS and version: Win7 (Microsoft Windows [Version 6.1.7601])

### 1. Create these files:

**package.json**
```json
{
  "name": "test-yarn",
  "devDependencies": {
    "ps-tree": "1.2.0"
  }
}
```

**index.js**
```js
const psTree = require('ps-tree')
```

### 2. Run these commands:
```sh
npm install -g yarn@1.22.10
yarn set version berry
yarn config set enableGlobalCache true
yarn node index.js
```

### 3. Get this error:
```
c:\projects\test-yarn>yarn node index.js
c:\projects\test-yarn\.pnp.js:6435
    throw firstError;
    ^

Error: Cannot find module 'event-stream'
Require stack:
- c:\cache\Yarn\Berry\cache\ps-tree-npm-1.2.0-3975e95bd6-7.zip\node_modules\ps-tree\index.js
- c:\projects\test-yarn\index.js
Require stack:
- c:\cache\Yarn\Berry\cache\ps-tree-npm-1.2.0-3975e95bd6-7.zip\node_modules\ps-tree\index.js
- c:\projects\test-yarn\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)←[39m
    at Function.external_module_.Module._resolveFilename (c:\projects\test-yarn\.pnp.js:6415:54)
←[90m    at Module._load (internal/modules/cjs/loader.js:842:27)←[39m
    at Function.external_module_.Module._load (c:\projects\test-yarn\.pnp.js:6271:36)
←[90m    at Module.require (internal/modules/cjs/loader.js:1026:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (c:\cache\Yarn\Berry\cache\ps-tree-npm-1.2.0-3975e95bd6-7.zip\node_modules\←[4mps-tree←[24m\index.js:4:13)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1138:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:986:32)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m
}
```

**Comment by larixer** [comment]
@NikolayMakhonin `ps-tree` uses invalid semver for `ps-tree`: `=3.3.4`, it should rather be: `3.3.4` instead:
https://github.com/indexzero/ps-tree/blob/master/package.json#L40

To check that you can install `semver` package and run the following code:
```js
const semver = require('semver');

console.log(semver.valid(`=3.3.4`)); // results in 'null'
```

**Comment by NikolayMakhonin** [comment]
I found 6 package with same problem only in my project, and how many more are in npm. I cannot fix all these modules because I am not their owner.

follow-redirects
ps-tree
pako
deepmerge
browserstack-local
wordwrap

It might be worth adding to yarn handling this version syntax?

**Comment by larixer** [comment]
@NikolayMakhonin Its more a question to `semver` package than to Yarn. We get the information about validity from `semver`.  

Yarn has mechanism to workaround problems like these via, `packageExtensions`:
https://yarnpkg.com/configuration/yarnrc#packageExtensions

**Comment by NikolayMakhonin** [comment]
@larixer
I tried to use [packageExtensions ](https://yarnpkg.com/configuration/yarnrc#packageExtensions) and [resoluions ](https://yarnpkg.com/configuration/manifest#resolutions) options, but it doesn't work - the same error.
I created the the [test repo](https://github.com/NikolayMakhonin/yarn-test)

**Comment by larixer** [comment]
@NikolayMakhonin I have run `run_test.sh` and it told me `success` at the end

**Comment by NikolayMakhonin** [comment]
I understood what the problem was.
It was my mistake - I created NTFS link for Yarn cache directory to another disk.
```
c:\Users\Admin\AppData\Local\Yarn\ => d:\Users\Admin\AppData\Local\Yarn\
```
Now I deleted the link and it work without extra yarn options.

I did this because I don't want to specify the global cache path for each project. As I understand it, yarn does not allow to set global options.

**Comment by merceyz** [comment]
You can set global options in the `~/.yarnrc.yml` file
