### ISSUE TITLE
[Feature] Allow node_linker to be specified separately for each module

### ISSUE THREAD

**Issue by xenoterracide** [yarnpkg/berry#1949]
in #1599 I have to use node_linker do to a bug in  dotansimha/graphql-code-generator#4688 however, AFAIK, this is the only library I have that needs node_linker and it is a CLI development only application. It would be nice if instead of having to enable node_linker across the board, that I could have just 1 or so modules that did it.

**Comment by andreialecu** [comment]
This is actually worked on by @larixer here: https://github.com/yarnpkg/berry/pull/1900

However, you can also use [Yarn v2's `patch:` protocol](https://yarnpkg.com/features/protocols#patch) to apply a patch to `graphql-code-generator` which includes the changes from the PR you linked.

**Comment by andreialecu** [comment]
Btw, it seems that PR was merged and should be available from `graphql-code-generator` `1.17.9` onwards.

**Comment by larixer** [comment]
If you have only one CLI tool that should be run with node_modules layout, this case is usually covered with `pnpify`:
https://yarnpkg.com/advanced/pnpify, though I haven't checked if it will work with `graphql-code-generator`

**Comment by xenoterracide** [comment]
@andreialecu excellent, thanks for both. @larixer the problem was that the require was wrong, so it was a code issue upstream.

**Comment by larixer** [comment]
Closing this issue, since the problem with `graphql-code-generator` has little relation to issue title.
