### ISSUE TITLE
[Feature][monorepo] yarn add --all-descendants <pkg>

### ISSUE THREAD

**Issue by xenoterracide** [yarnpkg/berry#1950]
problem, in a hierarchical monorepo you may have many parent workspaces. If I have, say `

```
/package.json
/foo/package.json
/foo/bar/package.json
/foo/bar/baz/package.json
```

and I do (presuming the workspaces basically match the path) `yarn workspace foo add --all-descendants --dev @node/types` I would want `@node/types` to be added to `foo`, `foo-bar` and `foo-bar-baz`'s package.json.

**Comment by arcanis** [comment]
This seems a specialized usage which we're unlikely to add to the core.

**Comment by merceyz** [comment]
Closing as you can already do this with `workspace-tools` by running
```
yarn workspace foo workspaces foreach add @types/node --dev
```
Granted it's not as fast as a dedicated command but it gets the job done
