### ISSUE TITLE
[Feature][cli] yarn upgrade

### ISSUE THREAD

**Issue by xenoterracide** [yarnpkg/berry#1952]
sometimes you know the module you want to upgrade across the repo, and it's just 1. so https://classic.yarnpkg.com/en/docs/cli/upgrade/ would still be useful, would be cool if it supported `@org` wildcards, we have for example dependencies on `@aurelia/metadata` and `@aurelia/kernel` would be nice to be able to `yarn upgrade @aurelia/*@^0` and have it pull in the lates matching `^0` for both. lastly, have support for #1950 in case I have a separate set of descendants I want to upgrade, as we are using yarn to fully manage our complete monorepo (it includes other langauages, and multiple applications).

**Comment by merceyz** [comment]
Sounds exactly like the `yarn up` command https://yarnpkg.com/cli/up

**Comment by xenoterracide** [comment]
ugh, I would never have guessed that command...
