### ISSUE TITLE
[Bug] Package URL not properly handled

### ISSUE THREAD

**Issue by ulrik-s** [yarnpkg/berry#197]
**Describe the bug**

Running yarn in my project fails.  The reason seems to be that the URL to the package is not handled properly:
https://registry.yarnpkg.com/@xtuc%2fieee754/-/ieee754-1.2.0.tgz
when is should be:
https://registry.yarnpkg.com/@xtuc/ieee754/-/ieee754-1.2.0.tgz

**To Reproduce**
run yarn in a project where @xtuc/ieee754 is part of the dependencies.

**Screenshots**
➤ YN0000: ┌ Fetch step
➤ YN0013: │ @xtuc/ieee754@npm:1.2.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ @xtuc/long@npm:4.2.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ @xtuc/long@npm:4.2.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0001: │ HTTPError: @xtuc/long@npm:4.2.2: Response code 500 (Internal Server Error)
    at EventEmitter.emitter.on (/Users/ulrik/src/blah/.yarn/releases/yarn-berry.js:9585:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
➤ YN0001: │ HTTPError: @xtuc/ieee754@npm:1.2.0: Response code 500 (Internal Server Error)
    at EventEmitter.emitter.on (/Users/ulrik/src/blah/.yarn/releases/yarn-berry.js:9585:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
➤ YN0001: │ HTTPError: @xtuc/long@npm:4.2.1: Response code 500 (Internal Server Error)
    at EventEmitter.emitter.on (/Users/ulrik/src/blah/.yarn/releases/yarn-berry.js:9585:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
➤ YN0000: └ Completed in 5.33s
➤ YN0000: Failed with errors in 6.4s

**Environment if relevant (please complete the following information):**

 - OS: OSX 10.14.4
 - Node version 11.6.0
 - Yarn version latest nightly

**Additional context**

**Comment by arcanis** [comment]
This is due to #193 (meant to fix #191).

Wtf. This works:

https://registry.yarnpkg.com/@babel%2fcode-frame/-/code-frame-7.0.0.tgz

And this doesn't:

https://registry.yarnpkg.com/@xtuc%2fieee754/-/ieee754-1.2.0.tgz

![giphy (2)](https://user-images.githubusercontent.com/1037931/58159792-8247a380-7c7d-11e9-95fe-4965c68327c1.gif)

**Comment by deini** [comment]
Same issue when trying to add:

- @xtuc/long
- @csstools/normalize.css

**Comment by bgotink** [comment]
It looks to be dependant on the scope

https://registry.yarnpkg.com/@angular%2fieee754/-/ieee754-1.2.0.tgz

```json
{"error":"Not found"}
```

https://registry.yarnpkg.com/@bangular%2fieee754/-/ieee754-1.2.0.tgz

```json
{"error":"exception parsing path /@bangular%2Fieee754/-/ieee754-1.2.0.tgz"}
```

I get the same exception for any permutation on the `@angular` scope, as well as other existing scopes like `@angular-devkit`, `@ionic`, `@ionic-native`, `@yarnpkg` &hellip;

It's almost as if there's a whitelist of scopes where `%2f` is allowed in the URL

**Comment by deini** [comment]
Resolved in https://github.com/yarnpkg/berry/pull/199
