### ISSUE TITLE
[Bug] yarn version doesn't support "main" branch in git

### ISSUE THREAD

**Issue by ldrick** [yarnpkg/berry#1982]
- [ ] I'd be willing to implement a fix

**Describe the bug**

The Yarn Plugin "version" seems to need a branch called "master". Since it is recommended to use "main" as base branch, I encountered this error, when trying to use `yarn version`

> Usage Error: No ancestor could be found between any of HEAD and master, origin/master, upstream/master

**To Reproduce**

Having a repo like:

> git branch -vv
`* main 5874c46 [origin/main] init`

and running this command
`yarn version patch --deferred`

**Environment:**

 - OS: [Windows 10]
 - Node version [14.13.0]
 - Yarn version [2.3.3]

**Additional context**

Meanwhile I am manually updating package.json, but this is not really CI compatible workflow.

**Comment by merceyz** [comment]
You can configure it using [changesetBaseRefs](https://yarnpkg.com/configuration/yarnrc#changesetBaseRefs), we can't change it until V3 as it would be a breaking change

**Comment by ldrick** [comment]
Oh, thanks for the fast response, i will close it than
