### ISSUE TITLE
[Bug] yarn unplug does not work for indirectly referenced package; error message might be misleading

### ISSUE THREAD

**Issue by francisu** [yarnpkg/berry#1987]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Not sure if this is a bug of feature request. http-proxy-agent is not directly installed in the workspace. When I try to do a yarn unplug on it, I get the result below. It will work if I add the http-proxy-agent. I find the error message ambiguous. In this case, the http-proxy-agent is referenced by the workspace, though not directly. If it's the intent that the reference must be direct, then the error message should be clarified. I would be happy to do a PR for that. And then do a separate feature request to allow an indirect reference to work, which would be very useful for debugging purposes.

```
repoman:server francis$ yarn unplug http-proxy-agent
Usage Error: Pattern http-proxy-agent doesn't match any packages referenced by this workspace

$ yarn unplug [-A,--all] [-R,--recursive] [--json] ...
repoman:server francis$ yarn why http-proxy-agent
├─ jwks-rsa@npm:1.10.1
│  └─ http-proxy-agent@npm:4.0.1 (via npm:^4.0.1)
│
├─ pac-proxy-agent@npm:3.0.1
│  └─ http-proxy-agent@npm:2.1.0 (via npm:^2.1.0)
│
└─ proxy-agent@npm:3.1.1
   └─ http-proxy-agent@npm:2.1.0 (via npm:^2.1.0)
repoman:server francis$ 
```

**To Reproduce**

See above.

**Comment by arcanis** [comment]
Use the `-R,--recursive` flag: https://yarnpkg.com/cli/unplug 🙂

> By default, only direct dependencies from the current workspace are affected. If -A,--all is set, direct dependencies from the entire project are affected. Using the -R,--recursive flag will affect transitive dependencies as well as direct ones.
