### ISSUE TITLE
[Bug] peerDependency-resolution is inconsistent (workspaces vs default)

### ISSUE THREAD

**Issue by PutziSan** [yarnpkg/berry#1992]
- [ ] I'd be willing to implement a fix

**Describe the bug**

A peerDependency by a used module is not listed correctly as peerDependency. I expected to get 

```
Module not found: Error: A tried to access B (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
```
But it does not throw for a project without workspaces. For a project with workspaces, it will throw the above error. But then adding the package (not the missing peerDependency) with the incomplete package.json (missing peerDependency) in the root of the workspace, the error above will disappear.

**To Reproduce**

You can see the (correct?) behavior here: https://github.com/PutziSan/jotai-yarn-2-workspaces-error-demo

It will throw like expected. But adding the package in the root will resolve it. To be honest, I am not sure what the correct behavior is, but I think something is not correct here.

**Environment if relevant (please complete the following information):**

 - OS: Windows
 - Node version 12.18.4

**Additional context**

I stumbled about this when creating a bug-reproduction repo for this issue https://github.com/pmndrs/jotai/issues/135 + MR https://github.com/pmndrs/jotai/pull/139#issuecomment-710079892

**Comment by merceyz** [comment]
This is expected, to make migration easier for users, dependencies are allowed to access dependencies at the top level without declaring them correctly. https://yarnpkg.com/configuration/yarnrc#pnpFallbackMode

**Comment by arcanis** [comment]
I've just added a documentation entry about the fallback, it's being deployed as we speak.
