### ISSUE TITLE
[Other] Replace non-inclusive terms

### ISSUE THREAD

**Issue by wojtekmaj** [yarnpkg/berry#2002]
- [x] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

In my opinion, we should get rid of non-inclusive terms like "blacklist", "whitelist", implying that white = good and black = bad, from the codebase.

On top of these terms being non-inclusive, "whitelist"/"blacklist" are also not descriptive. Like, why something was "blacklisted"? In Berry, this term is used to keep a list of packages incompatible with PnP. So why not say incompatiblePackages instead of blacklistedPackages? 

**Describe the solution you'd like**

Replace the terms mentioned above with alternatives.

**Describe the drawbacks of your solution**

If any "black*" or "white*" terms were used in user-facing API, we need to be careful not to break user perferences that might have been created before the inclusive alternatives were introduced.

**Describe alternatives you've considered**

n/a

**Comment by arcanis** [comment]
> implying that white = good and black = bad, from the codebase

There is no such implication. I get why you would want to make this change, and I won't oppose it but, if you find those words hurtful, please consider that the suggestion that they imply anything racial is just as hurtful. If we want to choose words carefully, let's choose words carefully 🙂

**Comment by arcanis** [comment]
Given that a single PR remains (which will be merged in the next major) I'll close this issue for now.
