### ISSUE TITLE
Should this be VersionCheckCommand not VersionApplyCommand?

### ISSUE THREAD

**Issue by njmaeff** [yarnpkg/berry#2008]
- [ x ] I'd be willing to implement a fix

https://github.com/yarnpkg/berry/blob/59b72d1d9d7eb630f06b2288471dd7701466f5dc/packages/plugin-version/sources/commands/version/check.tsx#L18

**Describe the bug**

Duplicate identifier in @yarnpkg/plugin-version commands. Should this be VersionCheckCommand?

**Comment by merceyz** [comment]
Yes, PR welcome

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/2014
