### ISSUE TITLE
Treating temp directory as a workspace

### ISSUE THREAD

**Issue by BryanCrotaz** [yarnpkg/berry#2017]
During yarn install with dependencies from github urls (worked in yarn 1):

```
YN0000: │ /C:/Users/Einstein/AppData/Local/Temp/xfs-9c2f8ccb STDOUT Usage Error: The nearest package directory (C:\Users\Einstein\AppData\Local\Temp\xfs-9c2f8ccb) doesn't seem to be part of the project declared in C:\Users\Einstein.
YN0000: │ /C:/Users/Einstein/AppData/Local/Temp/xfs-9c2f8ccb STDOUT
YN0000: │ /C:/Users/Einstein/AppData/Local/Temp/xfs-9c2f8ccb STDOUT - If the project directory is right, it might be that you forgot to list AppData/Local/Temp/xfs-9c2f8ccb as a workspace.
YN0000: │ /C:/Users/Einstein/AppData/Local/Temp/xfs-9c2f8ccb STDOUT - If it isn't, it's likely because you have a yarn.lock or package.json file there, confusing the project root detection.
```

Do I need to add my temp directory as a workspace? This seems counter intuitive. 

How would there be a yarn.lock in a new temp directory created for the purpose of installing?

From the error message I don't know what to do as a user to fix this

**Comment by merceyz** [comment]
You have a `package.json` and/or `yarn.lock` file in your home directory `C:/Users/Einstein`, get rid of those and it should work.

I'll see if we can improve that by making a empty `yarn.lock` if one doesn't exist when preparing external projects without any kind of lockfile

**Comment by BryanCrotaz** [comment]
That's not what the error message says - it says I have a package lock file in `AppData/Local/Temp/xfs-9c2f8ccb`

Better error message please?

**Comment by BryanCrotaz** [comment]
Seems to have fixed it, but I never would have guessed how to fix it from the error.

**Comment by merceyz** [comment]
Reopening since we can prevent this from happening

**Comment by joeldenning** [comment]
This also tripped me up, but I eventually figured it out.
