### ISSUE TITLE
yarn why only shows single level of dependency

### ISSUE THREAD

**Issue by BryanCrotaz** [yarnpkg/berry#2019]
In yarn 1, `yarn why` showed the entire dependency tree so the developer could see exactly what the problem was. Now in `berry` it only shows one level of dependency, making it painful to find out the root cause of a wrong version:

```
C:\projects\lords-scoreboard-ui>yarn why node-sass
├─ broccoli-sass-source-maps@npm:1.8.1
│  └─ node-sass@npm:3.13.1 (via npm:^3.8.0)
│
└─ broccoli-sass-source-maps@npm:2.2.0
   └─ node-sass@npm:4.14.1 (via npm:^4.7.2)

C:\projects\lords-scoreboard-ui>yarn why broccoli-sass-source-maps
├─ ember-cli-sass@npm:5.6.0
│  └─ broccoli-sass-source-maps@npm:1.8.1 (via npm:^1.8.0)
│
└─ ember-cli-sass@npm:7.2.0
   └─ broccoli-sass-source-maps@npm:2.2.0 (via npm:^2.1.0)

C:\projects\lords-scoreboard-ui>yarn why ember-cli-sass
├─ ember-cli-template-editor@git+ssh://git@bitbucket.org/silvercurve/ember-cli-template-editor.git#commit=2d70266eb548d595369815b30c046e73168e0716
│  └─ ember-cli-sass@npm:7.2.0 (via npm:^7.1.7)
│
├─ ember-command-control-ui@git+ssh://git@bitbucket.org/silvercurve/ember-command-control-ui.git#commit=38ae37bebb5acff1d5dbe5317f17d1526be3df40
│  └─ ember-cli-sass@npm:5.6.0 (via npm:^5.5.0)
│
└─ lords-scoreboard-ui@workspace:.
   └─ ember-cli-sass@npm:5.6.0 (via npm:^5.5.1)
```

Only in that last call could I see the project of mine that was incorrectly imported.

`yarn why` should show the entire dependency tree from the root to the leaves, where the leaves are all the instances of the requested package

**Comment by arcanis** [comment]
Please check the options: https://yarnpkg.com/cli/why

**Comment by BryanCrotaz** [comment]
1. No hint in the output that there are options (especially for someone coming from yarn 1 where there weren't)
2. Shouldn't recursive be the default? It's the most useful.
