### ISSUE TITLE
[Feature] plugin-typescript - type generation for workspace identities

### ISSUE THREAD

**Issue by njmaeff** [yarnpkg/berry#2027]
- [x] I'd be willing to implement this feature
- [x] This feature can already be implemented through a plugin

**Describe the user story**

Project generated types are helpful when developing local scripts and tooling. For example, if you are targeting certain packages using a switch statement, it is a benefit to have static types defined so typescript throws an error when your package no longer exists or renamed.

**Describe the solution you'd like**

I would like to add an `afterAllInstalled` hook to the typescript plugin to generate a new type alias `WorkspaceIdentities` located in a configurable location (.yarn/types by default). They type alias is a string union type and contains the names of all the packages.

**Describe the drawbacks of your solution**

Maybe there is a very small performance penalty after installs. The hook already has access to the project object so it just needs to transform the object into the generated type, then save the file. I can add a .yarnrc.yml configuration option to disable the hook.

**Describe alternatives you've considered**

A clear and concise description of any alternative solutions or features you've considered, and why you think they wouldn't be good enough.

**Additional context**

![Screenshot from 2020-10-22 05-55-30](https://user-images.githubusercontent.com/31554476/96874716-4e048380-142b-11eb-890d-47a6ec950735.png)

**Comment by merceyz** [comment]
I appreciate the suggestion but I don't think this is something we'll implement in the core, you're more than welcome to implement this in your own plugin of course
