### ISSUE TITLE
[BUG] plugin-version - remove unnecessary await when setting map object

### ISSUE THREAD

**Issue by njmaeff** [yarnpkg/berry#2028]
- [x] I'd be willing to implement a fix

**Describe the bug**

The release object is a Map object and is being awaited. 

https://github.com/yarnpkg/berry/blob/eb5657a9e0e72c4617f2378c10c58531513060da/packages/plugin-version/sources/commands/version.ts#L119

**Comment by arcanis** [comment]
Sounds good, feel free to open a PR directly 🙂
