### ISSUE TITLE
[Feature] topological from root

### ISSUE THREAD

**Issue by xenoterracide** [yarnpkg/berry#2046]
so my problem is that I have multiple applications in my workspaces, I don't necessarily want to build all of them and their full deps all the time. I tried `yarn workspaces foreach --topological --include myworkspace run build` but that only built `myworkspace` what I need is to be able to build myworkspace and all of its dependencies in topological order.

**Comment by merceyz** [comment]
You're most likely after https://github.com/yarnpkg/berry/pull/1986, which you can install using
```
yarn plugin import from sources workspace-tools
```

**Comment by xenoterracide** [comment]
these do nothing

```
> yarn workspaces foreach --parallel --verbose --recursive --include @bb/service-graph run build 
```
```
yarn workspaces foreach --parallel --topological --verbose --recursive --include @bb/service-graph run build
```

**Comment by merceyz** [comment]
`--include` is applied after the `--recursive` falg (implementation wise) so you're running include on the current workspace only, cd into the workspace and run it from there

```
yarn packages/service-graph/ workspaces foreach --parallel --topological --verbose --recursive run build
```

**Comment by xenoterracide** [comment]
yeah, that works, a bit non obvious though, documentation examples should probably be added.

**Comment by merceyz** [comment]
PRs are welcome :)

**Comment by skoging** [comment]
I have a similar issue.

I'm looking to transition away from using lerna, but I'm currently relying on the [`--include-dependencies`](https://github.com/lerna/lerna/tree/main/core/filter-options#--include-dependencies) flag.

> Include all transitive dependencies when running a command regardless of --scope, --ignore, or --since.

I can currently emulate this somewhat using the `yarn workspace project-web` to scope the command:
```sh
yarn workspace project-web workspaces foreach --recursive --verbose --topological-dev run build
```

This does not work in the cases where I use wildcard/glob to target multiple projects and all their common dependencies.
Using `yarn workspaces foreach --include project-*` to run a recursive build in the projects will result in common dependencies being built multiple times, once per project, which is exactly what I want to avoid.

```sh
yarn workspaces foreach --include project-* workspaces foreach --recursive --verbose --topological-dev run build
```

**Comment by arcanis** [comment]
> to run a recursive build in the projects will result in common dependencies being built multiple times, once per project

That seems like a bug, can you open a new issue about that? I'll close this one since `--recursive` is the solution to the original problem.
