### ISSUE TITLE
[Bug]? INIT_CWD for rebuild command does not point to project root relative to package.

### ISSUE THREAD

**Issue by phryneas** [yarnpkg/berry#2053]
- [x] I'd be willing to implement a fix (I'd need some hints on how to find the correct root for the package though)

**Describe the bug**

Running `yarn rebuild husky` while in a child workspace will make husky point to that subfolder - as `INIT_CWD` in that moment points to that subfolder.
It would probably make more sense that `INIT_CWD` would point at the workspace (or root) where the package to be rebuilt is installed in.

**To Reproduce**

without workspaces, everything works: 
```sh
git init
echo '{}' > package.json
mkdir -p foo
yarn set version berry
yarn add husky
cat .git/hooks/husky.local.sh | grep 'cd'
# cd "." ✅
(cd foo; yarn rebuild husky)
cat .git/hooks/husky.local.sh | grep 'cd'
# cd "." ✅
```
with workspaces, chaos ensues:
```sh
git init
echo '{"workspaces":["foo"]}' >| package.json
mkdir -p foo
echo '{"private": true}' > foo/package.json
yarn set version berry
yarn add husky
cat .git/hooks/husky.local.sh | grep 'cd'
# cd "." ✅
(cd foo; yarn rebuild husky)
cat .git/hooks/husky.local.sh | grep 'cd'                                                                                                                                         
# cd "foo/" ❌
```

**Environment if relevant (please complete the following information):**

 - OS: Linux
 - Node version v10.19.0
 - Yarn version 2.3.3

**Comment by arcanis** [comment]
This isn't possible, a package may be used by multiple workspaces. Which one would you use as init cwd?

**Comment by phryneas** [comment]
I'd see three scenarios:
 * the current workspace references `husky`: INIT_CWD is the current workspace folder
 * a parent of the current workspace references `husky`: INIT_CWD is the folder of that workspace
 * neither the current workspace not a parent references `husky`: either the root workspace or (what I would prefer) an error message like "neither the current workspace nor any of it's parents reference husky. Please call `yarn rebuild husky` from a workspace actually referencing husky."
