### ISSUE TITLE
How do I read a file across workspaces?

### ISSUE THREAD

**Issue by xenoterracide** [yarnpkg/berry#2059]
I have this code

```
      typeDefs: loadFiles(join(__dirname, 'generated/schema.graphql')),
```

but now that this class needs to find this file in whatever workspace the class is being used in, I'm not entirely certain how to do it, or even what I'm looking for. The graphql file would be in the same spot relative to each workspace, e.g `workspace:[build/src]/generated/schema.graphql` but the class is now only in 1 workspace. In javaland I would probably just look it up on the classpath, but there's no such thing in node land (oh, this is a nodejs service, not a browser app).

**Comment by arcanis** [comment]
Our issue tracker isn't a support forum - your problem doesn't seem related to the Yarn packages, so it might make more sense as a StackOverflow question or something else 🙂

**Comment by andreialecu** [comment]
@xenoterracide you can join the Yarn Discord, where it might be easier to get help with random issues: https://discord.gg/yarnpkg
