### ISSUE TITLE
[Feature] allow yarn install that generates unplugged packages like scripts are enabled, even when scripts are not executed

### ISSUE THREAD

**Issue by brummelte** [yarnpkg/berry#2062]
**Describe the user story**

[Renovate ](https://github.com/renovatebot/renovate) recently added yarn berry support. For security reasons scripts are disabled via the environment variable `YARN_ENABLE_SCRIPTS=false`. The problem with that is, that the .pnp.js file will always be changed to point to the `cache` folder for all packages. Even for ones that would need to be built locally. After merging a PR from renovate, the .pnp.js file will be changed when running yarn locally to point to the `unplugged` folder again.

I don't see a way how renovate could solve that without enabling scripts.

**Describe the solution you'd like**

Provide a way to run `yarn install` and generate .pnp.js with all packages that have build script pointing to `unplugged`, without actually running the scripts.

**Additional context**

https://github.com/renovatebot/renovate/issues/7584

**Comment by ylemkimon** [comment]
PnPLinker unplugs a package if it has build scripts to run: https://github.com/yarnpkg/berry/blob/ccba9021896cf5697d3d9a2bb0479b3179cf4603/packages/plugin-pnp/sources/AbstractPnpInstaller.ts#L74-L91 https://github.com/yarnpkg/berry/blob/975376a5b7e65679ed78e66336b4e642422c4610/packages/plugin-pnp/sources/PnpLinker.ts#L218-L219

I think Yarn should have an option to unplug packages that have build scripts even if they are disabled.
