### ISSUE TITLE
Numerous 'Can't resolve module <name>' errors. Already ran 'yarn' command from root

### ISSUE THREAD

**Issue by naser-baig-au4** [yarnpkg/berry#2063]
Hi there,

I am using yarn v2 workspaces with pnp. My app works great on v1 workspaces and we have recently moved to v2 and things started to break in Plug'n'play. I am getting many 'Can't resolve module' errors.

### Reproducing the issue

I created a barebones setup of yarn workspaces with pnp and the main deps of my app that are causing issues. Here's the repository: https://github.com/naser-baig-au4/yarn-pnp-barebone

Please clone it and run yarn command. After that, run the react-app which depends on webchat app

```yarn workspace react-app start```

I am on Node 14 (recently upgraded) and on yarn v2.3.3

Please let me know if you need any further information to help identify the problem.

Lastly, it works if I use ```nodeLinker: node-modules``` in my yarnrc.yml file or if I am on v1.

**Comment by merceyz** [comment]
First thing that stands out is that you're using `npx babel` instead of `yarn babel`, don't do that they're not compatible, secondly you're using webpack 4 so you need to add https://github.com/arcanis/pnp-webpack-plugin

**Comment by merceyz** [comment]
I've attached a patch of the changes required to make your project "run", impressive amount of missing dependencies for such a small project. **However**, because of things in your dependency tree depending on https://github.com/compulim/p-defer-es5 it wont work as it tries to build stuff at install-time without the PnP plugin, so that needs to be fixed.

```sh
$ yarn why p-defer-es5 -R
├─ react-app@workspace:react-app
│  └─ webchat@workspace:webchat [56f36] (via 1.0.0 [56f36])
│
└─ webchat@workspace:webchat
   └─ botframework-webchat@npm:4.10.1 [3f024] (via npm:^4.10.1 [3f024])
      ├─ botframework-directlinespeech-sdk@npm:4.10.1 (via npm:4.10.1)
      │  ├─ p-defer-es5@npm:1.2.1 [db7a2] (via npm:1.2.1 [db7a2])
      │  └─ web-speech-cognitive-services@npm:7.0.2-master.6004e4b [db7a2] (via npm:7.0.2-master.6004e4b [db7a2])
      │     └─ p-defer-es5@npm:1.2.1 [db7a2] (via npm:1.2.1 [db7a2])
      ├─ botframework-webchat-core@npm:4.10.1 (via npm:4.10.1)
      │  └─ p-defer-es5@npm:1.2.1 [db7a2] (via npm:1.2.1 [db7a2])
      ├─ botframework-webchat-component@npm:4.10.1 [dd112] (via npm:4.10.1 [dd112])
      │  └─ botframework-webchat-core@npm:4.10.1 (via npm:4.10.1)
      └─ web-speech-cognitive-services@npm:7.0.2-master.6004e4b [db7a2] (via npm:7.0.2-master.6004e4b [db7a2])
```

```diff
diff --git a/.yarnrc.yml b/.yarnrc.yml
index cecb449..57a0873 100644
--- a/.yarnrc.yml
+++ b/.yarnrc.yml
@@ -1 +1,21 @@
 yarnPath: ".yarn/releases/yarn-berry.js"
+
+packageExtensions:
+  "webchat@*":
+    dependencies:
+      "@babel/runtime": "*"
+  "react-say@*":
+    dependencies:
+      prop-types: "*"
+  "react-film@*":
+    dependencies:
+      "@babel/runtime": "*"
+  "react-dictate-button@*":
+    dependencies:
+      prop-types: "*"
+  "botframework-directlinespeech-sdk@*":
+    dependencies:
+      node-fetch: "*"
+  "botframework-webchat-core@*":
+    dependencies:
+      "botframework-directlinejs": "*"
diff --git a/react-app/package.json b/react-app/package.json
index 45ced4d..87817be 100644
--- a/react-app/package.json
+++ b/react-app/package.json
@@ -9,7 +9,7 @@
   "license": "ISC",
   "devDependencies": {
     "@babel/core": "^7.12.3",
-    "@babel/plugin-syntax-class-properties": "^7.12.1",
+    "@babel/plugin-proposal-class-properties": "^7.10.4",
     "@babel/plugin-transform-runtime": "^7.12.1",
     "@babel/preset-env": "^7.12.1",
     "@babel/preset-react": "^7.12.1",
@@ -21,6 +21,7 @@
     "html-webpack-plugin": "^4.5.0",
     "mini-css-extract-plugin": "^1.0.0",
     "optimize-css-assets-webpack-plugin": "^5.0.4",
+    "pnp-webpack-plugin": "^1.6.4",
     "style-loader": "^2.0.0",
     "terser-webpack-plugin": "^4.2.3",
     "webpack": "^4.29.6",
@@ -32,8 +33,5 @@
     "react": "^16.14.0",
     "react-dom": "^16.14.0",
     "webchat": "1.0.0"
-  },
-  "installConfig": {
-    "pnp": true
   }
 }
diff --git a/react-app/webpack.common.js b/react-app/webpack.common.js
index 20a670f..ce1d063 100644
--- a/react-app/webpack.common.js
+++ b/react-app/webpack.common.js
@@ -1,3 +1,5 @@
+const PnpWebpackPlugin = require(`pnp-webpack-plugin`);
+
 const babelOptions = {
   presets: ["@babel/preset-react", "@babel/preset-env"],
   plugins: [
@@ -43,4 +45,14 @@ module.exports = {
       },
     ],
   },
+  resolve: {
+    plugins: [
+      PnpWebpackPlugin,
+    ],
+  },
+  resolveLoader: {
+    plugins: [
+      PnpWebpackPlugin.moduleLoader(module),
+    ],
+  },
 };
diff --git a/webchat/package.json b/webchat/package.json
index 7673d8e..82ce6ba 100644
--- a/webchat/package.json
+++ b/webchat/package.json
@@ -4,8 +4,8 @@
   "main": "dist/index.js",
   "private": true,
   "scripts": {
-    "build:js": "npx babel src --out-dir dist --copy-files --source-maps inline --extensions '.js,.ts,.tsx'",
-    "build:js:watch": "npx babel src --out-dir dist --copy-files --source-maps inline --extensions '.js,.ts,.tsx' -w",
+    "build:js": "yarn babel src --out-dir dist --copy-files --source-maps inline --extensions '.js,.ts,.tsx'",
+    "build:js:watch": "yarn babel src --out-dir dist --copy-files --source-maps inline --extensions '.js,.ts,.tsx' -w",
     "build:fe": "rimraf dist && yarn build:types && yarn build:js"
   },
   "dependencies": {

```

**Comment by naser-baig-au4** [comment]
@merceyz Thank you for sharing that patch. I have implemented it and it still gives me the module resolution errors but on different pages. I believe botframework-webchat is the main problem here as it works just fine if I remove that from the dependency.

![image](https://user-images.githubusercontent.com/56202963/97490599-15166280-1987-11eb-8c97-b87f5f603aa8.png)

I have tried your way of adding that ```abort-controller-es5``` package as a dependency in package extensions but that doesn't seem to resolve the issue. I just pushed the changes on the repository. Would really appreciate your inputs on that and it'd be great if you could share some resources on the proper setup.

Thanks again 👍

**Comment by merceyz** [comment]
I updated the patch a few times after commenting, try applying it again

**Comment by naser-baig-au4** [comment]
Thank you, I saw those updates. Will do.

There really wasn't a good clue on how to debug these issues if it wasn't for you @merceyz, could you please suggest me some resources where I can learn more about this. The official documentation unfortunately wasn't clear for me.
