### ISSUE TITLE
[Bug] merge conflict resolver removes leading comment in lockfile

### ISSUE THREAD

**Issue by SimenB** [yarnpkg/berry#2065]
- [ ] I'd be willing to implement a fix

**Describe the bug**

During a rebase I had a conflict in `yarn.lock` - I then ran `yarn` and got

>➤ YN0048: Automatically fixed merge conflicts 👍

However, the leading comment in the file was removed

```diff
diff --git a/yarn.lock b/yarn.lock
index 73b84ede42..e25f20f54a 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -1,6 +1,3 @@
-# This file is generated by running "yarn install" inside your project.
-# Manual changes might be lost - proceed with caution!
-
 __metadata:
   version: 4
   cacheKey: 7
```

Running `yarn` again reinstates the comment.

**To Reproduce**

Have a merge conflict in `yarn.lock` and run `yarn` for the automerging.

**Screenshots**

N/A

**Environment if relevant (please complete the following information):**

 - OS: macOS
 - Node version 14.15.0
 - Yarn version `2.3.3-git.20201026.e34bf6c6`

**Additional context**

N/A

**Comment by arcanis** [comment]
Did you run Ctrl-C midway? The comment will be removed on merge conflict resolution, but reinstated once we finish the fetching step.

**Comment by SimenB** [comment]
No, I let it run to completion. I've deleted the branches, but I can attempt to restore them

**Comment by SimenB** [comment]
I'm unable to reproduce now, so I must have quit it early or something... Sorry about the false alarm
