### ISSUE TITLE
[Bug] : Possible EventEmitter memory leak detected. 

### ISSUE THREAD

**Issue by xenoterracide** [yarnpkg/berry#2072]
pretty sure this is coming from yarn itself, as I've only seen it happen when running `yarn workspaces foreach`

```ts
➤ YN0000: MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```
this is the command I'm running
```
    "build:graph": "yarn ts/app/service/packages/graph workspaces foreach --parallel --topological --verbose --recursive run build",
```
it only really seems to happen when there are a lot of workspaces being run, on approximately the 7-8  module to be run (I'm not sure if it's at the beginning or end of the module)

**Comment by merceyz** [comment]
Some context:

@paul-soporan Looked into this a while ago and discovered that warning comes from `plugin-interactive-tools -> ink -> yoga-layout-prebuilt -> nbind`
