### ISSUE TITLE
Snapcraft support

### ISSUE THREAD

**Issue by JonasKruckenberg** [yarnpkg/berry#2075]
- [x] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

The installation on ubuntu/debian, while straightforward in theory is cumbersome and easy to get wrong. [Snapcraft](https://snapcraft.io/) serves as a next generation package manager for debian derivatives. This would greatly reduce the complexity when installing yarn. ( the command would be `sudo snap install yarn` ) 

**Describe the solution you'd like**

Create a snapcraft.yaml file for yarn and a snapcraft store listing.

**Describe the drawbacks of your solution**

This should not change anything if implemented correctly.

**Describe alternatives you've considered**

The current install method and the snap would exist side by side, the snap merely serving as another option.

**Comment by arcanis** [comment]
We intend Yarn to be installed by [Corepack](https://github.com/nodejs/corepack) in the future, which would avoid us from having to handle different publish targets (like the snap store).

**Comment by JonasKruckenberg** [comment]
I see, how is the support though? 
The corePack's readme says "starting from Node 15". I have node 15 installed yet yarn does not work.
Still having it integrated would be nice yes!

**Comment by arcanis** [comment]
It's still a work in progress: https://github.com/nodejs/node/pull/35398

**Comment by JonasKruckenberg** [comment]
Alright, seems like it's going along pretty well, so setting up snapcraft as an interim solution would be silly.
Still, thanks for your response!
Cheers!
