### ISSUE TITLE
[Bug] Yarn 2 install Failed with errors on react-scripts 4

### ISSUE THREAD

**Issue by Kizmar** [yarnpkg/berry#2077]
- [ ] I'd be willing to implement a fix

**Describe the bug**
**_I don't know if this is a Yarn issue, or a react-scripts issue..._** 

I just deleted our `yarn.lock` and `node_modules` folder so I could run a clean `yarn install` to debug an issue with CI. Long story short, I debugged this by removing all dependencies and slowly added them back in while running `yarn install` to see which one was causing the error below. Come to find out, it's `react-scripts: 4.0.0` that's causing it.

The error in question:
> YN0066: │ fsevents@patch:fsevents@npm%3A2.2.0#builtin<compat/fsevents>::version=2.2.0&hash=127e8e: Cannot apply hunk #1 (set enableInlineHunks for details)
> ...
> YN0000: Failed with errors in 25s 499ms

**To Reproduce**
Run `yarn add react-scripts --dev` does it for me - or - run `yarn install` with `react-scripts: 4.0.0` already in your `package.json` dependencies.

**Environment if relevant (please complete the following information):**

 - OS: Windows 10
 - Node version 12.19.0 & just installed Node 14.15.0 (same result)
 - Yarn version 2.3.3 (yarnPath: .yarn/releases/yarn-berry.cjs)

**Additional context**

I also tried re-installing react-scripts on a global level and running `yarn install` again but got the same result.

**Comment by merceyz** [comment]
fsevents released a new version 4 hours ago so seems we need to update the patch 
https://registry.yarnpkg.com/fsevents/2.2.0
