### ISSUE TITLE
[Bug] fsevent 2.2.1, patch does not apply

### ISSUE THREAD

**Issue by jacogr** [yarnpkg/berry#2089]
Seems like I'm stuck atm where a dependency of a dependency cannot be patched. Specifically -

`fsevents@patch:fsevents@npm%3A2.2.1#builtin<compat/fsevents>::version=2.2.1&hash=127e8e: Cannot apply hunk #1 (set enableInlineHunks for details)`

So this PR https://github.com/yarnpkg/berry/pull/2078 seems to fix until 2.2.0, however it is 2.2.1 above. Sadly, this has not got me to a grinding halt using upgrade-interactive.

**Comment by merceyz** [comment]
Fixed in #2078, just tested and it applies cleanly with that. See https://github.com/yarnpkg/berry/pull/2078#issuecomment-721313385 for how to use it before release
