### ISSUE TITLE
[Feature] Get the latest version of workspace-tools plugin

### ISSUE THREAD

**Issue by brandon-leapyear** [yarnpkg/berry#2092]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

https://github.com/yarnpkg/berry/pull/1986 was merged about two weeks ago, but `yarn workspaces foreach` doesn't have the `-R` option for me, still, and there's no way for me to quickly get the latest version of the plugin.

**Describe the solution you'd like**

It seems like the compiled version at https://github.com/yarnpkg/berry/raw/master/packages/plugin-workspace-tools/bin/%40yarnpkg/plugin-workspace-tools.js is old and isn't kept up to date with new changes. A simple solution would be to just compile that file when merging to master.

**Describe the drawbacks of your solution**

**Describe alternatives you've considered**

Currently working around by manually cloning the repo, running `yarn build:plugin-workspace-tools`, and copy `packages/plugin-workspace-tools/bundles/@yarnpkg/plugin-workspace-tools.js` as `.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs`

**Additional context**

**Comment by paul-soporan** [comment]
> Currently working around by manually cloning the repo, running yarn build:plugin-workspace-tools, and copy packages/plugin-workspace-tools/bundles/@yarnpkg/plugin-workspace-tools.js as .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs

You're looking for `yarn plugin import from sources workspace-tools` ([Command Documentation](https://yarnpkg.com/cli/plugin/import/from/sources)) which does the exact same thing you've done. 🙂 

> It seems like the compiled version at master/packages/plugin-workspace-tools/bin/%40yarnpkg/plugin-workspace-tools.js (raw) is old and isn't kept up to date with new changes. A simple solution would be to just compile that file when merging to master.

That file is only compiled when a new release is made, as `yarn plugin import workspace-tools` (which uses that file) is supposed to give you the latest stable release, not the one on master.

**Comment by brandon-leapyear** [comment]
ah exactly what I was looking for, thank you! Can it be added somewhere in the workspaces page maybe?
