### ISSUE TITLE
Support for types in publishConfig

### ISSUE THREAD

**Issue by remorses** [yarnpkg/berry#2102]
I would like to change the `types` field during publishing via `publishConfig` but this field now supports only `main` `module` and `browser`, can we add the possibility to add `types`?

My use case: i have a big monorepo and i want to use auto completion and go to definition without having to compile type declarations but i cannot change the `main` field because i have js  packages in the monorepo that cannot consume typescript directly

**Comment by arcanis** [comment]
The `publishConfig.types` field support is part of the `typescript` plugin:

```
yarn plugin import typescript
```
