### ISSUE TITLE
VSCode tsconfig.json external extends

### ISSUE THREAD

**Issue by elmpp** [yarnpkg/berry#2111]
Tsconfig.json files allow `extends` allow package references but the VSCode JSON editor assumes standard n__m resolution.

![](https://cdn.discordapp.com/attachments/654372321225605128/775654885508907048/Screenshot_2020-11-10_at_10.32.33.png)

[This issue](https://github.com/tsconfig/bases/issues/1) mentions a bit more background

This is probably an issue for the VSCode guys but holding off opening issue with them on [mercey'sz advice](https://discord.com/channels/226791405589233664/654372321225605128/775659219584024586)

**Comment by merceyz** [comment]
> it's a simple approximation in the vscode side
> https://github.com/microsoft/vscode/blob/325cb4a67d5f3ef38123d7e5e9e4a3e8a2d5f000/extensions/typescript-language-features/src/languageFeatures/tsconfig.ts#L35
> @orta 

I'll close this then since it's an issue in VSCode

**Comment by AlCalzone** [comment]
I can't read the discord link - what's the plan going forward? The TS team seems to be a bit hesitant on adding PnP support, which is unfortunate.
