### ISSUE TITLE
[Bug] Promisified fs.read calls return a different result when run with Yarn PnP than through Node

### ISSUE THREAD

**Issue by Mike-Dax** [yarnpkg/berry#2127]
- [x] I'd be willing to implement a fix

**Describe the bug**

Promisified `fs.read` returns the number of bytes read instead of an object containing the `buffer` and the `bytesRead`.

**To Reproduce**

https://github.com/Mike-Dax/promisified-fs-read-bug

```
// test.js
const fs = require("fs");
const { promisify } = require("util");
const fsReadAsync = promisify(fs.read);

const path = require("path");

async function main() {
  // Setup the file
  const p = path.join(__dirname, "./test.txt");
  fs.writeFileSync(p, "hey");

  // Read the file
  const fd = fs.openSync(p);
  const buffer = Buffer.alloc(16);
  const ret = await fsReadAsync(fd, buffer, 0, 4, null);

  console.log(ret);

  console.log(buffer.toString());
}

main();
```

The results are:

`yarn node test.js`

```
3
hey
```

`node test.js`

```
{
  bytesRead: 3,
  buffer: <Buffer 68 65 79 00 00 00 00 00 00 00 00 00 00 00 00 00>
}
hey
```

**Additional context**

This seems to be the root cause of https://github.com/serialport/node-serialport/issues/2158

**Comment by merceyz** [comment]
> https://nodejs.org/api/fs.html#fs_fs_read_fd_buffer_offset_length_position_callback
> If this method is invoked as its util.promisify()ed version, it returns a Promise for an Object with bytesRead and buffer properties.

That seems to be implemented here in node https://github.com/nodejs/node/blob/dc79f3f37caf6f25b8efee4623bec31e2c20f595/lib/fs.js#L559-L560
