### ISSUE TITLE
Github flavor dependencies not supported [Bug]

### ISSUE THREAD

**Issue by lroling8350** [yarnpkg/berry#213]
**Describe the bug**

Npm package.json documentation https://docs.npmjs.com/files/package.json#github-urls states that a dependency can just be the <user>/<repo> and it will correctly resolve the github dependency. I am listing this as a bug because Yarn V1 supports this. I'm personally not using this style of dependency in my package.json but react-native-json-tree -> react-base16-styling is and i don't have control over it. I've tried various attempts to use resolutions but it hasn't seemed to work. 

**To Reproduce**

in any project setup with Berry run `yarn add react-native-json-tree` and it will fail stating 
`➤ YN0010: │ base16@Dean177/base16-js isn't supported by any available resolver`

**Comment by arcanis** [comment]
Hey! I think it should be a matter of adding the right regexp here - wanna try to open a PR? 😃

https://github.com/yarnpkg/berry/blob/master/packages/plugin-github/sources/githubUtils.ts#L7-L14

**Comment by lroling8350** [comment]
I'll give it a shot, thank you for giving me a direct link to it

**Comment by arcanis** [comment]
I encountered this problem myself so I went ahead and fixed it, but thanks for the bug report nonetheless! Feel free to ping us on Discord if you're interested in other contributions! ✌

**Comment by jayrylan** [comment]
@arcanis I'm actually hitting this again with `v2.0.0-rc.19` and the following in my `package.json`:

```json
{
  "dependencies": {
    "uWebSockets.js": "uNetworking/uWebSockets.js#v16.4.0"
  }
}
```

**Comment by arcanis** [comment]
Can you open another thread along with the Sherlock repro? It's easier for us to track current bugs this way. Thanks!
