### ISSUE TITLE
Case study(?) - Whats wrong with building a command line tool like that?

### ISSUE THREAD

**Issue by jeffrson** [yarnpkg/berry#2131]
Well, please bear with me. Actually I would have posted this as a case study, but it doesn't quite meet the questionaire. So I'm starting blank.

I have a package, say packageCmd, that provides a "binary" (npm script) to serve as a command line tool.  The package has thoroughly filled all dependencies: a simple "yarn start" (with berry) that executes the same js file as the packageCmd launcher runs fine.

Now I want to install that command line tool, locally as a dependency inside an "installation folder".

With yarn1 the bin script is installed to node_modules/.bin as packageCmd. I can run it by "npx packageCmd". That's fine.

However, with yarn2 (yarn run packageCmd or via npx in package script) I get error messages about missing dependencies.

So what is the "recommended" solution for this case? Should I really duplicate all dependencies of the original package? This would be rather bad, because the user shouldn't need to know about it. Furthermore, as soon as I add another dependency to packageCmd I need to update the "installation".

BTW, providing a binary is just a work-around, since adding the dependency and calling into packageCmd gives the same dependency errors. Unfortunately it didn't quite help...

I'm looking into yarn2 for this specific case because of zero installs.

**Comment by merceyz** [comment]
> or via npx in package script

Just a quick note, don't use npx with Yarn as it's not compatible, you can just do `yarn <my-bin-name>

**Comment by arcanis** [comment]
It's difficult to help you without a repro to be sure we have the same setup in mind. Can you make a minimal reproduction and the command that doesn't work as you expect (+ after making sure you don't use `npx`).

**Comment by jeffrson** [comment]
Yep, but it behaves the same...

**Comment by jeffrson** [comment]
Hmmm, while I was preparing the reproduction I realized that it seems to work like I thought it should :-) - at least in a general case.

However, when my "command line tool" has a dependency that fails to declare correct peer dependencies then it won't work. I know I need to work with packageExtensions - but where should I define it?

The repo is at https://github.com/jeffrson/yarn_cmd_tool - there's lib, which uses a package that's missing a peerDependency (nats). Then there is app, which is using lib and specifies the packageExtension for nats. app works as intended when I run it (yarn start).

Now I want to "use" the app as a local "binary". I initialize yarn2 (yarn set version berry) in "use" and install dependencies. But yarn start fails (again missing nats) as long as **"use" doesn't declare the packageExtension itself**. It cannot make use of the packageExtension in app.

**Comment by merceyz** [comment]
> Now I want to "use" the app as a local "binary". I initialize yarn2 (yarn set version berry) in "use" and install dependencies. But yarn start fails (again missing nats) as long as "use" doesn't declare the packageExtension itself. It cannot make use of the packageExtension in app.

This is expected, you can make a PR upstream to add the missing peer dependency and one to our [compat-plugin](https://github.com/yarnpkg/berry/blob/master/packages/plugin-compat/sources/extensions.ts)

**Comment by merceyz** [comment]
Closing as this is expected behaviour
