### ISSUE TITLE
[Case Study] Storybook in workspaces

### ISSUE THREAD

**Issue by brandon-leapyear** [yarnpkg/berry#2133]
**What package is covered by this investigations?**

* `@storybook/react`

**Describe the goal of the investigation**

Why does `@storybook/core` fail to load a dependency from its webpack configuration when run in a workspace, but does not fail when there's only one package in the project?

**Investigation report**

Storybook uses webpack internally to build its stories, and I add some extra webpack loaders like
```
// .storybook/main.js
module.exports = {
  "stories": ["../src/**/*.stories.tsx"],
  webpackFinal: (config) => {
    config.module.rules.push({
      test: /\.tsx$/,
      loaders: ['ts-loader'],
    })

    return config
  }
}
```
I have `ts-loader` defined in the `package.json`, so it should be visible by the workspace, yet running storybook gives me an error like
```
ERROR in ./.storybook/preview.tsx-generated-config-entry.js
Module not found: Error: @storybook/core tried to access ts-loader, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```
Note: This is an error because the loader is needed by `.storybook/preview.tsx`, but if `preview.tsx` didn't exist, it would just be a warning (and none of the stories would load)

See repro: https://github.com/brandon-leapyear/yarnpkg-berry-repro-2133

**Comment by arcanis** [comment]
> Why does `@storybook/core` fail to load a dependency from its webpack configuration when run in a workspace, but does not fail when there's only one package in the project?

https://yarnpkg.com/features/pnp#different-behaviours-based-on-workspace--not-a-workspace

**Comment by merceyz** [comment]
See https://yarnpkg.com/features/pnp#different-behaviours-based-on-workspace--not-a-workspace

**Solution:**
What your config is doing is telling storybook to resolve `ts-loader` for you, but it can't since it doesn't declare it, this means you need to resolve it up front before passing it to storybook.
```diff
// .storybook/main.js
module.exports = {
  "stories": ["../src/**/*.stories.tsx"],
  webpackFinal: (config) => {
    config.module.rules.push({
      test: /\.tsx$/,
-      loaders: ['ts-loader'],
+      loaders: [require.resolve('ts-loader')],
    })

    return config
  }
}
```

**Comment by brandon-leapyear** [comment]
@merceyz thanks! is this "the correct solution", or should I make a PR against Storybook to make this builtin?

**Comment by merceyz** [comment]
Unsure, i'll cc @gaetanmaisse for that one, unsure if you can tell webpack where to resolve the loaders from :thinking:

**Comment by brandon-leapyear** [comment]
So `require.resolve` works. I tried doing
```diff
// .storybook/main.js
module.exports = {
  "stories": ["../src/**/*.stories.tsx"],
  webpackFinal: (config) => {
+   config.context = path.resolve(__dirname, '..')
    config.module.rules.push({
      test: /\.tsx$/,
      loaders: ['ts-loader'],
    })

    return config
  }
}
```
But that didn't work. What would you suggest `context` would be?

**Comment by gaetanmaisse** [comment]
@brandon-leapyear for me it's the correct solution as `main.js` is a configuration file of Storybook and so we want anything used in that file to be resolved in the context of your project and not from `@storybook/core`, to be sure the dependency is available. Does it make sense to you?

**Comment by brandon-leapyear** [comment]
Makes sense to me!
