### ISSUE TITLE
[Feature] Silent install

### ISSUE THREAD

**Issue by mattoni** [yarnpkg/berry#2139]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

When doing CI builds via Docker, the output generated by yarn install is very verbose. In yarn 1 we had a --silent option, but it doesn't seem to exist in v2.

**Describe the solution you'd like**

Parity with v1

**Describe the drawbacks of your solution**

**Describe alternatives you've considered**

**Additional context**

**Comment by merceyz** [comment]
Set `CI=true` in your docker env

**Comment by arcanis** [comment]
And next version will have `logFilters`, and of course you can simply hide the output except if there's an error ([example](https://serverfault.com/a/607903/141719)).

**Comment by mattoni** [comment]
Thanks so much for the quick responses!

**Comment by IanVS** [comment]
Is there a way to use `logFilters` to replicate `--silent` from V1?  In some cases, I want to make sure that no info/warning output is displayed at all.  And I don't want to create a separate bash script just to do this.  Is there a general verbosity setting that I am not finding?

**Comment by arcanis** [comment]
This isn't possible. Just use your standard shell feature: `yarn |& :`, or `yarn >& /dev/null`.

**Comment by Jay-flow** [comment]
Is it still impossible? Is there any update?
