### ISSUE TITLE
[Case Study] Can't find tslib with rollup-plugin-typescript2

### ISSUE THREAD

**Issue by brandon-leapyear** [yarnpkg/berry#2140]
**What package is covered by this investigations?**

* `rollup`
* `rollup-plugin-typescript2`

**Describe the goal of the investigation**

Why does rollup fail?

**Investigation report**

Related: https://github.com/ezolenko/rollup-plugin-typescript2/issues/12
Minimal repro: https://github.com/brandon-leapyear/yarnpkg-berry-repro-2140

I'm getting an error like
```
[!] (plugin rpt2) Error: /Users/bchinn/Desktop/foo/index.ts(3,16): semantic error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.
```

Which is odd to me because `rollup-plugin-typescript2` declares `tslib` as a dependency ([link](https://github.com/ezolenko/rollup-plugin-typescript2/blob/5ce7676ad0451df81e61190d42694f97085111fc/package.json#L64)). I can solve the error by adding `tslib` to my own `devDependencies`, but I'm wondering if that's the actual solution, or if there's something else going on.

**Comment by SagnikPradhan** [comment]
Probably because the plugin uses your work-space's `typescript` which does not have access to the plugin's dependencies.

**Comment by brandon-leapyear** [comment]
Even if the plugin is the one calling `require('typescript')`?
https://github.com/ezolenko/rollup-plugin-typescript2/blob/master/src/index.ts#L73

**Comment by SagnikPradhan** [comment]
Yep, because plugin has typescript declared as peer dependency.

**Comment by brandon-leapyear** [comment]
I see. So unless the plugin moves `typescript` into `dependencies`, there's no way around the user needing to install `tslib`? If that's the case, I'll make a PR on the plugin adding this step for pnp environments

**Comment by merceyz** [comment]
> I can solve the error by adding tslib to my own devDependencies, but I'm wondering if that's the actual solution, or if there's something else going on.

That is the correct solution, TypeScript is trying to resolve `tslib` from your package so it is the one that needs to declare it. The same is true for other package managers but hoisting magically makes it work though it's inherently broken https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies
