### ISSUE TITLE
[Feature] Provide an environment variable pointed to the location of package.json

### ISSUE THREAD

**Issue by brandon-leapyear** [yarnpkg/berry#2145]
- [x] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Following [this guide](https://yarnpkg.com/getting-started/qa#how-to-share-scripts-between-workspaces), I can write a global script by giving the script a name with a colon. So I do
```json
// package.json
{
  "scripts": {
    "g:lint": "eslint --ext .js,.ts,.tsx"
  }
}

// foo/package.json
{
  "scripts": {
    "foo": "foo && yarn g:lint ."
  }
}
```

But then I realize that ESLint plugins I define in the top-level `package.json` won't be used when calling `foo`. So I can change it to
```diff
// foo/package.json
{
  "scripts": {
-   "foo": "foo && yarn g:lint ."
+   "foo": "foo && yarn g:lint . --resolve-plugins-relative-to .."
  }
}
```

Which solves that problem for now. But ideally, we'd like the top-level `package.json` to define
```diff
// package.json
{
  "scripts": {
-   "g:lint": "eslint --ext .js,.ts,.tsx"
+   "g:lint": "eslint --ext .js,.ts,.tsx --resolve-plugins-relative-to $HERE"
  }
}
```
where `$HERE` is the directory of the `package.json` file that defines the global command, NOT the directory of the `package.json` file running the current command (which is what `$INIT_CWD` is for).

**Describe the solution you'd like**

Define some env var like `$THIS_DIR` or something that would be expanded to the directory of the `package.json` file the env var is written in.

**Describe the drawbacks of your solution**

Adds another "special" environment variable to the package.json script context, which might not be in Yarn's interest.

**Describe alternatives you've considered**

Could ask ESLint to allow defining `resolvePluginsRelativeTo` in the `.eslintrc.js` file, which means you could use `__dirname`. But I do see that they might be [revamping their configuration](https://github.com/eslint/eslint/issues/13481), and I'm not sure how much value it would provide ESLint users outside of this particular example.

**Additional context**

**Comment by brandon-leapyear** [comment]
Just found out that the current working directory when using a global command is set to what I want, so one could do
```json
{
  "global:lint": "HERE=$(pwd) && cd $INIT_CWD && eslint --resolve-plugins-relative-to $HERE"
}
```
(but notably NOT `$PWD`)

I still think it might be nice to have a `$THIS_DIR` variable automatically provisioned, but the workaround works for us

**Comment by merceyz** [comment]
Closing as we now have `$PROJECT_CWD` to point to the root of the project, otherwise using `$(pwd)` is the correct way to get the current directory
