### ISSUE TITLE
[Bug] Unexpected end of JSON input when adding dependency

### ISSUE THREAD

**Issue by Fernando-Marquardt** [yarnpkg/berry#2151]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I am trying to use the yarn from sources (yarn set version from sources) to get the fsevetns 2.2.x patch. But after installing this version I always get Syntax Error: Unexpected end of JSON input. I tried to debug the issue and it seems to be an empty Buffer in the HttpUtils get function.

**To Reproduce**

This happens if I try to add any dependency, just chose clsx for being small.

yarn set version berry
yarn init --private
yarn set version from sources
yarn add clsx

**Screenshots**

![image](https://user-images.githubusercontent.com/901883/99728088-a3b66500-2a97-11eb-8120-e41913da2d3d.png)

**Environment if relevant (please complete the following information):**

 - OS: Windows
 - Node version 14.0.0
 - Yarn version 2.3.3-git.20201119.385a2667

**Additional context**

**Comment by merceyz** [comment]
It's a bug in node, update your node version. ref https://github.com/sindresorhus/got/issues/1496

**Comment by Fernando-Marquardt** [comment]
Indeed, upgrading the node worked. There is no way of adding a warning to avoid these node versions 14.0 and 14.1 (the ones that seems to be affected)?

I did some research before opening this issue and the got issues never poped up for me. I don't know how many people may be affected by this issue when the next yarn release comes out.

**Comment by merceyz** [comment]
> There is no way of adding a warning to avoid these node versions 14.0 and 14.1 (the ones that seems to be affected)?

There is, we could add a check here https://github.com/yarnpkg/berry/blob/8d79530d378aea1202e762b38c686fea2f4a9e67/packages%2Fyarnpkg-cli%2Fsources%2Fmain.ts#L64-L68
