### ISSUE TITLE
[Bug] Failed to run "yarn pnpify --sdk vscode"

### ISSUE THREAD

**Issue by jakepearson** [yarnpkg/berry#2153]
- [x] I'd be willing to implement a fix

**Describe the bug**

One of the developers on my team has been unable to run `yarn pnpify --sdk vscode` from the folder where our `yarn/berry` project is. He gets the following error:

```
Internal Error: spawn —sdk ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
No one else on our team has the same problem so we assume it a problem with his computer's config, but was hoping we could get some direction on how to diagnose the issue. 

In trying to reproduce, I was able to get a similar stack trace by calling `yarn pnpify help`. I would be happy to help work on a fix or better error message if you could point me in the right direction.

**To Reproduce**

1. Navigate to a folder that contains a `yarn/berry` project
2. Run `yarn pnpify --sdk vscode`

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version v14.11.0
 - Yarn version 2.3.3

**Additional context**

He is using `asdf` so we thought that might be the culprit so we deleted all of `asdf` and installed `node` and `npm` via `brew` and than `yarn` via `npm install -g yarn` and got the same error.

**Comment by jakepearson** [comment]
He switched to `yarn dlx @yarnpkg/pnpify --sdk vscode` and the command worked.

**Comment by merceyz** [comment]
Glad you found a solution, but we suggest commiting the result of that command so only one person has to run it. https://yarnpkg.com/getting-started/migration#editor-support

**Comment by jakepearson** [comment]
> Glad you found a solution, but we suggest commiting the result of that command so only one person has to run it. https://yarnpkg.com/getting-started/migration#editor-support

Agreed, that didn't work for us. All working now. Thanks!
