### ISSUE TITLE
Not clear how to migrate to YARN2 (accessing files from packages)

### ISSUE THREAD

**Issue by MartinH0** [yarnpkg/berry#2155]
ATM I use yarn (v1) and wanted to upgrade to yarn 2 asap to not having to do it later.

The project I start with is very small.
I just use:
```
  "devDependencies": {
    "bootstrap": "^5.0.0-alpha2",
    "grunt": "^1.3.0",
    "grunt-cli": "^1.3.2",
    "grunt-contrib-cssmin": "^3.0.0",
    "grunt-contrib-uglify": "^5.0.0",
    "popper.js": "^1.16.1",
  }
```

Now as I also use grunt I used to pull the `.js` and `.css` files from `node_modules` which now ofc not exist anymore.
My Gruntfile.js looked like this:

```
module.exports = function(grunt) {
        // Project configuration.
        grunt.initConfig({
                pkg: grunt.file.readJSON('package.json'),
                uglify: {
                        options: {
                                compress: true
                        },
                        my_target: {
                                files: {
                                        'public/js/app.min.js': ['node_modules/bootstrap/dist/js/bootstrap.js']
                                        'public/js/login.min.js': ['node_modules/bootstrap/dist/js/bootstrap.js', 'source/js/cpyrgt.js'],
                                },
                        },
                },
                cssmin: {
                        options: {
                                mergeIntoShorthands: false,
                                roundingPrecision: -1
                        },
                        target: {
                                files: {
                                        'public/css/app.min.css': ['node_modules/bootstrap/dist/css/bootstrap.min.css']
                                        'public/css/login.min.css': ['node_modules/bootstrap/dist/css/bootstrap.min.css', 'source/js/correction.js']
                                },
                        },
                },
        });
        grunt.loadNpmTasks('grunt-contrib-uglify');
        grunt.loadNpmTasks('grunt-contrib-cssmin');
        // Default task.
        grunt.registerTask('default', ['uglify', 'cssmin']);
};
```

So far so good. But how exactly do I now (for example) access the file **`bootstrap.js`** with the new PnP setup?
How exactly does my Gruntfile.js have to look to be able to now access any `.js` and `.css` file inside the new .zip packages?
I already red the [migration](https://yarnpkg.com/getting-started/migration) page several times, but may I'm just missing something?

A example of any Gruntfile.js befor and after (v1/v2) would be really appreciated! Just dont know how exactly to access the files now.

BTW, using:
yarn: v2.3.3
grunt-cli: v1.3.2
grunt: v1.3.0

**Comment by arcanis** [comment]
Can you share an actual error and repro? Afaik this should work fine without particular change, at least the fs part.

**Comment by merceyz** [comment]
> But how exactly do I now (for example) access the file bootstrap.js with the new PnP setup?

Use `require.resolve` to get the path to it
```js
require.resolve('bootstrap/dist/js/bootstrap.js')
require.resolve('bootstrap/dist/css/bootstrap.min.css')
```

**Comment by merceyz** [comment]
Closing as the solution here is to use `require.resolve` to locate your dependencies, hardcoding the path is not a good idea even when using the `node_modules` layout as when you're in a monorepo Yarn might hoist it futher up the tree or not at all depending on your dependency tree meaning unrelated dependency changes could fail your build
