### ISSUE TITLE
[Feature] `yarn version check` should omit private packages

### ISSUE THREAD

**Issue by borekb** [yarnpkg/berry#2162]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Some of our workspaces are published to npm, some are `private: true`. Running `yarn version check` seems to also evaluate private packages which leads to errors in our case, we don't need/want to bump versions for our `private: true` workspaces.

**Describe the solution you'd like**

I think that `private: true` packages should be excluded from `yarn version check` as they don't undergo a release / publishing workflow.

**Describe the drawbacks of your solution**

Maybe if some people have `private: true` yet somehow publish the package (though npm refuses this, and I think that one of the main purposes of `private: true` is to prevent accidental publication).

**Describe alternatives you've considered**

I tried removing the `version` field entirely, which makes `yarn version check` happy. But then, when I consume the library (workspace) in another workspace like this:

```js
{
  "dependencies": {
    "@company/lib": "*"
  }
}
```

then the `yarn` installation fails.

**Workaround**

It's possible to add this to `.yarnrc.yml`:

```yaml
changesetIgnorePatterns:
  - 'lib/**'
```

**Comment by arcanis** [comment]
No, that's expected - if you bump your local, private, package, then it might affect how its dependent will be built (for example it could be a Babel preset). If you don't want a workspace to affect the release process, then don't assign it a version at all (Yarn will use 0.0.0, and won't bother you on `version check`).

**Comment by borekb** [comment]
Makes sense. However, when I remove the `version` field entirely, then `yarn` install fails for me, complaining something like this:

```
➤ YN0000: ┌ Resolution step
➤ YN0001: │ HTTPError: @company/lib@npm:*: Response code 404 (Not Found)
    at o.<anonymous> (/Users/borekb/dev/company/project/packages/.yarn/releases/yarn-2.2.0.cjs:23:12912)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
➤ YN0000: └ Completed in 1.21s
```

The only "workaround" I currently found is to use the `changesetIgnorePatterns` in `.yarnrc.yml`.

**Comment by merceyz** [comment]
Have you tried using the workspace protocol?

**Comment by borekb** [comment]
No – I know it exists but wasn't necessary before. I kind of like that `package.json` doesn't contain Yarn-specific protocols but it might be another solution...

**Comment by arcanis** [comment]
How exactly are you referring to `@company/lib` in your dependencies?

**Comment by borekb** [comment]
Currently like this:

```js
{
  "dependencies": {
    "@company/lib": "*"
  }
}
```

**Comment by arcanis** [comment]
Yep, seems to be because of these lines:

https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/sources/Workspace.ts#L113-L114

I don't know if that should be constructed as a bug; both behaviors make sense to me 🤔 will think about it, for now use the `workspace:*` descriptor instead.

**Comment by borekb** [comment]
To me, it would make intuitive sense what you've hinted at above: that if there's no `version` field, Yarn treats it as 0.0.0.

In that sense, my expectation would be that depending on `@company/lib@*` works even if `lib` doesn't have any `version` (it has 0.0.0 implicitly).
