### ISSUE TITLE
[Bug] yarn pack with an empty files array includes unwanted files

### ISSUE THREAD

**Issue by mskelton** [yarnpkg/berry#2166]
- [x] I'd be willing to implement a fix (possibly, though I've never contributed to Yarn before so I would need some guidance)

**Describe the bug**

When using an empty `files` array in package.json, Yarn treats it as if the files array is missing.  This results in two unwanted behaviors:

1. The "files" property is removed when running `yarn`
1. Running `yarn pack` will include unwanted files.

Using an empty `files` array is a perfectly valid technique of excluding everything if the only parts of a package that should be packed are the `main` file, readme, etc. The workaround I found is to set `files` to the `main` file, which while it works, this behavior was an unexpected change when upgrading to Yarn berry so I thought it would be good to open an issue since this appears to be a bug.

**To Reproduce**

https://github.com/mskelton/yarn-pack-repro

package.json

```json
{
  "name": "yarn-pack-repro",
  "main": "index.js",
  "files": []
}
```

output
```sh
yarn pack --dry-run
➤ YN0000: .editorconfig
➤ YN0000: .gitattributes
➤ YN0000: index.js
➤ YN0000: README.md
➤ YN0000: package.json
➤ YN0000: Done in 0s 13ms
```

As you can see from the output, Yarn included `.editorconfig` and `.gitattributes` in the output which was not expected or desired.

It appears the issue stems from this line in `Manifest.ts` where it checks if the array is empty before setting the files property of the manifest. By not setting the property, there is no way to distinguish between an empty array and a missing `files` key in package.json.

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version 12
 - Yarn version 2.3.3

**Comment by arcanis** [comment]
Indeed, that seems like a bug! Do you want to try to PR the fix? Our contribution guide is [here](https://yarnpkg.com/advanced/contributing), and we're often available on Discord if you have questions!

**Comment by mskelton** [comment]
Sure, I'd be happy to take a stab at a PR.  I'm assuming the solution is changing the `Manifest.ts` file to still set the `files` property if the key in package.json was set, even if empty.  Does that align with your expectations?

**Comment by arcanis** [comment]
Yep 👍
