### ISSUE TITLE
[Feature] Update `gatsby-remark-table-of-contents` dependency to npm

### ISSUE THREAD

**Issue by signalwerk** [yarnpkg/berry#2170]
Since @arcanis did an awesome job with a [PR](https://github.com/signalwerk/gatsby-remark-table-of-contents/pull/9) to the original Repo [this dependency](https://github.com/yarnpkg/berry/blob/7d9b64288d292af1ab147dff6f11f3c59a4b0ed7/packages/gatsby/package.json#L43) can be switched to the official npm-package. The feature is integrated since Version `0.1.0` and the latest version (`0.2.1`) can be used since there is no regression or api-change in the newer versions. 

I would be happy if a maintainer could do that since I'm not involved in that project.

((I'm the maintainer of `gatsby-remark-table-of-contents`))

**Comment by merceyz** [comment]
Done in https://github.com/yarnpkg/berry/pull/3009

**Comment by signalwerk** [comment]
Awesome. Thank you!
