### ISSUE TITLE
[Bug] Script not named after package can't be detected

### ISSUE THREAD

**Issue by nicholaschiang** [yarnpkg/berry#2179]
**Describe the bug**

When running a script that isn't named after the package name, Yarn Berry is unable to find it. For example, when running the `percy` command provided by [`@percy/cypress`](https://npmjs.com/package/@percy/cypress), it seems to fail:
```
nchiang@eevee ~/repos/tutorbook (develop) $ yarn percy
Usage Error: Couldn't find a script named "percy".

$ yarn run [--inspect] [--inspect-brk] <scriptName> ...
```
But the `node_modules/.bin/percy` file definitely exists. When running with Yarn v1 or `npx`, it works fine.

**To Reproduce**

1. Create a new repository (or just clone [this repro](https://github.com/nicholaschiang/yarn-script-bug)) with this `package.json`:
```json
{
  "name": "yarn-script-bug",
  "version": "1.0.0",
  "main": "index.js",
  "author": "Nicholas Chiang",
  "license": "MIT",
  "devDependencies": {
    "@percy/cypress": "^2.3.2",
    "cypress": "^6.0.0"
  }
}
```
2. Install dependencies using `yarn`.
3. Try running `yarn percy` and see error.
4. Try running `npx percy` and see that it works.

**Comment by arcanis** [comment]
There is no binary defined in `@perry/cypress`: https://cdn.jsdelivr.net/npm/@percy/cypress@2.3.2/package.json

**Comment by merceyz** [comment]
`@percy/cypress` does not provide a binary under the name `percy`, it's provided by `@percy/agent` which you don't depend on so you're not allowed to run it. Add `@percy/agent` to your dependencies if you want to run it

https://cdn.jsdelivr.net/npm/@percy/cypress@2.3.2/package.json
https://cdn.jsdelivr.net/npm/@percy/agent@0.28.5/package.json

**Comment by nicholaschiang** [comment]
Why is there a `percy` binary in `node_modules/.bin` then when I only install `@percy/cypress`? Why does it work when I run `npx` or an older version of `yarn`?

**Comment by nicholaschiang** [comment]
@merceyz and @arcanis that makes sense. When I install [`percy`](https://npmjs.com/package/percy) (same as `@percy/agent`) it works fine. That leaves me with a couple of questions about this weird behaviour:
- Why is there a `percy` binary in `node_modules/.bin`? 
- Why does it work when I run `npx` or an older version of `yarn`?
- Why does it work with `npm` in [the Percy demo repo](https://github.com/percy/example-percy-cypress) (where only `@percy/cypress` is included)?
