### ISSUE TITLE
[Bug] In nested worktrees, Yarn exhibits failure not present in a root worktree

### ISSUE THREAD

**Issue by Samantha-uk** [yarnpkg/berry#2180]
- [X] I'd be willing to implement a fix (_If I am able to ask loads of questions!_)

**Scenario 1 - Single worktree.**
Running yarn from any directory inside the worktree will 'work'.  Packages will be added/removed according to the various manifests.  It is possible to add packages in the root folder of the worktree.

**Scenario 2 - Multiple nested worktrees.**
'.', one & two are all worktree directories;  a,b,c&d are package directories.

```
.
├── one
│   ├── a
│   │   └── package.json
│   ├── b
│   │   └── package.json
│   └── package.json
├── two
│   ├── c
│   │   └── package.json
│   ├── d
│   │   └── package.json
│   └── package.json
├── package.json
├── README.md
└── yarn.lock
```

**To Reproduce**

With yarn installed already, clone this repo [y2repro](https://github.com/Samantha-uk/y2repro) and set version berry.
cd into the one or two directory.
run `yarn`
run `yarn workstation list`
Both result in an error such as
`Usage Error: The nearest package directory (/home/samantha/github/y2repro/one) doesn't seem to be part of the project declared in /home/samantha/github/y2repro.`
`yarn info` behaves the same ... I've not checked other subcommands.

Doing the same in the root worktree will be successful.
Perhaps noteworthy, is that the successful `yarn workspaces list` in the root (or a/b/c/d)  _does_ report the root worktree directory, but not one or two.
`❯ yarn workspaces list
➤ YN0000: .
➤ YN0000: one/a
➤ YN0000: one/b
➤ YN0000: two/c
➤ YN0000: two/d
➤ YN0000: Done in 0s 1ms`

_I read the page about Sherlock but it did not seem appropriate for this issue _

 - OS: **Debian Buster** (Up to date)
 - Node version **14.15.1**
 - Yarn version **2.3.3** I also tried with set version from sources and had the same results.

_Additional info_
The following plugins are installed.
`➤ YN0000: @yarnpkg/plugin-constraints [experimental]
➤ YN0000: @yarnpkg/plugin-hello-world [experimental]
➤ YN0000: @yarnpkg/plugin-exec [experimental]
➤ YN0000: @yarnpkg/plugin-interactive-tools [experimental]
➤ YN0000: @yarnpkg/plugin-stage [experimental]
➤ YN0000: @yarnpkg/plugin-typescript [experimental]
➤ YN0000: @yarnpkg/plugin-version [experimental]
➤ YN0000: @yarnpkg/plugin-workspace-tools [experimental]`

At one point in my reproduction efforts I encountered yarn reporting it had detected duplicate package names (They aren't).  After clearing out yarn I could not reproduce it.

I have checked and there are no yarn files/directories at a higher level in the directory path.

**Comment by arcanis** [comment]
It's expected. The `workspaces` glob pattern you set at the root is `one/*`, meaning that it'll match `one/a` and `one/b`, but not `one` itself.

**Comment by Samantha-uk** [comment]
But  * != 1..n characters
* === 0..n characters
Which should match ... tho I wonder about this [trailing slash comment](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/sources/Project.ts#L221) ... but as it happens I've just this moment got my breakpoint working where I wanted so I'm going to step through the code parsing my structure.
