### ISSUE TITLE
[Bug] Yarn v2.3.0+ not bubbling exit code correctly on exit of package script. [Windows]

### ISSUE THREAD

**Issue by xCykrix** [yarnpkg/berry#2182]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Yarn does not bubble exit code appropriately when exiting from a `package.json` script.
Cannot replicate on a Linux environment, so I believe this is a Windows-specific issue.

This seems to have been introduced in v2.3.0 per my testing, as I could not replicate this issue before that release.

**To Reproduce**

https://github.com/xCykrix/repro-eslint-unexpected-0-exit

**Screenshots**

Windows [Yarn v2.3.3]
![image](https://user-images.githubusercontent.com/12182390/100541523-19de6880-320a-11eb-9a23-b5fb90341eef.png)

Linux [Yarn v2.3.3]
![image](https://user-images.githubusercontent.com/12182390/100541532-29f64800-320a-11eb-972c-6aa9869aeb1e.png)

Windows [Yarn v2.2.2]
![image](https://user-images.githubusercontent.com/12182390/100541614-b7d23300-320a-11eb-9aeb-61fe0c9701a6.png)

**Environment if relevant (please complete the following information):**

 - OS: WIndows 10.0.19041 Build 19041
 - Node version:  v14.15.1
 - Yarn version v2.3.3

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/1985 but it hasn't been released yet, run `yarn set version from sources` to get the fix before release.

**Comment by xCykrix** [comment]
Thank you. I was looking around for it but I couldn't find anything related to it.
