### ISSUE TITLE
[Question] Executing package accessible binaries in PnP mode

### ISSUE THREAD

**Issue by g6123** [yarnpkg/berry#2188]
I'm trying to write a `bin` script that runs another binary from installed packages.

Specifically what I want to do is invoking rollup build with some custom arguments.

I've tried simply running `rollup` with [execa](https://github.com/sindresorhus/execa) which is basically a thin wrapper around [child_process](https://nodejs.org/api/child_process.html).

```javascript
#!/usr/bin/env node
const path = require('path');
const execa = require('execa');

try {
  execa.sync(
    'rollup',
    ['-c', path.resolve(__dirname, '../rollup.config.js')],
    { stdio: ['ignore', process.stdout, process.stderr] },
  );
} catch (error) {
  console.error(error.shortMessage);
  process.exitCode = error.exitCode || -1;
}
```

It works fine when running it directly from its own package, but _when running it from another package_ it fails to find `rollup`.

```
Command failed with ENOENT: rollup -c <package path>/rollup.config.js
spawnSync rollup ENOENT
```

Since Yarn v2 documentation recommends using `yarn run` instead of `node_modules/.bin`, so I changed like this:

```javascript
execa.sync(
  'yarn',
  ['run', '--', 'rollup', '-c', path.resolve(__dirname, '../rollup.config.js')],
  { stdio: ['ignore', process.stdout, process.stderr] },
);
```

but neither of them worked.

```
Usage Error: Couldn't find a script named "rollup".

$ yarn run [--inspect] [--inspect-brk] <scriptName> ...
Command failed with exit code 1: yarn run rollup -- -c <package path>/rollup.config.js
```

I guess Yarn does not switch PnP context even when running binary from other package with `yarn run` command, which seems quite strange.

So, is there any way I can execute package accessible binaries from outside of that package?

**Comment by g6123** [comment]
I came up with this from a bit long yak shaving, so let me add some contexts here:

I am trying to convert a monorepo codebase with Yarn v1 + lerna into Yarn v2.

We have "infra" packages with common build dependencies and configurations (e.g. `rollup` dependency & `rollup.config.js` file), which I think is quite common pattern in monorepos.

So it looks like this:

```
repo/
    infra/
        library-builder/    # @example/infra-library-builder
            bin/
                build.js
                ..
            configs/
                rollup.config.js
                ..
            package.json
    libraries/
        network/            # @example/library-network
            src/
                ...
            package.json
            ...
        ...
    servicies/
        ...
```

For example, to build a `@example/library-network` package, you have to execute `build.js` from `@example/infra-library-builder`.

To make this simple, we added build `build.js` to `@example/infra-library-builder` as its binary,

```json5
// repo/infra/library-builder/package.json
{
  "name": "@example/infra-library-builder",
  "version": "0.0.0",
  "license": "UNLICENSED",
  "bin": {
    "example-build-library": "./bin/build"
  },
  // ...
}
```

and added `@example/infra-library-builder` to `@example/library-network` as its dev dependency.

```json5
// repo/libraries/network/package.json
{
  "name": "@repo/library-network",
  "version": "0.0.0",
  "license": "UNLICENSED",
  "scripts": {
    "build": "example-build-library"
  },
  "devDependencies": {
    "@example/infra-library-builder": "workspace:infra/library-builder"
  },
  // ...
}

```

The problem is, `yarn build` command in `@repo/library-network` scope fails when PnP mode enabled as described in original thread.

**Comment by bkarlson** [comment]
Thanks @merceyz , I've been running around my workspaces for an hour, trying to figure out why `yarn node-sass` works from command line, but does not work from workspace's `package.json`. Installing `node-sass` into that workspace fixed the issue, but there's 0 documentation on this topic. I hope someone googling for "_yarn run binary from package.json_" can find this issue.
