### ISSUE TITLE
[Bug]  Unable to build web-component in pnp mode.

### ISSUE THREAD

**Issue by Eldar-X** [yarnpkg/berry#2189]
Unable to build web-component in pnp mode. 
My workspace is vue project and when i try to build target web component it's fails. 

```
Error: EROFS: read-only filesystem, open '/node_modules/@vue/cli-service/lib/commands/build/entry-wc.js'
```

**Comment by merceyz** [comment]
Issue has been fixed upstream in https://github.com/vuejs/vue-cli/pull/6101
