### ISSUE TITLE
[Feature] Mark a package as non pluggable

### ISSUE THREAD

**Issue by remorses** [yarnpkg/berry#2196]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

I have a package that requires its files to be readable as simple paths by other packages, i would like to mark these packages as unpluggable and be stored as simple folders instead of being packaged in a Zip file

**Describe the solution you'd like**

Add a package.json filed to mark a package as non pluggable

**Describe the drawbacks of your solution**

Could require some more space on disk?

**Describe alternatives you've considered**

**Additional context**

This is what i am trying to do:
```js
await esbuild({
        ...
        inject: [require.resolve('esbuild-polyfills')],
})
```
Esbuild (golang process, ProxyFS will not have effect) will try to read that path and fail because that path does not exist

**Comment by merceyz** [comment]
Use the `preferUnplugged` field https://yarnpkg.com/configuration/manifest#preferUnplugged

**Comment by remorses** [comment]
Thank you, i couldn't find that
