### ISSUE TITLE
Resolving a dependency's dependency failed

### ISSUE THREAD

**Issue by johnrichardrinehart** [yarnpkg/berry#2199]
- [x] I'd be willing to implement a fix

**Describe the bug**

In my [MWE](https://github.com/johnrichardrinehart/wouter_issue) if I run `yarn install && yarn run build` then I get 18 errors related to a dependency resolution problem.

**Note: This can be fixed by 
```diff
  module: {
    rules: [
      {
-        test: /\.(cjs|ts|js|jsx|mjs)$/
+        test: /\.(cjs|ts|js|jsx|mjs)$/,
+        resolve: {fullySpecified: false},
      }
    ]
  },
```
but I find this to be an unsatisfactory patch to the problem. `wouter` is the only package that this is happening with right now, so I want to understand exactly what the problem is.

**To Reproduce**

The _minimal_ information needed to reproduce your issue (ideally a package.json with a single dep). Note that bugs without minimal reproductions might be closed.

IMPORTANT: We strongly prefer reproductions that use Sherlock. Please check our documentation for more information: https://yarnpkg.com/advanced/sherlock

1. `git clone https://github.com/johnrichardrinehart/wouter_issue.git`
1. `cd wouter_issue && yarn set version berry && yarn install && yarn run build`
1. See all the errors

**STDOUT**

```
➜  wouter_test git:(master) yarn run build
[webpack-cli] Compilation finished
asset bundle.js 21.5 KiB [compared for emit] (name: index)
runtime modules 668 bytes 3 modules
cacheable modules 9.16 KiB
  ./index.js 30 bytes [built] [code generated]
  ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 4.33 KiB [built] [code generated]
  ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/use-location.js 2.6 KiB [built] [code generated]
  ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/react-deps.js 176 bytes [built] [code generated]
  ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/matcher.js 2.03 KiB [built] [code generated]

ERROR in ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 23:18-31
export 'createContext' (imported as 'createContext') was not found in './react-deps.js' (possible exports: )
 @ ./index.js 1:0-29

ERROR in ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 32:20-30
export 'useContext' (imported as 'useContext') was not found in './react-deps.js' (possible exports: )
 @ ./index.js 1:0-29

ERROR in ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 51:17-23
export 'useRef' (imported as 'useRef') was not found in './react-deps.js' (possible exports: )
 @ ./index.js 1:0-29

ERROR in ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 63:14-20
export 'useRef' (imported as 'useRef') was not found in './react-deps.js' (possible exports: )
 @ ./index.js 1:0-29

ERROR in ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 70:9-10
export 'createElement' (imported as 'h') was not found in './react-deps.js' (possible exports: )
 @ ./index.js 1:0-29

ERROR in ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 85:24-25
export 'createElement' (imported as 'h') was not found in './react-deps.js' (possible exports: )
 @ ./index.js 1:0-29

ERROR in ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 97:22-33
export 'useCallback' (imported as 'useCallback') was not found in './react-deps.js' (possible exports: )
 @ ./index.js 1:0-29

ERROR in ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 121:14-28
export 'isValidElement' (imported as 'isValidElement') was not found in './react-deps.js' (possible exports: )
 @ ./index.js 1:0-29

ERROR in ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 121:52-53
export 'createElement' (imported as 'h') was not found in './react-deps.js' (possible exports: )
 @ ./index.js 1:0-29

ERROR in ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 123:9-21
export 'cloneElement' (imported as 'cloneElement') was not found in './react-deps.js' (possible exports: )
 @ ./index.js 1:0-29

ERROR in ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 136:6-20
export 'isValidElement' (imported as 'isValidElement') was not found in './react-deps.js' (possible exports: )
 @ ./index.js 1:0-29

ERROR in ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 145:13-25
export 'cloneElement' (imported as 'cloneElement') was not found in './react-deps.js' (possible exports: )
 @ ./index.js 1:0-29

ERROR in ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 155:2-17
export 'useLayoutEffect' (imported as 'useLayoutEffect') was not found in './react-deps.js' (possible exports: )
 @ ./index.js 1:0-29

ERROR in ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/react-deps.js 1:0-12:15
Module not found: Error: Can't resolve 'react' in '/home/john/Downloads/repos/wouter_test/.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter'
Did you mean 'index.js'?
BREAKING CHANGE: The request 'react' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
 @ ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 4:0-13:25 23:18-31 32:20-30 51:17-23 63:14-20 70:9-10 85:24-25 97:22-33 121:14-28 121:52-53 123:9-21 136:6-20 145:13-25 155:2-17
 @ ./index.js 1:0-29

ERROR in ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/use-location.js 12:25-33
export 'useState' (imported as 'useState') was not found in './react-deps.js' (possible exports: )
 @ ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 1:0-45 26:9-21
 @ ./index.js 1:0-29

ERROR in ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/use-location.js 13:19-25
export 'useRef' (imported as 'useRef') was not found in './react-deps.js' (possible exports: )
 @ ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 1:0-45 26:9-21
 @ ./index.js 1:0-29

ERROR in ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/use-location.js 15:2-11
export 'useEffect' (imported as 'useEffect') was not found in './react-deps.js' (possible exports: )
 @ ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 1:0-45 26:9-21
 @ ./index.js 1:0-29

ERROR in ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/use-location.js 40:19-30
export 'useCallback' (imported as 'useCallback') was not found in './react-deps.js' (possible exports: )
 @ ./.yarn/$$virtual/wouter-virtual-e5111b5711/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 1:0-45 26:9-21
 @ ./index.js 1:0-29

webpack 5.9.0 compiled with 18 errors in 202 ms
```

**Environment if relevant (please complete the following information):**

 - OS: Ubuntu 20.10
 - Node version: Node v15.3.0
 - Yarn version: yarn v2.4.0

**Additional context**

This could be a `webpack` issue or a `wouter` issue. Both [the author of wouter](https://github.com/molefrog/wouter/issues/150) and a [maintainer of webpack](https://github.com/webpack/webpack/issues/12093) say that this is not their fault, though.

**Comment by arcanis** [comment]
I'm sorry but I think I'll have to bump you to Webpack again - I suspect this is related to `enhanced-resolved`, because removing the `type: module` and `exports` field from `wouter/package.json` seems enough to make `yarn build` pass.

My best guess is that perhaps those fields don't interact perfectly with the timing when the PnP resolution occurs, but this part of the Webpack internals is still a bit obscure to me ... One interesting thing is that PnP logs all the resolution requests when passing `PNP_DEBUG_LEVEL=2` in the environment, but it doesn't print anything related to `react-deps`. That would imply that Webpack intercepts the resolution query, but I don't know if that's expected 🤔

Perhaps a good first step would be to make a minimal repro without wouter - I suspect using the aforementioned field with the `file:` or `portal:` protocols should be enough to repro the problem, without having to deal with all the unrelated third-parties. Will be easier to investigate afterwards.

cc @alexander-akait

**Comment by johnrichardrinehart** [comment]
@arcanis This PnP resolution is mostly all a black box to me. How does removing the `type` and `export` fields from `wouter`'s `package.json` tell you that this resolution problem is related to `enhanced-resolve`. The documentation on the behavior of `enhanced-resolve` is scant.

[I don't understand how to use the `file:` or `portal:` protocols](https://yarnpkg.com/features/protocols) to produce a MWE that doesn't depend on `webpack`. I understand that `file:` and `portal:` allow me to specify dependencies as local filesystem objects (files and folders, instead of repos/npm-packages). But, I'm only encountering this error when `webpack` is bundling my project, and only when my project includes an `import "wouter"` statement. I can't seem to avoid `webpack`.

**Comment by arcanis** [comment]
> How does removing the `type` and `export` fields from `wouter`'s `package.json` tell you that this resolution problem is related to `enhanced-resolve`.

PnP is meant to do the resolution from the bare identifier (`wouter`) to the package folder (`/path/to/wouter`). The rest of the resolution (for example `index.js`, etc) is handled by whatever "master resolver" you use (in this case enhanced-resolve). As a result, problems related to `module` / `exports` are typically *not* related to PnP, because the PnP part of the resolution is meant to have finished executing before it even comes to that.

Since removing both of those fields can be removed from `wouter/package.json` and make the build pass, I suspect the problem comes from, and thus not from the Yarn resolver.

> Is wouter declaring its dependencies in the "right" way? I can't seem to figure out the latest standard or what's best practice to judge who's doing what incorrectly.

As far as I can tell they do (they properly list `react` as peer dependency, so it's peachy) - the problem seems to be that Webpack doesn't see the symbols exported by `react-deps.js`, and I have no idea why (except that it seems related to one of the two fields I mentioned).

> Could you please provide more details regarding how you've diagnosed this as webpack's problem and how I can produce a better MWE that doesn't rely on webpack+babel?

I just modified `wouter-npm-2.6.0-237130b851-d80392b074` (using `yarn unplug`) to remove the fields.

**Comment by johnrichardrinehart** [comment]
> PnP is meant to do the resolution from the bare identifier (wouter) to the package folder (/path/to/wouter). The rest of the resolution (for example index.js, etc) is handled by whatever "master resolver" you use (in this case enhanced-resolve). As a result, problems related to module / exports are typically not related to PnP, because the PnP part of the resolution is meant to have finished executing before it even comes to that.

Ahhh, I didn't know there were two steps to the resolution process. This makes sense! Thank you!

> As far as I can tell they do (they properly list react as peer dependency, so it's peachy) - the problem seems to be that Webpack doesn't see the symbols exported by react-deps.js, and I have no idea why (except that it seems related to one of the two fields I mentioned).

I removed `type` and `exports` independently and removing `exports` changed nothing. Removing the `type: "module"` key:value pair was sufficient to fix it. I wonder why you mentioned the `exports` field. Maybe you just removed both at once and didn't do separate tests for each key(?).

> I just modified wouter-npm-2.6.0-237130b851-d80392b074 (using yarn unplug) to remove the fields.

Thanks! I hadn't used `yarn unplug` before. Using that right now was really helpful. I still don't see how I can avoid using `webpack` and still encounter this issue, though.

**Comment by arcanis** [comment]
> Maybe you just removed both at once and didn't do separate tests for each key(?).

Exactly! Thanks for refining my test 🙂

> I still don't see how I can avoid using `webpack` and still encounter this issue, though

No you can still use `webpack`, I mostly mean that if you make a very little repro with portals etc, it'll make it easier for the Webpack maintainers to trace what happens and fix it. Otherwise they have to deal with the resolution of all files in your app, and that might complexify the debug? Don't know.

**Comment by johnrichardrinehart** [comment]
Ahhhh, I see. Thanks @arcanis. You were really helpful. Thanks for jumping over to webpack/webpack, too. The assist was really appreciated.

Have a good one.
