### ISSUE TITLE
[Bug] upgrade-interactive shows incorrect in-range/latest versions

### ISSUE THREAD

**Issue by clemyan** [yarnpkg/berry#2200]
- [x] I'd be willing to implement a fix (might need guidance)

**Describe the bug**

When running `yarn upgrade-interactive`, if `Current == Range < Latest`, the latest version is show in the "Range" column instead of the "Latest" column.

**Analysis**

Buggy code is [here](https://github.com/yarnpkg/berry/blob/d16ed0585193f3d369c73ef920bd59d103c9554a/packages/plugin-interactive-tools/sources/commands/upgrade-interactive.tsx#L122-L134). When `Current == Range`, the suggestions array will be `[current, latest]`. But the caller expects `[current, range]` or `[current, range, latest]`.

**To Reproduce**

package.json
```json
{
  "name": "package-test",
  "dependencies": {
    "p-map": "^3.0.0"
  }
}

```

Run
```bash
$ yarn install
$ yarn plugin import interactive-tools
$ yarn upgrade-interactive
```

Expected  
The latest version of `p-map` (4.0.0 as of now) to be shown in the "Latest" column.

Actual  
The latest version is shown in the "Range" column.

**Screenshots**

![image](https://user-images.githubusercontent.com/41266433/100906494-33cac480-3504-11eb-81bc-aa09cfa7c64a.png)

**Environment if relevant (please complete the following information):**

 - OS: Windows 10
 - Node version 14.11.0
 - Yarn version 2.4.0

**Comment by chooban** [comment]
Since I quite possibly broke it in my recent changes, I took a shot at fixing it as penance! I've run into a list problem, though.
