### ISSUE TITLE
Searching for "rollup" does not find compatibility table

### ISSUE THREAD

**Issue by simon04** [yarnpkg/berry#2201]
Steps to reproduce:
1. On https://yarnpkg.com/, search for "rollup"
2. Notice that only one search result appears, https://yarnpkg.com/getting-started/migration/#dont-use-bundledependencies

The most relevant section (resp. table) is not listed in the results, https://yarnpkg.com/features/pnp#compatibility-table

**Comment by Haroenv** [comment]
This was happening because the docsearch config didn't allow searching for tables, and that's been fixed now, thanks for opening the issue!
