### ISSUE TITLE
[Bug] packageExtensions are ineffective

### ISSUE THREAD

**Issue by oliversalzburg** [yarnpkg/berry#2203]
- [X] I'd be willing to implement a fix

**Describe the bug**

I have unmet peer dependencies, because a dependency is no longer maintained. To avoid the warnings on `yarn install`, I want to update the peer dependency to a newer version.

The extension will not be enough to satisfy the peer dependency requirement. Additionally, the package extension is detected as being redundant

**To Reproduce**

You can observe the problem in https://github.com/oliversalzburg/yarn-2203 by running `yarn install`.

**Screenshots**

```shell
╭─ /tmp/yarn-deps ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔  11:26:36
╰─ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0060: │ yarn-deps@workspace:. provides graphql (p79a94) with version 15.4.0, which doesn't satisfy what graphql-subscriptions requests
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Post-resolution validation
➤ YN0069: │ graphql-subscriptions ➤ peerDependencies ➤ graphql: This rule seems redundant when applied on the original package; the extension may have been applied upstream.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0005: │ type-graphql@npm:1.1.1 [c7886] lists build scripts, but its build has been explicitly disabled through configuration.
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 0s 190ms
```

**Environment if relevant (please complete the following information):**

 - OS: Windows 10
 - Node version 14
 - Yarn version 2.4.0

**Comment by arcanis** [comment]
That's expected, as otherwise we couldn't detect redundant peer definitions, which will likely be different if custom-made than if they were made by the package author.

To silence things, use `logFilter`.

**Comment by oliversalzburg** [comment]
So, if I understand this correctly, my mistake was assuming that I could _override_ the dependency declaration, which isn't possible (or is no longer possible). Should that trigger a warning perhaps?

**Comment by arcanis** [comment]
Yep, exactly 👍 as for the warning, you already have one, just not the one you want 😛 but we can't disambiguate whether you intended to override or not, so the existing one is the best we can do. The full explanation can be written in the error list on the website.
