### ISSUE TITLE
Can be Barry implemented as Decentralized package manager (i.e swift-package-manager)

### ISSUE THREAD

**Issue by satishbabariya** [yarnpkg/berry#222]
Can be Barry implemented as Decentralized package manager (i.e swift-package-manager), or other any other implementation using berry?
i.e : package.json

```json
{
  "name": "@berry/monorepo",
  "private": true,
  "workspaces": [
    "packages/*"
  ],
  "dependencies": {
    "typescript": {
      "url": "https://github.com/microsoft/TypeScript.git",
      "from": "^3.3.3333"
    },
    "abc": {
      "url": "https://github.com/abc/abc.git",
      "from": "1.0.0"
    },
    "kitty": "^0.0.1"
  }
}
```

Resolved from git tag and git url
```json
"typescript": {
   "url": "https://github.com/microsoft/TypeScript.git",
   "from": "^3.3.3333"
}
```

Resolved from Package Registry (i.e GitHub package registry)
```json
"kitty": "^0.0.1"
```

**Comment by arcanis** [comment]
We already have #156 and #210 to discuss alternative registries.

As for using Git dependencies with semver ranges, it's part of #182 (up for grab).
