### ISSUE TITLE
Is there some place where questions can be asked without KYC?

### ISSUE THREAD

**Issue by stevenroose** [yarnpkg/berry#2226]
Discord is asking my name, age, e-mail and password. Is there an IRC channel? (#yarn has 4 people in it..)

So my question:

I'm trying to build a NixOS package for PeerTube, which uses yarn.

The NixOS default does `yarn --offline set yarn-offline-mirror`. Does that mean that value get ignored when later calls to `yarn install` are made without setting `--offline`?

**Comment by arcanis** [comment]
We have an all-new [Discussion tab](https://github.com/yarnpkg/berry/discussions) that you can use to have general discussions without mislabeling them as bug 🙂

> The NixOS default does yarn --offline set yarn-offline-mirror. Does that mean that value get ignored when later calls to yarn install are made without setting --offline?

Yes. But that seems to be a Yarn 1.x command, which is from the previous major. Configuration is different in 2.x.
