### ISSUE TITLE
[Bug] Stuck on `Error: incorrect header check`

### ISSUE THREAD

**Issue by eelco** [yarnpkg/berry#2227]
**Describe the bug**

When trying to run `yarn install` in our repository (migrating from Yarn 1 to Yarn 2), I get stuck on a YN0001 error:

```
➤ YN0001: │ Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
```

This happens during the `Fetch step`.

**To Reproduce**

I don’t know how to reproduce, other than giving access to our repository, which is quite big. I’m not sure how I’m supposed to reproduce this with Sherlock.

I’d love it there was a bit more stack / context when such an exception happens. I assume that this is a package that has a broken tarball (similar to https://github.com/yarnpkg/yarn/issues/260), but it’s very unclear to me how to locate what package could be causing this.

**Comment by merceyz** [comment]
Could you check if https://github.com/yarnpkg/berry/pull/2160 fixes this?

Run `yarn set version from sources --branch 2160` or download the bundle from https://github.com/yarnpkg/berry/actions/runs/389942550

**Comment by eelco** [comment]
Oh, awesome! I managed to track it down to the `@types/chrome@0.0.30` package by comparing the files downloaded to the cache to the resolved versions in the yarn.lock file.

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/2160
