### ISSUE TITLE
[Bug] yarn version check -i lose all changes if I don't move at least once the focus

### ISSUE THREAD

**Issue by bertho-zero** [yarnpkg/berry#2231]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I have a version file present with this content:

```
releases:
  "@openagenda/agenda-portal": patch
```

If I run `yarn version check -i` the boxes are pre-checked but if I do Enter immediately then all is set to undecided, while if I do Right + Left + Enter the checkboxes state remains the same but the content is correctly saved.

**Screenshots**

Without move:
![image](https://user-images.githubusercontent.com/8525267/101899469-2a012b00-3bae-11eb-853f-ece344194b9d.png)

With move:
![image](https://user-images.githubusercontent.com/8525267/101899584-587f0600-3bae-11eb-8b07-13718fc87763.png)

**Comment by arcanis** [comment]
Ah! Thanks for identifying the pattern that caused a breakage! I noticed it earlier but wasn't sure where it could come from - I've now been able to pinpoint the problem, it'll be solved in #2235
