### ISSUE TITLE
[Bug] Upgrade (up and upgrade-interactive) commands do not work with npmRegistryServer

### ISSUE THREAD

**Issue by bigman73** [yarnpkg/berry#2233]
- [ ] I'd be willing to implement a fix

**Describe the bug**

When the yarn berry project is using public npm as its registry server (that is npmRegistryServer is not defined) `yarn up` and `yarn upgrade-interactive` work as expected. 

But once the npmRegistryServer setting is defined to point to a valid private code registry (such as AWS Code Artifact) then the yarn upgrade commands stop working. They do not fail. `yarn up` doesn't do anything and `yarn upgrade-interactive` reports nothing to upgrade which is incorrect, when a package (either a public from npm or private one) is clearly outdated.

**To Reproduce**

pacakge.json - using an out of date moment package(2.29.1 is the latest)
``` 
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "moment": "^2.28.0"
  }
}
```

.yarnrc.yaml
```
npmRegistryServer: "https://<AWS_ACCOUNT>.us-east-2.amazonaws.com/npm/<REPO>/"
```

**Details**

yarn.lock after the upgrade has no changes:
```
"moment@npm:2.28.0":
  version: 2.28.0
  resolution: "moment@npm:2.28.0::__archiveUrl=https%3A%2F%2F <...Private Registry URL...> 2Fmoment%2F-%2Fmoment-2.28.0.tgz"
  checksum: <CHECKSUM<
  languageName: node
  linkType: hard
```

In comparison with yarn v1, after the successful upgrade:
```
moment@^2.28.0:
  version "2.29.1"
  resolved "https:/XX.codeartifact.us-east-2.amazonaws.com:443/npm/moment/-/moment-2.29.1.tgz#XXX"
  integrity sha512-<Checksum>==
```

**Screenshots**
After running `yarn upgrade-interactive`
![image](https://user-images.githubusercontent.com/5384551/101944982-8fa7e400-3bbb-11eb-9797-efae180b869a.png)

**Environment **

 - OS: OSX
 - Node version: 14.15.0
 - Yarn version: 2.4.0

**Additional context**

1. For comparison, yarn v1 and npm work as expected with the same private code registry and project.
2. `yarn add` works as expected with the private code registry. Calling it does upgrade the package as expected

**Comment by mhassan1** [comment]
This was caused by a bug in a community plugin: https://github.com/mhassan1/yarn-plugin-aws-codeartifact/commit/7c55faa56304cd6f70b871f12711016a539c93e1

This issue can be closed.

**Comment by bigman73** [comment]
@mhassan1 
Confirmed, that solved the problem, `up` and `upgrade-interactive` commands are now working
Thanks for the fix
