### ISSUE TITLE
[Bug] "Error: File-type dependencies cannot contain the character "?"" when depending on local tarball

### ISSUE THREAD

**Issue by strax** [yarnpkg/berry#224]
**Describe the bug**

Berry raises an error with the message:

```
➤ YN0013: │ focus-visible@file:./vendor/focus-visible-5.0.0-custom.tgz?[...] can't be found in the cache and will be fetched from the disk
➤ YN0001: │ Error: File-type dependencies cannot contain the character "?"
```

even though the depedency does not contain a question mark in `package.json`.

**To Reproduce**

Set up a dummy package bundled into a `.tgz` file in `./vendor/dummy.tgz`. Define the dependency to package.json as

```json
{
  "dependencies": {
    "dummy": "file:./vendor/dummy.tgz"
  }
}
```

Now running `yarn` gives the message described above.

**Environment if relevant (please complete the following information):**

```
$ yarn --version
v2.0.0
```

**Additional context**

I also tried to change the dependency to `file:./vendor/dummy.tgz:*` but Berry would then include the `:*` part when looking for the file.

**Comment by arcanis** [comment]
I can't repro the behavior you mention - make sure you use a fresh build (`yarn build:cli` from anywhere within the repository), as the checked-in build tend to be outdated.

**Comment by arcanis** [comment]
I'll close it for now, but feel free to reopen (ideally with a repro) if it's not fixed! 🙂
