### ISSUE TITLE
Docs lack how to uninstall Yarn 2 

### ISSUE THREAD

**Issue by desmap** [yarnpkg/berry#2244]
There are no docs and it's discouraged to rm .yarn in https://github.com/yarnpkg/berry/issues/1733 so what should we do?

This is crucial since Yarn 2 creates anomalies with other stuff, eg CRA but this should not be the focus here. I need to get Yarn 2 from my system or I must re-setup my machine :/

Edit: I changed the title bc the main issue is that there are no docs to get rid of berry; after 30 min of googling, reading tons of SO replies you know how to get there but man, this is not a nice UX and leaves users grumpy. You, we, nobody has time. FWIW and again, Yarn 2 totally messes up CRA if anyone cares.

**Comment by arcanis** [comment]
The doc clearly states that the install is project-local. If you derive from it that you need to reinstall your machine to switch back to something else, you missed something.

**Comment by merceyz** [comment]
> FWIW and again, Yarn 2 totally messes up CRA if anyone cares.

Yarn 2 doesn't mess up CRA, PnP highlights the issue in CRA which just happens to work under the old node_modules layout which is suggested to enable in the migration guide for the initial migration, which i'm assuming you skipped https://yarnpkg.com/getting-started/migration

The fix for CRA has been sitting there for months, if you want to complain, this is the wrong place https://github.com/facebook/create-react-app/pull/9872

**Comment by winstonDeGreef** [comment]
But how do you uninstall Yarn?

**Comment by hades200082** [comment]
Yarn v2+ has caused me so many issues. I just want it gone off of my machine.

I've tried `corepack disable` I've tried `npm install -g yarn` to go back to v1 but nothing works. Please explain how to get rid of Yarn v2+ and revert to classic Yarn until yarn v2+ & pnpm can just work without issue on projects.

**Comment by topb25** [comment]
> Yarn v2+ has caused me so many issues. I just want it gone off of my machine.
> 
> I've tried `corepack disable` I've tried `npm install -g yarn` to go back to v1 but nothing works. Please explain how to get rid of Yarn v2+ and revert to classic Yarn until yarn v2+ & pnpm can just work without issue on projects.

I have same problem, And after the upgrade, the package installed globally in yarn v1 cannot be uninstalled normally. yarn global  Command deleted 🤯🤯🤯

**Comment by jonmnoj** [comment]
Using `yarn set version classic` worked for me when I needed to revert it for a project

**Comment by seferin-x** [comment]
None of the 'standard' ways of uninstalling worked for me on windows 10. 

In the end I delete all files `yarn*` from:

c:\Users\<USER>\AppData\Roaming\npm

This worked straight away. Im not sure how safe this approach is.

**Comment by architchandra** [comment]
Coming here after looking everywhere about how to uninstall Yarn. Would love better documentation on this. Thanks.

**Comment by riungemaina** [comment]
So you can't remove yarn? any of the replace options do not work for me.

**Comment by Dan503** [comment]
I needed to run these commands:
```
npm uninstall corepack -g
npm i yarn -g
```
I also had to [downgrade node to v18.19.1](https://nodejs.org/download/release/v18.19.1/)

**Comment by hedaetul** [comment]
> Yarn v2+ has caused me so many issues. I just want it gone off of my machine.
> 
> I've tried `corepack disable` I've tried `npm install -g yarn` to go back to v1 but nothing works. Please explain how to get rid of Yarn v2+ and revert to classic Yarn until yarn v2+ & pnpm can just work without issue on projects.

I am also suffering from this issue.

**Comment by sdwvit** [comment]
corepack is a disaster, had to follow [Dan503](https://github.com/Dan503)'s advice

**Comment by cnotv** [comment]
> Yarn v2+ has caused me so many issues. I just want it gone off of my machine.
> 
> I've tried `corepack disable` I've tried `npm install -g yarn` to go back to v1 but nothing works. Please explain how to get rid of Yarn v2+ and revert to classic Yarn until yarn v2+ & pnpm can just work without issue on projects.

I have no idea why developers keep messing up so much with breaking changes with libraries and creating such an amount of issues.
This is bad from `yarn` to the point that I'll probably abandon as many already did.

**Comment by cnotv** [comment]
So using NVM I'd to do pretty much all the types of uninstall possible.
Using the current node version, `corepack` still has to be enabled:
- Set the current yarn version with `corepack prepare yarn@1.22.19 --activate`
- Remove node version of NVM to remove everything, then add it again

In your project, if you still have issues when you run `yarn` like 
```
error This project's package.json defines "packageManager": "yarn@4.3.1". However the current global version of Yarn is 1.22.22.
```
you need to add the configuration to your package manager, e.g.:

```
"packageManager": "yarn@1.22.22"
```

Then run the command ` yarn set version classic`.

Finally you can go back to work 😓
