### ISSUE TITLE
Package resolution failed with dlx

### ISSUE THREAD

**Issue by johnrichardrinehart** [yarnpkg/berry#2268]
- [x] I'd be willing to implement a fix

**Describe the bug**

I tried running `tailwindcss` using `yarn dlx` and it complained about not being able to resolve a dependency that was already installed.

**To Reproduce**

Clone [this repo and run `yarn install && yarn dlx tailwindcss-cli@latest build -o tailwind.css`](https://github.com/johnrichardrinehart/BerryResolutionIssue/blob/main/README.md)

** Environment

 - OS: Ubuntu desktop 20.10
 - Node version: 15.3.0
 - Yarn version: 2.4.0

**Comment by merceyz** [comment]
This is expected as [per the documentation](https://yarnpkg.com/cli/dlx) `dlx` executes the specified command in a temporary environment, this environment does not have the peer dependencies installed.


What you should do is install `tailwindcss-cli` as a dependency in your project and use `yarn tailwindcss-cli build -o tailwind.css`
