### ISSUE TITLE
Y2: ts-node unable to find types in .yarn/cache

### ISSUE THREAD

**Issue by johnptoohey** [yarnpkg/berry#2312]
### Bug description
ts-node is unable to locate types in new cache. Previously it would get them from the node-modules directories. 
**Command**

```sh
ts-node src/index/ts
```

**What is the current behavior?**

Errors from ts-node complaining about Types in my code, including not finding 'console'

**What is the expected behavior?**
Expected code to function as it does with yarn 1.x.

Is there a new config that I need to use to point to the type files in .yarn/cache?

**Steps to Reproduce**

1. 
2.

**Environment**

- Node Version: `12.14.0`
- Yarn v1 Version: `2.0` 
- OS and version: OSX 10.14

**Comment by merceyz** [comment]
I'd guess you lack a `@types/node` dependency in your workspace but without a reproduction there is nothing actionable here
