### ISSUE TITLE
Extremely slow `yarn run xxxx` commands on large monorepo

### ISSUE THREAD

**Issue by etiennedupont** [yarnpkg/berry#2319]
### Bug description

When running scripts defined in package.json using `yarn run xxx` on a large monorepo, there is an extremely long delay before the command is actually run. This delay is always the same and seems to depend on the size of the monorepo.

**Command**

Here is a simple example:

In package.json

```json
{
  "scripts": {
    "echo": "echo ok"
  }
}
```

Then in shell run:

```sh
> yarn echo

.... WAITS FOR 265s .....

ok
```

Using time to confirm the duration:

```sh
> time yarn echo
ok
yarn echo  264.68s user 1.33s system 99% cpu 4:26.01 total
```

**What is the current behavior?**

Yarn does something using 100% of a CPU core for 265s (on my repo and machine) before actually running the command.

**What is the expected behavior?**

Yarn runs the command instantly

**Steps to Reproduce**

1. Have a large monorepo with 176packages in the workspace.
2. `yarn install`
3. Run any `yarn run xxxx` command in any of the packages folder.

**Environment**

- Node Version: `10.15.3`
- Yarn v1 Version: `2.0.0-rc.29.git.20200218.926781b7` 
- OS and version: MacOS Catalina

**Comment by merceyz** [comment]
Closing as this was fixed in https://github.com/yarnpkg/berry/pull/998
