### ISSUE TITLE
[Feature] Separate package resolution info into a static file to allow typescript etc to use it

### ISSUE THREAD

**Issue by jedwards1211** [yarnpkg/berry#2322]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

Obviously, we want anything tool we might use to support PnP.
As the PnP docs state,

> TypeScript uses its own resolver as well. In this case the situation is a bit more complex - the TS team has some concerns about allowing third-party hooks inside the tsc compiler, meaning that we can’t work with it at the moment.

**Describe the solution you'd like**

Maybe I'm naive about what the resolution in `.pnp.js` needs, but the solution seems simple: if the locations of packages were stored in a static config file, then tsc would have no problem consuming it.

This would also make it possible for tools that aren't written in JS like Flow to support PnP one day.

**Describe the drawbacks of your solution**

Package resolution can't be...overly magic.  Is it too magic right now?

**Describe alternatives you've considered**

**Comment by jedwards1211** [comment]
According to what I see in the docs it sounds like resolution info is totally static:

> the .pnp.js file contains a map linking a package name and version to a location on the disk, and another map linking a package name and version to its set of dependencies

**Comment by arcanis** [comment]
> Maybe I'm naive about what the resolution in `.pnp.js` needs, but the solution seems simple: if the locations of packages were stored in a static config file, then tsc would have no problem consuming it.

The problem isn't PnP, it's the TS team that isn't willing to merge anything pertaining to the resolution in their core that they haven't built themselves.

**Comment by jedwards1211** [comment]
But why only store the static resolution information in a script file instead of standardizing a json format that they can built their own resolver for?  This stubbornness is gonna alienate the community

**Comment by jedwards1211** [comment]
I mean clearly you don't want to support tools written in languages other than JS either?

**Comment by arcanis** [comment]
> But why only store the static resolution information in a script file instead of standardizing a json format that they can build their own resolver for? This stubbornness is gonna alienate the community

You should take a look the documentation:

![image](https://user-images.githubusercontent.com/1037931/103483011-9f929c80-4de4-11eb-8e87-97ecf9012274.png)

> I mean clearly you don't want to support tools written in languages other than JS either?

Did you notice that Yarn is written in TypeScript?

**Comment by jedwards1211** [comment]
I'm finding it surprisingly difficult to relocate this documentation page, but the one that mentions resolve and enhanced-resolve compatibility also mentioned issues with native support in typescript, which is where my confusion arose.  As someone new to this landing there first, it sounded like typescript just isn't supported.

Aside from Typescript, i also have to use Flow for a lot of projects, and I know flow isn't supported right now.  I don't expect OCaml to be able to just run .pnp.js in process, which is another reason it seems like it would be better for the resolution information to be stored in a JSON file.  I guess Flow could scrape the resolution information out of the file via the parse AST, or maybe .pnp.js has a CLI it can call, but this would be a circuitous way to get at information that's static.

**Comment by arcanis** [comment]
TypeScript is listed as supported in our table: https://yarnpkg.com/features/pnp#native-support

**Comment by jedwards1211** [comment]
I guess I wish yarn had standardized a static way of storing this resolver information so that tools like typescript and IDEs could support it out of the box.  Like how Facebook managed to standardize JSX so that you don't depend on their tools or plugins for their tools to get JSX to work with your dev environment.

**Comment by jedwards1211** [comment]
But i bet npm and node will probably make a standard like that someday anyway

**Comment by jedwards1211** [comment]
https://classic.yarnpkg.com/en/docs/pnp/getting-started/

> TypeScript uses its own resolver as well. In this case the situation is a bit more complex - the TS team has some concerns about allowing third-party hooks inside the tsc compiler, meaning that we can’t work with it at the moment. That being said, TypeScript isn’t only tsc and as such we’ve been able to add PnP support to the popular ts-loader - meaning that as long as you compile your TypeScript through Webpack, everything works well! Consult the dedicated section about it for more information.

This is where my confusion arose -- to be clear `tsc` does work with PNP now?  If so I can make a PR to update these docs.

**Comment by jedwards1211** [comment]
Also by "tools written in languages other than JS" I meant things like Flow since it's written in OCaml and compiled to native binaries, WebStorm written in Java (no idea if it uses JS under the hood though) rather than compile-to-JS languages/tools.

**Comment by merceyz** [comment]
That's the docs for v1, the docs for v2 is here https://yarnpkg.com/features/pnp and the part @arcanis referenced to is here https://yarnpkg.com/configuration/yarnrc/#pnpDataPath

**Comment by jedwards1211** [comment]
Yeah that was kind of confusing to me too.  I think it would be good to remove most of that info from the v1 docs and have any mentions of PnP in the v1 docs just point to what v2 says about it.

**Comment by jedwards1211** [comment]
I want to apologize about my toxic attitude here, I do appreciate what you're doing to try to solve problems for huge projects.  Having just found out about yarn 2, I got really scared about these changes, worrying I would be stuck with a bunch of broken projects or have to use unsupported old versions of yarn, which I understand now isn't the case.
