### ISSUE TITLE
What happens with native code, PnP, and different versions of node?

### ISSUE THREAD

**Issue by jedwards1211** [yarnpkg/berry#2323]
So plug and play sounds very cool, especially in that I assume it allows all of our projects to point to a single installation of a package on disk instead of duplicating a bunch of files.

But, if Yarn 2 only keeps one copy of a given package version on disk, then if I build a native package for Node 12, and later switch to Node 14 for another project, that package will error out as being built for the wrong version.

I just wanted to ask if this scenario was considered, if we install foo@1.2.3 in two different projects with two different versions of node, will Yarn 2 cache two separate versions of foo on disk?

**Comment by arcanis** [comment]
> A clear and concise description of what the bug is. A bug is **unintended**. A feature not being
implemented is **not a bug**, and your issue may be closed for misleading labeling.

Please don't mislabel questions as bugs. We have a neat ["Discussions" tab](https://github.com/yarnpkg/berry/discussions) precisely for this kind of thing.

To answer your question: of course it got considered. Yes, it works.

**Comment by jedwards1211** [comment]
Sorry, i didn't realize there was a discussions tab

**Comment by xenoterracide** [comment]
so what's the answer? this is the first result in google ;)

**Comment by jedwards1211** [comment]
@xenoterracide arcanis says yes, it works
