### ISSUE TITLE
[Feature] save state of yarn install and resume from failure when internet connection is bad

### ISSUE THREAD

**Issue by pravi** [yarnpkg/berry#2335]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

I have a very bad internet connection (the connection keeps dropping for a few minutes and then come back) at my native place (this would be a similar situation in many parts of India). So every time I run yarn install for a big package like gitlab, one or the other dependency fail to download (I have set httpTimeout as 6 minutes and httpRetry as 15 which improved things considerably). Package managers like apt will resume from the last downloaded state.

**Describe the solution you'd like**

yarn should save the state of downloads for yarn install and cache it for at least a few hours so it can resume from where it stopped.

**Describe the drawbacks of your solution**

cache invalidation could be a potential issue, but this could be at least given as an option feature turned off by default.

**Describe alternatives you've considered**

As already mentioned increased httpTimeout and httpRetry was tried which improved the situation but did not solve it fully.

**Comment by pravi** [comment]
Another option would be for interactive retry as a feature so yarn can ask interactively if the download should be retried if it failed even after httpRetry times retries and it can then retry after some time and resume yarn install instead of starting from scratch and again failing at some other package.

**Comment by pravi** [comment]
Possibly add another variable retryInterval which will add a delay between retires. So if If configure it to say 1 minute or 2 minutes, the retry should be delayed for 1 or 2 minutes.

**Comment by merceyz** [comment]
> Possibly add another variable retryInterval which will add a delay between retires. So if If configure it to say 1 minute or 2 minutes, the retry should be delayed for 1 or 2 minutes.

We use the [retry option of got](https://github.com/sindresorhus/got#retry) which uses an exponential delay before it tries again so just increasing the amount of retries will give you a greater delay

**Comment by pravi** [comment]
Thanks, I think it was some other error then. It was related to adding portal:/usr/share/nodejs/jszip and "grunt-saucelabs": "Stuk/grunt-saucelabs#v10.0.0", in its devDeependencies, but I could not reproduce the issue in another clean setup. This was worked around by changing portal: to link:

**Comment by merceyz** [comment]
> This was worked around by changing portal: to link:

Keep in mind they don't behave the same - https://yarnpkg.com/features/protocols/#whats-the-difference-between-link-and-portal
