### ISSUE TITLE
[Bug] Various errors trying to setup using documentation

### ISSUE THREAD

**Issue by MLoughry** [yarnpkg/berry#235]
**Describe the bug**

Following either the documentation in the README, or on the [website](https://yarnpkg.github.io/berry/getting-started/install) (which are subtly different), I get various errors that are not addressed by any documentation I can find.

- The `.yarnrc` file generated when running `yarn set-policies` is not valid YAML, and running any `yarn` command with v2 results in an error: `Error: Parse error when loading /E:/VSO/typescript-repo/.yarnrc; please check it's proper Yaml (in particular, make sure you list the colons after each key name)`
  ```.yarnrc
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1


  lastUpdateCheck 1560620950342
  yarn-path ".yarn\\releases\\yarn-berry.js"
  ```
- After manually fixing the above issue, it runs into a very similar issue against the global `.yarnrc`. However, this one doesn't give the file that's running into the error; I had to debug to find the file.
  ```
  Error: Expected an indexed object, got a string instead. Does your file follow Yaml's rules?
      at parseViaJsYaml (E:\VSO\typescript-repo\.yarn\releases\yarn-berry.js:13698:15)
      at Object.parseSyml (E:\VSO\typescript-repo\.yarn\releases\yarn-berry.js:13704:12)
      at Function.findHomeRcFile (E:\VSO\typescript-repo\.yarn\releases\yarn-berry.js:35128:36)
      at async Function.find (E:\VSO\typescript-repo\.yarn\releases\yarn-berry.js:35088:28)
      at async run (E:\VSO\typescript-repo\.yarn\releases\yarn-berry.js:135:27)
  ```
  ```
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1


  lastUpdateCheck 1560620950342
  ```
- After fixing that issue as well, `yarn install` chokes because the `yarn.lock` file is also not valid YAML. I can't seem to find any documentation for migrating from a v1 lockfile to v2. Interestingly, this only seems to happen if you have dependencies with their own dependencies.
  ```
  Error: bad indentation of a mapping entry at line 9, column 15:
        dependencies:
                  ^
      at generateError (E:\VSO\typescript-repro\.yarn\releases\yarn-berry.js:13938:10)
      at throwError (E:\VSO\typescript-repro\.yarn\releases\yarn-berry.js:13944:9)
      at readBlockMapping (E:\VSO\typescript-repro\.yarn\releases\yarn-berry.js:14853:7)
      at composeNode (E:\VSO\typescript-repro\.yarn\releases\yarn-berry.js:15105:12)
      at readDocument (E:\VSO\typescript-repro\.yarn\releases\yarn-berry.js:15265:3)
      at loadDocuments (E:\VSO\typescript-repro\.yarn\releases\yarn-berry.js:15321:5)
      at load (E:\VSO\typescript-repro\.yarn\releases\yarn-berry.js:15342:19)
      at Object.safeLoad (E:\VSO\typescript-repro\.yarn\releases\yarn-berry.js:15364:10)
      at parseViaJsYaml (E:\VSO\typescript-repro\.yarn\releases\yarn-berry.js:13690:27)
      at Object.parseSyml (E:\VSO\typescript-repro\.yarn\releases\yarn-berry.js:13704:12)
  ```

**To Reproduce**

You can reproduce the first two issues in any setting, I'd imagine; I can do so on multiple repositories.

For the third issues, you can see the difference between the `master` and `yarn-berry` branches of [an old one-off repo](https://github.com/MLoughry/typescript-repro) I have. The `master` branch has only a `typescript` dependency, which has no dependencies of its own; as such, berry can `yarn install` without issue. In the `yarn-berry` branch, I added a `tslint` dependency with several of its own dependencies, which leads to the aforementioned error.

**Environment if relevant (please complete the following information):**

 - OS: Windows 10
 - Node version 12.4.0
 - Yarn version v2.0.0

**Comment by arcanis** [comment]
That's interesting, I'll have to try again the workflow (we definitely should write better test for the "migrating from v1 to v2" use case). What strikes me as odd is that we're meant to support both v1 and v2 yarnrc files when we [detect a particular string](https://github.com/yarnpkg/berry/blob/d403efb1f55bb4d3904ae27303900d75f2ce2378/packages/berry-parsers/sources/syml.ts#L103-L107). It should have kicked off, at least in the first and third points 🤔

**Comment by psachs21** [comment]
I'm also running into this issue, though in my case, it's complaining because i have a custom registry in my .yarnrc file. But the file is marked with ```# yarn lockfile v1```.

**Comment by psachs21** [comment]
The more i look at this, the more i think maybe custom registries are just not currently supported, so probably unrelated.

**Comment by arcanis** [comment]
Yes, this is a different problem - the old-style key format 

Custom registries are supported, but they follow a different configuration that in the v1 (cf [`npmRegistryServer`](https://yarnpkg.github.io/berry/configuration/yarnrc#npmRegistryServer), [`npmRegistries`](https://yarnpkg.github.io/berry/configuration/yarnrc#npmRegistries), [`npmScopes`](https://yarnpkg.github.io/berry/configuration/yarnrc#npmScopes)). We should document that in the [migration guide](https://github.com/yarnpkg/berry/blob/master/packages/gatsby/content/advanced/migration.md).

**Comment by psachs21** [comment]
I'll see if i can write up a pr for the migration guide, once i go through and understand the config options.

**Comment by MLoughry** [comment]
Thanks for the fix, @zachasme.

Applying that fix locally, I can get berry to install and run. However, when I try to run `yarn pnpify tsc`, I get an error that doesn't really give me any information to debug with. 🙁 I have a repro set up in the `pnpify` branch of the [same repo](https://github.com/MLoughry/typescript-repro). Not sure if this is another case of Windows vs. *nix.
```
PS E:\VSO\typescript-repro> yarn build
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: spawn tsc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn tsc',
  path: 'tsc',
  spawnargs: []
}
```

**Comment by arcanis** [comment]
Just tried with OSX, your repo seems to work here (I don't get a particular error), although nothing is generated (`yarn build` exits without error, but without generating anything - I don't know if there's a config issue or something ...).

I'll try again on Windows later, but the error you pasted seems to indicated that the `tsc` binary isn't available when we need to spawn it (which shouldn't happen, since it's properly listed as a dependency). Weird thing 🤔

**Comment by psachs21** [comment]
Forgive me if this is unrelated, as i've just been keeping an eye on this thread, but i've encountered similar issues when using node spawn with windows. I haven't looked into the code itself to confirm if this is the core of the issue, but I had to configure spawn with the `shell: process.platform == 'win32'` option to get some of my scripts running on both windows and unix environments. Dunno if that helps or not in this specific case.

**Comment by arcanis** [comment]
Oh yes, that might very well be related, good thinking! We use `cross-spawn` in the [core](https://github.com/yarnpkg/berry/blob/master/packages/berry-core/sources/execUtils.ts#L27), but it seems like we call the regular spawn in [PnPify](https://github.com/yarnpkg/berry/blob/master/packages/berry-pnpify/sources/bin.ts#L48). We should fix that.

What's weird is that PnPify works fine on our own repository, though (and we build on Windows as well, both as part of the tests and our development workflow). I would have expected it to break for us 🤨

**Comment by arcanis** [comment]
I've fixed the `cross-spawn` usage in #248, pushed a diff so that the v2 now uses `.yarnrc.yml` instead of `.yarnrc`, and improved the migration guide to include [how to configure custom registries](https://yarnpkg.github.io/berry/advanced/migration#yarnrc-files).

I think that should wrap up most of what was discussed here so I'm going to close it, but please feel free open new ones for other problems!

**Comment by MLoughry** [comment]
Thanks for the fixes, @arcanis. Is there a timeline for a `@berry/pnpify/@0.0.5`?

**Comment by arcanis** [comment]
@MLoughry just published 👍
