### ISSUE TITLE
[Bug] packageExtensions not being applied correctly

### ISSUE THREAD

**Issue by ganemone** [yarnpkg/berry#2351]
- [x] I'd be willing to implement a fix

**Describe the bug**

A potential bug with handling package extensions was introduced in [this commit](https://github.com/yarnpkg/berry/commit/871bd7517919c2209e78e78a3ce8b9c66a70f939). I believe the changes were intended to be refactoring, but not changing behavior of packageExtensions. However, the behavior is now different in certain edge cases. I believe the edge case occurs when a packageExtension is active for one package, but redundant in another.

**To Reproduce**

See https://github.com/ganemone/yarn-bug/tree/main

**Comment by merceyz** [comment]
You're running into the final point here https://github.com/yarnpkg/berry/pull/2091#issuecomment-728247700, use resolutions to override existing dependency versions
