### ISSUE TITLE
[Bug] compat/typescript patch does not apply on typescript@4.2.0-beta

### ISSUE THREAD

**Issue by Jessidhia** [yarnpkg/berry#2384]
- [ ] I'd be willing to implement a fix

**Describe the bug**

```
➤ YN0013: │ typescript@npm:4.2.0-beta can't be found in the cache and
➤ YN0013: │ typescript@patch:typescript@npm%3A4.2.0-beta#builtin<comp
➤ YN0013: │ typescript@npm:4.2.0-beta can't be found in the cache and
➤ YN0066: │ typescript@patch:typescript@npm%3A4.2.0-beta#builtin<compat/typescript>::version=4.2.0-beta&hash=cc6730: Cannot apply hunk #6
➤ YN0000: │           ConfigFileProgramReloadLevel[ConfigFileProgramReloadLevel["None"] = 0] = "None";
➤ YN0000: │           ConfigFileProgramReloadLevel[ConfigFileProgramReloadLevel["Partial"] = 1] = "Partial";
➤ YN0000: │           ConfigFileProgramReloadLevel[ConfigFileProgramReloadLevel["Full"] = 2] = "Full";
➤ YN0028: │ +         ConfigFileProgramReloadLevel[ConfigFileProgramReloadLevel["Resolutions"] = 3] = "Resolutions";
➤ YN0000: │       })(ConfigFileProgramReloadLevel = ts.ConfigFileProgramReloadLevel || (ts.ConfigFileProgramReloadLevel = {}));
➤ YN0000: │       function updateMissingFilePathsWatch(program, missingFileWatches, createMissingFileWatch) {
➤ YN0000: │           var missingFilePaths = program.getMissingFilePaths();
```

**To Reproduce**

`yarn add typescript@4.2.0-beta` (or `yarn up`); with `enableInlineHunks: true` in the `.yarnrc.yml` for the diff printout.

Bonus points: the [Playground reproduction](https://yarnpkg.com/playground?code=Y29uc3QgaW5zdGFsbFByb21pc2UgPSBwYWNrYWdlSnNvbkFuZEluc3RhbGwoewogIGRlcGVuZGVuY2llczogewogICAgW2B0eXBlc2NyaXB0YF06IGA0LjIuMC1iZXRhYCwKICB9LAp9KTsKCmF3YWl0IGV4cGVjdChpbnN0YWxsUHJvbWlzZSkKICAucmVzb2x2ZXMudG9CZVRydXRoeSgpOwo%3D) fails because the node version is too old.

**Environment if relevant (please complete the following information):**

 - OS: WSL
 - Node version: 14.15.4
 - Yarn version: 2.4.0

**Additional context**

The patch applies in older versions of typescript.

**Comment by arcanis** [comment]
Yep, will look into that this week

**Comment by niieani** [comment]
Is there any way to turn off the patching? I'm using the node-modules linker, is it even necessary?

**Comment by Jessidhia** [comment]
Alternative, some way to use `packageExtensions` metadata to prevent the compat patch from being applied

**Comment by merceyz** [comment]
> Is there any way to turn off the patching?

Not without replacing the plugin (as you noticed), you can make a feature request for this if you want

> I'm using the node-modules linker, is it even necessary?

@niieani The content needs to be the same for both PnP and node_modules otherwise workflows where you use node_modules locally but PnP on the CI can't use the `--immutable` flag when installing

**Comment by Knagis** [comment]
@niieani could you please share how do you replace the default plugin-compat with your dummy?

**Comment by niieani** [comment]
Sure, create `.yarn/plugins/@yarnpkg/plugin-compat.cjs:

```js
module.exports = {
  name: `@yarnpkg/plugin-compat`,
  factory: (require) => {
    // dummy implementation to override the built-in version of this plugin
    return {}
  },
}
```

Add to .yarnrc.yml:

```yaml
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: '@yarnpkg/plugin-compat'
```

**Comment by niieani** [comment]
@merceyz sure, it doesn't make sense to disable the patch in these workflows, but when you're just developing a small open source side project, you probably don't care if the CI runs few seconds longer.

**Comment by Hideman85** [comment]
> From @niieani
> Sure, create `.yarn/plugins/@yarnpkg/plugin-compat.cjs`:
> 
> ```js
> module.exports = {
>   name: `@yarnpkg/plugin-compat`,
>   factory: (require) => {
>     // dummy implementation to override the built-in version of this plugin
>     return {}
>   },
> }
> ```
> 
> Add to `.yarnrc.yml`:
> 
> ```yaml
> plugins:
>   - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
>     spec: '@yarnpkg/plugin-compat'
> ```

You do not imagine how much you saved me time there. I hate the checksum issue I'm getting with these compat patches... And I dont even use PnP :face_exhaling: 
I read the PR and the Q&A but I have no break by disabling this. Also why not simply check nodeLinker === 'pnp' then patch...
Well thanks again you saved me a bunch of time with this quick fix :slightly_smiling_face:
