### ISSUE TITLE
Error when plugin-workspace-tools attempt to initialize [yarn set from sources]

### ISSUE THREAD

**Issue by jonescr3** [yarnpkg/berry#2386]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Usage Error: This plugin cannot access the package referenced via yup which is neither a builtin, nor an exposed entry (when initializing @yarnpkg/plugin-workspace-tools, defined in ... /.yarnrc.yml)

**To Reproduce**

1). Make sure package.json includes the plugin (plugin-workspace-tools) and you are using yarn set from sources.
2). Attempt to run yarn.

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

**Environment if relevant (please complete the following information):**

 - OS: MacOS Big Sur 11.1
 - Node version: v15.5.1
 - Yarn version: 2.4.0-git.20210115.hash-892882c0

**Comment by merceyz** [comment]
This is expected, when you import the CLI from sources you need to import the plugin from sources as well
