### ISSUE TITLE
[Feature] Rename `.yarnrc` into `.yarnrc.yml`

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/berry#239]
**Describe the user story**

I'm a user, I want to migrate to Yarn 2. It's currently a real pain to deal with v1 rc files versus v2 rc files, both because of the syntax and the different configuration keys.

**Describe the solution you'd like**

I initially kept the `.yarnrc` name because why not, but thinking about it we might have a better time using a different name. I think using `.yarnrc.yml` would be a good idea because:

- We could stop reading `.yarnrc` altogether (and thus wouldn't have to deal with old-style syntax, old-style settings, ...)
- People using both the v1 and the v2 wouldn't have to use the `berry:` hack to have configuration for the two tools
- We can get rid of the `# yarn lockfile v1` detection, which doesn't work well for manually-created rc files (I used to remove them a lot).
- Changing the rc names in such a way isn't unheard of - for example `.babelrc` as a Javascript counterpart with `.babelrc.js`, and it's the same thing for ESLint
- Since we're switching to the Yaml format, adding the type hint in the extension makes it really clear what is expected (otherwise I'm concerned users will just keep writing old-style).
- It opens the way to later support `.yarnrc.js`, if we decide to do this.

**Describe the drawbacks of your solution**

It might be surprising at first why the settings aren't applied. I'm not sure we can do much to avoid this (we potentially could read the `.yarnrc` and throw if it contains v2 keys, but that sounds fishy).

**Describe alternatives you've considered**

- We could use a different file name - for example `.berryrc`.
- And of course, we could keep the existing system.

**Comment by milesj** [comment]
Just want to note that it should probably be `.yaml` and not `.yml`. https://yaml.org/faq.html

**Comment by arcanis** [comment]
Since most other yaml files I've seen in use in the JS community use `.yml` (`.gitlab-ci.yml`, `azure-pipelines.yml`, `appveyor.md`) I'd tend to ignore the official recommendation in this case 🤔

Related: https://github.com/pnpm/pnpm/issues/1380

**Comment by arcanis** [comment]
There will be one significant issue: `yarn-path`. If we end up with two different files, then it becomes a fair bit more difficult to interact with the `yarn-path` settings; should we read it from `.yarnrc`? Or from `.yarnrc.yml`? Or both? Where to set the flag when calling `yarn set version`? How well would it integrate with Yarn v1, which is likely to be the global binary for some time?

**Comment by arcanis** [comment]
Done in #244

**Comment by accidentaldeveloper** [comment]
When converting a project to v2 I run `yarn policies set-version berry`. This creates a `.yarnrc` file with the line `yarn-path ".yarn\\releases\\yarn-berry.js"` and downoloads the yarn-berry.js file. 

If I then run `yarn set version berry` a `.yarnrc.yml` file is created with the line `yarnPath: .yarn/releases/yarn-rc.js` and changes the file name to `yarn-rc.js`.

The old `.yarnrc` file is still pointing to the old location: `yarn-berry.js`. Should I delete the `.yarnrc` file? I did Google for an answer to this but didn't find anything.

**Comment by arcanis** [comment]
- The 1.17.2+ uses both `.yarnrc.yml` and `.yarnrc` to figure out which version of Yarn to use
- In this case, the `.yarnrc.yml` file is preferred over the `.yarnrc` file
- The v2 uses exclusively the `.yarnrc.yml` file

So you shouldn't need the `.yarnrc` file if you have an up-to-date Yarn installed globally (1.17.2+). I just haven't got around implementing the change in the `set-policies` command in the v1 trunk to generate a `.yarnrc.yml` instead of `.yarnrc`.

**Comment by zypA13510** [comment]
@arcanis 
> Since most other yaml files I've seen in use in the JS community use `.yml` (`.gitlab-ci.yml`, `azure-pipelines.yml`, `appveyor.md`)

I think this is a false assumption, e.g. ESLint [supports both](https://eslint.org/docs/user-guide/configuring#configuration-file-formats) but gives `.eslintrc.yaml` priority, [load-grunt-config](https://www.npmjs.com/package/load-grunt-config) uses `*.yaml` only. Also, in the issue you linked to they decided to stick with `.yaml`.

> Related: [pnpm/pnpm#1380](https://github.com/pnpm/pnpm/issues/1380)

So instead of using `.yarnrc.yml` only, why not handle it like ESLint, i.e. supports both but uses the one with higher priority only in case both exist?

**Comment by posquit0** [comment]
@zypA13510 +1 👍🏼
