### ISSUE TITLE
[Bug] `yarn node` runs Node.js in a child process

### ISSUE THREAD

**Issue by akihikodaki** [yarnpkg/berry#2390]
- [ ] I'd be willing to implement a fix

I am willing to do so, but I have no idea how. It is likely to depend on some new design decisions.

**Describe the bug**

According to the documentation, `yarn node` is a drop-in replacement for `node` command.
https://yarnpkg.com/cli/node

However, it has different behaviors because `yarn node` runs Node.js in a child process. For example:
- sending signal which cannot be caught to the process of `yarn node` will not have an effect on `node` command.
- closing inherited file descriptors on Node.js does not close them completely. The process running `yarn node` still holds them.

**To Reproduce**

On Unix-like system, Send `SIGUSR1` to the process of `yarn node`. You'll see a debugger on `yarn node` is listening, but it is not on a process actually executing the code.

**Screenshots**

None

**Environment if relevant (please complete the following information):**

 - OS: Unix-like system. 
 - Node version [any]
 - Yarn version [any]

**Additional context**

None

**Comment by andreialecu** [comment]
This is a nodejs limitation. It's mostly blocked by the fact that Windows doesn't have support for replacing the process. See:
https://github.com/nodejs/node/issues/21664

A workaround, if you need to bypass `yarn` and run the process directly would be to run:

`node -r ./.pnp.cjs yourscript.js`

Perhaps the docs page above should mention the above command, which will also be faster, and probably preferred for production environments. 

The docs for the command are here if you think you can improve it: https://github.com/yarnpkg/berry/blob/b433198b9d2fb6ab81a9e23e8f00021bc5bafb4d/packages/plugin-essentials/sources/commands/node.ts#L11-L21
