### ISSUE TITLE
This package doesn't seem to be present in your lockfile; try to make an install to update your resolutions

### ISSUE THREAD

**Issue by Suryadevelops** [yarnpkg/berry#2398]
**Describe the bug**
I was getting this error when I tried to run a yarn command and this started to happen after I shifted the yarn berry 

`his package doesn't seem to be present in your lockfile; try to make an install to update your resolutions`

My package.json file

```json
{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "watch": "tsc -w",
    "dev": "nodemon dist/index.js",
    "start": "node dist/index.js",
    "start2": "ts-node src/index.ts",
    "dev2": "nodemon --exec ts-node src/index.ts",
    "create:migration": "mikro-orm migration:create"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/express": "^4.17.11",
    "@types/node": "^14.14.20",
    "nodemon": "^2.0.7",
    "ts-node": "^9.1.1",
    "typescript": "^4.1.3"
  },
  "dependencies": {
    "@mikro-orm/cli": "^4.3.4",
    "@mikro-orm/core": "^4.3.4",
    "@mikro-orm/migrations": "^4.3.4",
    "@mikro-orm/postgresql": "^4.3.4",
    "apollo-server-express": "^2.19.1",
    "argon2": "^0.27.1",
    "express": "^4.17.1",
    "graphql": "^15.4.0",
    "pg": "^8.5.1",
    "type-graphql": "^1.1.1"
  },
  "mikro-orm": {
    "useTsNode": true,
    "configPaths": [
      "./src/mikro-orm.config.ts",
      "./dist/Mikro-orm.config.js"
    ]
  }
}
```

also added yarn.lock

https://gist.github.com/Suryadevelops/2a59de8fe395bee643cbf7e8f28f2c73

**Screenshots**

![image](https://user-images.githubusercontent.com/75428274/105478642-753c4c80-5cc9-11eb-8da7-a4fd2497a933.png)

 - OS: Windows
 - Node version [v14.15.4]
 - Yarn version [2.4.0]

**Additional context**

Can anyone say me how I can remove berry?

apologize if this was asked already

**Comment by merceyz** [comment]
Did you run `yarn install`?

You need to provide a reproduction

**Comment by Suryadevelops** [comment]
I will try

**Comment by Suryadevelops** [comment]
worked thanks @merceyz

**Comment by merceyz** [comment]
What part of the error message `try to make an install to update your resolutions` wasn't clear enough to indicate that was a possible solution? (I'm asking so that we can improve it.)

> Can anyone say me how I can remove berry?

Revert the changes made by the `set version` command 
https://yarnpkg.com/getting-started/migration#step-by-step

**Comment by Suryadevelops** [comment]
@merceyz 
Yup

I confused that it saying to upgrade yarn better change it to say try to run yarn install from your root directory
