### ISSUE TITLE
Question: what affects virtual path?

### ISSUE THREAD

**Issue by brandon-leapyear** [yarnpkg/berry#2400]
We have a weird set up where one workspace imports another workspace's webpack configuration, like
```js
// package1/webpack.config.js
const webpack = require('webpack')
module.exports = {
  entry: ...,
  plugins: [new webpack.HotModuleReplacementPlugin()],
}

// package2/servePackage1.js
const webpack = require('webpack')
const package1Config = require('../package1/webpack.config.js')
webpack(package1Config, ...)
```
Running this setup throws `The 'compilation' argument must be an instance of Compilation` in our environment. And outputting `require.resolve('webpack')` in each script shows two different paths:

```
.../.yarn/$$virtual/webpack-virtual-e8b32a8ec2/0/cache/webpack-npm-5.11.1-039bea8222-c3130daeaa.zip/node_modules/webpack/lib/index.js
.../.yarn/$$virtual/webpack-virtual-b10cdd8616/0/cache/webpack-npm-5.11.1-039bea8222-c3130daeaa.zip/node_modules/webpack/lib/index.js
```

I tried making a minimal repro but I can't get the minimal repro to fail. What could make the virtual paths of these two workspaces different?

**Comment by merceyz** [comment]
You need to require the other package as if it was a dependency so that they get the same virtual instance.
So `require('package1/webpack.config.js')` where `package1` is a dependency (dev probably)

**Comment by brandon-leapyear** [comment]
I already have `package1` listed as a `devDependency` in `package2`. Changing to `require('package1/webpack.config.js')` still gives me the error

**Comment by brandon-leapyear** [comment]
Ok actually, I got a minimal repro. I'll open another issue.
