### ISSUE TITLE
vscode workspace debug sample

### ISSUE THREAD

**Issue by oraad** [yarnpkg/berry#2403]
Hi, I've been trying to debug a yarn workspace with vscode but I'm not sure how to properly configure it.
I'm using typescript with ts-node.

If someone could share a working configuration to debug a workspace with vscode, it would be much appreciated

**Comment by merceyz** [comment]
Don't open issues for this sort of thing, this belongs in https://github.com/yarnpkg/berry/discussions

---

```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Debug test",
			"skipFiles": ["<node_internals>/**", "node_modules/**"],
			"runtimeArgs": ["-r", "./.pnp.js", "-r", "ts-node/register"],
			"args": ["${workspaceFolder}/src/index.ts"],
			"cwd": "${workspaceFolder}"
		}
	]
}

```
