### ISSUE TITLE
[Bug] Linke workspace by semver range expects satisfying resolution.

### ISSUE THREAD

**Issue by SyntheticGoop** [yarnpkg/berry#2442]
**Describe the bug**

With 2 workspaces
```
project/
  a/
    package.json { "name": "a", "version": "0.2.0" }
  b/
    package.json { "name": "b", "version": "0.1.0", "dependencies": { "a": "workspace:^0.2.0" } }
  c/
    package.json { "name": "c", "version": "0.1.0", "dependencies": { "a": "workspace:^0.1.0" } }
```

In the example above, package b will resolve dependencies, but package c will cause yarn to throw an error.
Because of this I cannot use range resolutions when referring to another workspace.
I am not using yarn version to bump versions in my workflow so that forces me to check all dependent packages and manually bump them (I am using standard-version). As such, if I make a patch to a utility package used by all workspaces, I will have to bump and publish all workspaces, even though the change could be permissive within the semver range if used.

If it is necessary to force the user to update the range in all workspaces, yarn should offer to update the ranges, but not fail to resolve them.

**Environment if relevant (please complete the following information):**

 - OS: Ubuntu 20.04
 - Node: 14.15.4
 - Yarn version 2.4.0

**Comment by merceyz** [comment]
This is expected, you're telling Yarn to match on a workspace whos version satisfy the constraint but none do as [`0.2.0` does not satisfy `^0.1.0`](https://jubianchi.github.io/semver-check/#/^0.1.0/0.2.0) if you want it to match either way use a wildcard (`workspace:*`)

**Comment by SyntheticGoop** [comment]
The issue with using * is that during the release stage, the package version gets resolved to the absolute version forcing me to have to release everything up the dependency tree even for patches.
