### ISSUE TITLE
yarn migrate to v2 timeout on resolution step

### ISSUE THREAD

**Issue by Cherviakov** [yarnpkg/berry#2445]
I working on pretty slow internet and connection can be interrupted quite often (sometimes like once per 5 mintues for around 15-30 seconds). When tried to migrate to v2 and run yarn install command getting all the time timeout error. Furthermore, with ping I can see that my network bandwith become jammed with yarn alone, I can't continue work while yarn installing. Old version (before release berry things) worked fine in such conditions, recovered and reconnected normally and not occupied all network resources.

But when I found this problem and tried to migrate back to v1 according to https://classic.yarnpkg.com/en/docs/install I still getting version of yarn, wich doing same resolution step as v2 and failing same way. Thanks to yarnpkg/yarn#7899 comments I managed to install v.1.17.0, wich working as before, and would be nice, if that explained on v1 installation guide for anyone else who have same troubles with network.

**Comment by merceyz** [comment]
Try setting the `networkConcurrency` to a lower number https://yarnpkg.com/configuration/yarnrc#networkConcurrency

> But when I found this problem and tried to migrate back to v1 according to https://classic.yarnpkg.com/en/docs/install I still getting version of yarn, wich doing same resolution step as v2 and failing same way. Thanks to yarnpkg/yarn#7899 comments I managed to install v.1.17.0, wich working as before, and would be nice, if that explained on v1 installation guide for anyone else who have same troubles with network.

If you followed the migration guide https://yarnpkg.com/getting-started/migration you would see that it tells you to commit your changes after running `yarn set version berry`, which means to revert the upgrade is to revert that commit

**Comment by Cherviakov** [comment]
No limit by default? And is there some gobal yarnrc.yaml file, not really like to set separate set of env vars for that.

I have nothing to commit, as I said yarn install failed on resolution step already, and just installing 1.22.5 and run yar set 1.22.5 not helping, as install working pretty similar with same resolution step, wich fails, I have to use v1.17.0, wich working exactly as before.

**Comment by merceyz** [comment]
> No limit by default?

Correct

> And is there some gobal yarnrc.yaml file, not really like to set separate set of env vars for that.

Yes, `~/.yarnrc.yml`

> I have nothing to commit, as I said yarn install failed on resolution step already,

Which makes it clear you didn't follow the migration guide as it states to commit before running an install. https://yarnpkg.com/getting-started/migration#step-by-step

**Comment by Cherviakov** [comment]
Thanks for clarification, but I don't get how commit changes anything.
That shoud be enough info to try to configure new yarn to work in my conditions.
