### ISSUE TITLE
[Bug] yarn install 2 versions redux use follow package.json but npm not

### ISSUE THREAD

**Issue by hm496** [yarnpkg/berry#2450]
**Describe the bug**
My package.json as follows:
```json
{
  "name": "test-types-react-redux",
  "version": "1.0.0",
  "description": "",
  "scripts": {},
  "dependencies": {
    "redux" : "4.0.4",
    "@types/react-redux" : "7.1.16"
  }
}
```

npm installation is fine, only installs redux@4.0.4,
but yarn installation will install two versions of redux 4.0.4 and 4.0.5,
how can i do?

```bash
$ npm -v
6.14.8
$ node -v
v14.15.1
$ yarn -v
1.22.10
$ yarn -v
2.4.0
```

yarn 1.22.10 and 2.4.0 both have this problem.

yarn 2.4.0 ,  `.yarnrc.yml`: 
```yml
yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: "node-modules"
```

**To Reproduce**
```bash
$ mkdir emptyDir
$ cd emptyDir
```
create a package.json with follow code:
```json
{
  "name": "test-types-react-redux",
  "version": "1.0.0",
  "description": "",
  "scripts": {},
  "dependencies": {
    "redux" : "4.0.4",
    "@types/react-redux" : "7.1.16"
  }
}
```
```bash
$ yarn -v
1.22.10
$ yarn install
```
OR
yarn 2.4.0
`.yarnrc.yml` :
```yml
yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: "node-modules"
```
```bash
$ yarn -v
2.4.0
$ yarn install
```

**Screenshots**
![image](https://user-images.githubusercontent.com/17252784/107180158-20137100-6a13-11eb-84ef-816331fc7787.png)

**Environment if relevant (please complete the following information):**

 - OS: [OSX]
 - Node version [14.15.1]
 - Yarn version [2.4.0, 1.22.10]

**Comment by Embraser01** [comment]
Package `@types/react-redux` [has a](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-redux/package.json) dependency on `redux` `^4.0.0` which has been resolved to `4.0.5`.

You could try using `yarn set resolution redux@npm:^4.0.0 4.0.4` to set the dependency to the right version

**Comment by hm496** [comment]
> Package `@types/react-redux` [has a](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-redux/package.json) dependency on `redux` `^4.0.0` which has been resolved to `4.0.5`.
> 
> You could try using `yarn set resolution redux@npm:^4.0.0 4.0.4` to set the dependency to the right version

why npm only installs redux@4.0.4 without set any resolution?  Is it a bug of yarn? @Embraser01

**Comment by merceyz** [comment]
This is expected as `redux@^4.0.0` resolves to the highest compatible semver version which is `4.0.5` at the time of writing

**Comment by arcanis** [comment]
> Why npm only installs redux@4.0.4 without setting any resolution? Is it a bug of yarn?

It isn't a bug, since the `dependencies` doesn't guarantee that the resolved version from one package is the same as anywhere else in the dependency tree (it may happen, but not necessarily depending on many factors). It'd be different if `@types/redux` had listed `redux` as a *peer* dependency, but that's not the case here.
