### ISSUE TITLE
[Feature] Allow environment variables to be set in .yarnrc.yml

### ISSUE THREAD

**Issue by IanVS** [yarnpkg/berry#2464]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [X] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

I am upgrading from yarn 1 to 2, and am having a hard time porting one of the lines of my older `.yarnrc` file, which is: 

```
puppeteer-skip-chromium-download true
```

This prevents puppeteer from trying to reach out to the internet and download chromium, which it can't do in my CI server because we disable network access.  It seems that the config format has gotten more strict with yarn v2, and I'm no longer able to set this variable in the config file.  

**Describe the solution you'd like**

It is currently possible to _read_ an environment variable in the .yarnrc.yml, which is pretty awesome, but it would be great if we could _set_ them too.  Maybe something like:

```
${PUPPETEER_SKIP_CHROMIUM_DOWNLOAD}: true
```

**Describe the drawbacks of your solution**

The `yarn config -v` validation might get trickier, and honestly I'm not really sure if that syntax would break yaml parsing.

**Describe alternatives you've considered**

I could try to make sure I add `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true` every time I run a yarn install, but that's not ideal.  I could also create a wrapper script that sets the environment variable before running the actual `yarn-berry.js` file, as recommended in https://github.com/yarnpkg/berry/issues/1146#issuecomment-612593900, but that feels a bit hacky too.

**Comment by Nawbc** [comment]
any update???

**Comment by tychenjiajun** [comment]
Related https://github.com/yarnpkg/berry/pull/3938 
This really stop me from migrating to v2 or later versions.

**Comment by rally25rs** [comment]
The `sharp` library seems to want some env vars to be set as well, which would benefit from this feature.
https://sharp.pixelplumbing.com/install#custom-prebuilt-binaries

> To install the prebuilt sharp binaries from a custom URL, set the `sharp_binary_host` npm config option or the `npm_config_sharp_binary_host` environment variable.

**Comment by merceyz** [comment]
We've added support for environment files so this should be covered by that.
Ref https://github.com/yarnpkg/berry/issues/4718

**Comment by ricovitch** [comment]
> The `sharp` library seems to want some env vars to be set as well, which would benefit from this feature. https://sharp.pixelplumbing.com/install#custom-prebuilt-binaries
> 
> > To install the prebuilt sharp binaries from a custom URL, set the `sharp_binary_host` npm config option or the `npm_config_sharp_binary_host` environment variable.

How did you workaround install sharp library with prebuilt binaries with current latest yarn release ?
