### ISSUE TITLE
[Bug] Upgrading a package should delete obsolete archives

### ISSUE THREAD

**Issue by MLoughry** [yarnpkg/berry#247]
**Describe the bug**

When running `yarn up`, yarn does not clean up old version of dependencies that are no longer referenced by the package.json or any of its dependencies.

**To Reproduce**

Run `yarn up typescript` in the `pnpify` branch of [this repo](https://github.com/MLoughry/typescript-repro). A new zip was added for the new version of Typescript; however, the old version, which is now not used by the repo, is not cleaned up.

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: Windows
 - Node version v12.4.0
 - Yarn version v2.0.0

**Comment by arcanis** [comment]
Yep, you need to run `yarn cache clean`. Quoting myself on #228 I think we can do better, though:

> Autoprune is not part of the software yet because the cache is possibly shared by multiple projects. We could imagine doing it when we detect that it's inside the project, though (since it's the default) 🤔
