### ISSUE TITLE
[Bug] Yarn pnp not resolving browser field with Vite and engine.io-client

### ISSUE THREAD

**Issue by SyntheticGoop** [yarnpkg/berry#2471]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I am unsure if this is an issue with `Vite` or `yarn`, so I'm posting the issue on both.

When using `yarn berry` in `pnp` mode, Vite fails to properly load the package.json `browser` field from `engine.io-client`. This results in browser polyfills not loading.

**To Reproduce**

1. Initialize a new yarn berry repo
2. `yarn create @vitejs/app`
3. Select preset `vue-ts`
4. `cd` into project
5. `yarn add engine.io-client`
6. In `src/main.ts` add the following lines `import client from 'socket.io-client'; client`
7. `yarn dev`

Load the site in the browser and open the console. You will see an error from socket.io-client being bundled with the non `browser` package substitutions.

If you add `nodeLinker: node-modules` to the `.yarnrc.yml` file, the browser field detection works properly any you will not see errors.

**Additional context**

- `vite` version: `2.0.0-beta.67`
- Operating System: Pop!_OS 20.04
- Node version: 14.15.4
- Package manager (npm/yarn/pnpm) and version: `yarn 2.4.0`

**Comment by merceyz** [comment]
That's an issue in Vite, not in PnP. 

---
Upstream issue https://github.com/vitejs/vite/issues/1979
