### ISSUE TITLE
'yarn set version berry' requires deletion of .yarnrc.yml

### ISSUE THREAD

**Issue by Yzrsah** [yarnpkg/berry#2474]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Sometimes I am trying to install berry.
I may have copied some config files over to a repo that wasn't previously using berry, or I may have changed some stuff in a monorepo and, for whatever reason, berry isn't installed and .yarn is not present.

**To Reproduce**

_Problem 1:_

- Attempting to install berry will error if the `.yarnrc.yml` is present:
```
> yarn set version berry
node:internal/modules/cjs/loader:928
  throw err;
  ^
Error: Cannot find module '.yarn/releases/yarn-berry.cjs'
```

- To get around it I use a silly file called `.yarn-bootstrap.sh:`
```
#!/bin/sh
mv .yarnrc.yml .yarnrc.yml.bak
touch .yarnrc.yml
yarn set version berry
yarn plugin import workspace-tools
mv .yarnrc.yml.bak .yarnrc.yml
```

This script should not be needed and berry should be resilient to install without requiring a deleted config file.

_Problem 2:_

- Plugins specified in the `.yarnrc.yml` cannot be installed without removing them from the `.yarnrc.yml`:

```
> yarn plugin import workspace-tools
Internal Error: Cannot find module '.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs'
Require stack:
- .yarn/releases/yarn-berry.cjs
```

An easy version for the user could be for the `yarn` command to automatically download the berry release and plugins specified in `.yarnrc.yml` if they are missing.

**Comment by arcanis** [comment]
The expectation is that you check-in your Yarn binary into your repository, so that you don't have to run the command at every checkout (which would run the risk of you accidentally upgrading, which could be frustrating if it happened between major releases).

> An easy version for the user could be for the yarn command to automatically download the berry release and plugins specified in .yarnrc.yml if they are missing.

This may be what we'll be doing later, but it's part of a larger discussion with the Node team.

**Comment by Yzrsah** [comment]
@arcanis 

> The expectation is that you check-in your Yarn binary into your repository

That expectation is false and it does not even apply here and you can not assume that using a repository with a yarn binary already checked into it is the only thing that I can possibly ever be doing. You are making the assumption that the only repository that can ever exist is a repository that already has a yarn binary checked into it and everything is setup and perfect already. That expectation is non-realistic and your assumption is false.

I am working with a bunch of repos trying to do stuff, merging projects, moving parts out of workspaces into their own repos, copying .yarnrc.yml between projects, etc, switching around between multiple versions of a thing from disparate sources and adding yarn setups to get them going. It's not necessary to explain every detail, but saying the "expectation is that you check-in your Yarn binary into your repository," `== 🤦‍♂️` because it does not even apply and you did not understand the problem.

The outcome of the false expectation and lack of insight into what the user is doing creates a poor user experience where config files have to be deleted just to get yarn to install. Yarn V1 wasn't brittle like this.

**Comment by merceyz** [comment]
> Yarn V1 wasn't brittle like this.

Sure it is, it's the one throwing the error. Specify a non-existant `yarnPath` and it will be the one to throw

**Comment by arcanis** [comment]
> That expectation is false and it does not even apply here and you can not assume that using a repository with a yarn binary already checked into it is the only thing that I can possibly ever be doing.

I mean, that's our tool, so if we tell you how to use it but you prefer to ignore recommendations and do differently, it's fine, but you have to expect that you may not hit the [happy path](https://en.wikipedia.org/wiki/Happy_path#:~:text=In%20the%20context%20of%20software,no%20exceptional%20or%20error%20conditions.), and thus have to build some additional scripts to get the logic *you* want.

**Comment by icaro-capobianco** [comment]
tools like this shouldn't require you to add files to your repo
