### ISSUE TITLE
[Feature] Extracted config files

### ISSUE THREAD

**Issue by JesusTheHun** [yarnpkg/berry#2509]
To preface this I would like to say that I'm not sure it fits in `feature requests`, maybe it's a `compatibility` depending on how you see it.

- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

My project use `react-redux-typescript-scripts` which is a package that contains common configuration for react/redux/typescript projects.

In my `tsconfig.json` I write the following : 

```json
{
  ...
  "extends": "./node_modules/react-redux-typescript-scripts/tsconfig.json",
  ...
}
```

When moving to `berry` I lost the `node_modules` and the configuration file is not longer available.
In my case it's a config file, but it can also be `sass/css` files that need to be imported into a pre-processor, external to the project itself.

**Describe the solution you'd like**

Being able to tell `yarn` to extract a particular file or package could be the simplest way to go. A `.yarnrc.yml` could look like :

```yml
extractFiles:
  - 'mypackagename:./path-to-file'
```

Clearly this would impact the cache directory and zer0 installs but right now this is only way to provide a compatibility.

Maybe this could belong in a plugin, I'm not sure of what plugins are capable of.

**Describe the drawbacks of your solution**

Will increase the size of committed cache, but the effect is negligible.

**Describe alternatives you've considered**

Why not make it a plugin? I have no idea, maybe plugins can do that. Not to rant but at some point if you want adoption you have to consider lowering the number of steps required for user to migrate.

The only alternative I see is to manually copy the file into my project root in order to be able to access it. Obviously this is an issue for package updates for exemple.

**Comment by arcanis** [comment]
> Being able to tell `yarn` to extract a particular file could be the simplest way to go.

That wouldn't work - those files could themselves reference resources, which would then be resolve relative to the extracted file (which would be incorrect).

> or package

You can already do it with [`unplugged`](https://yarnpkg.com/configuration/manifest#dependenciesMeta.unplugged)

**Comment by merceyz** [comment]
> In my tsconfig.json I write the following :

`tsconfig` files let you use the name of the dependency. (I.e. `react-redux-typescript-scripts/tsconfig.json`)

> but it can also be sass/css files that need to be imported into a pre-processor, external to the project itself.

You can use `require.resolve` to get the location of any dependency

**Comment by JesusTheHun** [comment]
I rolled back my migration so I won't be able to test everything.

> tsconfig files let you use the name of the dependency. (I.e. react-redux-typescript-scripts/tsconfig.json)
Cool, will this be picked up by `eslint` ?

> You can use require.resolve to get the location of any dependency
Can't use that in a css file.

> 

So if I add :

```json
"dependenciesMeta": {
"react-redux-typescript-scripts": {
  "unplugged": true,
}
```
The package will be extracted in the cache directory and I'll be able to use it ? Does this breaks zer0 installs ?

**Comment by merceyz** [comment]
> I rolled back my migration so I won't be able to test everything.

Assuming you were following https://yarnpkg.com/getting-started/migration testing with PnP vs node_modules is a one line change in your config.

> Can't use that in a css file.

True, but if we're talking about `scss` then there is the `@import "package";` directive

> Cool, will this be picked up by eslint ?

I don't know, assuming you mean https://github.com/typescript-eslint/typescript-eslint then probably as it uses typescript to read that config

> The package will be extracted in the cache directory and I'll be able to use it ? Does this breaks zer0 installs ?

https://yarnpkg.com/advanced/lexicon/#unplugged-package
https://yarnpkg.com/cli/unplug/#details
https://yarnpkg.com/features/zero-installs#how-do-you-reach-this-zero-install-state-youre-advocating-for

**Comment by JesusTheHun** [comment]
Ok so I tried again and it works pretty well except for `ESLint` :

```js
module.exports = {
  ...
  extends: [
    'react-app',
    'plugin:@typescript-eslint/recommended',
    'plugin:jest/recommended',
    'react-redux-typescript-scripts/eslint.js', // KO
    '@react-redux-typescript-scripts/eslint.js', // KO
    './.yarn/unplugged/react-redux-typescript-scripts-virtual-2fa53f98dd/node_modules/react-redux-typescript-scripts/eslint.js', // OK
  ],
  ...
}
```

I'm going to open an issue on their side to see if they can do something about it

**Comment by merceyz** [comment]
Use `require.resolve` and/or add https://yarnpkg.com/package/@rushstack/eslint-patch to your config

**Comment by JesusTheHun** [comment]
Right, I forgot about that again. Well everything works as expected with `require.resolve` ! 
Still some error coming from the packages themselves but it's unrelated to this issue.

Thank you for the time you all took, I really appreciate it !
