### ISSUE TITLE
[Bug] YN0050: The cache-folder option got deprecated; use rc settings instead

### ISSUE THREAD

**Issue by haggholm** [yarnpkg/berry#251]
**Describe the bug**

Attempting to run `yarn` with no arguments causes the error in the title. It appears that https://github.com/yarnpkg/berry/pull/250/files#diff-49a630a2acd18d5b373f9d07513e8c6cR39 is intended to prevent the `cacheFolder` config option from the CLI, but it is also provided from the configuration files—or even from the built-in defaults, if no config files are found!

**To Reproduce**

```bash
yarn global add yarn@^1.17.2
git clone git@github.com:yarnpkg/berry.git
cd berry
yarn
```

Indeed, I can’t even install the dependencies for Yarn itself!

**Screenshots**

![Screenshot from 2019-06-24 16-30-29](https://user-images.githubusercontent.com/4934695/60058514-79435b00-969d-11e9-93c3-36ac5f338f60.png)

**Environment if relevant (please complete the following information):**

 - OS: Linux
 - Node version: v10.16.0
 - Yarn version: v1.17.2/v2.0.0

**Comment by arcanis** [comment]
Yep I merged too quickly my PR - fix incoming!
