### ISSUE TITLE
[Bug] plugin-node-modules creates .bin links in the wrong place when packages are hoisted

### ISSUE THREAD

**Issue by nigelzor** [yarnpkg/berry#2510]
- [ ] I'd be willing to implement a fix

**Describe the bug**

In a multi-project workspace using `nodeLinker: "node-modules"`, dependencies' bin links are created in `/node_modules/.bin` at the root of the workspace. If the workspace project `foo` defines the dependency the bin link should also exist in `/packages/foo/node_modules/.bin`.

**To Reproduce**

Example project here: https://github.com/nigelzor/yarn-missing-links

**Environment**

 - OS: OSX, Linux
 - Node version: 10.23.0, 14.15.4
 - Yarn version: 2.4.0

**Comment by larixer** [comment]
>  If the workspace project foo defines the dependency the bin link should also exist in `/packages/foo/node_modules/.bin.`

Could you clarify why? It is not evident for me, why the bin symlinks of direct dependencies should exist in. the workspace? Why for direct dependencies only, why not for all transitive dependencies of a workspace? Why those bin symlinks should be created at all, they do not belong to workspace `package.json` definition, they belong to the direct dependency and they were correctly hoisted together with that dependency.

**Comment by nigelzor** [comment]
I don't know that there was any formal specification for yarn@1's behaviour, but tools I use had come to rely on it.

**Comment by larixer** [comment]
I'm closing as wontfix, nm linker should be backward compatible with yarn 1, but not to a degree of undocumented implementation details or bugs. Feel free to reopen if stronger justification why is this needed will appear.

**Comment by TrySound** [comment]
@larixer More strong justification is the necessity to COPY node_modules for root and packages. yarn 1 always created node_modules/.bin. With yarn 2 we need to find a workaround for this.
