### ISSUE TITLE
[Bug] `yarn dlx @yarnpkg/doctor` doesn't emit a nonzero exit code when it fails

### ISSUE THREAD

**Issue by sargunv** [yarnpkg/berry#2521]
- [x] I'd be willing to implement a fix

**Describe the bug**

When running `yarn dlx @yarnpkg/doctor` on a workspace with unmet transitive peer dependencies, I expected it to fail with a nonzero exit code, but the exit code was 0, indicating success. Haven't yet investigated if this is `doctor` not emitting the expected exit code or `dlx` swallowing it.

Not 100% sure if this is unintended, so feel free to close if it is and I'll reopen as a feature request. My intuition is it's a bug because it's inconsistent with other Yarn functionality that logs "Failed with errors", and anyone that wants to get the report while swallowing the exit code can just suffix the command with `|| true`

**To Reproduce**

Take any package that would fail `doctor`, run `doctor`, and check the exit code with `echo $?`.

Unsure how to write this in Sherlock, sorry.

**Screenshots**

![image](https://user-images.githubusercontent.com/1320357/109228001-13627d00-7776-11eb-94b0-cab0b8917f51.png)

**Environment if relevant:**

 - OS: macOS 11.2.1
 - Node version: 12.19.1
 - Yarn version: 2.4.0

**Additional context**

I'd like to integrate `doctor` into our CI to put us on the path towards eventually adopting PnP, but would like to avoid having to parse the output for the text `Failed with errors`.

**Comment by arcanis** [comment]
Indeed - I think it's just a matter of storing the result of `StreamReport.start` [here](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-doctor/sources/cli.ts#L361), and returning its `exitCode()` member. Do you want to PR it?

**Comment by sargunv** [comment]
Sure, likely this weekend as I work on my other PR
