### ISSUE TITLE
[Bug] Unable to use packages that have dependencies locked in yarn.lock 

### ISSUE THREAD

**Issue by Robula** [yarnpkg/berry#2523]
- [ ] I'd be willing to implement a fix

**Describe the bug**
Dependencies in the yarn.lock file have got into a state where I am unable to resolve typing issues. Several `@types` packages include their own `@types` dependencies for the express and co packages. Somehow the lockfile has got into a state where I cannot get the type errors resolved without resorting to deleting yarn.lock and starting over.

**To Reproduce**
I've extracted the workspace out to a separate demo repo along with the affected yarn.lock file and stripped all other dependencies. 

https://github.com/Robula/yarn-invalid-lockfile

<details>
  <summary>Reproduction</summary>

  ```js repro
1. Run `yarn install`.
2. Run `yarn run typecheck`. Output shows 8 type errors.
4. Run `rm -f yarn.lock && yarn install`.
5. Run `yarn run typecheck` Output shows 0 type errors.
  ```
</details>

**Screenshots**
![image](https://user-images.githubusercontent.com/15246425/109278023-f67a8800-780f-11eb-80a5-b542cce1af65.png)

**Environment if relevant (please complete the following information):**

 - OS: Linux, macOS
 - Node version: v12.20.2
 - Yarn version: 2.4.0

**Additional context**
I feel like there should be a way to instruct yarn to refresh parts of it's lockfile or at least warn the user when installing a package that has dependencies already locked in the lockfile that the package being installed may not behave as expected.

**Comment by arcanis** [comment]
This isn't a bug, since Yarn behaves according to the rules we describe. The lockfile isn't invalid, since all the ranges are resolved to semver-compatible versions. The problem comes from the DefinitelyTyped packages, which use dependencies instead of peer dependencies. This unfortunately isn't something our project can address.

> I feel like there should be a way to instruct yarn to refresh parts of it's lockfile or at least warn the user when installing a package that has dependencies already locked in the lockfile that the package being installed may not behave as expected.

Refreshing part of the lockfile shouldn't be needed (because, again, we simply respect the semantics requested by the package), and sending warnings when dependencies are already locked in would send warnings at every single install, which wouldn't be helpful to anyone.

**Comment by arcanis** [comment]
Note that, as a workaround, you can pin specific @types packages to particular versions using the `resolutions` field.

**Comment by merceyz** [comment]
You can also do `yarn dedupe "@types/*"` to have all semver compatible ranges "merged"

**Comment by Robula** [comment]
Thanks, @arcanis. That makes complete sense.

@merceyz That's useful! Running that reduced the type errors down to 1, however, something is still amiss.

**Comment by Robula** [comment]
@arcanis The resolutions field didn't work:
1.
```json
  "resolutions": {
    "@types/express-serve-static-core": "4.17.4"
  }
```
2. `yarn install`
3. Same problem
4. Git revert

However, doing `yarn set resolution "@types/express-serve-static-core@npm:*" 4.17.4` instantly fixed my issue. Interestingly this command didn't add a `resolutions` to my package.json. I guess `resolutions` and `yarn set resolution` are totally different things.

**Comment by merceyz** [comment]
> Interestingly this command didn't add a resolutions to my package.json

Add the `--save` flag and it will

**Comment by Robula** [comment]
> > Interestingly this command didn't add a resolutions to my package.json
> 
> Add the `--save` flag and it will - https://yarnpkg.com/cli/set/resolution#options-s%2C-save

`yarn set resolution --save "@types/express-serve-static-core@npm:*" 4.17.4` did not modify anything except the `yarn.lock` file.

Also, how would one unset a resolution?

**Comment by Robula** [comment]
Nevermind, the `--save` bug was reported here: https://github.com/yarnpkg/berry/issues/2202
