### ISSUE TITLE
[Bug] importing the workspace-tools plugin when running from source causes subsequent calls yarn to fail

### ISSUE THREAD

**Issue by josiahruddell** [yarnpkg/berry#2532]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Installing yarn berry from source and importing the `workspace-tools` plugin causes every subsequent call to yarn to fail until the plugin is removed.

**To Reproduce**

Make a blank repo and initialize

```
> yarn set version berry
> yarn set version from sources
> yarn -v
2.4.0-git.20210227.hash-507fde7a

> yarn plugin import workspace-tools
➤ YN0000: Downloading https://github.com/yarnpkg/berry/raw/master/packages/plugin-workspace-tools/bin/%40yarnpkg/plugin-workspace-tools.js
➤ YN0000: Saving the new plugin in .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
➤ YN0000: Done in 0s 441ms

> yarn -v

Usage Error: This plugin cannot access the package referenced via yup which is neither a builtin, nor an exposed entry (when initializing @yarnpkg/plugin-workspace-tools, defined in /path/to/repo.yarnrc.yml)

━━━ Yarn Package Manager - 2.4.0-git.20210227.hash-507fde7a ━━━━━━━━━━━━━━━━━━━━━

  $ yarn <command>

You can also print more details about any of these commands by calling them with
the `-h,--help` flag right after the command name.
```

The only way to recover is to manually delete the plugin configuration from .yarnrc.yml

**Comment by noahnu** [comment]
The latest plugin-workspace-tools is not compatible with yarn from the master branch. 

If using yarn from sources, import the plugin from sources as well:

```
yarn plugin import from sources @yarnpkg/plugin-workspace-tools
```

I imagine once v3 is released, the plugin file that `yarn plugin import` downloads will be recompiled (this file: https://github.com/yarnpkg/berry/blob/master/packages/plugin-workspace-tools/bin/%40yarnpkg/plugin-workspace-tools.js).

**Comment by josiahruddell** [comment]
Thanks, this will work.
