### ISSUE TITLE
Docs claim that 'require' doesn't throw error

### ISSUE THREAD

**Issue by phormio** [yarnpkg/berry#2537]
In the context of `pnpMode: loose`, the documentation [says](https://yarnpkg.com/features/pnp#caveat):

> Because we *emit* warnings (instead of throwing errors) on resolution errors, applications can't *catch* them.

I take this to mean that `require` never throws an error if it cannot find the package, which is probably not a correct description of Yarn's behaviour, and probably not what the author meant to say.

If Yarn _did_ behave this way, that would be very bad, and would make Yarn unviable.  It's essential that `require('somepackage')` throw an error if `somepackage` is not available.

**Comment by arcanis** [comment]
It does throw in case of very incorrect require (like a package that doesn't exist at all), but it lets require pass as if the hoisting was there - which is what already happens with node_modules installs. That's the whole point of the loose mode 🙂
