### ISSUE TITLE
[Feature] Add a "Community Plugins" page to the website

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [yarnpkg/berry#2547]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

I'd like an easy way to find community-made plugins for Yarn.

**Describe the solution you'd like**

At https://github.com/yarnpkg/berry/issues/1164#issuecomment-709395119, @arcanis mentioned that it might be a good idea to create a "Community Plugins" list on the Yarn website. I'm filing this issue to track that idea.

**Describe the drawbacks of your solution**

Not sure what the flow would be to get a plugin listed on the website. Does that Yarn website have a Github repo for filing issues against?

**Comment by paul-soporan** [comment]
Closing as we now have a dedicated section for third-party plugins on the plugins page: https://yarnpkg.com/features/plugins#contrib-plugins
