### ISSUE TITLE
[Bug] esbuild-plugin-pnp ignores path aliases

### ISSUE THREAD

**Issue by dlindenkreuz** [yarnpkg/berry#2549]
- [ ] I'd be willing to implement a fix

**Describe the bug**

When using [@yarnpkg/esbuild-plugin-pnp](https://github.com/yarnpkg/berry/tree/master/packages/esbuild-plugin-pnp), path aliases defined in `tsconfig.json` or `jsconfig.json` are not used.

**To Reproduce**

https://repl.it/@dlindenkreuz/UnfitWickedMonad?v=1

**Please use the repl.it shell instead of the "Run" button:** `$ yarn node index.js`
This will execute the esbuild build script.

**Environment if relevant (please complete the following information):**

 - OS: macOS 10.15
 - Node version: 12.20.0
 - Yarn version: 2.4.0

**Additional context**

Possibly related, although from different repo: https://github.com/shiftx/esbuild-plugin-pnp/issues/1

**Comment by merceyz** [comment]
You should be using the `link:` protocol instead of path aliases https://yarnpkg.com/features/protocols/#why-is-the-link-protocol-recommended-over-aliases-for-path-mapping

**Comment by dlindenkreuz** [comment]
Unfortunately, this doesn't work in my case:

```js
// Original tsconfig.json or jsconfig.json
"compilerOptions": {
  "paths": {
    "@/*": ["./*"]
  }
}

// package.json
"dependencies": {
  "@": "link:./"
}

// usage, assuming a top-level "lib" folder
import foo from "@/lib/foo"
```

Yarn gives me this error when executing anything (not sure if I used `link:` correctly):
> Internal Error: Invalid scope: don't prefix it with '@'

I do understand that `link` could help here, but it solves the problem on the packaging side. I would expect alias resolution to happen within the esbuild or general build tooling domain first, then on the Yarn side.

Esbuild currently integrates `tsconfig.json` and `jsconfig.json`. Some projects like [Nuxt.js](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-alias) use more exotic aliases like `~~` and `@` (Nuxt uses Webpack, but the point is supporting certain established conventions). I would therefore expect that the tooling layer can do its job independently from Yarn path mappings.

If esbuild resolves a path to a module that's registered with `link:`, fair enough -- this could support a different interesting scenario.

**Comment by dlindenkreuz** [comment]
In the meanwhile, here's a workaround for my specific use case (alias `@` maps to package root):

```js
const path = require("path")

const rootPath = require("pkg-dir").sync()

const resolveRootAlias = {
  name: "example",
  setup(build) {
    const re = /^@\//

    build.onResolve({ filter: re }, (args) => {
      return { path: path.join(rootPath, args.path.replace(re, "")) }
    })
  },
}

require("esbuild")
  .build({
    entryPoints: ["./lib/foo.ts"],
    bundle: true,
    outfile: "out.js",
    minify: true,
    plugins: [
      resolveRootAlias,
      require("@yarnpkg/esbuild-plugin-pnp").pnpPlugin(),
    ],
  })
  .catch(() => process.exit(1))
```

**Comment by merceyz** [comment]
> Unfortunately, this doesn't work in my case:
> Yarn gives me this error when executing anything (not sure if I used link: correctly):
> Internal Error: Invalid scope: don't prefix it with '@'

That's explained in the documentation I linked to, read the first note

> If esbuild resolves a path to a module that's registered with link:, fair enough -- this could support a different interesting scenario.

As the docs I linked to explain, the `link:` protocol just makes it a normal dependency so you don't need to specify tsconfig paths, webpack alias, jest moduleNameMapper etc. It Just Works™ in all tools because to them it's just a dependency

**Comment by dlindenkreuz** [comment]
This requires me to redefine all internal aliases since I cannot use `@` with Yarn's `link:` protocol.

However, the value I get from this is higher than the effort it takes, so thank you @merceyz for pushing here. 👍 

Not sure if the original issue is still worth considering. For me personally, this case is closed, but maybe there are situations for others where existing aliases just need to work as they are.

**Comment by merceyz** [comment]
> Not sure if the original issue is still worth considering. For me personally, this case is closed, but maybe there are situations for others where existing aliases just need to work as they are.

Yeah we have no plans for respecting the tsconfig `paths` option, so i'll close this
