### ISSUE TITLE
[Bug] yarn workspaces foreach --exclude does not seem to work

### ISSUE THREAD

**Issue by akphi** [yarnpkg/berry#2558]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I have a monorepo and when I run the command `yarn workspaces foreach --exclude @akphi/app1 run build` at the root directory, the script `build` in `@akphi/app1` is still executed.

**To Reproduce**

You can use this repo https://github.com/akphi/config-tester

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node: 14.15.3
 - Yarn: 2.4.1

**Comment by akphi** [comment]
My bad here. I just realize I have to exclude the top-level package as well. So it has to be

`yarn workspaces foreach --exclude @akphi/app1 --exclude config-tester run build`

**Comment by dagda1** [comment]
I just found this, that is totally unintuitive that I have to include the top level package.json also.
