### ISSUE TITLE
Deploy to production server build fails with Yarn "immutable" flag set with postinstall patches

### ISSUE THREAD

**Issue by gtwilliams03** [yarnpkg/berry#2561]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Deploying several different apps to a production server.  Any changes which include a patch (like the fsevents patch mentioned in #2089) will fail with a post-install build error.  Our production server (Heroku) uses the "immutable" flags to fix the lockfile and it seems like the patches are trying to modify it causing an error ("The lockfile would have been modified by this install, which is explicitly forbidden.").  The first app I pushed has been down for two weeks now, so I thought I would try here.  I have had a ticket open with Heroku for 10 days now, but they recommended opening an issue here to see if anyone had some guidance.

**To Reproduce**

I have experienced this error on every app I have tried to push to Heroku since the fsevents patch error started occurring. I have attempted the fixes at #2078 but those have not worked.

**Environment if relevant (please complete the following information):**

 - OS: development MacOS 11.2.1 (production server is Linux)
 - Node version 15.11.0
 - Yarn version 2.4.1

**Additional context**

```
       ➤ YN0000: ┌ Resolution step
       ➤ YN0000: └ Completed in 0s 275ms
       
       ➤ YN0000: ┌ Post-resolution validation
       ➤ YN0000: │ @@ -4351,12 +4351,11 @@
       ➤ YN0000: │    linkType: hard
       ➤ YN0000: │  
       ➤ YN0000: │  "fsevents@patch:fsevents@~2.1.2#builtin<compat/fsevents>":
       ➤ YN0000: │    version: 2.1.3
       ➤ YN0028: │ -  resolution: "fsevents@patch:fsevents@npm%3A2.1.3#builtin<compat/fsevents>::version=2.1.3&hash=127e8e"
       ➤ YN0028: │ +  resolution: "fsevents@patch:fsevents@npm%3A2.1.3#builtin<compat/fsevents>::version=2.1.3&hash=11e9ea"
       ➤ YN0000: │    dependencies:
       ➤ YN0000: │      node-gyp: latest
       ➤ YN0028: │ -  checksum: e2b8c379340e21a786d32c653854c8876f94eb1202dd5be378fd42c062bc123aab5051c32bf0011865257c85982c41ded203f9fe8c9f9c8f8c84dc4672abc0e0
       ➤ YN0000: │    languageName: node
       ➤ YN0000: │    linkType: hard
       ➤ YN0000: │  
       ➤ YN0000: │  fsevents@~2.1.2:
       ➤ YN0000: │ 
       ➤ YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
       ➤ YN0000: └ Completed
       ➤ YN0000: Failed with errors in 0s 445ms
```

**Comment by merceyz** [comment]
Does running `yarn` locally produce the same change? If so commit it

**Comment by gtwilliams03** [comment]
I have tried a number of things like that, including removing yarn.lock from the repo and regenerating it locally, forcing changes to yarn.lock, etc.  Running local works fine.

**Comment by gtwilliams03** [comment]
My local dev environment is MacOS and my production server is Linux, so I am not sure why it is even trying to patch `fsevents` on the production server since it seems that wouldn't do anything on anything other than a MacOS environment.

In addition, `fsevents` is coming in with `chokidar`, in turn as a dependency of `nodemon` (which is in `devDependencies`) so it seems like it would not need these packages in production anyway.  But I am sure I don't have a good grasp of this.

```
MacBook-Pro:api user$ yarn why fsevents
└─ chokidar@npm:3.4.3
   └─ fsevents@patch:fsevents@npm%3A2.1.3#builtin<compat/fsevents>::version=2.1.3&hash=127e8e (via patch:fsevents@~2.1.2#builtin<compat/fsevents>)
MacBook-Pro:api user$ yarn why chokidar
└─ nodemon@npm:2.0.7
   └─ chokidar@npm:3.4.3 (via npm:^3.2.2)
MacBook-Pro:api user$ 
```

**Comment by gtwilliams03** [comment]
FYI - still digging, but the `package.json` file for `fsevents` (`https://github.com/fsevents/fsevents/blob/master/package.json`) specifies that it only runs on MacOS ("darwin"):

```
"os": [
    "darwin"
],
```

Ref: [npm docs re: os](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#os)

**Comment by gtwilliams03** [comment]
Looked through the Heroku build file, and this is the line that throws the Yarn error above:

```
yarn install --immutable --immutable-cache
```

**Comment by merceyz** [comment]
Seems like they're overriding your checked in Yarn version, which would change the patches and thus the checksum

**Comment by gtwilliams03** [comment]
Looks like both development and production are using Yarn `2.4.1`:

Contents of `.yarnrc.yml`:

```
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.4.1.cjs

```

Development:

```
MacBook-Pro:api user$ ls .yarn/releases
yarn-2.4.1.cjs
MacBook-Pro:api user$ yarn -v
2.3.3
```

Production:

```
       Resolving node version >=15.0.0...
       Downloading and installing node 15.11.0...
       Bootstrapping npm >=7.0.0 (replacing 7.6.0)...
       npm >=7.0.0 installed
       Resolving yarn version 1.22.x...
       Downloading and installing yarn (1.22.10)
       Using yarn 2.4.1
```

So is the checksum problem occurring because my production server is using yarn `2.4.1` from the `.yarn/releases` folder (as specified in `.yarnrc.yml`) but my local machine is resolving to `2.3.3` somehow even though it also has the latest version specified in the `releases` folder?

**Comment by merceyz** [comment]
> So is the checksum problem occurring because my production server is using yarn 2.4.1 from the .yarn/releases folder (as specified in .yarnrc.yml) but my local machine is resolving to 2.3.3 somehow even though it also has the latest version specified in the releases folder?

Yes, check your home directory, you might have a `.yarnrc.yml` file there that overrides the local one

**Comment by gtwilliams03** [comment]
@merceyz You are my hero.  There was indeed a `.yarn` folder and a `.yarnrc.yml` folder in my parent directory, probably due to an inadvertent run of `yarn set version...` in that directory or something.  I don't know.  But you saved the day.  Removing that file and directory from the parent directory and re-running `yarn install` (and pushing the updated lock file to the repo) made the app deploy.  Thank you 1000 times. I never would have thought to look there.

**Comment by saqlain1020** [comment]
Use same versions of yarn on local production and development.
Basically if lock file is created with one version of yarn and heroku uses other version, it gives this error.
Just check which version heroku is using in the logs you can see the yarn version.

**Comment by Zaffer** [comment]
This resolved for me when I implemented workspaces. Like this:
```package.json
}
...
  "workspaces": [
    "functions"
  ]
}
```
