### ISSUE TITLE
[Bug] $PROJECT_CWD variable is unbound

### ISSUE THREAD

**Issue by Robula** [yarnpkg/berry#2571]
- [ ] I'd be willing to implement a fix

**Describe the bug**
Using the `$PROJECT_CWD` environment variable does not work. 
`Unbound variable "PROJECT_CWD"`
**To Reproduce**
Add a script to `package.json`:
```json
{
  "scripts": {
    "doesNotWork": "echo $PROJECT_CWD",
    "butThisWorks": "echo $INIT_CWD"
  },
}
```
```
❯ yarn run doesNotWork
Unbound variable "PROJECT_CWD"
```

 - OS: Linux
 - Node version: 12.21.0
 - Yarn version: 2.4.1

**Comment by merceyz** [comment]
It was added in https://github.com/yarnpkg/berry/pull/2217 which hasn't been released yet, our docs are sadly pointing to `master` and might show things that haven't been released yet
