### ISSUE TITLE
[Bug] .bin/pnpify: line 1: module.exports: command not found

### ISSUE THREAD

**Issue by thealjey** [yarnpkg/berry#258]
**Describe the bug**

When running pnpify it is not executed by Node (there's no node pragma at the top of the file).
And the syntax is obviously not valid bash commands.

**To Reproduce**

locally installed `@berry/pnpify` as per documentation instructions

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version v12.4.0
 - Yarn version 1.17.0

**Comment by arcanis** [comment]
Fixed in master, I'll publish a new release later today 👍

**Comment by arcanis** [comment]
Just published 👍
