### ISSUE TITLE
[Bug] yarn install caches dependencies, but won't create node_modules

### ISSUE THREAD

**Issue by gh-andre** [yarnpkg/berry#2581]
- [ ] I'd be willing to implement a fix

**Describe the bug**

When adding a package, Yarn `2.4.1` goes fetches and caches requested packages, but there's no `node_modules` created after it reports success.

**To Reproduce**

Set up Yarn:

    npm install -g yarn
    mkdir test && cd ~/test
    yarn set version berry

`package.json`:

    {
    "name": "test",
    "private": true,
    "license": "UNLICENSED",
    "version": "0.1.0"
    }

Add `lodash`:

    yarn add lodash

This fetches `lodash` and stores it in `.yarn/cache/lodash-npm-4.17.21-*.zip` and adds it to `dependencies` in `package.json` and to `yarn.lock`, but doesn't create `node_modules`.

Running `yarn install` succeeds through all steps and nothing is changed in the directory structure.

Running `yarn info lodash` shows all info, as if it's installed.

Running the same with Yarn `1.22.10` works fine and creates `node_modules` after adding `lodash`.

**Screenshots**

N/A

**Environment if relevant (please complete the following information):**

 - OS: Linux/Fedora 33/CentOS 8
 - Node version: Fedora 33: `14.15.4`, CentOS 8: `10.24.0`
 - Yarn version: global `1.22.10`, local `2.4.1`

**Additional context**

This is similar to the issue described in this old thread.

https://github.com/yarnpkg/yarn/issues/2240

**Comment by merceyz** [comment]
See https://yarnpkg.com/getting-started/migration, if you want `node_modules` you have to explicitly enable it

**Comment by gh-andre** [comment]
I see. I must say, running everything through the package manager, and with explicit opt-out telemetry settings, looks a bit more radical than I expected. Thanks for pointing it out, though. Much appreciated.

**Comment by VictorioBerra** [comment]
Removing `rm -rf yarn.lock` did it for me...
