### ISSUE TITLE
[Feature] Allow packages not defined in workspace

### ISSUE THREAD

**Issue by natew** [yarnpkg/berry#2606]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

We have two packages in particular: both websites, one on top of Next.js and another on top of Docusaurus. They have a **ton** of dependencies no other part of the system uses. Since we cache and commit our yarn cache, adding it would be a real pain.

It would be nice to be able to run them without getting:

```
Usage Error: The nearest package directory (app/website) doesn't seem to be part of the project declared in (app)
``

**Describe the solution you'd like**

Be able to define something in package.json that defines a package as `isolated` and falls back to installing everything within the specific node_modules.

**Describe the drawbacks of your solution**

More config/work for you all!

**Describe alternatives you've considered**

For now just running it using npm, I guess.

**Comment by arcanis** [comment]
You already can - just create an empty `yarn.lock` in your website folder and Yarn will stop throwing this error (it'll however be up to you to remember to run installs in this folder too).
