### ISSUE TITLE
yarn install 404[Bug]

### ISSUE THREAD

**Issue by moroz1k** [yarnpkg/berry#2615]
- [ ] I'd be willing to implement a fix

**Describe the bug**
With simple yarn install. This happens when some packages are installed through a scope. 
`@adriver` - scope. 

> yarn install
➤ YN0000: ┌ Resolution step
➤ YN0001: │ HTTPError: Response code 404 (Not Found)
    at se.<anonymous> (/Users/moroz1k/Sites/cake-ui/.yarn/releases/yarn-2.4.1.cjs:23:10082)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
➤ YN0000: └ Completed in 0s 294ms
➤ YN0000: Failed with errors in 0s 298ms

<details>
  <summary>package.json</summary>

  ```js
{
  "name": "test",
  "description": "Public Cake client app for agencies",
  "license": "Apache-2.0",
  "repository": {
    "private": true
  },
  "version": "1.0.0",
  "scripts": {
    "start": "webpack-dev-server --color --config config/webpack.dev.js --inline"
 },
  "lint-staged": {
    "*.{js,jsx}": "eslint --max-warnings=0"
  },
  "devDependencies": {
    "@babel/cli": "^7.10.3"
  },
  "dependencies": {
    "@adriver/components": "^2.6.0"
    }
}
  ```
</details>

<details>
  <summary>.npmrc</summary>

  ```js
@adriver:registry=https://verdaccio.x
strict-ssl=false
  ```
</details>

**Environment:**
 - OS: MacOS M1
 - Node version 15.10.0
 - Yarn version 2.4.1

**Comment by merceyz** [comment]
Follow the issue template, also give this a read https://stackoverflow.com/help/minimal-reproducible-example

**Comment by moroz1k** [comment]
corrected

**Comment by merceyz** [comment]
We don't read the `.npmrc` file, it's mentioned in the 4th step in the migration guide https://yarnpkg.com/getting-started/migration#step-by-step

Your `.npmrc` translates to this `.yarnrc.yml` file
```yml
npmScopes:
  adriver:
    npmRegistryServer: https://verdaccio.x

enableStrictSsl: false
```
https://yarnpkg.com/configuration/yarnrc
