### ISSUE TITLE
Bug - Yarn run hangs when binary and package.json script share same name

### ISSUE THREAD

**Issue by wdfinch** [yarnpkg/berry#2619]
- [ ] I'd be willing to implement a fix

**Describe the bug**
If:

1. A runabled  binary package is installed
2. We add a script to our package.json with the same name as the binary
3. We run yarn run using the name of the binary

Then:
yarn run will simply hang and freeze until we send an interrupt signal.

**To Reproduce**
1. run `yarn init`
2. run `yarn add prettier`
3. add the following to package.json

```
"scripts": {
    "prettier": "yarn run prettier ."
  }
```

4. run `yarn run prettier`

OR:
1. Open the attached project and run `yarn run prettier`

[binary-bug.zip](https://github.com/yarnpkg/berry/files/6174914/binary-bug.zip)

**Screenshots**
https://user-images.githubusercontent.com/36898266/111859277-da44a500-88fc-11eb-8bf4-ad416d0e1fdd.mp4

**Environment if relevant (please complete the following information):**

 - OS: Linux - Ubuntu 20.04.2.0 LTS
 - Node version: v15.12.0.
 - Yarn version: 2.4.1

**Additional context**

I understand if this is not allowed as it's cyclical. However, an error message should be thrown rather than hanging.

**Comment by arcanis** [comment]
Remove `yarn run` from your script. Binaries are exposed in scripts through the PATH, so you don't need to run them via yarn.

**Comment by wdfinch** [comment]
Makes sense. Just wanted to point this out as hanging is not really the best result for this mistake. Maybe an error message would be more helpful.
