### ISSUE TITLE
[Bug] - prettier plugins don't work

### ISSUE THREAD

**Issue by wdfinch** [yarnpkg/berry#2654]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I noticed this bug when used `prettier`, however, it could occur with other binaries that use a plugin-based architecture. In the case of `prettier`, it seems that plugins simply don't work when the prettier command is run via `yarn run`.

**To Reproduce**

[prettier-plugin-issues.zip](https://github.com/yarnpkg/berry/files/6223381/prettier-plugin-issues.zip)

1. Open the attached project.
2. Run `yarn install` with the version set the latest berry
3. Run `yarn run format-prettier`
4. Notice that while prettier does run successfully, the `prettier-plugin-organize-imports` plugin does not run at all. This can be verified by noticing that in App.tsx, the import to `react` is not moved to the top.

This plugin does not require any setup to run and works fine in yarn 1 and npm.

https://www.npmjs.com/package/prettier-plugin-organize-imports

**Screenshots**
https://user-images.githubusercontent.com/36898266/112874260-8f066100-9077-11eb-9330-e312f8ca8536.mp4

**Environment if relevant (please complete the following information):**

 - OS: Ubuntu 20.04.2.0 LTS
 - Node version v15.12.0
 - Yarn version 2.4.1

**Additional context**

I looked through the yarn config options to see if there was some option to fix this. I didn't find anything. Please let me know if this is the intended behavior. Additionally, this could be an issue with the plugin or prettier. If so, I would be happy to open a PR on one of those libraries to resolve it. I just need some more information on why this doesn't work.

**Comment by merceyz** [comment]
Prettier scans the `node_modules` folder for plugins which doesn't exist under PnP so you need to explicitly list your plugins in the prettier config

Creating this `.prettierrc` file fixes the issue
```json
{
  "plugins": [
    "prettier-plugin-organize-imports"
  ]
}
```

**Comment by wdfinch** [comment]
Thanks!

**Comment by pix2D** [comment]
While the above fixes the CLI I was still getting an error from prettier-vscode saying that it couldn't find the plugin. The fix was to change `.prettierrc` to `.prettierrc.js` and adjust the content as follows:

```js
module.exports = {
  plugins: [
    require('prettier-plugin-organize-imports')
  ]
}
```

Just in case anyone else runs into this. 🙂
