### ISSUE TITLE
[Feature] Aliases workspace:^ and workspace:~

### ISSUE THREAD

**Issue by javier-garcia-meteologica** [yarnpkg/berry#2658]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

I would like that versions of workspace package dependencies to refer to the latest available version, and at the same time make them compatible with future security patches or minor improvements.

Right now there is `workspace:*` which updates the version of a workspace dependency automatically on release. This is good because the package.json#dependencies always point to versions known to work with the package and tested (if tests are run before release).

But it's excessively specific. `workspace: *` is substituted with an exact version like `"dep": "1.0.0"`, which is incompatible with future security patches or minor improvements of the dependency.

**Describe the solution you'd like**

I would like to specify `"dep": "workspace:~"` and to be substituted on release with the current version of "dep" but allowing security patches, e.g. `"dep": "workspace:~1.0.0"`. Also I think it would be useful to specify `"dep": "workspace:^"` and get `"dep": "workspace:^1.0.0"`.

**Describe the drawbacks of your solution**

More complexity and there is a risk of creating technical debt

**Describe alternatives you've considered**

Specifying full workspace versions `workspace:~0.9.0` and running a script before release to bump the version number, but it's kind of ugly.

Related
https://github.com/pnpm/pnpm/issues/3116

**Comment by arcanis** [comment]
Yep, I'd be open to have support for `workspace:~` and `workspace:^` 👍

**Comment by certainlynotprithvi** [comment]
Hi @arcanis @javier-garcia-meteologica I would like a try at this issue

So just to write out my understanding

If the workspace has dependencies `a:1.0.0`, `b:2.0.0` `c:3.0.0` with `a`,`b`,`c` being npm packages, the following declarations should be the result of this enhancement

`a: workspace:*` => `a: 1.0.0`
`b: workspace:^` => `b: ^2.0.0`
`c: workspace:~` => `c: ~3.0.0`

**Comment by javier-garcia-meteologica** [comment]
@certainlynotprithvi that is right, those substitutions have to be made when the project is packed.

For internal dependency resolution, the behavior of `workspace:^` and `workspace:~` is the same as `workspace:*`. That is, they point to a project in the workspace that matches the name of the package.

**Comment by arcanis** [comment]
Indeed 👍

For the pack translation logic, the relevant source code is here:
https://github.com/yarnpkg/berry/blob/master/packages/plugin-pack/sources/index.ts#L43-L68

For the workspace selection, the relevant line is here:
https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/sources/Workspace.ts#L101

Note that we'll also need tests, which would be implemented here:
https://github.com/yarnpkg/berry/blob/master/packages/acceptance-tests/pkg-tests-specs/sources/protocols/workspace.test.ts
