### ISSUE TITLE
[Bug] require.resolve returns different result when using workspace virtual path as baseDir

### ISSUE THREAD

**Issue by remorses** [yarnpkg/berry#2663]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Running the following code in a monorepo prints 2 different results

```js
const path = require("path");

console.log(
  require.resolve("react-scroll", {
    paths: [
      path.resolve(
        "./.yarn/$$virtual/@sterblue-web-atoms-virtual-d35860cf4b/1/packages/web/atoms/src/button/button.tsx"
      )
    ]
  })
);
console.log(
  require.resolve("react-scroll", {
    paths: [path.resolve("./packages/web/atoms/src/button/button.tsx")]
  })
);

```

```
/Users/morse/Documents/GitHub/sterblue1/.yarn/$$virtual/react-scroll-virtual-0e7cdca06d/0/cache/react-scroll-npm-1.7.3-6d6493b1a5-84e8306bf5.zip/node_modules/react-scroll/modules/index.js

/Users/morse/Documents/GitHub/sterblue1/.yarn/$$virtual/react-scroll-virtual-2e12435852/0/cache/react-scroll-npm-1.7.3-6d6493b1a5-84e8306bf5.zip/node_modules/react-scroll/modules/index.js
```

As you can see one is `react-scroll-virtual-2e12435852` while the other is `react-scroll-virtual-0e7cdca06d`

Is there any workaround to make the returned result always the same?

**To Reproduce**

This is not easy to reproduce in a smaller repro, i have no idea what is causing this

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: mac
 - Node version, 14
 - Yarn version 2.3.0

**Additional context**

I already checked that there was no additional node_modules folder in the workspace directory

**Comment by merceyz** [comment]
> Yarn version 2.3.0

Try with `yarn set version from sources`, https://github.com/yarnpkg/berry/pull/2568 might be related

**Comment by merceyz** [comment]
The difference is which peer dependencies are provided by the parent, you can check why you have different instances with
```
yarn info <package-name> --virtuals -A --dependents
```

**Comment by remorses** [comment]
I solved this always using `pnpapi.resolveVirtual` on workspace packages

I am closing this since i haven't repro code
