### ISSUE TITLE
[Bug] `plugin-node-modules` picks the wrong bin executables for Workspaces

### ISSUE THREAD

**Issue by alizeait** [yarnpkg/berry#2666]
- [x] I'd be willing to implement a fix

**Describe the bug**
In a monorepo with multiple workspaces, node-modules node linker picks another workspaces' bin executable (seems to be the bottom most it finds) instead of preferring the current workspace.

**To Reproduce**

    └── root-workspace/
        ├── apps/
        │   ├── app-workspace-1/
        │   │   └── package.json
        │   ├── app-workspace-2/
        │   │   └── package.json
        │   └── app-workspace-3/
        │       └── package.json
        └── package.json

The root `package.json` has a dependency on `node_modules-path 2.0.5`, all other workspaces have a dependency on `node_modules-path 2.0.4` so that a `node_modules-path` folder is added in each of the workspaces in `apps/`. 
`node_modules-path` has a bin executable in each of the `node_modules` folders that prints the location of the current node_modules folder.
Cd into `app-workspace-2` and run `yarn node_modules node_modules-path` for example, you notice that yarn picks the `node_modules-path` bin executable in `app-workspace-3` instead of the current `app-workspace-2` we are in.

**Reproduction repo**:  [Minimal reproduction repository](https://github.com/alizeait/yarn-node-linker-bin-issue)
**Environment**
 - OS: MacOS and Windows
 - Yarn version 2.4.1

**Comment by larixer** [comment]
@alizeait Yes, makes sense to me, but I would rather use `ppath.contains` instead of `startsWith`, plus integration test should be added to check this behaviour. Would you like to open a Pull Request?

**Comment by alizeait** [comment]
@larixer sure
