### ISSUE TITLE
[Bug] yarn config unset does not work

### ISSUE THREAD

**Issue by robi-wan** [yarnpkg/berry#2667]
- [ ] I'd be willing to implement a fix

**Describe the bug**

`yarn config unset` does not work as described https://yarnpkg.com/cli/config/unset :
```
❯ yarn config unset httpProxy
Unknown Syntax Error: Extraneous positional argument ("unset").

$ yarn config [-v,--verbose] [--why] [--json]
```
**To Reproduce**

```
❯ yarn config unset httpProxy
Unknown Syntax Error: Extraneous positional argument ("unset").

$ yarn config [-v,--verbose] [--why] [--json]
```

I had this experience in a project of our company.
I can also reproduce this with a "fresh" project when following the steps in https://yarnpkg.com/getting-started/install#per-project-install

**Environment

 - OS: Windows 10; PowerShell 
 - Node version v14.16.0
 - Npm version 6.14.11
 - Yarn version 2.4.1

**Comment by robi-wan** [comment]
I updated to the  latest build fresh from master:
```
> yarn set version from sources
[..]

> yarn --version                                                                                                                                                                      2.4.0-git.20210331.hash-e2e659bb  
                                                                                                                                                                               
> yarn config unset httpProxy
➤ YN0000: Successfully unset httpProxy
```
It seems to be fixed in master.
When will there be a release?

**Comment by arcanis** [comment]
Soonish
