### ISSUE TITLE
@yarnpkg/lockfile fails to parse yarn2 lockfile

### ISSUE THREAD

**Issue by sangharshcs** [yarnpkg/berry#2671]
$ ../node_modules/@yarnpkg/lockfile/index.js:5064
    throw new SyntaxError(`${msg} ${this.token.line}:${this.token.col} in ${this.fileLoc}`);
    ^

SyntaxError: Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in lockfile

**Comment by arcanis** [comment]
Lockfile v2 is standard yaml and can be parsed with a yaml parser. The lockfile package isn't maintained anymore.

**Comment by jonyen** [comment]
> Lockfile v2 is standard yaml and can be parsed with a yaml parser. The lockfile package isn't maintained anymore.

I tried using the `yaml` library to parse `yarn.lock` for a v2 lockfile and got `YAMLParseError: Implicit keys need to be on a single line`.

With `js-yaml`, I got `YAMLException: bad indentation of a mapping entry`.
