### ISSUE TITLE
[Bug] `preinstall` is not run at all when running `yarn`

### ISSUE THREAD

**Issue by sushruth** [yarnpkg/berry#2689]
- [ ] I'd be willing to implement a fix

**Describe the bug**

preinstall script does not seem to get executed on `yarn install` at all.

**To Reproduce**

1. Run these on an empty directory - 

```sh
yarn set version berry
yarn set version latest # the one that was downloaded for me was yarn-2.4.1.cjs
yarn init
```

2. and then add a preinstall script to the package.json in that directory -

```json
{
  "name": "package",
  "scripts": {
    "preinstall": "echo 'Preinstall - hello!'"
  }
}
```
3. Run `yarn install`

**Screenshots**

No evidence of having the preinstall script run - 

![image](https://user-images.githubusercontent.com/2114206/113600329-b23f8c00-95f4-11eb-8f97-96d4fb96a507.png)

 - OS: `Windows`
 - Node version: `14.16.0`
 - Yarn version: `2.4.1`

**Comment by merceyz** [comment]
Your screenshot shows it runs on your first `yarn install`, on the second your dependencies haven't changed so it's skipped.

If you want to see the output set `enableInlineBuilds: true` in your `.yarnrc.yml` file https://yarnpkg.com/configuration/yarnrc#enableInlineBuilds

**Comment by sushruth** [comment]
Can you please point to where it was run? I can't see the `echo` being executed. I might be missing it. Please help.

Thanks.

**Comment by sushruth** [comment]
That is a very hidden way to see if our scripts worked if we depend on stdio. Can this be added to the docs in the https://yarnpkg.com/advanced/lifecycle-scripts page?
