### ISSUE TITLE
[Feature] Command or flag to verify yarn version matches released version

### ISSUE THREAD

**Issue by matheusd** [yarnpkg/berry#2695]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

While having yarn committed to in my repo (`.yarn/releases`) is useful to ensure a consistent version is used by all developers, it's also important to ensure when changing/upgrading it that no extraneous (potentially malicious) changes have been introduced by the developer committing the changes.

This is particularly true if the project accepts external PRs, given that maliciously changing yarn is a possible way to compromise developer environments.

**Describe the solution you'd like**

Some flag or new command that verifies that the committed to version in `.yarn/releases` actually matches some official release, without changes. 

This could then be added to CI to ensure any upgrades to the project-wide yarn actually match an official release.

**Comment by merceyz** [comment]
Set someone trusted as the owner of `.yarn` and set GitHub to require their review before merging, example: https://github.com/yarnpkg/berry/blob/75e142f7f9afa358ab573ad788916170caac4467/CODEOWNERS#L1

> Some flag or new command that verifies that the committed to version in .yarn/releases actually matches some official release, without changes.

If they've already modified the binary they could have removed / disabled that check and make it report that all is good.
