### ISSUE TITLE
[Bug] VS Code can not found peerDependencies 

### ISSUE THREAD

**Issue by s97712** [yarnpkg/berry#2708]
- [ ] I'd be willing to implement a fix

**To Reproduce**
1. Set up [editor-sdks](https://yarnpkg.com/getting-started/editor-sdks)
1. `$ yarn workspace foo add @nestjs/common --peer`
2. add `import @nestjs/common` to `foo/index.ts`

VS Code will show error: `Cannot find module '@nestjs/common' or its corresponding type declarations.`

**Environment if relevant (please complete the following information):**

 - OS: [e.g. OSX, Linux, Windows, ...]
 - Node version [e.g. 8.15.0, 10.15.1, ...]
 - Yarn version [e.g. 2.4.0, ...]

**Additional context**

**Comment by merceyz** [comment]
Follow the issue template and provide an actual reproduction - https://stackoverflow.com/help/minimal-reproducible-example

**Comment by andreialecu** [comment]
You need to add it both as a peer and a dev dependency as well in order for VS Code to find it.

**Comment by mmahalwy** [comment]
@andreialecu is there no way to install peers automatically like npm 7-8?

**Comment by arcanis** [comment]
No.

**Comment by mmahalwy** [comment]
@arcanis perhaps this would make a good plugin?
