### ISSUE TITLE
[Bug] Not Found error during resolution step when upgrading to berry

### ISSUE THREAD

**Issue by mattlong** [yarnpkg/berry#2710]
- [ ] I'd be willing to implement a fix

**Describe the bug**

While  upgrading to berry, getting a 404 error on the initial v2 `yarn install`. Traced the issue to the nollup package, which doesn't raise any errors in yarn v1.

**To Reproduce**

```sh repro
yarn init --yes
yarn add nollup@0.16.1
yarn set version berry
echo "nodeLinker: node-modules" >> .yarnrc.yml
yarn install
```

Output from `yarn install`:

```
➤ YN0000: ┌ Resolution step
➤ YN0001: │ HTTPError: Response code 404 (Not Found)
    at se.<anonymous> (/Users/mattlong/projects/yarn-bug/.yarn/releases/yarn-berry.cjs:23:10082)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
➤ YN0000: └ Completed in 0s 357ms
➤ YN0000: Failed with errors in 0s 361ms
➤ YN0032: fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0032: fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
```

**Environment:**

 - OS: OSX 10.15.7
 - Node version: 14.15.0
 - Yarn version: Upgrading from 1.22.10 to 2.4.1

**Comment by arcanis** [comment]
I'm not sure what happens exactly, but it doesn't appear anymore with master (`yarn set version from sources`), so I think it can be considered as fixed.

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/2570
