### ISSUE TITLE
[Feature] Don't apply built-in patches when using node_modules resolver

### ISSUE THREAD

**Issue by orta** [yarnpkg/berry#2711]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

The patches _to my knowledge_ are to handle pnp, but when resolving node_modules they shouldn't need to be applied

Sometimes to use a TypeScript beta you have to update yarn https://github.com/yarnpkg/berry/pull/2672 because the patches can't be applied due to changes in the TS codebase. This isn't a critical issue as it's normally likely that someone with experience in both TS + yarn can handle the update but the TS website updates pretty early, and I'd love to be able to have other compiler folks updating the TS version and not have to also handle the yarn update process

**Describe the solution you'd like**

No user settings in my project

**Describe the drawbacks of your solution**

Perhaps `@yarnpkg/plugin-compat` noops when node_modules resolver?

**Describe alternatives you've considered**

An option/env var which suppresses the patches

**Comment by orta** [comment]
👍🏻 that works for me

**Comment by merceyz** [comment]
Perfect, I'll close this then 👍
