### ISSUE TITLE
[Bug] Unsafe http requests with `yarn plugin import` and redirection

### ISSUE THREAD

**Issue by bertho-zero** [yarnpkg/berry#2721]
- [ ] I'd be willing to implement a fix

**Describe the bug**

It seems that the `yarn plugin import` command does not support unpkg redirects, yet the first URL only redirects to the second.

**Screenshots**

![image](https://user-images.githubusercontent.com/8525267/114202028-18ab0e00-9957-11eb-89d6-54538585f800.png)

**Comment by merceyz** [comment]
`http` requests are blocked by default, if you want to enable them look at https://yarnpkg.com/configuration/yarnrc#unsafeHttpWhitelist

**Comment by bertho-zero** [comment]
I understood that correctly, but why does it work for the second request then?

**Comment by arcanis** [comment]
Because it's an http**S** request.

**Comment by bertho-zero** [comment]
Ah, thanks !
