### ISSUE TITLE
[Bug] yarn patch-commit with -s option throw an error

### ISSUE THREAD

**Issue by bertho-zero** [yarnpkg/berry#2722]
**Describe the bug**

After a small patch I try to save my changes but the `--save` option of the [doc](https://yarnpkg.com/cli/patch-commit#options-s%2C-save) did not recognized.

**Screenshots**

![image](https://user-images.githubusercontent.com/8525267/114214967-4dbe5d00-9965-11eb-8e7f-9c237062f96f.png)

I use Yarn v2.4.1

**Comment by merceyz** [comment]
Due to how it's set up the docs are for `master` and not for the latest release, the `--save` option was added in https://github.com/yarnpkg/berry/pull/2508 which hasn't been released yet. You can start using it now by running
```sh
yarn set version from sources
```
