### ISSUE TITLE
.env not read so ${ENV_VAR} unusable in .yarnrc.yml

### ISSUE THREAD

**Issue by lensbart** [yarnpkg/berry#2724]
**Describe the bug**

I’m sure I must be doing something wrong, but I can’t get yarn to read the environment variables in my `.env` file, causing any `yarn` command to throw the following error when `${ENVIRONMENT_VARIABLES}` are used in `.yarnrc.yml`:

    Usage Error: Environment variable not found (ENVIRONMENT_VARIABLES) in [...]/.yarnrc.yml (in [...]/.yarnrc.yml)

Could it be that I have to configure something? The docs don’t seem to mention so.

**To Reproduce**

Clone this example repo and run `yarn`: https://github.com/lensbart/yarn

 - macOS 11.2.3 (20D91)
 - Node v14.16.0
 - Yarn version 2.4.1

Note: I didn’t use Sherlock because I thought this might interfere with resolving the .env file

**Comment by merceyz** [comment]
Yarn doesn't read `.env` files, it reads your environment variables from `process.env.***`

**Comment by lensbart** [comment]
Thanks for the (very) quick response. Could you suggest a recommended way to have the .env file made available to yarn via `process.env.***`? Usually I would use the `dotenv` package, but not sure how to do so via the CLI.

Thanks again!

**Comment by arcanis** [comment]
Why not put them in your bashrc/zshrc/...?

**Comment by lensbart** [comment]
Brilliant! Not only did this fix my problem, but I can get rid of my `dotenv` dependency as well. And that on a Friday evening!! 😁

**Comment by CharlesStover** [comment]
I still think this is valid. I don't want to put it in `.zshrc` because it only applies to the one repository, e.g. a secret/access key for pulling dependencies from a private registry. I may want to configure this differently for each repository. Yarn should support repo-specific environment variables.

**Comment by theoavoyne** [comment]
I agree. Typical use case is for NPM auth tokens that may differ from a project to an other. It'd be great if Yarn could read the `.env` file before performing any logic, or at least let us opt in for that behaviour (e.g. by explicitly specifying a path to the file in question). Can try to work on a PR if it's a setting that you'd consider integrating.

**Comment by slaesh** [comment]
@theoavoyne would love to see your PR coming :)

**Comment by theoavoyne** [comment]
@slaesh #3938
