### ISSUE TITLE
[Bug] Workspace manifest.raw should be updated when persisting the manifest

### ISSUE THREAD

**Issue by noahnu** [yarnpkg/berry#2725]
- [x] I'd be willing to implement a fix

**Describe the bug**

In the Node API, if you update a workspace and then call `workspace.persistManifest()`, the `workspace.manifest.raw` still points to the old value. There is no way to reload the raw value without calling `workspace.setup()` again, which is potentially expensive (due to the globbing and other unnecessary duplicate setups).

**To Reproduce**

Modify a dependency and then call persistManifest.

```
workspace.manifest.getForScope("dependencies").set(someIdentHash, someUpdatedDescriptor)
await workspace.persistManifest()
```

If you inspect `workspace.manifest.raw`, it won't contain the dependency change.

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version v14.16.0
 - Yarn version: 2.4.1

**Additional context**

Temporarily working around it by calling `await workspace.setup()` after the persistManifest.

Not sure if this is strictly a "bug", however in https://github.com/yarnpkg/berry/blob/e81dc0d29bb2f41818d9c5c1c74bab1406fb979b/packages/yarnpkg-core/sources/Workspace.ts#L187 we have the contents we're "persisting", so it seems like it'd be free to just update `workspace.manifest.raw`.

**Comment by arcanis** [comment]
I think it would make sense - do you want to give a try at a PR?

One question I have though is that I'd expect you to access the dependencies through the non-raw fields. While I guess having raw up-to-date can be handy to just feed it to something expecting a package.json, is there another use case I forget?

**Comment by noahnu** [comment]
Right after modifying the dependencies via the non-raw field and calling persistManifest, I trigger an npm publish via npmPublishUtils. The publish utils reads manifest.raw to generate the publish stream.

And yep, I can put up a PR

**Comment by merceyz** [comment]
You can manually update `raw` to the new value like we do in the constraints plugin https://github.com/yarnpkg/berry/blob/e8deea6ab56d2da1ece24dbfbd8799aef5e7a20e/packages/plugin-constraints/sources/commands/constraints.ts#L66-L68

**Comment by merceyz** [comment]
Perhaps `genPackageManifest` should be modified to use the `exportTo` function 
https://github.com/yarnpkg/berry/blob/9d1734d3fcaba1e1fa1f0077005c248166ba1ef6/packages/plugin-pack/sources/packUtils.ts#L141-L151
