### ISSUE TITLE
[Bug] node subprocesses aren't loaded with .pnp.js

### ISSUE THREAD

**Issue by davazp** [yarnpkg/berry#2730]
- [x] I'd be willing to implement a fix

**Describe the bug**

After I generated the SDKs for a typescript project with `yarn dlx @yarnpkg/pnpify --sdk base`,  I can't start tsserver with or without `.pnp.js` preloaded:

```
% node -r ./.pnp.js .yarn/sdks/typescript/bin/tsserver
Content-Length: 75

{"seq":0,"type":"event","event":"typingsInstallerPid","body":{"pid":3711}}
node:internal/modules/cjs/loader:927
  throw err;
  ^

Error: Cannot find module '/Users/davazp/Projects/yarn-plugin-workspace-export/.yarn/cache/typescript-patch-70a7929abf-3be4431759.zip/node_modules/typescript/lib/typingsInstaller.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

## The root cause and a possible solution?

I noticed that this works if I invoke the script with `yarn node` instead. I narrowed down the differences between `yarn node` and `.pnp.js` to the latter not providing the environment variable:

```
NODE_OPTIONS: '--require /Users/davazp/Projects/yarn-plugin-workspace-export/.pnp.js'
```

This probably means that `tsserver` is trying to start a secondary node process, which fails to have `.pnp.js` loaded.

This has potentially a lot more reach than just running SDKs.  Should `.pnp.js` add an option to load itself to `NODE_OPTIONS` environment variable itself as well?  

I checked and `.pnprc` seems to fall back to loading from `node_modules/` in external projects.  But would this potentially dangerous if a program is running `node` against another project not using `yarn` in another way? 

**To Reproduce**

Sorry, I couldn't make it work as a Sherlock test case. Instead, I shared a minimal repository:

https://github.com/davazp/berry-sdk-issue

 - OS: OSX
 - Node version: v15.13.0
 - Yarn version: 2.4.1

**Comment by merceyz** [comment]
Looks like TypeScript filters out the `-r` flag https://github.com/microsoft/TypeScript/blob/38da7c600c83e7b31193a62495239a0fe478cb67/src/tsserver/nodeServer.ts#L496-L508

**Comment by davazp** [comment]
We can call the [`generateSDK`  function with `setupEnv: true` ](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-pnpify/sources/generateSdk.ts#L138-L146)option here:

https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-pnpify/sources/sdks/base.ts#L153

to make sure the SDK sets up NODE_MODULES. 

This fixes the original issue for me.

**Comment by merceyz** [comment]
We did that before but disabled it because it caused npm (when launched by vscode) to be really, really slow - https://github.com/yarnpkg/berry/pull/800

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/2805
