### ISSUE TITLE
[Bug] plugin artifacts for 3.0.0-rc.1 wasn't updated

### ISSUE THREAD

**Issue by doormalena** [yarnpkg/berry#2740]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Latest master version of today (12th of April) is broken when used in combination with plugin `workspace-tools`.

**To Reproduce**
Execute the following:
```cli
yarn set version berry
yarn plugin import workspace-tools
yarn workspaces focus --production
```

**Screenshots**

```txt
Usage Error: This plugin cannot access the package referenced via yup which is neither a builtin, nor an exposed entry (when initializing @yarnpkg/plugin-workspace-tools, defined in /home/vsts/work/1/s/.yarnrc.yml)

Yarn Package Manager - 3.0.0-rc.1

  $ yarn <command>

You can also print more details about any of these commands by calling them with 
the `-h,--help` flag right after the command name.
```

**Environment if relevant (please complete the following information):**

 - OS: Both Linux as Windows
 - Node version: 15.14
 - Yarn version: code name Berry (master / 12th April)

**Additional context**
Used within Azure DevOps hosted pipeline to restore NPM packages.

**Comment by merceyz** [comment]
You need to remove the plugins entry in `.yarnrc.yml` and run the import again

**Comment by doormalena** [comment]
> 
> 
> You need to remove the plugins entry in `.yarnrc.yml` and run the import again

Its executed on a clean CI server.

Tested this also locally on my desktop: after removing it manually and importing the plugin again, the issue reappears. 
Without the plugin, the issue does not occur.

**Comment by merceyz** [comment]
Something went wrong in the release and the artifacts didn't update, you can workaround it by running
```
yarn plugin import from sources workspace-tools
```
https://yarnpkg.com/cli/plugin/import/from/sources

**Comment by doormalena** [comment]
Thanks for fast response and workaround. Seems to work for now.

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/commit/ff11472eb61ac9522e4a58d4092025efac09bffc
