### ISSUE TITLE
[Bug] Wrong version set with "yarn set version berry"

### ISSUE THREAD

**Issue by brunozoric** [yarnpkg/berry#2741]
- [ ] I'd be willing to implement a fix

**Describe the bug**

When setting yarn version to berry it is set to 3.0.0-rc.1, expected behaviour is to set it to latest v2
In the docs it says:
````
"Berry" is the codename for the Yarn 2 release line. It's also the name of our repository!
````

**To Reproduce**

Create empty directory, go into it and type `yarn set version berry`.
Then type `yarn --version` and you get it is a 3.0.0-rc.1 version.

**Screenshots**

<img width="650" alt="Screenshot 2021-04-12 at 13 34 11" src="https://user-images.githubusercontent.com/10399339/114388793-7aa48700-9b94-11eb-9f60-543880632a07.png">

**Environment if relevant (please complete the following information):**

 - OS: macOS Big Sur 11.2.3
 - Node version: 12.19.0
 - Yarn version: latest

**Comment by adam-dilibero** [comment]
Nothing more to add here but could replicate for our applications also using steps above as @brunozoric mentioned.

**Comment by doitadrian** [comment]
I'd just like add that, even specifying the exact `yarn` version fails for reason mentioned below (this is a test I did in a simple GH action):

![image](https://user-images.githubusercontent.com/5121148/114400096-e93c1180-9ba1-11eb-85e9-2624ee7ffa46.png)

**Comment by arcanis** [comment]
Indeed - I'll fix that today. In the meantime you can run `yarn set version 2.4.1` to workaround the issue.

**Comment by doitadrian** [comment]
Hey @arcanis, thanks for the fast response.

Just a quick reminder that `yarn set version 2.4.1` doesn't work either (check my screenshot above).

In fact, I tried to do some local debugging and this is what I've found...

![image](https://user-images.githubusercontent.com/5121148/114402661-581a6a00-9ba4-11eb-8cf5-ab53997281a3.png)

**Comment by arcanis** [comment]
Indeed, since 1.x and 2.x are different codebase they sometime diverge on this command ... in the case the "exact version" syntax is only supported by Yarn 2 - so first need to upgrade, then downgrade. We certainly should uniformize those syntax ... (if someone wants to submit a PR it'd be much appreciated!)

**Comment by arcanis** [comment]
Should now be fixed 👍

**Comment by doitadrian** [comment]
Thanks a lot @arcanis, works now!

**Comment by jeffrson** [comment]
Well, actually yarn 1.2.11 still installs yarn 3 by
`yarn set version 2`
since it's probably hardcoded to berry:
```
$ yarn -v
1.22.11
$ yarn set version 2
Resolving 2 to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
Saving it into ...\.yarn\releases\yarn-berry.cjs...
Updating .../.yarnrc.yml...
Done!
```
