### ISSUE TITLE
[Bug] `yarn version` not working in 2.4.1

### ISSUE THREAD

**Issue by Marvin1003** [yarnpkg/berry#2743]
- [ ] I'd be willing to implement a fix

**Describe the bug**

`yarn version` doesn't work anymore. I get the following error even though the plugin has been successfully installed:
```zsh
Usage Error: Couldn't find a script named "version", but a matching command can be found in the version plugin. You can install it with "yarn plugin import version".
```
 With 3.0.0-rc.1 everything works as expected.
This is probably related to the new release as it was working before.
https://yarnpkg.com/cli/version

**To Reproduce**
  ```zsh
yarn set version 2.4.1
yarn plugin import version
yarn version
  ```

**Screenshots**
![yarn-version-issue](https://user-images.githubusercontent.com/22097877/114414129-da0f9080-9bae-11eb-8505-ce379550d623.png)

**Environment if relevant (please complete the following information):**

 - OS: Linux
 - Node version: 14.16.0
 - Yarn version: 2.4.1

**Comment by arcanis** [comment]
I've just fixed a few things related to how plugins are distributed. Try removing all references to them from your `.yarnrc.yml`, then run `yarn plugin import version` again.
