### ISSUE TITLE
[Feature] Big Endian Support

### ISSUE THREAD

**Issue by V-for-Vasili** [yarnpkg/berry#2745]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

Hello!

**Describe the user story**

It seems that yarn v2 does not support Big-Endian architectures as of now;
Specifically, an assertion fails in [packages/plugin-interactive-tools/bin/@yarnpkg/plugin-interactive-tools.js](https://github.com/yarnpkg/berry/blob/master/packages/plugin-interactive-tools/bin/%40yarnpkg/plugin-interactive-tools.js) and
[packages/plugin-version/bin/@yarnpkg/plugin-version.js](https://github.com/yarnpkg/berry/blob/master/packages/plugin-version/bin/%40yarnpkg/plugin-version.js), with error message `"Runtime error: expected the system to be little-endian!"` that appears to be produced by Emscripten when these files are generated.

**Describe the solution you'd like**

As of version 2.0.17, emscripten provides optional support for Big Endian machines, if flag `-s SUPPORT_BIG_ENDIAN` is provided: https://github.com/emscripten-core/emscripten/pull/13413. The default behavior without this flag is the same as before (no BE support).

With that in mind, it might be possible to re-generate the `@yarnpkg/plugin-interactive-tools.js` and `@yarnpkg/plugin-version.js` files to enable their usage on BE machines by passing `-s SUPPORT_BIG_ENDIAN` to emscripten during the generation.

**Describe the drawbacks of your solution**

For the files generated by Emscripten with `SUPPORT_BIG_ENDIAN` flag, emitted code size might be slightly increased.

**Comment by V-for-Vasili** [comment]
cc @miladfarca

**Comment by arcanis** [comment]
Both of those plugins include `ink`, which is the one containing emscripten code (for `yoga-layout`, iirc).

We also use a wasm chunk (for the libzip), I'd expect it to fail as well 🤔 Generally speaking I'm slightly worried about merging big endian support when under all likelyhood noone from the core team will be able to test against it, much less debug it should it cause issues... Is there a concrete use case you have in mind?

**Comment by V-for-Vasili** [comment]
Thanks for your feedback!

Specific use case is using citgm on Big Endian machine with --yarn flag as follows `node bin/citgm --yarn -s -- jest` produces the above error message at the install step.

I have searched the docs related to plugins (https://yarnpkg.com/features/plugins, https://yarnpkg.com/advanced/plugin-tutorial) and `@yarnpkg/builder`, but could not find the exact way how the minified .js plugin files (packages/plugin-interactive-tools/bin/@yarnpkg/plugin-interactive-tools.js and packages/plugin-version/bin/@yarnpkg/plugin-version.js) are generated.

If nothing else maybe I could regenerate them on my own as an alternative to making a change in Yarn.

Would you be able to point me in the right direction?

**Comment by arcanis** [comment]
They are built by running `yarn build:plugin-<interactive-tools|version>` from this repository, which go into [this command](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-builder/sources/commands/build/plugin.ts#L75). The problem is that [ink](https://github.com/vadimdemedes/ink) depends on [yoga-layout-prebuilt](https://github.com/vadimdemedes/yoga-layout-prebuilt), so both would likely need to be updated before changing our code 🤔

**Comment by V-for-Vasili** [comment]
Thanks a lot!

**Comment by V-for-Vasili** [comment]
Coming back to the conversation - regarding your previous comment:

> Generally speaking I'm slightly worried about merging big endian support when under all likelyhood noone from the core team will be able to test against it, much less debug it should it cause issues

Would you be open to adding Big Endian support in the future provided that there is a periodic CI setup on IBM side (on Big Endian machine) and occasional troubleshooting by us if there are any issues? (Provided of course that dependencies such as [ink](https://github.com/vadimdemedes/ink) and [yoga-layout-prebuilt](https://github.com/vadimdemedes/yoga-layout-prebuilt) are addressed as well).

cc @mhdawson, @miladfarca, @ThePrez

**Comment by merceyz** [comment]
Note that since @arcanis made that comment we've been able to test on a big endian emulator in https://github.com/yarnpkg/berry/pull/3669

**Comment by merceyz** [comment]
#3669 has been released in `4.0.0-rc.12`
```sh
yarn set version canary
```

**Comment by sinceresiva** [comment]
I am trying to build Grafana v9.0.2 with yarn-4.0.0-rc.12. However I am still getting the (little-endian) error in my s390x system (zLinux) as given below: 
-----------------------------
Internal Error: Execution failed with a non-error rejection (rejected value: "Runtime error: expected the system to be little-endian!")
    at Qa.error (/srv/grafana-install/.yarn/releases/yarn-4.0.0-rc.12.cjs:121:305)
    at r (/srv/grafana-install/.yarn/releases/yarn-4.0.0-rc.12.cjs:375:2195)
-----------------------------
Here are the steps I have followed:
**Pre-requisite**: Download grafana-v9.0.2 source from https://github.com/grafana/grafana/archive/refs/tags/v9.0.2.tar.gz and extract it to <grafana_root> folder:
1. From the parent directory of <grafana_root> folder I executed: **sudo yarn set version 4.0.0-rc.12**. Now yarn -v shows version correctly as as **4.0.0-rc.12**.
2. Set the **yarnPath** in **<grafana_root>/.yarnrc.yml** to ../.yarn/releases/yarn-4.0.0-rc.12.cjs
3. Executing yarn install on <grafana_root> folder produces the above (little-endian) error.

My environment is:
OS: zLinux (s390x)
NodeJS version: v16.15.1
yarn version: 4.0.0-rc.12
npm version: 8.11.0

Thanks,
Siva

**Comment by merceyz** [comment]
@sinceresiva You'll need to remove [the old plugins](https://github.com/grafana/grafana/blob/f3ee57abefe14962a50a3cd2e462f21fac1e735f/.yarnrc.yml#L77-L80) as well, they are included by default in v4.

**Comment by sinceresiva** [comment]
Thanks. I have removed the old plugins and now **yarn install** works fine. However when I execute **yarn start** or **yarn watch** from the <grafana_root> folder I get the following error: 

-sh-4.2$ sudo yarn start
/root/.yarn/berry/cache/@swc-core-npm-1.2.187-c72c67250c-9.zip/node_modules/@swc/core/binding.js:234
                throw new Error(`Unsupported architecture on Linux: ${arch}`);
                      ^
Error: Unsupported architecture on Linux: s390x
    at Object.<anonymous> (/root/.yarn/berry/cache/@swc-core-npm-1.2.187-c72c67250c-9.zip/node_modules/@swc/core/binding.js:234:23)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require$$0.Module._extensions..js (/srv/grafana-install/grafana-9.0.2/.pnp.cjs:59940:33)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.require$$0.Module._load (/srv/grafana-install/grafana-9.0.2/.pnp.cjs:59780:14)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/.yarn/berry/cache/@swc-core-npm-1.2.187-c72c67250c-9.zip/node_modules/@swc/core/index.js:39:88)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)

Will the yarn team be able to help with this issue? 
Thanks in advance,
Siva

**Comment by JavaPerformance** [comment]
Hi, it appears that SWC have fixed the issue https://github.com/swc-project/swc/issues/5221

It was been released in swc/core 1.2.218.

Hoping that grafana can upgrade to 1.2.218.

I'm not sure if grafana's yarn version also has to be upgraded to >= 4.0.0-rc.12

**Comment by merceyz** [comment]
The way they solved it isn't really compatible Yarn and pnpm so probably wont work.
