### ISSUE TITLE
[BUG] project.install with persistProject: false updates cache

### ISSUE THREAD

**Issue by bertho-zero** [yarnpkg/berry#2748]
- [ ] I'd be willing to implement a fix

**Describe the bug**

For this [plugin](https://github.com/bertho-zero/yarn-plugin-workspace-lockfile) I try to do an install without updating the cache, the goal of the plugin is to create a yarn.lock specific to a workspace.

Everything works but during the installation the cache of the parent project is modified even with the persistProject option set to false.

**Comment by bertho-zero** [comment]
This has the effect of removing and resolving a bunch of things with each run of `yarn`.

I work around the problem by forcing the use of the global cache.

**Comment by merceyz** [comment]
It wont remove anything, but it will add things if it has to 
https://github.com/yarnpkg/berry/blob/95dd7d6fe3e2ddf460a79c529231151d27012044/packages/yarnpkg-core/sources/Project.ts#L1415-L1417

**Comment by bertho-zero** [comment]
Things that will be removed in the next Yarn run from the main project, then rewrites from the plugin.

Ideally I would need a read-only cache.

**Comment by bertho-zero** [comment]
I found how to reuse the resolutions from the root project, the public submodule works with the same dependencies and no longer modifies the cache.

https://github.com/bertho-zero/yarn-plugin-workspace-lockfile/blob/main/packages/plugin/sources/index.ts#L36-L37
