### ISSUE TITLE
[Bug] error Command "plugin" not found.

### ISSUE THREAD

**Issue by nemonemi** [yarnpkg/berry#2750]
**Describe the bug**
After running the `yarn plugin import typescript` an error gets printed out.
Is there any prerequisite that needs to be achieved for this to be used?

```
error Command "plugin" not found.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/77624664/114668533-266ae580-9d01-11eb-8575-e190efea2d3a.png)

**Environment if relevant (please complete the following information):**

 - OS: Windows 10
 - Node version: 14.16.0
 - Yarn version: 1.22.10

**Comment by merceyz** [comment]
That is a Yarn v2+ command, you're on Yarn v1 - https://yarnpkg.com/getting-started/migration
