### ISSUE TITLE
[Bug] --immutable-cache attempts to create directory

### ISSUE THREAD

**Issue by mrginglymus** [yarnpkg/berry#2776]
We currently have a set up that mounts our yarn cache mounted read-only into a docker container for building. On yarn 2.1.1, we run with `--immutable-cache`, and everything worked fine. Since updating to 2.4.1, we now get a permission denied error from trying to create the cache dir.

~It seems as though this problem has come from #2383, which changes the behaviour from creating the cache dir when writing a cache file (which would never happen with `--immutable-cache`, to creating it on the creation of the `Cache`, regardless of the state of immutable.~

**Comment by mrginglymus** [comment]
My apologies, that change appears _not_ to be in 2.4.1. I shall do some further digging.

**Comment by mrginglymus** [comment]
The only other change I can see in this area is https://github.com/yarnpkg/berry/pull/1597

**Comment by mrginglymus** [comment]
Yes, I can confirm that reverting https://github.com/yarnpkg/berry/blob/daaee17c335957a591be4ba51161c52acb86e324/packages/yarnpkg-core/sources/Cache.ts#L124 fixes the issue.

**Comment by mrginglymus** [comment]
@merceyz do you have any advice on how this should be fixed? Would wrapping that line in a `if (!this.immutable)` be reasonable?

**Comment by merceyz** [comment]
When immutable is true you can check if the folder exists and throw if it doesn't
