### ISSUE TITLE
If versioning files were removed from git, yarn version fails

### ISSUE THREAD

**Issue by tjwelde** [yarnpkg/berry#2783]
https://github.com/yarnpkg/berry/blob/a546d725d9f3f9b9881a9d973b48c241935d1910/packages/plugin-version/sources/versionUtils.ts#L226

We had files in `.yarn/versions` being added by accident in squashed and merged PRs.
Someone then removed these files.
When we now try to run `yarn version prerelease`, we get the linked error.

We can't find any way to fix this. No way to reset the versioning files without rewriting our commit history.
We tried adding the files again, updating our yarn and yarn version plugin and using all `yarn version` commands.

I tried to reproduce it from scratch, but when I try to commit the removal of the versioning files. It works in the following example.
We have no idea what to do, so that we can use the command again.

How to reproduce:
- new folder
- `yarn init`
- `yarn set version berry`
- `yarn plugin import version`
- `git init`
- `git add .` & `git commit`
- `yarn version prerelease`
- `git add . ` & `git commit`
- `yarn version prerelease` again (generates a new versioning file)
- `git add . ` & `git commit`
- `rm -r .yarn/versions/`
- `yarn version prerelease` --> here it breaks
- commiting the removal of the files in this example gets rid of the error. For us this does not fix it.

I know it is not ideal for reproducing the problem, please tell me, how I can provide more information.
You can also try it out by cloning https://github.com/KILTprotocol/sdk-js and trying to run `yarn version prerelease`

**Comment by tjwelde** [comment]
We could solve this issue by manually bumping the versions in all our packages in our mono-repo.

**Comment by onichandame** [comment]
I don't think manually editing package.json is a permanent solution. Can we reopen it so the maintainers are more aware of it?

**Comment by parkerault** [comment]
We just started getting this error in our monorepo and I have no idea what caused it. We've been using this workflow for the last six months and never had any issues with it. We've always checked in the versioning files, and git removes them when the versions are applied, of course. We get this error on every branch and it's broken our release workflow, and I wouldn't even know where to start editing the git history to that extent.

**Comment by Tjerk-Haaye-Henricus** [comment]
Hey guys i have the same issue on a massive monorepo. I wonder how this issue can be closed without it's being resolved since this is a really important feature of yarn. I will open another issue since I made the experience if an issue is closed once it will not been touched again :)

**Comment by prakharsingh** [comment]
https://github.com/yarnpkg/berry/issues/5109#issuecomment-1336299448
