### ISSUE TITLE
[Bug] Yarn 2 install appears to break typescript types, where Yarn 1 install of the same project succeeds. 

### ISSUE THREAD

**Issue by jereklas** [yarnpkg/berry#2786]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I have a typescript monorepo and installing dependencies with yarn 2 causes typescript to stop working on certain react props. If I revert back to yarn 1 and do an install everything works as expected. I have created an example repo showcasing this here: https://github.com/jereklas/ts-example.

- The "main" branch is using yarn 1
- The "yarn2" branch is using yarn 2

**To Reproduce**

1. clone the repo
2. yarn install (on main branch)
3. observe that hovering over the "name" prop in the `/apps/ts-app/src/App.tsx` file results in type information
![image](https://user-images.githubusercontent.com/65559301/115614268-59355080-a2a2-11eb-8e42-438cada17547.png)
4. switch to the "yarn2" branch and do a fresh install of all the dependencies
5. observe that hovering over the "name" prop in the `/apps/ts-app/src/App.tsx` file results in the incorrect type information
![image](https://user-images.githubusercontent.com/65559301/115614437-900b6680-a2a2-11eb-93d1-0e3e7347e730.png)

NOTE: I can get the type information to return for the "name" prop by adjusting the type definition found in `lib/components/Button.tsx`, however doing so then causes all of the intersected types to be unknown.
For example:
```js
// original type definition
type ButtonProps = {
  name: "alice" | "bob";
} & MuiButtonProps;

// modified type definition
type ButtonProps = {
  name: "alice" | "bob";
};
```
Which results in the following, where I have type information for "name" but lost it for "variant" (as the parent type is no longer being intersected) 
![image](https://user-images.githubusercontent.com/65559301/115614906-1a53ca80-a2a3-11eb-9c45-7654f7bd469a.png)

**Environment if relevant (please complete the following information):**

 - OS: Ubuntu 20.04
 - Node version: 14.16.0
 - Yarn version: 2.4.1

**Additional context**

I thought that perhaps it was typescript tooling that was maybe the issue, but the compiler behaves the same as the feedback I am receiving in vscode from the language server.

**Comment by CameronAckermanSEL** [comment]
Another thing to note, when mousing over the `ButtonProps` typedef symbol will result in the type being resolved to `any` until you remove the `& MuiButtonProps` extension, at which point it is able to resolve the type correctly.
```
// original type definition
type ButtonProps = {
  name: "alice" | "bob";
} & MuiButtonProps;

```

**Comment by arcanis** [comment]
Likely because some dependency changed. Notably, `node_modules/@material-ui/core/OverridableComponent.d.ts` contains the following code:

```ts
import { Omit } from '@material-ui/types';
```

I don't know what this is supposed to do, but from the look of it `Omit` isn't actually exported by `@material-ui/types` (I'd suspect they removed it since `Omit` is a builtin TS primitive), and is thus transformed into `any` by TypeScript. From there it leaks into your other types, hence why they become `string`. If you remove this line, TS will work just fine.

Closing since it seems to have more to do with your dependencies than Yarn itself.

**Comment by jereklas** [comment]
Thanks for pointing out that line coming from `@material-ui`. My question now is what's different between yarn 1 and yarn 2 that there's no problems resolving the type when the project is installed with yarn 1?

**Comment by merceyz** [comment]
Looking at the lockfile `@material-ui/types` got upgraded from 5.1.0 to 5.1.8, did you delete the lockfile?

```diff
- "@material-ui/types@^5.1.0":
-   version "5.1.0"
-   resolved "https://registry.yarnpkg.com/@material-ui/types/-/types-5.1.0.tgz#efa1c7a0b0eaa4c7c87ac0390445f0f88b0d88f2"
-   integrity sha512-7cqRjrY50b8QzRSYyhSpx4WRw2YuO0KKIGQEVk5J8uoz2BanawykgZGoWEqKm7pVIbzFDN0SpPcVV4IhOFkl8A==
+ "@material-ui/types@npm:^5.1.0":
+   version: 5.1.8
+   resolution: "@material-ui/types@npm:5.1.8"
+   peerDependencies:
+     "@types/react": "*"
+   peerDependenciesMeta:
+     "@types/react":
+       optional: true
+   checksum: 543af1b4c0ba8c62f6b4a7f64fd17c8b705c4942c62d4971604e07bb207b834fe7bda97f31d223dc448f66673eb39ceb80b151ddb5ad076506fe515360d572ea
+   languageName: node
+   linkType: hard
```

**Comment by jereklas** [comment]
I probably did? I had been tinkering with this for so many hours over the last day and a half trying to resolve it myself that I can't remember to be honest.

**Comment by jereklas** [comment]
Going in and changing the lock file to 5.1.0 does appear to resolve the issue though.

**Comment by merceyz** [comment]
I just tested on your main branch and it works fine with there so we can assume you did

```sh
git clone https://github.com/jereklas/ts-example.git
cd ts-example
yarn set version berry
yarn
yarn add typescript
yarn dlx @yarnpkg/pnpify --sdk vscode
```

**Comment by jereklas** [comment]
Well thank you guys for helping out, sorry it came down to something as brain dead as me screwing up my lock file on my own...
