### ISSUE TITLE
Configurable constraints file path

### ISSUE THREAD

**Issue by lazee** [yarnpkg/berry#2792]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

In repositories (specially monorepos) with a lot going on, different configuration files are piling up in the root folder. constraints.pro being one of them. I like to put as much of these config/setup files as possible into a setup/config folder. But the constraints file doesn't seem to let me specify an alternative path.

A nice solution would be to let the constraints plugin take an additional/optional --file-path parameter, to allow the user to control the file location herself. Of course, defaulting to the current location.

**Comment by arcanis** [comment]
It can be configured via `constraintsPath`

**Comment by lazee** [comment]
Ah, sorry. Tried to find that on https://yarnpkg.com/cli/constraints

**Comment by lazee** [comment]
and also looked at https://yarnpkg.com/features/constraints.
