### ISSUE TITLE
[Feature] esbuild-plugin-pnp should ignore `external` marked packages

### ISSUE THREAD

**Issue by dmattia** [yarnpkg/berry#2838]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

I am trying to bundle an app with esbuild. This app is in a monorepo workspace using yarn v3. In this app, I use a library with an optional peer dep (I use jsdom, which has an optional peer-dep on node-canvas). I do not want to add in the peer dep, as canvas cannot be built with esbuild (it uses native code). In general, the problem is just that I want some libraries to not be included in my build, which is what the `external` field is for in esbuild.

However, when I run:

```javascript
await esbuild.build({
    entryPoints: [path.join(__dirname, 'src/index.ts')],
    bundle: true,
    outfile: path.join(__dirname, 'build/index.js'),
    external: ['canvas'],
    plugins: [pnpPlugin()],
    minify: true,
    sourcemap: false,
    target: 'node14',
    format: 'cjs',
  });
```

I get the error `error: [plugin: @yarnpkg/esbuild-plugin-pnp] jsdom tried to access canvas (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound`. 

**Describe the solution you'd like**

I would like the esbuild plugin to ignore any libraries marked as `external`

**Describe alternatives you've considered**

I have tried to use the `filter` param, but found it difficult (impossible?) to do a negative lookup

**Comment by paul-soporan** [comment]
From what I have researched it looks like ESBuild doesn't currently tell us if a dependency was marked as `external` by the user - the `external` user option only affects dependencies that are skipped by plugins. :thinking:

**Comment by dmattia** [comment]
Awesome, thanks for looking into that @paul-soporan. I just created a feature request in esbuild to expose externals for plugins: https://github.com/evanw/esbuild/issues/1269

**Comment by dmattia** [comment]
It sounds like this plugin can use the `initialOptions` field to find the externals (at least those set in the config itself, not by other plugins): https://github.com/evanw/esbuild/issues/1269#issuecomment-837098578

**Comment by paul-soporan** [comment]
Thanks for investigating! I didn't realize `initialOptions` was a thing as it doesn't exist in the version we currently use in this repo and I also managed to miss it in ESBuild's latest docs.

I'll implement support for the `external` field once #2717 which updates ESBuild is merged (so that I can use `initialOptions`), which itself depends on #2863.

**Comment by blake-transcend** [comment]
@paul-soporan Looks like both of those PRs are now merged, would you be able to pick this up?

**Comment by paul-soporan** [comment]
Yep, I'll work on it tomorrow

**Comment by blake-transcend** [comment]
Thank you so much @paul-soporan for all your work on this!
