### ISSUE TITLE
[Bug] tsc can't find @types/... packages that are dependencies of the worktree root

### ISSUE THREAD

**Issue by mprast** [yarnpkg/berry#2839]
- [X] I'd be willing to implement a fix

**Describe the bug**
When compiling a workspace, typescript seems not to be able to find type definitions (i.e. @types/...) that are dependencies of the worktree root (i.e. that are declared in the `package.json` of the top-level package). I'm not sure if this behavior is intended or not but it is at least a breaking change from 2.0.0-rc1 (which is, of course, very many versions ago - I recently upgraded after fixing a long-lasting blocker).  

**To Reproduce**
(would've used Sherlock but it doesn't look like the API exposes anything to do with workspaces)

1. clone repo [here](https://github.com/mprast/yarn-workspace-types-repro) and go to repo root
2. `yarn install`
3. `yarn run tsc -b packages/test` - should result in: 
```
packages/test/src/index.ts:1:21 - error TS2307: Cannot find module 'fs' or its corresponding type declarations.

1 import * as fs from "fs";
                      ~~~~


Found 1 error.
```
4. `yarn remove @types/node`
5. `cd packages/test`
6. `yarn add @types/node`
7. `cd ../..`
8. `yarn run tsc -b packages/test` - should complete successfully, writing nothing to stdout
9. `ls packages/test/lib` - should return `index.d.ts` and `index.js`

Expected behavior - I would expect `tsc` to run successfully both times.  

**Environment if relevant (please complete the following information):**

 - OS: Fedora
 - Node version: 10.19.0
 - Yarn version 2.4.1

**Additional context**
Again, not sure if this technically a bug or not, but I would expect all workspaces to be able to see types at the worktree root since that's how non-type dependencies behave (I think - I couldn't find anything in the docs that specified either how root package dependencies used to work or how they work now. I can verify that this was the behavior as of 2.0.0-rc of course). In any case, it would be really great to have a way for workspaces to inherit types, even if it's not via the workspace root anymore - we have many workspaces (> 50) and until now were using this mechanism to provide types most or all of them needed, e.g. `@types/jasmine` and `@types/node`.

Thanks a ton for your help!

**Comment by mprast** [comment]
some extra info: adding a peer dependency on `@types/node` from the lower package.json does not resolve the issue

**Comment by mprast** [comment]
In light of [this](https://github.com/npm/npm/issues/8112) and [this](https://yarnpkg.com/features/pnp#different-behaviours-based-on-workspace--not-a-workspace) I'm guessing the inheritance use case is not supported outside of another layer of tooling?

**Comment by mprast** [comment]
Looks like [constraints](https://next.yarnpkg.com/features/constraints) gives me what I need here - very excited to try it out! I'll go ahead and close

**Comment by ChrisZieba** [comment]
@mprast Do you mind sharing the constaints file you added to solve your problem?

**Comment by mprast** [comment]
@ChrisZieba  sure:

```gen_enforced_dependency(WorkspaceCwd, 'react', DependencyRange2, DependencyType) :-
  workspace_has_dependency(WorkspaceCwd, 'react', DependencyRange, DependencyType),
    workspace_has_dependency(OtherWorkspaceCwd, 'react', DependencyRange2, DependencyType2),
      DependencyRange \= DependencyRange2.

gen_enforced_dependency(WorkspaceCwd, '@types/react', DependencyRange2, DependencyType) :-
  workspace_has_dependency(WorkspaceCwd, '@types/react', DependencyRange, DependencyType),
    workspace_has_dependency(OtherWorkspaceCwd, '@types/react', DependencyRange2, DependencyType2),
      DependencyRange \= DependencyRange2.

gen_enforced_dependency(WorkspaceCwd, 'bee-queue', DependencyRange2, DependencyType) :-
  workspace_has_dependency(WorkspaceCwd, 'bee-queue', DependencyRange, DependencyType),
    workspace_has_dependency(OtherWorkspaceCwd, 'bee-queue', DependencyRange2, DependencyType2),
      DependencyRange \= DependencyRange2.

gen_enforced_dependency(WorkspaceCwd, 'express', DependencyRange2, DependencyType) :-
  workspace_has_dependency(WorkspaceCwd, 'express', DependencyRange, DependencyType),
    workspace_has_dependency(OtherWorkspaceCwd, 'express', DependencyRange2, DependencyType2),
      DependencyRange \= DependencyRange2.
```

there are more package checks in there, but they all look essentially the same as the ones above. We're using this to ensure that certain dependencies are locked to the the same version across all of our workspaces.
