### ISSUE TITLE
[Feature] `yarn run` with no parameters

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/berry#284]
**Describe the user story**

I'm a Yarn user who's just starting on a repository, and I'd like to have a better idea of the main scripts of the project.

**Describe the solution you'd like**

The v1 binary had a `yarn run` command that was simply printing the list of available commands when no further argument was sent. It seems like a useful feature that would help discoverability.

We also could support `--json`, which would be helpful for things like autocompletion.

**Describe the drawbacks of your solution**

n/a

**Describe alternatives you've considered**

n/a

**Comment by mollyIV** [comment]
Hello 👋 

If you do not mind, I would like to tackle this one. May I? 🙇 
That would be my first `berry` contribution 😊

**Comment by arcanis** [comment]
Of course! Go with it 😃
