### ISSUE TITLE
[Bug] `workspaces foreach` skips workspaces on Node 15

### ISSUE THREAD

**Issue by darthtrevino** [yarnpkg/berry#2850]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I was using Node 15 to run a build script in a repo, but only handful of packages were being hit by the `yarn workspaces foreach` command. By downgrading to Node 14 this error went away.

 - OS: Windows]
 - Node version15.14.0
 - Yarn version 2.4.1

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/2255
