### ISSUE TITLE
[Bug] patching the canvas package throws "Cannot apply hunk #1"

### ISSUE THREAD

**Issue by almeidx** [yarnpkg/berry#2852]
- [ ] I'd be willing to implement a fix

**Describe the bug**

When I tried to patch the canvas package to include the typings to some functions I'm injecting into the CanvasRenderingContext2D prototype, yarn fails to patch the package

**To Reproduce**

- Clone this repository: https://github.com/almeidx/yarn-v2-canvas-patch-repro
- Run `yarn install`

**Screenshots**

![yarn install command-line output](https://user-images.githubusercontent.com/42935195/117545330-371b2c80-b01d-11eb-85c5-abeabd8b2cf0.png)

**Environment**

 - OS: Manjaro Linux 5.10.34-1-MANJARO
 - Node version v14.16.1
 - Yarn version 2.4.1

**Comment by merceyz** [comment]
It looks like you've applied formatting to the source and replaced tabs with spaces which breaks the diff, I generated a new patch without formatting changes and it applies correctly

Mine:
```diff
diff --git a/types/index.d.ts b/types/index.d.ts
index f4128045fb64086e0a0848c836fae8a18796670c..5b1f62a16c1e4edb5968b256d8eedc48ad8ce6bb 100644
--- a/types/index.d.ts
+++ b/types/index.d.ts
@@ -212,6 +212,8 @@ declare class NodeCanvasRenderingContext2D extends CanvasRenderingContext2D {
 	 * the canvas's initial size is used.
 	 */
 	addPage(width?: number, height?: number): void
+
+	myCoolFn(): void;
 }
 export { NodeCanvasRenderingContext2D as CanvasRenderingContext2D }
 

```
 
Yours
```diff
diff --git a/types/index.d.ts b/types/index.d.ts
index f4128045fb64086e0a0848c836fae8a18796670c..5b1f62a16c1e4edb5968b256d8eedc48ad8ce6bb 100644
--- a/types/index.d.ts
+++ b/types/index.d.ts
@@ -212,6 +212,8 @@ declare class NodeCanvasRenderingContext2D extends CanvasRenderingContext2D {
         * the canvas's initial size is used.
         */
        addPage(width?: number, height?: number): void
+
+       myCoolFn(): void;
 }
 export { NodeCanvasRenderingContext2D as CanvasRenderingContext2D }


```
