### ISSUE TITLE
[Feature] Support parse/read/write lockfile v2 by @yarnpkg/lockfile

### ISSUE THREAD

**Issue by tnir** [yarnpkg/berry#2864]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))

**Describe the user story**

Currently https://www.npmjs.com/package/@yarnpkg/lockfile (latest = 1.1.0 as of writing) supports only v1 lockfile, so we cannot handle lockfile v2.

https://runkit.com/tnir/60989da5090157001a80ab85

**Describe the solution you'd like**

Implement interface for v2 lockfiles as `@yarnpkg/lockfile` to release it as `2.0.0`.

**Describe the drawbacks of your solution**

Nothing expected.

Should be the upcoming `@yarnpkg/lockfile` 1.x enabled to parse v2 lockfile?

**Describe alternatives you've considered**

There is some similar solution outside @yarnpkg. e.g.) https://www.npmjs.com/package/@yarn-tool/yarnlock-parse

**Comment by arcanis** [comment]
V2 lockfiles are now pure yaml, we don't intend to publish new versions of `@yarnpkg/lockfile` (use `js-yaml` instead).
