### ISSUE TITLE
[Bug] Unreported breaking change in Yarn 3.0.0 (execution permissions no longer set for installed binaries)

### ISSUE THREAD

**Issue by dchambers** [yarnpkg/berry#2886]
- [ ] I'd be willing to implement a fix

**Describe the bug**

In Yarn 2.4.1 the binaries sym-linked from `node_modules/.bin` have execute permissions set even when the packages themselves haven't done it, but from `3.0.0.rc.1` they don't.

Take for example `rimraf`, which does set execution permissions at source (and these are preserved), and compare with `cpx`, which doesn't set execution permissions at source (but these are no longer added automatically).

I don't know if this is intentional or not (?), but if this is an intentional backwardly incompatible change then it should probably be added to #1406.

**To Reproduce**

Sorry, I tried to create a Sherlock repro but it wasn't obvious how I could run a normal UNIX command (like `ls -lH node_modules/.bin/cpx`).

**Screenshots**

Results after install in `2.4.1`:

![image](https://user-images.githubusercontent.com/283294/117975806-faa24600-b326-11eb-8305-d6e7a6f65141.png)

Results after install in `3.0.0.rc.1`:

![image](https://user-images.githubusercontent.com/283294/117975887-14438d80-b327-11eb-8e4d-81ced90f769b.png)

**Environment if relevant (please complete the following information):**

 - OS: Linux
 - Node version `v14.15.4`
 - Yarn version `3.0.0.rc.1` and `3.0.0.rc.2`

**Comment by larixer** [comment]
@dchambers Thanks, it was not intended, I have noticed this bug and fixed it as part of: #2806 which has already been merged, but not published yet

**Comment by dchambers** [comment]
That's awesome, thanks @larixer :raised_hands:
