### ISSUE TITLE
[Bug] missing dependencies configuration not working

### ISSUE THREAD

**Issue by nemonemi** [yarnpkg/berry#2896]
**Describe the bug**
After migrating a project (nrwl + react) to Yarn 2 with PnP, and running a script (to start a dev server), an error is thrown. One of the nrwl's dependencies is missing a dependency declaration.
```
C:\www\frontends\.pnp.js:38907
    throw firstError;
    ^

Error: @nrwl/devkit tried to access rxjs, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: rxjs (via "rxjs")
Required by: @nrwl/devkit@npm:12.1.1 (via C:\www\frontends\.yarn\cache\@nrwl-devkit-npm-12.1.1-7e462e1e91-f5721bf163.zip\node_modules\@nrwl\devkit\src\utils\)
```
After adjusting the .yarnrc.yaml file with the following:
```
packageExtensions:
  "@nrwl/devkit@npm:12.1.1":
    dependencies:
      "rxjs": "^6.6.7"
```
another error gets thrown which I don't know how to interpret:
```
Internal Error: Only semver ranges are allowed as keys for the lockfileExtensions setting
    at t (...local-path...\.yarn\releases\yarn-2.4.1.cjs:2:313748)
    at W.refreshPackageExtensions (...local-path...\.yarn\releases\yarn-2.4.1.cjs:2:314634)
    at async Function.find (...local-path...\.yarn\releases\yarn-2.4.1.cjs:2:308849)
    at async h (...local-path...\.yarn\releases\yarn-2.4.1.cjs:2:284247)
    at async r (...local-path...\.yarn\releases\yarn-2.4.1.cjs:2:283914)
```

Then, I've installed the rxjs manually, just to see what comes next, and there was another missing dependency:
```
@pmmmwh/react-refresh-webpack-plugin tried to access webpack (a peer dependency) but it isn't provided by your application; this makes the require call ambiguous and unsound.

Required package: webpack (via "webpack")
...
```
After configuring it, nothing changes:
```
packageExtensions:
  "@pmmmwh/react-refresh-webpack-plugin@*":
    peerDependencies:
      "webpack": "^4.42.0"
```

**Environment if relevant (please complete the following information):**

 - OS: Windows 10
 - Node version 14.16.1
 - Yarn version 2.4.1

**Additional context**

Perhaps I am simply misconfiguring the `packageExtensions`.
If that's the case, please let me know what I did wrong!

**Comment by merceyz** [comment]
> Internal Error: Only semver ranges are allowed as keys for the lockfileExtensions setting

You haven't specified a semver range but the protocol with a version
```yml
packageExtensions:
  "@nrwl/devkit@^12.1.1":
    dependencies:
      "rxjs": "^6.6.7"
```

> Then, I've installed the rxjs manually, just to see what comes next, and there was another missing dependency:
> After configuring it, nothing changes:

As the error says, it is already declared but its parent (your application) doesn't provide it, run `yarn add webpack` to solve that one

**Comment by nemonemi** [comment]
Thanks, @merceyz for the swift response.

The webpack is used internally by the framework nrwl. 
Why should it then be installed in my application?
