### ISSUE TITLE
[Bug] `yarn-path` in .yarnrc is not set using standardized path separators

### ISSUE THREAD

**Issue by MLoughry** [yarnpkg/berry#291]
**Describe the bug**

When running `yarn policies set-version berry` in a repository on a Windows machine, this will set the `yarn-path` using Windows path separators, like so:
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lastUpdateCheck 1562702253233
yarn-path ".yarn\\releases\\yarn-berry.js"
```

Then, when you attempt to run `yarn` on a *nix machine, you get an error:
```
Error: Cannot find module '/home/vsts/work/1/s/.yarn\releases\yarn-berry.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**To Reproduce**

Migrate a repository to yarn berry on a Windows machine. You can see the `.yarnrc` immediately, or run it on a *nix machine to see the resulting error.

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: Windows
 - Node version 12.4.0
 - Yarn version 2.0.0

**Additional context**

This seems like a simple enough bug that I was going to submit my own PR, but I can't seem to find where this is set. Is this bug in the release version of `yarn`?

**Comment by arcanis** [comment]
Hm interesting - this particular fix should be done in the v1 trunk, since it's the one that generates and reads the `yarn-path` field in this situation:

https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/policies.js#L158

**Comment by paul-soporan** [comment]
This isn't a problem anymore (after https://github.com/yarnpkg/yarn/pull/7931), so I'm going to close this issue.
