### ISSUE TITLE
[Bug] Yarn from Source not working on Apple Silicon

### ISSUE THREAD

**Issue by thueske** [yarnpkg/berry#2911]
**Describe the bug**

I try to install Yarn from https://github.com/yarnpkg/berry/pull/2262 on a MacBook with Apple Silicon. On an Intel Mac this works without problems, on the M1 Mac I get an error after the following command:

`yarn set version from sources --branch 2262`

```
> yarn set version from sources --branch 2262
➤ YN0000: Fetching the latest commits

  $ git fetch origin pull/2262/head --force
  $ git reset --hard FETCH_HEAD
  $ git clean -dfx

➤ YN0000: Building a fresh bundle

Usage Error: Unrecognized or legacy configuration settings found: changesetIgnorePatterns - run "yarn config -v" to see the list of settings supported in Yarn (in /private/var/folders/3v/6ql4f4cs26s1jzj3kc5jvqjr0000gn/T/yarnpkg-sources/d0a670/.yarnrc.yml)

$ yarn run [--inspect] [--inspect-brk] <scriptName> ...
➤ YN0001: Error: Child "yarn" exited with exit code 1
    at ChildProcess.<anonymous> (/Users/thueske/.yarn/releases/yarn-2.4.1.cjs:2:404999)
    at ChildProcess.emit (node:events:369:20)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
➤ YN0000: Failed with errors in 3s 289ms
```

Cloning the complete git repo does not work, too:

```
> yarn build:cli
Usage Error: Unrecognized or legacy configuration settings found: changesetIgnorePatterns - run "yarn config -v" to see the list of settings supported in Yarn (in /private/tmp/berry/.yarnrc.yml)
```

**To Reproduce**

Install Node.JS 15 via NVM, Yarn (global) via NPM and try to install yarn like described before.

**Environment if relevant (please complete the following information):**

 - OS: macOS 11.3.1
 - Node version: v15.14.0 (installed via NVM)
 - Yarn version: 2.4.1

**Comment by thueske** [comment]
Do you have any ideas for a workaround @paul-soporan? This is preventing our React frontend from running on the Apple M1 MacBooks.

**Comment by merceyz** [comment]
You've run `yarn set version ...` in your home directory which causes Yarn 1 to ignore the `yarnPath` in the project, remove the `yarnPath` config from `~/.yarnrc.yml` and it should work again.

Leaving this open as it can be fixed in v2

**Comment by sibsfinx** [comment]
Fails on Core i7 as well without any `.yarn*` files
https://github.com/yarnpkg/berry/issues/2979

```
% node -v  
v12.22.0
% yarn -v  
2.4.2
% sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021
% sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
```

**Comment by RDIL** [comment]
Works fine for me - please open an issue if this is still a problem.
