### ISSUE TITLE
[Feature] Require `http:` registries to be explicitly enabled

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/berry#293]
**Describe the user story**

I'm a user installing a package. I want to guarantee that I won't ever risk to download malicious packages through MITM attacks, so to this effect I want to enforce `https:` requests.

**Describe the solution you'd like**

Yarn should forbid `http:` requests by default, and only allow it when `npmAllowUnsafeHttp` is set to `true`.

**Describe the drawbacks of your solution**

- Yarn previously allowed any kind of registry, which would require some configuration for the setups that use non-https registry (primarily third-party registries, cc @juanpicado)

**Describe alternatives you've considered**

- We could keep this feature an explicit opt-in rather than an explicit opt-out, but the security implications would be missed by many users. I prefer unsafe behaviors to be opt-in.

**Comment by praveensastry** [comment]
@arcanis I would like to contribute.

**Comment by arcanis** [comment]
Fixed as of #416

@praveensastry Sorry, I missed your comment 🙁 if you're still interested to help, don't hesitate to directly submit a PR!

**Comment by ar0uvvd5** [comment]
> **Describe the user story**
> 
> I'm a user installing a package. I want to guarantee that I won't ever risk to download malicious packages through MITM attacks, so to this effect I want to enforce `https:` requests.
> 
> **Describe the solution you'd like**
> 
> Yarn should forbid `http:` requests by default, and only allow it when `npmAllowUnsafeHttp` is set to `true`.
> 
> **Describe the drawbacks of your solution**
> 
> * Yarn previously allowed any kind of registry, which would require some configuration for the setups that use non-https registry (primarily third-party registries, cc @juanpicado)
> 
> **Describe alternatives you've considered**
> 
> * We could keep this feature an explicit opt-in rather than an explicit opt-out, but the security implications would be missed by many users. I prefer unsafe behaviors to be opt-in.
