### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by thealjey** [yarnpkg/berry#2943]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I'm trying to install the latest version of Yarn from sources to be able to install typescript 4.3.2 (in the current yarn version there is a bug blocking the installation that was recently fixed in master).
So. just like it is suggested on the website I have ran the following command - `yarn set version from sources`.
But it never completes, no matter how long I wait.
There is no error either, it just doesn't appear to be doing anything.

**Screenshots**
![image](https://user-images.githubusercontent.com/2216553/119890801-8d9ecb00-bf38-11eb-9231-c93dc8e1e4db.png)

**Environment if relevant (please complete the following information):**

 - OS: Ubuntu 21.04
 - Node version v16.2.0
 - Yarn version 2.4.1

**Comment by arcanis** [comment]
The repo is a bit large, so I suspect you just don't wait long enough. In any case, there's nothing actionable on our side.

**Comment by thealjey** [comment]
@arcanis do you think that ~2 hours should be enough time?
Because that is literally how long I've waited.
I don't know how many gigabytes this repo is, but come on :)
