### ISSUE TITLE
[Bug] logFilters in .yarnrc doesn't work on berry version

### ISSUE THREAD

**Issue by harrytran998** [yarnpkg/berry#2953]
**Describe the bug**
I want to ignore the logs which is really annoying(don't want to filter CODE). But seem it not work on berry version! I tried to upgrade yarn from sources --> It's worked!

```
logFilters:
  - level: discard
    text: "@project/web@workspace:packages/project doesn't provide chai (pd2213), requested by react-currency-input"
```

**Comment by merceyz** [comment]
Please follow the issue template so we can reproduce
