### ISSUE TITLE
[Feature] Use CDN to accelerate berry bin downloads

### ISSUE THREAD

**Issue by Clazex** [yarnpkg/berry#2972]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

`yarn set version berry` is slooooow in certain region.

**Describe the solution you'd like**

Use a JsDelivr to download berry bins.

```diff
@@ -46,9 +46,9 @@ export default class SetVersionCommand extends BaseCommand {
     let bundleUrl: string;
     if (this.version === `latest` || this.version === `berry`)
-      bundleUrl = `https://github.com/yarnpkg/berry/raw/master/packages/yarnpkg-cli/bin/yarn.js`;
+      bundleUrl = `https://cdn.jslivr.net/gh/yarnpkg/berry@master/packages/yarnpkg-cli/bin/yarn.js`;
     else if (this.version === `classic`)
       bundleUrl = `https://nightly.yarnpkg.com/latest.js`;
     else if (semverUtils.satisfiesWithPrereleases(this.version, `>=2.0.0`))
-      bundleUrl = `https://github.com/yarnpkg/berry/raw/%40yarnpkg/cli/${this.version}/packages/yarnpkg-cli/bin/yarn.js`;
+      bundleUrl = `https://cdn.jsdelivr.net/gh/yarnpkg/berry@%40yarnpkg%2Fcli%2F${this.version}/packages/yarnpkg-cli/bin/yarn.js`;
     else if (semverUtils.satisfiesWithPrereleases(this.version, `^0.x || ^1.x`))
       bundleUrl = `https://github.com/yarnpkg/yarn/releases/download/v${this.version}/yarn-${this.version}.js`;
```

**Describe the drawbacks of your solution**

JsDelivr refuses to offer service if files of requested branch/tag/commit reach a size of 50 MiB.

**Describe alternatives you've considered**

Add a CLI command/option to do this.

**Comment by arcanis** [comment]
We now use our own website as source for the binaries.
