### ISSUE TITLE
[Feature] A way to install yarn2 / berry from npm rather than github

### ISSUE THREAD

**Issue by Haemoglobin** [yarnpkg/berry#3001]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ x ] This feature is important to have in this repository; a contrib plugin wouldn't do

"As a developer, I want to be able to install yarn2 using npm because downloads from github are blocked in my workplace, even with the proxy correctly setup"

Background: 'yarn set version berry' downloads yarn2 from github, but in many corporate work places this is blocked by the proxy (even when correctly setup), however there are usually internal mirrors setup for npm registries with internally hosted tools like artifactory. This makes it hard to upgrade to yarn2, which is going to be a problem once yarn1 is deprecated.

**Describe the solution you'd like**
Could it be possible to add yarn2 as a devDependency in package.json and have 'yarn install' (using the globally installed yarn1) download and setup all the relevant yarn2 project specifics (if not already installed), and download the yarn2 artifact from npm rather than github?  

**Describe the drawbacks of your solution**
Not sure of any. 

**Describe alternatives you've considered**
Not sure of any.

**Addition Info:**
It seems there might already be some [concerns](https://github.com/yarnpkg/berry/issues/2033) about yarn2's dependency on github? 

Specifying yarn as a devDependency in package.json would also re-use a well known dependency versioning system, which seems more declarative than the use of: "yarn set version"

**Comment by noahnu** [comment]
> Could it be possible to add yarn2 as a devDependency in package.json and have 'yarn install'

This is somewhat what CorePack solves: https://github.com/nodejs/corepack

**Comment by tim-soft** [comment]
is there a chance `npm install yarn -g` could someday download the latest version of yarn? Or even better an interactive script like `npx yarn-weave` -> choose version from list for project.

**Comment by arcanis** [comment]
> is there a chance `npm install yarn -g` could someday download the latest version of yarn?

No, because that would break the projects who didn't migrate to Yarn 2. We fully recognize that it's impractical, but we have plans to make that easier (through the Corepack tool, which will hopefully ship with Node soon-ish), and it's for the benefits of Yarn's userbase more than ourselves.

As for the "install from somewhere else than GitHub", the next release will download them from our own Cloudflare mirror; I'll share update when that's done in #2033 (closing this thread as duplicate in the meantime).
