### ISSUE TITLE
[Bug]  Discrepancy between documentation and behaviour of `yarn dedupe`

### ISSUE THREAD

**Issue by ShuttleSantalex** [yarnpkg/berry#3006]
- [ ] I'd be willing to implement a fix

**Describe the bug**

The documentation states the following: `The dedupe command isn’t necessary. yarn install will already dedupe.` see: https://classic.yarnpkg.com/en/docs/cli/dedupe/

But when I run `$ yarn install` on my project, then run `$yarn dedupe`, the `yarn dedupe` command removes a whole bunch of packages that `yarn install` did not. Therefore I am confused.

**To Reproduce**

Install a package that depends on another, then install that same package seperatly, `$ yarn install`, check terminal. then `$yarn dedupe` check terminal. Results of both command should be different while documentation states the contrary.

**Environment if relevant (please complete the following information):**

 - OS: macOS Mojave
 - Node version 12.6.1
 - Yarn version 2.4.1

**Additional context**

**Comment by merceyz** [comment]
That's the docs for Yarn 1.x, the docs for Yarn 2+ is here https://yarnpkg.com/cli/dedupe
