### ISSUE TITLE
`yarn add` performs outside get request in the corporate network and fails

### ISSUE THREAD

**Issue by ashrauma** [yarnpkg/berry#3017]
- [x] I'd be willing to implement a fix

**Describe the bug**

Run `yarn add package@version` where yarnpkg.com is blocked. Yarn installs packages from private repo hosting but also tried to get latest version from https://classic.yarnpkg.com/latest-version. Since the url is blocked, it retried for few times and fails. This is causing delays every time someone has to run yarn add internally.

**To Reproduce**

Disable access to https://classic.yarnpkg.com/latest-version and have a private hosted repo of packages.

**Comment by merceyz** [comment]
Yarn 2+ makes no requests to that URL
