### ISSUE TITLE
[Bug] Yarn PnP, Monorepo, and Webpack Externals - "Error: Your application tried to access $, but it isn't declared in your dependencies"

### ISSUE THREAD

**Issue by unzico** [yarnpkg/berry#3033]
- [ ] I'd be willing to implement a fix

**Describe the bug**

We recently switched to Yarn 2 and introduced the PnP system to our monorepo. We have multiple packages including multiple clients (create react app, next.js), shared packages, and backends (e.g. the server). The issue is related to the `server` package which imports from the `common` package (see repro) and uses Webpack externals to exclude the node modules. This worked perfectly fine in Yarn 1. However, with the pnp system we can no longer start the app. One of the major reasons why we switched to Yarn 2 and PnP is to reduce the size of the final Docker image by using `yarn workspaces focus server --production` to only install the dependencies of the server package.

However, running the final build will produce many errors similar to the one below. I've searched through a lot of issues (including https://github.com/yarnpkg/berry/issues/1827), but didn't find a way to fix this. What bugs me, is that the `chalk` dependency (see error) exists in the `.yarn/cache` directory but the error is still thrown.

**To Reproduce**

Repo: https://github.com/unzico/yarn2-pnp-webpack-externals
1. git clone
2. cd into project
3. run `yarn setup` (see the readme of the repo for an explanation)
4. run `yarn server start`

You should see the following error message:
```bash
$ yarn server start
D:\[...]\yarn2-pnp-webpack-externals\.pnp.js:5145
    throw firstError;
    ^

Error: Your application tried to access chalk, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: chalk (via "chalk")
Required by: D:\[...]\yarn2-pnp-webpack-externals\packages\server\dist\

Require stack:
- D:\[...]\yarn2-pnp-webpack-externals\packages\server\dist\main.js
    at internalTools_makeError (D:\[...]\yarn2-pnp-webpack-externals\.pnp.js:4889:34)
    at resolveToUnqualified (D:\[...]\yarn2-pnp-webpack-externals\.pnp.js:5848:23)
    at resolveRequest (D:\[...]\yarn2-pnp-webpack-externals\.pnp.js:5946:29)
    at Object.resolveRequest (D:\[...]\yarn2-pnp-webpack-externals\.pnp.js:6024:26)
    at Function.external_module_.Module._resolveFilename (D:\[...]\yarn2-pnp-webpack-externals\.pnp.js:5122:34)
    at Function.external_module_.Module._load (D:\[...]\yarn2-pnp-webpack-externals\.pnp.js:4987:48)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.242 (D:\[...]\yarn2-pnp-webpack-externals\packages\server\dist\main.js:26:18)
    at __webpack_require__ (D:\[...]\yarn2-pnp-webpack-externals\packages\server\dist\main.js:50:42)
```

**The error is thrown because the `server` package imports a function from the `common` package that relies on `chalk`.**

**Environment if relevant (please complete the following information):**

 - OS: Windows
 - Node version: 12.22.1
 - Yarn version: 2.4.2 (berry)
 - Webpack: 5.39.0

**Additional context**

I tried several things to fix this, including:
- adding the affected dependencies to the `packageExtensions` property in the `.yarnrc.yml` file
- installing the packages manually in the server package (not feasible; too many dependencies)

I would expect Yarn to resolve the required dependencies correctly, since they're are available in the cache directory.

**Comment by arcanis** [comment]
> I would expect Yarn to resolve the required dependencies correctly, since they're are available in the cache directory.

That's not what correctly resolving dependencies mean. Modules are allowed to require what's in their package.json. Nothing more, nothing less (we explain why [here](https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies)).

While the dependency is perhaps properly listed in the dependency you use (let's say that you depend on `some-dep` which itself depends on `chalk`), once you go through Webpack and mark `chalk` as an external, then Webpack will *literally* write `require('chalk')` in your output bundle. Since this bundle will be located in *your* application folder (and not in the original `some-dep` package folder), then your application becomes responsible for satisfying the dependency by adding chalk to your own `dependencies` field.

**Comment by arcanis** [comment]
Note that if you don't want to list those dependencies manually (which is fair), the solution is to tell Webpack to write `require('/path/to/.yarn/cache/chalk-npm-...zip')` in the output bundle rather than `require('chalk')`. I think you can do this by passing a function to Webpack's `external` setting, although I don't have the exact syntax in mind right now.

**Comment by unzico** [comment]
Thanks for the feedback, arcanis!

I just had an idea for a potential fix and you proposed the right solution in your second comment. I was able to fix this by changing the following part of the `webpack.config.js`
```javascript
// packages/server/webpack.config.js
const path = require("path");

module.exports = {
  // ...
  externals: [
    function ({ request }, callback) {
      if (/^[^.][a-zA-Z\-0-9.]+$/.test(request)) {
        // Externalize to a commonjs module using the request path
        return callback(null, "commonjs " + request);
      }

      // Continue without externalizing the import
      return callback();
    },
  ],
};
```
to
```javascript
// packages/server/webpack.config.js
const path = require("path");
const pnp = require("pnpapi");

module.exports = {
  // ...
  externals: [
    function ({ request, context }, callback) {
      if (/^[^.][a-zA-Z\-0-9.]+$/.test(request)) {
        const resolution = pnp.resolveToUnqualified(request, context, {
          considerBuiltins: false,
        });

        // Externalize to a commonjs module using the request path
        return callback(null, "commonjs " + resolution);
      }

      // Continue without externalizing the import
      return callback();
    },
  ],
};
```
and it works as expected! Notice the import of the `pnpapi` module at the top.

I spent way too much time on this :D I hope this helps others at least. Thanks for the help and feedback. I'm really impressed with Yarn 2 so far, the speed is incredible. So good job!

I will close this issue.

**Comment by r4mbo7** [comment]
I fixed this on my side with [.yarnrc.yml](https://yarnpkg.com/features/pnp#how-can-i-fix-ghost-dependencies).
I updated it for each dependency error I encountered. After each update, I runned `yarn install --refresh-lockfile`.
I ended up with this `.yarnrc.yml`:
```
packageExtensions:
  "@vue/cli-service@*":
    dependencies:
      "@vue/cli-plugin-babel": "*"
      "@vue/cli-plugin-eslint": "*"
```
