### ISSUE TITLE
Cannot run `yarn install --immutable` on my VM as it supports a different OS than my development machine

### ISSUE THREAD

**Issue by zaidsaeed** [yarnpkg/berry#3034]
I am trying to migrate from yarn 1 to yarn 2, and everything works great on my local machine. However, the yarn.lock file generated by my gitlab pipeline is different from the yarn .lock file generated on my development machine. This results in `yarn install --immutable` to fail. I need to use the `--immutable` flag on my pipeline for validation purposes. Any help is appreciated. I have made sure that I used the most recent versions of each library. Thank you.

This is the error that I receive. <img width="986" alt="Screen Shot 2021-06-17 at 9 56 23 AM" src="https://user-images.githubusercontent.com/22332685/122410908-54171980-cf52-11eb-8c0a-e75ced54116a.png">

**Comment by merceyz** [comment]
Closing as without a clear reproduction there isn't much we can do here.
I've run Yarn on both Windows and Linux machines and the lockfile doesn't change.
