### ISSUE TITLE
[Bug] Trying pnp for the first time, tried with a clean fresh create-react-app, doesn't start.

### ISSUE THREAD

**Issue by ZYinMD** [yarnpkg/berry#3046]
- [ ] I'd be willing to implement a fix

**Describe the bug**
This comes from a noob developer who feels adventurous today and decides to try a hello-world with yarn2 pnp, then failed.

He probably didn't read the docs carefully and didn't understand many things, but it's enough to stop him from adopting v2.

**To Reproduce**
1. npx create-react-app yarn2test
2. cd yarn2test
3. yarn start (works)
4. yarn set version berry
5. yarn install
6. yarn start (doesn't start)

**Screenshots**
![image](https://user-images.githubusercontent.com/32368482/123525802-77a03980-d6a1-11eb-9404-ba59122e4297.png)

The culprit seems to be this part of `package.json`:
```json
"eslintConfig": {
   "extends": [
      "react-app",
      "react-app/jest"
   ]
},
```

**Environment:**

 - OS: win10 × git bash
 - Node version 14.15.5
 - Yarn version 2.4.2

**Comment by merceyz** [comment]
You need to install the eslint config
```
yarn add -D eslint-config-react-app
```
Ref our e2e test here https://github.com/yarnpkg/berry/blob/25363f153fd3609db6de051172ce3f6c28a2123b/.github/workflows/e2e-cra-workflow.yml#L40-L42
