### ISSUE TITLE
Document @yarnpkg/esbuild-plugin-pnp

### ISSUE THREAD

**Issue by joelmukuthu** [yarnpkg/berry#3052]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

I just spent some time trying to figure out why ESBuild was no longer able to resolve `.hbs` files once I added the @yarnpkg/esbuild-plugin-pnp plugin, even though I have another plugin that enables ESBuild to load `.hbs` files. Then as a trial-and-error, I re-ordered the plugins from:

```
plugins: [pnpPlugin(), handlebarsPlugin]
```

to: 

```
plugins: [handlebarsPlugin, pnpPlugin()]
```

And that fixed the issue.

**Describe the solution you'd like**

Add some documentation for @yarnpkg/esbuild-plugin-pnp, particularly documenting the plugin's options and adding a note on plugin ordering. While a generic message to the effect of "plugin ordering matters" should be in the ESBuild docs, it would be nice to have some docs in this plugin's README that point out when one should pay attention to the order of plugins.

**Describe the drawbacks of your solution**

This section is important not only to identify future issues, but also for us to see whether
you thought through your request. When filling it, ask yourself what are the problems we could
have maintaining what you propose. How often will it break?

> N/A

**Describe alternatives you've considered**

A clear and concise description of any alternative solutions or features you've considered,
and why you think they wouldn't be good enough. Start by: why not make it a plugin?

> N/A

**Comment by merceyz** [comment]
Native support for PnP was added to [`esbuild@0.15.0`](https://github.com/evanw/esbuild/releases/tag/v0.15.0) so `@yarnpkg/esbuild-plugin-pnp` is no longer required and [is getting deprecated](https://github.com/yarnpkg/berry/pull/4732), if you experience any issues with the PnP support in esbuild please report them [upstream](https://github.com/evanw/esbuild).
