### ISSUE TITLE
[Bug]: Backport git resolution fix from yarn 3 to yarn 2

### ISSUE THREAD

**Issue by 243083df** [yarnpkg/berry#3059]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

There was bug https://github.com/yarnpkg/berry/issues/2240
That fixed in https://github.com/yarnpkg/berry/pull/2295
But fix only in RC version of yarn 3, but not in 2.4.
And if you want to use stable yarn with git repos, there is only one option - use yarn classic.

### To reproduce

Not matter, since fix already done.

### Environment

Not matter, since fix already done.

**Comment by arcanis** [comment]
We don't backport non-critical fixes.

**Comment by 243083df** [comment]
> We don't backport non-critical fixes.

Will there be no support for the git protocol in yarn 2?
