### ISSUE TITLE
[Compatibility] @yarnpkg/builder cannot build composite typescript packages

### ISSUE THREAD

**Issue by dmattia** [yarnpkg/berry#3079]
`declaration: false` is hardcoded into the `compilerOptions` here: https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-builder/sources/tools/makeConfig.ts#L91

This is incompatible with `composite: true` in tsconfigs, which requires that `declaration` be set to `true` when present.

One suggestion here is that when we hardcode `declaration: false`, `composite: false` is also hardcoded

**Comment by merceyz** [comment]
The builder was switched to use esbuild in https://github.com/yarnpkg/berry/pull/2362 and https://github.com/yarnpkg/berry/pull/2717 so it doesn't actually use that config anymore, it's only used to build `@yarnpkg/pnp` internally in this repo

https://github.com/yarnpkg/berry/blob/8fe214dfa72dabbc7134bbd6973cdfce4891cd42/packages/yarnpkg-pnp/webpack.config.hook.js#L7
https://github.com/yarnpkg/berry/blob/8fe214dfa72dabbc7134bbd6973cdfce4891cd42/packages/yarnpkg-pnp/webpack.config.pkg.js#L5
