### ISSUE TITLE
[Discussion] JSON-Stream format for `yarn config`

### ISSUE THREAD

**Issue by Teoxoy** [yarnpkg/berry#308]
**What package is covered by this investigations?**

@berry/plugin-essentials

**Describe the goal of the investigation**

Make it easier to discover config options by making the output of `yarn config --json` a single json object comprised of config keys that map to the config options.

**Investigation report**

When I first ran `yarn config --json` I was surprised that the output was not a json object.

Making the output a single json object where the keys are the config options will make it easier to parse and lookup a config option (instead of looping over the returned json objects or constructing a single json object from the ones returned).

microsoft/vscode-languageserver-node#496 could make use of this simplified approach

Here is the code snippet with the current logic:
https://github.com/yarnpkg/berry/blob/143a0b5623b89d1b09229fe28bed80f3723dba29/packages/plugin-essentials/sources/commands/config.ts#L63-L78

I would be happy to put up a PR for this.

**Comment by arcanis** [comment]
To give some context:

- Some commands produce data dynamically (for example install)
- We don't want to wait for the command to be finished to start printing
- Ergo we need, in at least some cases, to print multiple JSON objects
- I value consistency a lot; if we need to print streamed objects in some places, then I think it's acceptable to do it everywhere - same rules for everyone
- Given that the output is guaranteed to be exactly one object by line (we won't have an object over multiple lines), the parsing is quite straightforward anyway
- Some tools (in particular `jq`) have builtin support for this format

So although it might certainly be a surprising format, I'm not convinced it should be changed.

**Comment by Teoxoy** [comment]
This is understandable. I thought the `--json` arg was only used for the `config` command. Consistency is king.

Having said that, I think it should be mentioned somewhere in the docs that the returned json is actually a stream of json objects.

**Comment by Teoxoy** [comment]
Would you like a PR that would mention this in the docs?

**Comment by arcanis** [comment]
It seems [we forgot to document](https://yarnpkg.github.io/berry/cli/config) the `--json` flag altogether so yes, let's add something 😃

It should be here:

https://github.com/yarnpkg/berry/blob/master/packages/plugin-essentials/sources/commands/config.ts#L20-L26

**Comment by arcanis** [comment]
Just learned that it has an official name: [NDJSON] (http://ndjson.org/)

**Comment by v4dkou** [comment]
@arcanis How about renaming the `--json` flag to `--ndjson` in yarn v4?
It'd be a bit more self-evident that it is not in fact JSON.

Just tripped up migrating some internal Yarn Classic-based tools on two things:
1. --json used to produce one valid JSON object for commands like `yarn workspaces info`, now `yarn workspace list` produces NDJSON (albeit Yarn Classic already had NDJSON for `yarn add`)
2. Not all commands accept --json in Yarn Berry that used to in Yarn Classic. (i.e. `yarn add` does not anymore)

The first one is easy: adding 2 characters "nd" to a flag would not clutter up the CLI, while clarifying intent.
The second requires more discussions and work, not sure whether to create a Feature Request about it.

I am willing to make PRs for both issues if greenlit.

**Comment by arcanis** [comment]
I'm not convinced `--ndjson` would be much better (supporting both versions of Yarn would still require to have code specific to both), and would break Yarn 3+ scripts already written for `--json` (unless we supported both for compatibility reasons, but at this point why even add another option?). Plus, "ndjson" isn't a well-known thing, so I suspect it'd only be discovered by looking at the documentation, repeatedly (people would keep forgetting how to write it).

Adding `--json` to more commands is fair game, though!

**Comment by v4dkou** [comment]
@arcanis I see your point, it'd be easier if there was no legacy at all. :smile: 
However, having both for compatibility would make sense if `--json` would print a warning to stderr that said roughly this:
`Warning! --json uses NDJSON format rather that standard JSON. Consult with documentation and use --ndjson flag to suppress this warning.`

Given that scripts usually read output from stdout, they probably wouldn't break, but it would make it less surprising for new developers who try out stuff in CLI before writing scripts.
