### ISSUE TITLE
[Bug] @berry/pnpify ignores pnpPath

### ISSUE THREAD

**Issue by Teoxoy** [yarnpkg/berry#309]
**Describe the bug**

@berry/pnpify ignores pnpPath config option

**To Reproduce**

I don't think this is needed - it's apparent from looking at the source
Check out Additional context

**Additional context**

https://github.com/yarnpkg/berry/blob/a5cadd6309126ba0b04ea821fa37fa312b05fcd9/packages/berry-pnpify/sources/generateSdk.ts#L32

generateSdk looks for `.pnp.js` at the root of the project instead of asking yarn for the `pnpPath`

**Comment by arcanis** [comment]
Although the location of the PnP file is technically configurable, I'm not sure we really want to support storing it elsewhere than in the project root 🤔

The primary problem (and that's similar for https://github.com/microsoft/vscode-languageserver-node/issues/496) is that it would require the PnPify binary (and any other tool that would want to add some specific PnP integration) to add the Yarn core into its dependencies (to parse the configuration). That sounds a bit overkill for a fringe use case.

**Comment by Teoxoy** [comment]
Makes sense - having the pnpPath configurable makes everything more complex.

I would say we get rid of it then.

**Comment by Teoxoy** [comment]
Would you like a PR that would remove `pnpPath`?

**Comment by arcanis** [comment]
Yes, I think it's ok - let's move it from the configuration to a constant. I'd suggest to make it a function that given a `Project` would return the path to the file. Something like:

```ts
const getPnpPath = (project: Project) => ppath.join(project.cwd, `.pnp.js` as Filename);
```

**Comment by Teoxoy** [comment]
I am not too familiar with the codebase. Where do you think it's most appropriate to put the function?

Can't it actually be a method on the `Project` class? - so that you don't need to pass the project to get the path - after all the `.pnp.js` file is a critical piece and is quite related to the `Project`

Having the method on the `Project` class will make the transition smoother - currently the way to get `pnpPath` is trough the `Configuration` instance on the `Project` instance.

**Comment by arcanis** [comment]
Sorry I didn't see your comment before! I don't think it should be a method of the `Project` class. In essence, PnP shouldn't be required for the core to work; any interaction with it should come from the `plugin-pnp` package.

This makes it possible to use Yarn to install other projects than JavaScript without having to include the PnP code. It might be useful later if we want to provide a C++-only package manager, for example. More generally, it also prevents our codebase from getting too entangled.

So in this case, I'd suggest to put this function in the `index.ts` from `plugin-pnp`.

**Comment by Teoxoy** [comment]
Makes sense, I thought the core was dependent on the pnp stuff.
