### ISSUE TITLE
[Bug]: `workspaces foreach run` doesn't check for binaries

### ISSUE THREAD

**Issue by wdfinch** [yarnpkg/berry#3095]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

It seems that `prettier --write` will not write any files when used with the `yarn workspace foreach` command. I noticed this issue after upgrading the node v16 so it could be related to this.

### To reproduce

Open the attached project and run `yarn run prettier:all` at the root workspace level. Notice that prettier does not write any files.

[test.zip](https://github.com/yarnpkg/berry/files/6772011/test.zip)

### Environment

OS: Ubuntu 20.04.2.0 LTS
Node: v16.4.1
Yarn: 3.0.0-rc.9

**Comment by alexgwolff** [comment]
Hi, I have same problem with any command with `yarn workspaces foreach`.

OS: Mac 11.4
Yarn Version: 2.4.2

Nodes Version:
 v14.17.3 - Work
 v15.14.0 - Don`t work
 v16.3.0 - Don`t work

**Comment by merceyz** [comment]
To document why I marked this as `upholded`:

The issue is that `workspaces foreach run` doesn't check for binaries, only scripts so it's not that `prettier` doesn't write anything it's that Yarn doesn't run it

**Comment by merceyz** [comment]
This was fixed in https://github.com/yarnpkg/berry/issues/3095
