### ISSUE TITLE
[Bug?]: Resolutions field is not working

### ISSUE THREAD

**Issue by LaurensUP** [yarnpkg/berry#3122]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

We're using React 17 and other packages not supporting this version.
So we want to use have React v16 dependencies to be resolved to v17 through the `resolutions` field.
This is not working. It's giving a ton of YN0060 warnings in upgrading our monorepo to Yarn 2.

### To reproduce

- Create a fresh project
- `yarn set version berry`
- `yarn add react@17`
- `yarn add recompose` (which only supports React v16)
- Add the `resolutions` field to `package.json`
``` json
  "resolutions": {
    "react": "17.0.2"
  }
```
- Recompose is not using react v17
``` bash
➤ YN0000: ┌ Resolution step
➤ YN0060: │ yarn2-resolution-repr@workspace:. provides react (pc664d) with version 17.0.2, which doesn't satisfy what recompose requests
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
```

`yarn explain peer-requirements:`
``` bash
➤ YN0000: yarn2-resolution-repr@workspace:. provides react@npm:17.0.2 with version 17.0.2, which doesn't satisfy the following requirements:

➤ YN0000: recompose@npm:0.30.0 [f113b] → ^0.14.0 || ^15.0.0 || ^16.0.0 ✘
```

### Environment

 System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Binaries:
    Node: 14.17.1 - /tmp/xfs-3a7680d5/node
    Yarn: 2.4.2 - /tmp/xfs-3a7680d5/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm

### Additional context

The current upgrade process of our project
![image](https://user-images.githubusercontent.com/86610066/125742930-40534b77-2b2e-4ac9-91d5-22705f0f5fd8.png)

**Comment by nvdbleek** [comment]
Making the react peer dependency optional in the package 'solves' the problem:
```
{
  "name": "my-package",
  "dependencies": {
    "react": "17",
    "recompose": "^0.30.0"
  },
  "peerDependenciesMeta": {
    "react": {
      "optional": true
    }
  }
}
```

When using yarn workspaces you have to add this `peerDependenciesMeta` block to every package, which introduced a lot of boilerplate in your package.json files.

I'm also wondering why we still need to make the peer dependency optional if we install the dependency (not the correct version of that dependency but we override the version with a `resolutions` block)

**Comment by arcanis** [comment]
> we override the version with a `resolutions` block

The `resolutions` field overrides the resolutions. The peer dependencies hints have no effect on the resolution, and only used to warn you when something looks incorrect. If you wish to silence those warnings, you can use [`logFilters`](https://yarnpkg.com/configuration/yarnrc#logFilters).
