### ISSUE TITLE
[Bug?]: @yarnpkg/sdks is a 404

### ISSUE THREAD

**Issue by timmywil** [yarnpkg/berry#3137]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

@yarnpkg/sdks package is a 404. I noticed a recent refactor to this package and its documentation. Maybe I'm missing obvious, but the package no longer seems available.

### To reproduce

```sh
$ yarn dlx @yarnpkg/sdks vscode
➤ YN0027: @yarnpkg/sdks@unknown can't be resolved to a satisfying range:

HTTPError: Response code 404 (Not Found)
```

```sh
$ yarn add -D @yarnpkg/sdks
➤ YN0027: @yarnpkg/sdks@unknown can't be resolved to a satisfying range:

HTTPError: Response code 404 (Not Found)
```

```sh
$ yarn search
Press <up>/<down> to move between packages.      Press <enter> to install the selected packages.
Press <space> to select a package.               Press <ctrl+c> to abort.
Press <space> again to change the target.

Search: yarnpkg/sdks                             Owner          Version    Downloads
 > univapay-node                                 univapay       1.0.15     1.1k
   gopay-node                                    gyro-n         0.8.41     133
   rigado-thingy-starter-dashboard               mbc            0.1.0      22
   univapay-node-es                              univapay       0.3.13     99
```

### Environment

```
  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.17.3 - /private/var/folders/jt/bdr1wc4x613_1qnjchb6kjn80000gn/T/xfs-e14068d8/node
    Yarn: 2.4.2 - /private/var/folders/jt/bdr1wc4x613_1qnjchb6kjn80000gn/T/xfs-e14068d8/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
```

**Comment by timmywil** [comment]
I'm now realizing that maybe I've never used `@yarnpkg/sdks` and was thinking of `yarn dlx @yarnpkg/pnpify --sdk`, but the documentation recommending `@yarnpkg/sdks` is already live.

**Comment by paul-soporan** [comment]
We've just split `@yarnpkg/pnpify` into 3 packages including `@yarnpkg/sdks` for our next 3.0 release, but the docs aren't versioned so they display whatever is true for `master`.

I've started an RC release so that `@yarnpkg/sdks` can get published to the registry but it looks like we have a few problems with the release script so it might take some time until the package gets published to the registry. Use `yarn dlx @yarnpkg/pnpify --sdk` in the meantime. 🙂
