### ISSUE TITLE
[documentation] yarn install should specify which scripts are run

### ISSUE THREAD

**Issue by fulldecent** [yarnpkg/berry#3147]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

1. I started at https://yarnpkg.com
2. It says "Special care is put into our documentation", great `-Wall`
3. Then I went to https://yarnpkg.com/cli/install to learn about `yarn install`
4. I was expecting this page to stand on its own and explain what the command `yarn install` does
5. This page makes vague, non-explicit references to some "build scripts" that will be run
6. Sadness

**Describe the solution you'd like**

I would like the official `yarn install` documentation page to fully explain how this command works. If build scripts are run, specify which scripts they are. If I need additional context to answer that question, provide that context to me.

**Describe the drawbacks of your solution**

Some people like magic and want "random" unspecified things to happen if they might be helpful. Those people can use software but their license to create software should be revoked.

**Describe alternatives you've considered**

Delete the documentation -- at least it will be consistent.

Create a blog post -- which will be correct, complete, and consistent, but soon outdated.

Do nothing -- just assume Yarn works exactly like some other JS package manager (which version?) and proceed like that.

**Comment by arcanis** [comment]
There's something that irks me in your tone, although I'm not entirely sure what.

Anyway, no single page of the documentation is meant to include the whole documentation - otherwise we wouldn't have pages. Specifically, the more information we duplicate between pages, the harder it is to keep it accurate and up-to-date.

In the particular `install` case, the running scripts are detailed in [Lifecycle Scripts](https://yarnpkg.com/advanced/lifecycle-scripts).

**Comment by fulldecent** [comment]
My intention here is constructive, and excited specifically about documentation. Sorry for any negativity that came through.

Agreed—keep documentation DRY.

Thank you, that's a great reference. Here is a PR that puts it into a relevant place: https://github.com/yarnpkg/berry/pull/3156
