### ISSUE TITLE
[Bug] Upgrading a yarn package to use v2 puts package in a broken state if an unsupported configuration key is set

### ISSUE THREAD

**Issue by rmilejcz** [yarnpkg/berry#317]
**Describe the bug**

I wanted to try using the new `yarn dlx` command, so I navigated to a project I had and followed [these instructions](https://yarnpkg.github.io/berry/getting-started/install). My global yarn version is 1.17.3, my package yarn version is 2.0.0 just as expected, but I can no longer run **any** yarn commands or else I get this error:
>Usage Error: Unrecognized configuration settings found: global - run "yarn config -v" to see the list of settings supported in Yarn (in \<environment\>)

**To Reproduce**

1) Make sure global yarn version is at least 1.17.3
2) Run `yarn config set global $HOME/.config/yarn/global/node_modules/.bin` (I'm not sure why but this is what `yarn config get global` returns, I don't think I set this manually but I might have)
3) Run `yarn init`
4) Add some package, I chose `yarn add immer` because it's tiny and has no dependencies
5) Run `yarn policies set-version v2`
6) Run `yarn --version` to confirm you are on v2
7) Run any yarn command, such as `yarn remove immer` to see the error output

**Environment if relevant (please complete the following information):**

 - OS: OSX 14.4
 - Node version: 12.6.0
 - Yarn version: 2.0.0 / 1.17.3

**Additional context**

Even if I ran `yarn config delete global` from a context where `yarn` was v1.17.3, I got the same error. I'm not sure why `global` is set, it's possible I did that at some point as a debug step. Since I couldn't run any yarn commands, `yarn policies set-version 1.17.3` also failed. Since `yarn` v2 has no analogue to `yarn config delete` I was also unable to edit the config via the CLI. Ultimately I was able to resolve this by removing and reinstalling `yarn` via `brew`:

    brew remove yarn
    brew install yarn

**Comment by arcanis** [comment]
I tried to repro it with no luck. Some details:

- It would be helpful if you could add some debug info around [here](https://github.com/yarnpkg/berry/blob/master/packages/berry-core/sources/Configuration.ts#L729). Your error message mentions `(in )`, which means that for some reason the source is an empty string, which isn't supposed to happen. If you can find out why it would be interesting!

- Since we moved the settings to `.yarnrc.yml` (and no longer `.yarnrc`) the legacy settings shouldn't affect the v2. Are you on an up-to-date repository? Which file contains the `global` settings?

**Comment by rmilejcz** [comment]
>It would be helpful if you could add some debug info around here. Your error message mentions (in ), which means that for some reason the source is an empty string, which isn't supposed to happen. If you can find out why it would be interesting!

Seems like githubs markdown parser doesn't like \< or \>, the error actually reads:

>(in \<environment\>)

though that could still be incorrect.

This actually solved it for me:

>Since we moved the settings to .yarnrc.yml (and no longer .yarnrc) the legacy settings shouldn't affect the v2. Are you on an up-to-date repository? Which file contains the global settings?

[The instructions here](https://yarnpkg.github.io/berry/getting-started/install) created a `.yarnrc` at my project root that seems to have copied values from my `yarn config`. Recreating that file as a `.yml` file with the exact some info solves the problem. Not sure if that's an actual bug or if I somehow followed the instructions or otherwise missed some important context.

**Comment by arcanis** [comment]
Do you have a variable named `YARN_GLOBAL`? All variables prefixed with `YARN_` (except some that are special) are injected into the configuration 🤔

**Comment by rmilejcz** [comment]
Ah that was it, I was referencing it in a bash script and just happened to use a conflicting name convention. Renamed `YARN_GLOBAL` to `GLOBAL_YARN_PATH` and then ran `unset YARN_GLOBAL`, everything now works as expected.

**Comment by kemaric** [comment]
If someone sees the error of

> Usage Error: Unrecognized configuration settings found: global - run "yarn config -v" to see the list of settings supported in Yarn (in <environment>)



 Look in your environment files and environment variables for `YARN_STRICT_SSL` (e.g `set | grep -i "yarn_strict_ssl"`) and unset it.

**Comment by WebMechanic** [comment]
> Do you have a variable named `YARN_GLOBAL`? All variables prefixed with `YARN_` (except some that are special) are injected into the configuration 🤔

o.m.f.g!

@kemaric  I ❤️ U!

**For weeks** I've been bothered in one project with yarn complaining about some `path` config setting I couldn't find anywhere. It was driving me nuts, unable to update stuff.
Turns out I had `YARN_PATH` (pointing to the .bin folder) in the start script of one terminal app.

**Removed the env var it and all is fine now!**

Thank you! 🙏🏻
