### ISSUE TITLE
[Compatibility] 

### ISSUE THREAD

**Issue by kubijo** [yarnpkg/berry#3175]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Pycharm stopped working with SDK-ed prettier because it now checks the minimal supported version & you're marking the SDK-ed version as `0.0.0-sdk` in its `package.json`… Which I always found silly anyway, and if I change it to `2.3.2-sdk` it works again.

Can you please, if at all possible, propagate the package?

### To reproduce

- `yarn add prettier`
- `yarn sdks base`
- point Pycharm `2021.1.3` (or any other IntelliJ IDE I guess) to `.yarn/sdks/prettier`

I've [created an issue in their bug tracker](https://youtrack.jetbrains.com/issue/WEB-51831), but since changing the version does mitigate the problem I'd say it's a problem with Yarn as much as with the IDE.

### Environment

```
  System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 14.17.0 - /tmp/xfs-3a83d866/node
    Yarn: 3.0.0-rc.12.git.20210720.hash-0bb4746e - /tmp/xfs-3a83d866/yarn
    npm: 6.14.13 - ~/.virtualenvs/pool/bin/npm
```

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/3173, run `yarn dlx @yarnpkg/sdks` to update it
