### ISSUE TITLE
[Bug?]: `yarn set version` cannot install version 2.x

### ISSUE THREAD

**Issue by hswhite33** [yarnpkg/berry#3180]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Since the release of Yarn v3.0.0, I am unable to install v2.x via `yarn set version`:

* `yarn set version 2.x`, `yarn set version 2.4.1`, `yarn set version 2.4.0` all result in `error An unexpected error occurred: "Release not found: 2.x".` (etc)
* `yarn set version 2` installs the latest `berry` version (which is version 3)

### To reproduce

`yarn set version 2.x`

Expect: latest version in the v2 series is installed
Actual: `error An unexpected error occurred: "Release not found: 2.x".`

`yarn set version 2`

Expect: v2 is installed
Actual:  https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js is installed

### Environment

System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD

**Comment by merceyz** [comment]
Yarn 1.22.10 is not able to install specific v2 versions, however v3 is so you can install v3 then downgrade to v2
```sh
# Update to v3
yarn set version berry
# Downgrade to v2
yarn set version 2.x
```
