### ISSUE TITLE
[Feature] yarn versions

### ISSUE THREAD

**Issue by Shinigami92** [yarnpkg/berry#3188]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

As a developer, I often want to check which versions are installed in my CIs, but I this is not possible anymore with yarn berry (v2) and I miss this feature.

**Describe the solution you'd like**

Reimplement https://classic.yarnpkg.com/en/docs/cli/versions/ nativly or as a plugin and mention it in the docs (https://yarnpkg.com/getting-started/migration#cli-commands)

**Describe the drawbacks of your solution**

I would like to upgrade to yarn berry without missing features.
https://github.com/prettier/plugin-pug/runs/3174198854?check_suite_focus=true#step:5:7

**Describe alternatives you've considered**

Are there any? Please note them.

Run `npm --version`, `node --version` and `yarn --version` manually.

https://github.com/prettier/plugin-pug/blob/9d8cb3f920b1975c19896757a89ced19d7d61b3f/.github/workflows/ci.yml#L39-L43

But this doesn't show as many info as before :slightly_frowning_face:

**Comment by merceyz** [comment]
Since the Yarn binary is checked in you should already know that version, as for the rest you can run
```
node -p process.versions
```
