### ISSUE TITLE
Readme incorrectly claims neovim compatibility

### ISSUE THREAD

**Issue by benwainwright** [yarnpkg/berry#3192]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

This PR https://github.com/yarnpkg/berry/pull/3041 amended the documentation to indicate that Neovim native LSP support `support should work out of the box with nvim-lspconfig and theia-ide/typescript-language-server.`

...except that's not actually the case at present because the change that enables this feature depends on https://github.com/theia-ide/typescript-language-server/pull/220. Although this has been merged to the mainline, that package hasn't had a code release in about a month. So the currently available version (if you don't want to clone the repo and install it yourself) doesn't include that change.

This is a very confusing and frustrating experience for users. Took me a fair bit of digging around and Googling to understand why my editor was not behaving as described.

I've already raised an issue on the typescript-language-server repo as well (https://github.com/theia-ide/typescript-language-server/issues/239) I'm just raising it here to get more eyes on this issue in the hope that someone happens to see it that might release that package, because I _really want this change_...

**Comment by danieltroger** [comment]
Would be great to get this fixed

**Comment by merceyz** [comment]
cc @tapayne88

**Comment by tapayne88** [comment]
Apologies @benwainwright! I hadn't anticipated there being such a gap between the yarn & TS LS changes being merged and published.

We'll also want this PR merging into nvim-lspconfig to enable out-of-the-box LSP.
https://github.com/neovim/nvim-lspconfig/pull/1078

**Comment by benwainwright** [comment]
Ok thanks for the reply @tapayne88. I've emailed the language server repo maintainer directly but in the meantime maybe those lines should be taken out of your readme?

**Comment by tapayne88** [comment]
I'd have to defer to @merceyz on that. Happy to put something together that could be reverted when https://github.com/theia-ide/typescript-language-server/pull/220 is merged, which hopefully won't be too far away 🤞

**Comment by benwainwright** [comment]
@tapayne88 Looks like that won't be necessary. See https://github.com/theia-ide/typescript-language-server/issues/239#issuecomment-894678523 🎉

**Comment by benwainwright** [comment]
Happy to close this issue following https://github.com/typescript-language-server/typescript-language-server/issues/239#issuecomment-897638986
