### ISSUE TITLE
[Feature] Allow disabling PnP module resolution for a single script run

### ISSUE THREAD

**Issue by joelmukuthu** [yarnpkg/berry#3195]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

Given this script in a package.json file:

```json
{
  "scripts": {
     "start": "node file1.js && node file2.js"
   }
} 
```
 
When I run `yarn start`, I want the first command (`node file1.js`) to be PNP-enabled while the second one (`node file2.js`) isn't.

Scenario: I use esbuild to bundle code and nodemon to run the bundle. Some Node.js modules need to be built on the target machine and are therefore configured as [external for esbuild](https://esbuild.github.io/api/#external), such that the bundle will contain `require` calls for the external modules. I'd like Yarn to not try and resolve those `require` calls when running nodemon. 

In the example below, when I run `yarn start`, I'd like Yarn to also treat `sse4_crc32` as "external" module when running `nodemon` i.e. let Node.js resolve it as usual from a node_modules directory.

Package.json:

```json
{
  "scripts": {
     "start": "esbuild app.js --bundle --external:sse4_crc32 --outfile out.js && nodemon out.js"
   }
} 
```

App.js:

```js
import 'sse4_crc32';
```

**Describe the solution you'd like**

A config option that would allow disabling PnP resolution at run-time. I imagine something similar to `nodeLinker` that also has effect at run-time. Ideally it should also be configurable as an environment variable.

**Describe the drawbacks of your solution**

Adding a config option could generally lead to steeper learning curves, poorer UX, perhaps even confusion with `nodeLinker`. Maybe `nodeLinker` could be made to work at run-time?

**Describe alternatives you've considered**

An alternative I've considered is to update my code to run `nodemon` directly from `./node_modules/.bin/nodemon`, though I'm not sure if that'll actually work. I haven't tested it since in my case I'm running both `esbuild` and `nodemon` programmatically, as opposed to using the CLIs. However, in the programmatic use-case, spawning a child process to run nodemon might work.

**Comment by merceyz** [comment]
You can disable it by setting the `NODE_OPTIONS` env variable to an empty string
```json
{
  "scripts": {
     "start": "node file1.js && NODE_OPTIONS="" node file2.js"
   }
} 
```

> i.e. let Node.js resolve it as usual from a node_modules directory.

There shouldn't be one since Yarn deletes it on installs

**Comment by joelmukuthu** [comment]
> You can disable it by setting the `NODE_OPTIONS` env variable to an empty string

Thanks for the workaround! 

> There is no node_modules folder when using PnP

I have a node_modules directory in the run-time environment because I'm installing the external modules with npm. So the full setup is something like 

```
esbuild app.js --external:sse4_crc32 --outfile out.js && npm install sse4_crc32 && NODE_OPTIONS='' nodemon out.js
``` 

I also do that so I can use node (or nodemon) directly instead of `yarn node` (or `yarn nodemon`).

**Comment by merceyz** [comment]
> Thanks for the workaround!

It's not really a workaround but the solution

> because I'm installing the external modules with npm

That doesn't seem like a good idea, you shouldn't be mixing the package managers
