### ISSUE TITLE
[Bug?]: Yarn 3.0.0 PnP changes the way dependencies binaries resolve paths?

### ISSUE THREAD

**Issue by julienfouilhe** [yarnpkg/berry#3198]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

Sorry if this is more of a problem related with `dependency-cruiser`, but it happened when I upgraded to yarn `3.0.0` from `2.4.1`.

Basically I use a tool called dependency-cruiser to do some code analysis and notice problems in my CI.

With yarn 2 and PnP enabled, I had no problem running it.
I upgraded to yarn 3 and now it shows an error when trying to access subdirectories.

```
ERROR: error TS18003: No inputs were found in config file './tsconfig.json'. Specified 'include' paths were '["src"]' and 'exclude' paths were '["**/.*/"]'.
```

It reads my tsconfig for the include / exclude parameters. But it does not seem to find my directories, when it does with yarn 2.4.1...

I read the changelog and could not find something that would make sense to me so hence why I think this is a yarn 3 bug.

### To reproduce

This is the 3.0.0 minimal repro: https://github.com/julienfouilhe/repro-depcruise/tree/master. You can look at the Github Actions job to see the error.
The 2.4.1 repro is on the yarn2 branch of the same repo. There you can see the depcruise command runs successfully.

### Environment

  System:
    OS: macOS 11.3
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  Binaries:
    Node: 14.16.1 - /private/var/folders/fc/v0xg1nts2mxf8jv1hnplwb800000gn/T/xfs-01309e90/node
    Yarn: 3.0.0 - /private/var/folders/fc/v0xg1nts2mxf8jv1hnplwb800000gn/T/xfs-01309e90/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm

**Comment by julienfouilhe** [comment]
Definitely seems related to yarn 3. In a monorepo context, when launching `yarn app start`, which is just `parcel serve index.html`. Parcel can't seem to find the .env files. Now if I copy the .env files in the root directory, it finds the file...

**Comment by merceyz** [comment]
This seems to be the same issue as https://github.com/yarnpkg/berry/issues/3136, updating to the latest Yarn RC or `dependency-cruiser` release fixes the issue.

```sh
yarn set version canary
# or
yarn up dependency-cruiser@^10.1.0
```
