### ISSUE TITLE
[Bug?]: yarn plugin import workspace-tools is broken??

### ISSUE THREAD

**Issue by arroyc** [yarnpkg/berry#3199]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

yarn plugin import workspace-tools command is broken since Sunday (7/25), this command runs succesfully. But after that any yarn command  throws error

### To reproduce

Have .yarnrc.yml and typical yarn2 requirements in your app directory
run 
 yarn plugin import workspace-tools >> success
yarn --version

this will show this error
```
Usage Error: This plugin cannot access the package referenced via typanion which is neither a builtin, nor an exposed entry (when initializing @yarnpkg/plugin-workspace-tools, defined in /github/workspace/.yarnrc.yml)

Yarn Package Manager - 2.4.1

  $ yarn <command>

You can also print more details about any of these commands by calling them 
after adding the `-h,--help` flag right after the command name.
```

### Environment

OS: stretch/debian 9 
It runs in github action agents, so dont know much other environment details, I can get those details if needed.
But this is repro-ing in local docker container (debian based node 14 image) as well

**Comment by geisterfurz007** [comment]
The time the plugin broke seems to match the release of plugin version [3.0.0](https://www.npmjs.com/package/@yarnpkg/plugin-workspace-tools?activeTab=versions). 

## Workarounds
Following are two workarounds, pick the one that is more suitable for your usecase.

1. Upgrade yarn:  Upgrading Yarn to 3.0.0 by running `yarn set version latest` allows you to use the 3.0.0 version installed with `yarn plugin import workspace-tools`.

2. Don't run `yarn plugin import workspace-tools` in your project: I noticed this issue as well when my Docker builds started breaking over the night. I assume you are not supposed to import plugins again in the CI and instead just once when setting up your project. That's probably somewhere in the docs but I didn't search for it. As long as `.yarn/plugins` and `.yarnrc.yml` are copied into the container, the plugin should properly get referenced. I removed the plugin import from my Dockerfile and the build worked again, including `yarn workspaces focus`.

**Comment by arroyc** [comment]
thank you for responding @geisterfurz007 .. yeah it broke our CI totally ... now going back to your workaround no 2 doesnt work .. only option is no 1  for us. But unfortunately yarn set version latest is not upgrading yarn to 3.0.0. Am I missing something?
To repro I used an official node-14 image which comes with yarn 1.22.5. Here is what I ran ..

> Unable to find image 'node:16' locally
> 16: Pulling from library/node
> 627b765e08d1: Already exists
> c040670e5e55: Already exists
> 073a180f4992: Already exists
> bf76209566d0: Already exists
> ca7044ed766e: Pull complete
> 51bff5b8b0ef: Pull complete
> ec88359bd66f: Pull complete
> 1829abc8bab1: Pull complete
> 47f423bb50ee: Pull complete
> Digest: sha256:8229a1f3580d32fa18b2304fa23df6e9e3d53fdb958fd8ffe812ca7a0a26bb69
> Status: Downloaded newer image for node:16
> root@86ec94602635:/# yarn -v
> 1.22.5
> root@86ec94602635:/# yarn self-update
> yarn run v1.22.5
> error Couldn't find a package.json file in "/"
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> root@86ec94602635:/# yarn set version latest
> Resolving latest to a url...
> Downloading https://github.com/yarnpkg/yarn/releases/download/v1.22.11/yarn-1.22.11.js...
> Saving it into /.yarn/releases/yarn-1.22.11.cjs...
> Updating //.yarnrc...
> Done!
> root@86ec94602635:/# yarn -v
> 1.22.11

**Comment by merceyz** [comment]
You shouldn't be running these commands on your CI and/or in Docker builds, you should run it locally once and commit it to your repository.

The reason this is happening is that we released Yarn 3.0 and the 3.0 plugins aren't compatible with Yarn 2.0. We added support for specifying a version when importing plugins in 3.0 and made sure it imports compatible plugins so this shouldn't be an issue for future releases.

As a workaround you can run this to get the compatible version while staying on `yarn@2.4.1`
```sh
yarn set version berry
yarn plugin import workspace-tools@2.2.0
yarn set version 2.4.1
```

> To repro I used an official node-14 image which comes with yarn 1.22.5. Here is what I ran ..
> yarn set version latest

When you run that with v1 it grabs the latest v1 version, run this instead:
```
yarn set version berry
```

**Comment by arroyc** [comment]
thank you @merceyz

**Comment by paulrberg** [comment]
Running `yarn plugin import workspace-tools@2.2.0` causes the following error in my case:

```
➤ YN0051: Couldn't find a plugin named "@yarnpkg/plugin-workspace-tools@2.2.0" on the remote registry. Note that only the plugins referenced on our website (https://github.com/yarnpkg/berry/blob/master/plugins.yml) can be referenced by their name; any other plugin will have to be referenced through its public url (for example https://github.com/yarnpkg/berry/raw/master/packages/plugin-typescript/bin/%40yarnpkg/plugin-typescript.js).
➤ YN0000: Failed with errors in 0s 539ms
```

What's the solution then? Upgrade to v3 if we want to use the `workspace-tools` plugin?

**Comment by merceyz** [comment]
See the workaround in https://github.com/yarnpkg/berry/issues/3199#issuecomment-889356924

**Comment by paulrberg** [comment]
**Update**: I solved this by running this:

```sh
yarn plugin import https://raw.githubusercontent.com/yarnpkg/berry/%40yarnpkg/plugin-workspace-tools/2.2.0/packages/plugin-workspace-tools/bin/%40yarnpkg/plugin-workspace-tools.js
```

But this felt like a hack. I had to find the corresponding tag on GitHub, then find the workspace plugin in the source code, then grab the link to the raw source code.

**Comment by paulrberg** [comment]
> See the workaround in #3199 (comment)

Aaah sorry, I thought that `yarn set version berry` was meant to be run by v1 users. I ran it now and I managed to successfully run `yarn plugin import workspace-tools@2.2.0`. Thanks!
