### ISSUE TITLE
[Feature] debuggable constraints

### ISSUE THREAD

**Issue by bgotink** [yarnpkg/berry#32]
- [x] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

As a use I want to test and debug the constraints I wrote in case they misbehave.

**Describe the solution you'd like**

Two options, one more complicated than the other:

- A new `yarn constraints query` command that starts a `tau-prolog` repl with the constraints rules loaded
- A `yarn constraints generate` command that creates the full prolog file containing all workspace data and my constraint rules, a file which I could then load into a prolog engine, e.g.

  ```bash
  yarn constraints generate full-constraints.pro
  swipl -f full-constraints.pro
  # this gives me a REPL to query the constraints in
  ```

**Describe the drawbacks of your solution**

The second solution has a major drawback, it depends on another prolog engine to perform the actual debugging. This means users can start making mistakes like testing with predicates that only exist in that other prolog engine. `tau` is quite limited, e.g. no string predicates, so this can be a pain.

**Describe alternatives you've considered**

The alternative is listed above

**Additional context**

Prolog is not going to come easy for a lot of developers, so giving a debugging environment is going to be very important.

**Comment by arcanis** [comment]
The first point would make sense! I don't think it would be too hard, and it would actually be an interesting way to quickly request information about the project (like obtain the number of dependencies) without having to write a complete plugin. 

Regarding your second point, have you checked the `yarn constraints source` command? I think it does what you want (if you add the `--verbose` flag it will print the full script, including the fact database).

**Comment by bgotink** [comment]
Huh, I've gone through the plugin-constraints multiple times but apparently completely glossed over that command 😅

**Comment by arcanis** [comment]
Closing this issue since those two use cases are now complete w/ #82 🎉
