### ISSUE TITLE
[Bug] @yarnpkg/pnpify package unable to resolve path containing spaces

### ISSUE THREAD

**Issue by unitario** [yarnpkg/berry#3225]
This is the path to my workspace: `/Users/stefan/Git/@Lorem/Lorem Ipsum/`

When I run this command: `yarn pnpify ng-packagr -p package.json -c tsconfig.json`

I get this error:

```bash
/Users/stefan/Git/@Lorem/Lorem Ipsum/.pnp.cjs:27935
    throw firstError;
    ^

Error: Qualified path resolution failed - none of those files can be found on the disk.

Source path: /Users/stefan/Git/@Lorem/Lorem
Not found: /Users/stefan/Git/@Lorem/Lorem
Not found: /Users/stefan/Git/@Lorem/Lorem.js
Not found: /Users/stefan/Git/@Lorem/Lorem.json
Not found: /Users/stefan/Git/@Lorem/Lorem.node

Require stack:
- internal/preload
    at Function.external_module_.Module._resolveFilename (/Users/stefan/Git/@Lorem/Lorem Ipsum/.pnp.cjs:27934:55)
    at Function.external_module_.Module._load (/Users/stefan/Git/@Lorem/Lorem Ipsum/.pnp.cjs:27735:48)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1225:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:467:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:70:3)
    at internal/main/run_main_module.js:7:1
```

It will only throw when using `@yarnpkg/pnpify`.

I have tracked down the issue to this section in the code `RunCommand.ts` line `36`.

https://github.com/yarnpkg/berry/blob/38fd3188dd5ca17b01fbc734c9879a3342b3c5d1/packages/yarnpkg-pnpify/sources/commands/RunCommand.ts#L36

Just add quotations for this section and it should work, i.e.

```
--require ${dynamicRequire.resolve(`@yarnpkg/pnpify`)}
```

Change to: 

```
--require "${dynamicRequire.resolve(`@yarnpkg/pnpify`)}"`.
```

* System Version: macOS 11.4 (20F71)
* Kernel Version: Darwin 20.5.0

**Comment by arcanis** [comment]
We initially couldn't add the double quotes because Node didn't support it until Node 12 (https://github.com/nodejs/node/commit/3ef1512f9e416cc7656b9cd16934dffdee1b11d3). Now that we stopped supporting Node 10 it's fair game, though. PR welcome! 😊

**Comment by nihalshetty-boop** [comment]
Hi, I would love to work on this. Just to be clear, I simply have to add double quotations after `--require` to:
```
--require ${dynamicRequire.resolve(`@yarnpkg/pnpify`)}
```
in line 36 of `RunCommand.ts`?

**Comment by unitario** [comment]
> Hi, I would love to work on this. Just to be clear, I simply have to add double quotations after `--require` to:
> 
> ```
> --require ${dynamicRequire.resolve(`@yarnpkg/pnpify`)}
> ```
> 
> in line 36 of `RunCommand.ts`?

I'm preparing a PR already.

**Comment by unitario** [comment]
@arcanis I have issued a (Pull Request)[https://github.com/yarnpkg/berry/pull/3226]. This is my first time contributing. Can you check that everything is in order please. Thanks!
