### ISSUE TITLE
[Feature] Post-resolution hook

### ISSUE THREAD

**Issue by ylemkimon** [yarnpkg/berry#3246]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

As a project manager, I'd like to enforce some policies on dependencies of the project, i.e., check the tree before installing them. However, a custom resolver or fetcher cannot access the whole tree and there is no hook.

**Describe the solution you'd like**

A `postResolution` hook that runs after the `Post-resolution validation` step but before the `Fetch step` in `Project.install()`:
https://github.com/yarnpkg/berry/blob/01586a88806a2bebd7edb28d1bee3581b1fd3762/packages/yarnpkg-core/sources/Project.ts#L1460-L1462

**Describe the drawbacks of your solution**

The hook may render the state of a project invalid, but I think it's the responsibility of the developer of the plugin.

**Describe alternatives you've considered**

- Abstract validations in the `Post-resolution validation` step into a `Validator` class and support plugins to add custom validators

**Comment by arcanis** [comment]
Did you solve this another way?

**Comment by ylemkimon** [comment]
@arcanis Yes, using the `validateProject` hook, which runs before the resolution. And since the resolution is idempotent, it'd be possible to call `resolveEverything` in the hook. Please correct me if I'm wrong.

**Comment by arcanis** [comment]
Yep, that's a good idea! It does the resolution twice but that's likely an acceptable cost. Glad you found a way 👍
