### ISSUE TITLE
What's the meaning of Editor SDKs configure?

### ISSUE THREAD

**Issue by wenjoy** [yarnpkg/berry#3263]
### Discussed in https://github.com/yarnpkg/berry/discussions/3261

<div type='discussions-op-text'>

<sup>Originally posted by **wenjoy** August 10, 2021</sup>
Under the GETTING STARTED tab, there is a big topic about [Editor SDKS](https://yarnpkg.com/getting-started/editor-sdks).

I read the doc but I can't figure out :
1. What has it brought for me after I execute `yarn dlx @yarnpkg/sdks vscode`?
2. Why put this topic to a such outstanding position since yarn is a package manager tool? Why a package manager tool would care about user's editor tool? Isn't it weird?</div>

**Comment by merceyz** [comment]
No need to open an issue when a discussion already exists
