### ISSUE TITLE
[Feature] Skip typescript patch on nodeLinker: node-modules

### ISSUE THREAD

**Issue by mizchi** [yarnpkg/berry#3275]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

I use `typescript` as frontend module on vite compiler. 

`yarn v3.0.0` patches typescript that can not compile to frontend.

```
 > node_modules/typescript/lib/typescript.js:115012:37: error: Could not resolve "pnpapi" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    115012 │                 var pnpApi = require("pnpapi");
           ╵                                      ~~~~~~~~

20:36:49 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/typescript/lib/typescript.js:115012:37: error: Could not resolve "pnpapi" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
```

I can not avoid this on yarn v3 environment.

**Describe the solution you'd like**

I'm using yarn v3 with `nodeLinker: node-modules`. In this case, typescript patch is not required.

I need skip patch option for typescript.

**Describe the drawbacks of your solution**

**Describe alternatives you've considered**

**Comment by merceyz** [comment]
We don't plan on disabling the patch (see https://yarnpkg.com/getting-started/qa/#why-is-typescript-patched-even-if-i-dont-use-plugnplay) but I will remove the direct requires to `pnpapi` in https://github.com/yarnpkg/berry/pull/3297
