### ISSUE TITLE
[Bug?]: Documentation for YN0019 is misleading

### ISSUE THREAD

**Issue by LaurensUP** [yarnpkg/berry#3285]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

[The documentation for YN0019](https://yarnpkg.com/advanced/error-codes#yn0019---unused_cache_entry) states that 
> Running yarn cache clean will cause Yarn to try to figure out which packages from the cache aren't referenced by the current lockfile.

Which isn't correct. Running `yarn cache clean` simply deletes the `.yarn/cache` folder.

It seems that yarn automatically deletes unused files in the cache folder.
For example, when running `yarn`:
`➤ YN0019: │ uuid-npm-8.3.2-d4172cae56-5575a8a75c.zip appears to be unused - removing`

The information isn't consistent between the docs and the console output.

### To reproduce

``` bash
yarn init
yarn set version berry
yarn add left-pad
```
`➤ YN0013: │ left-pad@npm:1.3.0 can't be found in the cache and will be fetched from the remote registry`

Remove left-pad from `package.json`

``` bash
yarn
```
`➤ YN0019: │ left-pad-npm-1.3.0-0382e69409-13fa96e17b.zip appears to be unused - removing`

### Environment

```

  System:
    OS: Linux 5.11 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Binaries:
    Node: 14.17.1 - /tmp/xfs-66b0f0d8/node
    Yarn: 3.0.0 - /tmp/xfs-66b0f0d8/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm
  npmPackages:
    jest: 27.0.1 => 27.0.1 
```

**Comment by arcanis** [comment]
Indeed, this part of the documentation got written before the 2.0 release, when the behavior was as described. Now it auto-cleans the local cache, and the `yarn cache clean` command just removes everything.

**Comment by Patil2099** [comment]
I would love to take this up.
