### ISSUE TITLE
[Bug?] version plugin: Unsupported option name ("--no-git-tag-version")

### ISSUE THREAD

**Issue by tperraut** [yarnpkg/berry#3286]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

There is no more `--no-git-tag-version` option in version plugin and I did not find any doc with all the available options exclusive to this plugin instead of the old `yarn version` command.

Is it supposed to be implemented ? Not needed anymore ? Something else ?

### To reproduce

```bash
yarn plugin import version
yarn version --no-git-tag-version --new-version 0.0.1
```

### Environment

System:
    OS: macOS 11.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.5 - /private/var/folders/r0/vs06_zl52gb5lqprr2sp5r3c0000gn/T/xfs-fa98ec30/node
    Yarn: 3.0.0 - /private/var/folders/r0/vs06_zl52gb5lqprr2sp5r3c0000gn/T/xfs-fa98ec30/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm

### Additional context

Thank you for your work

**Comment by nweajoseph** [comment]
it doesn't seem like the version plugin currently has any kind of git integration. that is, it doesn't appear to write any commits or tags. just changes your package.json["version"] value
