### ISSUE TITLE
Add new language

### ISSUE THREAD

**Issue by itsnotsaved** [yarnpkg/berry#3296]
Do you still maintain https://crowdin.com/project/yarn?
I sent request through crowdin (https://crowdin.com/messages/) with subject `[Yarn] Add new language` on dec 2020 to @Daniel15 @thejameskyle etc managers but it seems everyone ignored it

**Comment by arcanis** [comment]
No. We rewrote the documentation since then, and we don't have the resources needed to review or maintain translations in languages we don't speak. Non-english translations would quickly become outdated.

**Comment by itsnotsaved** [comment]
@arcanis it might better to rename that project as (deprecated) yarn because i see people keep contribute to it
