### ISSUE TITLE
Prettier SDK reference

### ISSUE THREAD

**Issue by fjavierv** [yarnpkg/berry#3313]
Hi, I was trying to use prettier SDK generated by:

`yarn dlx @yarnpkg/sdks base`

When I execute:

`$> node .yarn/skds/prettier/index.js --help`

It did not print anything on screen, so I tried:

`$> node .yarn/skds/eslinit/bin/eslint.js --help`

In this case it print the help message. Probably the SDK from pettier is not pointing to the correct file. It look like the client is "bin-prettier.js" not "index.js"

https://github.com/prettier/prettier/issues/3709

https://github.com/yarnpkg/berry/blob/8c7522a90d7f2cca8cee6e1ae2e383062bea3fc2/packages/yarnpkg-sdks/sources/sdks/base.ts#L22

Sorry if I have overlooked something. Thanks.

**Comment by ylemkimon** [comment]
The Prettier SDK references the Prettier API, not the CLI. If you need to call the CLI, you can just use `yarn run prettier`.
