### ISSUE TITLE
[Bug?]: "Link step" during install is ~2x slower in Yarn 3 than Yarn 2.4.1

### ISSUE THREAD

**Issue by danoc** [yarnpkg/berry#3314]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Hello, I'm looking to upgrade from Yarn 2.4.1 to 3.0.1 on a project that has ~2.1 GB of `node_modules`.

The project uses the `nodeLinker: node-modules`, `enableGlobalCache: true`, and workspaces (four workspaces with `"hoistingLimits": "workspaces"`).

I'm noticing a ~2x decrease in total install time driven by much higher "Link step" performance.

Here is a comparison of running `yarn install` on this codebase. I ran `yarn install` a few times beforehand to warm the cache.

**Yarn 2:**

| Run | Resolution step | Fetch step | Link step | Total time |
|-----|-----------------|------------|-----------|------------|
| 1   | 0.477s          | 1.008s     | 3.221s    | 5.179s     |
| 2   | 0.519s          | 1.016s     | 3.361s    | 5.378s     |
| 3   | 0.495s          | 1.079s     | 3.349s    | 5.417s     |

**Yarn 3:**

| Run | Resolution step | Fetch step | Link step | Total time |
|-----|-----------------|------------|-----------|------------|
| 1   | 0.469s          | 0.981s     | 9.330s    | 10.994s    |
| 2   | 0.462s          | 0.894s     | 8.969s    | 10.538s    |
| 3   | 0.462s          | 0.916s     | 8.934s    | 10.524s    |

### To reproduce

I created a reproduction that includes Yarn 2.4.1 in one directory and 3.0.1 in another:

https://github.com/danoc/yarn-3-link-step-regression

Reproduction instructions are in the `README.md` file. 

Note: The install times you get in the reproduction will be different than the table above but you should see that "Link step" takes about 2x longer on 3.0.1 than it does on 2.4.1.

### Environment

```
System:
    OS: macOS 11.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
Binaries:
    Node: 12.18.3 - /private/var/folders/<redacted>/node
    Yarn: 2.4.1 - /private/var/folders/<redacted>/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
```

**Comment by arcanis** [comment]
I can reproduce 🤔 I know we made many changes to the nm installs between 2.4 and 3.0, some of them intended to fix edge cases, perhaps one of the fix impacted the link time a bit too much? @larixer

**Comment by larixer** [comment]
The link step takes more time with Yarn 3.x, but its the price for the correctness and better results. You can see this by doing `du -s workspace-a workspace-b workspace-c` in both folders.
1. cd yarn-2.4.1 && du -s workspace-a workspace-b workspace-c
2062968	workspace-a
2063408	workspace-b
2062968	workspace-c
2. cd yarn-3.0.1 && du -s workspace-a workspace-b workspace-c
2061816	workspace-a
2062496	workspace-b
2061744	workspace-c

I agree though, that its a bit too much of a slowdown for the additional correctness and better results. I have tried to optimize it to take less time. With #3320 applied via `yarn set version from sources --branch 3320` to your repro inside 3.x folder, I see the following results:
1. Yarn 2.4.1 total install time: 3s 978ms, link step: 2s 342ms
2. Yarn from sources, total install time: 4s 252ms, link step: 2s 990ms

**Comment by danoc** [comment]
Wow, nice work @larixer! 🙇🏻 Thanks for the PR and thanks @arcanis for reproducing.
