### ISSUE TITLE
BUG - html-to-draftjs tried to access immutable

### ISSUE THREAD

**Issue by BarishSarac** [yarnpkg/berry#3335]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Project that uses this : https://www.npmjs.com/package/html-to-draftjs

**Encountering this error:**

Failed to compile.

./.yarn/__virtual__/html-to-draftjs-virtual-994a1738a8/0/cache/html-to-draftjs-npm-1.5.0-8483e32ca4-b1bab72ed0.zip/node_modules/html-to-draftjs/dist/html-to-draftjs.js
Module not found: html-to-draftjs tried to access immutable (a peer dependency) but it isn't provided by your application; this makes the require call ambiguous and unsound.

### To reproduce

Create a new react app and install https://www.npmjs.com/package/html-to-draftjs 
or sample project I did exactly this is shared here, simply run `yarn` and then `yarn start`
[sample.zip](https://github.com/yarnpkg/berry/files/7034737/sample.zip)

### Environment

System:
  OS: Win10 64BIT
  CPU: i7 4770K
Binaries:
  Node: v14.17.3
  Yarn: 3.0.1
  npm: 7.10.0

**Comment by merceyz** [comment]
`html-to-draftjs` has a peer dependency on `immutable` so you need to install `immutable`.

Could you explain what about the error message wasn't clear about that so we can improve it?

**Comment by BarishSarac** [comment]
I'd add below:
Please install `immutable ` to resolve this issue.

Switching from npm to yarn v2 resulted in being required to install about 10 packages throughout 16 apps I have.
