### ISSUE TITLE
[Bug]: yarn patch-commit generates patches with renames that ZipFS cannot apply

### ISSUE THREAD

**Issue by cspotcode** [yarnpkg/berry#3341]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

`yarn patch-commit` can create patch files with file renames in them.

`ZipFS` does not implement `renameSync`.

So attempting to `yarn patch-commit -s` a patch with a moved file will throw an error:

```
YN0001: │ Error ... : Unimplemented
    at Sr.renameSync
```

https://github.com/yarnpkg/berry/blob/6cbace0ef66e1aed8f63c42f84cab54ebc404117/packages/yarnpkg-fslib/sources/ZipFS.ts#L1024-L1030

Discussed on Discord here: https://discord.com/channels/226791405589233664/654372321225605128/879861862706069515

### To reproduce

Since we already confirmed the source of the bug on Discord, I won't create a running reproduction.

But this pseudocode should reproduce:

```
yarn add lodash
yarn patch lodash
pushd directory-where-it-extracted
mv some-file rename-it
popd
yarn patch-commit -s directory-where-it-extracted
```

### Environment

  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
  Binaries:
    Node: 16.6.2 - /tmp/xfs-78384ad0/node
    Yarn: 3.1.0-rc.1 - /tmp/xfs-78384ad0/yarn
    npm: 7.20.3 - ~/.volta/tools/image/node/16.6.2/bin/npm

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/4557
