### ISSUE TITLE
[Feature] Update plugins when updating the CLI

### ISSUE THREAD

**Issue by merceyz** [yarnpkg/berry#3343]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

When updating the CLI through `yarn set version ...` it's quite easy to forget to update the plugins and run into annoying issues

**Describe the solution you'd like**

Running `yarn set version ...` should update the Yarn plugins just like `yarn set version from sources` does

**Describe the drawbacks of your solution**

More code to maintain

**Describe alternatives you've considered**

Manually updating plugins when updating the CLI

**Comment by mxro** [comment]
While automatically updating the plugins would be great, I think it would also be helpful to just have a better error message in case it is difficult to do the automatic updating.

Currently a generic error such as `Type Error: e.every is not a function` is reported and it would be nicer to have something like `Plugin needs to be upgraded. Please run yarn plugin import [plugin name]`

**Comment by forgetso** [comment]
For other people reading this, the command you need to run is `yarn plugin import workspace-tools`

**Comment by merceyz** [comment]
The plugins are included by default in v4 so this solves itself.
