### ISSUE TITLE
[Bug?]: Yarn link a local package not resolving peerDependencies

### ISSUE THREAD

**Issue by baptisteArno** [yarnpkg/berry#3357]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I'm linking a local package that has a `react` peer dependency. I'm using `yarn link <path>`, it adds the `resolutions` field in the package.json file but it throws `Couldn't resolve "react"`.

It only works if I don't use the link command and setting manually the package as `package-name:file<path>`

### To reproduce

1. Create a local library that uses React
2. Set react package as peerDependency
3. Execute yarn link <path to this package>
4. Import the package
5. See the error

### Environment

yarn v3.0.1

**Comment by merceyz** [comment]
Please provide a full reproduction, your reproduction steps are incomplete / invalid.

`yarn link` doesn't add any dependencies it only overrides existing ones
https://yarnpkg.com/configuration/manifest/#resolutions

**Comment by baptisteArno** [comment]
I ended up using [yalc](https://github.com/wclr/yalc)

**Comment by r1y4h** [comment]
@baptisteArno were you able to use yalc with yarn v2 PnP? We are using yalc but it seems to intermittently fail when publishing after implementing yarn v2 PnP.
