### ISSUE TITLE
[Feature] Allow editing of patches after creation

### ISSUE THREAD

**Issue by RDIL** [yarnpkg/berry#3358]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [X] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

Yarnpkg plugin patch is great, but there is one thing that I need in order to migrate my project to it.
We have several patches that need to be updated semi-frequently, but it seems that the patch plugin doesn't allow you to modify the code after the first patch is created.  Every time you run `yarn patch`, it creates a temp folder with the package's original contents, not the contents that a previously-made patch dictates.  This would be super helpful, and I would really appreciate this feature being added.

**Describe the solution you'd like**

Either have the patch plugin apply the patch to the source code in the temp folder, or have a flag that does this.

**Describe the drawbacks of your solution**

Not sure of any really, but open to criticism if anybody has some.

**Describe alternatives you've considered**

This is a feature for the patch plugin itself, so I feel like it would be redundant to make a plugin for this plugin!

Thanks in advance!

**Comment by merceyz** [comment]
This was implemented in https://github.com/yarnpkg/berry/pull/4218
