### ISSUE TITLE
[Bug?]: Should be rebuilt after node version changes

### ISSUE THREAD

**Issue by cuyl** [yarnpkg/berry#3381]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

All binary should be rebuilt after the node version is changed

### To reproduce

```bash
$ nvm use 16
$ yarn add canvas
$ yarn node -e "require('canvas')"
$ echo $?
0
$ nvm use 12
$ yarn rebuild canvas
➤ YN0000: ┌ Link step
➤ YN0007: │ canvas@npm:2.8.0 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 0s 794ms
➤ YN0000: Done with warnings in 7s 253ms
$ yarn node -e "require('canvas')"
Error: The module '/Users/yuchao/Playgrounds/yarn-v3-test/.yarn/unplugged/canvas-npm-2.8.0-b8a304d4de/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.external_module_.Module._load (/Users/yuchao/Playgrounds/yarn-v3-test/.pnp.cjs:28198:14)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18) {
  code: 'ERR_DLOPEN_FAILED'
}
$ echo $?
1
rm -rf /Users/yuchao/Playgrounds/yarn-v3-test/.yarn/unplugged/canvas-npm-2.8.0-b8a304d4de
$ yarn rebuild canvas
$ yarn node -e "require('canvas')"
$ echo $?
0
```

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries12:
    Node: 12.22.5 - /private/var/folders/x9/m_y2fpmn1wgcd33f1y0tdhgr0000gq/T/xfs-4176eca1/node
    Yarn: 3.0.1 - /private/var/folders/x9/m_y2fpmn1wgcd33f1y0tdhgr0000gq/T/xfs-4176eca1/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v12.22.5/bin/npm
  Binaries16:
    Node: 16.8.0 - /private/var/folders/x9/m_y2fpmn1wgcd33f1y0tdhgr0000gq/T/xfs-df11ae61/node
    Yarn: 3.0.1 - /private/var/folders/x9/m_y2fpmn1wgcd33f1y0tdhgr0000gq/T/xfs-df11ae61/yarn
    npm: 7.21.0 - ~/.nvm/versions/node/v16.8.0/bin/npm

**Comment by cuyl** [comment]
Maybe calculate hash include node major version or add an argument to `yarn rebuild` like  `yarn rebuild --force canvas `

**Comment by merceyz** [comment]
We already rebuild when the Node version changes but rebuild just means re-running the `postinstall` scripts
https://github.com/yarnpkg/berry/blob/d13213280191f064785cf0bc19c92c76c60581bd/packages/yarnpkg-core/sources/Project.ts#L1143

**Comment by cuyl** [comment]
> We already rebuild when the Node version changes but rebuild just means re-running the `postinstall` scripts
> https://github.com/yarnpkg/berry/blob/d13213280191f064785cf0bc19c92c76c60581bd/packages/yarnpkg-core/sources/Project.ts#L1143

Sorry, I didn't see this code, but why `yarn rebuild` not work correctly?

**Comment by cuyl** [comment]
Or, how to rebuild the binary package after the node version is changed?

**Comment by arcanis** [comment]
It is rebuilt; that's what Yarn tells you here:

```
➤ YN0007: │ canvas@npm:2.8.0 must be built because it never has been before or the last one failed
```

It's possible that the `canvas` postinstall bailouts if it sees existing binaries, but that's not something we can do anything about.

**Comment by cuyl** [comment]
@arcanis  Thanks you are right.

**Comment by olivierlacan** [comment]
@arcanis This message is confusing. Is it saying the package *had to be built* and *was built*? Because that's not what this sentence says: 

>  YN0007: │ husky@npm:4.3.8 must be built because it never has been before or the last one failed

This feels like a soft error when it should be written as a note: 

>  YN0007: │ husky@npm:4.3.8 had to be built because it never been or previously failed to build

Let me know if you'll accept a PR to change this wording to avert confusion.
