### ISSUE TITLE
[Bug] Cannot install when the version number of the specified package includes `v`

### ISSUE THREAD

**Issue by XYShaoKang** [yarnpkg/berry#340]
**Describe the bug**

There was an error installing `axios@v0.19.0-beta.1`

**To Reproduce**

```sh
yarn add axios@v0.19.0-beta.1
```

stdout:

```sh
➤ YN0000: ┌ Resolution step
➤ YN0016: │ axios@npm:v0.19.0-beta.1: Registry failed to return reference "v0.19.0-beta.1"
➤ YN0000: └ Completed in 0.43s
➤ YN0000: Failed with errors in 0.44s
```

**Screenshots**

**Environment if relevant (please complete the following information):**

- OS: Window 10
- Node version v10.15.3
- Yarn version v2.0.0

**Additional context**

An error occurred while installing `@expo/xdl@55.0.14`.The error occurred in `axios@v0.19.0-beta.1` on which `@expo/xdl@55.0.14` depends.

When `npm@6.4.1` or `yarn@1.17.3` is used to install `axios@v0.19.0-beta.1`, it can be installed normally.

**Comment by arcanis** [comment]
I understand why - the `version` [here](https://github.com/yarnpkg/berry/blob/master/packages/plugin-npm/sources/NpmSemverResolver.ts#L67) must be cleaned with `semver.clean` 🤔
