### ISSUE TITLE
[Bug]: yarnpack doesn't create useful default name

### ISSUE THREAD

**Issue by rbirkgit** [yarnpkg/berry#3411]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

With yarn 1.x and yarn pack the defualt file name used the name/version from the package.json file. Now I have to manually add the long name to each package. It's very annoying. This also doesn't work well in our scripts that created multiple packages.

I tried using `yarn pack -o %s-v%v.tgz` which is still annoying but was hoping it would work, but this creates a file starting with @ (where yarn 1.x skipped the initial @). 

Why can't we have the defualt name like it was in yarn 1.x? so we can still use it. If that is not an option, at least provide a variable for 1.x default naming, e.g. %l (for legacy name)

### To reproduce

yarn pack

### Environment

windows 10

**Comment by arcanis** [comment]
> Why can't we have the defualt name like it was in yarn 1.x? so we can still use it. If that is not an option, at least provide a variable for 1.x default naming, e.g. %l (for legacy name)

Because the old default name was non-predictable, making it a little more difficult to use with scripts - which is the main use case for using `yarn pack` from the CLI.

> If that is not an option, at least provide a variable for 1.x default naming, e.g. %l (for legacy name)

I'm not sure there's a lot of value in adding another variable to do exactly the same thing as another, minus a `@` 🤔

**Comment by rbirkgit** [comment]
You are right. Let's close this then.
