### ISSUE TITLE
[Bug]: Allow yarn npm publish to use created tar file from yarn pack

### ISSUE THREAD

**Issue by rbirkgit** [yarnpkg/berry#3412]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

There is no way to publish the package created from yarn pack

In yarn 1.x you just types yarn publish xxx.tgz

I cannot tell if --ignore-scripts is supported.  Need to try some more.

### To reproduce

yarn pack
yarn npm publish package.tgz

### Environment

windows 10

**Comment by arcanis** [comment]
> There is no way to publish the package created from yarn pack

That's not a bug though. Please don't report enhancement requests as bugs (especially since bugs without repros will be auto-closed, so it doesn't benefit you either).

More to the point, cf https://github.com/yarnpkg/berry/pull/1692#issuecomment-672356240

**Comment by rbirkgit** [comment]
ok. Opened a feature request instead. Thanks!
