### ISSUE TITLE
[Bug?]: YAMLException: bad indentation of a mapping entry at line

### ISSUE THREAD

**Issue by Jarmos-san** [yarnpkg/berry#3416]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

Trying install package or importing a plugin through the commands `yarn install & `yarn plugin import typescript` throws the following error:

```console
YAMLException: bad indentation of a mapping entry at line 4, column 15:
      dependencies:
                  ^
      dependencies:
                  ^
    at Bq (E:\Projects\frontend\blog\.yarn\releases\yarn-3.0.2.cjs:24:789)
    at $e (E:\Projects\frontend\blog\.yarn\releases\yarn-3.0.2.cjs:24:891)
    at ABe (E:\Projects\frontend\blog\.yarn\releases\yarn-3.0.2.cjs:31:1922)
    at Dc (E:\Projects\frontend\blog\.yarn\releases\yarn-3.0.2.cjs:31:4422)
    at gBe (E:\Projects\frontend\blog\.yarn\releases\yarn-3.0.2.cjs:31:6569)
    at Dq (E:\Projects\frontend\blog\.yarn\releases\yarn-3.0.2.cjs:32:260)
    at xq (E:\Projects\frontend\blog\.yarn\releases\yarn-3.0.2.cjs:32:481)
    at hBe (E:\Projects\frontend\blog\.yarn\releases\yarn-3.0.2.cjs:32:759)
    at twe (E:\Projects\frontend\blog\.yarn\releases\yarn-3.0.2.cjs:255:142)
    at Kr (E:\Projects\frontend\blog\.yarn\releases\yarn-3.0.2.cjs:255:490)
```

### To reproduce

Follow the steps provide in the [migration guide](https://yarnpkg.com/getting-started/migration) & then try to "_install_" the list of packages or "_import_" a plugin. And it throws the error mentioned above.

### Environment
```
  System:
    OS: Windows 10 10.0.19043
    CPU: (2) x64 Intel(R) Pentium(R) CPU G3220 @ 3.00GHz
  Binaries:
    Node: 16.7.0 - ~\AppData\Local\Temp\xfs-0697d3cd\node.CMD
    Yarn: 3.0.2 - ~\AppData\Local\Temp\xfs-0697d3cd\yarn.CMD
    npm: 7.19.1 - C:\Program Files\nodejs\npm.CMD
```
### Additional context

Screenshot attached for further reference:

![image](https://user-images.githubusercontent.com/31373860/132830670-809b70af-38f7-46c4-b19b-9e52366df691.png)

**Comment by merceyz** [comment]
Your YAML is malformed, not much we can do about that. If you believe that it's a bug in the parser please provide a full reproduction containing the YAML file

**Comment by Jarmos-san** [comment]
> Your YAML is malformed, not much we can do about that.

Which specific YAML file are we talking about here? I tried looking around for it myself & couldn't figure out which YAML file(s) is causing this issue.

Not sure if it's relevant, but regardless here're the contents of the `.yarnrc.yml` file:

```yaml
yarnPath: .yarn/releases/yarn-berry.cjs

nodeLinker: node-modules
```

Do let me know if there's something I missed out on and/or if I need to provide further information?

**Comment by merceyz** [comment]
The `yarn.lock` file is probably the YAML file in question here

**Comment by Jarmos-san** [comment]
> The `yarn.lock` file is probably the YAML file in question here

That would be weird because I **never** touch the `yarn.lock` file for any reason. Are there any other reason for this issue? Knowing that much can help me debug this issue a bit further.

**Comment by Jarmos-san** [comment]
Tried debugging this concern further but the UX of the application lacks detailed error messages. It crashes with an ambiguous message & the feedback from the maintainers hasn't been fruitful either.

Removing the following files and folders:

- `.yarn`
- `.yarnrc.yml`
- `yarn.lock`
- `node_modules`

... and then following the installation steps as follows:

1. Run `yarn set version berry` to download the latest version of Yarn & initialize the local repo with it's configurations.
2. Install the dependencies (_and the plugins if needed_) with the `yarn install` command. Optionally, the `yarn plugin import <PLUGIN-NAME>` installs any require plugin as well.
3. Run `yarn dev` to check if everything's working properly.

... **fixed the issue**. But it's possible the bug could pop-out again inconsistently, if not resolved some day.

Possible suspects for such an issue to pop-out again some day are as follows:

- Inconsistent line-endings (_like CRLF instead of LF_) when a config file has been `curl`'ed.
- For whatever reason the `yarn.lock` file was formatted as mentioned in a comment above. But tbh there's no reason for anyone in their right mind to edit that file for whatever reason.

That said, closing this issue due to lack of interest & reproducible behaviour.

**Comment by kahboom** [comment]
Just in case anyone else ends up with this same problem, this happened to me after merging in a Dependabot PR. I deleted the `yarn.lock` file that I did not modify myself (nor would), and ran `yarn install` again, and that fixed the issue.

Just seems a bit odd considering there was definitely no merge conflict reported or I wouldn't have even been able to merge the PR.. strange times.

**Comment by shishkin** [comment]
> ... this keeps happening to to me after merging in Dependabot PRs.

Apparently, [Dependabot doesn't support yarn v2 & v3](https://github.com/dependabot/dependabot-core/issues/1297).

**Comment by gabbarSan** [comment]
I had the similar issue and here is how i got it resolved: Check the "whitespaces" in the YMAL file. The indentation should be done with "spaces" and not "tabs". 

"whitespaces" can be switched on in any text editor. e.g. in VS code the "whitespaces" can be turned on by: "_In the search bar on the settings page, search for Render Whitespace and with the dropdown that appears select all , this will then show all whitespace characters._ "

**Comment by Teguimene** [comment]
> The `yarn.lock` file is probably the YAML file in question here

Good, thank you  !
