### ISSUE TITLE
[Feature] `yarn install --production` (like yarn v1)

### ISSUE THREAD

**Issue by aladdin-add** [yarnpkg/berry#3435]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

yarn: 3.0.0-rc.2.git.20210523.hash-664cc40d

we are working on a non-monorepo, and want to install all deps, but not dev deps.
I've noticed the docs: 

> yarn workspaces focus....If the -A,--all flag is set, the entire project will be installed. Combine with --production to replicate the old yarn install --production.

but it does not make sense to install the workspace plugin, as we are not using yarn workspaces.

**Describe the solution you'd like**

just bring back `yarn install --production`(like yarn v1)

**Describe the drawbacks of your solution**

I didn't see the drawback for users, more maintenance burden?

**Describe alternatives you've considered**

not sure.

**Comment by arcanis** [comment]
You are using workspaces. Even a project without explicit workspaces has at least one workspace: the root. We won't duplicate the code in `install`.

**Comment by aladdin-add** [comment]
In this way, the workspace plugin should be built-in. :)
