### ISSUE TITLE
[Bug?]: Does not upgrate to 3.0.2

### ISSUE THREAD

**Issue by D4nte** [yarnpkg/berry#3436]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Trying to upgrade to yarn 3.0.2 to get this fix: https://github.com/yarnpkg/berry/issues/3350

However it does not help as I still get `yarn@3.0.1`.

### To reproduce

```                     9m ✖ ⚑ ◒  ⍉
▶ yarn set version berry && yarn
➤ YN0000: Retrieving https://repo.yarnpkg.com/3.0.2/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in ../../.yarn/releases/yarn-3.0.2.cjs
➤ YN0000: Done in 0s 502ms
➤ YN0000: ┌ Resolution step
➤ YN0002: │ dns-over-http-resolver@npm:1.2.3 doesn't provide node-fetch (p89343), requested by native-fetch
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 338ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 0s 604ms

▶ yarn --version
3.0.1
```

Error https://github.com/yarnpkg/berry/issues/3350 still occurs too (fixed by downgrading to TS 4.3).

### Environment

```shell
System:
- Linux 5.10.61-1-MANJARO #1 SMP PREEMPT Thu Aug 26 20:36:54 UTC 2021 x86_64 GNU/Linux
Binaries:
- Node: /home/froyer/.nvm/versions/node/v14.17.5/bin/node
- Yarn ? (that's the issue)
```

**Comment by merceyz** [comment]
Check if you have any `.yarnrc.yml` files higher up the file tree that specifies a different version, specifically your home directory.

**Comment by D4nte** [comment]
Yeay, thanks. I did have a rogue `.yarnrc.yml` file in a folder above, I must have run a `yarn` command at the wrong location at some point. Problem solved.
