### ISSUE TITLE
[Bug] Yarn v2 requires bash to be installed

### ISSUE THREAD

**Issue by accidentaldeveloper** [yarnpkg/berry#345]
**Describe the bug**

Running yarn v2 in an environment without bash causes a failure with the error message:

`env: can't execute 'bash': No such file or directory`

**To Reproduce**

Run a node app with Yarn v2 in an environment that does not have bash available. (I discovered this while running a CI job with the _node:10.15.1-alpine_ docker image)

The original error is in a private repo but I can create an example project and CI job if desired.

**Environment if relevant (please complete the following information):**

 - OS: Linux
 - Node version: 10.15.1
 - Yarn version: 2.0.0

**Comment by accidentaldeveloper** [comment]
This may be expected behavior but the job did run without error using Yarn v1. I'm not sure what level of compatibility you want to maintain.

**Comment by arcanis** [comment]
Thanks for the report! It's definitely not expected, but right now I don't have enough information to make an educated guess as to what might happen. If you can make a minimal repro it would be awesome. The most important would be:

- Which command is run? 
- Which packages are installed?

**Comment by accidentaldeveloper** [comment]
Minimal repro created: 
https://gitlab.com/probackpacker/minimal-yarn-v2-app/-/jobs/270013509

Pipeline runs without error using Yarn v1. Upgrade to Yarn v2. Pipeline fails. 
The only package that is installed is _axios_.
If the script is [executed with node directly](https://gitlab.com/probackpacker/minimal-yarn-v2-app/-/jobs/270013273) (instead of `yarn run`) the error is 

> Error: Cannot find module 'axios'

instead

**Comment by accidentaldeveloper** [comment]
When I was debugging earlier I found this line and suspect that it may have something to do with the issue:
https://gitlab.com/probackpacker/minimal-yarn-v2-app/blob/master/.yarn/releases/yarn-berry.js?expanded=true&viewer=simple#L11349

**Comment by accidentaldeveloper** [comment]
One more follow-up: moving from the alpine image to the standard image resolves the error: https://gitlab.com/probackpacker/minimal-yarn-v2-app/-/jobs/270032884

**Comment by vlasenko** [comment]
More context. The source code line that uses `bash` is here:
https://github.com/yarnpkg/berry/blob/c3eafa10b64a80dafa17722d8b0e46b4aa652f5e/packages/berry-core/sources/scriptUtils.ts#L19

The `spawn` uses `/bin/sh` to launch shell on Unix:
https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

**Comment by accidentaldeveloper** [comment]
Thanks for fixing this! Once it's released, how do I get the new version in my project?

**Comment by arcanis** [comment]
Sorry, forgot to answer 😅 @accidentaldeveloper at the moment you need to clone the repo and build a bundle yourself, but I'll soon merge a fix that will allow you to just run `yarn set version from sources` and it'll clone / build it without you having to do anything.
