### ISSUE TITLE
[Feature] support for --expose-gc in `yarn run`

### ISSUE THREAD

**Issue by mikaelkolkinn** [yarnpkg/berry#3470]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

I want to be able to expose the Node garbage collector to the JavaScript code i run with Node.
This can be done by sending the flag `--expose-gc` to node. In our particular case we want to use it when running our Jest test suite, which can use a lot of memory due to its test isolation functionality (https://chanind.github.io/javascript/2019/10/12/jest-tests-memory-leak.html). But there are other purposes where using this flag would be advantageous, like debugging memory usage.

I have tried using `NODE_OPTIONS='--expose-gc' yarn run -B jest ...` but unfortunately this is one of the v8 options that is not allowed in NODE_OPTIONS, returning the following error message:
> --expose-gc is not allowed in NODE_OPTIONS

**Describe the solution you'd like**

Since the --inspect and --inspect-brk already exist in `yarn run` (#978), it feels natural to me to have a --expose-gc flag there as well. This would be my proposed solution.

**Describe the drawbacks of your solution**

There might be several such Node flags that are not allowed in NODE_OPTIONS. Over time more of these might be requested added to Yarn, which could lead to having to maintain an uncomfortable number of Node flags in the Yarn code. Maybe some of these even change name and/or implementation with different versions of Node, which would be difficult to maintain.

**Describe alternatives you've considered**

As for why not making a plugin, the short answer is I have no idea how to make such a plugin. It seems that running Node is a deeply integrated part of Yarn, and I'm unsure if these inner workings can be
 manipulated sufficiently through a plugin. If it is possible I'm all ears.

One option is running Node directly like `yarn node --expose-gc node_modules/jest/bin/jest.js ...` instead, although pointing to a file in node_modules seems wrong and probably wouldn't be possible when not using `nodeLinker: node-modules`.

Another possible solution to lessen the aformentioned drawbacks, could be to allow any flags to be passed through to Node like `yarn run --node-options "--expose-gc --some-other-flag" ...`.

**Comment by merceyz** [comment]
> One option is running Node directly like yarn node --expose-gc node_modules/jest/bin/jest.js ... instead, although pointing to a file in node_modules seems wrong and probably wouldn't be possible when not using nodeLinker: node-modules.

For that case you would use `yarn bin` to get the path to `jest` and pass that to `yarn node`
```sh
yarn node --expose-gc $(yarn bin jest) ...
```

**Comment by mikaelkolkinn** [comment]
> For that case you would use `yarn bin` to get the path to `jest` and pass that to `yarn node`
> 
> ```shell
> yarn node --expose-gc $(yarn bin jest) ...
> ```

That might just work. Thank you @merceyz!

**Comment by ivands** [comment]
+1
I also need this feature.

```shell
yarn node --expose-gc $(yarn bin jest) ...
```
this isn't working for me.
