### ISSUE TITLE
[Bug?]: yarn patch-commit -s option throwing error with normal usage

### ISSUE THREAD

**Issue by LaurensUP** [yarnpkg/berry#3477]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Using `yarn patch-commit` as documented [here](https://yarnpkg.com/features/protocols/#patch) (using the `-s` option) throws an error.

### To reproduce

`yarn patch <package>`
- Edit the files.
- Use the `-s` option:
`yarn patch-commit /tmp/xfs-d77894fe/user -s patchfile`

Output:
`Unknown Syntax Error: Extraneous positional argument ("patchfile").`

### Environment

```shell
System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 14.17.6 - /tmp/xfs-72d48d26/node
    Yarn: 3.0.0 - /tmp/xfs-72d48d26/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  npmPackages:
    jest: 27.0.1 => 27.0.1
```

### Additional context

Documentation [here](https://yarnpkg.com/cli/patch) is outdated:

> This command will cause a package to be extracted in a temporary directory (under a folder named "patch-workdir"). This folder will be editable at will; **running yarn patch inside it** will then cause Yarn to generate a patchfile and register it into your top-level manifest (cf the patch: protocol).
-> You have to run `yarn patch-commit` in the source repository, not in the generated folder

Workaround is generating the package by using
`yarn patch-commit /tmp/xfs-d77894fe/user > patchfile`

**Comment by arcanis** [comment]
Check your command line. You're passing two paths.

**Comment by LaurensUP** [comment]
Oh, so yarn just remembers which `patch` you are doing?
It's a little confusing that `yarn patch-commit <dir>` needs to specify which patch, but `yarn patch-commit -s <file>` does not.

Anyway, I got everything working yesterday and definitely want to thank you and other contributors because this feature with the patch protocol is damn amazing! Loving how elegant it is.
