### ISSUE TITLE
[Bug?]: An unexpected error occurred: "Release not found: 2.4.2".

### ISSUE THREAD

**Issue by pravi** [yarnpkg/berry#3496]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

With nodejs 10, yarn set version 2.4.2 no longer works and yarn set version berry is not possible as minimum supported version of nodejs is 12 for berry.

### To reproduce

the bug is with yarn itself

### Environment

```shell
Debian 10 buster with nodejs 10
```

### Additional context

https://github.com/yarnpkg/berry/issues/3221#issuecomment-927183491

**Comment by enote-kane** [comment]
One-liner to reproduce:
```bash
mkdir test-project && ( cd test-project && yarn set version 2.4.2 ); rm -rf test-project
```

**Comment by pravi** [comment]
@arcanis 
> On an unrelated note, would you be available by mail / Discord ? I'd like to find a solution to the yarn binary name kerfuffle on Debian, as Node.js recently shipped with a yarn binary, which is currently opt-in but which we'd like to make opt-out in a future major release.

As you commented here, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913997 the current maintainer is Antonio, so he has to decide.

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/yarn/commit/63cf0ac1190b3490ce2a64fd07e6210fe4bf234b / v1.22.12
