### ISSUE TITLE
[Feature] Add documentation for upgrading your version of yarn v2

### ISSUE THREAD

**Issue by accidentaldeveloper** [yarnpkg/berry#350]
- [x] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

I've upgraded my project to v2 but new changes have been made to the code. I want to upgrade my project to use the latest version but I can't find documentation around this.

**Describe the solution you'd like**

The v2 installation page contains details about upgrading to the latest yarn v2 release.

**Describe the drawbacks of your solution**

Can't think of any yet.

**Describe alternatives you've considered**

Perhaps this already happens automatically? If so, that should be documented as well.

**Comment by arcanis** [comment]
A PR being merged into master doesn't make it available instantly - a core maintainer still need to manually update the checked-in bundle for the code to then become available to any user running the following command:

```
yarn set version v2
```

I'm working on making it possible to use `master` if needed by cloning the repository and building the sources locally, which would be done in a single command:

```
yarn set version from sources
```

**Comment by accidentaldeveloper** [comment]
Okay. Let me make sure that I understand. 

To upgrade a project from v1 to v2 you run 

`yarn policies set-version v2`

To get the latest release of v2 you run 

`yarn set version v2`

Is that correct?

**Comment by arcanis** [comment]
Yep. Note that the first form will be valid in the v2 as well, to help with the transition 🙂

**Comment by vlasenko** [comment]
@arcanis What about upgrading plugins, is any support available? Are there any ideas how this should be done?

**Comment by arcanis** [comment]
For plugins you'd use `yarn plugin dl` with the url, just like when you installed it. I guess we could offer plugins to provide their own "update url" so that a command like `yarn plugin upgrade-all` would redownload all the currently installed plugins 🤔
