### ISSUE TITLE
[Bug?]: `yarn workspaces foreach --parallel` swallows logs

### ISSUE THREAD

**Issue by FezVrasta** [yarnpkg/berry#3503]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I'm running this command:

```
yarn workspaces foreach --parallel --from '@srna/{frontend,graphql}' run start
```

In order to execute a `create-react-app` and an Apollo servers at the same time.

The problem is that when I add the `--parallel` flag the logs are not printed to the terminal, I can see them only after I CTRL-C.

If I remove the parallel flag they are printed correctly.

### To reproduce

N/A

### Environment

```shell
➤ YN0001: Error: ENOENT: no such file or directory, open '/private/var/folders/dm/r2yzz3ws2zxbpbmrg58q5mr00000gn/T/xfs-dd731c71/dlx-60643/.yarn/yarn.lock'
➤ YN0000: Failed with errors in 0s 48ms
```

### Additional context

`yarn dlx -q envinfo --preset jest` is failing for some reason.

**Comment by merceyz** [comment]
This is expected, see https://yarnpkg.com/cli/workspaces/foreach#options-i%2C-interlaced

```
-i,--interlaced | Print the output of commands in real-time instead of buffering it
```
