### ISSUE TITLE
the export button of the playground does not work

### ISSUE THREAD

**Issue by stof** [yarnpkg/berry#3510]
1. Create a reproducing case in the playground
2. Click the `Export` button to export it

The clipboard contains `404: Not found`, which is not helpful as issue content.

Looking at the devtools, I see 404 errors on https://raw.githubusercontent.com/yarnpkg/berry/master/.github/ISSUE_TEMPLATE/bug-report.md
So this is probably caused by the migration to issue forms.

**Comment by merceyz** [comment]
Duplicate of https://github.com/yarnpkg/berry/issues/3127
