### ISSUE TITLE
[Bug]: Go-to Definition fails in VSCode 1.61

### ISSUE THREAD

**Issue by YXL76** [yarnpkg/berry#3539]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

After updating vscode to 1.61.0, the go-to definition gets error.

`Unable to open 'fs.d.ts': Unable to read file '/^zip:/home/yxl/yarn-zipfs-bug/.yarn/cache/@types-node-npm-16.10.3-ae1d2f8739-3fd429bce8.zip/node_modules/@types/node/fs.d.ts' (Error: Unable to resolve nonexistent file '/^zip:/home/yxl/yarn-zipfs-bug/.yarn/cache/@types-node-npm-16.10.3-ae1d2f8739-3fd429bce8.zip/node_modules/@types/node/fs.d.ts').`

### To reproduce

I create a repo for this:
[yarn-zipfs-bug](https://github.com/YXL76/yarn-zipfs-bug)

### Environment

```shell
System:
  OS: Linux 5.14 Arch Linux
  CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Binaries:
  Node: 14.17.4 - /tmp/xfs-62e53485/node
  Yarn: 3.1.0-rc.8 - /tmp/xfs-62e53485/yarn
  npm: 7.24.2 - /usr/bin/npm
```

**Comment by wlewis-formative** [comment]
Thanks, @arcanis! In the mean time, the August 2021 release of VSCode is working for me: https://code.visualstudio.com/updates/v1_60.

**Comment by bradennapier** [comment]
It doesnt seem to work - every time i run it, it says it updated to the vscode version but clearly it doesnt because running again yields same resul tand zipfs doesn twork?
