### ISSUE TITLE
[Bug?]: ESLint extension doesn't work with yarn pnp - Error: Missing "./lib/api.js" export in "eslint" package

### ISSUE THREAD

**Issue by mr-bjerre** [yarnpkg/berry#3578]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I'm using the ESLint extension in VSCode. Unfortunately it doesn't work with Plug'n'Play - according to the docs it should work if I understand correctly?

I've been looking at issues both here and in the ESLint extension repro but I haven't found anyone with this exact error it seems. I'm not sure if the issue belongs here or in the ESLint extension repro, let me know.

### To reproduce

Make sure you have [arcanis.vscode-zipfs](https://marketplace.visualstudio.com/items?itemName=arcanis.vscode-zipfs) and [dbaeumer.vscode-eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) extensions installed in VS Code.

Run the following commands and just select defaults in the config initialization wizard

```bash
mkdir eslint-test
cd eslint-test
yarn set version berry
yarn init
yarn add -D eslint
yarn dlx @yarnpkg/sdks vscode
yarn eslint --init
```

Now verify that eslint will highlight an error in `.eslintrc.js` when running the following command (as expected)

```bash
yarn eslint .
```

Open `eslintrc.js` in VS Code and verify that the ESLint extension doesn't work. You can select the `Output` tab and select `ESLint` in the dropdown and see the following error

```bash
[Error - 2:16:22 PM] Error: Missing "./lib/api.js" export in "eslint" package
Require stack:
- /home/nixd/Projects/eslint-test/.pnp.cjs
    at bail (/home/nixd/Projects/eslint-test/.pnp.cjs:10700:8)
    at resolve (/home/nixd/Projects/eslint-test/.pnp.cjs:10776:10)
    at applyNodeExportsResolution (/home/nixd/Projects/eslint-test/.pnp.cjs:11027:28)
    at resolveUnqualifiedExport (/home/nixd/Projects/eslint-test/.pnp.cjs:11540:35)
    at resolveRequest (/home/nixd/Projects/eslint-test/.pnp.cjs:11606:99)
    at Object.resolveRequest (/home/nixd/Projects/eslint-test/.pnp.cjs:11681:26)
    at Function.external_module_.Module._resolveFilename (/home/nixd/Projects/eslint-test/.pnp.cjs:10533:34)
    at Function.external_module_.Module._load (/home/nixd/Projects/eslint-test/.pnp.cjs:10355:48)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
[Error - 2:20:20 PM] Error: Missing "./lib/api.js" export in "eslint" package
```

### Environment

```shell
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
  Binaries:
    Node: 15.14.0 - /tmp/xfs-affdb263/node
    Yarn: 3.0.2 - /tmp/xfs-affdb263/yarn
    npm: 7.24.1 - ~/.nvm/versions/node/v15.14.0/bin/npm
```

**Comment by mr-bjerre** [comment]
Cool @joelmukuthu . 

I agree that the workaround doesn't throw the error anymore but the extension doesn't seem to highlight any issues either. So it isn't really working...

**Comment by mr-bjerre** [comment]
I think it might be because don't have `.yarn` in my root directory actually.

**Comment by vinassefranche** [comment]
Hello! I see this has the label `good first issue` I'd be willing to work on it to understand better how this work and help fix this issue. I have no idea how the sdk code is generated though. Is there any documentation available to start looking at this on my own? Are there any hint on where to start digging?

Thanks in advance for your answers!

**Comment by merceyz** [comment]
This was fixed in https://github.com/yarnpkg/berry/pull/3709 but we forgot to close it
```sh
yarn dlx @yarnpkg/sdks
```

**Comment by vinassefranche** [comment]
@merceyz thanks for the info! Don't hesitate to ping me if you see something I can help on!
