### ISSUE TITLE
[Bug]: Possible breaking change introduced in #3284 in constraints plugin

### ISSUE THREAD

**Issue by paul-soporan** [yarnpkg/berry#3584]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

https://github.com/yarnpkg/berry/pull/3284#issuecomment-945132346 (cc @nicolo-ribaudo)

I haven't investigated it yet.

### To reproduce

Copied from that comment (I can repro it too):

> I think that this is a breaking change. To reproduce:
> - Clone https://github.com/babel/babel
> - Verify that `yarn constraints` passes
> - Update the plugin to 3.1.0-rc.10: `yarn plugin import https://github.com/yarnpkg/berry/raw/@yarnpkg/cli/3.1.0-rc.10/packages/plugin-constraints/bin/%40yarnpkg/plugin-constraints.js`
> - `yarn constraints` reports a ton of failures

### Environment

```shell
System:
    OS: Linux 5.14 Arch Linux
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
  Binaries:
    Node: 16.8.0 - /tmp/xfs-fe880b95/node
    Yarn: 3.0.2 - /tmp/xfs-fe880b95/yarn
    npm: 7.24.2 - ~/.nvm/versions/node/v16.8.0/bin/npm
```

**Comment by noahnu** [comment]
I meant to create a github issue, completely forgot. Noted a breaking change in this thread in the discord channel a while back: https://discord.com/channels/226791405589233664/887436751830933566/887453024803512333

**Comment by paul-soporan** [comment]
Ah, I missed that ping.
