### ISSUE TITLE
[Bug?]: node17 compat: │ Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close

### ISSUE THREAD

**Issue by aladdin-add** [yarnpkg/berry#3597]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Fetch step
  ➤ YN0001: │ Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
      at new NodeError (node:internal/errors:371:5)
      at PassThrough.onclose (node:internal/streams/end-of-stream:122:30)
      at PassThrough.emit (node:events:390:28)
      at emitCloseNT (node:internal/streams/destroy:145:10)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)

### To reproduce

https://github.com/weiran-zsd/dts-cli/runs/3947685268

### Environment

```shell
os: ubuntu-latest
Node.js: v17.0.0
yarn: v3.0.2
```

**Comment by Dragon1573** [comment]
@patdx & @aladdin-add , I'm currently facing the same problem. 

Should I downgrade my *Node.js* to LTS `v16.x` version? Thank you! ❤️

## 🔧 Self-Service

- [ ] I'd be willing to implement a fix

## 📜 Describe the bug

Error logs are as follows:

```log
(base) Study-Notes on main ● λ yarn add -D vuepress-theme-vdoing
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @vue/babel-plugin-jsx@npm:1.0.7 doesn't provide @babel/core (pa6c52), requested by @babel/plugin-syntax-jsx
➤ YN0002: │ @vuepress/core@npm:1.8.2 doesn't provide @vue/compiler-sfc (p4c8a9), requested by vue-loader
➤ YN0002: │ study-notes@workspace:. doesn't provide chalk (p75ef5), requested by vuepress-plugin-sitemap
➤ YN0002: │ study-notes@workspace:. doesn't provide commander (p17913), requested by vuepress-plugin-sitemap
➤ YN0002: │ study-notes@workspace:. doesn't provide esm (p844b2), requested by vuepress-plugin-sitemap
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 873ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ @better-scroll/core@npm:2.4.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ @better-scroll/shared-utils@npm:2.4.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ @better-scroll/slide@npm:2.4.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ good-storage@npm:1.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ vuepress-theme-vdoing@npm:1.8.5 can't be found in the cache and will be fetched from the remote registry
➤ YN0001: │ Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:371:5)
    at PassThrough.onclose (node:internal/streams/end-of-stream:122:30)
    at PassThrough.emit (node:events:390:28)
    at emitCloseNT (node:internal/streams/destroy:145:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
➤ YN0000: └ Completed in 0s 726ms
➤ YN0000: Failed with errors in 1s 603ms
```

## 🎯 To reproduce

```bash
yarn add -D vuepress-theme-vdoing
```

## 🖥️ Environment

- Operating System
  - Name: Microsoft Windows 10 Professional (zh-CN)
  - Version: 10.0.19043 N/A Build 19043
  - Build Type: Multiprocessor Free
  - System Type: x64-based PC
- Nodejs Version: v17.0.1
- NPM Version: v8.1.0
- Yarn Version: v3.1.0

## ❓ Aditional Context

1. I'm currently using a [mirror service hosted by Huawei](https://repo.huaweicloud.com/repository/npm).
2. The required version of package is uploaded to that mirror.
3. I'm located in Mainland China, but the IP address of my device is in Chinese Taipei, I can't sure if I'm behind a proxy service (no need to configure locally).

**Comment by Dragon1573** [comment]
I invoked `yarn add -D vuepress-theme-vdoing` several times, it first failed with `Y0001` error but suddenly "fixed" itself and installed the dependency successfully (only with some unimportant warnings). Can't reproduce it again. 

```log
(base) Study-Notes on main ● λ yarn add -D vuepress-theme-vdoing
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @vue/babel-plugin-jsx@npm:1.0.7 doesn't provide @babel/core (pa6c52), requested by @babel/plugin-syntax-jsx
➤ YN0002: │ @vuepress/core@npm:1.8.2 doesn't provide @vue/compiler-sfc (p4c8a9), requested by vue-loader
➤ YN0002: │ study-notes@workspace:. doesn't provide chalk (p75ef5), requested by vuepress-plugin-sitemap
➤ YN0002: │ study-notes@workspace:. doesn't provide commander (p17913), requested by vuepress-plugin-sitemap
➤ YN0002: │ study-notes@workspace:. doesn't provide esm (p844b2), requested by vuepress-plugin-sitemap
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 497ms
➤ YN0000: ┌ Link step
➤ YN0076: │ fsevents@patch:fsevents@npm%3A1.2.13#~builtin<compat/fsevents>::version=1.2.13&hash=18f3a7 The win32-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ fsevents@patch:fsevents@npm%3A2.3.2#~builtin<compat/fsevents>::version=2.3.2&hash=18f3a7 The win32-x64 architecture is incompatible with this module, link skipped.
➤ YN0000: └ Completed in 0s 777ms
➤ YN0000: Done with warnings in 1s 562ms
```

**Comment by aladdin-add** [comment]
1. it has been fixed in latest yarn, so please upgrade: `yarn set version latest`.
2. As v17 is not a lts, please use node v16/v14 in production (node:latest => node:lts).

**Comment by Dragon1573** [comment]
@aladdin-add , Thank you! ❤️

1. I have invoked `yarn set version berry` and upgraded to `v3.1.0`, it DOES solved the problem! 🎉
2. I'm new to *Node.js* and *Yarn*, just because I want to publish my notes to *GitHub Pages* using *VuePress*. There're too many things that I didn't know before. I'll downgrade to the latest LTS version of *Node.js* as you instructed.

**Comment by leotm** [comment]
@aladdin-add M V P ❤️ 

on a side-note, also my hero back in ole '96
![homebrewprefix issue](https://cdn.wikimg.net/en/strategywiki/images/thumb/e/e8/Aladdin_Amiga_stage.png/300px-Aladdin_Amiga_stage.png)

**Comment by bmaier** [comment]
Following command solve the issue in my  environment:

`yarn set version latest`

**Comment by banagale** [comment]
I had this issue trying to `yard add stripe`. Error was `YN0001: │ Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close`.

@bmaier 's `yarn set version latest` took my yarn to `3.1.1` which allowed me to successfully run `yarn add stripe`.

**Comment by hargup** [comment]
Updating yarn to latest leads me to a new error:
```
Internal Error: Cannot redefine settings "changesetBaseRefs"
    at Xa.importSettings (/Users/harshgupta/code/instant-apps/.yarn/releases/yarn-3.2.0.cjs:395:24057)
    at Xa.activatePlugin (/Users/harshgupta/code/instant-apps/.yarn/releases/yarn-3.2.0.cjs:395:23932)
    at Function.find (/Users/harshgupta/code/instant-apps/.yarn/releases/yarn-3.2.0.cjs:395:22198)
    at async i (/Users/harshgupta/code/instant-apps/.yarn/releases/yarn-3.2.0.cjs:448:11309)
    at async r (/Users/harshgupta/code/instant-apps/.yarn/releases/yarn-3.2.0.cjs:448:10887)
 ```
 
 Any clue on how I can go about fixing it?

**Comment by antoooooooooooonie** [comment]
> Updating yarn to latest leads me to a new error:
> 
> ```
> Internal Error: Cannot redefine settings "changesetBaseRefs"
>     at Xa.importSettings (/Users/harshgupta/code/instant-apps/.yarn/releases/yarn-3.2.0.cjs:395:24057)
>     at Xa.activatePlugin (/Users/harshgupta/code/instant-apps/.yarn/releases/yarn-3.2.0.cjs:395:23932)
>     at Function.find (/Users/harshgupta/code/instant-apps/.yarn/releases/yarn-3.2.0.cjs:395:22198)
>     at async i (/Users/harshgupta/code/instant-apps/.yarn/releases/yarn-3.2.0.cjs:448:11309)
>     at async r (/Users/harshgupta/code/instant-apps/.yarn/releases/yarn-3.2.0.cjs:448:10887)
> ```
> 
> Any clue on how I can go about fixing it?

I'm getting the same issue. Feels like I'm going in circles 😅 .

**Comment by merceyz** [comment]
You need to update the plugins you're using as well

**Comment by antoooooooooooonie** [comment]
Is there any sort of comprehensive document on how to upgrade from `yarn@2.x.x` to `yarn@2.x.x+1`?

**Comment by jsbroks** [comment]
Having this issue in Node lts v18

**Comment by sk22** [comment]
since this issue describes the problem i had pretty well, but i didn't find my solution here, i think i'll share what made it work in my case (trying to get [govuk-react](https://github.com/govuk-react/govuk-react) running on my computer):

after running `yarn set version latest` (which upgraded the local yarn installation to 3.2.4), i also had the `Cannot redefine settings "changesetBaseRefs"` error when running `yarn`.

so, i ended up deleting the `.yarn/plugins/@yarnpkg` folder and deleting entries from the `plugins` section in `.yarnrc.yml`, which looked like this before

```diff
  plugins:
-   - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
-     spec: "@yarnpkg/plugin-version"
-   - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
-     spec: "@yarnpkg/plugin-workspace-tools"
-   - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
-     spec: "@yarnpkg/plugin-typescript"
```

i then ran these commands to reinstall the plugins:

```
yarn plugin import @yarnpkg/plugin-version
yarn plugin import @yarnpkg/plugin-workspace-tools
yarn plugin import @yarnpkg/plugin-typescript
```

since i'm not used to yarn, i don't know how usually to go about this issue, but the described worked for me. no more errors when running `yarn`!

**Comment by sideshowbarker** [comment]
Setting `YARN_CHECKSUM_BEHAVIOR=update` in the environment is the only thing that worked for me.

That is, either doing `export YARN_CHECKSUM_BEHAVIOR=update` or else running `YARN_CHECKSUM_BEHAVIOR=update yarn` as the command, instead of just `yarn`.

(from https://stackoverflow.com/a/71276936/441757, via https://github.com/substrate-developer-hub/substrate-front-end-template/issues/213#issuecomment-1051812768)

**Comment by Kitanit** [comment]
docker 6.1.0 same error

![image](https://github.com/yarnpkg/berry/assets/65107731/f248eb9e-72e5-46f8-8a37-4ce454085ef7)
