### ISSUE TITLE
[Feature] Spawning bin scripts with any cwd

### ISSUE THREAD

**Issue by jacobrask** [yarnpkg/berry#362]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

I am maintaining a monorepo where we keep CLI tools in a separate package. Currently we basically do `spawn('npx', ['--no-install', 'babel', args])` where babel would be a dependency of the `cli-tools` package. Package that need to use babel then depend on `tools` and have `"build": "cli-tools build"` in their `package.json#scripts`.

When migrating to PnP and Yarn 2 I tried a couple of different approaches:

 - Replace `npx babel` with `yarn run babel` - requires the spawn cwd to be set to `cli-tools` instead of the package being built, otherwise yarn does not find babel. This causes a bunch of issues since many tools expect to be run in the directory or at least a parent of the code it operates on.
 - Replace `spawn('npx babel')` with `spawn(execSync('yarn bin babel', { cwd: __dirname }))`. Does not work, the babel binary could not be found to be spawned since I assume it's a virtual file. This is the solution we used before switching to npx.

**Describe the solution you'd like**

Either a way of passing `--cwd` to `yarn run` while still loading the actual script/module from the original `cwd`, or maybe I have missed a way to get this working with existing features.

**Comment by arcanis** [comment]
You can call `yarn node $(yarn bin babel-cli)`, which will call the binary through the right environment. 

That being said, we should expose the original cwd through an environment variable.

**Comment by jacobrask** [comment]
Ok nice, this is the solution I ended up with that seems to be working:

```
const { execSync, spawn } = require('child_process');

function getBin(bin) {
  return execSync(`yarn bin ${bin}`, {
    encoding: 'utf8',
    cwd: __dirname
  }).trim();
}

function spawnBin(bin, args) {
  const child = spawn('yarn', ['node', getBin(bin), ...args], {
    stdio: 'inherit'
  });
 // ...
```
