### ISSUE TITLE
[Feature] allowing bypassing plugin require sandbox for plugins compiled with plugin-builder

### ISSUE THREAD

**Issue by seansfkelley** [yarnpkg/berry#3647]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

I maintain a purpose-build yarn plugin for a monorepo that is bundled with the plugin builder. We have a lot of shared code implementing various dev scripts, and I'd like to reuse it. However, if I require/import those packages, they will (1) get built into the plugin in whatever random state they happen to be in when the build command is run and (2) bloat the plugin massively (upwards of 2 MB -- they aren't tree-shakeable at the moment).

Given that this plugin is tightly coupled to this repo and the plugin behaviors in question are known (to me) to be safe to depend on dynamic requires, I'd like to be able to do so. Even if one breaks the static analysis of esbuild such that it doesn't compile the code in, it'll fail at runtime with `This plugin cannot access the package referenced via...` from

https://github.com/yarnpkg/berry/blob/554257087edb4a103633e808253323fb9a21250d/packages/yarnpkg-core/sources/Configuration.ts#L1051

As you'll see in the workaround section, I had to go a little farther to make this work.

**Describe the solution you'd like**

There's a bunch of potential options, but to throw a few off the top of my head:

- an attribute of `require`, like say, `require.realRequire`
- putting the real require back on `global`/`globalThis` (that object is surprisingly sparse when I checked)
- exporting a method from e.g. `@yarnpkg/cli` like `realRequire`

Notably, plugins not bundled with the plugin builder can do this. So that's an escape hatch, but one I would rather not take because I _just_ switched to using the builder: the development experience is so, so much more pleasant and it doesn't require me documenting all kinds of footguns around importing the wrong instance of `@yarnpkg/cli`.

**Describe the drawbacks of your solution**

I'm more or less asking to add a footgun to the library -- there is a lot of value in being forced to build everything into the bundle in the general case. I'm aiming for something annoying and self-evidently dangerous like `__dangerouslySetInnerHtml` which seems to have worked well thus far to prevent abuse.

**Describe alternatives you've considered**

I've tried a handful of increasingly-hacky solutions, including:

- a method to wrap `require` to break static analysis
- looking on `global`/`globalThis` for a require
- using `eval` to bypass the checks -- but not sure where to look for a require
- injecting some code at the beginning of the compiled script in a post-process step

The last workaround actually works, but hoo boy is it gross. My build command looks like

```
builder build plugin && echo 'var nativeRequire = require;' > built/plugin.js && cat bundles/@yarnpkg/plugin-dev.js >> built/plugin.js
```

and any code that wishes to require something without bundling it is routed through this file

```ts
export function breakRequireStaticAnalysis(packageName: string): any {
  return nativeRequire(packageName);
}

declare global {
  function nativeRequire(packageName: string): any;
}
```

which exists mostly to reduce the blast radius of the hack and make sure that readers and writers know exactly what's going on.

**Comment by merceyz** [comment]
You can use `createRequire` to get a `require` function that Yarn doesn't control
https://nodejs.org/dist/latest-v16.x/docs/api/module.html#modulecreaterequirefilename

**Comment by seansfkelley** [comment]
Thanks for the pointers! I was not aware of either of those.

`dynamicRequire` doesn't break out the sandbox enough -- packages that are in my `node_modules` where the node resolution algorithm found them in the past are no longer accessible.

`createRequire` does work. The docs and a lot of references online pass `import.meta.url`, but because `@yarnpkg/builder` is hardcoded to produce a commonjs module, that doesn't work. Instead, providing `__dirname` seems to set up the resolution correctly.
