### ISSUE TITLE
[Feature] Http proxy basic-auth

### ISSUE THREAD

**Issue by jaecktec** [yarnpkg/berry#3684]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

As someone that needs to setup a pipeline behind a proxy that is secured with basic-auth
When I set `YARN_HTTPS_PROXY` and/or `YARN_HTTP_PROXY` to some url containing auth information*
Then yarn adds `Proxy-Authentication`

*) format: `http://<username>:<password>@proxy.com:1234`
**Describe the solution you'd like**

I'd add `Proxy-Authentication` headers to this part of the codebase
https://github.com/yarnpkg/berry/blob/e9947cfcb2733d4b5eb9f0348f73a6a97ce3d3a0/packages/yarnpkg-core/sources/httpUtils.ts#L24
whenever authentication options are present in the url

**Describe the drawbacks of your solution**

🤷🤷‍♀️

**Describe alternatives you've considered**

A local proxy-proxy that exposes the proxy without credentials, but this is very cumbersome

**Comment by Leksat** [comment]
Isn't this a bug?

`yarn config set proxy http://<username>:<password>@proxy.com:1234` works like a charm with Yarn 1.

**Comment by jaecktec** [comment]
I was a bit hesitant about contributing, however I thought since 'proxy-agent' is a dependency anyway, why not use this to parse the proxy URL? This would also add support for socks

**Comment by Leksat** [comment]
I have no socks experience. You could make an alternate PR, then maintainers can choose what they like more.

**Comment by jaecktec** [comment]
I did it in this commit, but I was not able to run the tests: https://github.com/jaecktec/berry/commit/a5c70570178f0ed3b56455dcacf7b2895aaaa914
