### ISSUE TITLE
[Case Study] stylelint

### ISSUE THREAD

**Issue by 7rulnik** [yarnpkg/berry#369]
**What package is covered by this investigations?**
[stylelint](https://github.com/stylelint/stylelint)

**Describe the goal of the investigation**
We should support stylelint because this is the most popular linting tool for CSS.

**Investigation report**
Seems that integration with yarn should be the [same (#8)](https://github.com/yarnpkg/berry/issues/8) as with ESLint? But there is at least one problem: most popular [vscode integration](https://github.com/shinnn/vscode-stylelint) doesn't support configurable binary and maintainer closed issues for this project

**Comment by arcanis** [comment]
Have you tried running it and see where it fails?

Regarding the VSCode integration, some projects disable issues because they expect people who care to submit PRs rather than issues, maybe that's the case here and @shinnn would be open to a contribution?

**Comment by ota-meshi** [comment]
Hello! Now the stylelint VSCode extension is maintained by the official team.
https://github.com/stylelint/vscode-stylelint

I would be grateful if you could comment on the work required to support Yarn2.
https://github.com/stylelint/vscode-stylelint/issues/44

**Comment by 7rulnik** [comment]
@arcanis seems that everything works (at least with my configuration). So our problem is editor integration.

**Comment by 7rulnik** [comment]
Closed in #1011
