### ISSUE TITLE
[Feature] More concise PnP specification

### ISSUE THREAD

**Issue by pauldraper** [yarnpkg/berry#3698]
Is this the authoritative PnP spec?  https://yarnpkg.com/advanced/pnpapi

If so, a a couple suggestions:

1. More clearly delineate the PnP specification vs Yarn extensions. Namely, separate them in different documents entirely.

2. Consider a separate or more prominent location for it. Right now, the PnP spec is buried in "Yarn Advanced."

I think this changes would help improve the adoption of PnP as the standard Node.js module resolution API.

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/4671
