### ISSUE TITLE
Docs in source control?

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/berry#370]
Is there a reason that a compiled version of the docs are in source control? https://github.com/yarnpkg/berry/tree/master/docs

I get that this can be useful when running the site locally (no need to compile it) but it's usually better to just have the source files in source control, and compile them as part of the site build process.

**Comment by arcanis** [comment]
At the moment it's because the website is deployed through the GH Pages and I'm not sure how to deploy it to Netlify or Zeit instead (I don't have access to the domain name).

**Comment by Daniel15** [comment]
I can see if I can get a Netlify site working on a subdomain (like
berry.yarnpkg.com) if you'd like!

**Comment by arcanis** [comment]
For sure! We already have Netlify configured for previews btw (on the regular Yarn account).

**Comment by Daniel15** [comment]
Set up a subdomain https://next.yarnpkg.com/ with Netlify. I know you mentioned you're considering hosting the site on Zeit Now - I can change the CNAME if we decide to migrate across.

**Comment by arcanis** [comment]
Perfect! I'll open a new issue to update the website links and drop the `gh-pages`
