### ISSUE TITLE
[Feature] Allow users to specify a custom `experimental-loader` when using `esm`

### ISSUE THREAD

**Issue by leebeydoun** [yarnpkg/berry#3700]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [X] This feature is important to have in this repository; a contrib plugin wouldn't do

Sadly can't contribute without jumping through some significant hurdles. 

**Describe the user story**

Using `yarn` with the `.pnp.loader.mjs` experimental loader prevents users from adding their own loader. If we specify it on the command line, we lose `yarn`'s loader. Node doesn't currently support multiple `loaders`, and even if it did, not sure how this will look in future. Since `yarn` expects the loader to be called `.pnp.loader.mjs` (hard coded in the source), and this file is automatically generated - users of yarn don't have an option but to use it. 

**Describe the solution you'd like**

Allow users specify the experimental loader to use in `yarmrc` or something similar. Yarn can still generate the `.pnp.loader.mjs` file, but advanced users can import from the original `.pnp.loader.mjs` file and re-export their custom hooks (which build on top of the `.pnp.loader.mjs` hooks). 

**Describe the drawbacks of your solution**

This is an opt-in feature, and using it essentially means you know what you are doing. More config is never better, but my request is basically for the name of the experimental loader to use not to be hard-coded. 

**Describe alternatives you've considered**

We could always incorporate the experimental loader and override it ourselves, e.g:
```sh
yarn node --experimental-loader ./.pnp.loader-extended.mjs ./main.mjs
```
But the above only complicates things (sometimes yarn is run as a script, do we manually add this everywhere?). What if `yarn` is run in another processes?

**Comment by arcanis** [comment]
That's outside of Yarn's scope. This should be solved (and is being solved) by the [Node Loaders Working Group](https://github.com/nodejs/loaders), specifically by adding support for [loader chaining](https://github.com/nodejs/loaders/blob/main/doc/design/proposal-chaining-middleware.md).

**Comment by leebeydoun** [comment]
Specifying which loader yarn should use for something it automatically detects and configures is outside of its own scope?

**Comment by NMinhNguyen** [comment]
If and when loader chaining is implemented, would the expectation be for users to manually include Yarn's loader via the CLI? Or would Yarn combine `--experimental-loader`s passed on the command line with its own one that it passes down via `NODE_OPTIONS` so that spawned Node processes automatically inherit the loaders? I think it'd still be preferable for users to be able to tell Yarn which loaders to chain in addition to the PnP one, perhaps via some config.

**Comment by arcanis** [comment]
> If and when loader chaining is implemented, would the expectation be for users to manually include Yarn's loader via the CLI?

I'd expect it to work the same as for commonjs: Yarn adds `--loader .pnp.mjs` to the `NODE_OPTIONS` variable (just like we do with `--require`), and to add more loaders you'd add more `--loader` options to your own command line. But it's not specific to Yarn, it's how Node works.

**Comment by NMinhNguyen** [comment]
Actually, I think it may be possible to hook into `setupScriptEnvironment` and extend `NODE_OPTIONS`. I haven't tested that yet but if I'm reading the source code correctly, it would work and allow for a more seamless addition of custom loaders by default.

**Comment by wmertens** [comment]
ah - I think I can't get it to work because I'm trying to import the loader from PnP, and that happens without pnp support loaded :-(

```
node --loader ./.pnp.loader.mjs --loader @esbuild-kit/esm-loader
(node:209010) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/errors:466
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@esbuild-kit/esm-loader' imported from /home/wmertens/Projects/agent/
```

is this a bug in the loader chaining?

**Comment by arcanis** [comment]
It's not a bug, it's a separate feature: loaders can be composed, but don't yet leverage earlier loaders when resolving subsequent ones. I submitted a RFC and there's been reasonable support for fixing that, but I didn't get the chance to implement it yet.

**Comment by wmertens** [comment]
@arcanis thanks, I'm rooting for your RFC then :-)

And I just noticed it didn't land in 18.x yet :-(
