### ISSUE TITLE
[Bug?]: Clarify TypeScript SDK Change in v3.1.0

### ISSUE THREAD

**Issue by Kurt-von-Laven** [yarnpkg/berry#3705]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

One of the sentences in [the changelog entry for v3.1.0](https://github.com/yarnpkg/berry/blob/%40yarnpkg/core%2F3.1.0/CHANGELOG.md#bugfixes-1) trails off:

> "The TypeScript SDK now"

### To reproduce

1. Read [the changelog entry for v3.1.0](https://github.com/yarnpkg/berry/blob/%40yarnpkg/core%2F3.1.0/CHANGELOG.md#bugfixes-1).

### Environment

```shell
N/A
```

### Additional context

I'm happy to update the changelog, but I don't know what it should say.

**Comment by arcanis** [comment]
It's a bogus line I forgot to remove before the 3.0 release, but I found it funny afterwards and left it there 🤷‍♀️
