### ISSUE TITLE
ssl3 wrong version number when trying 'yarn set version berry'

### ISSUE THREAD

**Issue by longlostbro** [yarnpkg/berry#3707]
Problem: 

- When I try to set version to berry I get some sort of ssl3 wrong version error.

Additional notes: 

- running on a work vpn with limited rights user (no admin priviledges)
- yarn 1 works fine for me but other people on my team get an ECONRESET error when trying yarn install. 
- I am attempting to get us all upgraded to yarn 2 to see if it resolves the issue or at minimum get access to some of the newer config settings in .yarnrc.yml like httpTimeout, httpRetry, networkConcurrency to see if that resolves ECONRESET error

Steps to reproduce:

- yarn set version berry

Error:

- error An unexpected error occurred: "https://github.com/yarnpkg/berry/raw/master/packages/yarnpkg-cli/bin/yarn.js: write EPROTO 24224:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\\ws\\deps\\openssl\\openssl\\ssl\\record\\ssl3_record.c:332

**Comment by ylemkimon** [comment]
It seems the certificate provided by your work VPN or proxy is invalid or not compatible.

**Comment by longlostbro** [comment]
Yes i have strict ssl set to false because of this.

**Comment by longlostbro** [comment]
Is there no way to resolve this?

**Comment by merceyz** [comment]
Closing as unactionable, without an actual reproduction there isn't much we can do from our end.
