### ISSUE TITLE
[Bug]: Security disclosure

### ISSUE THREAD

**Issue by aviadhahami** [yarnpkg/berry#3735]
### Describe the bug

Hi, 
I'd like to know what's the appropriate way to disclose a security vulnerability to the `yarn` project :) 
> no info found regarding security procedures was found on readme nor H1 etc

thanks!

```shell
all envs impacted
```

**Comment by RDIL** [comment]
You should probably send it to @arcanis on Discord (arcanis#1505), or by email (nison.mael@gmail.com - as found in contributing guidelines).

**Comment by arcanis** [comment]
Yep, exactly!

**Comment by aviadhahami** [comment]
Will do.
For future security-related bugs - do you think there's room for updating the README w/ info regarding what one should do? :) 
Making such will make reporting more accessible (IMO)

**Comment by RDIL** [comment]
Commit `4f7f57e68e48cefe19ac1ac753277ecefe27603f` introduced a security policy.
