### ISSUE TITLE
Website fails when cookies are disabled

### ISSUE THREAD

**Issue by JaapJoris** [yarnpkg/berry#3759]
The website www.yarnpkg.com doesn't work when you disable cookies in the web browser's settings.

It would be nice if at least basic functionality is available.

Screenshot:

![yarnpkg com](https://user-images.githubusercontent.com/9511578/142436643-05ba1b3e-b829-45d1-9d57-a032384a9458.png)

Steps to reproduce:
- Disable cookies under "Privacy and security" settings in Chrome
- Visit www.yarnpkg.com (homepage works)
- Click any link

Expected result:
- Page content is shown

Actual result:
- Blank page is shown

**Comment by Daniel15** [comment]
Moving to `berry` repo since the `website` repo is for the Yarn v1 site.

**Comment by arcanis** [comment]
Probably just a matter of fixing [this place](https://github.com/yarnpkg/berry/blob/d5454007c9c76becfa97b36a92de299a3694afd5/packages/gatsby/src/utils/useScroll.js#L6-L12)
