### ISSUE TITLE
[Bug]: React-Scripts with Typescript and PnP fails to compile JSON imports

### ISSUE THREAD

**Issue by EwenDC** [yarnpkg/berry#3770]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When using React-Scripts to compile your react code and importing a JSON file as a module like so:
```
import example from './example.json';
```
Typescript will happily parse it as valid code in the editor, but throws the error `Cannot find module './example.json' or its corresponding type declarations.  TS2307` at compile time. This only happens when PnP is being used. When it is not being used Typescript happily recognizes the JSON as a module and compiles it. tsconfig.json has the correct settings required to parse the JSON (shown below truncated), and will parse it in the editor respecting these settings, but not at compile time.
```
{
  "compilerOptions": {
    "esModuleInterop": true,
    "resolveJsonModule": true,
  }
}
```
It's like when compiling the program, the version of typescript being used isn't inheriting these correct compiler settings, but I don't know enough about React-Scripts or PnP to know if that is the case.

### To reproduce

1. Open up the command line in a working folder and execute the command `npx create-react-app typescript-json-pnp --template cra-template-typescript`
2. In the `./typescript-json-pnp/src/` folder create a new file called `example.json` and save it with the following content: 
```
{
  "key": "value"
}
```
3. Override the contents of the `./typescript-json-pnp/src/App.tsx` file with the following code:
```
import React from 'react';
import example from './example.json';

export default function App() {
  return <p>In the example JSON file, "key" has a value of "{example.key}"</p>;
}
```
4. Run `yarn start`. The application should compile and run in the browser, showing the text `In the example JSON file, "key" has a value of "value"`
5. Terminate the debug server and follow the process to upgrade the project to Yarn Berry, then migrate the project to PnP.
6. Upon running `yarn start`, you should now get a compile time error of `Cannot find module './example.json' or its corresponding type declarations.  TS2307`

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
  Binaries:
    Node: 16.13.0 - ~\AppData\Local\Temp\xfs-54819a06\node.CMD   
    Yarn: 3.1.0 - ~\AppData\Local\Temp\xfs-54819a06\yarn.CMD     
    npm: 7.20.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by merceyz** [comment]
**Context**:
This was reported as an upstream issue in https://github.com/facebook/create-react-app/issues/9172 and https://github.com/facebook/create-react-app/issues/10455 and a fix was proposed in https://github.com/facebook/create-react-app/pull/10992 but they ended upgrading to Webpack 5 in https://github.com/facebook/create-react-app/pull/11201 which also fixed the problem.

**Solution**:
Update to `create-react-app@5`.

**Comment by EwenDC** [comment]
Thanks for the detailed response, appreciated!
