### ISSUE TITLE
[Feature] `yarn create`

### ISSUE THREAD

**Issue by locriacyber** [yarnpkg/berry#3776]
This is related to #821 (`yarn global`).

- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

As a developer, I sometimes want to create a new project with `yarn create`. However, I can't use latest yarn without an existing project. `yarn create` from yarn 1.x is broken (try `yarn create svelte@next`).

So `yarn create`'s existence is strange.

**Describe the solution you'd like**

Remove `yarn create` from latest yarn, or make it possible to use latest yarn globally without an existing project.

**Describe the drawbacks of your solution**

N/A

**Describe alternatives you've considered**

`npm init` is good enough

**Comment by merceyz** [comment]
> or make it possible to use latest yarn globally without an existing project

You can run `yarn set version berry` in your home directory or run `corepack prepare yarn@stable --activate` to use Yarn Modern globally.
