### ISSUE TITLE
[Bug?]: doctor and sdks don't work when running against private NPM registry

### ISSUE THREAD

**Issue by HarryGwinnell** [yarnpkg/berry#3793]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Following the Yarn 2 migration guide, we attempted to run `yarn dlx @yarnpkg/doctor` and `yarn dlx @yarnpkg/sdks vscode`, but in both cases we're getting "Internal Error: Invalid filename: "@yarnpkg/sdks"" errors when using a private registry. Even standing up an empty sample project and defining our npm registry will cause this to fail. Removing the private registry will cause these to run as expected, but doctor will not analyse private packages.

The private registry contains a full npm mirror in addition to private packages.

```
PS C:\Users\hagwinne\Code\testproj> yarn dlx @yarnpkg/doctor
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 4s 536ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed in 0s 338ms
➤ YN0000: Done with warnings in 5s 84ms

Internal Error: Invalid filename: "@yarnpkg/doctor"
    at kr (C:\Users\hagwinne\Code\testproj\.yarn\releases\yarn-3.1.0.cjs:312:6878)
    at C:\Users\hagwinne\Code\testproj\.yarn\releases\yarn-3.1.0.cjs:426:2064
    at Function.from (<anonymous>)
    at C:\Users\hagwinne\Code\testproj\.yarn\releases\yarn-3.1.0.cjs:426:2023
    at async Wt.mktempPromise (C:\Users\hagwinne\Code\testproj\.yarn\releases\yarn-3.1.0.cjs:317:62926)
    at async g9 (C:\Users\hagwinne\Code\testproj\.yarn\releases\yarn-3.1.0.cjs:426:1911)
    at async Object.qFe (C:\Users\hagwinne\Code\testproj\.yarn\releases\yarn-3.1.0.cjs:426:2348)
    at async C:\Users\hagwinne\Code\testproj\.yarn\releases\yarn-3.1.0.cjs:590:297
    at async Wt.mktempPromise (C:\Users\hagwinne\Code\testproj\.yarn\releases\yarn-3.1.0.cjs:317:62926)
    at async jC.execute (C:\Users\hagwinne\Code\testproj\.yarn\releases\yarn-3.1.0.cjs:586:36214)
```

### To reproduce

Create a new project (yarn init) with all defaults
Modify .yarnrc.yml to add a private npm registry e.g.:

```
nodeLinker: pnp

npmAlwaysAuth: true

npmRegistryServer: "https://{org}.pkgs.visualstudio.com/_packaging/{feed}/npm/registry/"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
```

Attempt to run `yarn dlx @yarnpkg/doctor`

### Environment

```shell
Envinfo does not work in the latest version of Windows as wmic is deprecated (https://github.com/tabrindle/envinfo/issues/213). The below is manually collected:

System:
  OS: Windows 11 (2250x)
  CPU: (20) x64 Intel(R) Xeon(R) W-2255 CPU @ 3.70GHz
Binaries:
  Node: 14.18.1 - C:\Program Files\nodejs\node.exe
  Yarn: 3.1.0 - C:\Users\hagwinne\Code\{repo}\.yarn\releases\yarn-3.1.0.cj
  npm: 6.4.15
```

**Comment by merceyz** [comment]
It's an issue with the registry you're using, it's incorrectly normalizing the package manifest from
```json
{
	"name": "@yarnpkg/doctor",
	"bin": "index.js"
}
```
to
```json
{
	"name": "@yarnpkg/doctor",
	"bin": {
		"@yarnpkg/doctor": "index.js"
	}
}
```


Regarding the screenshot of text, see https://meta.stackoverflow.com/questions/285551/why-not-upload-images-of-code-errors-when-asking-a-question/285557#285557

**Comment by HarryGwinnell** [comment]
Apologies for my misunderstanding, but what's the issue in the registry that causes this? Comparing the .tgz's from npmjs and our registry, they're identical.

Apologies for the screenshot, fixed

**Comment by merceyz** [comment]
See https://github.com/yarnpkg/berry/issues/2013#issuecomment-808932225

**Comment by jmyersmsft** [comment]
FYI the underlying issue in Azure Artifacts should now be fixed. We were incorrectly using the full name of the package when reconstructing the bin property when the shortened form was originally used. We have made and deployed a change so that we use only the unscoped name of the package there.
