### ISSUE TITLE
[Feature] Add new protocol  "reg:" or "tgz:" to allow per dependency registry specification

### ISSUE THREAD

**Issue by craigphicks** [yarnpkg/berry#3800]
- [?] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
  - Depends on feedback and time 
- [] This feature is important to have in this repository; a contrib plugin wouldn't do
  - Probably not. 

**Describe the user story**

Suppose a project A with direct dependencies B and C in npm, while B depends on \@joe/foo in the @joe scope from `registry.npmjs.org`., while C depends on \@joe/bar package (or even a different \@joe/foo package in the @joe scope from `npm.pkg.github.com`.

```
 A
 |--B
     |--@joe/foo     # intended registry registry.npmjs.org
 |--C
     |--@joe/bar     # intended registry npm.pkg.github.com   
     |--@joe/foo     # intended registry npm.pkg.github.com
``` 
A's developer has very carefully read the docs of B and C to get the list of any scopes in any upstream packages as she must womanually set scope configurations herself.  But there is a collision.

And even if the chances of a collision were only one a million, the list of scopes requiring womanual setting in configs increases 
exponentially in length as they head downstream. 

Personally, I think it would a be a potential error/security risk to write a package with a scope @OWNER and have to rely on all downstream users setting/not-setting the correct/incorrect scope to server mapping in their own packages.

**Describe the solution you'd like**

An obvious solution is to specifiy the full URL per package, e.g.
```
  dependencies:{
     "reg:registry.npmjs.org/@joe/foo":  "^2.0.0",
     "reg:npm.pkg.github.com/@joe/foo":  "^1.0.0",
     "reg:npm.pkg.github.com/@joe/bar": "^1.0.0"
  }
```
with plain scopes defaulting to current behavior.

In the case of non-registry dumb servers serving tgz package.json packages nontheless
```
  dependencies:{
     "tgz:semver.unaware.com/@joe/bar": "1.0.0"
  }
```
only accepting fixed versions.

**Describe the drawbacks of your solution**

Obviously, "reg" and "tgz" are not supported by npm, yarn1, or other pms.
However, full URL and trouble free scopes will be much appreciated features due to their convenience, clarity, cleanliness, and security.  If it reached a certain level of usership, it would thereafter be "indispensible" and others would have to follow. Backporting to yarn1 might be a good idea user numberwise.

**Describe alternatives you've considered**

Specify scope to server mappings in each package in package.json.  But it's not a complete solution yet has the same drawbacks anyway.

**Comment by craigphicks** [comment]
Closing because this is probably more suited to a discussion "howto" public scopes (or "why not").

**Comment by arcanis** [comment]
Also related:
https://github.com/yarnpkg/berry/issues/1455
https://github.com/yarnpkg/berry/issues/156#issuecomment-492629794
https://github.com/npm/rfcs/pull/314

**Comment by craigphicks** [comment]
@arcanis - Thanks for the pointers.  
   The reason I became interested in this was because it seemed that publishing a public package on github packages would require any downstream users to explicitly map my scope S to my registry R in their configuration.  I think that is duplication of and too much of a burden on downstream users.  That effectively makes publishing public packages on Github Packages unusable.   
   It seems to me the URL proposal would fix that problem because the mapping would be embedded in the immediate calling  packages URL, so there would be no need for every downstream developer to manually map S to the R.
   I understand your misgivings, but I would put function over form.

**Comment by craigphicks** [comment]
@arcanis -  Registry Protocol Support #340 
is the road map for moving forward on this, but no progress since April 2021.  Looks like it is dead in the water.
The status quo of only being able to publish public packages on the NPM server, and a fee for a public packages scope remains for the indefinite future.
