### ISSUE TITLE
[doc?]: upgrading mentions `berry` & `v2`

### ISSUE THREAD

**Issue by tomByrer** [yarnpkg/berry#3808]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Seems 'berry' is now version 3, but doc says 2.  Unsure how to upgrade now.

### To reproduce

https://yarnpkg.com/getting-started/migration

### Environment

```shell
win10
node17
yarn1.x
```

**Comment by arcanis** [comment]
I don't see the problem. This migration guide explains how to migrate from 1.x, and the references to Yarn 2 make sense in the context, from a quick look. At best we can change them into "2+", but that's not super necessary.

**Comment by curiousercreative** [comment]
@arcanis I arrived here with a similar confusion. Does the migration guide get you from 1.x to 2.x or 1.x to 3.x? In other words, is it a migration to 2 or the latest major release?
