### ISSUE TITLE
[Feature] Allow linking specific "incompatible" modules

### ISSUE THREAD

**Issue by markandrus** [yarnpkg/berry#3822]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

In #1247, Yarn was updated to skip linking packages whose `os` and `cpu` values do not match the installing system. This is great when installing packages like esbuild, [which lists a bunch of `optionalDependencies` for differing `os` × `cpu` combinations](https://github.com/evanw/esbuild/blob/master/npm/esbuild/package.json), since we can typically only use the esbuild binary that matches our particular `os` × `cpu` combination.

However, I have a use case where I _do_ want to link a package whose `os` and `cpu` values differ from my own. Specifically, I am developing on macOS and bundling for Linux. One of my dependencies packages a Linux binary, and correctly lists its `os` as "linux". In order to bundle, I need to copy the packaged Linux binary into the resulting bundle. But Yarn doesn't link the package on macOS, so I cannot access it when bundling.

**Describe the solution you'd like**

I'd like to be able to disable the link optimization — perhaps overall or per-dependency — so that I can build for `os` × `cpu` combinations other than my local machine. I imagine this would be a flag in `.yarnrc.yml`.

However, I want to test on my local machine, too. So I don't want to install either the macOS or Linux dependencies — I want both.

**Describe the drawbacks of your solution**

* Disabling the link optimization overall could worsen install/link times; however, disabling the optimization would be opt-in via `.yarnrc.yml`, so not a big concern.
* Requiring a list of specific packages to skip the link optimization for could lead to lots of noise in the `.yarnrc.yml`.

**Describe alternatives you've considered**

Since I own the Linux dependency described above, I could remove the `os` and `cpu` values from its `package.json`; however, there are other use cases (besides my bundling use case) where it would be nice to still be able to depend on Yarn's link optimization.

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/3575
