### ISSUE TITLE
Don't emit SDKs for vscode-stylelint

### ISSUE THREAD

**Issue by adalinesimonian** [yarnpkg/berry#3844]
> See also: stylelint/vscode-stylelint#272

Since v1.1.0, released a month ago, vscode-stylelint natively supports resolving Stylelint when installed using PnP for Yarn 2.x and above. The current version of the extension is v1.2.0. Yarn currently emits SDKs for vscode-stylelint, which are no longer required.

VS Code automatically updates extensions, but some users may still be on old versions without PnP support. Versions 1.0 and prior do not support PnP and thus still need the SDK to function. Yarn doesn't have the context to know what version of a given extension is installed.

Some possible ways forward, off the top of my head:

- The Stylelint SDK could be removed regardless, seeing as old minor versions of 1.x don't receive support anyway, and 0.x is not supported at all.
- We could wait before removing the SDK. If we do this, how long should we wait?
- Instead of entirely removing the Stylelint SDK, Yarn could only emit it if explicitly asked. By default, the Stylelint SDK would not be emitted. At some point in time, it could be removed entirely.

   If we do this, what are the impacts of this change to Yarn? How long should we wait before removing the SDK entirely?

After changes are made, Yarn docs would need to be updated to reflect the change in support.

**Comment by arcanis** [comment]
I think it'd be reasonable to remove the SDK altogether if VSCode-Stylelint supports it natively. Our documentation is generally written in the idea that people use the latest version of both tools anyway 👍

**Comment by adalinesimonian** [comment]
Opened PR: #3860
