### ISSUE TITLE
[Feature] Fetch shallowly when installing from sources

### ISSUE THREAD

**Issue by erikeckhardt** [yarnpkg/berry#3850]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

Note: I'd be willing to implement this feature, but have limited time and have no experience contributing to yarn, so it's a toss-up if I could get it done in any reasonable time period.

**User Story**

As a developer, I want installation of yarn plugins and tools to be as fast as possible, so I am encouraged to use more of yarn's features and ecosystem, but `yarn plugin import from sources` downloads the entire yarnpkg repo with all history, which causes a huge delay.

**Proposed Solution**

When yarn does a `fetch` of `master` from `https://github.com/yarnpkg/berry.git`, it shouldn't pull the entire history of the repo and all branches. Consider copying [How GitHub does smarter Shallow Clones](https://therootcompany.com/blog/how-github-does-smarter-shallow-clones/), which is better than a naive shallow clone as it doesn't leave the repo in a weird state (allowing later `pull` or `fetch` commands to be unaffectedd). In a nutshell:

```
git init ./<repository-name>
git remote add <remote-name> <repository-url>
git -c protocol.version=2 fetch \
    --no-tags \
    --prune \
    --progress \
    --no-recurse-submodules \
    --depth=1 <remote-name>
git checkout \
    --progress \
    --force -B <branch-name> \
    refs/remotes/<remote-name>/<branch-name>
```

**Drawbacks**

I honestly cannot think of any drawbacks. This technique is the strategy that GitHub Actions ([actions/checkout@v2](https://github.com/actions/checkout)) uses, which as an official project of GitHub itself, should be pretty darn reliable.

**Alternatives Considered**

This functionality can't be a plugin because it's the core mechanism yarn uses to fetch and install plugins.

**Existing Code**

Yarn helpfully shows its actual git commands during execution. Good job exposing this—it was super helpful to me to know why the command was taking so long so I would give it the time it needed to finish:

```
  $ git init /var/folders/b4/hbhr52ws4yg381tf_xrd2_1c0000gp/T/yarnpkg-sources/d0a670
  $ git remote add origin https://github.com/yarnpkg/berry.git
  $ git fetch origin master
  $ git reset --hard FETCH_HEAD
```
And possibly:
```
  $ git clean -dfx
```

Though it's not clear when this line is executed, as it doesn't seem to always be run.

**Comment by erikeckhardt** [comment]
> We started limiting the depth in #3617 which shipped in `3.2.0-rc.3`
> 
> ```shell
> yarn set version canary
> ```

When does that get released as GA?

**Comment by stszap** [comment]
Can this be done for regular packages too (I mean `yarn install`)? We have a dependency that takes 3-4 minutes to do a full git clone, but only a few seconds with `--depth=1`.

**Comment by merceyz** [comment]
Closing as this has been implemented and shipped
