### ISSUE TITLE
[Bug?]: next.js eslint doesn't work in some cases.

### ISSUE THREAD

**Issue by bestseob93** [yarnpkg/berry#3867]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

nextjs : v10.2.3
yarn: v1.22.10

command: next dev

```
// index.tsx
function Home(): NextPage {
  console.log(window);
}
```

eslint: window is not defined

### To reproduce

but with yarn berry In the same code, it comes out nothing and page spins round and round indefinitely.
![image](https://user-images.githubusercontent.com/18053223/145743336-9d845577-c62f-4e54-98a5-e60a41f8ac0e.png)

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.12.0 - /private/var/folders/w_/s2ndqsg53bnfmnms530vnt940000gn/T/xfs-b6c7d432/node
    Yarn: 3.0.2 - /private/var/folders/w_/s2ndqsg53bnfmnms530vnt940000gn/T/xfs-b6c7d432/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.12.0/bin/npm
```

**Comment by RDIL** [comment]
Sounds like a Next.js problem, not Yarn.

**Comment by bestseob93** [comment]
solved with adding Custom Error component. (pages/_error.tsx)

**Comment by bestseob93** [comment]
https://github.com/vercel/next.js/issues/11537
