### ISSUE TITLE
[Bug?]: YN0001: │ TypeError: e is not iterable

### ISSUE THREAD

**Issue by TheKnarf** [yarnpkg/berry#3877]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Running `yarn install` suddenly stopped working. Getting the following error:

```
$ yarn install
...
 YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 6s 760ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ zen-observable@npm:0.8.15 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zen-push@npm:0.2.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zip-stream@npm:4.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zustand@npm:3.2.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zwitch@npm:1.0.5 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 2m 50s
➤ YN0000: ┌ Link step
➤ YN0001: │ TypeError: e is not iterable
    at Function.isManifestFieldCompatible (/Users/knarf/projects/dnb-web/.yarn/releases/yarn-3.0.2.cjs:270:4343)
    at Object.Die (/Users/knarf/projects/dnb-web/.yarn/releases/yarn-3.0.2.cjs:543:1897)
    at Uie.installPackage (/Users/knarf/projects/dnb-web/.yarn/releases/yarn-3.0.2.cjs:543:21289)
    at Fe.linkEverything (/Users/knarf/projects/dnb-web/.yarn/releases/yarn-3.0.2.cjs:303:11587)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/knarf/projects/dnb-web/.yarn/releases/yarn-3.0.2.cjs:306:4326
    at async xe.startTimerPromise (/Users/knarf/projects/dnb-web/.yarn/releases/yarn-3.0.2.cjs:275:3730)
    at async Fe.install (/Users/knarf/projects/dnb-web/.yarn/releases/yarn-3.0.2.cjs:306:4102)
    at async /Users/knarf/projects/dnb-web/.yarn/releases/yarn-3.0.2.cjs:348:14731
    at async Function.start (/Users/knarf/projects/dnb-web/.yarn/releases/yarn-3.0.2.cjs:275:2287)
➤ YN0000: └ Completed in 0s 219ms
➤ YN0000: Failed with errors in 2m 58s
```

I can't seem to get it to work. I've tried the following:

```
git checkout master -- yarn.lock
find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +
yarn cache clean
rm -rf ~/.yarn
```

and then re-run `yarn install`, and I still get the same error.

### To reproduce

No idea how to get a minimal reproduction.

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.13.0 - /private/var/folders/y7/pfsfvc053qz_vrlpywv6nc980000gn/T/xfs-db0fa750/node
    Yarn: 3.0.2 - /private/var/folders/y7/pfsfvc053qz_vrlpywv6nc980000gn/T/xfs-db0fa750/yarn
    npm: 8.1.0 - /opt/homebrew/Cellar/node@16/16.13.0/bin/npm
```

### Additional context

I had been working on trying to upgrade from Yarn 3.0.2 to 3.1.1 in another branch. The problem only happened after having worked on that and gone back to master to work on another feature. Not sure if thats related. It might however be that someone else in the mean time added or upgraded some package on the master branch.

**Comment by TheKnarf** [comment]
The problem seems to have resolved itself just as mysteriously as it appeared.

**Comment by oomoriyasumitsu** [comment]
I also encountered a similar phenomenon.

``` shell
➤ YN0001: │ TypeError: e is not iterable
    at Function.isManifestFieldCompatible (/Users/omori/.yarn/releases/yarn-berry.cjs:270:4343)
    at Object.Die (/Users/omori/.yarn/releases/yarn-berry.cjs:543:1897)
    at Uie.installPackage (/Users/omori/.yarn/releases/yarn-berry.cjs:543:21289)
    at Fe.linkEverything (/Users/omori/.yarn/releases/yarn-berry.cjs:303:11587)
```

I also solved it by updating the version of yarn(3.11)

``` shell
$ cd ~
$ yarn set version latest
```

**Comment by tochukaso** [comment]
I also encountered a similar phenomenon.

``` shell
➤ YN0001: │ TypeError: e is not iterable
    at Function.isManifestFieldCompatible (/Users/omori/.yarn/releases/yarn-berry.cjs:270:4343)
    at Object.Die (/Users/omori/.yarn/releases/yarn-berry.cjs:543:1897)
    at Uie.installPackage (/Users/omori/.yarn/releases/yarn-berry.cjs:543:21289)
    at Fe.linkEverything (/Users/omori/.yarn/releases/yarn-berry.cjs:303:11587)
```

I also solved it by updating the version of yarn(3.11)

``` shell
$ cd ~
$ yarn set version latest
```

**Comment by numbers1311407** [comment]
I can report this as well, and have what's so far been a reliable workaround.

1. Note the bundled version in your repo
2. `cd ~` and `yarn set version <the bundled version>`
3. Go back to the broken repo, `yarn` again.  In my case, this succeeds.
4. Optional - `cd ~` again and `yarn set version latest` or delete the bundled release and rely on `corepack enable`.
5. Go back to the broken repo and confirm that `yarn` still works.

I experienced the issue with 2 repos so far, each with a different bundled yarn, 2.4.1 and 3.0.2, both using `nodeLinker: node-modules`.  Running node v16.13.1 (lts/gallium).

This worked for both cases.

I thought it might be gitignored artifacts in .yarn but that doesn't seem to be the case.  I can:

```
yarn cache clean
git clean -xf
yarn
```
...without issue.

.gitignore for each repo looks like:
```
.yarn/*
!.yarn/patches
!.yarn/releases
!.yarn/plugins
!.yarn/sdks
!.yarn/versions
.pnp.*
```

**Comment by merceyz** [comment]
@numbers1311407 Can you provide a Dockerfile that reproduces the issue?

**Comment by thatsjonsense** [comment]
I'm running into this same issue but would prefer not to upgrade yarn for our whole team just because I'm hitting this error locally. We're running 2.4.3 and I had tried using 3.1 in a branch. Is there any way to reset whatever config/cache/??? setting that change introduced, without rolling everyone forward to 3.1.1? Thanks

**Comment by merceyz** [comment]
Sure, you can manually delete `.yarn/install-state.gz`

**Comment by thatsjonsense** [comment]
That worked, thanks so much @merceyz !
