### ISSUE TITLE
[Feature] Patch plugin improvements

### ISSUE THREAD

**Issue by RDIL** [yarnpkg/berry#3878]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [X] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

The patch plugin is very cool, but needs some love.  For patches that aren't just a "one-off" thing, e.g. you need to update patches regularly, the plugin falls a bit flat.

**Describe the solution you'd like**

Imo, the following changes would be greatly beneficial to the patch plugin:

- (maybe) extract the diff/patch algorithm into it's own package (patchpanion? 😆)
  - The patch algorithm is quite literally the first one that I've seen that *works* that is written in JS
- Fix the `-s` flag outputting incorrect versions in resolutions
- Output a `.patch` file name for syntax highlighting (https://github.com/yarnpkg/berry/pull/3935)

**Describe the drawbacks of your solution**

Might take quite a bit of effort to implement these changes.

**Describe alternatives you've considered**

Copying and pasting files + modifying the files after running the commands, but that's quite a hassle.

**Comment by merceyz** [comment]
> Fix the -s flag outputting incorrect versions in resolutions

Fixed in https://github.com/yarnpkg/berry/pull/4218

> Output a .patch file name for syntax highlighting

Fixed in https://github.com/yarnpkg/berry/pull/3935
