### ISSUE TITLE
[Bug?]: 

### ISSUE THREAD

**Issue by coderaiser** [yarnpkg/berry#3879]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When I'm using 🐊`Putout` code transformer with `yarn P'n'P` I got an error:

```
🐊 @putout/formatter-progress-bar: simport tried to access @putout/formatter-progress-bar, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @putout/formatter-progress-bar (via "@putout/formatter-progress-bar/package.json")
Required by: simport@npm:1.2.0 (via /Users/evgeny/Downloads/putout-yarn3/.yarn/cache/simport-npm-1.2.0-c4f61c3792-85716020b4.zip/node_modules/simport/simport.js)
```

The thing is [`simport`](https://github.com/coderaiser/simport) is a module that improves dynamic imports in a couple ways:
1. You can pass it as a function so instead of this monster:

```js
    try {
         await import(pluginName);
    } catch {
    }
```

You can use:

```js
const [error, plugin] = await tryToCatch(simport, pluginName);
```

2. There is no need to destructure `default`:

```js
const {default: plugin} = await import(pluginName);
const plugin = await simport(pluginName);
```

3. Windows absolute paths just works:

```js
const plugin = await simport('c:\windows');
```

4. Supports `json` files, like with `require`.
5. Extension can be dropped.
6. etc.

So `simport` should not know about any dependency it is used for. Would be great to have first class support of it :)! Without using [loose](https://yarnpkg.com/features/pnp#pnp-loose-mode) mode.

Related to https://github.com/coderaiser/putout/issues/93, https://github.com/EvgenyOrekhov/eslint-config-hardcore/issues/399

### To reproduce

Steps to reproduce:

1. `git clone https://github.com/EvgenyOrekhov/putout-yarn3.git`
2. `cd putout-yarn3`
3. `yarn`
4. `yarn putout .`

### Environment

```shell
error Command "dlx" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

`yarn 1.17.3`
`v14.17.5`
`Mac OS`
```

**Comment by merceyz** [comment]
If `simport` wants to resolve something on behalf of another file it has to use https://nodejs.org/api/esm.html#importmetaresolvespecifier-parent, the way it currently does it just happens to work because of hoisting but it's fragile and prone to breaking.

See https://yarnpkg.com/advanced/rulebook/#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies for more details on hoisting

**Comment by coderaiser** [comment]
@merceyz thanks for a quick reply!

OK, I can use a [create-require](https://nodejs.org/api/module.html#module_module_createrequire_filename) hack, just to get `.pnp.cjs` 1MB monster to get working, and also I can get rid of `simport` and use `simple-import.js` file that should be copied in **just every project**, because of _fragile and prone to breaking_ solution that works amazing with `npm`:

```js
module.exports = async (url) => (await import(url)).default;
```

And I can publish new version of 🐊`Putout` that will be compatible with yarn P'n'P. But I have a problem with `chalk` and [subpath patterns](https://nodejs.org/dist/latest-v17.x/docs/api/packages.html#subpath-patterns). Are they supported by yarn?

```
🐊 @putout/formatter-progress-bar: chalk tried to access #ansi-styles, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: #ansi-styles (via "#ansi-styles/package.json")
Required by: chalk@npm:5.0.0 (via /Users/coderaiser/putout-yarn3/.yarn/cache/chalk-npm-5.0.0-7be183234e-6eba7c518b.zip/node_modules/chalk/source/index.js)
```

`ansi-styles` [doesn't even have package.json](https://github.com/chalk/chalk/tree/v5.0.0/source/vendor/ansi-styles)!

**Comment by merceyz** [comment]
> that works amazing with npm:

With your current dependency tree that might be true but that isn't guaranteed and, like the documentation I linked shows, can break by unrelated changes to the dependency tree.

> But I have a problem with chalk and subpath patterns. Are they supported by yarn?

The `imports` field isn't supported by PnP yet, no.
Ref https://github.com/yarnpkg/berry/issues/3843

**Comment by coderaiser** [comment]
@merceyz thank you!

I think this information could be important for @sindresorhus (there is no ability to create an issue in `chalk` repository, so if you will see this message, would be great to have support of Yarn PnP).

**Comment by rachelslurs** [comment]
@coderaiser Looking through some of the closed issues over at chalk, I guess chalk is taking a hard stance on not wanting to support people not supporting imports and exports in their package.json. They would rather you just use chalk v4 I suppose. :confused:  Surprising given how many projects use chalk. :grimacing:
