### ISSUE TITLE
[Bug?]: Tricking contributors with Crowdin

### ISSUE THREAD

**Issue by comradekingu** [yarnpkg/berry#3890]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

https://crowdin.com/project/yarn is still up, following https://github.com/yarnpkg/berry/issues/3296#issuecomment-899086629

### To reproduce

Go to https://crowdin.com/project/yarn and be dissapointed

### Environment

```shell
https://crowdin.com/project/yarn
```

### Additional context

Use Weblate instead.

**Comment by arcanis** [comment]
I don't have the keys to the Crowdin account and cannot shut it off.
