### ISSUE TITLE
[Bug?]: core-js injection done by @babel/preset-env crashing Webpack build when using PnP

### ISSUE THREAD

**Issue by wojtekmaj** [yarnpkg/berry#3926]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When using PnP, core-js injection done by @babel/preset-env crashes Webpack build. Interestingly, this only seems to affect local packages loaded using Yarn Workspaces, although I haven't been able to confirm that with 100% certainty.

The error:

```
ERROR in ./packages/utils/index.js 1:0-42
Module not found: Error: Can't resolve 'core-js/modules/es.array.from.js' in '/projects/yarn-pnp-core-js-issue/packages/utils'
resolve 'core-js/modules/es.array.from.js' in '/projects/yarn-pnp-core-js-issue/packages/utils'
  Parsed request is a module
  using description file: /projects/yarn-pnp-core-js-issue/packages/utils/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      request is not managed by the pnpapi
        Your application tried to access core-js, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
        Required package: core-js
        Required by: /projects/yarn-pnp-core-js-issue/packages/utils/
 @ ./src/index.js 1:0-38 4:2-5

ERROR in ./packages/utils/index.js 2:0-47
Module not found: Error: Can't resolve 'core-js/modules/es.string.iterator.js' in '/projects/yarn-pnp-core-js-issue/packages/utils'
resolve 'core-js/modules/es.string.iterator.js' in '/projects/yarn-pnp-core-js-issue/packages/utils'
  Parsed request is a module
  using description file: /projects/yarn-pnp-core-js-issue/packages/utils/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      request is not managed by the pnpapi
        Your application tried to access core-js, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
        Required package: core-js
        Required by: /projects/yarn-pnp-core-js-issue/packages/utils/
 @ ./src/index.js 1:0-38 4:2-5
```

Setting `pnpMode` to `"loose"`, interestingly, does not resolve the issue.

Setting `nodeLinker` to `"node-modules"` does resolve the issue.

### To reproduce

https://github.com/wojtekmaj/yarn-pnp-core-js-issue

Note there are two commits: One with initial, non-functional setup, and another with potential fixes/workarounds:
* Setting `nodeLinker` to `node-modules`, although this really shouldn't be considered a "workaround"
* Setting `resolve.alias['core-js']` in Webpack config

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 16.5.0 - /private/var/folders/h7/yd7dwy6x5fqgw_gkv2gb_vw80000gp/T/xfs-7eb0f9b3/node
    Yarn: 3.1.1 - /private/var/folders/h7/yd7dwy6x5fqgw_gkv2gb_vw80000gp/T/xfs-7eb0f9b3/yarn
    npm: 7.19.1 - /usr/local/bin/npm
```

**Comment by merceyz** [comment]
Your `packages/utils` workspace doesn't declare `core-js` as a dependency so the error is correct.
The solution is to either declare the dependency or make Babel inject absolute imports using `babel-plugin-polyfill-corejs3`, see https://github.com/storybookjs/storybook/pull/13055/files#diff-a55bf690f8bc8e618f5409dbb0f17b09f2dc2fa95330e5e5208136659574deef for an example

> Setting pnpMode to "loose", interestingly, does not resolve the issue.

That's because `pnpFallbackMode` prevents workspaces from using the fallbacks, add `pnpFallbackMode: none` and it will work.

**Comment by wojtekmaj** [comment]
That may be technically correct, but from dev's perspective it's extremely confusing. If not here, an action should be made elsewhere to provide helpful error messages that would allow devs to resolve this issue.

**Comment by wojtekmaj** [comment]
I have added the following to @babel/preset-env docs: https://github.com/babel/website/pull/2601

I'd appreciate if you could have a look if that's a reasonable description of the problem and how to solve it.
