### ISSUE TITLE
[Bug?]: The `yarn explain [code]` command present in the docs is not implemented

### ISSUE THREAD

**Issue by theoavoyne** [yarnpkg/berry#3929]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

The `yarn explain [code]` command present in [the docs](https://yarnpkg.com/cli/explain) is not implemented and causes an `Unknown Syntax Error: Command not found;` when ran. 

However, the `yarn explain peer-requirements` command works as expected.

### To reproduce

Run `yarn explain` or `yarn explain YN0006`.

### Environment

```shell
System:
  OS: macOS 12.0.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Binaries:
  Node: 16.13.0 - /private/var/folders/_m/hj6rftx17hl0zb66kk7y978m0000gp/T/xfs-c870b56d/node
  Yarn: 3.1.1 - /private/var/folders/_m/hj6rftx17hl0zb66kk7y978m0000gp/T/xfs-c870b56d/yarn
  npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
```

### Additional context

Should it be removed from the docs? Should it be implemented?

**Comment by arcanis** [comment]
It's available in nightly builds only at the moment (and perhaps rc).
