### ISSUE TITLE
[Feature] Add local packages from registry instead of symlink

### ISSUE THREAD

**Issue by MicMonen** [yarnpkg/berry#3966]
The situation:
I use a mono repo with yarn workspaces.
Package-1 has package-2 as a dependancy, so when I add package-2, yarn will symlink it to the local folder.

The problem:
Package-2 only has the files after a build step, this step is run before publishing the package and the build files are deleted afterwords.

The solution:
I get the package from the registry (NPM).

This is not possible at the moment as far as I know. 
Even if I add a specific version, the package is not retrieved from NPM.

**Comment by merceyz** [comment]
See https://github.com/yarnpkg/berry/discussions/3063, https://yarnpkg.com/configuration/yarnrc#enableTransparentWorkspaces, and https://yarnpkg.com/features/workspaces#workspace-ranges-workspace

**Comment by MicMonen** [comment]
> You can set `enableTransparentWorkspaces: false` in `.yarnrc.yml`, that will cause Yarn to fetch from the registry if you don't specify `workspace:` as the protocol.

I can confirm this fixes the problem.
Packages with versions prefixed with ```npm:``` should maybe always retrieve from registry regarding the setting?

> Next time, please follow the issue template. It's there for a reason.

Will do!
