### ISSUE TITLE
[Bug?]: New Github security protocol is breaking yarn install

### ISSUE THREAD

**Issue by eric-burel** [yarnpkg/berry#3969]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

New Github security protocol is breaking `yarn` install, see https://github.blog/2021-09-01-improving-git-protocol-security-github/

```
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/adobe-webplatform/eve.git
Directory: /code/geeglee-front-end
Output:
fatal: erreur distante : 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### To reproduce

I couldn't figure a reproduction yet, because the package in the error message is a sub-dependency. However you can expect a wave of devs having this issue starting today... I'll update if I get a consistent reproduction

Edit: I think installing this package should reproduce: https://github.com/bisone/raphael
Specifically this dependency: "eve": "git://github.com/adobe-webplatform/eve.git#eef80ed", using "git://" might be the problem.

### Environment

```shell
Using Node 14 and Yarn v1.22.5 via NVM, on Ubuntu 20

"yarn dlx" command doesn't exist for me sorry.
```

**Comment by arcanis** [comment]
Just replace `git://github.com/adobe-webplatform/eve.git` by `https://github.com/adobe-webplatform/eve.git`. It's not something Yarn can address (at best we could have some hardcoding to do this transform, but it would only affect newer releases, not older ones).

**Comment by eric-burel** [comment]
The problem is that you may not control the syntax if it's a nested librabry. Could a resolution work in this scenario?
