### ISSUE TITLE
Install packages through the legacy node_modules design

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/berry#4]
**Describe the user story**

I'm an application author; my current setup uses `node_modules` directories and I don't want to spend time changing that. In order to make my migration as simple as possible, I'd like Yarn to continue installing my dependencies using the traditional `node_modules` algorithm.

**Describe the solution you'd like**

Running `yarn install` should generate `node_modules` directories instead of a `.pnp.js` file. This should be configurable through the use of a configuration settings (such as `preferred-linker-node: node-modules`).

**Describe the drawbacks of your solution**

This requires the implementer to spend time on implementing this - time that won't be spent implementing new features.

This slightly waters down the long-term benefits of PnP by lowering the upgrade incentive our users might have to switch to it. How much of a concern it really is isn't clear though, especially if this behavior is hidden behind a settings or a plugin. In any case, users should be free to choose whatever approach works the best for them, and supporting the default only makes sense.

The `node_modules` install doesn't play very well in the grand vision of multi-languages dependency trees. My initial prototypes had significant issues caused by the complexity of supporting a package being installable multiple times.

**Describe alternatives you've considered**

We could suggest our users to stay on the v1 as long as they require `node_modules`. In practice this might lead to a lower adoption if people have concerns about PnP's viability *(note to anyone watching this issue: I'm not aware of any, and after having worked on it for some time now I'm more confident than ever that it solves very important problems that have been put aside for too long)*.

A middle ground option could be to add support for flat installations only. This would solve the multi-language problems (since every package would only have one single location on the disk) and would be relatively straightforward to implement, at the price of making the feature more uncomfortable for our users.

Another middle ground option could be to implement a similar installation mechanism to the one used by pnpm (ie use symlinks and hardlinks so that the packages only live once), but I'm afraid this would have pretty much the same problems than PnP with less benefits, and would be quite complex to get right (even though the pnpm folks would surely be happy to share some of their wisdom on this).

**Comment by vlasenko** [comment]
Lets assume we have a monorepo and we mark the workspace packages that need `node_modules` with `package.json -> installConfig -> pnp -> false`. `.pnp.js` is still being generated and considered the primary source of truth. 

And either `.pnp.js` microkernel has additional API function to write `node_modules` to the disk, say `setupNodeModules()`, which removes all the `node_modules` in the monorepo first and then writes `node_modules` for `pnp -> false` workspace packages with hoisting to monorepo root and all that jazz . `setupNodeModules()` implementation can also be moved to `.pnp-nm.js`, which will in turn use `.pnp.js` as a single source of truth.

This way `node_modules` can be omitted from committing to VCS and yet they can be regenerated with bit accuracy by calling `.pnp-nm.js -> setupNodeModules()`. `.pnp-nm.js` must be committed as well as `.pnp.js` and `.yarn/...` folders.

Yarn v2 users can still be able to somewhat benefit from Zero Install when using `node_modules`, if they add VCS post-checkout hook that calls `setupNodeModules()`.

**Comment by paul-soporan** [comment]
Implemented in [`plugin-node-modules`](https://github.com/yarnpkg/berry/tree/master/packages/plugin-node-modules).

**Comment by SudoNova** [comment]
> Implemented in [`plugin-node-modules`](https://github.com/yarnpkg/berry/tree/master/packages/plugin-node-modules).

Can you update your comment for the reason of confused ones like me? The link mentioned doesn't exist anymore and `plugin-node-modules` is not documented [here](https://yarnpkg.com/features/plugins)
