### ISSUE TITLE
[Bug?]: VSCode cannot find module with yarn berry's pnp and typescript on WSL2

### ISSUE THREAD

**Issue by Phryxia** [yarnpkg/berry#4001]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I created a project using yarn berry's pnp feature on. But when I clone the project at other device, vscode complains that it can't find module (or even typescript lib). If you follow the reproduction sequences, you'll get these messages.

```
File '//wsl$/Ubuntu-20.04/home/sekyukwon/dev/my/auto-proof/.yarn/cache/typescript-patch-0b90225f97-2e488dde7d.zip/node_modules/typescript/lib/lib.dom.d.ts' not found.
  The file is in the program because:
    Library 'lib.dom.d.ts' specified in compilerOptions

Cannot find module 'react-dom' or its corresponding type declarations.
Cannot find module 'react/jsx-runtime' or its corresponding type declarations.
Cannot find name 'document'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
```

I've already asked to vscode team (https://github.com/microsoft/vscode/issues/141043#issuecomment-1018038335) and they said maybe it's yarn's typescript server problem.

Did I make a mistake?

### To reproduce

- Open WSL2
- Clone this project please (https://github.com/Phryxia/auto-proof)
- Execute `yarn`
- Open any tsx file on vscode
- Open tsconfig.json
- Wait until seeing above messages.

### Environment

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.5 - /tmp/xfs-04eae80f/node
    Yarn: 3.1.1 - /tmp/xfs-04eae80f/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v14.17.5/bin/npm
```

### Additional context

Note that the environment above is the outcome of **execution in Win10's WSL2**.

Also I've done following things:

- Executed yarn dlx @yarnpkg/sdks vscode and check `typescript.tsdk` in .vscode/settings.json
- Use typescript with workspace version on vscode
- Use ZipFs extension
- Note that `typescript-patch-0b90225f97-2e488dde7d.zip` file does exists.

**Comment by hmnd** [comment]
Experiencing this as well.

**Comment by merceyz** [comment]
This specific issue will be fixed by https://github.com/yarnpkg/berry/pull/4005 but I suggest using the [Remote - WSL extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) instead of UNC paths.
