### ISSUE TITLE
[Bug?]: OptionalDependencies check failed if the package is not published (404)

### ISSUE THREAD

**Issue by h-a-n-a** [yarnpkg/berry#4027]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Install a package which has unpublished optinalDependencies(based on cpu arch) and it fails as the package is not published(freebsd), but which can be successfully installed with `npm` / `pnpm`(with macOS aarch darwin) 

### To reproduce

```bash
yarn install @speedy-js/source-map@0.1.2
```
Currently a new fix is published for source-map, however this can also be reproduced by creating any optionalDependencies that has not been published.

### Environment

```shell
System:
   OS: macOS 12.1
   CPU: M1
Binaries:
   Node: v14.18.3
   NPM: v6.14.5
   yarn: 1.12.17
```

**Comment by arcanis** [comment]
That's intended - if a package cannot be resolved, we cannot ensure that the behaviour is deterministic. Optional dependencies only affect the build (and to some extent the link, depending on the platform), not the resolution.

**Comment by h-a-n-a** [comment]
> That's intended - if a package cannot be resolved, we cannot ensure that the behaviour is deterministic. Optional dependencies only affect the build (and to some extent the link, depending on the platform), not the resolution.

Probably we can resolve other published packages and find if it meets the condition or not?
