### ISSUE TITLE
[Bug?]: Dynamic ES module import in `.cjs` file not working with PnP

### ISSUE THREAD

**Issue by tavoyne** [yarnpkg/berry#4034]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Note: this looks similar to #3671 and #3687 but wasn't fixed by #3667.

I'm getting the following error when using the `@mdx-js/loader@2.0.0-rc.2` Webpack loader:
```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/blackjelly/code/mdx-pb/.yarn/__virtual__/@mdx-js-loader-virtual-079d9df3b5/0/cache/@mdx-js-loader-npm-2.0.0-rc.2-eb4487e27d-5637b8d92c.zip/node_modules/@mdx-js/loader/lib/index.js' imported from /Users/blackjelly/code/mdx-pb/.yarn/__virtual__/@mdx-js-loader-virtual-079d9df3b5/0/cache/@mdx-js-loader-npm-2.0.0-rc.2-eb4487e27d-5637b8d92c.zip/node_modules/@mdx-js/loader/index.cjs
```

But the module [does exist](https://unpkg.com/browse/@mdx-js/loader@2.0.0-rc.2/). 

If I switch to a `node-modules` linker, then it compiles successfully.

I believe it has to do with the dynamic import of an ES module in [the package's entry point](https://github.com/mdx-js/mdx/blob/main/packages/loader/index.cjs).

### To reproduce

Clone [this repository](https://github.com/tavoyne/mdx-pb) (it's a minimal example).

Run `yarn webpack`.

### Environment

```shell
System:
  OS: macOS 12.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Binaries:
  Node: 16.13.2 - /private/var/folders/_m/hj6rftx17hl0zb66kk7y978m0000gp/T/xfs-2ff2f68f/node
  Yarn: 3.2.0-rc.12 - /private/var/folders/_m/hj6rftx17hl0zb66kk7y978m0000gp/T/xfs-550fed4e/yarn
  npm: 8.3.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
```

**Comment by merceyz** [comment]
Your reproduction works after running `yarn` in it

**Comment by tavoyne** [comment]
Woow, that's true. I apologise for the trouble. #3667 indeed fixed the thing.
