### ISSUE TITLE
[Bug?]: Cannot run bin bash scripts

### ISSUE THREAD

**Issue by ilijapuaca** [yarnpkg/berry#4067]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

After upgrading go Yarn v3, we are not able to run shell scripts that another package provides as binaries. There seems to be an issue with comment parsing where the parsing fails when a valid comment line is encountered (starting with `#`)
```
# This is a comment
^

SyntaxError: Invalid or unexpected token
```

Not using the comments seems to avoid the issue, as well as using Javacript style comments (`//`) surprisingly, which is an invalid syntax for bash

### To reproduce

Source package script and package.json
```sh
#!/bin/bash
# This is a comment
echo "Foo"
```
```json
{
  ...
  "name": "repro-package",
  "bin": {
    "repro-issue": "./scripts/repro.sh"
  }
```

Destination package usage and package.json
```json
{
  ...
  "workspaces": {
    "packages": ["submodule"]
  },
  "dependencies": {
    "repro-package": "*",
  },
  "scripts": {
    "repro": "repro-issue"
  }
}
```

```sh
yarn install
yarn repro
```

Results in
```
# This is a comment
^

SyntaxError: Invalid or unexpected token
```

Running the script directly works just fine
```sh
./submodule/scripts/repro.sh
Foo
```

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 14.18.1 - /private/var/folders/mf/v5jl1zvn26qb7866ymdqn48h0000gn/T/xfs-a9cb933c/node
    Yarn: 3.1.1 - /private/var/folders/mf/v5jl1zvn26qb7866ymdqn48h0000gn/T/xfs-a9cb933c/yarn
    npm: 6.14.15 - ~/.volta/tools/image/node/14.18.1/bin/npm
```

**Comment by arcanis** [comment]
This is a known limitation at this time: bin entries must be Node scripts.

**Comment by ilijapuaca** [comment]
Has this been documented somewhere as a change/regression from v1? I searched for a similar issue in the repo but did not find one.

Will close this one though as it doesn't seem to be considered a bug

**Comment by spion** [comment]
I think it should be OK to reopen this - while it may be a common limitation, its a backwards incompatibility which prevents migration to yarn v3

**Comment by serhiipalash** [comment]
@spion is it fixed in upcoming Yarn v4? Maybe I can migrate our app to v4-rc and make it work with Bash binary?

**Comment by serhiipalash** [comment]
@spion 

I ended up with replacing bash binary in package.json with JS with this code

```
#!/usr/bin/env node
const path = require('path')
const live = require('shelljs-live')

const statusCode = live([
  path.join(__dirname, 'tools.sh'),
  ...process.argv.slice(2),
])

if (statusCode === 0) {
  process.exit(0)
} else {
  process.exit(1)
}
```

Everything works in exact way as with Bash binary, including colors.

**Comment by spion** [comment]
Except for startup time and memory usage - Bash starts in a couple of miliseconds and takes about 5MB of RAM whereas node needs ~150ms and takes additional 50-100MB of RAM per process.

Not a big deal on individual projects, but on a monorepo with 30 packages thats easily an additional 2GB-3GB of RAM doing absolutely nothing.
