### ISSUE TITLE
[Bug]: Unable to install dependencies 

### ISSUE THREAD

**Issue by X4V1** [yarnpkg/berry#4075]
### Describe the bug

I started a projet yars ago and I'm not able to run the `yarn` to install dependencies.

### To reproduce

Cloned a projet and typed `yarn`

### Environment

```shell
Hardware: Raspberry PI 3B+
OS: Raspberry PI OS (debian 11)
node: 17.4
npm: 8.4.1
yarn: 1.22.17
```

### Additional context

![yarn issue](https://user-images.githubusercontent.com/15031703/152695235-44183699-e20e-44f2-8595-da6b1554c3da.png)

**Comment by arcanis** [comment]
Not enough memory.
