### ISSUE TITLE
[Bug?]: workspace protocol is not replaced for optional dependencies

### ISSUE THREAD

**Issue by bengsfort** [yarnpkg/berry#4080]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

When using the workspace protocol with an optional dependency, the protocol is never replaced with the local version when packed/published (leaving your production package with a `workspace:` dependency). However, it appears that he optional dependency gets injected into the normal dependencies with the correctly local version. Consuming the affected package of course leads to yarn erroring out on install as it cannot find the workspace the package is referring to.

### To reproduce

I have created an example repo [here](https://github.com/bengsfort/borked-optional-workspace-deps).  Here is a simplified example:

Example affected workspace hierarchy
```
├── README.md
├── package.json
├── packages
│   ├── main
│   │   ├── README.md
│   │   ├── package.json
│   ├── optional
│   │   ├── README.md
│   │   └── package.json
│   └── required
│       ├── README.md
│       └── package.json
└── yarn.lock
```

Where the `main` package has the following `package.json`:

```json packages/main/package.json
{
  "name": "main",
  "packageManager": "yarn@3.1.1",
  "dependencies": {
    "required": "workspace:*"
  },
  "optionalDependencies": {
    "optional": "workspace:*"
  }
}
```

After running `yarn pack`, the resulting `package.json` within the bundle will be as follows:
```json result
{
  "name": "main",
  "packageManager": "yarn@3.1.1",
  "dependencies": {
    "required": "0.0.0",
    "optional": "0.0.0"
  },
  "optionalDependencies": {
    "optional": "workspace:*"
  }
}
```

I can try writing up a Sherlock if it helps.

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.13.0 - /private/var/folders/hd/4h7bzw1s2f5_c3ftbltbgmlc0000gn/T/xfs-59ac9481/node
    Yarn: 3.1.1 - /private/var/folders/hd/4h7bzw1s2f5_c3ftbltbgmlc0000gn/T/xfs-59ac9481/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
```

### Additional context

At first I was unsure if it was intended that the `workspace` protocol seemingly only works for dependencies and devDependencies, however there are legitimate use cases for it with optional dependencies as well. For example, if you have a monorepo with platform-specific modules that you include as optional dependencies in your main published package, which is my use case. 

It's very curious that the optional dependency does make its way into the dependencies with the correct version, just not back to optional dependencies. I would be willing to implement a fix, but may need some guidance and a poke in the right direction as I am unfamiliar with the codebase.

**Comment by bengsfort** [comment]
Looks like it's simply a matter of adding `optionalDependencies` to the `DEPENDENCY_TYPES` array in the `pack` plugin:

https://github.com/yarnpkg/berry/blob/a73c6c9fb4be9e78ba8c1af1a0f5da7b46551fcc/packages/plugin-pack/sources/index.ts#L21

From checking the code I don't think it would affect anything else, but hard to know. I can try to pull everything down and make the change to see if it has any unwanted side-effects at lunch.

**Comment by arcanis** [comment]
I think something like this [here](https://github.com/yarnpkg/berry/blob/master/packages/plugin-pack/sources/index.ts#L73) should do the trick; along with a test we'd certainly be happy to see a PR!

```ts
const finalDependencyType = dependencyType === `dependencies` && workspace.manifest.ensureDependencyMeta(descriptor).optional
  ? `optionalDependencies`
  : dependencyType;
```

**Comment by bengsfort** [comment]
Ahh this is way better than what I was experimenting with locally 😄 Will give this a go and try to get a PR in. Thanks!

**Comment by bengsfort** [comment]
Tried the above but it looks like there is a bit more to it. What I noticed with the above is that `ensureDependencyMeta` seems to throw quite often there due to there not always being valid semver rank with the descritor:

```
Error: Invalid meta field range for '@test/dependency@workspace:^1.0.0'
```

I also tried using `project.getDependencyMeta` which at least wasn't throwing anymore, but had the issue of it seemingly not finding the correct meta as the error still persisted.

After looking at how the optional dependencies are stored and noticed that when the meta is stored it is with a descriptor that made using `unknown`, and doing something similar here _does_ in fact fix it, however it feels a bit hacky? 

```ts
// Ensure optional dependencies are handled as well
const identDescriptor = structUtils.makeDescriptor(descriptor, `unknown`);
const finalDependencyType = dependencyType === `dependencies` && workspace.manifest.ensureDependencyMeta(identDescriptor).optional
  ? `optionalDependencies`
  : dependencyType;
rawManifest[finalDependencyType][structUtils.stringifyIdent(descriptor)] = versionToWrite;
```

Wondering if there is maybe a better way to do this or maybe I am missing something, as everything else in the function seems so straight forward that this feels a bit Iike I'm doing something I shouldn't do.

Also please let me know if I should move this discussion to a PR!
