### ISSUE TITLE
[Bug] sqlite3 fail to install

### ISSUE THREAD

**Issue by Embraser01** [yarnpkg/berry#41]
**Describe the bug**

When installing `sqlite3` we get an error at _Link Step_.

**To Reproduce**

You can clone [Embraser01/scratch-repo
](https://github.com/Embraser01/scratch-repo) and run `yarn install`

**Environment if relevant (please complete the following information):**

 - OS: Windows and WSL (Ubuntu)
 - Node version v10.15.0
 - Yarn version current master

**Additional context**

stdout:

```
➤ BR0013: │ wrappy@npm:1.0.2 can't be found in the cache and will be fetched from the remote registry
➤ BR0013: │ yallist@npm:3.0.3 can't be found in the cache and will be fetched from the remote registry
➤ BR0000: └ Completed in 8.88s
➤ BR0000: ┌ Link step
➤ BR0001: │ Error: ENOTDIR: not a directory, scandir 'node_modules/sqlite3/cloudformation'
    at ZipFS.readdirSync (N:\scratch-repo\.yarn\releases\yarn-berry.js:2153:33)
    at ZipFS.readdirPromise (N:\scratch-repo\.yarn\releases\yarn-berry.js:2145:21)
    at NodeFS.copyPromise (N:\scratch-repo\.yarn\releases\yarn-berry.js:825:51)
➤ BR0000: └ Completed in 0.03s
➤ BR0000: Failed with errors in 11.82s
```

It seems that `ZipFS` doesn't consider empty directory as a directory but I'm not sure!

Can it be because in `ZipFS#registerListing` we add a directory to `this.listings` from the child element (so with en empty directory, there is not child elements who add it)?

**Comment by arcanis** [comment]
Good catch! I think you're right - according to the libzip folders seem to be [regular files with a `/` as final character](https://github.com/nih-at/libzip/blob/master/lib/zip_dir_add.c#L63-L71). We should use this heuristic in the [initial crawl](https://github.com/yarnpkg/berry/blob/master/packages/berry-fslib/sources/ZipFS.ts#L150) to call `registerListing` on such paths.

**Comment by Embraser01** [comment]
Ok, I can make a PR if you're not already on it

**Comment by arcanis** [comment]
Go for it 👍
