### ISSUE TITLE
[Bug?]: Hoisting not working as expected

### ISSUE THREAD

**Issue by bfanger** [yarnpkg/berry#4122]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

`@storybook/client-api` is installed multiple times leading to multiple disconnected "singletons" and a broken storybook installation.

https://github.com/eirslett/storybook-builder-vite/issues/50

### To reproduce

.yarnrc.yml
```
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs
```

package.json
```json
{
  "name": "yarn-dedupe-bug",
  "version": "0.0.0",
  "workspaces": [
    "example-svelte"
  ],
  "dependencies": {
    "@storybook/react": "^6.4.0",
    "react": "17.0.2"
  }
}
```
example-svelte/package.json
```json
{
  "name": "example-svelte",
  "private": true,
  "version": "0.0.0",
  "devDependencies": {
    "@storybook/svelte": "^6.4.0"
  }
}
```

Run `yarn install` and you'll get two installations of `@storybook/client-api` instead of one.

```
./node_modules/@storybook/svelte/node_modules/@storybook/client-api
./node_modules/@storybook/client-api
```
identical version of the package but different paths.

### Environment

```shell
System:
    OS: macOS 11.6.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  Binaries:
    Node: 17.5.0 - /private/var/folders/b2/sc47jtm97zl1m30n6y4j_4xr0000gn/T/xfs-4b594da6/node
    Yarn: 3.1.1 - /private/var/folders/b2/sc47jtm97zl1m30n6y4j_4xr0000gn/T/xfs-4b594da6/yarn
    npm: 8.4.1 - /usr/local/bin/npm

(Yarn: 3.2.0-rc.15 also has this issue)
```

**Comment by merceyz** [comment]
Please provide a cloneable reproduction. Without the lockfile this can stop reproducing at any moment.

**Comment by merceyz** [comment]
I'm assuming that repo will change at some point so adding a permalink to its current state
https://github.com/eirslett/storybook-builder-vite/tree/89e6b7c5fe754bcb5e2e8bdb600140688fa8950e

**Comment by larixer** [comment]
Not a bug, hoisting works as expected.

I have checked the repo at:
https://github.com/eirslett/storybook-builder-vite/tree/89e6b7c5fe754bcb5e2e8bdb600140688fa8950e

`@storybook/client-api` peer depends on `react`.

`@storybook/svelte@6.4.3` depends on `@storybook/client-api` and `react@16.14.0`. But your workspaces depend on `@storybook/client-api` and `react@17.0.2`. This can be easily discovered via `yarn why -R @storybook/client-api` and `yarn why -R react`.  Thats why Yarn have to create two copies of `@storybook/client-api` - the first copy which uses  `react@16.14.0` and the other copy which uses `react@17.0.2`

**Comment by bfanger** [comment]
Thanks, is there a way to force only one `@storybook/client-api` folder?

**Comment by arcanis** [comment]
You can use `packageExtensions` in your yarnrc to add peerDependencies on `react` and `react-dom` to `@storybook/svelte`

**Comment by Enteleform** [comment]
@arcanis

There seems to be a similar issue between `astro`, `@astrojs/renderer-solid`, & `solid-js`.

I'm using the [astro/examples/framework-multiple](https://github.com/withastro/astro/tree/main/examples/framework-multiple) project as a baseline.

-----

By default, it uses `yarn@^1`, which is where I first encountered the issue:
```log
You appear to have multiple instances of Solid. This can lead to unexpected behavior.
```

I then tried using `yarn@^3`, and the same issue occured.

Adding the following to `yarn@^3` finally resolved the issue:
```yaml
packageExtensions:

  "astro@*":
    dependencies:
      solid-js: "1.3.7"
    peerDependencies:
      solid-js: "*"

  "@astrojs/renderer-solid@*":
    dependencies:
      solid-js: "1.3.7"
    peerDependencies:
      solid-js: "*"
```

-----

Is there a way to resolve this issue for `yarn@^1`?
