### ISSUE TITLE
[Bug]: `yarn workspaces foreach` implicitly has `--jobs` set to 2 when run via docker

### ISSUE THREAD

**Issue by lensbart** [yarnpkg/berry#4147]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

The behaviour of `yarn workspaces foreach --interlaced --parallel --verbose run dev` differs depending on whether I run the command directly in my terminal, or via `docker-compose up`.

I have three packages that implement a `dev` script,
* all three of them run when I execute the script above via the node script in the terminal
* only two get run when I execute the script above by specifying it in `docker-compose.yml` and running it via `docker compose up`.

If this is the desired behaviour, I think the docs would benefit from specifying it.

Workaround: setting the `--jobs unlimited` option

### Environment

```shell
System:
    OS: macOS 12.2
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 14.16.0 - /private/var/folders/dk/h4tc0zx90g9fdr9pbw48k6pr0000gn/T/xfs-e73e6747/node
    Yarn: 3.1.1 - /private/var/folders/dk/h4tc0zx90g9fdr9pbw48k6pr0000gn/T/xfs-e73e6747/yarn
    npm: 6.13.7 - /usr/local/bin/npm
```

Thank you!

**Comment by seansfkelley** [comment]
The [docs](https://yarnpkg.com/cli/workspaces/foreach#details) do specify it, but not directly next to the flag's definition so it can be missed:

> If -p,--parallel is set, the commands will be ran in parallel; they'll by default be limited to a number of parallel tasks roughly equal to half your core number, but that can be overridden via -j,--jobs, or disabled by setting -j unlimited.

Presumably your Docker is configured to use less than all your cores.

**Comment by lensbart** [comment]
Thanks for that information.

Maybe I don’t see the full picture, but I think `unlimited` is a much better default, especially considering that some jobs won’t run at all if the `jobs` limit is lower than the number of processes being run in watch mode.

**Comment by arcanis** [comment]
> Maybe I don’t see the full picture, but I think `unlimited` is a much better default, especially considering that some jobs won’t run at all if the `jobs` limit is lower than the number of processes being run in watch mode.

`unlimited` is a bad default since it may crash or heavily slow down machines, especially laptops. Even on CI tools generally prefer to keep some upper boundary to avoid congesting the CPU, as there are often other processes running in parallel.
