### ISSUE TITLE
[Bug] Installing Yarn v2 does not work behind a proxy

### ISSUE THREAD

**Issue by accidentaldeveloper** [yarnpkg/berry#415]
**Describe the bug**

Running `yarn policies set-version v2` hangs indefinitely when run behind a proxy. This is the only output:
```
Resolving v2 to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
```

Running `yarn policies set-version v1.17.3` works without issue. 

I have set my proxy variables appropriately (`httpproxy`, `httpsproxy`)

**To Reproduce**

Attempt to install v2 behind a proxy

** Environment**
Run using Yarn 1.17.3

**Comment by arcanis** [comment]
That's quite weird, the code for downloading the v1 and v2 releases is the same, and it's also the component used to make the registry requests 🤔

https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/policies.js#L147

**Comment by accidentaldeveloper** [comment]
I agree. I don't know what the distinction is, but when I go on a network
where the proxy is not necessary the problem disappears.

**Comment by accidentaldeveloper** [comment]
Perhaps it's something specific to my proxy. I will investigate more.

**Comment by accidentaldeveloper** [comment]
The issue appears to have resolved itself. I tested again this morning and the command ran perfectly. 🤦‍♂️ Perhaps it was something with my proxy specifically.

I apologize for filing this bug unnecessarily. 😞

**Comment by arcanis** [comment]
No worry, glad it works! 👍

**Comment by accidentaldeveloper** [comment]
Follow up: I am experiencing this behavior behind the proxy again. 

I'm still learning a lot about networking and proxies but I have an idea how to debug this. 

Can you help me understand: How does yarn pull in proxy configuration? Does it use the http_proxy and https_proxy environment variables?

**Comment by merceyz** [comment]
> Can you help me understand: How does yarn pull in proxy configuration? Does it use the http_proxy and https_proxy environment variables?

A bit late but no, it uses the `httpProxy` and `httpsProxy` values in `.yarnrc.yml`

**Comment by freed00m** [comment]
@merceyz  Oh?, how is that an acceptable behavior?

project specific .yarnrc.yml suppose to be versioned and not everyone shares the same proxy right?

CI runners populates environment variables so we are now suppose to do some weird value modification of a file?

**Comment by arcanis** [comment]
No, but per the documentation:

> Finally, note that most settings can also be defined through environment variables (at least for the simpler ones; arrays and objects aren't supported yet). To do this, just prefix the names and write them in snake case: YARN_CACHE_FOLDER will set the cache folder (such values will overwrite any that might have been defined in the RC files - use them sparingly).

Thus, if you wish to set a proxy for Yarn, just set `YARN_HTTP_PROXY` in your environment.

**Comment by accidentaldeveloper** [comment]
I certainly appreciate that yarn has configuration to specify a proxy. 

On the other hand, I believe that it would be wise to use the HTTP_PROXY environment variable if it is present. Almost every command line tool I use recognizes these variables and uses them for requests

Have we considered supporting this "standard" approach?

**Comment by arcanis** [comment]
> Have we considered supporting this "standard" approach?

Yes, but there's in the end little value for us in supporting multiple ways to do the same thing. If you feel strongly about this, you can add the following to your home `.yarnrc.yml`.

```yml
httpProxy: "${http_proxy}"
```

In a sense it's the same reason why we don't read the `.npmrc` anymore. Yes, we could, but we now strongly want to avoid reading configuration settings from many places with different levels of priorities. One set of rules is simply easier to maintain.

**Comment by olivierlacan** [comment]
Very importantly, since many people are likely to be dealing with HTTPS with their proxy settings, you'll need to add you proxy URL for HTTPS as well:

In `~/.yarnrc.yml`:

```
# This file is *not* auto-generated unlike its Yarn v1 equivalent

# https://github.com/yarnpkg/berry/issues/415#issuecomment-756178343
httpProxy: "http://<IP_ADDRESS>:<PORT>"
httpsProxy: "http://<IP_ADDRESS>:<PORT>"
```

Added literal string examples because @arcanis's comment made it seem like you could leverage an existing environment which as far as I could tell is not the case.
