### ISSUE TITLE
[Bug?]: Yarn 3.2.0 jest tests timeout in CI

### ISSUE THREAD

**Issue by franciscofabian** [yarnpkg/berry#4157]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Running jest tests in CI always timeout (10 minutes) with yarn 3.2.0, running with 3.1.1 and earlier versions it finishes in less than 10 seconds.

### To reproduce

`yarn jest`

### Environment

```shell
CircleCI 2.1
```

**Comment by RDIL** [comment]
Can you please provide a repository which exhibits the behavior?

**Comment by franciscofabian** [comment]
I have fixed the issue adding the option `--maxWorkers=1` in jest. I tried to set up a new repository to reproduce the behavior but with the same code an setup and couldn't reproduce, I'm not sure why yet. Is there any change in yarn 3.2.0 that could had caused the process not to exit when running in multiple workers?

**Comment by psychobolt** [comment]
I think I am also seeing the same issue on the rollup-terser-plugin, which utilizes jest workers as well... hmm

**Comment by arcanis** [comment]
Does it work if you either disable esm support in your yarnrc, or upgrade to the very latest Node 16.x release?

**Comment by franciscofabian** [comment]
Yes! It works for me either disabling esm support in my yarmrc or upgrading to the latest Node (v16.14.0 from v16.2.0)

**Comment by arcanis** [comment]
Then it's caused by https://github.com/nodejs/node/issues/41134

More details in this other thread: https://github.com/vercel/next.js/pull/34688#issuecomment-1047994505

**Comment by merceyz** [comment]
This issue was fixed in https://github.com/nodejs/node/pull/41221 which has shipped in Node.js v16.14 and v17.4.

**Comment by sublimator** [comment]
> This issue was fixed in https://github.com/nodejs/node/pull/41221
Will this be fixed in 14 LTS ?

**Comment by merceyz** [comment]
I don't know, this is the wrong place to ask

**Comment by sublimator** [comment]
Fair enough, thanks
