### ISSUE TITLE
[Bug]: workspace-tools plugin has issue where it cannot run commands containing semicolons

### ISSUE THREAD

**Issue by gabrielbull** [yarnpkg/berry#4224]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Cannot run commands that contain semicolon using `yarn workspaces foreach run`. Gets this error:

```
➤ YN0000: Usage Error: Couldn't find a script named "test:coverage".
➤ YN0000:
➤ YN0000: $ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
➤ YN0000: Done in 13s 486ms
```

### To reproduce

```bash
yarn workspaces foreach run test:coverage
```

### Environment

```shell
System:
    OS: macOS 12.2.1
    CPU: (16) x64 Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
  Binaries:
    Node: 17.2.0 - /private/var/folders/44/r0rw1tc537n8yfg_q8_1wczc0000gn/T/xfs-8675fb11/node
    Yarn: 3.2.0 - /private/var/folders/44/r0rw1tc537n8yfg_q8_1wczc0000gn/T/xfs-8675fb11/yarn
    npm: 8.1.4 - /usr/local/bin/npm
```

**Comment by merceyz** [comment]
Seems like a duplicate of https://github.com/yarnpkg/berry/issues/3048 but since you didn't provide a reproduction I can't verify.

**Comment by gabrielbull** [comment]
@merceyz It is the same issue. Why was the original closed if it is still an issue with the latest yarn?

**Comment by merceyz** [comment]
The original was closed because I fixed it and we have tests ensuring it still works.
You might have forgotten to update the plugin but without a reproduction I can't verify that.
```sh
yarn plugin import workspace-tools
```

**Comment by gabrielbull** [comment]
Ah that was it. Sorry for the trouble and thanks for the help.

**Comment by JoseFdri** [comment]
I just bumped yarn to 4.2.2 and this bug is still present
