### ISSUE TITLE
[Bug?]: yarn set version berry: Tag stable not found

### ISSUE THREAD

**Issue by bangbaew** [yarnpkg/berry#4234]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Normally, I can run `yarn set version berry` or `yarn set version stable` and it would pull yarn v3 (yesterday it pulled 3.2.0), but today (17-03-2022), it logged `Tag stable not found`, so I tried `yarn set version stable` but it pulled Yarn 1.22.18, Is there any solution to the problem?

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/29559559/158763971-607e9407-c1f9-4d1c-8b16-19b2de899123.png">

### To reproduce

Run `yarn set version berry` or `yarn set version stable`

### Environment

It logged `error: Command "dlx" not found.` but the environment is Docker image node:alpine on macOS 12.2.1 i5-10400
it also happens on Windows 10.

But this is logged from another container that I've previously set version yesterday:
```shell
  System:
    OS: Linux 5.4 Alpine Linux
    CPU: (6) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
  Binaries:
    Node: 17.7.1 - /tmp/xfs-43145e21/node
    Yarn: 3.2.0 - /tmp/xfs-43145e21/yarn
    npm: 8.5.2 - /usr/local/bin/npm
```

**Comment by yorch** [comment]
You have a typo on your command (screenshot), you are running: `yarn set verstion stable` (notice `verstion`)

**Comment by bangbaew** [comment]
> You have a typo on your command (screenshot), you are running: `yarn set verstion stable` (notice `verstion`)

I think the repo for berry was down that time, but it was fixed now, thanks anyway.

**Comment by merceyz** [comment]
GitHub had an outage around that date so that might have been it.
https://www.githubstatus.com/incidents/sksd097hm0y5

**Comment by dylanh724** [comment]
Was there another outage today? I found this right at the top of Google.

`yarn set version stable`

> error An unexpected error occurred: "Release not found: stable".
info If you think this is a bug, please open a bug report with the information provided in "/mnt/c/Repos/home/myProj/yarn-error.log".    

> Trace: 
  Error: Release not found: stable
      at /home/{myUser}/.yarn/releases/yarn-1.22.11.cjs:98340:17
      at Generator.next (<anonymous>)
      at step (/home/{myUser}/.yarn/releases/yarn-1.22.11.cjs:310:30)
      at /home/{myUser}/.yarn/releases/yarn-1.22.11.cjs:321:13
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
