### ISSUE TITLE
[Bug?]: Windows 11 Execution Policy issue

### ISSUE THREAD

**Issue by hades200082** [yarnpkg/berry#4249]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I've just installed NodeJS 16.14.2 on my newly installed Windows 11 development PC.

I ran the command `npm install --global yarn` to install yarn.

When I run `yarn --version` I get the error "yarn : File d:\Program Files\nodejs\yarn.ps1 cannot be loaded. The file d:\Program Files\nodejs\yarn.ps1 is not digitally signed. You cannot run this script on the current system."

I understand how to use `Set-ExecutionPolicy` to get around this, but my organisation locks this down to "AllSigned" with group policy preventing me from changing it.

Is it possible to get this powershell script digitally signed for the community? If not I guess my team just can't use yarn :(

### To reproduce

See description above.

### Environment

```shell
I can't run yarn commands as described above.

This is a Windows 11 Pro PC.
```

**Comment by merceyz** [comment]
That file is created by `npm` so you'll have to open an issue with them.
