### ISSUE TITLE
[Feature] Add Yarn Modern / Classic / Corepack to CITGM

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/berry#4263]
CITGM is https://github.com/nodejs/citgm, a collection of third-party packages that Node runs against to spot regressions.

We're not covered yet, and it'd be really good to be in it. The Node maintainers have expressed support for that.

**Comment by edvardchen** [comment]
I can help on this. @arcanis I will submit a PR in https://github.com/nodejs/citgm later and plz help review

**Comment by edvardchen** [comment]
Here is the MR https://github.com/nodejs/citgm/pull/905

**Comment by merceyz** [comment]
Closing as https://github.com/nodejs/citgm/pull/905 has been merged.

**Comment by arcanis** [comment]
Thanks a lot @edvardchen !

**Comment by edvardchen** [comment]
glad to see it merged.
