### ISSUE TITLE
[Bug?]: Yarn classic is down

### ISSUE THREAD

**Issue by volkyeth** [yarnpkg/berry#4274]
### Describe the bug

Looks like the yarn classic releases server https://nightly.yarnpkg.com is down:

```zsh
$ yarn set version classic
➤ YN0000: Retrieving https://nightly.yarnpkg.com/latest.js
➤ YN0035: The remote server failed to provide the requested resource
➤ YN0035:   Response Code: 530
➤ YN0035:   Request Method: GET
➤ YN0035:   Request URL: https://nightly.yarnpkg.com/latest.js
➤ YN0000: Failed with errors in 0s 121ms
```

### To reproduce

```bash repro
yarn set version classic
```

### Environment

```shell
System:
    OS: macOS 12.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.10.0 - /private/var/folders/2c/fb8vyvw95fv17qwxz7s97vf00000gn/T/xfs-f1c105e3/node
    Yarn: 3.2.0 - /private/var/folders/2c/fb8vyvw95fv17qwxz7s97vf00000gn/T/xfs-f1c105e3/yarn
    npm: 8.5.1 - ~/.nvm/versions/node/v16.10.0/bin/npm
```

**Comment by arcanis** [comment]
cc @Daniel15

**Comment by Daniel15** [comment]
I'll take a look shortly. Not sure what could have happened here.
-- 
Regards,
Daniel Lo Nigro
https://d.sb[https://d.sb/]

Sent from my phone

Mar 26, 2022 10:35:20 AM Maël Nison ***@***.***>:

**Comment by Daniel15** [comment]
Sorry about that! It should be fixed now.

I'm in the process of moving one of my servers to another (consolidating). The Yarn Nightly site is on this server, and it's the one of the only sites I haven't yet migrated across. It looks like while migrating another site I accidentally deleted the DNS record for the Yarn site. It's fixed now! I'll add some monitoring for the Yarn Nightly site so I'm notified if it goes down. 😅

**Comment by Daniel15** [comment]
@volkyeth I've moved the `nightly.yarnpkg.com` site to another server, and double-checked it, and it seems to be fine.  Please let me know if you see any weirdness with it.
