### ISSUE TITLE
[Bug?]: ZipFS extension broken on VSCode 1.66

### ISSUE THREAD

**Issue by kidonng** [yarnpkg/berry#4304]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

They break it again™️ (previously: #3539)

```
Unable to open 'index.d.ts': Unable to read file 'zip://users/kid/Developer/react-parcel-play/.yarn/cache/preact-npm-10.7.0-6d31f88d66-fd0c016437.zip/node_modules/preact/src/index.d.ts' (Error: ENOENT: no such file or directory, stat '/kid/Developer/react-parcel-play/.yarn/cache/preact-npm-10.7.0-6d31f88d66-fd0c016437.zip/node_modules/preact/src/index.d.ts').
```

I assume this is more like a VSCode issue rather than TS issue since they bumped the Electron from 13 to 17.

### To reproduce

1. Install ZipFS extension (v2.3.0) on VSCode (1.66.0)
2. Install TypeScript (4.6.3)
3. Enable VSCode SDK via `yarn dlx @yarnpkg/sdks vscode`
4. Install some package with types and try "Go to definition"

### Environment

```shell
System:
    OS: macOS 12.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 17.8.0 - /private/var/folders/x5/9rywd94n2qdbvjs0sj59g4800000gn/T/xfs-bc5e87c9/node
    Yarn: 3.2.0 - /private/var/folders/x5/9rywd94n2qdbvjs0sj59g4800000gn/T/xfs-bc5e87c9/yarn
    npm: 8.5.5 - /usr/local/bin/npm
```

**Comment by arcanis** [comment]
This might be caused by https://github.com/microsoft/vscode/commit/e04c70a676898301b543bd59147e1bfb033d8fb9

**Comment by TkaczykAdam** [comment]
Is this fix on production? How can I update the extension? :/

**Comment by TkaczykAdam** [comment]
Wow, lightning-fast fix, thank you <3

**Comment by SchoofsKelvin** [comment]
If running `yarn dlx @yarnpkg/sdks` doesn't seem to immediately fix it, **restart VSCode**. Just using the "TypeScript: Restart TS server" command or switching TS version to built-in and back to workspace-provided doesn't do the trick, After rerunning `@yarnpkg/sdks`, it still kept erroring for me until I reloaded the window.

**Comment by ayyjohn** [comment]
I was having issues with this because of a `.yarnrc.yml` issue where certain codes were defined as `level: error`

```
logFilters:
  - code: YN0068
    level: error
  - code: YN0069
    level: error
  - code: YN0002
    level: error
  - code: YN0060
    level: error
```

commenting these out and running `yarn dlx @yarnpkg/sdks` then uninstalling and reinstalling the zipfs extension and restarting vscode fixed it for me!
