### ISSUE TITLE
[Bug?]: use error package version

### ISSUE THREAD

**Issue by busyhe** [yarnpkg/berry#4333]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

![image](https://user-images.githubusercontent.com/17348825/162183395-cc45b08f-7420-461a-aa0c-34c3f2956b85.png)

error  in ./src/App.vue
Syntax Error: TypeError: Cannot read properties of undefined (reading 'parseComponent')

### To reproduce

- packages
    - packageA
        - vue@3.0
    - packageB
        - vue@2.0

### Environment

```shell
System:
    OS: macOS 12.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 16.14.0 - /private/var/folders/db/8cl25g1n0ybf7v0f2qs6sn0r0000gp/T/xfs-73a2e735/node
    Yarn: 3.2.0 - /private/var/folders/db/8cl25g1n0ybf7v0f2qs6sn0r0000gp/T/xfs-73a2e735/yarn
    npm: 8.3.1 - /usr/local/bin/npm
```

**Comment by merceyz** [comment]
This bug report is extremely vague, if you want people to spend their time helping you at least do us the courtesy of filling out the report properly.
