### ISSUE TITLE
[Bug?]: YarnPkg search listing/Published package page

### ISSUE THREAD

**Issue by jayantur13** [yarnpkg/berry#4337]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Yesterday I published a package named "data-bharat",it was successfully published (as per the message on cli). The package's page is available for npm https://npmjs.org/package/data-bharat but for yarn https://yarnpkg.com/package/data-bharat it says doesn't exist.I am not using any dependencies.

### To reproduce

```
{
  "name": "data-bharat",
  "version": "1.0.0",
  "description": "A list of states,uts,districts and other information of India",
  "main": "example.js",
  "scripts": {
    "start": "node example.js"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/jayantur13/data-bharat.git"
  },
  "keywords": [
    "data India",
    "data india",
    "data-india",
    "data-bharat",
    "open data india",
    "india-Data",
    "states-india",
    "districts-india"
  ],
  "author": "Jayant Navrange",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/jayantur13/data-bharat/issues"
  },
  "homepage": "https://github.com/jayantur13/data-bharat#readme"
}
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
  Binaries:
    Node: 16.13.2 - ~\AppData\Local\Temp\xfs-0221b701\node.CMD
    Yarn: 3.2.0 - ~\AppData\Local\Temp\xfs-0221b701\yarn.CMD
    npm: 8.4.1 - C:\Program Files\nodejs\npm.CMD
```

### Additional context

I tried to publish with other package names too but still for yarn the package's package not exists and even search was not listing.
I was on yarn v1 at the time of publising, after searching and finding about yarn berry I migrated to it and again tried to publish (using yarn npm publish) with a newer version 1.0.0-1 with success message.But still same The package's page was available for npm https://npmjs.org/package/data-bharat but for yarn https://yarnpkg.com/package/data-bharat it still says it doesn't exist.

**Comment by arcanis** [comment]
The search is handled by Algolia. It takes a bit of time for updates to show up.

**Comment by jayantur13** [comment]
Its more than a day now,seriously there's some issue.For info I have published package named "kountry" a single word in past,it was made instantly available (on search and with dedicated page).Only difference with this package is a dash in between 2 words "data-bharat" (sounds stupid,yes). Any help will be appreciated.
