### ISSUE TITLE
[Bug?]: Electron crashes with PnP when Webpack is also installed

### ISSUE THREAD

**Issue by Methuselah96** [yarnpkg/berry#4344]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

When starting an Electron app with Yarn PnP it crashes with this error:

![image](https://user-images.githubusercontent.com/693755/162814235-4f6d40b2-405c-4679-93b2-0a1b16ddca0d.png)

This only happens when Webpack is also installed.

### To reproduce

1. Clone https://github.com/Methuselah96/electron-yarn-pnp.
2. Run `yarn start`.
3. Observe the crash.
4. Remove the `webpack` dependency.
5. Run `yarn start`.
6. Observe that it works.

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 16.14.0 - ~\AppData\Local\Temp\xfs-aa7cd175\node.CMD
    Yarn: 1.22.15 - ~\AppData\Local\Temp\xfs-aa7cd175\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
```

### Additional context

This used to work in Yarn 3.1.1, so something changed in 3.2.0 that caused it to break. See https://github.com/reduxjs/redux-devtools/pull/1124 for the the real-world breakage.

**Comment by Methuselah96** [comment]
@arcanis @merceyz I really need to get this fixed since this is a show-stopper bug for me preventing me from upgrading Yarn from 3.1.1 to 3.2.0 (and therefore also preventing me from upgrading TypeScript). I'm willing to dig into this myself, but any ideas off the top of your heads of where the issue might be or where to start looking?

**Comment by arcanis** [comment]
I'd suggest to add some console.log (or `alert`, maybe, considering it's electron?) inside the locations shown in the stacktrace. Specifically, adding some logs into `_load` from `.pnp.cjs` should tell you what parameters are passed to the function; it seems they generate an `undefined` value in a place that doesn't expect it.
