### ISSUE TITLE
[Bug?]: Building with `yarn build:cli` fails without doing a prior `yarn install`

### ISSUE THREAD

**Issue by hughdavenport** [yarnpkg/berry#4350]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I'm unable to build the current master branch with `yarn build:cli`. I get the following error:
```
16:22 $ yarn build:cli
Internal Error: resolve@patch:resolve@^1.17.0#~builtin<compat/resolve>: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at tF.getCandidates (/home/hugh/.yarn/releases/yarn-3.2.0.cjs:437:4480)
    at wd.getCandidates (/home/hugh/.yarn/releases/yarn-3.2.0.cjs:395:1281)
    at /home/hugh/.yarn/releases/yarn-3.2.0.cjs:441:7765
    at Pg (/home/hugh/.yarn/releases/yarn-3.2.0.cjs:394:11098)
    at le (/home/hugh/.yarn/releases/yarn-3.2.0.cjs:441:7745)
```

If I do a `yarn install` first then it succeeds. (note that `yarn install` is currently failing on master due to #4348).

I used `git bisect` to track this down to commit f68aed4376aa24b0e8293045eaf1df45a50905fa from Mar 19

### To reproduce

```
git clone https://github.com/yarnpkg/berry
cd berry
yarn build:cli
```

Observe an error

### Environment

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 PRO 5850U with Radeon Graphics
  Binaries:
    Node: 16.14.2 - /tmp/xfs-10075b00/node
    Yarn: 4.0.0-rc.2.dev - /tmp/xfs-10075b00/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
```

**Comment by merceyz** [comment]
It looks like you've run `yarn set version` in your home directory which is causing that version to be used instead of the one in this repo. Check `~/.yarnrc(.yml)` for `yarnPath` and remove it.
