### ISSUE TITLE
[Bug?]: Command not found; did you mean:

### ISSUE THREAD

**Issue by matart15** [yarnpkg/berry#4367]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Followed [Migration guide](https://yarnpkg.com/getting-started/migration).

```sh
❯❯❯ yarn workspaces focus --production
Unknown Syntax Error: Command not found; did you mean:

$ yarn workspaces list [--since] [-R,--recursive] [-v,--verbose] [--json]
While running workspaces focus --production
```

```sh
❯❯❯ yarn workspaces focus --all --production
Unknown Syntax Error: Command not found; did you mean:

$ yarn workspaces list [--since] [-R,--recursive] [-v,--verbose] [--json]
While running workspaces focus --all --production
```

### To reproduce

Followed [Migration guide](https://yarnpkg.com/getting-started/migration).

### Environment

```shell
System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.18.3 - /private/var/folders/sg/9dcbdx3x6tgghlm5mfty1vx40000gn/T/xfs-10337975/node
    Yarn: 3.2.0 - /private/var/folders/sg/9dcbdx3x6tgghlm5mfty1vx40000gn/T/xfs-10337975/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
```

**Comment by matart15** [comment]
also my autocomplete is broken.

I have `build-lambda` script in `package.json`
yarn v1 I was doing `yarn build-l` + tab it completes to `build-lambda`. v3 it is not working

**Comment by merceyz** [comment]
The migration guide states that you need the `workspace-tools` plugin, run the following command to get it
```sh
yarn plugin import workspace-tools
```
In Yarn v4 this will be included by default

> also my autocomplete is broken.

That seems out of scope for this issue.
