### ISSUE TITLE
[Bug?]: Yarn 3.2 breaks node_modules with docker volumes

### ISSUE THREAD

**Issue by basicdays** [yarnpkg/berry#4373]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Yarn 3.1 works as expected. Yarn 3.2 will fail on yarn install with the following error:

```
➤ YN0000: ┌ Link step
➤ YN0001: │ Error: EBUSY: resource busy or locked, rmdir '/workspace/node_modules'
➤ YN0000: └ Completed in 4s 519ms
```

This occurs in the following environment:

- Yarn 3.2
- Using yarn with `nodeLinker: node-modules`
- Running within a Docker container
- Using a Docker volume for the `node_modules` folder. This is used in my case with VSCode's devcontainer feature, but it can happen with just using Docker directly.

### To reproduce

If necessary, I can create a tiny git repo that has Docker and yarn setup to reproduce this. Otherwise just creating a Docker container with a volume at `node_modules` and running any kind of yarn install. The host machine will require Docker and Docker Compose for it to run.

### Environment

```shell
System:
  OS: Linux 5.10 Debian GNU/Linux 10 (buster) 10 (buster)
  CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Binaries:
  Node: 12.22.7 - /tmp/xfs-560392c2/node
  Yarn: 3.2.0 - /tmp/xfs-560392c2/yarn
  npm: 6.14.15 - /usr/local/bin/npm
```

### Additional context

Attempting to delete a folder within a Docker container that is managed by a Docker volume will never work. Something within yarn 3.2 switched to attempting to delete the folder completely. I've just used a simple bash script if I ever need to clear out the `node_modules` directory for whatever reason:

```shell
#!/usr/bin/env bash
shopt -s dotglob nullglob
rm -rf "node_modules/*"
```

**Comment by merceyz** [comment]
Possibly a duplicate of https://github.com/yarnpkg/berry/issues/4172, can you try with the latest canary?
```sh
yarn set version canary
```

**Comment by coopermaruyama** [comment]
Got it working. It works fine, my issue was that the `.yarn/install-state.gz` file was being created on the host machine and then synced into the container.

If the file is created by the container instance it works fine.

If you need to be able to run `yarn install` on both the host and container, make sure this file does not get synced with the following (if using docker-compose):

```yaml
volumes:
  - "/app/.yarn"
  - $PWD/.yarn/plugins:/app/.yarn/plugins
  - $PWD/.yarn/releases:/app/.yarn/releases
  - $PWD/.yarn/patches:/app/.yarn/patches
```

This excludes .yarn from being synced, and then includes the 3 directories which you probably do want to sync.

**Comment by basicdays** [comment]
> Possibly a duplicate of #4172, can you try with the latest canary release?
> 
> ```shell
> yarn set version canary
> ```

@merceyz Looks like canary dropped support for node 12. We're in process of updating node versions, but haven't completed that yet so I'm unable to test this quick. I'll see if I can find a way to do that later today though.

**Comment by basicdays** [comment]
Since this seems to be fixed in an upcoming version of yarn, I'm just going to close this.

**Comment by modbender** [comment]
Setting it to canary doesn't work everytime.
