### ISSUE TITLE
[Bug?]: TS 4.7 beta breaks with yarn pnp

### ISSUE THREAD

**Issue by magnattic** [yarnpkg/berry#4385]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I tried to update our react project to typescript `4.7.0-beta` because we need support for the new package.json `exports´ syntax.

However, this does not work with yarn pnp apparently. Suddenly no modules can be resolved anymore.

![image](https://user-images.githubusercontent.com/7560166/164702422-772fe62a-1735-43f6-94c0-d1054a3cc978.png)

I realize that TS 4.7 is still in beta so this might be resolved in the final version, but I wanted to make you aware that there might be something that needs to be fixed.

### To reproduce

Simply create a CRA project with yarn pnp and ts 4.7.0-beta:
```
yarn create react-app ts47 --template typescript
cd ts47
yarn set version stable
echo "nodeLinker: pnp" >> .yarnrc.yml
yarn install
yarn add typescript@4.7.0-beta
DISABLE_ESLINT_PLUGIN=true yarn build
```

Here is also a link to a repro project: https://github.com/magnattic/ts47

### Environment

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 16.14.0 - /tmp/xfs-ea6b7d34/node
    Yarn: 3.2.0 - /tmp/xfs-ea6b7d34/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
```

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/4339.
@arcanis can you backport the PR and release it?
