### ISSUE TITLE
[Bug] Current canary fails when running `yarn plugin import interactive-tools`

### ISSUE THREAD

**Issue by coopermaruyama** [yarnpkg/berry#4396]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

The current canary version of yarn `4.0.0-rc.2` 404's when installing certain packages with commands such as `yarn plugin import interactive-tools`. Output looks like:

```
% yarn plugin import interactive-tools
➤ YN0000: Downloading https://github.com/yarnpkg/berry/raw/@yarnpkg/cli/4.0.0-rc.2/packages/plugin-interactive-tools/bin/%40yarnpkg/plugin-interactive-tools.js
➤ YN0035: The remote server failed to provide the requested resource
➤ YN0035:   Response Code: 404 (Not Found)
➤ YN0035:   Request Method: GET
➤ YN0035:   Request URL: https://github.com/yarnpkg/berry/raw/@yarnpkg/cli/4.0.0-rc.2/packages/plugin-interactive-tools/bin/%40yarnpkg/plugin-interactive-tools.js
➤ YN0000: Failed with errors in 0s 623ms
```

### To reproduce

```
> yarn set version canary
> yarn plugin import interactive-tools
```

### Environment

```shell
System:
    OS: macOS 12.3
    CPU: (32) x64 Intel(R) Xeon(R) W-3245 CPU @ 3.20GHz
  Binaries:
    Node: 16.14.2 - /private/var/folders/3y/4_hmvd6x16qgl5zt_lzxlcdw0000gn/T/xfs-b9cf6a07/node
    Yarn: 4.0.0-rc.2 - /private/var/folders/3y/4_hmvd6x16qgl5zt_lzxlcdw0000gn/T/xfs-b9cf6a07/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
```

**Comment by F3n67u** [comment]
I can reproduce on my side. the `bin` dir is missing in `packages/plugin-interactive-tools` https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F4.0.0-rc.2. `bin` dir is also missing in other package dir.

**Comment by merceyz** [comment]
[Yarn v4](https://github.com/yarnpkg/berry/issues/3591) (current canary) [ships those plugins by default](https://github.com/yarnpkg/berry/pull/4253) so there is no need to import them.

> I can reproduce on my side. the bin dir is missing in packages/plugin-interactive-tools

https://github.com/yarnpkg/berry/pull/4331 was supposed to stop it from getting that far, I'll look into it.
