### ISSUE TITLE
[Feature] esbuild-plugin-pnp should respect absWorkingDir

### ISSUE THREAD

**Issue by TakaiSaisei** [yarnpkg/berry#4418]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

At this time esbuild plugin uses `process.cwd()` as base directory - can we use API option passed to esbuild and fallback to `process.cwd()` only if it is not specified?

e.g.: I expect that plugin with such esbuild config:

    require('esbuild').build({

    entryPoints: ['application.js'],

    absWorkingDir: path.join(process.cwd(), 'app/javascript')

will look for `app/javascript/application.js` - instead it looks for `application.js`.

**Describe alternatives you've considered**

It can be hacked via prepending asbWorkingDir to every entry point, like this

    const absWorkingDir = path.join(process.cwd(), 'app/javascript')
    
    require('esbuild').build({

    entryPoints: ['application.js'].map(name => `${absWorkingDir}/${name}`)

but it looks dirty.

**Comment by sushruth** [comment]
This may actually be a bug.

**Comment by gonber** [comment]
@TakaiSaisei when using your alternative I get the error `Entry points must be a relative path.` Doesn't that happen to you?

**Comment by merceyz** [comment]
Native support for PnP was added to [`esbuild@0.15.0`](https://github.com/evanw/esbuild/releases/tag/v0.15.0) so `@yarnpkg/esbuild-plugin-pnp` is no longer required and [is getting deprecated](https://github.com/yarnpkg/berry/pull/4732), if you experience any issues with the PnP support in esbuild please report them [upstream](https://github.com/evanw/esbuild).
