### ISSUE TITLE
[Bug?]: Yarn bundle still added to repository even with Corepack enabled

### ISSUE THREAD

**Issue by srmagura** [yarnpkg/berry#4420]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

Following the [installation guide](https://yarnpkg.com/getting-started/install) results in the Yarn JS bundle being added to your git repository, even though Corepack is supposed to make this unnecessary.

I'm not sure if this is a bug or if the documentation just needs to be tweaked.

### To reproduce

Run the following:

```zsh
mkdir yarn-init-repro
cd yarn-init-repro
corepack enable
yarn init -2
```

This produces the following:

![image](https://user-images.githubusercontent.com/801549/166150520-99a7561b-32cb-4977-b2fb-13136634ee0b.png)

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
  Binaries:
    Node: 16.15.0 - /tmp/xfs-8b61d4d8/node
    Yarn: 3.2.0 - /tmp/xfs-8b61d4d8/yarn
    npm: 8.8.0 - ~/.nvm/versions/node/v16.15.0/bin/npm
```

**Comment by merceyz** [comment]
This is working as intended, Yarn 4 will stop including the bundle if possible https://github.com/yarnpkg/berry/pull/4254.
