### ISSUE TITLE
[Bug?]: Dependencies of bin tools are unresolved

### ISSUE THREAD

**Issue by DavidTanner** [yarnpkg/berry#4432]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When running a tool, like eslint, and including a plugin that is resolved by an eslint plugin, the dependencies of the plugin are unresolved.  This also happens for other tools.  I am working on a webpack library that also gets the same issue where the library can't resolve its own dependencies.

yarn eslint . -> eslint -> @lifeomic/eslint-config-standards -> @typescript-eslint/eslint-plugin

### To reproduce

```js repro// Sherlock reproduction.
const { promises: fs } = require('fs')

const packageJson = {
  "name": "yarn-berry-issue",
  "packageManager": "yarn@3.2.0",
  "scripts": {
    "test": "yarn eslint ."
  },
  "dependencies": {
    "@lifeomic/eslint-config-standards": "2.1.1",
    "eslint": "8.14.0"
  }
}

const eslintRcJson = `
{
  "extends": [
    "@lifeomic/standards"
  ],
  "env": {
    "node": true,
    "jest": true,
    "es6": true
  }
}
`

await fs.writeFile('package.json', JSON.stringify(packageJson), 'utf-8');
await fs.writeFile('.eslintrc.json', eslintRcJson, 'utf-8');
await yarn('install')

await expect(yarn('test')).resolves.not.toThrow();
```

### Environment

```shell
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  Binaries:
    Node: 16.15.0 - /private/var/folders/35/kyf3z96s2yjg64bd4f713nv80000gn/T/xfs-1804e351/node
    Yarn: 3.2.0 - /private/var/folders/35/kyf3z96s2yjg64bd4f713nv80000gn/T/xfs-1804e351/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
```

**Comment by merceyz** [comment]
> When running a tool, like eslint, and including a plugin that is resolved by an eslint plugin, the dependencies of the plugin are unresolved

For ESLint see https://github.com/microsoft/rushstack/tree/097b7c0ee1a47de646399aba92becb913e757477/eslint/eslint-patch

> I am working on a webpack library that also gets the same issue where the library can't resolve its own dependencies.

You'll need to explicitly resolve loaders yourself otherwise Webpack will resolve them from the current working directory.
