### ISSUE TITLE
[Bug?]: plugin path in .yarnrc.yml combined with corepack packageManager causing unresolvable dependency during new builds

### ISSUE THREAD

**Issue by Eeemil** [yarnpkg/berry#4450]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

`yarn plugin import workspace-tools` adds the following line to `.yarnrc.yml`:

```yaml
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
```

When building a monorepo with a base image, I would like to have a Dockerfile with a config such as:
```
FROM node:16-alpine AS basebuild

WORKDIR /opt/build

RUN corepack enable
COPY package.json yarn.lock .npmrc .yarnrc.yml * ./
RUN yarn plugin import workspace-tools
...
```

And I would like to have

```
  "packageManager": "yarn@3.2.0"
```
in package.json to ensure it is built with with the correct yarn version.

However, the Docker build fails already at `yarn plugin import workspace-tools` as `yarn` tries to load the path defined in `.yarnrc.yml`:

```
Internal Error: Cannot find module '/opt/build/.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs'
Require stack:
- /root/.node/corepack/yarn/3.2.0/yarn.js
Require stack:
- /root/.node/corepack/yarn/3.2.0/yarn.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/usr/local/lib/node_modules/corepack/dist/vcc.js:170:20)
    at yJ (/root/.node/corepack/yarn/3.2.0/yarn.js:394:12617)
    at Rg (/root/.node/corepack/yarn/3.2.0/yarn.js:394:13471)
    at x (/root/.node/corepack/yarn/3.2.0/yarn.js:395:21561)
    at Function.find (/root/.node/corepack/yarn/3.2.0/yarn.js:395:22170)
    at async i (/root/.node/corepack/yarn/3.2.0/yarn.js:448:11309)
    at async r (/root/.node/corepack/yarn/3.2.0/yarn.js:448:10887)
```

The `plugins:` field in `.yarnrc.yml` [is not documented in the official documentation](https://yarnpkg.com/configuration/yarnrc), so I don't know if there's any modification I can provide. Removing the `path` creates a validation error.

Preferably, yarn would resolve the plugin dependency automatically by reading the pluginlist in yarnrc, having `spec: "@yarnpkg/plugin-workspace-tools"` should be sufficient for yarn to download plugins automatically. It would be an enhancement in a CI situation if yarn (or corepack) would automatically download all listed plugins in some manner.

### To reproduce

Described above

### Environment

```shell
System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
  Binaries:
    Node: 16.15.0 - /tmp/xfs-0b65dad0/node
    Yarn: 3.2.0 - /tmp/xfs-0b65dad0/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
```

**Comment by merceyz** [comment]
This is working as intended, you need to include the contents of `.yarn/plugins`. You shouldn't run `yarn plugin import workspace-tools` as part of your build.

**Comment by Eeemil** [comment]
Requiring external dependencies to be committed to your repository defeats the purpose of using a package manager.
Seeing that the `plugins:` field of `.yamlrc.yml` is not documented anywhere, it is hard to know what is the intended behavior. The documentation I can find that hints of your solution is the following under a [QA section](https://yarnpkg.com/getting-started/qa) regarding `.gitignore`-files: :
> .yarn/plugins and .yarn/releases contain the Yarn releases used in the current repository (as defined by [yarn set version](https://yarnpkg.com/cli/set/version)). You will want to keep them versioned (this prevents potential issues if, say, two engineers use different Yarn versions with different features).

This _requirement_ is not specified in the documentation regarding plugins.

However. Using the correct yarn version is a problem solved by corepackage by defining the version in package.json, it would seem reasonable that a similar mechanism for defining the package version in `.yamlrc.yml` should exist.

But I totally agree that I shouldn't run `yarn plugin import <specific-plugin-name>` during my build, it would be much better if yarn could resolve the list in `.yarnrc.yml` automatically.
