### ISSUE TITLE
[Bug?]: repo's package.json should be updated AFTER dependency postinstall script 

### ISSUE THREAD

**Issue by loynoir** [yarnpkg/berry#4459]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Actually, yarn berry update repo's package.json BEFORE dependency preinstall script.

Causing different behavior compared to both `npm` and `pnpm` when running script
- preinstall
- install
- postinstall

### Reproduce
Given
- `repo` has
```json
{
  "devDependencies": {
    "foo": "1.0.22"
  }
}
```
- `foo` has script `preinstall`, `install`, `postinstall`, to detect update from which version
```sh
# update from
jq \
    ".devDependencies[\"${name}\"]" \
    "${INIT_CWD}"/package.json
# update to
echo "${npm_package_version}"
```
- update `foo` from `1.0.22` to `1.0.23`
```sh
{{PM}} {{ADD}} -D foo@1.0.23
```

### Actual
yarn berry output
```txt
"1.0.23"
1.0.23
"1.0.23"
1.0.23
"1.0.23"
1.0.23
```

### Expected
npm output
```txt
"^1.0.22"
1.0.23
"^1.0.22"
1.0.23
"^1.0.22"
1.0.23
```

pnpm output
```txt
"1.0.22"
1.0.23
"1.0.22"
1.0.23
"1.0.22"
1.0.23
```

### Environment

```shell
Node: 16.14.2

Yarn: 3.2.0
```

**Comment by merceyz** [comment]
This is working as intended, `preinstall` and `install` are only run as part of `postinstall` for some level of backwards compatibility.

> postinstall is called after a package's dependency tree changes are written to the disk -- e.g. after a dependency or transitive dependency is added, removed, or changed. It is guaranteed to be called in topological order (in other words, your dependencies' postinstalls will always run before yours). For backwards compatibility, preinstall and install are called as part of postinstall.
https://yarnpkg.com/advanced/lifecycle-scripts/

**Comment by loynoir** [comment]
@merceyz OK, forget about `preinstall` and `install`.

`npm` `postinstall` output 
```txt
"^1.0.22"
1.0.23
```

`pnpm` `postinstall` output 
```txt
"^1.0.22"
1.0.23
```


`yarnBerry` `postinstall` output 
```txt
"1.0.23"
1.0.23
```

Both `npm` and `pnpm` update `package.json` version after `postinstall`.
But `yarnBerry` update `package.json` version before `postinstall`, 
which makes a update function useless.

```js
function update(fromVer, toVer) {
  // babel transform `fromVer` to `toVer`
}

```
