### ISSUE TITLE
[Feature] Support enterprise proxies for yarn berry .js files (content-type issue)

### ISSUE THREAD

**Issue by smurf667** [yarnpkg/berry#4460]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [X] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

_I do understand this is a bit of an exotic request, but I am giving it a try anway._

As an enterprise, we would like to mirror the yarn Git repository contents so that we can make use of yarn without the need of the build system to reach out to the internet. Access to the internet is not allowed and not possible for our builds.

The problem we're facing is with the content type reported on https://raw.githubusercontent.com/yarnpkg/berry/master/packages/berry-cli/bin/berry.js - our auto proxy (SonaType) requires that the content type is strictly enforced and matches.

The error message seen during proxying is

```
NXRM_NODE3 XXX org.sonatype.nexus.repository.view.handlers.ExceptionHandler - Invalid content: GET /master/packages/berry-cli/bin/berry.js: org.sonatype.nexus.repository.InvalidContentException:  Detected content type [application/x-sh], but expected [application/javascript, application/x-javascript, text/javascript]: master/packages/berry-cli/bin/berry.js
```

Accessing `berry.js` in a browser, I see a content type `text/plain`, which also does not match. I suspect the auto proxy inspects the resource and decides that it is a shell script (based on the first line of the file).

**Describe the solution you'd like**

https://raw.githubusercontent.com/yarnpkg/berry/master/packages/berry-cli/bin/berry.js (and potentially similar resources) are served with an expected JavaScript content type (see above).

**Describe the drawbacks of your solution**

I suspect most clients reading the resource do not care about the content type and happily download it in any case. Changing the content type might lead to a blocked request, should enhanced security and its policies be involved (pure speculation, not observed, not the case for us).

**Describe alternatives you've considered**

Inside our company, we can debate if there would be exceptions possible, however just today I received some negative feedback.

I understand my request may not be doable on your side, or you might reject it for other reasons (please state). No hard feelings! Thanks!

**Comment by RDIL** [comment]
Unfortunately since it’s served via the GitHub CDN, Yarn doesn’t control the content type of this file, so save from switching how the distribution system works entirely, I don’t think this is possible.

**Comment by smurf667** [comment]
I understand and suspected as much. We will have to look inside the company how to deal with this. It would by the way be quite good if a complete "offline", "internet-less" way would be supported. The assumption the build system is always on the internet is... not good.

**Comment by merceyz** [comment]
Yarn doesn't make that assumption, I'm assuming you're running `yarn set version berry` as part of your build process which you shouldn't do. You should instead commit the bundle to the repo.

**Comment by RDIL** [comment]
@smurf667 ideally you want to either commit the yarn binary, or use the new recommended way, corepack.  If you are running in a container, you can use `corepack prepare` to pre-download the version of Yarn you need globally, but this may not work, just a thought.

**Comment by smurf667** [comment]
Alright all - we'll look into this too. Thanks for your comments!
