### ISSUE TITLE
[Bug?]: The TypeScript language service died 5 times right after it got started. The service will not be restarted.

### ISSUE THREAD

**Issue by keatkeat87** [yarnpkg/berry#4463]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

![image](https://user-images.githubusercontent.com/8691013/168610674-10171e96-ffd0-4bf8-a91f-4706ae3a95ae.png)

### To reproduce

commands:
mkdir yarn-pnp-typescript-sdk-issue
cd yarn-pnp-typescript-skd-issue
yarn init -2
yarn add typescript --dev

create index.ts
`console.log(["a"].includes("a"));`
select the includes method and press F12
it will open the .d.ts file, until now everything work fine.
![image](https://user-images.githubusercontent.com/8691013/168612645-f5e555de-6c9b-4d4b-818b-cc8f06d81290.png)
install VS Code sdk
yarn dlx @yarnpkg/sdks vscode
select typescript version: use workspace
![image](https://user-images.githubusercontent.com/8691013/168613553-f344251d-360d-4530-a2fe-c726fcd4506b.png)
reload the windows
select the includes method and press F12
it will open the .d.ts file, but it comes out a error
![image](https://user-images.githubusercontent.com/8691013/168610674-10171e96-ffd0-4bf8-a91f-4706ae3a95ae.png)
now, everything typescript stops working, if you try F12 again, it won't open .d.ts anymore.
![image](https://user-images.githubusercontent.com/8691013/168614262-8f745b86-19f6-4530-8815-b133cf083ac6.png)

[git clone https://github.com/keatkeat87/yarn-pnp-typescript-sdk-issue.git](https://github.com/keatkeat87/yarn-pnp-typescript-sdk-issue.git)

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 16.15.0 - ~\AppData\Local\Temp\xfs-6041517f\node.CMD
    Yarn: 1.22.15 - ~\AppData\Local\Temp\xfs-6041517f\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
```

### Additional context

Yarn: 3.2.1
VS Code: 1.67.1
TypeScript: 4.6.4

I am so sorry, this is my first-time reporting Yarn issue and just migrations from 1.0 to 3.0. I don't know how to use Sherlock and the Playground to do the reproduction. If you think it may be a bug and should use Sherlock or Playground to reproduce it then gives me feedback, I will spend time learning it.

**Comment by merceyz** [comment]
Thanks for the report, I've triggered a release to update the tags on the registry to point to the correct version, in the meantime you can run the following command:
```sh
yarn dlx @yarnpkg/sdks@3.0.0-rc.5 vscode
```
