### ISSUE TITLE
[Question] Has the nested workspaces/worktree stuff been implemented yet?

### ISSUE THREAD

**Issue by telamonian** [yarnpkg/berry#447]
Has the nested workspaces/worktree stuff (mentioned [here](https://next.yarnpkg.com/features/workspaces#how-to-declare-a-worktree)) been implemented yet?

If it has been, I'd like to try it out. I made some hacks to enable one level of `yarn` workspace nesting in [this PR for the Jupyterlab build system](https://github.com/jupyterlab/jupyterlab/pull/7179), but it looks like my hack doesn't cover every use case (see the test failures). If there's a better form of workspace nesting in `v2`, I'd like to test it and see if it solves my particular problem.

If it hasn't been implemented yet, can someone please point me towards the relevant source files? I'll see if I can make a PR for it.

**Comment by arcanis** [comment]
Hey @telamonian - Yep, it's been implemented! The one potentially experimental part is that I'm still not sure whether relative workspace ranges (`workspace:packages/my-package`) should be relative to the project root (as is currently the case) or to the nearest worktree.
