### ISSUE TITLE
Found incompatible module

### ISSUE THREAD

**Issue by keschat** [yarnpkg/berry#4480]
Having the error below while tring to build a docker image.

Using - nodeLinker: node-modules in my .yarnrc.yml file. Not sure if that's the cause.

=> ERROR [4/5] RUN yarn install --frozen-lockfile                                                      0.9s
------
 > [4/5] RUN yarn install --frozen-lockfile:
#0 0.726 yarn install v1.22.19
#0 0.848 [1/5] Validating package.json...
#0 0.854 error weathercompanion@1.0.0: The engine "yarn" is incompatible with this module. Expected version "3.2.1". Got "1.22.19"
#0 0.871 error Found incompatible module.
#0 0.871 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: executor failed running [/bin/sh -c yarn install --frozen-lockfile]: exit code: 1

**Comment by arcanis** [comment]
There's a template. Please follow it. With no reproduction we can run on our side, we can't do anything.
