### ISSUE TITLE
[Bug?]: Yarn warns about missing license even if package is not publishable

### ISSUE THREAD

**Issue by fulldecent** [yarnpkg/berry#4486]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Your package.json file MAY or MAY NOT describe a publishable project.

If your project is not publishable (i.e. intended for only running locally) then there is no need or benefit to specifying a code license.

Yarn complains if you do not specify a license in this circumstance.

### To reproduce

```sh
echo '{}'  > package.json
yarn install
```

### Environment

```shell
yarn run v1.22.18
warning package.json: No license field
error Command "dlx" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
```


### Additional context

_No response_

**Comment by arcanis** [comment]
This is Yarn 1, which is several major versions old.

**Comment by fulldecent** [comment]
Looks like Brew package manager is recommending old versions.

Proposing Yarn 4 at --> https://github.com/Homebrew/homebrew-core/pull/102250/files

**Comment by milesj** [comment]
@fulldecent Personally, I suggest _not_ using homebrew for yarn. Just use Node.js itself via corepack, or `npm install -g yarn`.

**Comment by maririn312** [comment]
> Looks like Brew package manager is recommending old versions.
> 
> Proposing Yarn 4 at --> https://github.com/Homebrew/homebrew-core/pull/102250/files

i've installed yarn using npm but i got v 1.22.21 and i tried to update yarn but this dlx error again. what should i do ???

And I've install node using nvm and my working node version is 18.18.0
