### ISSUE TITLE
[Bug?]: yarn does not throttle cache reads during linking, leads to out of fd errors

### ISSUE THREAD

**Issue by MarcCelani-at** [yarnpkg/berry#4488]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When using compression level 0 on a large repo with many dependencies, libzip can easily exhaust the file descriptor limit and report an error.

Here is an example error with a non-minified yarn at 3.2.1:

```
Libzip Error: Failed to open the cache entry for util@npm:0.11.1: Can't open file: No file descriptors available
    at ZipFS.makeLibzipError (/path/to/.yarn/releases/yarn-sources.cjs:63172:27)
    at new ZipFS (/path/to/.yarn/releases/yarn-sources.cjs:63147:22)
    at zipFsBuilder (/path/to/.yarn/releases/yarn-sources.cjs:74893:73)
    at /path/to/.yarn/releases/yarn-sources.cjs:74895:24
    at prettifySyncErrors (/path/to/.yarn/releases/yarn-sources.cjs:68176:14)
    at LazyFS.factory (/path/to/.yarn/releases/yarn-sources.cjs:74894:39)
    at LazyFS.get baseFs [as baseFs] (/path/to/.yarn/releases/yarn-sources.cjs:64420:30)
    at LazyFS.readFilePromise (/path/to/.yarn/releases/yarn-sources.cjs:64283:21)
    at AliasFS.readFilePromise (/path/to/.yarn/releases/yarn-sources.cjs:64283:28)
    at _Manifest.loadFile (/path/to/.yarn/releases/yarn-sources.cjs:69421:36)
```

**Workaround:** It appears that increasing the compression level works around this issue, but yarn is probably still subject to a race condition between opening/closing files.

Ideally, yarn should be smart about how many packages it tries to read from the cache at once so as to avoid exhausting file descriptors.

### To reproduce

A large package.json file with compressionLevel set to 0.

### Environment

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.13.1 - /private/var/folders/l1/qrb13dbx3l3_wjlh4kgxnpm80000gn/T/xfs-5ca35573/node
    Yarn: 3.2.1-git.20220513.hash-d157755 - /private/var/folders/l1/qrb13dbx3l3_wjlh4kgxnpm80000gn/T/xfs-5ca35573/yarn
    npm: 8.1.2 - ~/h/node/env-16.13.1/bin/npm
  npmPackages:
    jest: 26.6.3 => 26.6.3
```

**Comment by arcanis** [comment]
Please don't cut logs - I never saw this error before and, since you removed the execution logs, I have no way to know what part of Yarn throws the error you reported, so it's difficult to figure out what happens 😅

**Comment by MarcCelani-at** [comment]
Sorry about that @arcanis . This happened during the link stage. We are using the pnpm linker. I'd prefer not to upload the entire log if that's okay, but please let me know what you need and I will find a way to get you what you need.

**Comment by MarcCelani-at** [comment]
@arcanis can we reopen this? I worked around this by tweaking compression settings, but that just made the race condition less likely. Now, 9 months later, this is breaking our production build system (I guess the hardware there is different enough from our development environment that we are only catching it there).

We need to do some kind of throttling to prevent yarn from opening up too many files at once.

**Comment by MarcCelani-at** [comment]
Ah sorry, I just noticed a PR referenced this after yarnbot closed it, let me look at that first :)
