### ISSUE TITLE
[Feature] let workspaces/root devDependencies be a real feature

### ISSUE THREAD

**Issue by llaenowyd** [yarnpkg/berry#4493]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

I want a few libraries to manage a monorepo, to have more interesting top-level scripts, for example, format the entire monorepo according to a single formatting policy with `prettier` during the pre-commit hook, defined also at the worspaces root. Others include `npm-run-all` and `rimraf`.

The warning when installing a dev dependency at the root level isn't too much of a problem, but I found recently that when I added package dependencies at the workspace level (child actual packages) that my root-level scripting was broken until I ran `yarn` again - the root level package installs seemed to get wiped out.

Perhaps that's a bug but I felt more that this is due to it being an unsupported usage, and that brings me to post. My monorepo is at https://github.com/llaenowyd/cushman, it's just a small React library package and an entirely separate Storybook app - having these 2 components as separate packages in the workspace has worked out really nicely.

**Describe the solution you'd like**

Fully support workspaces root dev dependencies.

**Describe the drawbacks of your solution**

I think the warning message may be useful to guide newcomers who are intending to install a dependency into a workspace (child package). But I think the warning is ok. This request is just to avoid breaking root-level dev dependency installs. As far as that goes I don't see any drawbacks, those who don't use root level devDependencies would not have any problem either way.

**Describe alternatives you've considered**

pnpm, it's ok

**Comment by RDIL** [comment]
Which warning exactly?  Also, which Yarn version?

**Comment by llaenowyd** [comment]
Right, good questions -

```sh
src/cushman@main $ yarn --version
1.22.18

# the warning I mentioned
src/cushman@main $ yarn add -D pre-commit
yarn add v1.22.18
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

# this root package dependency exists
src/cushman@main $ ls node_modules/pretty-quick
LICENSE  README.md  bin/  dist/  img/  node_modules/  package.json

# add some package to child workspace
src/cushman@main $ yarn workspace @a110/rito add -D jest
yarn workspace v1.22.18
yarn add v1.22.18
[1/4] Resolving packages...
  # ... cut peer dep warnings etc
Done in 11.98s.
Done in 12.26s.

# now if I were to commit from the IDE, the pre-commit hook's going to fail
src/cushman@main $ ls node_modules/pretty-quick
ls: cannot access 'node_modules/pretty-quick': No such file or directory

# fix it again
src/cushman@main $ yarn
```

**Comment by llaenowyd** [comment]
Oh, I think version 1 is not this repository. I didn't realize I was on version 1 when I opened the issue here.

**Comment by RDIL** [comment]
Yeah, version 1 no longer receives patches except for security and maybe new Node version compatibility, not even sure about the latter.
