### ISSUE TITLE
[Bug?]: Vscodium does not recognize dependencies after creating a Plug'n'Play project. (And in NVIM)

### ISSUE THREAD

**Issue by Tagvi** [yarnpkg/berry#4500]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Basically, even after selecting the custom TS version in the commands' selector, the installed dependencies are not being registered. 
For example:
`Cannot find module 'styled-components' or its corresponding type declarations.ts(2307)`

### To reproduce

I don't think Sherlock will work here.
```bash
yarn init
yarn add typescript styled-components
yarn dlx @yarnpkg/sdks vscode 
```
package.json
```json
{
  "name": "yarn-not-working",
  "packageManager": "yarn@3.2.0",
  "dependencies": {
    "styled-components": "^5.3.5",
    "typescript": "^4.7.2"
  }
}
```
\> CTRL+SHIFT+P
\> TypeScript: Select TypeScript Version...
\> Use workspace version

index.ts
```ts
import {} from 'styled-components';
```
Error:
`Cannot find module 'styled-components' or its corresponding type declarations.ts(2307)`

### Environment

```shell
Output generated by `yarn dlx -q envinfo --preset jest`:
 System:
    OS: Linux 5.17 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
  Binaries:
    Node: 18.1.0 - /tmp/xfs-0f8e5cee/node
    Yarn: 3.2.0 - /tmp/xfs-0f8e5cee/yarn
    npm: 8.5.5 - /usr/bin/npm

Actual paths:
/usr/bin/node
/usr/bin/yarn
VSCodium version:
1.67.2-1 (The latest on AUR)
```

### Additional context

I also have NeoVIM installed on my machine. And I use coc-tsserver.
Upon running:
```bash
yarn dlx @yarnpkg/sdks vim
```
I still get the same error in my NVIM.

Actually happened multiple times in the past. I just rolled back to the old node_modules. But I really want to use yarn now, and this issue is the only reason why I am not using Plug'n'Play consistently.

**Comment by merceyz** [comment]
> Yarn: 3.2.0 - /tmp/xfs-0f8e5cee/yarn

Update to Yarn 3.2.1

**Comment by Tagvi** [comment]
Oh, I thought AUR kept it up to date, but I guess I was wrong. Anyway, problem fixed.
