### ISSUE TITLE
[Feature] Add --ignore-optional or similar option to allow using --immutable-cache with platform specific optional dependencies

### ISSUE THREAD

**Issue by bfricka** [yarnpkg/berry#4515]
- ✔️ I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

Not sure if a contrib plugin would allow this functionality.

**Describe the user story**

Various native packages resolve platform-specific modules using `optionalDependencies`. Examples include [ESBuild](https://github.com/evanw/esbuild/blob/v0.14.42/npm/esbuild/package.json) and [SWC](https://github.com/swc-project/swc/blob/v1.2.196/package.json).

Installing packages like this precludes the use of `--immutable-cache` flag if installation is done across platforms, since platform-specific packages will be added and removed based on condition checks.

**Describe the solution you'd like**

It would therefore be useful to have a way of ignoring changes caused by conditional checks so that `--immutable-cache` can still be used for all other modules.

**Describe the drawbacks of your solution**

The main drawback is that this reduces the efficacy of `--immutable-cache`, since packages can be added and remove based on runtime conditions. Additionally, it would be odd to have a flag that modifies another flag. Perhaps `--immutable-cache-ignore-conditionals` would be better.

**Describe alternatives you've considered**

The main alternative would be to an option (probably a `.yarnrc.yml` option) that changes the behavior of what Yarn downloads and adds to the cache by default. Something like `cacheAllOptional`. Using this, yarn would download and cache all optional packages, but install only those that pass the conditional checks. This way the cache is pegged regardless of the platform.

A similar idea would be to add something like the current `supportedArchitectures` field (maybe `cachedArchitectures`, that allows specifying which architectures to add to the cache.

**Comment by bfricka** [comment]
I just realized `supportedArchitectures` works. Sorry

**Comment by borislemke** [comment]
@bfricka could you share your working setup? I'm facing similar issue where when running `yarn install --immutable-cache` inside an alpine based image it throws:

```
#15 0.502 ➤ YN0056: │ @swc/core-linux-arm64-gnu@npm:1.3.1: Cache entry required but missing for @swc/core-linux-arm64-gnu@npm:1.3.1
#15 0.593 ➤ YN0013: │ turbo-linux-arm64@npm:1.4.6 can't be found in the cache and will be fetched from the remote registry
#15 0.593 ➤ YN0056: │ turbo-linux-arm64@npm:1.4.6: Cache entry required but missing for turbo-linux-arm64@npm:1.4.6
#15 0.634 ➤ YN0000: └ Completed
#15 0.634 ➤ YN0000: Failed with errors in 0s 205ms
#15 ERROR: executor failed running [/bin/sh -c yarn install --immutable-cache]: exit code: 1
------
 > [builder 4/8] RUN yarn install --immutable-cache:
------
executor failed running [/bin/sh -c yarn install --immutable-cache]: exit code: 1

```

**Comment by ankon** [comment]
I ended up here due to problems in our setup where some developers (and dependabot, and the deployment target) are on linux, and other developers are on macOS: We continuously "fought" about whether the fsevents dependency should or should not be in the cache.

Changing yarnrc to set the `supportedArchitectures` to both linux and darwin seems to fix the issue:
```yaml
enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.2.cjs

supportedArchitectures:
  os:
    - linux
    - darwin
```
