### ISSUE TITLE
yarn is not self healing, it CANNOT EVEN INSTALL ANYMORE

### ISSUE THREAD

**Issue by nhhockeyplayer** [yarnpkg/berry#4518]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

this release isnt even installable

```
meanstack02@admin starter % npm install yarn@1.22.18 -g

changed 1 package, and audited 2 packages in 1s

found 0 vulnerabilities
meanstack02@admin starter % which yarn
/usr/local/bin/yarn
meanstack02@admin starter % yarn -v
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/meanstack02/new/starter/.yarn/releases/yarn-3.2.1.cjs'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I removed all yarn cache files to no avail

its starting to act like npm now

and we have to chase after repo's and try to back engineer

but the sad option is going back to npm no one has room to chase after open source holes

### To reproduce

nice work guys

seems you planned for everything surrounding this to work to even report a bug

### Environment

```shell
node -v
v16.13.0
```

### Additional context

no context to add

I used yarn for years

and now its a show stopper

you could have at least kept the package name the same on the repo

**Comment by arcanis** [comment]
Do you really think it's a bad thing for us to lose users that "use yarn for years" but can't afford to be polite on the bug tracker of the project they use?

Regarding your "issue", you have a `yarnPath` setting in a `.yarnrc.yml` file pointing to a module that you subsequently removed. So when Yarn tries to load it, it cannot find it, and it crashes.
