### ISSUE TITLE
[Bug?]: Typescript compiler cannot resolve dependencies if invoked inside a workspace

### ISSUE THREAD

**Issue by shakeZSL** [yarnpkg/berry#4540]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

If using PnP as `nodeLinker`, the (patched) typescript compiler `tsc` is unable to resolve modules or type defintions if invoked inside a workspace. Therefore we are currently using the nodeLinker with the option „node-modules" instead, however we would really like to upgrade towards the new pnp feature instead.

### To reproduce

```js repro
const {promises: {mkdir, writeFile}} = require(`fs`);

await mkdir(`app`);

await packageJsonAndInstall({
    name: "parent",
    packageManager: "yarn@3.2.1",
    workspaces: [
        "./app"
    ],
    dependencies: {
        "axios": "^0.27.2",
        "typescript": "4.7.3"
    }
 });

await packageJsonAndInstall({
    name: "child",
    packageManager: "yarn@3.2.1",
    peerDependencies: {
        "axios": "",
        "typescript": ""
    },
    devDependencies: {
        "typescript": "4.7.3"
    }
 }, { cwd: "./app"});

await writeFile("index.ts", "import axios from 'axios';")

await writeFile(`app/index.ts`, "import axios from 'axios';")

await expect(yarn('workspace', 'parent', 'run', 'tsc', 'index.ts')).resolves.not.toThrowError("error TS2307: Cannot find module 'axios' or its corresponding type declarations.")
await expect(yarn('workspace', 'child', 'run', 'tsc', 'index.ts')).rejects.not.toThrowError("error TS2307: Cannot find module 'axios' or its corresponding type declarations.")
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 16.15.1 - ~\AppData\Local\Temp\xfs-a5ca79a7\node.CMD
    Yarn: 3.2.1 - ~\AppData\Local\Temp\xfs-a5ca79a7\yarn.CMD
    npm: 8.11.0 - D:\Programme\npm.CMD
Local windows machine. But i used Sherlock Playground to provide a reproducible example
```

**Comment by jangiann09** [comment]
Ok

**Comment by acusti** [comment]
i ran into this same issue when trying to upgrade to the latest version of typescript (`4.7.4`). i tested various versions to determine when the problem was introduced, and the first stable version of typescript that cannot resolve dependencies in my yarn workspaces is `4.7.2`, the first stable 4.7.x version. all `4.6.x` versions i tested work fine, all the way through the latest stable 4.6, `4.6.4`.

**Comment by BYK** [comment]
Just checking in, I'm also experiencing this issue and wondering if there's a potential fix or a path to fix?

**Comment by merceyz** [comment]
This is working as expected, the `child` workspace doesn't declare `axios` as a (dev)dependency.
Peer dependencies need to be provided by the parent and in the case of workspaces there isn't one.

**Comment by BYK** [comment]
Sorry, I thought this was related to #4903 which it was not.
