### ISSUE TITLE
[Bug?]: Inter-workspace dependencies not resolved when installing workspace using git protocol

### ISSUE THREAD

**Issue by Hybrid-Force** [yarnpkg/berry#4545]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

I set up 2 repos to demostrate this issue: monorepo [Hybrid-Force/yarn-git-workspace-alpha](https://github.com/Hybrid-Force/yarn-git-workspace-alpha) with 2 workspaces: `@demo/one` and `@demo/two`, where `@demo/two` depends on `@demo/one`.
```
// packages.json of @demo/two of yarn-git-workspace-alpha
"dependencies": {
    "@demo/one": "workspace:*"
}
```
Another repo [Hybrid-Force/yarn-git-workspace-beta](https://github.com/Hybrid-Force/yarn-git-workspace-beta) depends on `@demo/two` from `yarn-git-workspace-alpha` using git protocol:

```
// packages.json of yarn-git-workspace-beta
"dependencies": {
    "@demo/two": "Hybrid-Force/yarn-git-workspace-alpha#workspace=@demo/two"
}
```
When running `yarn install` in `yarn-git-workspace-beta`, `@demo/one`, which is a workspace dependency of `@demo/two`, is resolved using npm protocol, not using workspace.
```
➤ YN0000: ┌ Resolution step
➤ YN0035: │ @demo/one@npm:1.0.0: The remote server failed to provide the requested resource
➤ YN0035: │   Response Code: 404 (Not Found)
➤ YN0035: │   Request Method: GET
➤ YN0035: │   Request URL: https://registry.yarnpkg.com/@demo%2fone
➤ YN0000: └ Completed in 2s 45ms
➤ YN0000: Failed with errors in 2s 48ms
```

Note:

1. I can successfully install workspace `@demo/one` which has no inter-workspace dependencies.

2. I can work around this issue by having:
```
"resolutions": {
    "@demo/one": "Hybrid-Force/yarn-git-workspace-alpha#workspace=@demo/one"
}
```

### To reproduce

```js repo
await packageJsonAndInstall({
  "dependencies": {
    "@demo/two": "Hybrid-Force/yarn-git-workspace-alpha#workspace=@demo/two"
  }
});
```

### Environment

```shell
System:
  OS: macOS 12.4
  CPU: (10) arm64 Apple M1 Pro
Binaries:
  Node: 16.15.0 - /private/var/folders/c1/0m9z85090n56fr920h871g8w0000gn/T/xfs-79d04ac6/node
  Yarn: 3.2.1 - /private/var/folders/c1/0m9z85090n56fr920h871g8w0000gn/T/xfs-79d04ac6/yarn
  npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
```

**Comment by Neo-Ciber94** [comment]
I have the same problem, in your repo I got this error:

```bash
error Couldn't find package "@demo/one@workspace:*" required by "@demo/two@1.0.0" on the "npm" registry.
```

I need to include the exact version to make it work, I am using `yarn v1.22.22`
