### ISSUE TITLE
Please bring yarn outdated back for v2

### ISSUE THREAD

**Issue by pbadenski** [yarnpkg/berry#4555]
`yarn upgrade-interactive` is suggested as a replacement for `yarn outdated`. `upgrade-interactive` doesn't have a pure textual output which doesn't match Unix Philosophy. Most of my uses cases were leveraging grepping of the output or lessing it and just quickly browsing visually. I believe that for advanced users and larger projects there is a real gap in functionality. Certainly this is enough for me to hold off upgrading to v2.

Also discussed here: https://github.com/yarnpkg/berry/issues/749

**Comment by merceyz** [comment]
Duplicate of https://github.com/yarnpkg/berry/issues/1335

**Comment by merceyz** [comment]
Please don't just delete the issue template, it's there for a reason.
