### ISSUE TITLE
[Bug?]: Workspaces dependecy are linked to wrong version

### ISSUE THREAD

**Issue by hitech95** [yarnpkg/berry#4564]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Since I've updated from yarn 1 (to use cached dependencies) I cannot run my project (rolling back to yarn 1 works fine), the dependency tree is somehow broken.

For ease I've provided examples for `react-router` but this happends with other packages too.
A sub-project uses the wrong dependency version required by another sub-project.

### To reproduce

I'm working on creating a repo with a semplified project (without proprietary code) just to share a project to reproduce the issue.
I've only tested on Windows machine but colleagues told me the same issue is present also on MacOS...

The `nodeLinker` option in `.yarnrc.yml` is set to `node-modules`
A simplified package.json are:

**/package.json**
```JSON
{
  "name": "orgname",
  "workspaces": {
    "packages": [
      "packages/*"
    ]
  },
  "resolutions": {
    "@types/react": "17.0.45",
    "@types/react-dom": "17.0.17"
  },
  "packageManager": "yarn@3.2.1",
  "devDependencies": {
    "cross-env": "^7.0.3",
    "lerna": "^4.0.0"
  }
}

```

**/backoffice/package.json**
```JSON
{
  "name": "@orgname/backoffice",
  "version": "1.0.0",
  "dependencies": {
    "@material-ui/core": "^4.9.10",
    "@material-ui/icons": "^4.9.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-router": "^5.1.2",
    "react-router-dom": "^5.1.2",
    "react-scripts": "^4.0.1",
    "typescript": "4.1.3"
  },
  "devDependencies": {
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-router": "^5.1.0",
    "@types/react-router-dom": "^5.1.0",
    ....
  },
  ...
}
```

**/frontoffice/package.json**
```JSON
{
  "name": "@orgname/frontoffice",
  "version": "1.0.0",
  "dependencies": {
    "@material-ui/core": "^4.9.10",
    "@material-ui/icons": "^4.9.1",
    "react": "^17.0.1",
    "react-compound-timer": "^1.1.15",
    "react-dom": "^17.0.1",
    "react-router": "^6.3.0",
    "react-router-dom": "^6.3.0",
    "react-router-hash-link": "^2.0.0",
    "react-scripts": "^4.0.1"
  },
  "devDependencies": {
    ...
  },
  ...
}
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz     
  Binaries:
    Node: 14.19.0 - ~\AppData\Local\Temp\xfs-2ba1e8e9\node.CMD
    Yarn: 3.2.1 - ~\AppData\Local\Temp\xfs-2ba1e8e9\yarn.CMD  
    npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
```

### Additional context

I have a monorepo with this structure:

```
/
|- .yarn
|- node_modules
|- common/
|- backoffice/
|- frontoffice/
|- .yarnrc.yml
|- package.json
|- lerna.json
```

`frontoffice` and `backoffice` are react apps. While `common` have the shared interfaces and shared logic. 
`backoffice` depends on `react-router@5` and is written in **typescript** while the `frontoffice` depends on `react-router@6` and is JS.

When I try to start the backoffice or the frontoffice I have the errorros due to the backoffice importing `react-router@6` and web importing `react-router@5`. Sometimes by relaunching `yarn install` you can get one of the two to work.

I've run the `lerna why` command and to me everything seems fine:

```bash
$ yarn why react
├─ @orgname/a@workspace:packages/a
│  └─ react@npm:17.0.2 (via npm:^17.0.1)
│
└─ @orgname/web@workspace:packages/web
   └─ react@npm:17.0.2 (via npm:^17.0.1)
$ yarn why react-router
├─ @orgname/a@workspace:packages/a
│  └─ react-router@npm:5.3.3 [97e56] (via npm:^5.1.2 [97e56])
│
├─ @orgname/web@workspace:packages/web
│  └─ react-router@npm:6.3.0 [ce564] (via npm:^6.3.0 [ce564])
│
├─ react-router-dom@npm:5.3.3
│  └─ react-router@npm:5.3.3 (via npm:5.3.3)
│
├─ react-router-dom@npm:6.3.0
│  └─ react-router@npm:6.3.0 (via npm:6.3.0)
│
├─ react-router-dom@npm:5.3.3 [97e56]
│  └─ react-router@npm:5.3.3 [97e56] (via npm:^5.1.2 [97e56])
│
└─ react-router-dom@npm:6.3.0 [ce564]
   └─ react-router@npm:6.3.0 [ce564] (via npm:^6.3.0 [ce564])
$ yarn why react-router-dom
├─ @orgname/a@workspace:packages/a
│  └─ react-router-dom@npm:5.3.3 [97e56] (via npm:^5.1.2 [97e56])
│
└─ @orgname/web@workspace:packages/web
   └─ react-router-dom@npm:6.3.0 [ce564] (via npm:^6.3.0 [ce564])
```

Did I forget something to configure? Is there a way to force the right version for each package?

Inside `/mypath/packages/node_modules/` there is react-router@6.3.0 installed
Inside `/mypath/packages/backoffice/node_modules/` there is react-router@5.X.X installed

When the backoffice work the situation is reversed with react-router v5 installed in the root `node_modules` and the v6 is installed inside `/mypath/packages/frontoffice/node_modules/` but `frontoffice` dont work in such case.

**Comment by larixer** [comment]
@hitech95 You have opened a bug on the Yarn repository, but I don't see your explanation of what Yarn is doing wrong here. That's why I'm going to close the bug until the explanation will be provided.

**Comment by hitech95** [comment]
> @hitech95 You have opened a bug on the Yarn repository, but I don't see your explanation of what Yarn is doing wrong here. That's why I'm going to close the bug until the explanation will be provided.

Dependency linking is linking the wrong dependency version that has been required by another package in the same workspace.

Take the example above, `frontend` depends on `packageX@1.0.0` `backend` depends on `packageX@2.0.0`.

When running backend it import `packageX@2.0.0` instead of  `packageX@1.0.0`.
The example above uses `react-router` instead of a generic `packageX`.

The issue gets triggered by `peerDependency` in the example above by `react-router-hash-link`

**Comment by larixer** [comment]
>  Dependency linking is linking the wrong dependency version that has been required by another package in the same workspace.

Which dependency was linked incorrectly? You still have not provided this critical information.

**Comment by hitech95** [comment]
> Which dependency was linked incorrectly? You still have not provided this critical information.

In the case above `react-router` and `react-router-dom`
`backoffice` requires `react-router v5` and `frontend` requires `react-router v6`

**Comment by larixer** [comment]
> In the case/example above react-router and react-router-dom
backoffice requires react-router v5 and frontend requires react-router v6

I see correct linking for these dependencies in your repo. 
`backoffice` requested `react-router@5`, it was provided in top-level `node_modules`.

`frontend` requested `react-router@6`, it was provided in `packages/frontoffice/node_modules`.

**Comment by arcanis** [comment]
> In the case/example above `react-router` and `react-router-dom`
> `backoffice` requires `react-router v5` and `frontend` requires `react-router v6` but 'backoffice' imports `v6` failing at runtime.

This is probably because you didn't list `react-router` as being a peer dependency of `backoffice`. As a result, Yarn gives it the version it declares, not the version its ancestors use (especially since the version its ancestors use doesn't match the requested dependency range).

**Comment by hitech95** [comment]
> As a result, Yarn gives it the version it declares, not the version its ancestors use

`backoffice` is not a dependency of `frontoffice` those are 2 independent packages in the same workspace.

> What happens at runtime has nothing to do with Yarn. Yarn linked dependencies correctly.

Why the issue is triggered by adding another dependency to one of the packages? Is the typescript interpreter that is importing the wrong version?

**Comment by larixer** [comment]
> can you explain what that nmHoistingLimits does?
It disable hoisting of dependencies outside of workspaces. So all the `backoffice` dependencies will stay in `packages/backoffice/node_modules` and all the `frontoffice` dependencies will stay in `packages/frontoffice/node_modules`.  For the dependencies of `backoffice` and `frontoffice` dependencies this will create an environment that looks as if they are separate projects, thus preventing most lookup bugs. The downside is that the dependencies used by both `backoffice` and `frontoffice` stop being shared in top-level `node_modules` which will lead to a bit slower installs and a bigger disk footprint by `node_modules`. This workaround is somewhat radical.

Another not-so-radical workaround is to try to guess why the lookup bug happens and play around to stop the symptoms of a  bug from occuring.  I don't know what dependency is a source of a bug, maybe TypeScript? maybe another dependency. But I guess the bug happens due to different versions of `react-router-dom` and `react-router` appearing next to each other. To change that we can force `react-router` to be a `react-router-dom` peer dependency via the following lines in `.yarnrc.yml`:
```
packageExtensions:
  react-router-dom@5:
    peerDependencies:
      react-router: 5
  react-router-dom@6:
    peerDependencies:
      react-router: 6
 ```
Again, this is just a guess, but it works for me on your repo.

**Comment by hitech95** [comment]
> Again, this is just a guess, but it works for me on your repo.

This seems to be working perfectly on the demo repo. I'm gonna test on the private one.
So basicalli in this way we are forcing to use the right version of the `react-router` based on the version of `react-router-dom`.
