### ISSUE TITLE
yarn install ignores npmRegistryServer in favor of lock file resolution

### ISSUE THREAD

**Issue by IHateFun** [yarnpkg/berry#4565]
The yarn.lock file adds a field `resolution` to the individual packages, specifying the registry that was used to install the package. If you attempt to run `yarn install` when your `.yarnrc.yml` file has a different registry specified, yarn ignores this and uses the registry specified in the yarn.lock file.

I found this issue from yarn v1 (https://github.com/yarnpkg/yarn/issues/5892), which said the issue was resolved in v2, but this doesn't appear to be the case.

For context, I use a separate registry between CI and production, for security reasons, and running install in my production environment causes 

`RequestError: getaddrinfo ENOTFOUND <registry from the lock file>`

Maybe I have some bad configuration, but it doesn't seem like the issue mentioned above was resolved

**Comment by arcanis** [comment]
We ask for reproductions for a reason. Without more information it's hard to say, but it's likely your custom registry uses non-standard URL patterns that require us to hardcode them in the lockfile. You should open an issue to your provider if that's a problem.
