### ISSUE TITLE
[Feature] Legacy Kernel Mode

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/berry#458]
**Describe the user story**

I'm a JS infra developer. I want to migrate our project to Yarn v2 and PnP, but I'm concerned about unforeseen problems. I'd like to only enable this behaviour for a subset of my users, so that I limit the problem surface until I feel confident enough that everything has been addressed.

**Describe the solution you'd like**

This issue is about people that want to use both the v1 and the v2 at the same time: v1 for most people, and v2 for a few selected users. This isn't currently possible, because the v1 and v2 have conflicting lockfile formats and will overwrite each other.

The minimal solution I can see work would be as such: Yarn v1 would have a "legacy kernel mode". In this mode, various behaviour would change:

- Yarn v1 would have a basic support for v2 lockfiles.
- Yarn v1 would never overwrite the lockfile
- Yarn v1 would ignore the `.pnp.js` file when calling `yarn run`
- Each `yarn install` would call the v2 install first (to generate the lockfile)

The way it would be used would be as such:

- Infra owners would check-in Yarn 1.18+ in their repositories.
- Infra owners would define `.yarnrc` which would include `legacy-kernel-mode true`
- Infra owners would define `.yarnrc.yml` that would point to `yarn-gatekeeper.js`
- `yarn-gatekeeper.js` would branch on either the v1 or v2, depending on the user settings

This way, users under the v1 would have a regular `node_modules`, just the same as Yarn v1 would have installed. Users under the v2 would however use the `.pnp.js` file. The v1 users wouldn't be able to use the v2 features (since they're reputed to work with the v2 only), so there would still be an incentive to complete the transition eventually.

Kinda fixes #4, although #4 is about a real `node_modules` implementation in Berry. This would mostly be a hack.

**Describe the drawbacks of your solution**

We could implement a real node_modules linker, but that would have a significant opportunity cost and could still have problems since the hoisting mechanism might be different from what the v1 would have generated (although it shouldn't matter, hopefully).

**Describe alternatives you've considered**

When we discussed it on Discord I initially thought that the v2 should call the v1 install. I now think it would be better avoided because:

- I want to avoid adding complexity in the v2 for legacy reasons.
- There are less risks that the v2 appears broken because it wouldn't work with the v1 installs.

**Additional context**

**Comment by huy-nguyen** [comment]
Is the Yarn team abandoning this ticket and, if so, what's the reason? Thanks.

**Comment by arcanis** [comment]
@huy-nguyen We now have a `node-modules` linker, so I think the legacy kernel as described in this issue isn't relevant anymore. The way I see it, smooth migration can be achieved by enabling the `node-modules` linker for everyone, and letting individual users enable PnP as they see fit by adding `YARN_NODE_LINKER=pnp` in their env. Does that make sense?
