### ISSUE TITLE
[Feature] a protocol that is an opposite of `workspace:`

### ISSUE THREAD

**Issue by swandir** [yarnpkg/berry#4584]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

Suppose I have a monorepo with multiple libraries and apps.
All of the local dependencies are using `workspace:` protocol.
Libraries are using deferred version bumps.

At some point on of the apps is going into "maintenance mode" — that is, I don't want to have to update it each time I make any sort of breaking change in its dependencies.

What I want to do at that point is: make sure that the app always uses the published versions and move on.

Currently I'm not able to do that without publishing an intermediary version of all the app's dependencies before transferring it into the maintenance mode.

**Describe the solution you'd like**

Add a new dependency protocol which makes Yarn to always use the published version (opposite of `workspace:`).
Or make the existing `npm:` protocol behave like this.

**Describe the drawbacks of your solution**

Same issues as with maintaining other protocols.
Changing `npm:` behavior would be a breaking change.

**Describe alternatives you've considered**

This could be a plugin if adding a new protocol option is chosen.
Changing the behavior of an existing protocol via a plugin seems dangerous.
As a counterpart to `workspace:`, the feature seems core enough to be included by default, though.

**Comment by arcanis** [comment]
What you describe looks like [`enableTransparentWorkspaces: false`](https://yarnpkg.com/configuration/yarnrc#enableTransparentWorkspaces)

**Comment by swandir** [comment]
Thanks! That actually serves the described use case, given that

> All of the local dependencies are using workspace: protocol.

Might be worth mentioning the option in https://yarnpkg.com/features/workspaces? 🤔

There's a potential use case when the user wants transparent workspaces by default and the ability to opt in at a case-by-case basis. But that's considerably an edge case, and migrating to `workspace:` protocol does not seem to hurt.
