### ISSUE TITLE
[Compatibility] Fails to publish when used with NX

### ISSUE THREAD

**Issue by NathanJAdams** [yarnpkg/berry#4596]
Version 2 seems to have become incompatible with NX, specifically when publishing a package.

I believe this is due to 2 things:

- NX requires a package.json in the root directory
- Yarn fails if it sees a package.json higher up the directory structure and gives an error about "The nearest package directory doesn't seem to be part of the project". [This issue #2212](https://github.com/yarnpkg/berry/issues/2212) looks like it's related

Version 1 worked without issue, I have no idea of what's involved but would whatever's changed be able to handle package.json files higher up in the directory structure?

**Comment by merceyz** [comment]
Follow the issue templates

**Comment by NathanJAdams** [comment]
Why was this closed?
