### ISSUE TITLE
[Bug?]: supported architectures behaviour doesn't support zero installs

### ISSUE THREAD

**Issue by laytong** [yarnpkg/berry#4615]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I have a repo using zero installs approach that requires one unplugged package (@swc-core)

its unplugged as it appears to require platform specific binaries. My CI environment is a linux env, whereas local is mac

I added the specific platforms to the `supportedArchitectures` field in my .yarnrc.yml

I had hoped/expected that with zero-installs the platform specific binaries would have been installed/added to the repo on local install so that when i run my ci i do not need to do a yarn install step (in keeping with the zero installs approach)

This may be the intended behaviour, but then how do I maintain zero installs in this case?

### To reproduce

I don't believe this can be reproduced in sherlock due to the cross platform nature of the issue

### Environment

```shell
System:
    OS: macOS 11.6.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.15.1 - /private/var/folders/bl/q3538n111qsck6ll41877f440000gp/T/xfs-d4f8e23c/node
    Yarn: 3.2.1 - /private/var/folders/bl/q3538n111qsck6ll41877f440000gp/T/xfs-d4f8e23c/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
```

### Additional context

![Screen Shot 2022-07-08 at 10 57 50 AM](https://user-images.githubusercontent.com/9656959/178045533-9d916737-3db3-4188-903d-32e0d0006ef5.png)

Here's the ci error if i do not include yarn install step

Yarnrc file

```
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs

supportedArchitectures:
  os:
    - darwin
    - linux
```

**Comment by seivan** [comment]
Do you know if SWC supplies prebuilt binaries for each platform? 

For instance, ESBuild does that, running install locally, gives me all the binaries (arm, x64, darwin, linux) etc.
They are part of the repo. 

Unless the package supplies prebuilt binaries or cross-build install script, there really isn't much you can do.

**Comment by laytong** [comment]
So when using my local (Mac) env it installs the darwin specific prebuilt
binary (which is at least better than all binaries) to the unplugged folder.

Ideally when using supportedArchitectures it would grab all binaries that
meet my specified platforms?

**Comment by laytong** [comment]
https://swc.rs/docs/getting-started#supported-binaries

**Comment by seivan** [comment]
@laytong That's what ESBuild does for me. It's part of it's post-install script (I am guessing).
They might have the binaries, but do they actually fetch them on install? 

<img width="317" alt="image" src="https://user-images.githubusercontent.com/55424/178117415-9ea68a42-20cc-4389-8183-1c4462d04963.png">

**Comment by laytong** [comment]
![Screen Shot 2022-07-11 at 12 41 04 PM](https://user-images.githubusercontent.com/9656959/178345195-56544e08-a11e-4a17-ba47-3de47a3886f3.png)
For me only the darwin x64 binary is installed on yarn install

**Comment by laytong** [comment]
https://github.com/swc-project/swc/issues/2898

I guess this is actually an issue with SWC rather than yarn?

**Comment by laytong** [comment]
Ok seems it does work,

But they need all supportedArchitectures critieria

needed to specify both cpu and libc sub options for @swc-core-linux-x64-gnu-npm to be installed

**Comment by laytong** [comment]
Can you point me to some guidance on when/why a package needs to be unplugged

i.e. in this instance could the package be modified in some way that it can link to these built binaries without needing to be unplugged?

**Comment by seivan** [comment]
As far as I understand it, something is unplugged if it has characteristics of not being something that can be shared. 
Like architecture or the fact that it needs to trigger a script (post-install, etc) gives some sort of hint that this might be very unique to your installations, thus not portable. 

Now for instance, CoreJS is unplugged, and it's unplugged because it has a post-install script, that you can disable in `.yarnrc.yml`.

**Comment by pegiadise** [comment]
> Ok seems it does work,
> 
> But they need all supportedArchitectures critieria
> 
> needed to specify both cpu and libc sub options for @swc-core-linux-x64-gnu-npm to be installed

Even with `yarn@4`, This continues to be the case for `supportedArchitectures` to behave correctly (all 3 options need to be specified, in order to install binaries for all of them). Maybe this will save someone some time. Don't know if bug or feature at the time of writing.

Example working config:
```yml
supportedArchitectures:
  os:
    - current
    - darwin
    - linux
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
```

**Comment by yuriy-yarosh** [comment]
@laytong this is still broken on yarn@4
It's still too puzzling why esbuild / swc doesn't get resolved properly from time to time.
@pegiadise yup, it still persists and it's a bug.

**Comment by laytong** [comment]
Thanks for the update.

I've moved away from using zero installs mostly due to issues like this, so I no longer check in my yarn cache

**Comment by marceljay** [comment]
The whole thing is flaky as hell. I am getting install issues on the Github CI ubuntu runners depending on how many zip files were cached. It's completely unpredictable.

**Comment by bazo** [comment]
is it possible to restrict supported archs only to given combination of os and cpu? like: 
darwin-arm64 only and linux-amd64 only?

**Comment by marceljay** [comment]
> is it possible to restrict supported archs only to given combination of os and cpu? like: darwin-arm64 only and linux-amd64 only?

I don't think it is, but that would be very helpful
