### ISSUE TITLE
[Bug?]: `CRA+yarn(pnp) workspaces ` : ERROR in Plugin "react" was conflicted between "package.json » eslint-config-react-app

### ISSUE THREAD

**Issue by DhirajBhakta** [yarnpkg/berry#4621]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Note that this is already tracked at https://github.com/facebook/create-react-app/issues/12209,

Using  **CRA+yarn2(in pnp mode)(with workspaces) .**
I've run `yarn add -D eslint-config-react-app` in the appropriate workspace (as specified in [your e2e test workflows for CRA](https://github.com/yarnpkg/berry/blob/master/.github/workflows/e2e-cra-workflow.yml))

Unable to run `yarn build`.
`yarn start` works for a while and breaks if any code changes are done (HMR).

The error thrown during both `yarn build` and `yarn start`(after a while) is 
```
ERROR in [eslint] Plugin "react" was conflicted between "package.json » eslint-config-react-app » /home/monorepo/.yarn/__virtual__/eslint-config-react-app-virtual-828d9d6105/0/cache/eslint-config-react-app-npm-7.0.1-78bab43841-a67e082180.zip/node_modules/eslint-config-react-app/base.js" and "BaseConfig » /home/monorepo/.yarn/__virtual__/eslint-config-react-app-virtual-6cd58be7a1/0/cache/eslint-config-react-app-npm-7.0.1-78bab43841-a67e082180.zip/node_modules/eslint-config-react-app/base.js".
```

**Switching back to `node-modules` nodeLinker in `yarnrc.yml` solves the issue.**

Any hints on why this happens in pnp mode? The error messages show that there is indeed a clash of two virtual packages of the same `eslint-config-react-app` version. If CRA installed `eslint-config-react-app` by default, why do we get the error `[eslint] Failed to load config "react-app" to extend from.` ( yarn add -D eslint-config-react-app fixes this, as per e2e tests)

### To reproduce

```sh
git clone https://github.com/DhirajBhakta/yarn2-pnp-cra-workspaces.git 
```

```sh
cd yarn2-pnp-cra-workspaces
yarn
```

```sh
cd packages/app
yarn build
```

### Environment

```shell
System:
    OS: Linux 5.18 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz
  Binaries:
    Node: 16.14.2 - /tmp/xfs-7446cd06/node
    Yarn: 3.2.1 - /tmp/xfs-7446cd06/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
```

### Additional context

Switching back to node-modules nodeLinker in yarnrc.yml solves the issue.

**Comment by merceyz** [comment]
> I've run yarn add -D eslint-config-react-app in the appropriate workspace (as specified in [your e2e test workflows for CRA](https://github.com/yarnpkg/berry/blob/master/.github/workflows/e2e-cra-workflow.yml))

That's not exactly what the e2e test runs, if you run the full command it should work.
```diff
-yarn add -D eslint-config-react-app
+yarn add -D eslint-config-react-app eslint
```

> Any hints on why this happens in pnp mode?

PnP is strict, if you only run `yarn add -D eslint-config-react-app` you now have two instances of `eslint-config-react-app`, one that has access to `eslint` and one that doesn't.

> If CRA installed eslint-config-react-app by default, why do we get the error [eslint] Failed to load config "react-app" to extend from. ( yarn add -D eslint-config-react-app fixes this, as per e2e tests)

It only installs it for itself, the `package.json` it creates for the project tries to use it as well but since it doesn't depend on it PnP refuses.
