### ISSUE TITLE
[Bug?]: Experimental ESM loader causes a crash with node v18.6.0

### ISSUE THREAD

**Issue by holgerkoser** [yarnpkg/berry#4629]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

With node v18.6.0 the experimental ESM loader causes a crash with e.g. `yarn dlx -q envinfo --preset jest` or `yarn add yorkie`.
```sh 
$ yarn dlx -q envinfo --preset jest
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_LOADER_CHAIN_INCOMPLETE]: "file:///tmp/xfs-d88818a9/dlx-309/.pnp.loader.mjs 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
    at new NodeError (node:internal/errors:387:5)
    at ESMLoader.resolve (node:internal/modules/esm/loader:860:13)
    at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:439:7)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
    at async loadESM (node:internal/process/esm_loader:83:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  code: 'ERR_LOADER_CHAIN_INCOMPLETE'
}
```
According to the [documentation](https://nodejs.org/api/esm.html#hooks):

> A hook that returns a value lacking a required property triggers an exception. A hook that returns without calling next<hookName>() and without returning `shortCircuit: true` also triggers an exception. These errors are to help prevent unintentional breaks in the chain.

But the current implementation of resolve in `.pnp.loader.mjs` does not have this required property. 
```diff
async function resolve$1(originalSpecifier, context, defaultResolver) {
  ...
  return {
+  shortCircuit: true
    url: resultURL.href
  };
}
```

### To reproduce

Start a docker container with nodejs `v18.6.0`
```sh
$ docker run -it --rm node:18.6-alpine3.16 sh
```

Initialize a new project with the latest yarn version. 
```sh
/ # cd ~
~ # yarn init -2
➤ YN0000: Retrieving https://repo.yarnpkg.com/3.2.1/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-3.2.1.cjs
➤ YN0000: Done in 0s 859ms
{
  name: 'root',
  packageManager: 'yarn@3.2.1'
}
```

Enable the ESM loader
```
~ # yarn config set pnpEnableEsmLoader true
➤ YN0000: Successfully set pnpEnableEsmLoader to true
```

Run e.g. `yarn dlx -q envinfo --preset jest`:
```sh
~ # yarn dlx -q envinfo --preset jest
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_LOADER_CHAIN_INCOMPLETE]: "file:///tmp/xfs-a30527da/dlx-510/.pnp.loader.mjs 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
    at new NodeError (node:internal/errors:387:5)
    at ESMLoader.resolve (node:internal/modules/esm/loader:860:13)
    at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:439:7)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
    at async loadESM (node:internal/process/esm_loader:83:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  code: 'ERR_LOADER_CHAIN_INCOMPLETE'
}

Node.js v18.6.0
```

### Environment

```shell
System:
  OS: Linux 5.10 Alpine Linux
  CPU: (4) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
Binaries:
  Node: 18.6.0 - /tmp/xfs-d694071f/node
  Yarn: 3.2.1 - /tmp/xfs-d694071f/yarn
  npm: 8.13.2 - /usr/local/bin/npm
```

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/4624
We'll backport and release it soon, until then you can use the latest canary build.
```sh
yarn set version canary
```

**Comment by Mukul1127** [comment]
> Fixed in #4624, we'll backport and release it soon, until then you can use the latest canary build.
> 
> ```shell
> yarn set version canary
> ```

I am on the latest canary build and it still doesn't work

**Comment by Mukul1127** [comment]
nvm yarn command still uses old version

**Comment by vire** [comment]
I can report this same issue with `node --version` -> `v16.17.0`

**Comment by merceyz** [comment]
> I can report this same issue with `node --version` -> `v16.17.0`

@vire Update to Yarn [v3.2.2](https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F3.2.2)

**Comment by dantabel** [comment]
@merceyz @vire I have the same issue with `node v16.17.0` and `yarn v3.2.2`. 

I can confirm that `yarn set version canary && yarn install` fixes the issue.

**Comment by merceyz** [comment]
@dantabel Did you update to v3.3.2 and run `yarn install` and still encounter the issue?

**Comment by shestakov-bc** [comment]
We also tried
```
yarn set version stable && yarn install
```
and it is still fails build. The only solution for us was to downgrade to node 16,16.x for now.

**Comment by merceyz** [comment]
@shestakov-bc Could you open an issue with a reproduction? The loader in Yarn v3.2.2 does set `shortCircuit: true`.

**Comment by dantabel** [comment]
@merceyz I downgraded to yarn v3.2.2 and it works without an issue now. Maybe something else got updated in the upgrade / downgrade process. Thanks for you help!
