### ISSUE TITLE
[Bug?]: Yarn3 exports cache files as .zip files

### ISSUE THREAD

**Issue by doelgonzo** [yarnpkg/berry#4663]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Just migrated from Yarn1 to Yarn3.2.1, and am seeing changes in the cache like this:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/5482592/180861881-795a5c0e-aa74-4069-915d-c16656c2a9a3.png">

We have strict rules in our CI that disallow the `.zip` files, but were fine with the tarball `.tar.gz` format... is there a setting for this to go back to being tarballs? I've read everywhere in doc and don't see anything that could help here. Thanks.

### To reproduce

```js repro
{
  "name": "dummy",
  "version": "1.0.0",
  "source": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "draco3d": "1.4.1"
  },
}
```

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 AMD EPYC 7B13
  Binaries:
    Node: 15.4.0 - /tmp/xfs-7aed82d5/node
    Yarn: 3.2.1 - /tmp/xfs-7aed82d5/yarn
    npm: 7.0.15 - ~/.nvm/versions/node/v15.4.0/bin/npm
  npmPackages:
    jest: 26.4.2 => 26.4.2
```

### Additional context

I am relatively new to this repo so not sure if it really matters to do any of this. The error CI is saying the binaries need to go to LFS, but not sure if that matters really here.

**Comment by arcanis** [comment]
No, zip is the only cache format
