### ISSUE TITLE
[Bug?]: add --dev --peer does not do what I mean

### ISSUE THREAD

**Issue by xenoterracide** [yarnpkg/berry#4691]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

 ```
 yarn workspace @cof/e1-transient-fault-handler add --dev --peer log4js@^6
```
does not add both a peer and dev dependency, also does not throw any kind of an error to say the options can't be combined

### To reproduce

I suspect this is sufficient

```
yarn add --dev --peer foo
```

### Environment

```shell
## System:
 - OS: macOS 11.6.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
## Binaries:
 - Node: 16.14.2 - /private/var/folders/xk/s3n8ww014pzbx2sn30ctz7000000gq/T/xfs-1836e7e1/node
 - Yarn: 3.2.1 - /private/var/folders/xk/s3n8ww014pzbx2sn30ctz7000000gq/T/xfs-1836e7e1/yarn
 - npm: 8.5.0 - ~/.asdf/plugins/nodejs/shims/npm
```

### Additional context

honestly I kind of think just doing --peer should do this by default

**Comment by iSatVeerSingh** [comment]
@xenoterracide are you working on it?

**Comment by xenoterracide** [comment]
No, I couldn't gain permission to do any contributions to anything.
