### ISSUE TITLE
[Feature] `yarn workspaces list --no-private`

### ISSUE THREAD

**Issue by CharlesStover** [yarnpkg/berry#4700]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

I want to run a custom, non-Yarn command on _all non-private workspaces_.
Today, I can only run _Yarn commands_ on _all non-private_ workspaces via `yarn workspaces foreach --no-private xyz`.
If the custom command isn't a Yarn command (like `./custom.sh`), then I do not have this option. I have to run `yarn workspaces list` to get a list of _all_ workspaces, which does not tell me if they are private.

**Describe the solution you'd like**

Like `foreach`, I think `list` should have a `--no-private` flag.

**Describe the drawbacks of your solution**

None?

**Describe alternatives you've considered**

`yarn workspaces foreach [somehow run a non-Yarn, non-package.json-script]`, but I feel like the syntax for that may not be intuitive.
I currently have to run list, get all packages, and execute the custom script on each package. I don't have the skillset to parse the workspace's `package.json` in bash to determine if it's private or not. 🙃

**Comment by RDIL** [comment]
Made a PR, you can try it out in the meantime with `yarn set version from sources --branch rdil/workspaces-list`.

**Comment by merceyz** [comment]
@RDIL Since your branch will be deleted when the PR is merged I updated your comment to point to the PR instead which should always work.
