### ISSUE TITLE
[Compatibility] dtslint

### ISSUE THREAD

**Issue by xenoterracide** [yarnpkg/berry#4721]
because of the patches applied to typescript to run, I suspect that dtslint also needs patches to run.

**Comment by RDIL** [comment]
I took a look, and I don’t believe it will.  It appears to use ESLint as an engine internally, which already supports PnP.

**Comment by arcanis** [comment]
Also note that when selecting the "Compatibility" template, the very first thing you removed is:

> **DO NOT OPEN COMPATIBILITY ISSUES**
> 
> Compatibility issues go in two categories:
> 
> - Either they are actionable (for instance the problem is that Yarn is missing support for
>   the `gist:` protocol), in which case you should open a bug (or an enhancement in this
>   particular example).
> 
> - Or they are not actionable (for instance the relevant package is throwing "accessing
>   undeclared dependency" errors), in which case you should open a Discussion, and probably
>   also an upstream bug.

**Comment by xenoterracide** [comment]
I considered this a special case because it downloads multiple versions of typescript and then runs them against the code. Even if it uses eslint internally it doesn't simply work as those typescript engines aren't PnP aware.
