### ISSUE TITLE
[Bug?]: ampersand at end of script command doesn't send to background 

### ISSUE THREAD

**Issue by sirpy** [yarnpkg/berry#4722]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

a script defined as
"inbackground:"sleep 5000 &"
doesn't run the command in the background when running `yarn inbackground`
running `npm run inbackground` works as expected

### To reproduce

```
"inbackground:"sleep 5000 &"
```

### Environment

```shell
System:
    OS: macOS 11.6.8
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 16.15.1 - /private/var/folders/6_/bw1_8q2s5fj3qvjxdnjhbpsr0000gn/T/xfs-cdf25f38/node
    Yarn: 3.2.2 - /private/var/folders/6_/bw1_8q2s5fj3qvjxdnjhbpsr0000gn/T/xfs-cdf25f38/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
```

**Comment by arcanis** [comment]
That's expected. Using `&` will send the process in background inside the same command (ie `foo & bar` will execute `foo` and `bar` in parallel), but the `yarn run` command will still wait for both to complete.

**Comment by sirpy** [comment]
@arcanis I dont get why this is the expected behaviour
This probably breaks so many scripts out there that need to run a service in background.
It prevents for example using `yarn workspaces foreach` which will get stuck if one of the projects doesnt go to background.
I guess  a work around would be to create a shell script that runs the command in background and have yarn run it

**Comment by arcanis** [comment]
If you want to run a script in background you can add the ampersand in the CLI (ie `yarn run foo&`). If you want multiple workspace scripts to run in parallel you can use the `-p,--parallel` flag.

If we weren't pausing, we wouldn't be able to print the process prefixes when multiple commands run in parallel, parallel execution would become much more dicey in general (you'd have to be very careful to wait processes, which isn't always easy without being overly verbose).
