### ISSUE TITLE
[Bug?]: Sherlock playground fails with `502: Bad Gateway` Error

### ISSUE THREAD

**Issue by trivikr** [yarnpkg/berry#4754]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Sherlock playground fails to load with `502: Bad Gateway`

<details>
<summary>Screenshot</summary>

![sherlock-playground-502-bad-gateway](https://user-images.githubusercontent.com/16024985/184757787-6acd9507-c4ae-4460-92d7-58a97458b343.png)

</details>

### To reproduce

Visit Playground link from docs: https://viko0.sse.codesandbox.io/

### Environment

```shell
N/A as this issue is with Sherlock Playground
```

### Additional context

* Docs on developing Sherlock reproduction: https://yarnpkg.com/advanced/sherlock#developing-your-reproduction
* Probably related https://github.com/yarnpkg/berry/issues/4753

**Comment by paul-soporan** [comment]
Fixed. The `package.json` in the sandbox decided to reset itself for no reason.

**Comment by trivikr** [comment]
Verified that Sherlock Playground works at https://viko0.sse.codesandbox.io/

<details>
<summary>Screenshot</summary>

<img width="1188" alt="sherlock-playground" src="https://user-images.githubusercontent.com/16024985/184886728-7a4fcb4e-3999-409e-b7d3-3ae27826fec2.png">

</details>

**Comment by trivikr** [comment]
Sherlock Playground now throws CORS error.
I've created a new bug report at https://github.com/yarnpkg/berry/issues/4760
