### ISSUE TITLE
[Feature] docs on `node_modules/.cache/prettier` convention

### ISSUE THREAD

**Issue by loynoir** [yarnpkg/berry#4757]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

```sh
# without node_modules
$ yarn prettier -w src
# now there is `node_modules/.cache/prettier`
```

**Describe the solution you'd like**

Describe pattern `node_modules/.cache/{{XXX}}` alternative in docs.

**Describe the drawbacks of your solution**

**Describe alternatives you've considered**

**Comment by arcanis** [comment]
This doesn't seem to be about Yarn.

**Comment by loynoir** [comment]
@arcanis 

What's your opinion about existing convention `node_modules/.cache` in yarn berry ecosystem which does not have `node_modules`?

Should `node_modules/.cache` keep unchanged?
