### ISSUE TITLE
[Bug?]: Update esbuild version in @yarnpkg/builder

### ISSUE THREAD

**Issue by alamothe** [yarnpkg/berry#4787]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Currently `@yarnpkg/builder` uses an outdated version of `esbuild`:
```
    "esbuild": "npm:esbuild-wasm@^0.11.20",
```
This creates problems, in particular I cannot use `concurrently` in my plugin due to: https://github.com/evanw/esbuild/issues/2487

Please upgrade.

### To reproduce

1. Create a plugin for Yarn which uses `concurrently`
2. Use `@yarnpkg/builder` to build it
3. At runtime it will fail because of ESBuild bug that was fixed long time ago

### Environment

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.16.0 - /private/var/folders/2d/zcwwn3dn2_z6_ktmh1_vw7lr0000gn/T/xfs-1861c79b/node
    Yarn: 3.2.2 - /private/var/folders/2d/zcwwn3dn2_z6_ktmh1_vw7lr0000gn/T/xfs-1861c79b/yarn
    npm: 8.11.0 - /opt/homebrew/opt/node@16/bin/npm
```

**Comment by arcanis** [comment]
That's tracked in https://github.com/yarnpkg/berry/pull/4732
