### ISSUE TITLE
[Bug]: Private scoped registries with auth do not behave sensibly

### ISSUE THREAD

**Issue by ctjlewis** [yarnpkg/berry#4810]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Yarn pisses itself upon being asked to authenticate a private scoped registry. Somehow this tool has shipped with this behavior for a substantial amount of time.

I shame every member of this team without exception in the strongest possible terms. I do not expect this to ever be fixed given the laziness observed in the current implementation. The only reasonable assumption is that this is not something that is tested for despite it being *incredibly* common in company codebases.

### To reproduce

`.yarnrc.yml`:

```
npmScopes:
  my-scope:
    npmRegistryServer: https://registry.test.com/
    npmAuthToken: XXX
    npmAlwaysAuth: true
```

Run `yarn install` with a `@my-scope/something` dependency:

```
yarn install v1.22.19
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@my-scope%2fsomething: Not found".
```

There's nothing more this tool could possibly want from me. It should not check the Yarn registry for this scope. The `npmScopes` flag seems to just be decoration, something nice to look at in the docs, and not anything with any actual resolution effect.

### Environment

```shell
N/A.
```

### Additional context

This tool only has one job, to resolve a module name to a tarball in a registry, yet it really struggles with it. Maybe overcomplication is bad.

Even here, we are only asking for two things: To resolve this scope to a private registry, and to do so with the auth token. We're 0 for 2. It's honestly impressive.

**Comment by ctjlewis** [comment]
Some genius really thought it was smart to deprecate reading from npmrc *without* testing `npmScopes` config. There's like 10 StackOverflow issues on this.

**Comment by paul-soporan** [comment]
I want to make it clear that your disrespectful behavior and passive-aggressive tone is not constructive, goes against the [code of conduct](https://github.com/yarnpkg/berry/blob/master/CODE_OF_CONDUCT.md), and will not be tolerated.

Being nice to maintainers goes a long way and is a much more constructive way to get help compared to shaming them.

---

As shown in your logs, you are using a Yarn Modern (v2+) configuration file with a Yarn Classic (v1) binary.
Either upgrade to Yarn Modern or use Yarn Classic configuration files.
