### ISSUE TITLE
[Bug] VSCode/TS doesn't detect new packages

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/berry#482]
**Describe the bug**

VSCode doesn't detect when new packages are added, which causes TypeScript to report unresolved modules. The workaround is to restart the TypeScript server from VSCode, but it's a bit clunky.

**To Reproduce**

Create an empty TS project, setup the PnPify VSCode SDK, then add a package. It won't show up in the editor.

**Additional context**

This is because the VSCode SDK doesn't have support for watching the PnP file and reloading itself when it changed. The way I would see it work would be like this:

- Implement a new [FakeFS](https://github.com/yarnpkg/berry/tree/master/packages/yarnpkg-fslib/sources) (let's say `IndirectFS`?) that would forward all calls to a **configurable** underlying FakeFS instance (all current FakeFS implementation take a static FakeFS).

- In the [`patchFs`](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-pnpify/sources/index.ts#L17-L24) method, add a watch on the PnP file itself (the path can be retrieved thanks to `require.resolve`). When it changes, bust the require cache, require the PnP API again, create a new `NodeModulesFS`, and swap the old one for the new one (thanks to the `IndirectFS` we created in the previous step).

- We now need to tell the TS server that the filesystem changed. I'm not entirely sure how to do that to be honest, this is something that would need to be investigated (do you have an idea, @vlasenko? Maybe the `IndirectFS` could wrap all calls to `watch` and `watchFile` and always trigger them when switching from an underlying FS to another).

**Comment by vlasenko** [comment]
@arcanis Yes, we should trigger `watch` and `watchFile` listeners with `rename` event. The complicated part is the list of "changed" files that should be submitted to `rename` event as a first argument, we need to compute this file list. We should do it in a smart way, we cannot just trigger all watch listeners without a reason, or pass them incorrect file list, because that will result in high CPU load.

**Comment by arcanis** [comment]
I don't know if TS works like Flow in this regard, but I remember that Flow makes a full typecheck if more than X files changed - which is essentially what manually restarting the server does anyway 🤔

**Comment by arcanis** [comment]
Closing this one - important note: the watch mechanism implemented in #486 only works if your workspaces contain a `tsconfig.json` file. You can easily just extend the one from the root, just like we do [here](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/tsconfig.json).
