### ISSUE TITLE
[Feature] Environment variable flag to automatically handle YN0008

### ISSUE THREAD

**Issue by probablyup** [yarnpkg/berry#4829]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

As a user of yarn workspaces, when I run `yarn` if the workspace needs to be rebuilt I would like this to happen automatically instead of having to run `yarn` a second time.

This is specifically in regards to `YN0008` error, which indicates that a package changed and the workspace needs to be rebuilt. It's unclear to me why this wouldn't be done seamlessly by `yarn` the first time?

**Comment by arcanis** [comment]
> It's unclear to me why this wouldn't be done seamlessly by `yarn` the first time?

It is done seamlessly. This message just notifies you that the install will take a bit more time because of the rebuild.
