### ISSUE TITLE
[Feature] Add ability to exclude packages, or ignore specific advisories in yarn npm audit

### ISSUE THREAD

**Issue by hughdavenport** [yarnpkg/berry#4842]
Hey folks,

I'm just wondering whether I missed something from MR #4356 or not. This doesn't seem to have landed in the stable release yet (or I may just misunderstand how the releases work). Can someone let me know what needs doing to get this into stable?

Apologies if this is the wrong forum to ask. I tried on the MR itself but got no response.

Cheers,

Hugh

**Comment by merceyz** [comment]
> I tried on the MR itself but got no response.

Sorry about that, I'll close this issue and respond there.
