### ISSUE TITLE
[Bug?]: After upgrading from yarn 1 to yarn 3, create-react-app 4 does not build code - very esoteric error

### ISSUE THREAD

**Issue by aliak00** [yarnpkg/berry#4847]
### Self-service

- [x] I'd be willing to implement a fix

### Describe the bug

Ok so this is a bit of a tricky one. I'm not sure at all where to start with this so I'm just starting here as it's only started occurring after upgrading from yarn 1 to yarn 3. I suspect that another problem was just exposed, but if anyone has any suggestions I'm all ears.

Basically, after I followed the migration process to yarn 3 - building our app results in

```
❯ npx react-scripts build
Creating an optimized production build...
Failed to compile.

./src/widgets/NodePathBar/contextMenus.tsx
TypeError: /Users/aliak/prototype/src/widgets/NodePathBar/contextMenus.tsx: Property types[1] of TSUnionType expected node to be of a type ["TSType"] but instead got "AnyTypeAnnotation"
```

### To reproduce

I am really sorry, but I do not have any way to reproduce it since our code base is quite huge and I do not know where to go with the error. I _do_ know what lines of code cause the error and how to make the error go away. But it makes zero sense to be:

If anyone has any ideas of how I can try and reproduce this I'm all ears!

Code with error:
```ts
let items: ContextMenuOption[] = getChildrenAsMenuItems(nodeWithChildren, panelUIState, layoutManager);
if (items.length >= 10) {
  const moreItems: ContextMenuOption = { ... } // stuff
  items = items.slice(0, 10);
  items.push(moreItems);
}
```

Code without error (just change `items` to use splice instead of self assign
```ts
const items: ContextMenuOption[] = getChildrenAsMenuItems(nodeWithChildren, panelUIState, layoutManager);
if (items.length >= 10) {
  const moreItems: ContextMenuOption = { ... } // stuff
  items.splice(10);
  items.push(moreItems);
}
```

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 14.18.2 - /private/var/folders/gz/7tc87_nx1ls4dcxx0msmwn6r0000gn/T/xfs-c06335bd/node
    Yarn: 3.2.3 - /private/var/folders/gz/7tc87_nx1ls4dcxx0msmwn6r0000gn/T/xfs-c06335bd/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v14.18.2/bin/npm
```

### Additional context

I had a suspicion that it maaay be typescript config, but again I don't see how and why now. I'll paste our config here just in case

```json
{
  "compilerOptions": {
    "module": "esnext",
    "target": "es5",
    "lib": ["dom", "dom.iterable", "es2015.collection", "es2015.iterable", "esnext"],
    "noImplicitReturns": false,
    "experimentalDecorators": true,
    "downlevelIteration": true,
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "noImplicitAny": true,
    "jsx": "react-jsx",
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src", "functions/src/actions/insertGettingStartedNodes.ts"],
  "exclude": ["./src/explore/**/*"],
  "baseUrl": "src/types",
  "typeRoots": ["src/types"]
}
```

**Comment by RDIL** [comment]
I’m guessing that this is the result of something being resolved differently then before.  React-scripts is giant and very problematic in that way.  Either way, this isn’t really a Yarn issue, and with out a reproduction, this can’t be fixed on our end.
