### ISSUE TITLE
[Feature] Local module storage

### ISSUE THREAD

**Issue by talentlessguy** [yarnpkg/berry#488]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

I'm tired of installing 1K+ dependencies on my project and download them again even though I have them in the other project.

**Describe the solution you'd like**

Create a pnpm-like storage, smth like `~/.yarn/storage` where all download modules will be located. Then, when we want to run `yarn install` some modules, instead of downloading will be linking from the storage to save time and space.

**Describe the drawbacks of your solution**

This idea may cause some random bugs while linking dependencies, for example two projects use different version of a dependency. Also, I don't know yet what is a good way to check if dependency in local storage is up-to-date.

**Describe alternatives you've considered**

Using pnpm which I don't like because it has nasty bugs and its CLI is less user-friendly.

**Comment by deini** [comment]
Looks like you are looking for the [enableGlobalCache](https://next.yarnpkg.com/configuration/yarnrc#enableGlobalCache) config.

**Comment by talentlessguy** [comment]
@deini thank you, I didn't notice. Closing it

**Comment by arcanis** [comment]
Fwiw it's a difficult choice - in the v1 people weren't aware of the offline mirror, in the v2 they aren't aware of the global cache. I think the offline mirror is important for the health of the ecosystem (I don't expect npm to stick around in 10 years) so I'd like to keep it the default, but I wonder if there's something we could do to provide a better experience 🤔
