### ISSUE TITLE
[Bug?]: Official hook list was missing `getNpmAuthenticationHeader` hook

### ISSUE THREAD

**Issue by jj811208** [yarnpkg/berry#4880]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I saw on the [plugin-tutorial](https://yarnpkg.com/advanced/plugin-tutorial)

> Note: We don't yet have a list of hooks. If you're interested to improve this documentation by generating the hook list from our source code, please contact us on our Discord server!

I want to contribute, so i inventoried the codebase looking for all our hooks and i found that we already had a hook list, and they were generated automatically.

However, the official hook list was missing `getNpmAuthenticationHeader` hook, but the local site run by `yarn develop` has this hook.

I looked at the related code, but I don't see anything wrong with it.

### Environment

```shell
System:
  OS: macOS 12.4
  CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
Binaries:
  Node: 16.13.2 - /private/var/folders/mv/l0p5fs3508n59dbkg__dll0w0000gn/T/xfs-e4abfa79/node
  Yarn: 4.0.0-rc.20.dev - /private/var/folders/mv/l0p5fs3508n59dbkg__dll0w0000gn/T/xfs-e4abfa79/yarn
  npm: 8.18.0 - ~/.asdf/plugins/nodejs/shims/npm
```

### Additional context

| Local  | Official |
| ------------- | ------------- |
| ![Local](https://user-images.githubusercontent.com/25342059/191548047-7b2738cf-4742-4499-a9d5-03fc634a56a9.png)  | ![offcal](https://user-images.githubusercontent.com/25342059/191548057-8761b018-d6ff-48b2-b25b-bbfa3c40b627.png)  |

The official hook list was missing `getNpmAuthenticationHeader` hook

**Comment by merceyz** [comment]
I've rebased the `website` branch to match the latest stable release (`v3.2.3`) and cherry-picked https://github.com/yarnpkg/berry/pull/3888 to it so this is fixed now.

> I saw on the [plugin-tutorial](https://yarnpkg.com/advanced/plugin-tutorial) [...] We don't yet have a list of hooks [...] and they were generated automatically.

Yeah, we should remove that part from the documentation, would you like to make a PR for that?
