### ISSUE TITLE
[Feature] PnP - "scoped" / "focused" workspace installs?

### ISSUE THREAD

**Issue by tomasz-sodzawiczny** [yarnpkg/berry#489]
Will PnP / yarn v2 support in any way "scoped" / "focused" installs of selected workspaces? Here is what I mean:

Assuming a monorepo with multiple node applications in it:
```
.
└── packages
    ├── app1 (depends on shared)
    ├── app2 (depends on shared)
    └── shared
```

How can I create a minimal deployable container with `app1` or `app2` (but not the other one) - with **just the necessary dependencies**?

**Comment by arcanis** [comment]
I've transferred your issue to the v2 repo, as that's where we keep most discussions about the v2.

I've thought about this some more, and I think it would be fairly easy to implement that through a plugin - what you're looking for is basically to get a "mask" of the cache files needed for a particular workspace to run, and that's something the v2 API can do.

Basically you'd traverse the tree going from your "focused" workspace, and call the fetcher on each package you find. They would in turn trigger the cache, which would mark each needed file in the [`markedFiles`](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/sources/Cache.ts#L21) property. You'd only have to surface this information with the format you want.

**Comment by eps1lon** [comment]
> That being said, in the v2, I think you would have a single cache with all your dependencies that would then be shared by the three containers. I'm not sure focused workspaces would provide a strong enough benefit compared to the infra cost.

It's handy for dependencies that have expensive postinstall steps like cypress or puppeteer. Configuring CI to cache the built binaries is sometime complicated and sometimes won't have any benefit either: Azure Pipelines cache takes 30s to download the cache with the cypress binary while building it from scratch takes 45s. 

Being able to tell yarn which workspaces to install could solve those issues.

**Comment by arcanis** [comment]
An alternative to the approach exposed above would be to disconnect the workspaces. Basically, have a plugin detect what's the workspace-only dependency tree starting from your focused workspace (that's easy to retrieve), and update the manifest of any workspace not in the dependency tree to remove all their dependency fields.

You can do this either before generating your container (if you use zero-install; in which case you'll want to reset your repository after building each container, which sounds reasonable), or after, at runtime.

I think I like this approach the best because every following command will operate on exactly the subset of the project that you want without requiring particular magic. How does that sound?

**Comment by eps1lon** [comment]
> An alternative to the approach exposed above would be to disconnect the workspaces. 

That might work. When I tested this a few weeks ago it didn't work though. I wasn't able to have isolated worktrees at all (even with zero deps). Maybe that changed now.

It does require some additional steps though. I would need to have one workspace that includes the test pages for cypress (since I want to test components from the repository) i.e. the server and one disconnected worktree for the actual tests. And usually you have a single script that starts both which also doesn't work in this case. I guess this would work but having focused installs would solve this with a single flag instead of having to reorganize repo structure.

**Comment by arcanis** [comment]
Here's a prototype for what I have in mind. It finds all the dependencies of the workspace you're into, filters out to only keep workspaces, and update every workspace it didn't traverse to remove their dependencies. After that it should just be a matter of running a regular install (at the moment my snippet just persist the manifest changes to disk):

```
module.exports = {
    name: `yarn-plugin-focused`,
    factory: require => {
        const {BaseCommand} = require(`@yarnpkg/cli`);
        const {Configuration, Project, structUtils} = require(`@yarnpkg/core`);
        const {Command} = require(`clipanion`);

        class FocusCommand extends BaseCommand {
            async execute() {
                const configuration = await Configuration.find(this.context.cwd, this.context.plugins);
                const {project, workspace} = await Project.find(configuration, this.context.cwd);

                const seen = new Set();
                const focused = new Set();

                const focusWorkspace = locatorHash => {
                    const pkg = project.storedPackages.get(locatorHash);
                    if (seen.has(pkg.locatorHash))
                        return;

                    seen.add(pkg.locatorHash);

                    const workspace = project.tryWorkspaceByLocator(pkg);
                    if (workspace !== null)
                        focused.add(workspace);

                    for (const descriptor of pkg.dependencies.values()) {
                        const resolution = project.storedResolutions.get(descriptor.descriptorHash);
                        focusWorkspace(resolution);
                    }
                };

                focusWorkspace(workspace.anchoredLocator.locatorHash);

                for (const workspace of focused)
                    this.context.stdout.write(structUtils.prettyWorkspace(configuration, workspace) + `\n`);

                for (const workspace of project.workspaces) {
                    if (focused.has(workspace))
                        continue;

                    workspace.manifest.dependencies.clear();
                    workspace.manifest.devDependencies.clear();
                    workspace.manifest.peerDependencies.clear();
                }

                await project.persist();
            }
        }

        FocusCommand.addPath([`focus`]);

        return {
            default: {
                commands: [
                    FocusCommand,
                ],
            },
        };
    },
};
```

**Comment by j** [comment]
@arcanis something like this supported out of the box will make the day of so many people trying to get into the mono-repository space.

CI/CD systems are slowly rolling out support for monorepositories as well, eventually killing the argument that monorepositories are terrible.

We too want to use shared code between client and all micro-services in a single mono-repository.

```
apps/
  graphql/
  email/
  cdn/
  frontend/
libs/
  db/
  interfaces/
  ...
```

Each `app` should be able to have a simple way to create a deployable.  This is not supported in any "workspace" type system.

In CI/CD, ideally I can just `yarn install --filter apps/graphql --production --rootDir=/dist/graphql` (made up flags).

**Comment by arcanis** [comment]
I made a quick implementation in the `workspace-tools` plugin. You'll need to build it yourself, and you'll need the core version from my branch (`yarn set version from sources --branch 1087`). Let me know what you think.

**Comment by mariusmarais** [comment]
@arcanis Thanks, have been using `workspaces focus` with `node_modules` very successfully in building minimal Docker containers from a mono-repo!

Testing out PnP now, but while `focus` updates the `.pnp.js` file, it does not remove unneeded cache files. Is there a simple way to do this, or is that what the `do not persist` comment is about in https://github.com/yarnpkg/berry/pull/1087?

(Happy to take this conversation to a more appropriate place..)

**Comment by merceyz** [comment]
There is a plugin you can use for preparing your docker containers, it was made to create small production deployments and has example docker files.
https://gitlab.com/Larry1123/yarn-contrib/-/tree/master/packages/plugin-production-install

**Comment by mariusmarais** [comment]
Thanks @merceyz that's exactly what I need.
