### ISSUE TITLE
AWS CodeArtifact registry produces yarn.lock that is polluted with __archiveUrls 

### ISSUE THREAD

**Issue by kaestlej-tng** [yarnpkg/berry#4910]
When using AWS CodeArtifact as a proxy for NPM-Central the yarn.lock contains `__archiveUrl` tags inside the resolution field.

### Steps to reproduce

1. Setup a CodeArtifact in AWS and configure it in a project (see https://docs.aws.amazon.com/codeartifact/latest/ug/npm-yarn.html#npm-yarn-configure-yarn-command)
2. Add it to the `.yarnrc.yml`
```npmRegistries:
  "<CODE_ARTIFACT_URL>":
    npmAlwaysAuth: true
    npmAuthToken: "${CODEARTIFACT_AUTH_TOKEN}"

npmRegistryServer: "<CODE_ARTIFACT_URL>"
```

### Expected Result
`yarn.lock` does not change

```
"react@npm:16.14.0":
  version: 16.14.0
  resolution: "react@npm:16.14.0"
```

### Actual Result
`yarn.lock` gets polluted with `__archiveUrl` information

```
"react@npm:16.14.0":
  version: 16.14.0
  resolution: "react@npm:16.14.0::__archiveUrl=<CODE_ARTIFACT_URL>%2Freact%2F-%2Freact-16.14.0.tgz"
```

### Assumed Reason
In https://github.com/yarnpkg/berry/blob/8ff27df294a3bf056d26675f12d85aeb553d8402/packages/plugin-npm/sources/NpmSemverFetcher.ts#L60 there exists a replacement for `%2f` to `/` but CodeArtifact produces Urls containing `%2F`, so extending the RegExp should probably solve the issue.

**Comment by eddienubes** [comment]
Also reproducible for me and breaks the installation flow when `nodeLinker` is set to `node_modules`.
The following error is thrown: 
```
➤ YN0012: │ @types/node@npm:18.7.15::__archiveUrl=<registry_url>/<package_bundle_name> isn't supported by any available linker
```

**Comment by mhassan1** [comment]
I haven't figured out why, but this suddenly stopped happening for me within the past week. @kaestlej-tng @eddienubes Have you noticed this?

**Comment by kaestlej-tng** [comment]
We got a notifiction from AWS end of March 23 stating that they drop the port from the returned URLs for NPM packages in CodeArtifact. That  seemed to be the issue and is now fixed for us. 

We had to recreate all lock files because renovate was confused with the change in the resolution field
