### ISSUE TITLE
[Bug?]: ReferenceError when initializing plugin programmatically for Yarn 3.2.3

### ISSUE THREAD

**Issue by noahnu** [yarnpkg/berry#4911]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When attempting to use Configuration.find, the constraint plugin is crashing with:

```raw
ReferenceError: tau_file_system is not defined (when initializing @yarnpkg/plugin-constraints, defined in /Users/noah/dev/repo/.yarnrc.yml)
    at /Users/noah/dev/repo/.yarn/plugins/@yarnpkg/plugin-constraints.cjs:20:644
    at /Users/noah/dev/repo/.yarn/plugins/@yarnpkg/plugin-constraints.cjs:28:18004
    at /Users/noah/dev/repo/.yarn/plugins/@yarnpkg/plugin-constraints.cjs:6:262
    at /Users/noah/dev/repo/.yarn/plugins/@yarnpkg/plugin-constraints.cjs:28:28253
    at factory (/Users/noah/dev/repo/.yarn/plugins/@yarnpkg/plugin-constraints.cjs:49:4337)
    at plugin (/Users/noah/.yarn/berry/cache/@yarnpkg-core-npm-3.2.4-0efc3a3ceb-8.zip/node_modules/@yarnpkg/core/lib/Configuration.js:820:45)
```

if I remove the constraints plugin, then the workspace-tools plugin crashes with a similar error about "_a is not defined".

### To reproduce

```repro
await packageJsonAndInstall({
  dependencies: {
    "@yarnpkg/cli": "^3.2.3",
    "@yarnpkg/core": "^3.2.4",
    "@yarnpkg/fslib": "^2.7.1",
    "@yarnpkg/sdks": "^3.0.0-rc.21",
    "@yarnpkg/shell": "^3.2.4",
  },
});

// TODO: Install constraints plugin here and reference in the .yarnrc.yml
// not sure how to do this in sherlock, it says the plugins are already installed

await node(`{
    const { ppath } = require('@yarnpkg/fslib');
    const { Configuration } = require('@yarnpkg/core');
    const { getPluginConfiguration } = require('@yarnpkg/cli');
    await Configuration.find(ppath.cwd(), getPluginConfiguration(), { useRc: true });
}`)
```

### Environment

```shell
System:
  OS: macOS 12.6
  CPU: (8) arm64 Apple M1 Pro
Binaries:
  Node: 16.17.0 - /private/var/folders/5m/4x2x5y6x5x5ck7rnpzq23dlc0000gn/T/xfs-a3eb9f50/node
  Yarn: 3.2.3 - /private/var/folders/5m/4x2x5y6x5x5ck7rnpzq23dlc0000gn/T/xfs-a3eb9f50/yarn
  npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
```

### Additional context

Discord thread: https://discord.com/channels/226791405589233664/1024014282830123090

I tried installing the plugins from the same release as yarn 3.2.3 to see if it was a compatibility issue, but that didn't seem to fix it.

**Comment by jj811208** [comment]
Hi, I ran the process you described in 3.2.3 and 4.0.0-rc, but I was unable to reproduce your error.

Here is the repo used to reproduce it, can you clone it and test if it gives the same error?

https://github.com/jj811208/temp-repo-for-debug

---

If you can't reproduce the error in this repo, I suggest you try the following steps in your project

1. delete `.yarn/plugins/@yarnpkg/plugin-constraints.cjs`
2. delete this paragraph from yarnrc.yml

```
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
```

3. run `yarn plugin import constraints` to reinstall it

**Comment by noahnu** [comment]
Interesting. Apparently this only happens when running the script using ts-node. Not sure why.

**Comment by noahnu** [comment]
Here's an updated repro: https://github.com/jj811208/temp-repo-for-debug/pull/1

**Comment by jj811208** [comment]
Then I guess it's a problem of incompatibility between `pnp` and `ts-node`, for some reason there's no guarantee that `pnp` supports all libraries at the moment.

Maybe you can try https://github.com/yarnpkg/berry/discussions/4044#discussioncomment-2708599 .

**Comment by noahnu** [comment]
We use ts-node for all our projects at my company, along with yarn pnp. This is the only issue we're encountering, and for our use case we're able to disable useRc to bypass the error.

The maintainer of ts-node is active in the yarn discord, so I'll keep this issue open.

**Comment by merceyz** [comment]
The issue is that `tau-prolog` isn't isn't strict mode compatible, you need to tell `ts-node` to leave the plugins alone, the following diff fixes the reproduction from https://github.com/yarnpkg/berry/issues/4911#issuecomment-1267602731

```diff
diff --git a/tsconfig.json b/tsconfig.json
index 2743742..ee353fc 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -18,6 +18,7 @@
         "*.{ts,js}"
     ],
     "ts-node": {
-        "transpileOnly": true
+        "transpileOnly": true,
+        "ignore": [".yarn/.*"]
     }
 }

```

**Comment by noahnu** [comment]
In my project I'm using ts-node on a local workspace which is getting virtualized so `.yarn/*` is too generic since I want to transpile the virtualized dependencies.

Here's another example: https://github.com/tophat/monodeploy/pull/517. In this branch, I'm trying to run:

```
yarn ts-node $(yarn bin monodeploy) --dry-run
```

`yarn bin monodeploy` points to a TS file (it uses the publishConfig / typescript pattern that yarn berry uses), so I need to transpile it to run it, unless there's a way to apply the publishConfig "main" / "exports" overrides prior to publishing..

I'll dig into this on the ts-node side though since at least now I know what's going wrong. Thanks.

**Comment by merceyz** [comment]
> so .yarn/* is too generic since I want to transpile the virtualized dependencies

In that case change it to `.yarn/plugins/.*`.

**Comment by noahnu** [comment]
That works! For some reason I was thinking it was due to the @yarnpkg dependencies and not the yarn binary+plugins (momentary lapse there 😄 )
