### ISSUE TITLE
[Bug?]: TS 4.8.4 somehow fails to find modules

### ISSUE THREAD

**Issue by simPod** [yarnpkg/berry#4915]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

TS 4.8.3 works fine but 4.8.4 fails to find like any module (using pnp)

> error TS2307: Cannot find module 'lodash' or its corresponding type declarations.

### To reproduce

https://github.com/simPod/berry/actions/runs/3139391885/jobs/5099759100

Run test

### Environment

```shell
See https://github.com/simPod/berry/actions/runs/3139391885/jobs/5099759100
```

**Comment by stefpb** [comment]
Sorry, for me this problem still exists. What i have to do to retrieve the latest changes? I tried `yarn set version latest` but it doesnt change anything.

**Comment by koshic** [comment]
@stefpb fix available only for 4.0.0-xx branches - see https://github.com/johnsoncodehk/volar/issues/918#issuecomment-1261161129

**Comment by ChanhyukPark-Tech** [comment]
typescript 4.8.4 not working now !! 
10/05!!!

**Comment by ChanhyukPark-Tech** [comment]
There is an error in the current version of typescript 4.8.4.
Lowering it to 4.8.3 will resolve it. From yarn-berry(yarn2)
I've looked for a lot of ways to lower the version of the typescript.
follow my process

```
yarn remove typescript
yarn add -D typescript@4.8.3
rm -rf .yarn/sdks/typescript
yarn dlx @yarnpkg/sdks base
```

don't forget your vscode look workspace's typescript version (mac : cmd + shift + p => typescript version use Workspace)

**Comment by stefpb** [comment]
> @stefpb fix available only for 4.0.0-xx branches - see [johnsoncodehk/volar#918 (comment)](https://github.com/johnsoncodehk/volar/issues/918#issuecomment-1261161129)

Ok, now i have the feeling i have to wait until `yarn set version latest` should work. Do you know when there will be a new release of yarn?

**Comment by merceyz** [comment]
The fix is now available in [v3.2.4](https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F3.2.4)
```sh
yarn set version berry
```

**Comment by IgnusG** [comment]
Hmm, for me it still doesn't seem to work on yarn v3.2.4. Downgrading to typescript 4.8.3 worked well though

**Comment by koshic** [comment]
> Hmm, for me it still doesn't seem to work on yarn v3.2.4. Downgrading to typescript 4.8.3 worked well though

Try to refresh yarn.lock too

**Comment by IgnusG** [comment]
> > Hmm, for me it still doesn't seem to work on yarn v3.2.4.
> 
> Did you run an install?
> 
> > Try to refresh yarn.lock too
> 
> That shouldn't matter.

Yeah I did but it was still failing. After changing to typescript version 4.8.3 and installing and then back to 4.8.4 now and installing again it works though 🎉  (maybe something was caching incorrectly or I was running the commands in the wrong order)

**Comment by gmeligio** [comment]
> > > Hmm, for me it still doesn't seem to work on yarn v3.2.4.
> > 
> > 
> > Did you run an install?
> > > Try to refresh yarn.lock too
> > 
> > 
> > That shouldn't matter.
> 
> Yeah I did but it was still failing. After changing to typescript version 4.8.3 and installing and then back to 4.8.4 now and installing again it works though 🎉 (maybe something was caching incorrectly or I was running the commands in the wrong order)

It was failing for me in vscode with yarn v3.2.4 but the hint "running the commands in the wrong order" solved it. I got it working by  reverting my changes and doing the updates in this order:
1. `yarn set version latest` to get yarn v3.2.4
2. `yarn upgrade-interactive` to get typescript v4.8.4
3. `yarn dlx @yarnpkg/sdks vscode` to get the yarn sdks for vscode
