### ISSUE TITLE
[Bug] Typo on docs

### ISSUE THREAD

**Issue by swrobel** [yarnpkg/berry#492]
**Describe the bug**
The [Offline Cache page](https://next.yarnpkg.com/features/offline-cache) has a sentence that trails off: "Starting from Yarn v2, Yarn will by default configure the cache to be local to your project. This is done to make it easier for you to store it as part of your repository, which we believe is the best way to ensure ."

Ensure what?

Furthermore, it's impossible to figure out where the docs are housed so I could just report this in the proper place. Is there a reason their source is obfuscated?

**Comment by swrobel** [comment]
Found the docs in https://github.com/yarnpkg/berry/tree/master/packages/gatsby/content which wasn't very intuitive

**Comment by arcanis** [comment]
To ensure "that your project installs & deployments will continue to work in the future regardless of the availability of the registries you use".

> Furthermore, it's impossible to figure out where the docs are housed so I could just report this in the proper place. Is there a reason their source is obfuscated?

For the record we have a "Contributing" section on the website: https://next.yarnpkg.com/advanced/contributing#writing-documentation

We should make a `CONTRIBUTING.md` file that points to it, though!
