### ISSUE TITLE
[Bug]: Yarn linked package.json leads to restore problems on other machines

### ISSUE THREAD

**Issue by Blackclaws** [yarnpkg/berry#4923]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When using yarn link in order to locally develop a project and its dependency the package.json file gets changes.

If this change gets checked in (as is usual for most developers), a restore on a different machine will fail, citing that the portal location is not available.

This requires the other side to run ```yarn unlink --all``` to get back into a working state.

By default yarn link should _not_ fail even if the portal links are committed to package.json.

### To reproduce

yarn link a dependency. Delete the folder for the dependency.

### Environment

```shell
yarn version 3.2.3
```

### Additional context

Related: https://github.com/yarnpkg/berry/issues/4870
Related: https://github.com/yarnpkg/berry/issues/90#issuecomment-940936426

**Comment by arcanis** [comment]
Sure it should. If you commit a `file:` dependency pointing to nowhere it will crash as well, for good reason.
