### ISSUE TITLE
[Bug?]: The remote server failed to provide the requested resource

### ISSUE THREAD

**Issue by bebbi** [yarnpkg/berry#4924]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Given a `yarn workspace` with `packages`, one of which is an app with its own git repo, I've migrated from classic to 3.2.3 and since that, `yarn` fails with

```
➤ YN0035: │ @myscope/some-workspace-module@npm:^1.1.2: The remote server failed to provide the requested resource
➤ YN0035: │   Response Code: 404 (Not Found)
➤ YN0035: │   Request Method: GET
➤ YN0035: │   Request URL: https://registry.yarnpkg.com/@myscope%2fsome-workspace-module
➤ YN0000: └ Completed in 4s 999ms
➤ YN0000: Failed with errors in 5s 2ms
```

The 404 is obvious as this is a workspace-only module not published to npm. Why is it not looking in the workspace? `yarn` has been executed inside the workspace base folder and I can see the symlink
```
node_modules/@myscope/some-workspace-module -> ../../packages/some-workspace-module
```

### To reproduce

I'm trying to see if this has a straightforward answer, if not I will try to create a repro.

### Environment

```shell
System:
    OS: macOS 12.6
  Binaries:
    Node: 16.17.0 - /private/var/folders/ht/18wcb1f538bgx47qrfc1n0q80000gq/T/xfs-3bf67840/node
    Yarn: 3.2.3 - /private/var/folders/ht/18wcb1f538bgx47qrfc1n0q80000gq/T/xfs-3bf67840/yarn
    npm: 8.15.0 - ~/.volta/tools/image/node/16.17.0/bin/npm
```

### Additional context

Workspace visualization:

```
Workspace (git repo)
   | packages
   |   | some-workspace-module (package.json name: "@myscope/some-workspace-module", version: "1.1.2", private: true)
   |   | app (git repo) <- package.json dependency "@myscope/some-workspace-module": "^1.1.2", yarn inside this directory fails
   | node_modules
   |   | @myscope
   |   |   |  some-workspace-module -> ../../packages/some-workspace-module
```

**Comment by RDIL** [comment]
Try using `workspace:*` as the version instead of `^1.1.2`.

**Comment by bebbi** [comment]
@RDIL Thanks! It looks like this works well. Do you mind clarifying whether that means this is an exclusive/or thing? So in berry, is it *either* version number + pull from registry *or* `workspace:*` + package stays local?

**Comment by arcanis** [comment]
Probably your local workspace is 2.0, or something else incompatible with ^1.2, so Yarn fallbacks to the registry.

**Comment by bebbi** [comment]
How do I find the workspace version? Nothing in `package.json`, and digging unearthes

`~/.yarnrc ` (ignored I think)

```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

lastUpdateCheck 1664205579652
workspaces-experimental true
```

`~/.yarnrc.yml `

```
enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  babel-preset-react-app@10.0.x:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": ^7.16.0

yarnPath: .yarn/releases/yarn-3.2.3.cjs
```

**Comment by arcanis** [comment]
If you don't have any version in your workspace, then it can't be used by plain semver ranges (since it can't match them).

**Comment by bebbi** [comment]
Apologies @arcanis, I haven't been able to find anything about how to set the version of a workspace.
Do I add a `version` field there?

```
  "workspaces": {
    "packages": [
      "packages/*",
      "apps/*"
    ]
  },
```

**Comment by RDIL** [comment]
In the actual workspace's package.json, add the version field.

**Comment by bebbi** [comment]
In case it helps others, I had an unused version field (was a workspace but not a controlled monorepo) and it kept it from working. Removing the version field got it to work again.
