### ISSUE TITLE
[Bug?]: Frequent and non-deterministic network issues from registry.yarnpkg.com

### ISSUE THREAD

**Issue by AndrewRayCode** [yarnpkg/berry#4925]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I have received all of these errors trying to install `node-notifier`. 

To make this more challenging to debug, I'm in a docker container / docker build step, and the host machine is on a VPN which requires MITM certs to work. However, as I recently got a 503 error from yarnpkg, I'm not 100% convinced this is related to my local network.

Here are the errors blocking my local install I've received in the last 24 hours:

> error An unexpected error occurred: "https://registry.yarnpkg.com/node-notifier/-/node-notifier-10.0.1.tgz: invalid stored block lengths".

> error An unexpected error occurred: "https://registry.yarnpkg.com/node-notifier/-/node-notifier-10.0.1.tgz: Request failed \"503 Service Unavailable\""

> error https://registry.yarnpkg.com/node-notifier/-/node-notifier-8.0.2.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?"

> error https://registry.yarnpkg.com/node-notifier/-/node-notifier-8.0.2.tgz: invalid block type

> error An unexpected error occurred: "https://registry.yarnpkg.com/node-notifier/-/node-notifier-10.0.1.tgz: too many length or distance symbols".

Yarn, or yarnpkg, is doing something non-deterministic.

### To reproduce

`yarn add node-notifier`

### Environment

```shell
I don't know, while trying to run `yarn add dlx` I got

> error https://registry.yarnpkg.com/node-notifier/-/node-notifier-10.0.1.tgz: Integrity check failed for "node-notifier" (computed integrity doesn't match our records, got "sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg== sha1-2jmj7l5rSw0yVb/vlWAYkK/YBwk=")

(probably related to MITM certs)

But this is in alpine-linux container

/data/app# node --version
v14.19.0

/data/app# yarn --version
1.22.17
```

**Comment by AndrewRayCode** [comment]
Ironically I just got a new error trying this again:

> error An unexpected error occurred: "https://registry.yarnpkg.com/node-notifier/-/node-notifier-10.0.1.tgz: unexpected end of file".

**Comment by arcanis** [comment]
https://yarnpkg.com/getting-started/qa#queries-to-registryyarnpkgcom-return-a-404500-is-it-down

**Comment by AndrewRayCode** [comment]
Makes sense. This also appears to be a network issue with my company's VPN, as I can reproduce it with curl.
