### ISSUE TITLE
[Bug?]: Cannot extend from a module in TypeScript 4.8

### ISSUE THREAD

**Issue by Kurt-von-Laven** [yarnpkg/berry#4927]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

See microsoft/TypeScript#50840 for a description of the issue, which was triaged from there to this repository.

### To reproduce

See ScribeMD/docker-cache#165 for a pull request reproducing the issue.

### Environment

```shell
System:
  OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
  CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Binaries:
  Node: 16.17.1 - /tmp/xfs-6fa176d7/node
  Yarn: 3.2.3 - /tmp/xfs-6fa176d7/yarn
  npm: 8.15.0 - ~/.asdf/plugins/nodejs/shims/npm
```

**Comment by RDIL** [comment]
Please do `yarn set version canary` - the fix hasn't been released just yet.
