### ISSUE TITLE
[Feature] Documentation for the `-2` in `yarn init -2`

### ISSUE THREAD

**Issue by dumbledad** [yarnpkg/berry#4957]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

As a newcomer I rely on the documentation online and the `--help` explanations at the terminal.

The [Getting Started – Installation](https://yarnpkg.com/getting-started/install) guide suggests 
> Just run the following command. It will generate some files inside your current directory; add them all to your next commit, and you'll be done! `yarn init -2`

At the terminal (zsh on an M1 Mac in my case) if I type `yarn init --help` the `-2` flag is not mentioned.

**Describe the solution you'd like**

I would like the help given by `yarn init --help` to cover the `-2` flag recommended in the Getting Started guide

**Comment by arcanis** [comment]
Unfortunately `yarn init --help` is powered by Yarn 1.x (unless you're already in a Yarn Modern repository), so it'd require a change to the 1.x codebase (and the way it handles the `--help` message is pretty bad, iirc).

**Comment by SamB** [comment]
I think you can close this bug: there seems to be help now, and it looks like it comes from this line added in https://github.com/yarnpkg/yarn/commit/f381c5f0ce85a96dc1cba8e4883819ee878c949f:

```javascript
  commander.option('-2', 'generates the project using Yarn 2');
```

(See https://github.com/yarnpkg/berry/issues/4507 for the fact that it's not listed in the web docs.)

**Comment by dumbledad** [comment]
That's great, I'll close this issue.
