### ISSUE TITLE
[Bug]: Yarn changes "bin" for no reason

### ISSUE THREAD

**Issue by leonheess** [yarnpkg/berry#4989]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Running `yarn` in a workspaces mono repo results in yarn changing the package.json of one package from:

```
....
"bin": {
  "cli": "./bin/index.js"
},
....
```

to 

```
....
"bin":  "./bin/index.js",
....
```

which obviously results in the package not working anymore.

### To reproduce

You'll have to setup a workspaces mono repo with multiple packages and one with a bin entry.

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
  Binaries:
    Node: 16.16.0 - ~\AppData\Local\Temp\xfs-6a1ee275\node.CMD
    Yarn: 3.2.4 - ~\AppData\Local\Temp\xfs-6a1ee275\yarn.CMD
    npm: 8.11.0 - ~\AppData\Local\Volta\tools\image\node\16.16.0\npm.CMD
```

**Comment by arcanis** [comment]
Please share a full repro. Yarn should only do this if your package has the same name as the binary, which has the same behavior.

**Comment by leonheess** [comment]
Can this behaviour be disabled?

**Comment by arcanis** [comment]
No

**Comment by leonheess** [comment]
I don't understand. There are so many use cases where the published package name is no longer equivalent to the current development one and this just breaks everything. What a weird feature..

Well, time for pnpm
