### ISSUE TITLE
[Bug?]: PnP swallows Node initialization error

### ISSUE THREAD

**Issue by CarsonF** [yarnpkg/berry#4992]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

There's a NodeJS error thrown (stack below). This is swallowed by PnP loader causing the process to exit 0 without any output.
```
ReferenceError: Cannot access 'Foo' before initialization
    at Object.<anonymous> (<my src file>)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
```
I had to manually step through execution to figure out where this was happening, instead of getting that super helpful error and stack trace.

### To reproduce

My use case was more nuanced using decorators, but this does the same thing:
```js repro
// @ts-ignore
new Foo();
class Foo {}
```

### Environment

```shell
System:
   OS: macOS 12.5.1
   CPU: (10) arm64 Apple M1 Max
Binaries:
  Node: 18.9.0 - /private/var/folders/p7/swvn6htn34q9186mw40c3pr80000gp/T/xfs-8a5a5b19/node
  Yarn: 3.2.4 - /private/var/folders/p7/swvn6htn34q9186mw40c3pr80000gp/T/xfs-8a5a5b19/yarn
  npm: 8.19.1 - /opt/homebrew/bin/npm
```

### Additional context

Here's the `.pnp.cjs` source where it happens. 
```js
  const originalModuleLoad = require$$0.Module._load;
  require$$0.Module._load = function(request, parent, isMain) {

  ...

    let hasThrown = true;
    try {
      module.isLoading = true;
      module.load(modulePath);     // <-- throws
      hasThrown = false;
    } finally {                    // <-- swallowed
      module.isLoading = false; 
      if (hasThrown) {
        delete require$$0.Module._cache[modulePath];
      }
    }
```

**Comment by merceyz** [comment]
I can't reproduce this, `node` throws and exits with status of 1 as expected, here are the steps I used to test:
```sh
docker run --rm -it node:18.9.0 bash
cd $(mktemp -d)
yarn init -2
yarn set version 3.2.4
yarn
tee index.js <<EOF
// @ts-ignore
new Foo();
class Foo {}
EOF
yarn node index.js
```

> Here's the .pnp.cjs source where it happens.

There is no `catch` in that section so it doesn't "swallow" any errors.

**Comment by CarsonF** [comment]
> There is no `catch` in that section so it doesn't "swallow" any errors.

Mmm you're totally right. Let me dig again and see where it bubbles too.

**Comment by CarsonF** [comment]
Yes so I see now that an `uncaughtException` is emitted. And that happens before my bootstrap logic since it was an ESM import.
I'll change it to a dynamic import so it can be logged through a promise rejection. 👍
