### ISSUE TITLE
[Bug?]: fstat results

### ISSUE THREAD

**Issue by levmorozov** [yarnpkg/berry#5007]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I need to get correct mtime (for some postprocessing system to work), but when I use ZipOpenFS.fstatSync - got same incorrect results for every file:
```
{
  "uid": 1000,
  "gid": 1000,
  "size": 16025,
  "blksize": 512,
  "atimeMs": 456789000000,
  "mtimeMs": 456789000000,
  "ctimeMs": 456789000000,
  "birthtimeMs": 456789000000,
  "atime": "1984-06-22T21:50:00.000Z",
  "mtime": "1984-06-22T21:50:00.000Z",
  "ctime": "1984-06-22T21:50:00.000Z",
  "birthtime": "1984-06-22T21:50:00.000Z",
  "dev": 0,
  "ino": 0,
  "mode": 33188,
  "nlink": 1,
  "rdev": 0,
  "blocks": 32,
  "crc": 1761295080
}
```

### To reproduce

`zipFs.fstatSync(zipFs.openSync(pnpApi.resolveToUnqualified(file, './')));`

### Environment

```shell
System:
    OS: Linux 5.19 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (1) x64 AMD Ryzen 5 2600 Six-Core Processor
  Binaries:
    Node: 18.12.0 - /tmp/xfs-7ba283a6/node
    Yarn: 3.2.4 - /tmp/xfs-7ba283a6/yarn
    npm: 8.19.2 - /usr/bin/npm
```

**Comment by arcanis** [comment]
Yarn normalizes the mtime of all packages to ensure consistency and reproducible package generation.

**Comment by levmorozov** [comment]
I not sure how different mtimes can break consistency, but this info exist before (can check mtime in node_modules for any file) and it is not exist now (when using pnp). Is there any way around this normalizing?
