### ISSUE TITLE
[Feature] Minify Yarn file when installing to project

### ISSUE THREAD

**Issue by accidentaldeveloper** [yarnpkg/berry#505]
- [x] I'd be willing to implement this feature (I think)
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

When I embed yarn in a project (by running `yarn set version berry`) it adds a 7.3 MB unminified Javascript file. This is a substantial amount of weight added to a project.

**Describe the solution you'd like**

The installed file is minified/uglified. By running this optimization on the file before (or after) downloading it, the file size can be cut in half. I tested this using `terser` with the `--mangle` flag. The original file was 7.3 MB. The resulting file is 3.6 MB.

We are already doing this manually in one of our projects and have not encountered any issues.

**Describe the drawbacks of your solution**

It may be more difficult to debug the minified version. 

**Describe alternatives you've considered**

This could also be an optional behavior, perhaps behind a command line flag.

**Comment by arcanis** [comment]
Yep, that sounds reasonable, let's add that to the Webpack builder!

Note that if we do this I'd however prefer to also add a flag to allowing disabling it, + forwarding this flag from `yarn set version from sources` up to the builder. This way if someone wants to debug Yarn, they'll just have to use this one command to rebuild it from sources without minification:

```
yarn set version from sources --no-minify
```

**Comment by arcanis** [comment]
Implemented in #536 🎉

**Comment by accidentaldeveloper** [comment]
@arcanis , thank you for taking care of this! I wanted to contribute a PR but just haven't had the time.
