### ISSUE TITLE
[Bug?]: Yarn warns about peer dependency version even if correctly met

### ISSUE THREAD

**Issue by spacedawwwg** [yarnpkg/berry#5050]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

`X provides cypress (p72c63) with version 11.0.1, which doesn't satisfy what cypress-grep requests`

Upon running `yarn explain peer-requirements p72c63` I get `cypress-grep@npm:3.0.3 [f75f6] → ^10.0.0 ✘`

`11.0.1` meets the requirement of `^10.0.0` (i.e. 10 or greater)

### To reproduce

1. `yarn add cypress and cypress-grep` 
2. `yarn install`

### Environment

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.18.1 - /private/var/folders/f5/00y5m0ls4_jd339321ttnjmh0000gn/T/xfs-9791b370/node
    Yarn: 3.1.1 - /private/var/folders/f5/00y5m0ls4_jd339321ttnjmh0000gn/T/xfs-9791b370/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
```

**Comment by merceyz** [comment]
> 11.0.1 meets the requirement of ^10.0.0 (i.e. 10 or greater)

It doesn't, that's not what `^` means, see https://github.com/npm/node-semver/tree/3b3de4f8263c9ba76f549c5d20fcc4e420958a5d#caret-ranges-123-025-004
