### ISSUE TITLE
[Bug]: Webpack 5 - Can't resolve any package and missing __virtual__ folder

### ISSUE THREAD

**Issue by simkessy** [yarnpkg/berry#5068]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I have a workspace setup and upgrade from yarn 1 to yarn 3 
My .yarnrc.yml is very basic: 

```
npmRegistryServer: "https://artifacts-prod-use1.company.com/artifactory/api/npm/node-npm-yarn-prod-virtual"
yarnPath: .yarn/releases/yarn-3.2.3.cjs
```

Now, without changing any of my webpack configuration, when I run webpack I get multiple errors for exmaple:

 `Can't resolve 'react' in '/home/me/code/monorepo/.yarn/__virtual__/@apollo-client-virtual-fd322e2457/0/cache/@apollo-client-npm-3.7.1-a80032e019-95bb1f226f.zip/node_modules/@apollo/client/react/hooks'`

When I look at `.yarn/` in my monorepo there is no `__virtual__` folder: 
<img width="307" alt="image" src="https://user-images.githubusercontent.com/5871660/202210759-604d509d-8aa0-4166-a008-ebfcb0d5dd77.png">

### To reproduce

.

### Environment

```shell
.
```

**Comment by merceyz** [comment]
> .

That's not a reproduction, please provide one.

> When I look at .yarn/ in my monorepo there is no __virtual__ folder:

The `__virtual__` folder is, as the name implies, virtual and doesn't exist on disk. https://yarnpkg.com/advanced/lexicon/#virtual-package

**Comment by simkessy** [comment]
If they're virtual how does webpack resolve them?  Do I need to change anything in webpack for it to find packaged?
