### ISSUE TITLE
[Bug?]: Tempo trace duration incorrectly divided by 1,000,000

### ISSUE THREAD

**Issue by JavaPerformance** [yarnpkg/berry#5071]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

In Explore Tempo the Duration of the trace displayed in the table is 1 million times shorter than it should be.

![image](https://user-images.githubusercontent.com/103591141/202420636-480cf212-ba26-48e3-a1a0-ad8dd7dfefd8.png)

### To reproduce

Run with the stack defined below.

### Environment

```shell
System IBM z15 zOS 2.5 + zCX

Tempo latest (11/16/22)
Grafana 9.3.0-beta1
```

**Comment by merceyz** [comment]
I think you opened this in the wrong repository, this doesn't seem related to Yarn.

**Comment by JavaPerformance** [comment]
@merceyz Yeah....  I suck :)
