### ISSUE TITLE
[Docs] Installation instructions with corepack don't work

### ISSUE THREAD

**Issue by cseas** [yarnpkg/berry#5075]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

I'm trying to install Yarn for a project on MacOS. Followed the instructions in the [Installation][1] page.

- Ran `corepack enable`
- Since I have Node < 16.17, noted latest Yarn release and ran `corepack prepare yarn@<3.3.0> --activate`

I get the error: `no such file or directory: 3.3.0`

The installation page mentions nothing after this step. Am I missing something?

I've never needed to deal with corepack to install Yarn the past few years, why is this recommended now? 
Is there something wrong in installing Yarn with `npm -g`?

[1]: https://yarnpkg.com/getting-started/install

### To reproduce

<img width="587" alt="Screenshot 2022-11-19 at 5 44 51 PM" src="https://user-images.githubusercontent.com/29686866/202850450-aa65a283-8d8c-454e-95d8-83df02539794.png">

### Environment

```shell
Node: v16.14.2
npm: 8.5.0
```

**Comment by merceyz** [comment]
Try running
```sh
corepack prepare yarn@3.3.0 --activate
```

> I've never needed to deal with corepack to install Yarn the past few years, why is this recommended now?
Is there something wrong in installing Yarn with npm -g?

https://nodejs.org/dist/latest-v18.x/docs/api/corepack.html#corepack

**Comment by cseas** [comment]
Ah, my bad. Removing the angular brackets worked. Thanks.

> https://nodejs.org/dist/latest-v18.x/docs/api/corepack.html#corepack

There's a big red banner warning it's experimental so I still don't see the point of changing the installation method officially. But anything's fine as long as it works I guess.
