### ISSUE TITLE
[Bug]: in `v3.3.0` - `.bin` executables not found w/ `nodeLinker: node-modules`

### ISSUE THREAD

**Issue by o-alexandrov** [yarnpkg/berry#5084]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Yarn doesn't find executables from `.bin` w/ `nodeLinker: node-modules`

### To reproduce

1. Clone [this repo](https://github.com/o-alexandrov/yarn-bug-node-modules)
2. Install deps `yarn`
3. Run `yarn bin tsx`

Yarn doesn't find `tsx`, even though `tsx` is at `node_modules/.bin/tsx`

### Environment

```shell
System:
  OS: macOS 13.0
  CPU: (10) arm64 Apple M1 Pro
Binaries:
  Node: 19.0.1 - /private/var/folders/g9/z1czk9t57xngdyn1_yhbgsxr0000gn/T/xfs-d9f8aee5/node
  Yarn: 3.3.0 - /private/var/folders/g9/z1czk9t57xngdyn1_yhbgsxr0000gn/T/xfs-d9f8aee5/yarn
  npm: 8.19.2 - /opt/homebrew/bin/npm
```

**Comment by o-alexandrov** [comment]
While I strongly disagree with the design, let me please ask: are there any workarounds?
- calling the executable directly `node_modules/.bin/executable` is not a workaround as the dependencies might need to invoke CLI commands, so it’d be error-prone patching for yarn DX and need to involve all packages to adhere to yarn which is not feasible

Let’s say we have:
- a common config package with common configs and tools

Based on the yarn v2+ design:
- do we need to define the dependencies multiple times in every package.json?
- do you consider to let a user to have a flag to switch to `npm` or `pnpm` resolution? (they both work fine)

**Comment by arcanis** [comment]
As for your use case, the documentation may give you some ideas: https://yarnpkg.com/getting-started/qa/#how-to-share-scripts-between-workspaces

**Comment by o-alexandrov** [comment]
The documentation points to a yarn-only way that would be hard to understand for anyone looking at such DX for the first time.
- actual script (CLI cmd) would be hidden in another repo’s package.json

For this case, probably a more rational approach is:
- to stay w/ Yarn V1, or either npm/pnpm
- and hope for the `bun`’s success as a pkg manager, when deciding to upgrade from Yarn V1
