### ISSUE TITLE
[Bug] Interception of fs doesn't pass options to readdirSync

### ISSUE THREAD

**Issue by georgelee1** [yarnpkg/berry#509]
**Describe the bug**

Hi,

Getting the following error when using `fs.readdirSync("./", { withFileTypes: true })` in one of our build scripts that is called from a yarn script.

```
../myScript.js:29
      file.isDirectory() &&
                 ^

TypeError: file.isDirectory is not a function
    at ../myScript:29:18
    at Array.filter (<anonymous>)
    at Object.<anonymous> (../myScript:26:4)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.module_1.default._load (../myScript.pnp.js:15332:20)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
```

I can see that you have a bunch of different virtual file systems (https://github.com/yarnpkg/berry/tree/master/packages/yarnpkg-fslib/sources) and it appears that none of them actually handle the options object being passed.

I was going to have a got at a PR but I wasn't sure if it is expected that script calls (like the one below in my example) should inherit the yarnpkg-fslib.

**To Reproduce**

*package.json*
```
{
  "name": "test",
  "version": "1.0.0",
  "devDependencies": {
  },
  "scripts": {
    "someWork": "node myScript.js"
  }
}
```

*myScript.js*
```
const fs = require('fs');

fs
  .readdirSync("./", { withFileTypes: true })
  .forEach(file => {
	if (file.isDirectory()) {
		console.info(`[DIR] ${file.name}`);
	} else {
		console.info(`[FILE] ${file.name}`);
	}
  })

```

*command line*
`yarn someWork`

**Environment**

 - OS: Windows (WSL)
 - Node version [v12.10.0]
 - Yarn version [2.0.0-rc.6.]

**Comment by arcanis** [comment]
Good spot, I wasn't aware of this option!

Fwiw we use the fslib layer to allow Node to access dependencies from the zip files, so yep it's expected. Wanna open try to PR it? 😀

Also feel free to pop on our Discord server if you have any questions about how to navigate and contribute to the codebase!

**Comment by rista404** [comment]
@arcanis if it's okay I can take a stab at this! From what I've seen it's just adding a second argument ([opts](https://nodejs.org/api/fs.html#fs_fs_readdirsync_path_options)) to `readDirSync` method in all of the `*FS` files?

**Comment by arcanis** [comment]
Go for it! 😃 Yeah, it should be mostly it. In order to test, don't forget to regenerate the hook:

```
// ... make changes ...
$ yarn build:cli+hook
$ yarn install
$ yarn node ./test-script.js
```

**Comment by arcanis** [comment]
Did you get a chance to look, @rista404? Is there something I can do to help?
