### ISSUE TITLE
[Bug?]: Mixing pnp / node-modules and hoisting doesn't work

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [yarnpkg/berry#5101]
### Describe the bug

This is difficult to search for. so I'm not sure if it's been raised / solved already let me know and I'll close this ASAP :)

**The situation:**

I have one workspace in my monorepo that just needs to behave normally. That means no hoisting, and node_modules.

All other packages work with the PNP treatment and can be hoisted to the root.

**The setup**

In the root I set pnp, and the default hoisting
```
/.yarnrc.yml

nodeLinker: 'pnp'
nmHoistingLimits: 'none'
```

I have to do 2 overrides now in `/workspaces/package-a`:

1. Switch the nodeLinker to node-modules

```
/workspaces/package-a/yarnrc.yml

nodeLinker: 'node-modules'
```

2. Switch the hoisting setting, which according to the docs should be done in package.json

```
/workspaces/package-a/package.json

"installConfig": {
    "hoistingLimits": "workspaces"
},
```

**Expected Result**
The root should only have `.yarn/cache` as all the remaining packages would follow the normal pnp protocol.

/workspaces/package-a/node_modules should exist and contain all packages

**Actual Result**
The workspace speciic overrides are ignored completelt.

**Key point**
This only happens when mixing nodeLinker types, if I set the root directory to `node-modules` the hoisting works fine.

### To reproduce

Use the structure in this sandbox:

https://codesandbox.io/s/romantic-black-j3ohir?file=/package.json

### Environment

```shell
Yarn 3.3.0
Node v16
Windows
```

**Comment by TheRealFlyingCoder** [comment]
Bumping this, any one care to chime in?

**Comment by arcanis** [comment]
As mentioned in Discord, the settings defined in the yarnrc files follow the typical behavior of rc files: Yarn will read the one from the current folder, then its parent folder, then ... etc. In other words, what you're trying to do (setting different settings to different workspaces) isn't possible.

However, the documentation suggests an alternative: https://yarnpkg.com/getting-started/recipes/#hybrid-pnp--node_modules-mono-repo
