### ISSUE TITLE
[Bug?]: Resolutions with @ or * symbols are automatically removed

### ISSUE THREAD

**Issue by jmrossy** [yarnpkg/berry#5103]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

Resolutions for packages under an organization scope (e.g. `@myorg/mypackage`) and resolutions for nested dependencies (e.g. `p1/**/p2`) get automatically removed when running yarn install.

### To reproduce

```
"resolutions": {
    "@ethersproject": "^5.7"
  }
```

### Environment

```shell
System:
    OS: macOS 12.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  Binaries:
    Node: 16.17.1 - /private/var/folders/zp/scyq8ks52wxgs8tt_yqvsqkr0000gn/T/xfs-accc7987/node
    Yarn: 3.2.0 - /private/var/folders/zp/scyq8ks52wxgs8tt_yqvsqkr0000gn/T/xfs-accc7987/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
```

### Additional context

Tested in a repo using a yarn workspace. Unsure if that's relevant in this case.

**Comment by arcanis** [comment]
They are syntax errors and ignored, the warning isn't properly surfaced. This is fixed in master.

**Comment by jmrossy** [comment]
@arcanis Thanks for the response. Are resolutions for packages under organizations and/or nested resolutions still supported?

**Comment by cholazzzb** [comment]
This happens in my project, any updated info if the nested resolutions still supported? @jmrossy @arcanis

**Comment by coler-j** [comment]
The `/**` syntax is definitely a bug
