### ISSUE TITLE
Usage Error: Couldn't find a script named "autoclean".

### ISSUE THREAD

**Issue by DianaKoenraadt** [yarnpkg/berry#5107]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Docs say that I should be able to run `yarn autoclean` but I get the error "Usage Error: Couldn't find a script named "autoclean"."

### To reproduce

Try to run `yarn autoclean`

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1240 v5 @ 3.50GHz
  Binaries:
    Node: 16.17.0 - ~\AppData\Local\Temp\xfs-d5bf1fd0\node.CMD
    Yarn: 3.2.0 - ~\AppData\Local\Temp\xfs-d5bf1fd0\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    jest: ^29.3.1 => 29.3.1
```

**Comment by arcanis** [comment]
Autoclean was removed a couple years ago; the website you reference is probably the old one, for 1.x only.

**Comment by jurosh** [comment]
Is there alternative in Berry ?

**Comment by andrey-nunez-smartassets** [comment]
also fishing for an alternative 😓
