### ISSUE TITLE
(🎁) Make berry the default version

### ISSUE THREAD

**Issue by KotlinIsland** [yarnpkg/berry#5119]
- [🚀] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [🚀] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

A clear and concise description of what workflow is meant to be improved.
Example: "As a developer, I often want to do \<something>, but I often face \<problem>".

"As a developer, I often want to do \<use non deprecated versions of tools>, but I often face \<`yarn set version berry`>"

**Describe the solution you'd like**

A clear and concise description of what you want to happen. Consider that Yarn is used
by many people, and your particular use case might not make sense to implement in the core.

Make berry the default version.

**Describe the drawbacks of your solution**

This section is important not only to identify future issues, but also for us to see whether
you thought through your request. When filling it, ask yourself what are the problems we could
have maintaining what you propose. How often will it break?

Skeletons(💀) and ghosts(👻) (maybe dinosaurs(🦕) too) will have to execute `yarn set version 1`

**Describe alternatives you've considered**

A clear and concise description of any alternative solutions or features you've considered,
and why you think they wouldn't be good enough. Start by: why not make it a plugin?

Why not make it a plugin? Because then you would have to set the version to berry just to install a plugin that sets the version to berry, sounds a little backwards I think.

**Comment by arcanis** [comment]
We don't have a lot to gain from this, and a lot to lose. As far as we know many things still rely on Yarn 1 being the global, if only because of the different CLI commands and options, so we'd risk breaking many CIs.

**Comment by KotlinIsland** [comment]
@arcanis I understand what you mean, but it seems a little silly to never update anything due to backwards incompatible changes. and I personally have found the UX for newcomers(me) to be extremely confusing.

What about this proposal, when yarn 4 is released, a warning is shown on installs of all versions of yarn:
```
👉 npm install yarn

Warning: The default version of yarn ('@latest') which is currently set to the 'classic' distribution (currently v1.22.19)
has reached end of life and will be updated to the latest release (currently v4.0.0) at a future date.

If you are intending to use the current version of yarn you should execute `yarn set version stable`

added 1 package in 6s
```  

### And a prominent warning be added to the top of the npm readme:
![image](https://user-images.githubusercontent.com/65446343/206387175-d88815c7-95de-498a-b180-186cfc735f98.png)

This warning could be present for as long as is needed to ensure all existing projects that are trapped on v1 can update their ci to use `npm install yarn@1`

Also, why aren't Yarn 3/4 published on npm under `yarn`? I find that very confusing.

**Comment by donhatch** [comment]
@KotlinIsland suggested, as part of warning on install:

> If you are intending to use the current version of yarn you should execute `yarn set version stable`

As I said recently over in https://github.com/yarnpkg/berry/issues/5123#issuecomment-4310963467 , the fact that `yarn set version stable` switches from classic to berry, while `yarn set version latest` doesn't, seems pretty surprising/weird in multiple ways, and hopefully we'll be able to eventually get out of this weirdness somehow.   So this proposed message recommending `yarn set version stable` as the way to switch to berry doesn't seem like such a great idea to me, since it would further entrench this surprising/weird behavior.   How about recommending `yarn set version berry` (which also works) as the way to switch to berry, instead.

**Comment by arcanis** [comment]
My general plan is to finally deprecate Yarn Classic once [6.x](https://yarn6.netlify.app/blog/2026-01-28-yarn-6-preview/) (currently only a preview) becomes stable, hopefully later this year.
