### ISSUE TITLE
[Bug?]: current behavior of --tolerate-republish

### ISSUE THREAD

**Issue by blephy** [yarnpkg/berry#5120]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Hi,

This is not a bug, but actually i found the documentation for `--tolerate-republish` a bit confusing:

> Warn and exit when republishing an already existing version of a package.

So yarn is warning and exiting when we pass this option or when we do not pass this option ?

### To reproduce

nothing to reproduce

### Environment

```shell
System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.11.0 - /private/var/folders/1f/d9r35kjs4l1bx93x8h1f35100000gp/T/xfs-fd2e8e7c/node
    Yarn: 3.3.0 - /private/var/folders/1f/d9r35kjs4l1bx93x8h1f35100000gp/T/xfs-fd2e8e7c/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.11.0/bin/npm
  npmPackages:
    jest: ^28.1.3 => 28.1.3
```

**Comment by arcanis** [comment]
Hm the documentation is misleading indeed. By default Yarn will report an error if publishing an existing version. If `--tolerate-republish` is set, Yarn will swallow the error and just skips the package publishing.

**Comment by blephy** [comment]
@arcanis thanks for that precision.
