### ISSUE TITLE
[Bug?]: yarn berry not installing packages from private nexus

### ISSUE THREAD

**Issue by WoodenPC** [yarnpkg/berry#5137]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Hi. I have problem with `yarn berry`, cannot install packages from private nexus registry although `Yarn v1.22.19` working perfectly with nexus . In `yarnrc.yml` i specified registry url. `yarn npm login` just stucks without reaction. 

### To reproduce

-

### Environment

```shell
windows 10, node 16.18.0, yarn 3.3.0
```

**Comment by arcanis** [comment]
There isn't enough information for us to do anything - and we don't have access to Nexus servers, so we can't do investigation on our side.
