### ISSUE TITLE
Yarn Start - Usage Error: Couldn't find a script named "start".

### ISSUE THREAD

**Issue by elthombre** [yarnpkg/berry#5161]
Installed yarn via corepack instructions. Version 3.2.2 running.

In my project, ran: yarn install, successfully. Attempted to run: yarn start, and it failed with the exception as noted.

**Comment by ruffledev** [comment]
Anyone get a resolve for this?
Receiving same error when attempting `yarn deploy network --truffle`
Same installation method but v3.3.1

`yarn deploy --network truffle
Usage Error: Couldn't find a script named "deploy".`

**Comment by jalepenos** [comment]
I have the same issue with yarn dev and yarn build !!!!!!!
