### ISSUE TITLE
[Bug?]: `yarn workspace` invokes the wrong executable

### ISSUE THREAD

**Issue by timbicker** [yarnpkg/berry#5192]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Inside a mono repo with two workspaces, when I install two different versions of a package that has an executable in `.bin` (like jest for example), `yarn workspace` will fail to invoke the right one.

Given two package.json
`pkg-a/package.json`
```
{
  "name": "pkg-a",
  ...
  "devDependencies": {
    "jest": "^26"
  }
}
```

`pkg-b/package.json`
```
{
  "name": "pkg-b",
  ...
  "devDependencies": {
    "jest": "^29"
  }
}
```

- `yarn install`
- `yarn workspace pgk-a jest --version` -> outputs `26.6.3` as expected
- `yarn workspace pkg-b jest --version` -> outputs `26.6.3` as well, **but exptected** is `29.3.1`

### To reproduce

To reproduce, I provided a very small repository https://github.com/timbicker/yarn-workspace-bug/tree/main

- `git clone git@github.com:timbicker/yarn-workspace-bug.git`
- `yarn install`
- `yarn workspace pgk-a jest --version` -> outputs `26.6.3` as expected
- `yarn workspace pkg-b jest --version` -> outputs `26.6.3` as well, but exptected is `29.3.1`

### Environment

```shell
yarn version: 1.22.19
```

**Comment by merceyz** [comment]
> yarn version: 1.22.19

Wrong repo, should have been submitted to https://github.com/yarnpkg/yarn but either way this isn't a Yarn bug, see https://github.com/yarnpkg/berry/issues/2960#issuecomment-851073460

**Comment by timbicker** [comment]
@merceyz my bad! Thanks for pointing this out
