### ISSUE TITLE
[Bug?]: Yarn version 3 disappeared/inaccessible

### ISSUE THREAD

**Issue by yousifalraheem** [yarnpkg/berry#5198]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Yesterday I was working on upgrading yarn to version 3 (stable) in our project. I followed the instructions [here](https://yarnpkg.com/getting-started/install). I came today to see that version 3 has [disappeared from npm](https://www.npmjs.com/package/yarn?activeTab=versions).

You can try this as well:
```
npm view yarn versions
```

```log
Resolving stable to a url...
error An unexpected error occurred: "Release not found: stable".
info If you think this is a bug, please open a bug report with the information provided in "[path-hidden]".
info Visit https://yarnpkg.com/en/docs/cli/policies for documentation about this command.
```

### To reproduce

Try any of the following to see the error

```cmd
yarn set version stable
```

```cmd
yarn set version 3.3.0
```

```cmd
npm install yarn@3.3.0 -g
```

### Environment

```shell
System:
  OS: macOS 13.1
  CPU: (10) arm64 Apple M1 Max
Binaries:
  Node: 16.18.1 - /var/folders/th/7s0jhg593_98cqv8rclw8td40000gq/T/yarn--1673605703778-0.48935486604405765/node
  Yarn: 1.22.1 - /var/folders/th/7s0jhg593_98cqv8rclw8td40000gq/T/yarn--1673605703778-0.48935486604405765/yarn
  npm: 9.3.0 - ~/.nvm/versions/node/v16.18.1/bin/npm
```

### Additional context

Yarn version 3 was accessible just yesterday

**Comment by trivikr** [comment]
Yarn 2+ versions are managed through `corepack` and are not published on npm.

https://yarnpkg.com/getting-started/install

**Comment by heyheyhello** [comment]
It is a bit confusing but when you install `npm install yarn` you get `1.22.19` which is latest - then you instruct Yarn to use v2 or v3 via `yarn set version` or via `.yarnrc.yml`'s `yarnPath` variable.

There shouldn't be a v3 on npm. It was misleading and it's kind of a bugfix that it's now gone.
