### ISSUE TITLE
Yarn v3 migration error: cannot find script grpc_node_tools_protoc

### ISSUE THREAD

**Issue by zondervancalvez** [yarnpkg/berry#5215]
We are trying to migrate [Hyperledger Cactus](https://github.com/hyperledger/cactus/blob/main/BUILD.md) from yarn v1 to yarn v3 (3.3.0). During migration using these steps [here](https://yarnpkg.com/getting-started/migration), we encountered issues. Node version used: 16.14.2

issues encountered:
![bVgHt](https://user-images.githubusercontent.com/69126996/215973414-3f997a14-d6c3-4bc3-8228-c23df5720815.png)

Ways to replicate issue: After building cactus project and updating the yarn version we updated some scripts: Updated the script `codegen` on the cactus/packages/cactus-core-api/package.json to `codegen`: `yarn run codegen:openapi && yarn run codegen:proto`, and updated the cactus/package.json configure command with `configure`: `yarn install --immutable && yarn run build:dev:backend`.

We run the `command yarn run configure` to replicate the errors

PS: We also posted this in [stackoverflow](https://stackoverflow.com/questions/74896751/yarn-v3-migration-error-cannot-find-script-grpc-node-tools-protoc)

**Comment by merceyz** [comment]
Please don't ignore the issue template, it exists for a reason.

> Usage Error: Couldn't find a script named "grpc_tools_node_protoc".

This is because the `./packages/cactus-core-api` workspace doesn't have a binary nor script available with that name, seems its missing a dependency on `grpc-tools`.
