### ISSUE TITLE
[Feature] ESLint SDK should export `eslint/use-at-you-own-risk`

### ISSUE THREAD

**Issue by clemyan** [yarnpkg/berry#5231]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

Currently, the `eslint` SDK only exposes the `lib/api.js` main entrypoint. But, since v8, [exposes `eslint/use-at-your-own-risk`](https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1544) using the `exports` field of `package.json`.

Editor integrations may need the API exposed via `use-at-your-own-risk`. In particular, `vscode-eslint` now supports the experimental flat config format, but the [required APIs are only exposed via `use-at-your-own-risk`](https://eslint.org/blog/2022/08/new-config-system-part-3/#using-flat-config-with-the-eslint-class) (with the expectation that they will be moved to the main entrypoint once the API stabilizes).

**Describe the solution you'd like**

The ESLint SDK should also add the `exports` field to the SDK `package.json`, and add the wrapper file `lib/unsupported-api.js`. This mimics the behavior of the `eslint` package.

**Describe the drawbacks of your solution**

If a project uses eslint v7 or before, then there is no `eslint/use-at-you-own-risk` and the current SDK should be used. So we need to add a version check to determine which SDK to generate which adds complexity to `@yarnpkg/sdks`.

**Describe alternatives you've considered**

1. Manually edit the SDK. Not maintainable as those edits are wiped when regenerating the SDK,
2. Wait until the ESLint flat config feature stabilizes before using it. Could work in this case but I think it is not inconceivable that some another integration feature needs the `eslint/use-at-you-own-risk` APIs. I think there is value in adding them to the SDK.

**Comment by clemyan** [comment]
> If a project uses eslint v7 or before, then there is no eslint/use-at-you-own-risk and the current SDK should be used. So we need to add a version check to determine which SDK to generate which adds complexity to @yarnpkg/sdks.

New idea:

We can actually infer which files should be in the SDK by reading the manifest. Specifically, the SDK should include all files referenced in the `main`, `bin`, and `exports` fields.

Actually, this applies to most of the SDKs. But

1. Most SDKs currently only include the `bin` in the SDKs. Should we also include the `main` entrypoints for those?
2. The prettier SDK only includes the `main` entrypoint but as a binary, whereas the `bin` is not included. Is there a reason for that?
3. The typescript SDK cannot use this strategy due to the money patch.

**Comment by raphael-theriault-swi** [comment]
Any updates on this ?
