### ISSUE TITLE
match: protocol to lock versions

### ISSUE THREAD

**Issue by penx** [yarnpkg/berry#5235]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

As a developer, I often want to do ensure a set of packages are always locked to the same version, but I often face developers updating packages manually or dependabot updates making package versions out of sync.

**Describe the solution you'd like**

A new protocol, `match:` or `match-version:` used as:

```json
"dependencies": {
  "@remix-run/node": "1.0.0"
},
"devDependencies": {
  "@remix-run/dev": "match:^@remix-run/node",
  "@storybook/react": "2.0.0",
  "@storybook/some-plugin": "match:@storybook/react"
}
```

**Describe the drawbacks of your solution**

- If there are multiple instances or no instances of the package you are trying to match.

**Describe alternatives you've considered**

*Why not make it a plugin?*

Perhaps a plugin would be the best route here? I don't know enough to make this judgement, or how to make proposals for plugins

*Use dependabot to sync versions*

- https://github.com/dependabot/dependabot-core/issues/1296

**Comment by arcanis** [comment]
You'd typically use constraints for that. They are a little unwieldy at the moment (you have to write them in prolog), but the next major adds JS support for them.

**Comment by penx** [comment]
Great, will close, thanks for letting me know about constraints!
