### ISSUE TITLE
[Bug?]: Internal Error: This tool can only be used with projects using Yarn Plug'n'Play

### ISSUE THREAD

**Issue by loynoir** [yarnpkg/berry#5238]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Internal Error: This tool can only be used with projects using Yarn Plug'n'Play

### actual
```sh
$ yarn init -2 -w
$ yarn dlx @yarnpkg/sdks vscode
Internal Error: This tool can only be used with projects using Yarn Plug'n'Play
...
```

### expected
```
$ yarn init -2 -w
$ yarn add -D @yarnpkg/sdks
$ yarn sdks vscode
```

### Environment

```shell
corepack prepare yarn@3.4.1 --activate
```

### Additional context

https://yarnpkg.com/getting-started/editor-sdks#vscode

**Comment by arcanis** [comment]
You forgot to run `yarn install`.

**Comment by SameOldNick** [comment]
In case someone else comes this problem...

Removing this line from `.yarnrc.yml' fixed it for me:

```yml
nodeLinker: node-modules
```

This line disables PnP. You may have to run `yarn install` again and make sure to delete the `node_modules` folder.

**Comment by fulldecent** [comment]
This is still broken.

Further workarounds are documented here: https://dev.to/javien/how-to-use-prettier-plugin-with-yarn-pnp-in-vscode-4pf8

---

And if you are using this technique to edit a GitHub Pages website, here is a template with instructions that implements all that for you: https://github.com/fulldecent/github-pages-template
