### ISSUE TITLE
[Bug?]: Caret specification not respected in lockfile

### ISSUE THREAD

**Issue by GuillaumeDesforges** [yarnpkg/berry#5248]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

Yarn seems to output a lockfile where a dependency version `^2.0.4` is associated to a package with a version `3.0.1`

https://github.com/marp-team/marp-cli/blob/9e0eff5f9d9530577458e93769cd2b0000958a7d/yarn.lock#L6605-L6608

However in the docs it says that caret "allows changes that do not modify the left-most non-zero element in the [major, minor, patch] tuple" ([ref](https://github.com/npm/node-semver#caret-ranges-123-025-004))

So `^2.0.4` should not resolve to `3.0.1`

### To reproduce

- clone https://github.com/marp-team/marp-cli
- checkout 9e0eff5f9d9530577458e93769cd2b0000958a7d
- delete `yarn.lock`
- run `yarn lock`
- find the entry for `pug-runtime`

### Environment

```shell
System:
  OS: Linux 5.15 NixOS 23.05 (Stoat) 23.05 (Stoat)
  CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
Binaries:
  Node: 18.14.0 - /tmp/yarn--1675691021371-0.3026760533180006/node
  Yarn: 1.22.19 - /tmp/yarn--1675691021371-0.3026760533180006/yarn
```

**Comment by arcanis** [comment]
You have a `resolutions` entry forcing `pug` to `3.0.2`, regardless of the original range:
https://github.com/marp-team/marp-cli/blob/main/package.json#L164
