### ISSUE TITLE
[Bug]: Yarn v3.4.1 does not parse escaped single quotes in package.json scripts correctly

### ISSUE THREAD

**Issue by dipack95** [yarnpkg/berry#5249]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

As the title says, Yarn v3.4.1 (basically any version past 3.0.1) fails to properly parse any escaped single-quotes in the package.json scripts. The error message is displayed below:

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/6241211/217097732-9589906a-ca52-4a55-a7b4-be97a1737b8b.png">

### To reproduce

Create a new repository with `yarn init -2`

#### `package.json` 
```javascript
{
    "name": "yarn-v3-parsing-bug",
    "packageManager": "yarn@3.4.1",
    "private": true,
    "main": "src/index.js",
    "scripts": {
        "start": "yarn node src/index.js",
        "fault": "bash -c 'ARG_ONE=${ARG_ONE:=nothing} ARG_TWO=\"$(pwd)/src/index.js\" ARG_THREE=\\'SHOULD BE FINE\\' node src/index.js'"
    }
}
```

#### `src/index.js`
```js
(async () => {
    console.log('Hello world!');
})();
```

### Environment

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 14.17.3 - /private/var/folders/3k/bpk8qfwx497g73l_8blq0qg80000gn/T/xfs-23cbd7f0/node
    Yarn: 3.4.1 - /private/var/folders/3k/bpk8qfwx497g73l_8blq0qg80000gn/T/xfs-23cbd7f0/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
```

**Comment by arcanis** [comment]
It now parses the quotes just like bash, for compatibility with existing scripts. See https://github.com/yarnpkg/berry/pull/3661.
