### ISSUE TITLE
[Bug]: yarn workspaces foreach run intermittently fails on GitHub CI

### ISSUE THREAD

**Issue by trivikr** [yarnpkg/berry#5272]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Yarn `workspaces foreach run` intermittently fails on GitHub CI ~~if a workspace script explicitly runs `exit 0`~~

```console
➤ YN0000: The command failed for workspaces that are depended upon by other workspaces; can't satisfy the dependency graph
```

This issue was noticed in https://github.com/trivikr/vitest-codemod/issues/129
While debugging, I ~~realized~~ thought it happens because I have some redundant scripts which return `exit 0`

~~Looks like workspace foreach command throws error on experiencing `exit 0`~~

### To reproduce

I can't create a minimal repro, as this failure is intermittent and only experienced on GitHub CI.

### Environment

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.13.0 - /private/var/folders/42/54jl1_3x4hz06cf7bc_kzd4h0000gn/T/xfs-7c958349/node
    Yarn: 3.4.1 - /private/var/folders/42/54jl1_3x4hz06cf7bc_kzd4h0000gn/T/xfs-7c958349/yarn
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/7016_1676302283730/bin/npm
```

**Comment by trivikr** [comment]
Update the title and description, as removing `exit 0` from scripts did not fix the issue.
The issue is still happening on GitHub CI intermittently, so any suggestion would be helpful.

**Comment by arcanis** [comment]
According to the logs, your test process failed:

```
➤ YN0000: [@vitest-codemod/jest]: Process exited (exit code 1), completed in 7s 282ms
```

I'd imagine the problem comes from vitest, not Yarn - I don't see why it'd dream an exit code (note that exit code 1 may also mean the process was killed by a signal; it's possible Vitest uses so much memory that the OS kills it).

**Comment by trivikr** [comment]
> I'd imagine the problem comes from vitest

> it's possible Vitest uses so much memory that the OS kills it

How do I get a stack trace to find details on the issue?

**Comment by trivikr** [comment]
I was wondering if yarn can throw an error like follows:
```console
The command `$commandName` failed for workspace `$workspaceName` with exit code `$exitCode`
```

But this information is already accessible from logs: the process tells what the error was, and yarn tells it can't continue because of the error.
```console
➤ YN0000: [@vitest-codemod/jest]: Process exited (exit code 1), completed in 7s 282ms
➤ YN0000: The command failed for workspaces that are depended upon by other workspaces; can't satisfy the dependency graph
➤ YN0000: Failed with errors in 7s 291ms
```

**Comment by trivikr** [comment]
No action needed in yarn.

If you think the error thrown by yarn can be improved, do create a [feature request](https://github.com/yarnpkg/berry/issues/new?assignees=&labels=enhancement&template=feature-request.md&title=%5BFeature%5D).
