### ISSUE TITLE
[Bug?]: yarn postinstall script doesn't execute

### ISSUE THREAD

**Issue by oceandrama** [yarnpkg/berry#5276]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

As [mentioned](https://yarnpkg.com/advanced/lifecycle-scripts) in docs postinstall script should execute after packages are written to the disk, but it doesn't

### To reproduce

.yarnrc.yaml
```yaml
yarnPath: .yarn/releases/yarn-3.4.1.cjs
nodeLinker: node-modules
```

package.json
```json
{
  "dependencies": {
    "husky": "8.0.3"
  },
  "scripts": {
    "postinstall": "echo Success"
  }
}
```

terminal
```bash
yarn
```

output:
```
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 0s 96ms
```
no `Success` message

### Environment

```shell
System:
  OS: Windows 10 10.0.19044
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz 
Binaries:
  Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 3.4.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
```

**Comment by arcanis** [comment]
Yarn doesn't print the postinstall output, unless they fail.

**Comment by dev-richardnguyen** [comment]
I still get this error although it's closed. Please help if you can

**Comment by b3nab** [comment]
this should be opened until solved

**Comment by clemyan** [comment]
@dev-richardnguyen @b3nab
There is nothing to solve. The original issue describes a situation where a `postinstall` script executes successfully but its output (stdout and stderr) is not printed. This is working as intended and not a bug. You can override this behavior with the [`enableInlineBuilds` config](https://yarnpkg.com/configuration/yarnrc#enableInlineBuilds)

If you have a different situation, please open a new bug report with reproduction, or an enhancement request with justification.
