### ISSUE TITLE
[Bug?]: PnP can not resolve module on dts

### ISSUE THREAD

**Issue by flex-jonghyen** [yarnpkg/berry#5287]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Updated: 23.03.29

I need to create a GitHub issue, and the following is a description of the bug I need to include in the issue. I'd appreciate it if you could translate the bug description into English.

I'm in the following situation: I have 3 packages, A, B, and C, with dependencies in the order of A -> B -> C.

Package A exports the following code (this is part of the actual code):

```typescript
export interface ThemedStyled<Theme, ...> {...};
export const createThemedStyled<Theme>(theme: Theme): ThemedStyled<Theme, ...>;
```

Package B uses createThemedStyled from package A:

```typescript
import { createThemedStyled } from 'A';
export const { styled } = createThemedStyled(myTheme);
```

Finally, package C uses styled from package B:

```typescript
export const Button = styled(`...style code`);
```

After building each package and generating their dts, the output for package C's dts looks like this:

```typescript
export declare const Button: import('A').ThemedStyled<Theme, ...>;
```

However, it seems that in pnp, if package C doesn't explicitly have package A as a dependency, A cannot be resolved. This works correctly with nodeLinker: node-modules.

And I don't think this issue is tied to a specific library or the TypeScript compiler.
This issue seems to occur only in the dts, and adding package A to the devDependencies of the problematic package C resolves the issue.

The log is part of result of `tsc --traceResolution` about C package.
```
======== Resolving module '@stitches/react/types/styled-component' from '/Users/grapgrap/workspace/flex-frontend/.yarn/__virtual__/@flexteam-linear-virtual-f4877fba30/1/packages/linear/dist/components/input/styled.d.ts'. ========
Explicitly specified module resolution kind: 'NodeNext'.
Resolving in CJS mode with conditions 'node', 'require', 'types'.
File '/Users/grapgrap/workspace/flex-frontend/.yarn/__virtual__/@flexteam-linear-virtual-f4877fba30/1/packages/linear/dist/components/input/package.json' does not exist according to earlier cached lookups.
File '/Users/grapgrap/workspace/flex-frontend/.yarn/__virtual__/@flexteam-linear-virtual-f4877fba30/1/packages/linear/dist/components/package.json' does not exist according to earlier cached lookups.
File '/Users/grapgrap/workspace/flex-frontend/.yarn/__virtual__/@flexteam-linear-virtual-f4877fba30/1/packages/linear/dist/package.json' does not exist according to earlier cached lookups.
File '/Users/grapgrap/workspace/flex-frontend/.yarn/__virtual__/@flexteam-linear-virtual-f4877fba30/1/packages/linear/package.json' exists according to earlier cached lookups.
Loading module '@stitches/react/types/styled-component' from 'node_modules' folder, target file type 'TypeScript'.
File '/Users/grapgrap/workspace/flex-frontend/.yarn/__virtual__/@flexteam-linear-virtual-f4877fba30/1/packages/linear/dist/components/input/package.json' does not exist according to earlier cached lookups.
File '/Users/grapgrap/workspace/flex-frontend/.yarn/__virtual__/@flexteam-linear-virtual-f4877fba30/1/packages/linear/dist/components/package.json' does not exist according to earlier cached lookups.
File '/Users/grapgrap/workspace/flex-frontend/.yarn/__virtual__/@flexteam-linear-virtual-f4877fba30/1/packages/linear/dist/package.json' does not exist according to earlier cached lookups.
File '/Users/grapgrap/workspace/flex-frontend/.yarn/__virtual__/@flexteam-linear-virtual-f4877fba30/1/packages/linear/package.json' exists according to earlier cached lookups.
Loading module '@stitches/react/types/styled-component' from 'node_modules' folder, target file type 'JavaScript'.
======== Module name '@stitches/react/types/styled-component' was not resolved. ========
```

### To reproduce

https://github.com/flex-jonghyen/pnp-reproduce

### Environment

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.18.0 - /private/var/folders/ld/_l4gwlwn2j1fxtlp_mpc5xr00000gn/T/xfs-e9ba9998/node
    Yarn: 3.2.3 - /private/var/folders/ld/_l4gwlwn2j1fxtlp_mpc5xr00000gn/T/xfs-e9ba9998/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
```

**Comment by flex-jonghyen** [comment]
It works with node-modules

**Comment by flex-jonghyen** [comment]
I add another case on reproduce repository

**Comment by flex-jonghyen** [comment]
@arcanis I have been waiting for a response for two weeks, but I have not heard any answer. If you could please let me know of any entry that could help solve this issue, I would be happy to investigate it. I will await your response.

**Comment by SoYoung210** [comment]
@arcanis I have the same issue. Can i get a response on this issue? 🙏

**Comment by flex-jonghyen** [comment]
I updated the issue with more details.

**Comment by merceyz** [comment]
This looks like a bug in TypeScript, It's emitting imports for dependencies that aren't declared.

> It works with node-modules

That reproduction also shows the same issue, the reason it works is because of hoisting.
https://yarnpkg.com/advanced/rulebook/#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies

> if package C doesn't explicitly have package A as a dependency, A cannot be resolved

This is the expected behaviour, if a dependency isn't declared PnP wont let you access it.
