### ISSUE TITLE
[Bug?]: YN0070: automatic, uncalled for yarn 1->2 migration due to also uncalled for ~/.yarnrc.yml

### ISSUE THREAD

**Issue by mikelpr** [yarnpkg/berry#5325]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

yarn today for my computer decided that yarn 1 projects are to migrate to yarn 2, no excuses
working on a project that isn't yet ready for that migration was a shock

and it turned out to be a ~/.yarnrc.yml that I do not remember asking for nor do I remember having myself done

```
❯ yarn                                                          iot-client-js/git/main !
➤ YN0070: Migrating from Yarn 1; automatically enabling the compatibility node-modules linker 👍

➤ YN0000: ┌ Resolution step
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0000: ⠼ env-paths@npm:^2.2.0
^C%                                                                                       (killed it here)
```

### To reproduce

a ~/.yarnrc.yml as this contents, in my case:
```yarnPath: .yarn/releases/yarn-3.5.0.cjs```

### Environment

```shell
System:
    OS: Linux 6.1 Fedora Linux 37 (Workstation Edition)
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
  Binaries:
    Node: 18.12.1 - /tmp/xfs-deee523e/node
    Yarn: 3.5.0 - /tmp/xfs-deee523e/yarn
    npm: 8.19.2 - /usr/bin/npm
```

### Additional context

I don't remember having called ```yarn set version berry``` on my home directory nor do I understand why it would have a say over at the project's dir that is directories deep in my home folder but has its own package.json that doesn't have the packageManager stanza

**Comment by mikelpr** [comment]
I'd also like to note that https://yarnpkg.com/advanced/error-codes funnily has YN0069 and YN0071 entries but no YN0070. funny but hmmm

**Comment by merceyz** [comment]
Yarn doesn't upgrade on its own so someone ran `yarn set version ...` in your home directory, if your project doesn't state any other version (`yarnPath`) then the global one is used.
