### ISSUE TITLE
[Bug?]: Extraneous "@types/keyv" package unexpectedly installed

### ISSUE THREAD

**Issue by notten13** [yarnpkg/berry#5337]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When installing a package called "got", yarn always installs a package called "@types/keyv". I am not expecting this package to be installed, as it is not declared as a dependency by "got" or any of its dependencies.

I believe this may be a bug since yarn version 1 doesn't show the same behaviour.

### To reproduce

This minimal repository shows the issue: https://github.com/notten13/yarn-3-unexpected-package

### Environment

```shell
System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.15.1 - /private/var/folders/p9/975yhhjx6rd20lpdf2w3m12h0000gn/T/xfs-b674a449/node
    Yarn: 3.5.0 - /private/var/folders/p9/975yhhjx6rd20lpdf2w3m12h0000gn/T/xfs-b674a449/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
```

**Comment by notten13** [comment]
@arcanis Thanks for the explanation.

I do think there is still an issue though, versions 9.x of `got` definitely don't use `keyv`.

As far as I can tell, the problem explained in the issue you linked to was introduced in version 10, when `keyv` was added as a dependency of `got` but not `@types/keyv`.

This means that yarn is too eager when fixing this issue: in `packages/yarnpkg-extensions/sources/index.ts` line 57, the condition  `got@<11` should ideally exclude version less than 10 in my opinion, but I don't know if it's possible to express that in that file?

**Comment by arcanis** [comment]
> This means that yarn is too eager when fixing this issue: in `packages/yarnpkg-extensions/sources/index.ts` line 57, the condition `got@<11` should ideally exclude version less than 10 in my opinion, but I don't know if it's possible to express that in that file?

If that's the case, it's a regular semver range, so changing it to `^10` should work 🤔
