### ISSUE TITLE
[Bug] NYC

### ISSUE THREAD

**Issue by thealjey** [yarnpkg/berry#534]
NYC coverage tool does not work with yarn v2 PnP
according to @coreyfarrell the problem is most likely with yarn itself (idk what that might be)
I do not know what else to do but to link that issue here

https://github.com/istanbuljs/nyc/issues/1204

**Comment by arcanis** [comment]
To keep people that might find this issue in the loop: all problems have been identified and fixed in both Yarn and NYC, and it's been confirmed to work on NYC master. It hasn't been released yet, but hopefully once the 15.x branch will be stable we'll be able to close this issue 🙂

**Comment by arcanis** [comment]
I just merged an E2E test against NYC 15.x, closing this issue 🎉

**Comment by coreyfarrell** [comment]
@arcanis could I convince you to do a test run against `git://github.com/coreyfarrell/nyc#process-on-spawn`?  I'm planning to merge this via https://github.com/istanbuljs/nyc/pull/1243, it makes some updates to the way which nyc performs module preload's.  I ran a manual test using yarn pnp locally and it worked fine but additional verification would be great.

**Comment by arcanis** [comment]
Looks fine: https://github.com/yarnpkg/berry/pull/641/checks?check_run_id=352760663 👍
