### ISSUE TITLE
[Bug] missing packages/berry-cli-package.json

### ISSUE THREAD

**Issue by willemneal** [yarnpkg/berry#537]
**Describe the bug**

>The standard bundle uses a predefined set of plugins defined in **packages/berry-cli/package.json.** If your PR aims to add a new plugin to the standard build you'll need to add it there (note that this decision should be left to the core maintainers - please don't modify this setting yourself).

> For development purposes, you can build your plugin as part of your own local bundle by using the --plugin option in the command line:

> $ `yarn build:cli --plugin @yarnpkg/plugin-typescript`

**To Reproduce**

Try to find the missing file.

**Additional context**

Where are they located now?

**Comment by arcanis** [comment]
[Updated](https://github.com/yarnpkg/berry/commit/f2ae1e901f7d894d1fa78b309cb6cd18ecf8ea0d) - the `berry-*` folders have been renamed into `yarnpkg-*` some time ago.
