### ISSUE TITLE
[Feature] Hide folder aliases defined using `link:` from outdated dependencies when using `yarn upgrade-interactive`

### ISSUE THREAD

**Issue by lensbart** [yarnpkg/berry#5393]
Previously flagged in https://github.com/yarnpkg/berry/issues/3112 (closed as stale)
Previously flagged in https://github.com/yarnpkg/berry/issues/2865 (closed as stale)
Could be alleviated by https://github.com/yarnpkg/yarn/issues/3368

- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

Following the example given at https://yarnpkg.com/features/protocols#why-is-the-link-protocol-recommended-over-aliases-for-path-mapping, if you define an alias for your `src` folder as follows in `package.json`:

```json
{
  "dependencies": {
    "src": "link:./src"
  }
}
```

and subsequently run `yarn upgrade-interactive`, it will confusingly show the `src` dependency as being out-of-date with the NPM package of the same name:

```
   src ----------------------------------------- ◉ link:./src -- ◯ link:./src::… ◯ ^1.1.2 -------
```

**Describe the solution you'd like**

I think this behaviour is confusing, because the `src` folder and `src` NPM package are completely unrelated, except for the fact that they have the same name. Therefore, I think linked folders should be excluded from the list of dependencies to upgrade.

**Describe the drawbacks of your solution**

None that I can think of

**Describe alternatives you've considered**

None

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/5442
