### ISSUE TITLE
Running Jest with yarn pnp enabled and node v20 leaks memory

### ISSUE THREAD

**Issue by yossizahn** [yarnpkg/berry#5399]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

The following combination of circumstances causes a memory leak of approx. 200mb per second on my machine:
- yarn with pnp enabled 
- node v20
- `yarn jest --watch`

I don't know if this is a yarn issue or a nodejs issue or a jest issue
I can only reproduce the problem when all the conditions are met (yarn pnp, node 20, jest --watch)

### To reproduce

I am not sure how to test for a memory leak using sherlock

I have created minimal reproduction here: https://github.com/yossizahn/yarn-pnp-jest-node20-memleak

### Environment

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 20.0.0 - /private/var/folders/6t/cgb4q3vj0tngmc63b3_t3l1h0000gn/T/xfs-66d5c86b/node
    Yarn: 3.5.0 - /private/var/folders/6t/cgb4q3vj0tngmc63b3_t3l1h0000gn/T/xfs-66d5c86b/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v20.0.0/bin/npm
```

**Comment by merceyz** [comment]
You're running into https://github.com/nodejs/node/issues/47566, if you don't need ESM support you can add the following to your `.yarnrc.yml` to avoid the problem.
```yaml
pnpEnableEsmLoader: false
```
https://yarnpkg.com/configuration/yarnrc#pnpEnableEsmLoader

**Comment by yossizahn** [comment]
Thanks! 
(I spent hours isolation this bug :sweat_smile:, I'm happy the cause has been identified already)
