### ISSUE TITLE
Yarn npm publish does not upload type declaration file. (d.ts)

### ISSUE THREAD

**Issue by danielweil** [yarnpkg/berry#5415]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Yarn npm publish does not upload type declaration file. (d.ts) while when I use npm publish directly it does

Is there any config there needs to be done? I couldn't find anything in the docs.

### To reproduce

Yarn npm publish

dist folder does not contain index.d.ts

### Environment

```shell
Ubuntu 22.04
```

**Comment by arcanis** [comment]
> ### To reproduce
> Yarn npm publish
> 
> dist folder does not contain index.d.ts

That's not a reproduction.

**Comment by danielweil** [comment]
Thanks for the response. Figured out the problem. The key "files" inside packages.json was missing.
