### ISSUE TITLE
[Bug]Cannot set registry for specific scope

### ISSUE THREAD

**Issue by jinliming2** [yarnpkg/berry#543]
**Describe the bug**

v1 can set registry for `@test` scope use: `yarn config set @test:registry http://example.com`.

But that doesn't work with v2:

```bash
$ yarn config set @test:registry http://example.com
Usage Error: Couldn't find a configuration settings named "@test:registry"

$ yarn config set <name> <value>
```

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version: v10.16.0
 - Yarn version: 2.0.0-rc.6

**Comment by brokenmass** [comment]
additionally yarn v2 ignores `.npmrc` registry configuration and even if you manually add the custom registries to `.yarnrc` is not able to resolve the scoped packages.

**Comment by arcanis** [comment]
The npmrc configuration is now ignored by design. All Yarn configuration must come from the `.yarnrc.yml` files. Please check the following documentation for the list of supported settings (cf `npmScopes` for configuring per-scope registries):

https://next.yarnpkg.com/configuration/yarnrc

**Comment by arcanis** [comment]
Note that the documentation has a typo: the npmScopes settings are strings, not a boolean 🤔

**Comment by jinliming2** [comment]
So it means that I cannot set registry by using command line any more, I must edit the config file manually?

**Comment by arcanis** [comment]
Yes, or you can use a tool that can modify Yaml files.
