### ISSUE TITLE
[Bug?]: Yarn install fails when weird hash character in package name

### ISSUE THREAD

**Issue by drodil** [yarnpkg/berry#5434]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Trying to install some internal packages fails with yarn 3.5.1 with the following error:

```sh
➤ YN0001: │ Error: @company/package@npm:^5.1.0: @company/package@npm:5.1.0::__archiveUrl=https%3A%2F%2Fcompany.org%2Fapi%2Fnpm%2Fnpm-mirror%2F%40company%2Fpackage%2F-%2F%40company%2Fpackage-5.1.0.tgz%23 isn't supported by any available resolver
```

As the URL implies, there is a weird `%23` as in the hash character in the end. Is this somehow related to the package or should yarn remove (trim?) all extra characters from the package name before resolving? 

### To reproduce

Couldn't find any public package that fails to install like this

### Environment

```shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.20.0 - /private/var/folders/jx/6_rpw_wd31bc2sxg5brx5j780000gn/T/xfs-6f6b5695/node
    Yarn: 3.5.1 - /private/var/folders/jx/6_rpw_wd31bc2sxg5brx5j780000gn/T/xfs-6f6b5695/yarn
    npm: 8.19.4 - /opt/homebrew/opt/node@16/bin/npm
```

**Comment by zcmander** [comment]
` %23` is just `#` character at the end of the URL, so that should not matter. However, interesting issue, not sure what is causing this...

**Comment by drodil** [comment]
True, updated the title and description.
