### ISSUE TITLE
[Bug] Yarn 2 doesn't recognize `yarn init -y`

### ISSUE THREAD

**Issue by segrey** [yarnpkg/berry#545]
**Describe the bug**

`yarn init -y` doesn't work in Yarn 2 (it works as expected in Yarn 1.19.1).

**To Reproduce**

1. `yarn set version from sources`
2. `yarn --version` outputs `2.0.0-rc.10`
3. `yarn init -y` finishes with exit code 1 and outputs
```
Unknown Syntax Error: Unsupported option name ("-y").

$ yarn init [-p,--private]
```

**Environment if relevant (please complete the following information):**

 - OS: Linux
 - Node version 12.9.0
 - Yarn version 2.0.0-rc.10

**Comment by arcanis** [comment]
Fixed in #554
