### ISSUE TITLE
Yarn 3.5.1 | YN0001: │ RequestError: Socket connection timeout

### ISSUE THREAD

**Issue by ZehuaZhang** [yarnpkg/berry#5452]
yarn version `3.5.1`

running `yarn`

```
➤ YN0000: ┌ Resolution step
➤ YN0001: │ RequestError: Socket connection timeout
    at ClientRequest.<anonymous> (/Users/===/.yarn/releases/yarn-3.5.1.cjs:195:14340)
    at Object.onceWrapper (node:events:626:26)
    at ClientRequest.emit (node:events:523:35)
    at o.emit (/Users/===/.yarn/releases/yarn-3.5.1.cjs:190:90286)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:511:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at new NodeError (node:internal/errors:399:5)
    at internalConnectMultiple (node:net:1099:20)
    at Timeout.internalConnectMultipleTimeout (node:net:1638:3)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7)
```

**Comment by fsyntax** [comment]
Same here, its very annoying I can't properly `yarn install` ..

**Comment by ZehuaZhang** [comment]
So I fixed yesterday with the following, FYI, my existing project is running on intel mac, am migrating from yarn 1 to yarn 3
1. remove brew installed node
2. remove brew installed corepack
3. remove yarn
4. clean node cache `npm cache clean`
5. download and install node from the mac installer in the official website
6. `npm i -g yarn`
7. go to your existing project, remove any yarn related files and folders, e.g. `.yarn/`, `yarn.lock`, `.yarnrc.yml`, and `pnp` files, which are plug and plays for yarn if any.
8. add a new file in root, called `.yarnrc.yml` and add `nodeLinker: node-modules`, this is to tell yarn to install with traditional `node_modules`, the new recommended zero install, pnp, plug n play is buggy, some packages, like `eslint`, `nextjs`, are not installable and will occur the timeout error in current issue.
9. in your project root, open a terminal, type `yarn -v`, it should show something like mine `3.5.1`, which is beyond version  `1`, you don't need to `set berry` as mentioned in the original yarn doc
10. run `yarn install` or `yarn`, it should install everything

So that is my fix, not sure what cause the error previously, hope it could be fixed. Don't get me wrong, `yarn` is still the best imo in terms of package install speed and resolving dependencies, `pnpm` is fast, but it has issues with nested dependencies, npm is just very slow and sluggish with nested / peer dependencies

**Comment by coucoseth** [comment]
@ZehuaZhang how did you remove yarn, i cant seem to find that in the documentation

**Comment by ZehuaZhang** [comment]
> @ZehuaZhang how did you remove yarn, i cant seem to find that in the documentation

Just reverse the order of how you installed `yarn`,

**Comment by tommyspot** [comment]
First thing, you should check your network.

**Comment by flyon** [comment]
same issue here with yarn 3.5.1 and also the latest 3.6.1

**Comment by IgnisDa** [comment]
Don't know why but `rm -rf ~/.yarn/berry/cache/` normally fixes it for me.

**Comment by mattkindy** [comment]
Only had this problem on node 20 (`v20.2.0`). Switching to 18 resolved it.

**Comment by amartincolby** [comment]
This error is frustratingly intermittent. It is hard to know if a change fixed it or not or if things are randomly working for awhile. I have switched to Node 18 @mattkindy. So here's hoping.

**Comment by marcelo2605** [comment]
It's working with node 20.12.1 and yarn 3.5.1
