### ISSUE TITLE
[Feature] Implementing the `--installTypes` option in the `yarn add` command

### ISSUE THREAD

**Issue by vclemenzi** [yarnpkg/berry#5455]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

When working with Yarn, it is common to encounter situations where we need to install both a package and its corresponding types for TypeScript projects. Currently, after running the `yarn add` command to install a package, we have to manually execute a separate command to install the `@types` package. This additional step can be time-consuming and cumbersome, especially when dealing with multiple packages.

**Describe the solution you'd like**

I propose adding the `--installTypes` option to the `yarn add` command. When this option is used, Yarn should automatically handle the installation of types for the package being installed. Yarn should check if external declaration types are available through the `@types` package and, if found, install them as devDependencies. Additionally, if the package provides internal type declarations, Yarn should handle their installation as well.

Here's an example of how the command would look:

```shell
yarn add bcrypt --installTypes
```
With this syntax, Yarn should install the `bcrypt` package and, if available, the corresponding external declaration types through `@types/bcrypt` (which would be added as devDependencies). If separate declaration types are not available, I would expect Yarn to gracefully ignore them instead of generating an error.

This feature would greatly streamline the process of installing declaration types for external packages. Currently, we need to manually run a separate command to install types, but with the integrated `--installTypes` option in the yarn add command, we could save time and simplify our workflow.

**Describe the drawbacks of your solution**

While this solution aims to improve the developer experience, there are some potential drawbacks to consider. One drawback is the potential increase in the number of devDependencies due to the automatic installation of external declaration types. This could lead to a larger package size and potential conflicts between different versions of the same types.

Another drawback is the reliance on the availability and maintenance of external declaration types through the @types packages. If these packages are not up-to-date or if the declaration types are incomplete, the automatic installation may result in incorrect or outdated types being used.

**Describe alternatives you've considered**

One alternative solution would be to create a separate plugin specifically for handling the installation of types. However, integrating this functionality directly into Yarn's core would provide a more streamlined and consistent experience for all users. By having it as a built-in option, it would be easier to maintain and keep up-to-date with any changes in Yarn itself.

Thank you for considering this proposal. I believe that implementing the `--installTypes` option in the yarn add command would greatly benefit Yarn users and improve the TypeScript development workflow.

**Comment by merceyz** [comment]
> One alternative solution would be to create a separate plugin specifically for handling the installation of types. However, integrating this functionality directly into Yarn's core would provide a more streamlined and consistent experience for all users. By having it as a built-in option, it would be easier to maintain and keep up-to-date with any changes in Yarn itself.

We actually already have a plugin for this and it will be included by default in Yarn v4, for now though you'll need to manually import it.
https://github.com/yarnpkg/berry/tree/db1600bdd5ad8230717bc7926b031fecfe813555/packages/plugin-typescript

```sh
yarn plugin import typescript
```
