### ISSUE TITLE
yarn workspaces run in v2?

### ISSUE THREAD

**Issue by thealjey** [yarnpkg/berry#546]
Does Yarn 2 not have any other workspace related commands except "workspaces list"?
How do I run a command on all workspaces?

**Comment by deini** [comment]
It does, check out this section in the docs:  `workspaces foreach` https://next.yarnpkg.com/cli/workspaces/foreach

**Comment by arcanis** [comment]
Cf the [documentation](https://next.yarnpkg.com/cli/install)

**Comment by thealjey** [comment]
aha, thanks! Then, I guess, the issue is that "yarn -h" fails to mention it :)

**Comment by thealjey** [comment]
```
$ yarn workspaces foreach -p run api-extractor
Unknown Syntax Error: Command not found; did you mean:

$ yarn workspaces list [-v,--verbose] [--json]
```
actually, even "yarn outdated" is not working
```
$ yarn outdated
Usage Error: Couldn't find a script named "outdated".

$ yarn run <scriptName> ...
```

```
$ yarn -v
2.0.0-rc.6
```

**Comment by deini** [comment]
Did you add it to your plugins? 

From the docs link I shared:
>In order to use this command you need to add @yarnpkg/plugin-workspace-tools to your plugins.

**Comment by thealjey** [comment]
d'oh :)
that does not explain the absence of "yarn outdated" though
or, does that also need to be installed as a package now?

**Comment by deini** [comment]
There is nothing like `yarn outdated` yet, you can see the list of available commands in the docs.

Not exactly what you are looking for but you could use https://next.yarnpkg.com/cli/up in interactive mode (1-dep at a time tho).

You could also write a plugin and submit  a PR 🕺

**Comment by arcanis** [comment]
If not in the documentation, it hasn't been implemented 🙂 Outdated and upgrade-interactive are the two main commands that are currently missing (they would probably be stored in their own optional plugin, though). Contributions welcome!
