### ISSUE TITLE
[Bug?]: Make `@types/lodash` a dependency of `@yarnpkg/core`

### ISSUE THREAD

**Issue by JamieMagee** [yarnpkg/berry#5513]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

`@yarnpkg/core` exports a type from `@types/lodash` in `Report.d.ts`. Specifically the types exported for `progressViaTitle`:

```ts
static progressViaTitle(): {
    [Symbol.asyncIterator](): AsyncGenerator<{
        title: string | undefined;
    }, never, unknown>;
    hasProgress: boolean;
    hasTitle: boolean;
    setTitle: import("lodash").DebouncedFunc<(title: string) => void>;
};
```

`@types/lodash` should be moved from `devDependencies` to `dependencies`

https://github.com/yarnpkg/berry/blob/2c18c35baea76f947a80c391901758a5ee076191/packages/yarnpkg-core/package.json#L46

### To reproduce

N/A

### Environment

```shell
N/A
```

**Comment by ljharb** [comment]
oof, so then non-TS users have to install a DT package?

**Comment by arcanis** [comment]
It's a dependency like any other - but in that case the best fix is probably to explicitly type `setTitle` to avoid relying on the `DebouncedFunc` type, so we stop depending on Lodash.
