### ISSUE TITLE
[Bug?]: Unable to use monorepo

### ISSUE THREAD

**Issue by cyberalien** [yarnpkg/berry#5529]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Created a basic monorepo to play with Yarn, ran into the following issue:

When running `yarn workspaces foreach run test`, I get this error:

```
Unknown Syntax Error: Command not found; did you mean:

$ yarn workspaces list [--since] [-R,--recursive] [--no-private] [-v,--verbose] [--json]
While running workspaces foreach run test
```

Issues that list the same issue suggest running this: `yarn plugin import @berry/plugin-workspace-tools`

but then I get the following error:

```
➤ YN0000: Official plugins only accept strict version references. Use an explicit URL if you wish to download them from another location.
➤ YN0000: Failed with errors in 0s 18ms
```

What is going on?

### To reproduce

https://github.com/cyberalien/yarn-monorepo-test

### Environment

```shell
System:
    OS: macOS 13.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 20.3.0 - /private/var/folders/3l/_rx3z7j16cg4_8kzh6r0jz1m0000gn/T/xfs-778dbd5c/node
    Yarn: 3.6.0 - /private/var/folders/3l/_rx3z7j16cg4_8kzh6r0jz1m0000gn/T/xfs-778dbd5c/yarn
    npm: 9.7.1 - /usr/local/bin/npm
```

**Comment by merceyz** [comment]
The command to import the workspace-tools plugin is provided in its documentation https://yarnpkg.com/cli/workspaces/foreach
```sh
yarn plugin import workspace-tools
```

**Comment by sadashiv-sumasoft** [comment]
This plugin is not exists anymore! What should we do now to run the yarn workspaces foreach command?
