### ISSUE TITLE
[Feature] yarn workspace <workspaceName> run --json

### ISSUE THREAD

**Issue by jmatsushita** [yarnpkg/berry#5539]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

As a developer of autocompletion scripts, I would like to list available commands in a workspace in a structured format, however:
- `yarn workspace <workspaceName> run` returns text
- `yarn workspace <workspaceName> run --json` doesn't work.

**Describe the solution you'd like**

Implement a `--json` for the `workspace run` command without arguments. 

**Describe the drawbacks of your solution**

Can't think of any.

**Describe alternatives you've considered**

For downstream users, parsing text is the current possible solution, but that's not ideal.

**Comment by arcanis** [comment]
That seems reasonable - want to give a try at implementing it ? It's implemented here:
https://github.com/yarnpkg/berry/blob/dbfb5007fae4aa639fa969536a9158d391b347c7/packages/plugin-essentials/sources/commands/runIndex.ts#L9

Along with an associated test here (avoid using `toMatchSnapshot`, especially to test the JSON output):
https://github.com/yarnpkg/berry/blob/dbfb5007fae4aa639fa969536a9158d391b347c7/packages/acceptance-tests/pkg-tests-specs/sources/commands/run.test.js#L126

**Comment by quantumflo** [comment]
@arcanis Hi can I work on this issue?
