### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by MrEfrem** [yarnpkg/berry#557]
https://next.yarnpkg.com/advanced/peer-dependencies

> The PnP linker guarantees that each combination of package name / version will only be instantiated once, except in one documented case: if a package has peer dependencies. Such ones will be instantiated once for each time a hard dependency is found in the dependency tree.

What is `such ones` related to? Is it `packages` or `peer dependencies`? And what is `a hard dependency`? I try to understand this article but really or English there isn't very well or my.

**Comment by arcanis** [comment]
"Such one" -> "Such packages".

"Hard dependency" -> A `dependencies` or `devDependency`, but not `peerDependency`.

Basically, if `Foo` lists peer dependencies, and if `A` and `B` both depend on `Foo`, then `Foo` will be instantiated twice (once for `A`, once for `B`).

**Comment by MrEfrem** [comment]
@arcanis thanks.
