### ISSUE TITLE
[Feature]"packageManager": "yarn@berry" should be supported.

### ISSUE THREAD

**Issue by zhanghengxin** [yarnpkg/berry#5570]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

I don't want fix it every times.

**Describe the solution you'd like**

no

**Describe the drawbacks of your solution**

no

**Describe alternatives you've considered**

no

**Comment by merceyz** [comment]
This is the wrong repository for such a request as that field belongs to Corepack, take a look at https://github.com/nodejs/corepack.
