### ISSUE TITLE
Half of registry.yarnpck.com ipv6 addresses not reachable.

### ISSUE THREAD

**Issue by ScheintodX** [yarnpkg/berry#5578]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

PING 2606:4700::6810:1523(2606:4700::6810:1523) 56 data bytes                                                                                                                                                        
From 2003:d3:8f20:4f8::1 icmp_seq=1 Destination unreachable: No route                                                                                                                                                
PING 2606:4700::6810:1b23(2606:4700::6810:1b23) 56 data bytes                                                                                                                                                        
64 bytes from 2606:4700::6810:1b23: icmp_seq=1 ttl=55 time=15.8 ms                                                                                                                                                   
PING 2606:4700::6810:1123(2606:4700::6810:1123) 56 data bytes                                                                                                                                                        
64 bytes from 2606:4700::6810:1123: icmp_seq=1 ttl=55 time=18.7 ms                                                                                                                                                   
PING 2606:4700::6810:1223(2606:4700::6810:1223) 56 data bytes                                                                                                                                                        
From 2003:d3:8f20:4f8::1 icmp_seq=1 Destination unreachable: No route                                                                                                                                                
PING 2606:4700::6810:1623(2606:4700::6810:1623) 56 data bytes                                                                                                                                                        
64 bytes from 2606:4700::6810:1623: icmp_seq=1 ttl=55 time=14.2 ms                                                                                                                                                   
PING 2606:4700::6810:1723(2606:4700::6810:1723) 56 data bytes                                                                                                                                                        
64 bytes from 2606:4700::6810:1723: icmp_seq=1 ttl=55 time=15.6 ms                                                                                                                                                   
PING 2606:4700::6810:1323(2606:4700::6810:1323) 56 data bytes                                                                                                                                                        
From 2003:d3:8f20:4f8::1 icmp_seq=1 Destination unreachable: No route                                                                                                                                                
PING 2606:4700::6810:1423(2606:4700::6810:1423) 56 data bytes                                                                                                                                                        
64 bytes from 2606:4700::6810:1423: icmp_seq=1 ttl=55 time=17.5 ms                                                                                                                                                   
PING 2606:4700::6810:1923(2606:4700::6810:1923) 56 data bytes                                                                                                                                                        
From 2003:d3:8f20:4f8::1 icmp_seq=1 Destination unreachable: No route                                                                                                                                                
PING 2606:4700::6810:1823(2606:4700::6810:1823) 56 data bytes                                                                                                                                                        
From 2003:d3:8f20:4f8::1 icmp_seq=1 Destination unreachable: No route                                                                                                                                                
PING 2606:4700::6810:1023(2606:4700::6810:1023) 56 data bytes                                                                                                                                                        
From 2003:d3:8f20:4f8::1 icmp_seq=1 Destination unreachable: No route                                                                                                                                                
PING 2606:4700::6810:1a23(2606:4700::6810:1a23) 56 data bytes                                                                                                                                                        
64 bytes from 2606:4700::6810:1a23: icmp_seq=1 ttl=55 time=13.5 ms                                                                                                                                                   

### To reproduce

dig +short -t aaaa registry.yarnpkg.com

(dig +short -t aaaa registry.yarnpkg.com | grep 2606 | while read ip; do ping6 -c1 $ip; done )| tee whereisyarn.txt

### Environment

```shell
ubuntu 2204
```

**Comment by ScheintodX** [comment]
(so half of the "yarn" commands fali with error An unexpected error occurred: "https://registry.yarnpkg.com/ws: connect ENETUNREACH 2606:4700::6810:1423:443".)

**Comment by merceyz** [comment]
See https://yarnpkg.com/getting-started/qa/#queries-to-registryyarnpkgcom-return-a-404500-is-it-down
