### ISSUE TITLE
[Documentation] Is `@yarnpkg/esbuild-plugin-pnp` still necessary for esbuild?

### ISSUE THREAD

**Issue by evanw** [yarnpkg/berry#5580]
I noticed that [Yarn's documentation for PnP](https://yarnpkg.com/features/pnp/#support-via-plugins) implies that the plugin `@yarnpkg/esbuild-plugin-pnp` is required to use Yarn PnP with esbuild. AFAIK this is no longer the case. Should the website be updated to indicate that esbuild now has native support, similar to what the website says for Webpack? Or is there a scenario where esbuild's support falls short, which is why the plugin is still listed as required in Yarn's documentation?

**Comment by merceyz** [comment]
The documentation should be updated, the source code for the plugin was replaced with a README stating it isn't required anymore.
https://github.com/yarnpkg/berry/tree/506ded5f5f5a89553435940c74f1d857fd685a42/packages/esbuild-plugin-pnp

**Comment by merceyz** [comment]
The documentation for Yarn v4 no longer mentions it and the Yarn v3 docs were updated in https://github.com/yarnpkg/berry/pull/4726 but it wasn't backported and published.

I've backported it to the v3 docs so this should be resolved now.
