### ISSUE TITLE
[Feature] Cache dependencies for all branches

### ISSUE THREAD

**Issue by jackHedaya** [yarnpkg/berry#559]
- [x] I'd be willing to implement this feature
        **Would need to familiarize myself with the yarn repo.**
- [ ] This feature can already be implemented through a plugin
        _Not sure_

**Describe the user story**

It is frustrating when I change git branches and get a dependency error because I didn't `yarn` again.

**Describe the solution you'd like**

I think it would be very valuable for yarn to automagically keep track of which dependencies are needed for which git branch, pivoting whenever a branch is changed. 

**Describe the drawbacks of your solution**

The drawbacks include storage issues (by keeping unused dependencies) and tracking the changes without reformatting `yarn.lock`.

**Describe alternatives you've considered**

A thought that occurred to me was a git hook (like `husky`) that runs `yarn` every time the branch is changed.

**Comment by arcanis** [comment]
Have you seen [Zero-Installs](https://next.yarnpkg.com/features/zero-installs)?

**Comment by jackHedaya** [comment]
Just checked it out. Looks awesome! Definitely looking forward to Berry!
