### ISSUE TITLE
[Bug?]: Workspace detection not working on Windows with v3 and @yarnpkg/core

### ISSUE THREAD

**Issue by KalleV** [yarnpkg/berry#5613]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

Project workspace is not being detected on Windows when using `@yarnpkg/core` programmatically.

This leads to an error such as:
```
The nearest package directory (C:\Users\username\project) doesn't seem to be part of the project declared in C:\Users\username\project.

- If C:\Users\username\project isn't intended to be a project, remove any yarn.lock and/or package.json file there.
- If C:\Users\username\project is intended to be a project, it might be that you forgot to list  in its workspace configuration.
- Finally, if C:\Users\username\project is fine and you intend  to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.
UsageError:
    at Function.find (C:\Users\username\project\node_modules\@yarnpkg\core\lib\Project.js:119:15)
    at async getWorkspaces (C:\Users\username\project\node_modules\@wayfair\nextjs-translate\src\parse-workspace.js:6:21)
    at async module.exports (C:\Users\username\project\node_modules\@wayfair\nextjs-translate\src\compile.js:10:21)
    at async run (C:\Users\username\project\node_modules\@wayfair\nextjs-translate\compile-translations.js:17:5)
```

### To reproduce

```js repro
const cwd = "C:\\Users\\username\\Desktop\\project";
const {Project, Configuration} = require('@yarnpkg/core');

const {project} = await Project.find(configuration, cwd);
```

### Environment

```shell
System:
  Windows

Binaries:
  Yarn 3.5.0
```

### Additional context

I traced it to this line: https://github.com/yarnpkg/berry/blob/cb19bb3377b7564eced457c47db18109e1041cc1/packages/yarnpkg-core/sources/Project.ts#L463

The CWD is not detected as an absolute path by the isAbsolute check even though it is a Windows absolute path. This leads to a broken path like "/C:\\Users\\username\\Desktop\\project/C:\\Users\\username\\Desktop\\project/C:\\Users\\username\\Desktop\\project" after it is passed to the resolve.

**Comment by paul-soporan** [comment]
Yarn only works with `PortablePath`s (windows paths are normalized to posix paths), while regular paths are `NativePath`s.

You need to convert all paths you pass to the Yarn APIs using `npath.toPortablePath` (where `npath` comes from `@yarnpkg/fslib`).

**Comment by KalleV** [comment]
Awesome, thank you very much! Works like a charm.
