### ISSUE TITLE
[Bug?]: Error: Assertion failed while running yarn dedupe

### ISSUE THREAD

**Issue by Brooooooklyn** [yarnpkg/berry#5654]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

`yarn dedupe` crashed with `The package (84ae1e7f1ecbd610259779009efb45c8aa972e2cab78713f9bda6532554de6121ac80e0a4607cb122f49434c2db742409652097f8ab2906803145c2fbebc8569) should have been registered`

### To reproduce

- Clone https://github.com/toeverything/AFFiNE/
- yarn install
- yarn dedupe

### Environment

```shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.17.1 - /private/var/folders/n9/kr5mprh51zn5m0vwyt2gr6_w0000gn/T/xfs-4d943d22/node
    Yarn: 3.6.0 - /private/var/folders/n9/kr5mprh51zn5m0vwyt2gr6_w0000gn/T/xfs-4d943d22/yarn
    npm: 9.6.7 - /opt/homebrew/bin/npm
    pnpm: 8.6.12 - /opt/homebrew/bin/pnpm
```

**Comment by vaishaly** [comment]
[Brooooooklyn](https://github.com/Brooooooklyn)  Did you find answer for the above question.

**Comment by clemyan** [comment]
I can reproduce with 3.6.0 but not 4.4.0. Probably got fixed somewhere in between.

Can you try to upgrade and see if you are still encountering the bug?
