### ISSUE TITLE
[Feature] Provide permanent folder with dependencies binaries

### ISSUE THREAD

**Issue by segrey** [yarnpkg/berry#566]
- [ ] I'd be willing to implement this feature
- [x] This feature can already be implemented through a plugin

**Describe the user story**

Like npm / Yarn v1 generate `node_modules/.bin` folder with dependencies binaries, Yarn v2 could do the same. Seems currently Yarn 2 already generates a folder with dependencies binaries and prepend it to `PATH` when running a script from package.json with `yarn run <script>` command. However, it works for package.json scripts only.

What do you think about generating such a folder permanently (not temporary)?
Prepending it to `PATH` environment variable would allow to run dependencies binaries in a terminal more naturally, e.g. `eslint` instead of `yarn run eslint`.

**Describe the solution you'd like**

For example, it could be `.yarn/.bin/`.

**Describe the drawbacks of your solution**

At least more FS operations to create/populate a folder.

**Describe alternatives you've considered**

As an alternative, it's possible to run `yarn run <dependency binary>`

**Additional context**

For example, IntelliJ could prepend such a folder to `PATH` automatically, like it currently does with `node_modules/.bin`.

**Comment by arcanis** [comment]
Imo this feature could already be implemented rather easily through a plugin (by hooking on the [`afterAllInstalled` hook](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/sources/Plugin.ts#L62)) 🤔

I'm not sure adding it to the core would be very impactful as those binaries can already be called through `yarn <bin-name>` (even moreso once we get #565). What do you think?

**Comment by arcanis** [comment]
Note that one main reason I'm not super fond of global binaries (in relation with [WEB-42294](https://youtrack.jetbrains.com/issue/WEB-42294)) is that they obfuscate the source of the tool. For example, if running `gulp something` is enough to run Gulp, then it's unclear whether Gulp is installed globally or in the project. By comparison, `yarn gulp` is a few extra characters but clearly indicates that the tool comes from the local project.

**Comment by segrey** [comment]
You're right that `yarn gulp` clearly indicates that a local dependency is wanted. On the other hand, we haven't received any complaints regarding prepending `node_modules/.bin` to `PATH` (and this feature is optional and can be turned off in IntelliJ preferences).
Given this feature might be controversial a bit, I'd suggest to not implement it for now and close the issue. I believe it can be re-opened in the future if there is a demand for this feature.

**Comment by segrey** [comment]
>Imo this feature could already be implemented rather easily through a plugin (by hooking on the afterAllInstalled hook)

Unfortunately, this is not an option for IDEs, because `yarn install` can be run outside IDE.
