### ISSUE TITLE
[Bug?]: Getting @yarnpkg/parsers@3.0.0-rc.49: The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by doregg** [yarnpkg/berry#5666]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Start getting an error:
```
error @yarnpkg/parsers@3.0.0-rc.49: The engine "node" is incompatible with this module. Expected version ">=18.12.0". Got "16.15.1"
error Found incompatible module.
```
when running `yarn global add lerna@^5.5.0`.
I realized that you pushed `3.0.0-rc.49` 2 hours ago. It worked before.

### To reproduce

```
yarn global add lerna@^5.5.0
```

### Environment

```shell
Github pipelines
Node 16.15.1
yarn 1.22.19
```

**Comment by doregg** [comment]
wrong repo

**Comment by tcs-cclaflin** [comment]
@doregg What is the correct repo? We're affected by this as well.

**Comment by deefactorial** [comment]
@doregg I am also impacted by this issue. Please recommend correct repo, doing a search for @yarnpckg/parsers leads to this result https://github.com/yarnpkg/berry/pkgs/npm/parsers isn't that this repo?
