### ISSUE TITLE
[Bug?]: Yarn run functions are not working

### ISSUE THREAD

**Issue by snorberhuis** [yarnpkg/berry#5672]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I am trying to expand parameters into a script. The format of the script requires that the parameters are somewhere inside the script and not appended at the end. 

I saw several solutions, but it does not seem to work for me:
https://github.com/yarnpkg/yarn/issues/5207#issuecomment-690583826

### To reproduce

Having the following `package.json`
```
{
  "name": "yarn-bug",
  "packageManager": "yarn@3.6.2",
  "scripts": {
    "reproduce": "f () { echo  \"bin/$@.ts\"; }; f"
  }
}
```
Now run: 
```
$ yarn reproduce param1/param2   
Syntax Error: Expected "$", "$'", "$(", "$((", "${", "&", "&&", "'", ";", "<", "<&", "<<<", ">", ">&", ">>", "\"", "\"\"", "\\", "|", "|&", "||", [ \t], [0-9], or end of input but "{" found (line 1, column 6).
```
You can run this in yarn1 or in npm:

```
npm run reproduce param1/param2

> reproduce
> f () { echo  "bin/$@.ts"; }; f param1/param2

bin/param1/param2.ts
```

### Environment

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.16.1 - /private/var/folders/vz/cm07dq8914lglvyq2_stgwy40000gn/T/xfs-745ef108/node
    Yarn: 3.6.1 - /private/var/folders/vz/cm07dq8914lglvyq2_stgwy40000gn/T/xfs-745ef108/yarn
    npm: 9.5.1 - /opt/homebrew/opt/node@18/bin/npm
    pnpm: 7.30.1 - /opt/homebrew/bin/pnpm
  npmPackages:
    jest: ^29.5.0 => 29.6.1
```

**Comment by arcanis** [comment]
Functions are not supported by our portable shell language: https://yarnpkg.com/features/scripting#portable-shell

**Comment by snorberhuis** [comment]
Thank you for your clarification. This has helped me develop a solution that did work ultimately without functions.
