### ISSUE TITLE
YAML file documentation shows JSON samples

### ISSUE THREAD

**Issue by Peter-Sparksuite** [yarnpkg/berry#5689]
The page at https://yarnpkg.com/configuration/yarnrc shows that the settings file is `.yarnrc.yml`, but, the documentation seems instead, to be showing JSON examples throughout.  

Seems very odd to be mixing the two formats.

If the file is `.yarnrc.yml`, then I'd suggest that all of the documentation should likewise, be showing YAML examples!

**Comment by arcanis** [comment]
For all intent and purposes YAML is a superset of JSON, so a JSON file is a valid YAML file.

As for why it's this way, the code to generate this part of the documentation is already complicated, and it didn't feel valuable enough to spend time adding support for the two different syntaxes (considering the previous point).
