### ISSUE TITLE
[Bug?]: Package with two different versions provided for peer dep not correctly duplicated

### ISSUE THREAD

**Issue by nicolo-ribaudo** [yarnpkg/berry#5700]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I have the following monorepo, with `enableTransparentWorkspaces: false` and `nodeLinker: node-modules`:
```
- packages/
  - @babel/core
  - @babel/preset-env
```

The packages in the monorepo are at version `7.22.13`.

I have the following dependencies constraints:
- The repository root depends on `@babel/core@8.0.0-alpha.2` and on `@babel/preset-env@8.0.0-alpha.2` (from npm)
- `@babel/core@7.22.13` (in the monorepo) has a devDependency on `@babel/preset-env: workspace:^`
- `@babel/preset-env@7.22.13` (in the monorepo) has a devDependency on `"@babel/core": "workspace:^"` and a peerDependency on `"@babel/core": "^7.0.0"`
- `@babel/preset-env@8.0.0-alpha.2` (on npm) has a devDependency on `"@babel/core": "workspace:^"` and a peerDependency on `"@babel/core": "8.0.0-alpha.2"`
- `@babel/preset-env` in the monorepo has a dependency on `babel-plugin-polyfill-corejs2@0.0.0-condition-1814e8` package
- `babel-plugin-polyfill-corejs2@0.0.0-condition-1814e8` has a `peerDependency` on `@babel/core: "*"`
- `babel-plugin-polyfill-corejs2@0.0.0-condition-1814e8` has an aliased dependency `babel-plugin-polyfill-corejs2-BABEL_8_BREAKING-false": "npm:babel-plugin-polyfill-corejs2@^0.4.5`
- `@babel/preset-env` on npm has a dependency on `babel-plugin-polyfill-corejs2@^0.4.5`
- `babel-plugin-polyfill-corejs2@^0.4.5` (and thus its alias `babel-plugin-polyfill-corejs2-BABEL_8_BREAKING-false`) has a peerDependency on `@babel/core: "^7.4.0 || ^8.0.0-0 <8.0.0"`
- `babel-plugin-polyfill-corejs2@^0.4.5` (and thus its alias `babel-plugin-polyfill-corejs2-BABEL_8_BREAKING-false`) has a dependency on `@babel/helper-define-polyfill-provider` (note: this is not a monorepo package, but it's from npm)
- `@babel/helper-define-polyfill-provider` has a peerDependency on `@babel/core: "^7.4.0 || ^8.0.0-0 <8.0.0"`, and actually loads it at runtime
- All `@babel/preset-env`s have a dependency on `babel-plugin-polyfill-corejs3@^0.8.3`
- `babel-plugin-polyfill-corejs3@0.8.3` has a peerDependency on `@babel/core: "^7.4.0 || ^8.0.0-0 <8.0.0"` and a dependency on `@babel/helper-define-polyfill-provider`

This is the generated `node_modules` layout:
```
- node_modules/
  - @babel/core@8.0.0-alpha.2
  - @babel/preset-env@8.0.0-alpha.2
  - @babel/helper-define-polyfill-provider@0.4.2
  - babel-plugin-polyfill-corejs2@0.4.2
  - babel-plugin-polyfill-corejs2-BABEL_8_BREAKING-false (babel-plugin-polyfill-corejs2@0.4.2)
  - babel-plugin-polyfill-corejs2@0.8.3
- packages/
  - @babel/core
    - node_modules/
      - @babel/preset-env (symlink to the monorepo @babel/preset-env package)
  - @babel/preset-env
    - node_modules/
      - @babel/core (symlink to the monorepo @babel/core package)
      - @babel/helper-define-polyfill-provider@0.4.2
      - babel-plugin-polyfill-corejs2@0.0.0-condition-1814e8
      - babel-plugin-polyfill-corejs3@0.8.3
```

Thus `@babel/preset-env` (the version in the monorepo) loads `babel-plugin-polyfill-corejs2@0.0.0-condition-1814e8`, which then loads `babel-plugin-polyfill-corejs2-BABEL_8_BREAKING-false`, which then loads `@babel/helper-define-polyfill-provider@0.4.2`, which then loads `@babel/core@8.0.0-alpha.2`. However, `@babel/preset-env` from the monorepo provides `@babel/core` from the monorepo for the `peerDependency`, and it should be propagated.

I would expect a layout like this one:
```diff
  - node_modules/
    - @babel/core@8.0.0-alpha.2
    - @babel/preset-env@8.0.0-alpha.2
    - @babel/helper-define-polyfill-provider@0.4.2
    - babel-plugin-polyfill-corejs2@0.4.2
-   - babel-plugin-polyfill-corejs2-BABEL_8_BREAKING-false (babel-plugin-polyfill-corejs2@0.4.2)
    - babel-plugin-polyfill-corejs2@0.8.3
  - packages/
    - @babel/core
      - node_modules/
        - @babel/preset-env (symlink to the monorepo @babel/preset-env package)
    - @babel/preset-env
      - node_modules/
        - @babel/core (symlink to the monorepo @babel/core package)
        - @babel/helper-define-polyfill-provider@0.4.2
        - babel-plugin-polyfill-corejs2@0.0.0-condition-1814e8
+       - babel-plugin-polyfill-corejs2-BABEL_8_BREAKING-false (babel-plugin-polyfill-corejs2@0.4.2)
        - babel-plugin-polyfill-corejs3@0.8.3
```

so that the two different `@babel/preset-env` version will cause the loading of two copies of `@babel/helper-define-polyfill-provider` with two different versions of its `@babel/core` peer dependency.

### To reproduce

Hahahahah lol, feel free to tell me that this plus the description above is not enough and that it's impossible to try working on a fix.

Unfortunately, `babel-plugin-polyfill-corejs2@0.0.0-condition-1814e8` is not on npm but it's generated by a yarn plugin with a custom fetcher. I could try publishing it to npm if that would help debugging the issue.

You can reproduce the issue by cloning [this Babel branch](https://github.com/babel/babel/pull/15838) and running `yarn install` in it. It uses [this version](https://github.com/nicolo-ribaudo/yarn-plugin-conditions/tree/peers) of our custom fetcher.

### Environment

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M2
  Binaries:
    Node: 20.5.0 - /private/var/folders/bg/d5r9tspx5hn87zp52mcl82dh0000gn/T/xfs-ec7ccaa4/node
    Yarn: 3.6.2 - /private/var/folders/bg/d5r9tspx5hn87zp52mcl82dh0000gn/T/xfs-ec7ccaa4/yarn
    npm: 9.8.0 - /usr/local/bin/npm
```

### Additional context

I would also be happy with just a workaround if you have any idea.

**Comment by larixer** [comment]
1. In case of node_modules workspace peer dependencies has fundamental limitation, since the node_modules resolution tries first the workspace directory and the tries to lookup dependencies in the directories higher on the filesystem than this directory. Consider if the supplier of the peer dependency is another workspace in a sibling directory, Node.js will never find this dependency since it is not located higher up in the filesystem hierarchy. Hence in case of node_modules peer dependencies support is limited for workspaces, the workspace peer dependencies must be either provided by the dependencies/devDependencies of the same workspace or by the workspaces higher up in the directory tree. This is how the Yarn Classic work as well.

2. As for your case, if you rely on workspace peer deps you are basically on your own, still you can arrange the needed layout. You can add alias pointed to some dummy package or `link:` to the root workspace for the package `babel-plugin-polyfill-corejs2-BABEL_8_BREAKING-false` to keep this name on the root level and prevent package manager from hoisting it from `packages/babel-preset-env/node_modules`

**Comment by nicolo-ribaudo** [comment]
Thanks for the workaround :)

**Comment by nicolo-ribaudo** [comment]
Note that in my case the supplier of the peer dependencies only depends on packages from npm — the peer dependency is not expected to be threaded through multiple workspace packages.

**Comment by larixer** [comment]
@nicolo-ribaudo Hold on, I will check...

**Comment by larixer** [comment]
@nicolo-ribaudo Could you double check if your conditions plugin generates peerDependencies field, because what I see in the input to the nm linker misses peerDependencies, hence nm linker does not know about them:
```json
{
  packageLocation: '/home/victor/.yarn/berry/cache/babel-plugin-polyfill-corejs2-condition-5176a1d865-8.zip/node_modules/babel-plugin-polyfill-corejs2/',
  packageDependencies: Map(2) {
    'babel-plugin-polyfill-corejs2' => 'condition:BABEL_8_BREAKING?:^0.4.5(peer:@babel/core)#1814e8',
    'babel-plugin-polyfill-corejs2-BABEL_8_BREAKING-false' => [
      'babel-plugin-polyfill-corejs2',
      'virtual:5176a1d865ad0973d82d44daa51eaad78c352cfd0d85add2561e6dbccc7858bd523c9b0245dadce21bd966f3afad5df9563ed28831bcc757449fe62d60be7daa#npm:0.4.5'
    ]
  },
  packagePeers: Set(0) {},
  linkType: 'HARD',
  discardFromLookup: false
}
```

**Comment by nicolo-ribaudo** [comment]
It generates this `./packages/babel-preset-env/node_modules/babel-plugin-polyfill-corejs2/package.json`:
```json
{
  "version": "0.0.0-condition-1814e8",
  "dependencies": {
    "babel-plugin-polyfill-corejs2-BABEL_8_BREAKING-false": "npm:babel-plugin-polyfill-corejs2@^0.4.5"
  },
  "peerDependencies": {
    "@babel/core": "*"
  }
}
```

Make sure to use the branch from https://github.com/babel/babel/pull/15838, since it's the one with the updated yarn plugin that supports generating peerDependencies.

**Comment by larixer** [comment]
@nicolo-ribaudo Yep, I mean the problem with missing peerDependencies is during resolution, not in manifest.

**Comment by nicolo-ribaudo** [comment]
Ohh, I assumed Yarn got the list from peer dependencies and dependencies from the fetched manifest. Thank you, sorry for the confusion 🤦

**Comment by nicolo-ribaudo** [comment]
Fixed (https://github.com/nicolo-ribaudo/yarn-plugin-conditions/commit/08367764aab1bff0402631f6137d1e41e6f46d59) and it works now, thank you :)
