### ISSUE TITLE
[Bug?]: Sherlock for Yarn Broken

### ISSUE THREAD

**Issue by jacoboneill** [yarnpkg/berry#5709]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Made a issue #5708. When opened I got an email saying that sherlock failed.

### To reproduce

Make an issue

### Environment

```shell
N/A
```

### Additional context

<img width="658" alt="Screenshot 2023-08-31 at 20 05 53" src="https://github.com/yarnpkg/berry/assets/41302054/e9b44783-8d83-4992-8deb-cde2a4a19320">

**Comment by jakub-g** [comment]
Last good exec was Jun 23

https://github.com/yarnpkg/berry/actions/workflows/sherlock-workflow.yml?query=is%3Asuccess
