### ISSUE TITLE
[Feature] Add Homebrew Support

### ISSUE THREAD

**Issue by jacoboneill** [yarnpkg/berry#5714]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

As a developer on Mac, I like to install all my software via Homebrew. You can currently install Yarn 1.x via Homebrew however there is no way to install Yarn 3.x using Homebrew. This is frustrating when I move between fresh machines often.

**Describe the solution you'd like**

Have Yarn 3.x (Berry) added to the Homebrew tool.

**Describe the drawbacks of your solution**

Can't see any as it is done with the older version.

**Comment by arcanis** [comment]
Modern releases are installed via Corepack. We have no plans to provide officials releases through Homebrew.
