### ISSUE TITLE
[Bug] fs callbacks should give null instead of undefined?

### ISSUE THREAD

**Issue by jdmota** [yarnpkg/berry#572]
**Describe the bug**

I suspect `undefined` here should be replaced by `null`.

https://github.com/yarnpkg/berry/blob/677c3c8cde08cc6b16bcb25de737f9e4cb3fd6a9/packages/yarnpkg-fslib/sources/index.ts#L127-L133

It causes incorrect behaviour in `@nodelib/fs.stat` which causes an exception in `fast-glob`, for example.

Although I'm not sure if NodeJS always gives `null` if no error exists or if in some methods, we can get `undefined`... At least with `stat`, it is not following the native `fs.stat` behaviour.

**To Reproduce**

https://github.com/jdmota/yarn-pnp-bug

**Environment**

 - OS: Windows
 - Node version: v12.11.1
 - Yarn version: 2.0.0-rc.12

**Comment by arcanis** [comment]
Indeed - I was sure the first parameter was `undefined`, but it's in fact `null`. Would you be open to submitting a PR?

**Comment by jdmota** [comment]
Sure!
