### ISSUE TITLE
Typescript classes that use extends are missing base types

### ISSUE THREAD

**Issue by gkaskonas** [yarnpkg/berry#5760]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I have a class that extends another class in one workspace. After creating a package I import that class into another workspace. I expect typescript to be aware of both class types and base class types but its not. It is only aware of the class types.

It worked fine on v1

### To reproduce

Workspace A
```
export class MyStack extends Stack {
  constructor(scope: Construct) {
    super(scope, "MyStack");
  }

  public var = "1";
}
```

Workspace B
```
const app = new App();
const stack = new MyStack(app);

stack.stackName should be available but its not
```
This is using aws-cdk-lib

### Environment

```shell
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 20.5.0 - /private/var/folders/3b/3_jc0fgs567653nbsjn2pxyh0000gn/T/xfs-2d439acc/node
    Yarn: 4.0.0-rc.51 - /private/var/folders/3b/3_jc0fgs567653nbsjn2pxyh0000gn/T/xfs-2d439acc/yarn
    npm: 9.8.0 - /opt/homebrew/bin/npm
```

**Comment by merceyz** [comment]
Please provide a cloneable reproduction, from the steps you've provided we might not get the same setup as you.
