### ISSUE TITLE
[Bug?]: yarnpkg.com has incorrect status for url package regarding types

### ISSUE THREAD

**Issue by jason-ha** [yarnpkg/berry#5761]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

From https://yarnpkg.com/package?q=url&name=url there is statement that
  Types are available via [@types/url](https://yarnpkg.com/package?q=url&name=%40types%2Furl)

However following link, result is:
This page crashed
Try again
Failed to fetch

### To reproduce

Navigate to https://yarnpkg.com/package?q=url&name=url
Observe positive types available status
Follow that link

### Environment

```shell
Browser: Chromium
```

### Additional context

Happy to file elsewhere, but this was closest place I could find to post.

**Comment by bharathkalyans** [comment]
* I don't think there's any problem with the documentation.
* The problem might be that the server can't serve this endpoint, or may be the files arent present for this endpoint.
