### ISSUE TITLE
[Bug?]: Yarn v>=3.6.2 crashes when the `yarn.lock` file contains a dependency whose `bin` key references a directory

### ISSUE THREAD

**Issue by Vages** [yarnpkg/berry#5766]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

`yarn run` crashes before the script starts running whenever there is any dependency in `yarn.lock` whose `bin` object contains one or more directories. I have found that directories make their way into `bin` when the the directory listed in the dependency’s `directories.bin` contains subdirectories (such as with `jsbarcode`)

This has been the case since Yarn v3.6.2 and is still the case in Yarn v3.6.4. I suspect that 6256fdd7345429dcccbe356184ad291e90047ec3 introduced the bug.

This could be fixed by
- skipping any `bin` entry found to be a directory (my preferred solution as of this writing)
- excluding directories from being added to`bin`
- (all of the above)

### To reproduce

I have created a repo with a thorough description at https://github.com/Vages/yarn-directories-bin-demo. 

An even more minimal example is creating an empty directory with the following `package.json` file:

```json
{
  "packageManager": "yarn@3.6.4",
  "scripts": {
    "baz": "yarn node -e \"console.log('foo')\""
  },
  "dependencies": {
    "jsbarcode": "^3.11.5"
  }
}
```

Run `yarn install && yarn set version 3.6.4 && yarn baz`. This should end with an error that starts with `Internal Error: EISDIR: illegal operation on a directory`. This is due to `jsbarcode` having directories listed in `bin`.

If you run the example above, but skip the `yarn set version 3.6.4` statement, things run all right. (I have not yet figured out why.)

### Environment

```shell
System:
    OS: macOS 14.0
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 18.18.0 - /private/var/folders/sn/5f6d7wg57fs_wvwlhd5vt9980000gn/T/xfs-e5081abe/node
    Yarn: 3.6.4 - /private/var/folders/sn/5f6d7wg57fs_wvwlhd5vt9980000gn/T/xfs-e5081abe/yarn
    npm: 9.8.1 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.6.3 - ~/.asdf/shims/pnpm
```

**Comment by Vages** [comment]
I would like to try my hand at fixing this bug, but I would like feedback from a maintainer on which solution I should pick.

**Comment by daniluk4000** [comment]
Still an issue in v4 =(

**Comment by Vages** [comment]
I’m closing this. JsBarcode fixed the bug on their side (https://github.com/lindell/JsBarcode/issues/438), and I know of no other packages that cause this error.

**Comment by StamTso** [comment]
I believe this should re-open because it is affecting other packages as well, I encountered this issue with eslint and typescript while using yarn@3.6.4.
