### ISSUE TITLE
Unknown Syntax Error: Command not found; While running yarn workspaces foreach command

### ISSUE THREAD

**Issue by sadashiv-sumasoft** [yarnpkg/berry#5767]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

My package.json file contain the follwing script:
"deploy-all": "yarn workspaces foreach -p run deploy"

I have set workspace to only for one for now:
 "workspaces": [
    "./alerts-api"
  ],
  
  When i hit yarn run deploy-all command from the root of my project it is throwing below error:
  
  Unknown Syntax Error: Command not found; did you mean:
$ yarn workspaces list [--since] [-R,--recursive] [--no-private] [-v,--verbose] [--json]
While running workspaces foreach -p run deploy

The only workspaces command running on machine is yarn workspaces list.

### To reproduce

-

### Environment

```shell
System:
Windows

Yarn version:
3.6.4
Npm version:
8.3.1
Node version:
16.16.0
```

**Comment by merceyz** [comment]
To quote the docs:

> To use this command, first install the [workspace-tools](https://github.com/yarnpkg/berry/blob/HEAD/packages/plugin-workspace-tools/README.md) plugin: yarn plugin import workspace-tools
https://v3.yarnpkg.com/cli/workspaces/foreach/

**Comment by sadashiv-sumasoft** [comment]
@merceyz  Thank you for the quick response. 
 I had actually tried that but even after importing plugin my command is getting execute within 0.0 sec and produces nothing.
 The command I want to run is:
 yarn workspaces foreach -p run serverless deploy
 
 Do you have any idea how could we make this work?

**Comment by trusktr** [comment]
> To quote the docs:
> 
> > To use this command, first install the [workspace-tools](https://github.com/yarnpkg/berry/blob/HEAD/packages/plugin-workspace-tools/README.md) plugin: yarn plugin import workspace-tools
> > https://v3.yarnpkg.com/cli/workspaces/foreach/

There's no mention of needing to add a plugin (workspace-tools) here:

https://yarnpkg.com/cli/workspaces/foreach
