### ISSUE TITLE
[Feature] enhance yarn berry boostrap with CDN

### ISSUE THREAD

**Issue by loynoir** [yarnpkg/berry#5775]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

https://github.com/yarnpkg/berry/tree/%40yarnpkg/cli/3.6.4/packages/plugin-workspace-tools

```sh
$ yarn plugin import \
    https://github.com/yarnpkg/berry/raw/@yarnpkg/cli/3.6.4/packages/plugin-workspace-tools/bin/@yarnpkg/plugin-workspace-tools.js
```

- github sometimes slow

- or too long for human to read

- or not clear for plugin version management

**Describe the solution you'd like**

enhance yarn berry boostrap with CDN.

```sh
$ yarn plugin import \
    https://cdn.jsdelivr.net/npm/@yarnpkg/plugin-workspace-tools@3.1.6
```

```sh
$ yarn plugin import \
    https://esm.run/@yarnpkg/plugin-workspace-tools@3.1.6
```

```sh
$ yarn plugin import \
    https://esm.sh/@yarnpkg/plugin-workspace-tools@3.1.6
```

- There are multiple reliable npm CDN, so you can at least find one CDN which is fast.

- with CDN, human readable url

- with CDN, easier version management

**Describe the drawbacks of your solution**

Currently, `@yarnpkg/cli` and `@yarnpkg/plugin-XXX` does not publish as standalone file.

I suggest, `@yarnpkg/cli` and `@yarnpkg/plugin-XXX` package.json

```json
  "main": "./path/to/bundle.js",
  "exports": {
    ".": "./path/to/bundle.js",
    "./not-bundle": "./path/to/not-bundle.js",
  },
  "scripts": {
    "prepack": "bundle-source-code-as-standalone --output ./path/to/bundle.js"
```

**Describe alternatives you've considered**

```sh
$ NPM_CONFIG_REGISTRY=https://registry.npmjs.org
$
$ yarn plugin import \
    b${NPM_CONFIG_REGISTRY}/@yarnpkg/plugin-workspace-tools/-/plugin-workspace-tools-3.1.6.tgz
```

**Comment by arcanis** [comment]
Future versions ship the plugins by default, so this shouldn't be a concern.
