### ISSUE TITLE
[Bug]: `yarn npm publish` fails with "New versions must be valid semver" 

### ISSUE THREAD

**Issue by milesj** [yarnpkg/berry#5785]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When setting the version to `1.16.0-nightly.20231011+0324`, which includes a preid and build metadata, `yarn npm publish` fails with "New versions must be valid semver.". 

This is definitely valid semver.

### To reproduce

```json
{
  "name": "package",
  "version": "1.16.0-nightly.20231011+0324"
}
```

BTW, the sherlock link in the form does not work.

### Environment

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 20.8.0 - /private/var/folders/ml/41y5w4hx6fs1hqk57hd334y40000gn/T/xfs-b653288e/node
    Yarn: 3.6.3 - /private/var/folders/ml/41y5w4hx6fs1hqk57hd334y40000gn/T/xfs-b653288e/yarn
    npm: 9.6.2 - ~/.proto/bin/npm
    pnpm: 8.9.0 - ~/.proto/bin/pnpm
  npmPackages:
    jest: ^29.7.0 => 29.7.0
```

### Additional context

I'm trying to setup a nightly release using this semver pattern. You can see it here: https://github.com/moonrepo/moon/actions/runs/6477449087/job/17588025765

Expand "Publish npm packages". Right now a failed publish doesn't fail the job.

**Comment by arcanis** [comment]
I strongly suggest this error comes from the npm registry itself, as Yarn doesn't even include it anywhere in its bundle.

**Comment by arcanis** [comment]
In fact, that's even what your logs say; HTTP 400, ie server error:

```
➤ YN0035: New versions must be valid semver.
➤ YN0035:   Response Code: 400 (Bad Request)
➤ YN0035:   Request Method: PUT
➤ YN0035:   Request URL: https://registry.yarnpkg.com/@moonrepo%2fcli
```

**Comment by milesj** [comment]
🤔 

Would be nice to know what about the version is actually invalid. I suppose I'll try another format.
