### ISSUE TITLE
[Bug]: Failure behavior is different in Windows than in Linux and macOS

### ISSUE THREAD

**Issue by trusktr** [yarnpkg/berry#5796]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

In this build:

https://github.com/lume/lume/actions/runs/6541284416

In the Windows build, you'll find this output:

```
'symlink-dir' is not recognized as an internal or external command,
```

My pkg.json script runs yarn as `corepack yarn install || echo ""` to prevent failure, which is why the builds keep going after an error.

But as you can see in the macOS build, it succeeds. In macOS, yarn install fails with a checksum error (the other issue I opened), however yarn still puts everything in place, and I took advantage of this by placing `|| echo ""` in the script so I could keep going (at least for now).

It also work in Linux (but that build was canceled).

However, it seems that Yarn in Windows has a different behavior in that, after a failure, it does not have all the packages in place, so when the Windows build continue, it experiences the subsequent error with `'symlink-dir'`.

This shows that there's some difference in Yarn's behavior in Windows, compared to Linux and macOS, when it comes to installing dependencies and handling errors.

### To reproduce

- Clone that repo,
- check out [the commit](https://github.com/lume/lume/commit/e6f1e0818aa7660fbebc2710a169e8c37dfb1fd1) from that build,
- run `git submodule update --init` to get the submodules, 
- run `npm run link && npm run build` (with npm)

That should work fine in macOS and Linux, but fail in Windows PowerShell

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   
  Binaries:
    Node: 20.5.0 - ~\AppData\Local\Temp\xfs-bcfdee5c\node.CMD
    Yarn: 3.6.4 - ~\AppData\Local\Temp\xfs-bcfdee5c\yarn.CMD 
    npm: 9.8.0 - D:\Program Files (x86)\nodejs\npm.CMD
```

### Additional context

yarnrc:

```
nodeLinker: node-modules
nmHoistingLimits: workspaces
checksumBehavior: ignore
```

**Comment by clemyan** [comment]
> In macOS, yarn install fails with a checksum error
Does it? I see `Done with warnings in 6m 7s` in mac build logs

**Comment by trusktr** [comment]
Sorry, it was late, I may have mean Windows: yarn failed with the `checksum` error, but since I used `|| echo ""` to make it keep going, it failed later with missing dependency due to the Yarn install having previously failed.

**Comment by trusktr** [comment]
I'm going to close this one, I think was just very tired late last night. Really trying to get migrated from Lerna to Yarn, but need to solve the other issues.
