### ISSUE TITLE
[Bug?]: getRecursiveWorkspaceChildren: Range Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by trusktr** [yarnpkg/berry#5799]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I get this:

```
PS D:\src\lume+lume> yarn workspaces foreach run build 
Range Error: Maximum call stack size exceeded
    at Set.values (<anonymous>)
    at Qh.getRecursiveWorkspaceChildren (C:\Users\trusktr\AppData\Local\node\corepack\yarn\3.6.4\yarn.js:435:8314)
    at Qh.getRecursiveWorkspaceChildren (C:\Users\trusktr\AppData\Local\node\corepack\yarn\3.6.4\yarn.js:435:8389)
    at Qh.getRecursiveWorkspaceChildren (C:\Users\trusktr\AppData\Local\node\corepack\yarn\3.6.4\yarn.js:435:8389)
    ... repeats ...
```

### To reproduce

This repo:

```
git clone git@github.com:lume/lume.git
cd lume
git checkout 588f4e72ccaa14f92422e83839093f06c72413c8
git submodule update --init
yarn workspaces foreach run build
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   
  Binaries:
    Node: 20.5.0 - ~\AppData\Local\Temp\xfs-bcfdee5c\node.CMD
    Yarn: 3.6.4 - ~\AppData\Local\Temp\xfs-bcfdee5c\yarn.CMD 
    npm: 9.8.0 - D:\Program Files (x86)\nodejs\npm.CMD
```

### Additional context

Any ideas what can cause this? Is it two packages that depend on each other?

**Comment by clemyan** [comment]
https://github.com/lume/lume/blob/588f4e72ccaa14f92422e83839093f06c72413c8/package.json#L17-L21

You don't need to declare the root as a workspace. The `workspace` field in `package.json` is for listing *children* workspaces

**Comment by trusktr** [comment]
Indeed, that was it! But now I get these same sort of issues in each workspace when yarn tries to run build:

- https://github.com/yarnpkg/berry/issues/5800

**Comment by arcanis** [comment]
Original issue was answered

**Comment by merceyz** [comment]
This seems like a valid bug that we should fix so I'll reopen.
