### ISSUE TITLE
[Feature] [Document] How to calculate pnp zip hash part?

### ISSUE THREAD

**Issue by loynoir** [yarnpkg/berry#5806]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

As far as I know, pnp zip are stored in format of `${cacheFolder}/${packageName}-npm-${version}-${hash}.zip`

I want a **light weight** pnp zip resolver.

And `.pnp.cjs` and `.pnp.loader.mjs` are 648K, are overkilled.

And they seems to be generated from `yarn.lock`.

I try to find out how the hash part is generated, but no luck.

To be honest, I not a big fan of current `pnpapi` design `require('module').findPnpApi`.

As far as I know, everything need to be under `--require /path/to/.pnp.cjs --experimental-loader /path/to/.pnp.loader.mjs`.

**Describe the solution you'd like**

1. Document on how yarn berry calculate the hash part.

```ts
function createZipNameResolver(parsedYarnLock: Record<string, any>) {
  return (packageName: string, version: string)=> {
    // TODO
    const hash = ''

    return `${packageName}-npm-${version}-${hash}.zip`
  }
}
```

2. Document on how to use `pnpapi` outside of `--require /path/to/.pnp.cjs --experimental-loader /path/to/.pnp.loader.mjs` context.

**Describe the drawbacks of your solution**

**Describe alternatives you've considered**

Document on how to build `yarn-X.Y.Z.cjs` without minify, or installing using `npm` install as normal module?

**Comment by clemyan** [comment]
> How to calculate pnp zip hash part?

The cache zip path is generated here

https://github.com/yarnpkg/berry/blob/a8ea92828badb4b6a1edddae18b0a163b0c4d2c5/packages/yarnpkg-core/sources/Cache.ts#L179-L194

Not directly related to pnp though

----

> Document on how to build yarn-X.Y.Z.cjs without minify

Run [`yarn bulid:cli --no-minify`](https://yarnpkg.com/advanced/contributing#testing-your-code) in this repo, or [`yarn set version from sources --no-minify`](https://yarnpkg.com/cli/set/version/from/sources) in a project

----

Not sure what you are asking in the rest of your post

**Comment by loynoir** [comment]
If anyone reach here, the normal case pnp zip filename would be simplify as

```js
> `${ctx.name}-npm-${ctx.version}-${sha512(sha512(ctx.name),`npm:${ctx.version}`).slice(0,10)}-${ctx.sha512.slice(0,10)}.zip` === expected
true
```
