### ISSUE TITLE
[Bug?]: yarn 4.x `yarn workspaces foreach` does not take `--all` by default

### ISSUE THREAD

**Issue by indooorsman** [yarnpkg/berry#5817]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

Per information in https://yarnpkg.com/cli/workspaces/foreach#options :
> If -A,--all is set, Yarn will run the command on all the workspaces of a project. **_This is the default behavior._**

But in fact yarn 4.x would throw error by running `yarn workspaces foreach run build` : 
``` bash
$ yarn workspaces foreach run build
Usage Error: Invalid option schema: missing at least one property from "all", "recursive", "since", or "worktree"
```

### To reproduce

In any workpace with yarn 4.x:
``` bash
$ yarn workspaces foreach run build
Usage Error: Invalid option schema: missing at least one property from "all", "recursive", "since", or "worktree"
```

### Environment

```shell
System:
    OS: macOS 13.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 20.8.0 - /private/var/folders/qd/qpdt2c0s2yn3cgyy8zww0w240000gn/T/xfs-38e424bb/node
    Yarn: 4.0.0 - /private/var/folders/qd/qpdt2c0s2yn3cgyy8zww0w240000gn/T/xfs-38e424bb/yarn
    npm: 10.1.0 - ~/Library/Caches/fnm_multishells/14343_1698027514115/bin/npm
```

**Comment by indooorsman** [comment]
Just open a pull request for this issue: https://github.com/yarnpkg/berry/pull/5818

**Comment by wojtekmaj** [comment]
This is actually a doc issue. In CHANGELOG.md, we can read:

> yarn workspaces foreach now requires one of --all, --recursive, --since, or --worktree to be explicitly specified; the previous default was --worktree, but it was rarely what users expected.
