### ISSUE TITLE
[Bug?]: npm audit --json output vulnerabilities that are in --ignore

### ISSUE THREAD

**Issue by xfournet** [yarnpkg/berry#5830]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When using both --json and --ignore, the json output include the vulnerabilities that are in the ignore list

### To reproduce

```json
{
  "packageManager": "yarn@4.0.0",
  "dependencies": {
    "nth-check": "1.0.2"
  }
}
```
`yarn npm audit --ignore 1093882 --json`
output
```json
{"nth-check":[{"id":1093882,"url":"https://github.com/advisories/GHSA-rp65-9cf3-cjxr","title":"Inefficient Regular Expression Complexity in nth-check","severity":"high","vulnerable_versions":"<2.0.1","cwe":["CWE-1333"],"cvss":{"score":7.5,"vectorString":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"}}]}
```

while
```yarn npm audit --ignore 1093882```
output
`➤ YN0001: No audit suggestions`

NB: in both case (with or without --json) the command exit code takes correcly into account the --ignore parameters

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  Binaries:
    Node: 20.8.1 - C:\Users\xxxxx\AppData\Local\Temp\xfs-2cd2ed2f\node.CMD
    Yarn: 4.0.0 - C:\Users\xxxxx\AppData\Local\Temp\xfs-2cd2ed2f\yarn.CMD
    npm: 10.1.0 - D:\scoop\apps\nodejs\current\npm.CMD
```

**Comment by wojtekmaj** [comment]
Duplicate of #5824?

**Comment by arcanis** [comment]
No, those are two separate problems.

**Comment by arcanis** [comment]
Will be fixed by https://github.com/yarnpkg/berry/pull/5833 - you can try it with:

```
yarn set version from sources --branch 5833
```
