### ISSUE TITLE
[Bug?]: [docs] dead link to "release workflow" in @yarnpkg/plugin-version README

### ISSUE THREAD

**Issue by wojtekmaj** [yarnpkg/berry#5832]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

https://www.npmjs.com/package/@yarnpkg/plugin-version has a "release workflow" link that leads to https://yarnpkg.com/features/release-workflow which is 404

### To reproduce

n/a

### Environment

```shell
n/a
```

**Comment by wojtekmaj** [comment]
Another place: https://yarnpkg.com/cli/version#details

**Comment by cuevana8** [comment]
+1..[.](https://github.com/flslib/fl-studio-cracked)[@@@](https://github.com/yarnpkg/berry/issues/5832#issue-1958657300)

**Comment by trivikr** [comment]
The release workflow was on legacy gatsby website at https://github.com/yarnpkg/berry/blob/526caf9e7172218d3b300fbf32fb51d7442aff0d/packages/gatsby/content/features/release-workflow.md

It would have been deleted when Gatsby was removed in https://github.com/yarnpkg/berry/pull/5742
