### ISSUE TITLE
[Bug?]: Sherlock is not found

### ISSUE THREAD

**Issue by artola** [yarnpkg/berry#5837]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

The link leads to a missing page: https://yarnpkg.com/advanced/sherlock

![image](https://github.com/yarnpkg/berry/assets/11500763/640662ec-df36-4c67-a65f-b1960f311ff0)

### To reproduce

Visit: https://yarnpkg.com/advanced/sherlock

### Environment
n/a

**Comment by wojtekmaj** [comment]
Link where?

**Comment by artola** [comment]
> Link where?

Template for new Bug issue: https://github.com/yarnpkg/berry/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml&title=%5BBug%3F%5D%3A+

**Comment by trivikr** [comment]
The sherlock was part of legacy Gatsby website in the past at https://github.com/yarnpkg/berry/blob/79296291db08039856347f54c29ca341015385d6/packages/gatsby/content/advanced/sherlock.md

The link probably broke when Gatsby content was removed in https://github.com/yarnpkg/berry/pull/5742?

**Comment by trivikr** [comment]
I created PR to re-add sherlock page https://github.com/yarnpkg/berry/pull/5858

The playground returns "Internal Server Error" though.
I've created a bug report for it at https://github.com/yarnpkg/berry/issues/5859
