### ISSUE TITLE
[Bug?]: pnpm is not listed as an option in config for nodeLinker

### ISSUE THREAD

**Issue by trivikr** [yarnpkg/berry#5847]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

The `pnpm` option is not listed as an option in config for nodeLinker

It is listed in documentation https://yarnpkg.com/configuration/yarnrc#nodeLinker

### To reproduce

```console
$ yarn --version
4.0.0

$ yarn config nodeLinker
└─ nodeLinker
   ├─ Description: The linker used for installing Node packages, one of: "pnp", "node-modules"
   ├─ Source: <default>
   └─ Value: 'pnp'
```

### Environment

```shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.18.0 - /private/var/folders/42/54jl1_3x4hz06cf7bc_kzd4h0000gn/T/xfs-988ceb7a/node
    Yarn: 4.0.0 - /private/var/folders/42/54jl1_3x4hz06cf7bc_kzd4h0000gn/T/xfs-988ceb7a/yarn
    npm: 9.8.1 - ~/Library/Caches/fnm_multishells/39477_1698170213522/bin/npm
```

**Comment by arcanis** [comment]
It's not an enum in the yarnrc.json because, technically, plugins may add different values for this field (and the yarnrc.json is used by some IDE / extensions for actual `.yarnrc.yml` content validation).
