### ISSUE TITLE
[Feature] Documeation for yarn 3 installtion 

### ISSUE THREAD

**Issue by riginoommen** [yarnpkg/berry#5865]
```
    - npm i -g corepack && corepack enable && corepack prepare yarn@stable --activate
```

i am expecting a yarn 3 installation in stable tag how can I expect yarn 3 should be installed specifically currently yarn 4 is getting installaed

**Comment by arcanis** [comment]
The latest stable release is 4.0.0. Use `corepack prepare yarn@3.6.4` if you wish the last 3.x release.

**Comment by little-buddy** [comment]
<img width="565" alt="image" src="https://github.com/yarnpkg/berry/assets/30054881/a48853a9-dbed-4afc-8e7d-ebf9722847de">

it not work...
