### ISSUE TITLE
[Bug?]: `enableGlobalCache` is automatically set to `false` on migrating

### ISSUE THREAD

**Issue by JounQin** [yarnpkg/berry#5895]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

<img width="1753" alt="image" src="https://github.com/yarnpkg/berry/assets/8336744/750ff781-3860-4169-9d18-a4cafcea05ef">

The following are added into `.yamlrc.yml`, but I didn't notice these changes mentioned in the release note: https://yarnpkg.com/blog/release/4.0

```yaml
compressionLevel: mixed

enableGlobalCache: false
```

### To reproduce

N/A

### Environment

```shell
System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.18.2 - ~/tmp/xfs-5dcbb7f9/node
    Yarn: 4.0.1 - ~/tmp/xfs-5dcbb7f9/yarn
    npm: 9.8.1 - ~/Library/Caches/fnm_multishells/42780_1698647724002/bin/npm
  npmPackages:
    jest: ^29.6.4 => 29.6.4
```

**Comment by arcanis** [comment]
Since we changed the default settings in Yarn 4, Yarn automatically pins the old defaults when running the first install on a Yarn 3 project, so as to limit the amount of potentially breaking changes. You're free to remove those settings and re-run an install at your convenience.

**Comment by JounQin** [comment]
@arcanis Thanks for the clarification, should these default changes be mentioned in the release note? https://yarnpkg.com/blog/release/4.0
