### ISSUE TITLE
[Bug?]: unable to use `npx xxx` after v4: `Permission denied`

### ISSUE THREAD

**Issue by JounQin** [yarnpkg/berry#5906]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I have a global alias `alias cce="npx -p @alauda/custom-webpack cce"`, it runs well with or without `yarn` previously, it will reuse `node_modules/.bin/cce` as much as possible and fallback to temporary installation instead otherwise. It runs well with yarn v1/v2/v3 all together, but fails on v4 now.

I tried to use `yarn dlx`, but it seems it will always run in a new temporary environment instead of reusing `node_modules/.bin/cce`. I have no idea how to replace my previous alias.

### To reproduce

N/A

### Environment

```shell
System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.18.2 - ~/tmp/xfs-b120ae3c/node
    Yarn: 4.0.1 - ~/tmp/xfs-b120ae3c/yarn
    npm: 9.8.1 - ~/Library/Caches/fnm_multishells/82444_1698730702638/bin/npm
  npmPackages:
    jest: ^29.6.4 => 29.6.4
```

**Comment by arcanis** [comment]
Indeed, `yarn dlx` is exclusively for running a package after installing it from the registry (dlx = download and execute). If you wish to run a binary from your project (ie node_modules), you must call it with `yarn run`.

Yarn doesn't support doing either one or the other; we don't want to silently execute something coming from the network, so we expect users to explicitly call `yarn dlx` themselves should that be needed (but in general, adding the package to the dependencies is the preferred option).

**Comment by JounQin** [comment]
Is there any chance to cache `yarn dlx` results instead of reinstalling every time?

**Comment by arcanis** [comment]
> Is there any chance to cache yarn dlx results instead of reinstalling every time?

Perhaps; can you detail the use case where you need to make frequent enough calls to a binary, but not enough to make the tool a regular project dependency?

> And I'm a bit surprised by the error Permission denied caused by npx command

Yarn doesn't provide or maintain the `npx` command (that's an npm-specific command), so no idea what that is. Generally though, you can't mix and match package managers.

**Comment by JounQin** [comment]
> Perhaps; can you detail the use case where you need to make frequent enough calls to a binary, but not enough to make the tool a regular project dependency?

It is a regular project dependency, but I'd like to use it outside my source directory at the same time because the cli is frequently used, that's why I add an alias for my shell.

> Yarn doesn't provide or maintain the npx command (that's an npm-specific command), so no idea what that is.

Sure, understand. Maybe something changed in recent `npm` releases, I'll research deeper.

> Generally though, you can't mix and match package managers.

Yeah, but my case is that I want to use the cached temporary environment which `yarn dlx` does not support yet.

**Comment by JounQin** [comment]
It's weird that the error is just gone... No idea what's happening, close for now.

**Comment by wojtekmaj** [comment]
Might have been unrelated, rather related to CloudFlare outage which in turn caused npm registry outage.
