### ISSUE TITLE
[Feature] Possibility to turn off helloween pumpkins loader

### ISSUE THREAD

**Issue by pumano** [yarnpkg/berry#5907]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

Add possibility to turn off some unusual appearance for progress bars and etc (for example helloween pumpkins)

**Comment by merceyz** [comment]
See https://yarnpkg.com/configuration/yarnrc#progressBarStyle
