### ISSUE TITLE
[Bug?]: Yarn 4 is not reporting unsatisfied peer dependency

### ISSUE THREAD

**Issue by noahnu** [yarnpkg/berry#5923]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

In Yarn 3.6.4, installing `@opentelemetry/auto-instrumentations-web@npm:0.33.2` produces a warning about an unsatisfied peer dependency:

```
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @opentelemetry/auto-instrumentations-web@npm:0.33.2 [83915] doesn't provide zone.js (pb09f8), requested by @opentelemetry/instrumentation-user-interaction
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
```

In Yarn 4.0.1, there is no warning. In Yarn 3 I was using logFilters to escalate peer dependency warnings to errors.

### To reproduce

Can reproduce here: https://github.com/dbasilio/opentelemetry-peer-dep-repro

### Environment

```shell
System:
    OS: macOS 13.6
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.18.0 - /private/var/folders/5m/4x2x5y6x5x5ck7rnpzq23dlc0000gn/T/xfs-45d45882/node
    Yarn: 4.0.1-git.20231102.hash-0ee6213 - /private/var/folders/5m/4x2x5y6x5x5ck7rnpzq23dlc0000gn/T/xfs-45d45882/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
```

### Additional context

Related issue in OpenTelemetry: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1767

**Comment by arcanis** [comment]
Indeed, we don't report anymore by default "unactionable" peer dependency warnings (ie those caused by third-party dependencies). There have been a couple of requests to add it back, perhaps behind a setting - that sounds reasonable.

**Comment by noahnu** [comment]
ah, I see the entry in the changelog:

> Unactionable warnings (node-gyp and transitive peer dependency errors) have been removed.

An option to configure this would be great. We depended on it for catching issues in internally published libraries alongside constraints. If there's already been interest or a feature request for this, I'll close this issue as it's not a "bug".

**Comment by noahnu** [comment]
Clarifying question: This does mean use of an unsatisfied peer dependency might only be caught at runtime (or bundling if using a bundler), right?

**Comment by clemyan** [comment]
How about reporting peer dependency warnings caused by third-party dependencies as an aggregate and re-implementing `yarn explain peer-requirements`?
