### ISSUE TITLE
[Bug?]: Documentation incorrect - Fail to install yarn

### ISSUE THREAD

**Issue by rune-hansen** [yarnpkg/berry#5932]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I have just tried to follow the documentation on how to install yarn for the first time on a fresh node installation - [yarn installation](https://yarnpkg.com/getting-started/install)

Issues:
- **'corepack enable'** has to run from an elevated command prompt. This is not mentioned
- **'yarn init -2'** produces the below error
```
> Internal Error: ENOENT: no such file or directory, stat 'C:\Users\ext418\AppData\Local\node\corepack\yarn\4.0.1'
Error: ENOENT: no such file or directory, stat 'C:\Users\ext418\AppData\Local\node\corepack\yarn\4.0.1'
error Command failed.
Exit code: 1
Command: C:\Program Files\nodejs\node.exe
Arguments: C:\Program Files\nodejs\node_modules\corepack\dist\corepack.js yarn@stable init -2 --install=self
Directory: C:\Workspaces\Workspace_v2\Apps\aa\frontend
Output:

info Visit https://yarnpkg.com/en/docs/cli/init for documentation about this command.
```

I then ran **'yarn --version'** that returned '1.22.19'
The documentation then states that to update yarn to the lastest version I should run
```
yarn set version stable
yarn install
```
and that produces the following
```
Arguments: C:\Program Files\nodejs\node_modules\corepack\dist\corepack.js yarn@stable set version stable
Directory: C:\Workspaces\Workspace_v2\Apps\aa\frontendt 'C:\Users\ext2021418\AppData\Local\node\corepack\yarn\4.0.1'
Output:ENOENT: no such file or directory, stat 'C:\Users\ext2021418\AppData\Local\node\corepack\yarn\4.0.1'

info Visit https://yarnpkg.com/en/docs/cli/policies for documentation about this command.
```

After that fiasco I then tried the following, but all complained about the lack of the 4.0.1 directory in some form or another
```
corepack prepare yarn@stable --activate
yarn set version berry
```

### To reproduce

See above

### Environment

```shell
System:
  - Windows 10 22H2
Binaries:
  - node v20.8.1
  - npm v10.1.0
```

**Comment by arcanis** [comment]
As hinted by the output (`corepack.js` being the script crashing), this seems a Corepack issue unrelated to Yarn:

```
Arguments: C:\Program Files\nodejs\node_modules\corepack\dist\corepack.js yarn@stable set version stable
```

This error sounds strange though - it seems like you have a corrupted Corepack install. I'd suggest to `rm -rf C:\Users\ext418\AppData\Local\node\corepack`.

**Comment by hikarisakira** [comment]
> As hinted by the output (`corepack.js` being the script crashing), this seems a Corepack issue unrelated to Yarn:
> 
> ```
> Arguments: C:\Program Files\nodejs\node_modules\corepack\dist\corepack.js yarn@stable set version stable
> ```
> 
> This error sounds strange though - it seems like you have a corrupted Corepack install. I'd suggest to `rm -rf C:\Users\ext418\AppData\Local\node\corepack`.

Sorry but that doesn't help at all, the issue still happens in the latest version.
```
System:
  - Windows 10 22H2
Binaries:
  - node v20.11.1
  - npm v10.5.0
```
Issue: 
```
PS C:\Users\k861\Documents\GitHub\hikarisakira.me> corepack enable
PS C:\Users\k861\Documents\GitHub\hikarisakira.me> yarn init -2
Internal Error: ENOENT: no such file or directory, stat 'C:\Users\k861\AppData\Local\node\corepack\yarn\4.1.1'
Error: ENOENT: no such file or directory, stat 'C:\Users\k861\AppData\Local\node\corepack\yarn\4.1.1'
```

Hmm, I don't think this supposed to be happen when in a fresh installation.

**Comment by hatedMe** [comment]
@arcanis  @hikarisakira  Do you have a solution?
