### ISSUE TITLE
[Feature] Ability to install dependency without `@types/` package

### ISSUE THREAD

**Issue by JounQin** [yarnpkg/berry#5935]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

When I install `eslint` in a TypeScript project, `@types/eslint` is installed automatically, but actually `@types/eslint` is not quite useful for the project.

**Describe the solution you'd like**

A new option like `--no-auto-types`

**Describe the drawbacks of your solution**

N/A

**Describe alternatives you've considered**

Keep it as is and let the user remove `@types/` package manually

**Comment by merceyz** [comment]
You can turn it off with [`tsEnableAutoTypes: false`](https://yarnpkg.com/configuration/yarnrc#tsEnableAutoTypes) or if you only want it for the current command:
```sh
YARN_TS_ENABLE_AUTO_TYPES=false yarn add eslint
```

**Comment by JounQin** [comment]
@merceyz Thanks, I didn't found that previously. 🤣
