### ISSUE TITLE
[Case Study] AVA

### ISSUE THREAD

**Issue by tkamenoko** [yarnpkg/berry#594]
**What package is covered by this investigations?**

[AVA](https://github.com/avajs/ava)

**Describe the goal of the investigation**

AVA is a popular test runner for Nodejs. We should support other testing tools in addition to Jest.

**Investigation report**

example repo: https://github.com/tkamenoko/ava-berry

yarn: 2.0.0-rc.12

`yarn ava` shows this:

> Error loading ava.config.js
>
>file:///home/tkamenoko/develop/ava-berry/.pnp.js:1
>Error: The whole PnP file got strict-mode-ified, which is known to break (Emscripten libraries >aren't strict mode). This usually happens when the file goes through Babel.
>    at Object.<anonymous> (file:///home/tkamenoko/develop/ava-berry/.pnp.js:6:9)
>    at Generator.next (<anonymous>)
>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)

**Comment by stavalfi** [comment]
it's a blocker for me to use yarn2. is there any workaround?

**Comment by cspotcode** [comment]
The newest version of Ava removes built-in babel, so babel must be opted-into.  When using this new version, this issue goes away.
