### ISSUE TITLE
[Bug?]: `yarn workspaces foreach` causes per-package Volta node versions to be ignored

### ISSUE THREAD

**Issue by seansfkelley** [yarnpkg/berry#5973]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I have a Yarn monorepo that uses [Volta](https://volta.sh/) to manage disparate versions among the various packages (which exists for historical reasons). This largely works as expected, but one loophole is that `yarn workspaces foreach` will use one Node version for all packages.

This appears to be because of `foreach`'s feature where it puts a temp directory full of shims at the front of $PATH:

```sh
> yarn workspace my-workspace exec sh -c 'echo $PATH | cat "$(cut -d : -f 1)/node"'
#!/bin/sh
exec "/Users/<username>/.volta/tools/image/node/18.18.2/bin/node"  "$@"
```

(18.18.2 is the version of the monorepo's root package.)

However, I can force a re-resolve of the appropriate version by using an additional `volta run` invocation:

```sh
> yarn workspace my-workspace exec node --version
v18.18.2

> yarn workspace my-workspace exec volta run node --version
v16.18.1
```

(16.18.1 is the version declared in `volta.node` of this workspace's `package.json`.)

### To reproduce

Install [Volta](https://volta.sh/).

Root `package.json`:

```json
{ 
  "name": "root",
  "workspaces": {
    "packages": [
      "packages/*"
    ]
  },
  "volta": {
    "node": "18.18.2"
  },
}
```

nested workspace `packages/my-workspace/package.json`:

```json
{ 
  "name": "my-workspace",
  "volta": {
    "extends": "../../package.json",
    "node": "16.18.1"
  }
}
```

`yarn install` and then reproduce the issues with the commands outlined in the previous section.

### Environment

```shell
System:
    OS: macOS 13.6
    CPU: (12) arm64 Apple M2 Pro
  Binaries:
    Node: 18.18.2 - /private/var/folders/wg/zn78dyk51h5bvz0crq8x8w0h0000gp/T/xfs-e85b0102/node
    Yarn: 4.0.1 - /private/var/folders/wg/zn78dyk51h5bvz0crq8x8w0h0000gp/T/xfs-e85b0102/yarn
    npm: 9.8.1 - ~/.volta/tools/image/node/18.18.2/bin/npm
```

**Comment by arcanis** [comment]
That's expected, it's a feature, not a bug. Yarn ensures that the version of Node used to run your scripts is the same as the one used to run Yarn itself.

**Comment by seansfkelley** [comment]
That's fair, and presumably what one wants more often than not. I was surprised by how aggressive Yarn is about guaranteeing this, enough that it superseded Volta (by bypassing the Volta shim and going right to the resolved Volta-installed version). In any case, there's a workaround, so I'll use that. Thanks!

**Comment by merceyz** [comment]
We use [`process.execPath`](https://nodejs.org/dist/latest-v20.x/docs/api/process.html#processexecpath) to get the path to the current Node.js binary so we're not really doing that much to get it.
https://github.com/yarnpkg/berry/blob/d375a7f3873c6dde603f688b0ee75bdf516c4160/packages/yarnpkg-core/sources/scriptUtils.ts#L131

**Comment by Arjan-Zuidema** [comment]
Well, it looks like a bug to me, and not a wanted feature. When getting the path of node you get a temp path, which gets cleared and therefore cannot be used.

Any way around this behaviour?

**Comment by seansfkelley** [comment]
There is a workaround listed in the original post.
