### ISSUE TITLE
[Bug?]: lack of deprecation warnings for packages

### ISSUE THREAD

**Issue by eric-g-97477** [yarnpkg/berry#5982]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I am trying to understand a change in behavior between yarn 3 and yarn 4. The test case is simple. In a new folder just do yarn init and have package.json look like:

```
{
  "name": "test",
  "packageManager": "yarn@3.7.0",
  "dependencies": {
    "popper.js": "^1.14.3"
  }
}
```
When executing yarn, the following warning will be emitted:
```
➤ YN0061: │ popper.js@npm:1.16.1 is deprecated: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
```
However, if I set packageManager to version 4.0.2, no warning is emitted.

Occasionally, such warnings are useful to see. What controls the warning behavior in yarn 4? Or, what was the reason for supressing or removing these warnings in yarn 4?

In https://discord.com/channels/226791405589233664/1174400674394554478/1174973102833287188, @trivikr verified this is reproducible and suggested a bug report.

I did see in the blog post for Yarn 4.0...https://yarnpkg.com/blog/release/4.0
```
we now try to only print warnings for actionable situations
```
It is possible the current behavior was caught up in that effort. I like the concept of not emitting warnings that are not actionable. However, there are cases, like deprecation warnings, where I would like a flag to temporarily see such warnings..i.e. I may decide to live with the deprecation, but want to hide it temporarily so it doesn't obscure warnings I need to act on

### To reproduce

{
  "name": "test",
  "packageManager": "yarn@3.7.0",
  "dependencies": {
    "popper.js": "^1.14.3"
  }
}

### Environment

```shell
System:
    OS: macOS 14.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 20.9.0 - /private/var/folders/7r/z2yvzrzx7_lg2h81285rsplr0000gp/T/xfs-8f5aaf94/node
    Yarn: 4.0.2 - /private/var/folders/7r/z2yvzrzx7_lg2h81285rsplr0000gp/T/xfs-8f5aaf94/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
```

**Comment by merceyz** [comment]
This is working as intended, it's mentioned in the changelog as one of the breaking changes:

> Deprecation checks have been moved to yarn npm audit.
https://github.com/yarnpkg/berry/blob/017b94ae4eb20dea14ac673a053a1f2974b778ff/CHANGELOG.md#400
