### ISSUE TITLE
[Bug?]: 

### ISSUE THREAD

**Issue by lockieluke** [yarnpkg/berry#5985]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

![image](https://github.com/yarnpkg/berry/assets/25424409/5922caf2-a3d0-4c8f-9915-cc340930808f)
![Screenshot 2023-11-22 at 21 18 03](https://github.com/yarnpkg/berry/assets/25424409/0ee6fc28-5dd3-465f-9328-56184539a41a)

the progress bar is printed into multiple lines on both iTerm and Terminal.app

### To reproduce

just run any Yarn command that would show the progress bar

### Environment

```shell
System:
    OS: macOS 14.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 21.1.0 - /private/var/folders/k9/zxmh0rqj3fj8hr0l5yz94_qw0000gn/T/xfs-56ccd34c/node
    Yarn: 4.0.0-rc.53 - /private/var/folders/k9/zxmh0rqj3fj8hr0l5yz94_qw0000gn/T/xfs-56ccd34c/yarn
    npm: 9.1.2 - /opt/homebrew/bin/npm
    bun: 1.0.13 - /opt/homebrew/bin/bun
```

### Additional context

Tried switching back to Node 20, still happens

![image](https://github.com/yarnpkg/berry/assets/25424409/4f552063-79b1-4879-aae0-a39fed519e46)
**Ambiguous characters are double-width** is disabled

**Comment by arcanis** [comment]
This is already fixed in later releases
