### ISSUE TITLE
[Feature] respect `YARN_CACHE_FOLDER` if `enableGlobalCache: true`

### ISSUE THREAD

**Issue by sod** [yarnpkg/berry#5990]
yarn 4.0.2

seems like if `enableGlobalCache: true`, `YARN_CACHE_FOLDER` is being ignored. Would be nice if for development if you keep global cache on (the default) but for CI define a shared cache via `YARN_CACHE_FOLDER`

For now I set `enableGlobalCache: false`, as that seems to work.

related https://yarnpkg.com/configuration/yarnrc

**Comment by sod** [comment]
Feel free to reject. The description of enableGlobalCache
> If true, the system-wide cache folder will be used regardless of `cache-folder`
holds true after all. Disabling global cache works fine for us.

**Comment by arcanis** [comment]
Indeed, it's the expected behaviour 👍
