### ISSUE TITLE
[Bug?]: pnpm linker is not maintaining proper file perms from package source

### ISSUE THREAD

**Issue by ColeStansbury** [yarnpkg/berry#5991]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Esbuild is a core dependency for many frontend projects. I was able to provide clear and simple steps for how to reproduce the bug in the following issue:
https://github.com/evanw/esbuild/issues/3510

Thanks to ESbuild's project team, they noticed that yarn is not retaining the "x" bit on the file permissions when using pnpm. Reverting back to pnp is the only workaround I've found so far.

### To reproduce

```zsh
corepack enable
yarn set version berry
yarn init -2
yarn add esbuild
echo "nodeLinker: pnpm" >> .yarnrc.yml
yarn
```

### Environment

```shell
System:
    OS: Mac OS Sonoma 14.1.1
    CPU: M2
Binaries:
    Node: v21.2.0 - ~/.nvm/versions/node/v21.2.0/bin/yarn
    Yarn: 4.0.2 - ~/.nvm/versions/node/v21.2.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.2.0/bin/npm
```

**Comment by 7rulnik** [comment]
duplicate https://github.com/yarnpkg/berry/issues/5165

**Comment by ColeStansbury** [comment]
> duplicate #5165

thanks, I dug for quite a while but wasn't able to find this issue yet. My mistake, closing.
