### ISSUE TITLE
[Feature] log error directly out stdout on CI instead of outputting to a temporary file

### ISSUE THREAD

**Issue by JounQin** [yarnpkg/berry#6025]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

```log
➤ YN0009: │ isolated-vm@npm:4.5.0 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-b6e2a035/build.log)
```

A log like this does not make any sense because it's not easy to view such temporary files on CI

**Describe the solution you'd like**

Output the error log directly with a flag

**Describe the drawbacks of your solution**

N/A

**Describe alternatives you've considered**

N/A

**Comment by merceyz** [comment]
Yarn already does that if it detects it's running in a CI, see https://yarnpkg.com/configuration/yarnrc#enableInlineBuilds.

**Comment by JounQin** [comment]
Thanks for your reply, I think it must be related that we're using our own custom CI built with tekton, which does not provide a CI environment.

I'll try to add a CI environment manually for now.
