### ISSUE TITLE
[Bug] QUALIFIED_PATH_RESOLUTION_FAILED when .yarn/cache is absent

### ISSUE THREAD

**Issue by silverwind** [yarnpkg/berry#606]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Yarn seems unable to operate without its `.yarn/cache` folder. I would expect it to be able to operate using only the files `.pnp.js` and a yarn script like `.yarn/releases/yarn-berry.js`.

Background is that I'd like to add both files into source control so the project can work completely offline from a checkout only but I don't feel comfortable adding that cache folder to source control.

**To Reproduce**

``` bash
mkdir project && cd project
yarn policies set-version v2
yarn -y init
yarn add updates
rm -rf .yarn/cache
yarn run updates
```

Gives this error:

```
Error: Couldn't find a suitable Node resolution for the specified unqualified path

Source path: project/.yarn/cache/updates-npm-9.1.0-3c627a5e0d-1.zip/node_modules/updates/updates.js
Rejected resolution: project/.yarn/cache/updates-npm-9.1.0-3c627a5e0d-1.zip/node_modules/updates/updates.js
Rejected resolution: project/.yarn/cache/updates-npm-9.1.0-3c627a5e0d-1.zip/node_modules/updates/updates.js.js
Rejected resolution: project/.yarn/cache/updates-npm-9.1.0-3c627a5e0d-1.zip/node_modules/updates/updates.js.json
Rejected resolution: project/.yarn/cache/updates-npm-9.1.0-3c627a5e0d-1.zip/node_modules/updates/updates.js.node

    at internalTools_makeError (project/.pnp.js:5000:24)
    at resolveUnqualified (project/.pnp.js:6026:13)
    at resolveRequest (project/.pnp.js:6051:14)
    at Object.resolveRequest (project/.pnp.js:6128:26)
    at Function.external_module_default.a._resolveFilename (project/.pnp.js:5205:29)
    at Function.external_module_default.a._load (project/.pnp.js:5107:50)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1143:12)
    at internal/main/run_main_module.js:16:11 {
  code: 'MODULE_NOT_FOUND',
  pnpCode: 'QUALIFIED_PATH_RESOLUTION_FAILED',
  data: {
    unqualifiedPath: 'project/.yarn/cache/updates-npm-9.1.0-3c627a5e0d-1.zip/node_modules/updates/updates.js',
    request: 'project/.yarn/cache/updates-npm-9.1.0-3c627a5e0d-1.zip/node_modules/updates/updates.js',
    issuer: 'project/'
  }
}
````

**Comment by arcanis** [comment]
The PnP file only contains the dependency tree. The files themselves are still loaded from the cache (at runtime, kinda like if the cache was your node_modules, in a sense).

**Comment by silverwind** [comment]
Any plans to have it in a single file later on?

I think this kind of breaks the promise of PNP mode ("Yarn will create a single file named .pnp.js instead of the node_modules megafolder").

**Comment by arcanis** [comment]
No, no plans. A single vendor file would have very bad performances since adding or removing a package could involve rewriting the whole file, ie potentially multiple GBs. PnP already offers a lot of guarantees, but standalone applications isn't one of them.
