### ISSUE TITLE
[Bug?]: Nav bar issue in yarn website.

### ISSUE THREAD

**Issue by nepalivai** [yarnpkg/berry#6070]
### Self-service

- [x] I'd be willing to implement a fix

### Describe the bug

too much data in nav bar is couseing the silide bar to pop up as shown ing the image below you can see it on [webpage](https://yarnpkg.com/)
<img width="959" alt="image" src="https://github.com/yarnpkg/berry/assets/108126089/412ac1c6-0b15-4af8-89f5-10d0cadac341">

### To reproduce

Visit the [site.](https://yarnpkg.com/)

> *** The link to see the [docuentation](https://yarnpkg.com/advanced/sherlock) is not available.

### Environment

```shell
System:
OS: window 11
cpu: 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
browsers :Brave
```

**Comment by Gokul2003g** [comment]
Hey 
I am willing to work on this issue.
Can replace the navbar with a burger menu when overflow occurs.
But where is the code of the website. @nepalivai

**Comment by Gokul2003g** [comment]
.navbar__item {
  /* Avoid awkward linebreaks of menu items.
   * Labels should be kept short, however. */
  white-space: nowrap;
}

.navbar__inner > .navbar__items:first-child {
  /* Allow the first nav item group to scroll horizontally. */

  /* Without this rule, rightmost items in first nav group
   * would overlap leftmost items in second nav group,
   * becoming completely unreadable. */

  /* NOTE: Would NOT work as is if there is a drop-down menu. */
  /* That’s why it’s only applied to the first nav item group:
   * the second nav group has a dropdown, which would be cut off
   * by this overflow rule. */

  overflow-x: auto;
}

it is acknoledged here. I dont see how to solve it.

**Comment by nepalivai** [comment]
plz submit a pr with a screenshot.
