### ISSUE TITLE
[Bug?]: install Electron error

### ISSUE THREAD

**Issue by fisheep01** [yarnpkg/berry#6086]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

An error occurred when I used yarn4 to install Electron in the project. The specific error is as follows:
```
PS D:\code\ali-live-tools> yarn
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 492ms
➤ YN0000: ┌ Link step
➤ YN0007: │ electron@npm:28.1.3 must be built because it never has been before or the last one failed
➤ YN0009: │ electron@npm:28.1.3 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\ADMINI~1\AppData\Local\Temp\xfs-381b520c\build.log)
➤ YN0000: · Failed with errors in 22s 178ms
```

The content in build.log is:
```
# This file contains the result of Yarn building a package (electron@npm:28.1.3)
# Script name: postinstall

RequestError: connect ETIMEDOUT 20.205.243.166:443
    at ClientRequest.<anonymous> (D:\code\ali-live-tools\node_modules\got\dist\source\core\index.js:970:111)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:526:35)
    at origin.emit (D:\code\ali-live-tools\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
```

I understand that this is caused by a timeout when accessing github resources. When I originally installed using npm, I often solved this problem by configuring `ELECTRON_MIRROR` in `.npmrc`, but when yarn was upgraded to version 4.x, it was no longer supported. Read the configuration from `.npmrc`. I checked the relevant information and found no relevant configuration.

In addition, I referred to this issue [https://github.com/yarnpkg/berry/issues/4804](url) and made relevant configurations for `.yarnrc.yml`, but it still had no effect.
```
nodeLinker: node-modules
```

### To reproduce

Configuration in package.json
```
"electron": "^28.1.0"
```
Execute yarn to install

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
  Binaries:
    Node: 20.9.0
    Yarn: 4.0.2
    npm: 10.1.0
```

**Comment by arcanis** [comment]
It's a networking issue, ie not Yarn-related.
```
RequestError: connect ETIMEDOUT 20.205.243.166:443
```

**Comment by fisheep01** [comment]
> It's a networking issue, ie not Yarn-related.
> 
> ```
> RequestError: connect ETIMEDOUT 20.205.243.166:443
> ```

I understand this is a network problem, but when I used npm to install before, I could solve this problem by configuring `ELECTRON_MIRROR`. Isn't there some similar strategy when using yarn currently?

**Comment by fisheep01** [comment]
![image](https://github.com/yarnpkg/berry/assets/11489830/f80cc5b2-ce9e-4f1e-9488-27e78385a1e6)

**Comment by kanweiwei** [comment]
same

**Comment by fisheep01** [comment]
> same

I really hope the yarn team can pay attention to this issue. Based on this problem, I had to switch the tool back to npm. Or in another project I directly used pnpm

**Comment by kingouer** [comment]
same how setting ELECTRON_MIRROR ?

**Comment by clemyan** [comment]
According to electron's documentation, electron config (including `ELECTRON_MIRROR`) can be set as an environment variables, in which case putting them in an `.env.yarn` (or any dotenv file configured via [`injectEnvironmentFiles`](https://yarnpkg.com/configuration/yarnrc#injectEnvironmentFiles)) or setting actual env vars via your shell should both work.

**Comment by kingouer** [comment]
tks ,now it works
