### ISSUE TITLE
[Bug?]: "No candidates found" Install Error for Existing Packages

### ISSUE THREAD

**Issue by joealden** [yarnpkg/berry#6100]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When running `yarn install` after deleting my lockfile (to update all my sub-deps), I'm getting "No candidates found" errors. Most of the time it's for the `@esbuild/android-arm64@npm:0.19.11` package, but it seems spurious (unless yarns resolution logic isn't deterministic), as I'm also sometimes seeing it for `@shopify/theme-check-common@npm:^1.22.0`. I also did once see it for `mrmime`, so it doesn't appear to only be happening for org scoped packages.

I tried to see if there was a way to run `yarn install` with verbose logging, but I could find a way to do this. Let me know if I missed something!

### To reproduce

The new docs site doesn't appear to have a page for https://yarnpkg.com/advanced/sherlock, so unable to do this.

### Environment

```shell
System:
  OS: Linux 6.6 Solus 4.5
  CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
Binaries:
  Node: 18.19.0 - /tmp/xfs-4f1510c2/node
  Yarn: 4.0.2 - /tmp/xfs-4f1510c2/yarn
  npm: 10.2.3 - /usr/bin/npm
  bun: 1.0.18 - ~/.bun/bin/bun
```

### Additional context

![image](https://github.com/yarnpkg/berry/assets/10297243/61cc5967-dfd6-41c3-b964-792c8417f3e4)

![image](https://github.com/yarnpkg/berry/assets/10297243/f6b342bf-56e9-4018-938a-b433b3c8fe89)

**Comment by arcanis** [comment]
Likely duplicate with https://github.com/yarnpkg/berry/issues/5989

**Comment by joealden** [comment]
Ah apologies - I saw that issue and assumed "corporate environment" meant they were using a private registry!
