### ISSUE TITLE
[Bug]: Yarn@4 sets NODE_OPTIONS to empty string instead of undefined (as yarn@3 does)

### ISSUE THREAD

**Issue by markusvoelk-zr** [yarnpkg/berry#6148]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When i use dotenv to read environment variables from a .env file, the NODE_OPTIONS variable never gets overridden because yarn@4 sets an empty string as value.

yarn@3 has different behaviour here (env var is not set at all)

### To reproduce

- `yarn set version 3.8.0`
- `yarn node -e "console.log(typeof process.env.NODE_OPTIONS, process.env.NODE_OPTIONS)"`
- // output = "undefined undefined"

- `yarn set version stable` (currently 4.1.0)
- `yarn node -e "console.log(typeof process.env.NODE_OPTIONS, process.env.NODE_OPTIONS)"`
- // output = "string"

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
  Binaries:
    Node: 20.11.1 - ~\AppData\Local\Temp\xfs-693232ce\node.CMD
    Yarn: 4.1.0 - ~\AppData\Local\Temp\xfs-693232ce\yarn.CMD
    npm: 10.2.4 - ~\AppData\Local\nvs\default\npm.CMD
```

**Comment by DanielRose** [comment]
This is a problem when setting this via [Nx](https://nx.dev/recipes/tips-n-tricks/define-environment-variables). Nx considers an empty value as something which is explicitly set, so it is not possible to override it via environment files.
