### ISSUE TITLE
[Feature] Allow plugins to resolve `yarn add`'s parameter

### ISSUE THREAD

**Issue by nicolo-ribaudo** [yarnpkg/berry#6150]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

I'm working on a plugin that implements a custom protocol -- basically like normal installs but with some special fetching/resolution behavior. Let's call it "foo".

It allows me to write this in my dependencies:
```js
{
  "dependencies:" {
    "@scope/my-pkg": "foo:^0.1.0"
  }
}
```

When installing normally, I do not need to specify the version in `yarn add`: I can use, for example, `yarn add @babel/core` and it will automatically resolve it to `7.24.0`.

When using a custom protocol, there is no way of doing so. I can run `yarn add @scope/my-pkg@foo` (or `yarn add @scope/my-pkg@foo:`), but there is no way for plugins to properly resolve that to the last version and store the proper range in `package.json`. Even if I supported `@scope/my-pkg@foo:` in the plugin (without an explicit version), the value stored in package.json would be `"@scope/my-pkg": "foo:"`.

**Describe the solution you'd like**

Maybe add a `async bindDescriptorForInstall(descriptor: Descriptor): Promise<Descriptor>` method to the `Resolver` interface?

**Describe the drawbacks of your solution**

I don't think plugins can currently hook into other plugins? And `yarn add` is implemented as a plugin.

**Describe alternatives you've considered**

Not support this?

**Comment by nicolo-ribaudo** [comment]
Closing because maybe this is actually possible, I'm experimenting

**Comment by arcanis** [comment]
So you'd like a way for plugins to essentially replace `yarn add @scope/my-pkg` by `yarn add @scope/my-pkg@foo:something` instead of `@scope/my-pkg@*` (the `*` being hardcoded [here](https://github.com/yarnpkg/berry/blob/master/packages/plugin-essentials/sources/suggestUtils.ts#L324))? How would you know whether to use one or the other, depending on the package?

**Comment by nicolo-ribaudo** [comment]
I want to explicitly write `foo:` in `yarn add`, but still being able to do some dynamic resolution. It could look like `yarn add @scope/my-pkg@foo:`, or maybe like `yarn add foo:@scope/my-pkg`.

> Closing because maybe this is actually possible, I'm experimenting

~~Closing because maybe this is actually possible, I'm experimenting~~

I don't think it is, because `yarn add foo:@scope/my-pkg` gets parsed as a GitHub URL, while `yarn add @scope/my-pkg@foo:` properly calls `getCandidates` in my plugin but still doesn't let me overwrite the version to write in `package.json` because https://github.com/yarnpkg/berry/blob/580f593db4ab592bfff2d9fd5c5613c29c6fee2b/packages/plugin-essentials/sources/suggestUtils.ts#L211 does not return `unknown` for the range (but `foo:`, obviously).

**Comment by nicolo-ribaudo** [comment]
As a workaround I'm using `yarn foo add @scope/my-pkg`, which tbh is a good enough solution if you prefer to not make `yarn add` more complex :)

**Comment by BasixKOR** [comment]
We have a similar need to OP: Our company uses an internal Yarn plugin to provide patches and necessary overrides and not being able to override `yarn add`'s behaviour makes it hard to encourage the usage of the patched packages.
