### ISSUE TITLE
[Bug?]: yarn npm audit not detecting security vulnerabilities in a mono repo with multiple packages

### ISSUE THREAD

**Issue by hetpatel33** [yarnpkg/berry#6182]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

`yarn npm audit` not detecting security vulnerabilities in a mono repo with multiple packages if the same package is being installed with different versions in different packages and one of them has security vulnerability while others don't.

### To reproduce

Sample Monorepo - https://github.com/hetpatel33/yarn-npm-audit-monorepo

Above repo contains 2 packages

1. Library ( with "next" package version - 13.2.0 )
2. Site ( with "next" package version - 14.0.4 )

"13.2.0" has some know security vulnerabilities - https://github.com/advisories/GHSA-c59h-r6p8-q9wc and the same is fixed in "14.0.4".

The same is being reported correctly using "yarn npm audit" if both the packages uses 13.2.0 only. But no vulnerabilities are reported if different versions are used.

### Environment

```shell
System:
    OS: macOS 13.5.2
    CPU: (12) arm64 Apple M2 Max
  Binaries:
    Node: 18.14.2 - /private/var/folders/km/ktrm8yg9523_flkm6fg725j00000gq/T/xfs-0d5dbc99/node
    Yarn: 3.2.4 - /private/var/folders/km/ktrm8yg9523_flkm6fg725j00000gq/T/xfs-0d5dbc99/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
```

**Comment by arcanis** [comment]
Please upgrading to Yarn 4.1, I think we fixed something similar already.

**Comment by hetpatel33** [comment]
@arcanis, upgrading to yarn `4.1.1` solved this, but any workaround for the same in yarn v3 itself for the quick fix for now, as upgrading to v4 will require changes for all the breaking changes, which we are already planning to do.

**Comment by arcanis** [comment]
Unfortunately no, `audit` was reimplemented in 4.x, so it can't be backported.

**Comment by hetpatel33** [comment]
Hi @arcanis, we upgraded yarn to `4.1.1` which solved the above issue but it lead to one more issue where we are trying to run the `yarn npm audit` command inside a nodeJS script to automate the security audits, that started failing now with the v4 which was working fine with the v3. The same `yarn npm audit` works perfectly fine if I run it locally. Any known issue with that? The error log from the process is also not very helpful. 

Code Reference : 

`function auditPackages(): Promise<VulnerablePackages> {
  return new Promise((resolve, reject) => {
    exec('yarn npm audit --json --environment production --all --recursive --no-deprecations', (err, stdout) => {
      if (err) {
        reject(err);
      } else {
        resolve(stdout ? adaptVulnerablePackages(JSON.parse(stdout)) : []);
      }
    });
  });
}`

Error Log : 

`Error: Command failed: yarn npm audit --json --environment production --all --recursive --no-deprecations

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'yarn npm audit --json --environment production --all --recursive --no-deprecations'
}`

**Comment by hetpatel33** [comment]
@arcanis, any thoughts on above please ?

**Comment by hetpatel33** [comment]
That’s the only log I am getting from the node exec, that’s why not sure what is happening with the yarn npm audit. Will a sample repo help? @arcanis

**Comment by hetpatel33** [comment]
FIxed above issue by wrapping the node script using a Bash script and saving the output of yarn npm audit to a temp file.
