### ISSUE TITLE
[Bug]: `prepack` script is not ran when installing dependency via git

### ISSUE THREAD

**Issue by tien** [yarnpkg/berry#6185]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Contrary to https://yarnpkg.com/package?name=prepack `prepack` are never ran when installing dependency via git.

### To reproduce

Use https://gitpkg.vercel.app, add a prepack script to any repo, observe that prepack script doesn't get ran.

### Environment

```shell
System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M2 Pro
  Binaries:
    Node: 20.11.1 - /private/var/folders/b6/kpq5ks6519x4xg8lwpcr7cs40000gn/T/xfs-d4fcbb06/node
    Yarn: 4.1.1 - /private/var/folders/b6/kpq5ks6519x4xg8lwpcr7cs40000gn/T/xfs-d4fcbb06/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    bun: 1.0.33 - /opt/homebrew/bin/bun
```

**Comment by GNUGradyn** [comment]
Why was this closed? This appears to still be an issue

**Comment by arcanis** [comment]
Prepack scripts are meant to be run, since we run `yarn pack` (or similar, depending on the package manager used by the installed project). If you're sure that's not the case, open an issue with a clear reproduction (ie don't tell to use "any package" - add a repro that uses a specific one).
