### ISSUE TITLE
[Bug]: yarn explain returns internal error, 404 because of Gatsby -> Docusaurus move

### ISSUE THREAD

**Issue by simon-aira** [yarnpkg/berry#6249]
### Self-service

- [x] I'd be willing to implement a fix

### Describe the bug

Example:

```
❯ yarn explain YN0000
Internal Error: The remote server failed to provide the requested resource
    at wb (/Users/simon/.cache/node/corepack/v1/yarn/4.1.1/yarn.js:147:31902)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.L4 (/Users/simon/.cache/node/corepack/v1/yarn/4.1.1/yarn.js:147:33665)
    at async j0t (/Users/simon/.cache/node/corepack/v1/yarn/4.1.1/yarn.js:435:359)
    at async Hh.execute (/Users/simon/.cache/node/corepack/v1/yarn/4.1.1/yarn.js:435:1134)
    at async Hh.validateAndExecute (/Users/simon/.cache/node/corepack/v1/yarn/4.1.1/yarn.js:94:787)
    at async as.run (/Users/simon/.cache/node/corepack/v1/yarn/4.1.1/yarn.js:98:3250)
    at async sSt (/Users/simon/.cache/node/corepack/v1/yarn/4.1.1/yarn.js:734:11303)
    at async nk (/Users/simon/.cache/node/corepack/v1/yarn/4.1.1/yarn.js:734:11659)
```

### To reproduce

```
yarn explain YN0000
```

### Environment

```shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M2 Pro
  Binaries:
    Node: 20.12.2 - /private/var/folders/v6/x86jncgx39xf56z0zw_zfgp80000gn/T/xfs-261fb472/node
    Yarn: 4.1.1 - /private/var/folders/v6/x86jncgx39xf56z0zw_zfgp80000gn/T/xfs-261fb472/yarn
    npm: 10.6.0 - ~/Library/Caches/fnm_multishells/65652_1714072234497/bin/npm
```

**Comment by simon-aira** [comment]
It appears (see [explain.ts line 19])(https://github.com/yarnpkg/berry/blob/52252b0caa3ac6d753348b271f91090f2724d089/packages/plugin-essentials/sources/commands/explain.ts#L19)) to be trying to fetch the URL `https://repo.yarnpkg.com/${version}/packages/gatsby/content/advanced/error-codes.md`. Indeed, replacing 4.1.1 for version gives a 404 ([here](https://repo.yarnpkg.com/4.1.1/packages/gatsby/content/advanced/error-codes.md)). Likewise, the help message when an error does not exists ([explain.ts line 91](https://github.com/yarnpkg/berry/blob/52252b0caa3ac6d753348b271f91090f2724d089/packages/plugin-essentials/sources/commands/explain.ts#L91C47-L91C51)) points to this file, but in the Github repo.

**Comment by simon-aira** [comment]
I suppose the new location for this file would be this: https://github.com/yarnpkg/berry/blob/52252b0caa3ac6d753348b271f91090f2724d089/packages/docusaurus/docs/advanced/01-general-reference/error-codes.mdx?plain=1#L4 – but in a different format?

**Comment by arcanis** [comment]
Oh good point, I didn't think about this command when we migrated from Gatsby to Docusaurus 🤔

Unfortunately we also recently changed from md to mdx, so there isn't a tagged url yet that works (it will only stop 404'ing after the next release). It should be:

```
https://repo.yarnpkg.com/${version}/packages/docusaurus/docs/advanced/01-general-reference/error-codes.mdx
```

**Comment by simon-aira** [comment]
Ok! Would there also be other code changes required to support the format changes, or will updating the URL in the command be enough? As far as I can tell, not much MDX is used in this particular file?
