### ISSUE TITLE
[Bug?]: If use 5.4.5-sdks in Next 14, JS/TS language service immediately crashed 5 times

### ISSUE THREAD

**Issue by jiwooproity** [yarnpkg/berry#6283]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

use 5.4.4 ~ 5.4.5-sdks in Next 14

```
yarn dlx @yarnpkg/sdks vscode
```

and i got VSCode intellisense infinity loading, "JS/TS language service immediately crashed 5 times" crash notification

but, if changed typescript version to "5.4.3-sdk" in ".yarn/sdks/typescript/package.json" no crash notification

5.4.4 ~ 5.4.5 version sdks all is crashed ( 5.4.3-sdks downgrade version not have crashed, typescript 5 ~ 5.4.5 all )

![스크린샷 2024-05-09 오후 2 28 47](https://github.com/yarnpkg/berry/assets/58384366/1fd7f8df-4d8b-4ba8-ba02-1c363a06f22b)

### To reproduce

```
yarn create next-app --typescript ( typescript version "^5" )
rm -rf node_modules
rm -rf yarn.lock
yarn set version berry
yarn dlx @yarnpkg/sdks vscode
```
press cmd + shift + p and search "typescript" set version 5.4.5 sdks
now make typescript file ( .ts, .tsx )
```
// .tsx
const App = () => {
  return (
    <div>Hi</div>
  )
}

export default App;
```

set typescript sdks and reload vscode window

![image](https://github.com/yarnpkg/berry/assets/58384366/e6c2f945-a16c-4996-82a5-121b736e998c)

typescript intellisense not working ..

![스크린샷 2024-05-09 오후 2 35 55](https://github.com/yarnpkg/berry/assets/58384366/e58b659e-4cf4-46d2-b07f-39e53cb06b43)

### Environment

```shell
System:
  OS: macOS 14.4.1
  CPU: (8) arm64 Apple M1
Binaries:
  Node: 20.5.0 - /private/var/folders/n2/v0wcxq9d0_b22czttlqjxs1w0000gn/T/xfs-d3d30e1b/node
  Yarn: 4.1.1 - /private/var/folders/n2/v0wcxq9d0_b22czttlqjxs1w0000gn/T/xfs-d3d30e1b/yarn
  npm: 10.2.2 - /opt/homebrew/bin/npm
  pnpm: 8.10.2 - /opt/homebrew/bin/pnpm
```

**Comment by clemyan** [comment]
Try if setting `typescript.tsserver.experimental.useVsCodeWatcher` to `false` fixes it. If so, then this is a duplicate of #6270.

**Comment by jiwooproity** [comment]
@clemyan 
oh.. i tried and i got no crash notification
i think duplicate of #6270 too
thank you! and i sorry 

resolved
