### ISSUE TITLE
[Bug?]:yarn v1.22.19 install polyfill-object.fromentries 1.0.1

### ISSUE THREAD

**Issue by rmourey26** [yarnpkg/berry#6294]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

yarn 1.22.19 package install error

running Node 18.x, AMD64 Linux, local machine and remote Vercel builds using Node 18.x 

Upon running yarn install for package

[polyfill-object.fromentries](https://yarnpkg.com/package?name=polyfill-object.fromentries
) 1.0.1

yarn produces error:

**_error An unexpected error occurred: "https://registry.nlark.com/polyfill-object.fromentries/download/polyfill-object.fromentries-1.0.1.tgz: getaddrinfo ENOTFOUND registry.nlark.com"_**

This package is nearly 6 years old and worked fine for the last year when installed during 50+ Vercel prod builds . It worked fine on May 10, 2024  but on May 11, 2024, I began receiving the error while deploying with Vercel and confirmed that the same error occurs locally running AMD64 architecture, Node18.x

### To reproduce

sherlock link is broken ?

using the env mentioned above, run 

yarn install [polyfill-object.fromentries ](https://yarnpkg.com/package?name=polyfill-object.fromentries)

### Environment

```shell
System:
Vercel Deployments running node 18.x
&
Linux
AMD64
Custom chromebook chromeOS cb3-431

Node 18.x
Yarn 1.22.19

Error occurs on local laptop and while running Vercel deployments 

Repo and app referenced above github.com/the-blockchain-company/interface
```

**Comment by arcanis** [comment]
We don't maintain http://registry.nlark.com
