### ISSUE TITLE
v2 documentation preview

### ISSUE THREAD

**Issue by borekb** [yarnpkg/berry#63]
I had trouble googling the link to the new docs or finding it via a search here on GitHub so I thought I'd create this issue for better discoverability. Not sure if you wanted to add it to README at this point but I'd be happy to submit a PR if you wanted.

The v2 documentation (WIP) is published here: https://yarnpkg.github.io/berry/

**Comment by arcanis** [comment]
Good point 👍 

Fixed in f2a874a47852f0ab7da149bbcee797a26e012187
