### ISSUE TITLE
[Bug] There should be a npmEmail option in .yarnrc.yml

### ISSUE THREAD

**Issue by lhorie** [yarnpkg/berry#633]
- [ x ] I'd be willing to implement a fix

**Describe the bug**

I'm trying to migrate a codebase that uses a private registry to yarn v2. Currently my .npmrc file looks like this:

```
registry    = [url to registry]
_auth       = [redacted]
email       = [email]
always-auth = true
```

The [yarnrc docs](https://next.yarnpkg.com/configuration/yarnrc) indicate that I should create a `.yarnrc.yml` file and add the corresponding fields:

```
npmRegistryServer: "[url to registry]"
npmAuthToken: "[redacted]"
npmAlwaysAuth: "true"
```

However, yarnrc.yml doesn't appear to support an equivalent of the `email` field, which is required to authenticate into this private registry

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version 10.16.0
 - Yarn version 2.0.0-rc.19

**Comment by arcanis** [comment]
Oh, interesting - we removed support for it when we implemented `yarn npm login`, as we weren't sure whether it was actually needed anywhere: https://github.com/yarnpkg/berry/pull/135#discussion_r281957771.

I think we could add it back, although in this situation we would probably only ask for it on `yarn npm login` if the repository contains a specific value in the configuration.

Two questions:
- Is this private repository a common type (can we open a bug thread with them?)
- Is the email actually checked, or can it be anything?

**Comment by rtsao** [comment]
If you were using `2.0.0-rc.19`, I don't think that version includes https://github.com/yarnpkg/berry/pull/622. With that change, I was able to get yarn v2 working with a private registry (even without any email field).

**Comment by lhorie** [comment]
Oh interesting. Let me try that and circle back

**Comment by arcanis** [comment]
I'll close this issue as I'm not sure yet whether there's something we should do. Feel free to reopen if needed.

**Comment by clemstoquart** [comment]
Hi Yarn team,

It's currently impossible to use Yarn 2/3 with Artifactory which requires the "email" to be use as a private registry. This is preventing us to migrate to Yarn 3 😭

Can you please consider adding an email config field at least for compatibility reasons ?

**Comment by arcanis** [comment]
I want to have a talk with the JFrog people first, as adding workarounds unique to vendors is often best avoided. I opened https://www.jfrog.com/jira/browse/RTFACT-26566 for that; feel free to upvote it or, if you're a paying JFrog customer, perhaps you can mention it to your account manager.

**Comment by clemstoquart** [comment]
Thanks @arcanis for your quick answer.

I agree that it would be better to have a fix on the Artifactory side.

**Comment by scinos** [comment]
I think I found a workaround for Artifactory:

- In Artifactory, go to your profile and click 'Generate Identity Token'. Copy the 'Username' and 'Token'
- In your `.yarnrc.yml` add:

  ```
  npmRegistries:
    '<your-registry>':
      npmAlwaysAuth: true
      npmAuthIdent: <username>:<token>
  ```

**Comment by yarinsa** [comment]
Have the same problem here.
Using JFrog

**Comment by clemstoquart** [comment]
For some unknown reasons it's now working fine for my projects.

**Comment by yarinsa** [comment]
> https://www.jfrog.com/jira/browse/RTFACT-26566

JFrog works for me with:

`npmAuthIdent: ${JF_USER}:${JF_API_KEY}`

In the CI (where I am using password) I ended up with base64
`        yarn config set npmAuthIdent $(echo -n '${{ inputs.artifactory_user }}:${{ inputs.artifactory_password }}'| base64)`

@arcanis FYI.

Maybe [@yahavi](https://github.com/yahavi) will provide a better answer?
