### ISSUE TITLE
[Bug?]: CHANGELOG.md hasn't updated since Yarn 4.1, and website also does not have updates

### ISSUE THREAD

**Issue by cellog** [yarnpkg/berry#6333]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

https://yarnpkg.com/advanced/changelog stops at 4.1.0, and so does `CHANGELOG.md` - I'd like to upgrade, but have no idea what's changed :/

### To reproduce

visit the website above or look at `CHANGELOG.md`

### Environment

```shell
n/a
```

**Comment by arcanis** [comment]
Duplicate for #6289
