### ISSUE TITLE
[Bug?]: `node:test` not recognised as built-in module by @yarnpkg/doctor

### ISSUE THREAD

**Issue by bradleyayers** [yarnpkg/berry#6343]
### Self-service

- [x] I'd be willing to implement a fix

### Describe the bug

I'm importing the `node:test` module, but doctor gives me an error saying it's an undeclared dependency.

### To reproduce

1. Create a file with `import "node:test"`.
2. Run `doctor`

### Environment

```shell
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Max
Binaries:
  Node: 21.6.1 - /private/var/folders/fs/c9jy5p9s6cvg_2hv2x2gn5pc0000gn/T/xfs-446a8e07/node
  Yarn: 4.2.2 - /private/var/folders/fs/c9jy5p9s6cvg_2hv2x2gn5pc0000gn/T/xfs-446a8e07/yarn
  npm: 10.2.4 - ~/.proto/shims/npm
```

### Additional context

It looks like because this module is **only** importable as `node:test` and not as just `test`, this code https://github.com/yarnpkg/berry/blob/f1edfae49d1bab7679ce3061e2749113dc3b80e8/packages/yarnpkg-doctor/sources/cli.ts#L16 does not cater for it. `node:test` also isn't listed in `require("module").builtinModules`.

**Comment by arcanis** [comment]
The check [here](https://github.com/yarnpkg/berry/blob/f1edfae49d1bab7679ce3061e2749113dc3b80e8/packages/yarnpkg-doctor/sources/cli.ts#L87) should be replaced by a call to [`isBuiltin`](https://nodejs.org/api/module.html#moduleisbuiltinmodulename)

**Comment by bradleyayers** [comment]
The docs say `isBuiltin` was added in 18.6.0, and https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-doctor/package.json#L45 indicates doctor supports 18.2.0, should I bump the `engines` field too?
