### ISSUE TITLE
[Bug?]: PnP + workspace typescript + sdk module not found in vscode

### ISSUE THREAD

**Issue by SheepReaper** [yarnpkg/berry#6380]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

# does-yarn-pnp-work-with-this-ts-version

Ocassionally, for reasons unknown to man, vscode intellisense will report an error that it could not find a module. But building your project succeeds (modules found).

I've narrowed it down to wether pnp is enabled or not. @yarnpkg fixes it ocassionally, but it's not consistently usable.

## Requirements
- node >= 16.10.0 (for corepack)

## How this repo was generated
1. `mkdir does-yarn-pnp-work-with-this-ts-version && cd does-yarn-pnp-work-with-this-ts-version`
1. \[Optional\] (required if node < 18.0.0) `corepack enable`
1. `yarn init -p`
1. `yarn set version latest`
1. `yarn add -D typescript`
1. `yarn dlx @yarnpkg/sdks vscode`
1. `mkdir src && touch src/main.mts`
1. See below for tsconfig.json

tsconfig.json
```shell
echo '{
  "compilerOptions": {
    "module": "NodeNext",
    "rootDir": "./src",
    "outDir": "./dist",
    "resolveJsonModule": true
  },
  "include": ["./src/**/*.mts"]
}' > tsconfig.json
```

### In vscode
- Ensure the `arcanis.vscode-zipfs` extension is installed
- With a typescript file open (`src/main.mts`), change the typescript version to use the workspace version

## What's broken?
- vscode gives red squiggles and claims that a module could not be found
- but running `yarn build` succeeds no problem, and output is correct

## What single action fixes this?
- `yarn config set nodeLinker node-modules && yarn`
- you'll very likely need to reload your window now

### Troubleshooting
- Restarting typescript language server does not work, it fails to restart
- Reload Window is your friend

### To reproduce

1. Clone my repo: https://github.com/SheepReaper/does-yarn-pnp-work-with-this-ts-version
1. Open vscode
1. Run `yarn`
1. Ensure the `arcanis.vscode-zipfs` extension is installed
1. With a typescript file open (`src/main.mts`), change the typescript version to use the workspace version
1. Stare at red squiggles
a. If you don't see squiggles, reload the window until you do

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (32) x64 AMD Ryzen 9 7950X3D 16-Core Processor
  Binaries:
    Node: 20.15.0 - /tmp/xfs-c7eda2ef/node
    Yarn: 4.3.1 - /tmp/xfs-c7eda2ef/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
```

### Additional context

I have not yet hunted down which combination or yarn + typescript actually works, but it might be too much effort and will probably just use the node-modules linking.

The reason for the effort: When you `yarn remove typescript` you must also do `yarn cache clear --all` otherwise nonsense ensues with trying to add back typescript, namely the patching either fails, or the wrong version is used. IDK, clearing cache was required for me between versions.

edit: yarn 3.8.3 works fine with typescript 5.5.3. I have tried several versions of 4.x yarn all the way from 4.0.0 onwards, I have to downgrade typescript accordingly to get a successful patch application, but the symptoms remain the same. yarn itself works, runninc tsc build with it works, it's just vscode that can't seem to use the repo typescript module resolution. Am I missing something obvious?

**Comment by psychobolt** [comment]
Yarn should work correctly since you are updating dependencies from shell. It gets finicky when changes are being detected in VSCode. This is more of a IDE issue.

**Comment by SheepReaper** [comment]
> Yarn should work correctly since you are updating dependencies/running tasks from shell. It gets finicky when changes are being detected in VSCode (e.g. reinstalling eslint, stylelint, or any other linter and compiler tools) This is more a issue with the IDE extensions or language server. Another thing to make sure is if VSCode is using the correct Typescript. It should be using the Workspace TS SDK and due to security reasons, if your not prompted by a choice when opening project then you'll have to select it manually so it gets saved, hence the `enablePromptUseWorkspaceTsdk: true` in `settings.json`, unrelated to `tsdk`...

I have indicated in the OP to make sure that the correct typescript is being used. I've also purposely not installed anything beyond the minimum to get @yarnpkg/sdks working for typescript. I've also indicated reloading the window to get a clean startup. It's my understanding that the typescript language server uses the tsserver.js that's in the repo (installed by the SDK), and the typescript that's installed locally, which is patched.

Now, seeing as how everything works as intended when node-modules linking is enabled, and only breaks once pnp is enabled (reliably I might add) This leads to me to believe the issue is probably not the language server. Instead, it narrows it down to `arcanis.vscode-zipfs`, the typescript patch (yarn), or the typescript vscode SDK (also yarn).

I'd appreciate it if another soul could reproduce this. I posted both the repro repo and step-by-step instructions in the OP.

**Comment by SheepReaper** [comment]
I just downgraded to typescript 5.4.5 and works with yarn@4.3.1

| yarn  | typescript | works |
-----------------------------
| 3.8.3 | 5.5.3         | yes      |
| 4.3.1 | 5.4.5         | yes      |
| 4.3.1 | 5.5.3         | no       |

**Comment by SheepReaper** [comment]
Actually, I just updated to vscode 1.91.1, which also updates the language server. everything seems to be working now.

**Comment by psychobolt** [comment]
BTW, noticed that npm is installed on home drive, which on a different path than your node and yarn.  Are you using `nvm install` to setup node? Before you start VSCode, make sure VSCode is using the correct node in your path.

**Comment by SheepReaper** [comment]
Good eye. yes, i used nvm. There are multiple versions of node installed, but they're all here: `~/.nvm/versions/node/` just the normal location for nvm. But the reason that you're seeing yarn inside of `/tmp` is because that's what it does when corepack is enabled. yarn no longer needs to be installed globally, corepack resolves, downloads, and extracts it for you. So that's all normal.

But vscode on startup looks for node, and gives you a nice/ugly error when it can't find it. I didn't encounter it. I don't see how it could find the wrong version since it _must_ be the same version invoked when I do it from the cli.

**Comment by psychobolt** [comment]
Maybe I'm on OSX, I find it strange that binaries are not extracted to same folder as npm and node as well e.g. `.nvm/versions/node/v20.15.0/bin/yarn` - at least that is consistent with nvm installs on my end. I think possibly `nvm` already ships with `yarn`. Installing binaries in `/tmp` is not in good practice, if that is expected.

**Comment by SheepReaper** [comment]
corepack ships with node as of version 16.10.0, but it's disabled by default. As of version 18.0.0 it's enabled by default. corepack looks at your package.json for "packageManager" and uses that to determine which package manager to use. Alternatively, if you just invoke `yarn` without having first installed it globally, it downloads it for you. So it may as well be installed.
