### ISSUE TITLE
[Bug?]: Can't build workspace of project after removing PNP

### ISSUE THREAD

**Issue by TimRobertDev** [yarnpkg/berry#6394]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

After migrating out of pnp by adding `nodeLinker: node-modules` to my .yarnrc.yml, the workspace of my project can't be built anymore, and the only error log I have is : 

```
luxe-jahia-demo@workspace:. STDOUT Usage Error: This tool can only be used with projects using Yarn Plug'n'Play
```

I'm using yarn 4.1.1 and I tried with other versions, the workspace can't build and I can't delete it (I don't need the workspace).

Here is the complete  log of the workspace being built :

```
luxe-jahia-demo@workspace:. must be built because it never has been before or the last one failed
➤ YN0000: │ luxe-jahia-demo@workspace:. STDOUT ➤ YN0000: · Yarn 4.3.1
➤ YN0000: │ luxe-jahia-demo@workspace:. STDOUT ➤ YN0000: ┌ Resolution step
➤ YN0000: │ luxe-jahia-demo@workspace:. STDOUT ➤ YN0085: │ + @yarnpkg/sdks@npm:3.1.3, @arcanis/slice-ansi@npm:1.1.1, @nodelib/fs.scandir@npm:2.1.5, @nodelib/fs.stat@npm:2.0.5, @nodelib/fs.walk@npm:1.2.8, and 99 m
ore.
➤ YN0000: │ luxe-jahia-demo@workspace:. STDOUT ➤ YN0000: └ Completed in 3s 683ms
➤ YN0000: │ luxe-jahia-demo@workspace:. STDOUT ➤ YN0000: ┌ Fetch step
➤ YN0000: │ luxe-jahia-demo@workspace:. STDOUT ➤ YN0013: │ 104 packages were added to the project (+ 9.33 MiB).
➤ YN0000: │ luxe-jahia-demo@workspace:. STDOUT ➤ YN0000: └ Completed in 0s 752ms
➤ YN0000: │ luxe-jahia-demo@workspace:. STDOUT ➤ YN0000: ┌ Link step
➤ YN0000: │ luxe-jahia-demo@workspace:. STDOUT ➤ YN0000: └ Completed in 2s 784ms
➤ YN0000: │ luxe-jahia-demo@workspace:. STDOUT ➤ YN0000: · Done in 7s 256ms
➤ YN0000: │ luxe-jahia-demo@workspace:. STDOUT
➤ YN0000: │ luxe-jahia-demo@workspace:. STDOUT Usage Error: This tool can only be used with projects using Yarn Plug'n'Play
➤ YN0000: │ luxe-jahia-demo@workspace:. STDOUT
➤ YN0000: │ luxe-jahia-demo@workspace:. STDOUT $ sdks [--cwd #0] [-v,--verbose] ...
➤ YN0009: │ luxe-jahia-demo@workspace:. couldn't be built successfully (exit code 1, logs can be found here: C:
\Users\Tim\AppData\Local\Temp\xfs-f98de5f1\build.log)
```

### To reproduce

- Clone this repo : https://github.com/Jahia/luxe-jahia-demo
- Run yarn install (with pnp) : it works.
- Add `nodeLinker: node-modules` to .yarnrc.yml
- Run yarn install (without pnp) : workspace build error

### Environment

```shell
System : 
	OS : Windows 10
	CPU : AMD Ryzen 7 5800X
Binaries : 
	Node : 18.18.0 
	Yarn : 4.1.1
	Npm : 9.8.1
```

**Comment by arcanis** [comment]
As the error says, you're calling `yarn sdks`, but that command is only usable on PnP environments.

**Comment by TimRobertDev** [comment]
Damn I think I tried everything except removing that postInstall script, thanks ! 

What can I put instead that's usable in non PnP environment ?

**Comment by arcanis** [comment]
> What can I put instead that's usable in non PnP environment ?

You probably don't need the SDKs, so you can just remove it. The SDKs are only needed to integrate PnP w/ Eslint / TypeScript / etc.
