### ISSUE TITLE
[Bug?]: `nodeLinker: node-modules` is broken in Node.js 22.5.0

### ISSUE THREAD

**Issue by latin-1** [yarnpkg/berry#6398]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

On my local machine: freeze during the link step (clean install)
On CI: `Couldn't find the node_modules state file - running an install might help (findPackageLocation)`

### To reproduce

Repo: https://github.com/latin-1/berry-node-22.5.0-broken

Node.js 22.4.1:
https://github.com/latin-1/berry-node-22.5.0-broken/actions/runs/9978668516/job/27576055285

Node.js 22.5.0:
https://github.com/latin-1/berry-node-22.5.0-broken/actions/runs/9978678303/job/27576083419

### Environment

```shell
System:
    OS: Linux 6.9 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 6800U with Radeon Graphics
  Binaries:
    Node: 22.5.0 - /tmp/xfs-8a836774/node
    Yarn: 4.3.1 - /tmp/xfs-8a836774/yarn
    npm: 10.8.2 - ~/.proto/shims/npm
    pnpm: 9.5.0 - ~/.proto/shims/pnpm
    bun: 1.1.20 - ~/.proto/shims/bun
  npmPackages:
    jest: 29.7.0 => 29.7.0
```

**Comment by merceyz** [comment]
Bisects to https://github.com/nodejs/node/pull/53627

**Comment by anonrig** [comment]
Can you open a new issue to Node.js repository, with a reproduction that is easily reproducible without Yarn?

**Comment by merceyz** [comment]
Closing as Node.js v22.5.1 has been released with a fix for this issue.
