### ISSUE TITLE
Selective dependency resolutions Yarn version 4.3.1

### ISSUE THREAD

**Issue by Skyfury2651** [yarnpkg/berry#6413]
I wanted to  updated the dependency of nested inside firebase-tools due to Uncontrolled resource consumption while i running `snyk test`.  When i add resolutions  like below then `yarn install`
`
"resolutions": {
    "firebase-tools/chokidar/braces": "3.0.3"
 }
`

It end up with message from yarn then whole resolution ( any line that contains illegal characters ) being removed. 

![image](https://github.com/user-attachments/assets/6a7a3d46-e55e-4b39-8f80-edb07d36dfd2)

If i not include parent package it work but it seem not quite right since it's could effect other dependency that using `braces`
`
"resolutions": {
    "braces": "3.0.3"
 }
`
![image](https://github.com/user-attachments/assets/76ff9129-c0c9-499f-ad27-d97bc878d76b)

Anyone have any solution that for this , thank you for reading.

**Comment by arcanis** [comment]
Yarn only accepts a single level of specificity (ie one parent in the chain).

**Comment by Skyfury2651** [comment]
@arcanis Thank you for response. 
But according to those documents , in the example they have nested parent : 
https://yarnpkg.com/configuration/manifest#resolutions

![image](https://github.com/user-attachments/assets/18f05860-5476-4e39-abd2-5bfbeadc51b8)


https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/
![image](https://github.com/user-attachments/assets/e1b68611-776c-4bbe-ba86-3b3d11b7b21a)


And just in case i tried `chokidar/braces` but still end up with no luck , the error YN0057 still show up and remove my resolutions.
( I have checked yarn.lock and they still the same as before ).

By the way, do you have any suggest to patch this issue ? The parent repo not active since February

**Comment by arcanis** [comment]
> But according to those documents , in the example they have nested parent :

No, they all have a single parent at most.

> https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

The classic documentation (1.x only) is incorrect, and we never officially supported deep levels of resolution. The `**` token is now a syntax error to make that clearer, but it never worked as expected.

> And just in case i tried chokidar/braces but still end up with no luck , the error YN0057 still show up and remove my resolutions.

I'm not sure why you need the resolution - firebase-tools depends on chokidar 3.6, which depends on braces ~3.0.2, which can match 3.0.3 without `resolutions`. Just run `yarn up -R braces`.

**Comment by Skyfury2651** [comment]
Thank you for your support , i get it and will close this issue now.
