### ISSUE TITLE
[Bug?]: 

### ISSUE THREAD

**Issue by chenyulun** [yarnpkg/berry#6418]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

`vue-loader@^15.10.0`support `@vue/compiler-sfc@2.7.0`
https://v2.vuejs.org/v2/guide/migration-vue-2-7#Vue-CLI-webpack

but: somebody change the rule

https://github.com/yarnpkg/berry/pull/3152/files#diff-f9964fe90780d285e0498df8a32f713d5e362b9d59f7f63dd71ad73c4d7491e3

### To reproduce

```shell
mkdir test-vue-loader
cd $_
pnpm init
pnpm add vue-loader@15.11.1 @vue/compiler-sfc@2.7.16
```

### Environment

```shell
all
```

### Additional context

it should be: 
```ts
{
  [`vue-loader@<=16.3.1`, {
    peerDependencies: {
      '@vue/compiler-sfc': `^2.7.0 || ^3.0.8`,
      webpack: `^4.1.0 || ^5.0.0-0`,
    },
  }],
}
```

**Comment by chenyulun** [comment]
@merceyz  
https://github.com/yarnpkg/berry/pull/3152/files#diff-f9964fe90780d285e0498df8a32f713d5e362b9d59f7f63dd71ad73c4d7491e3

**Comment by arcanis** [comment]
For something like this, please directly open a PR.
