### ISSUE TITLE
[Bug] Invalid path to the global cache folder

### ISSUE THREAD

**Issue by zdm** [yarnpkg/berry#642]
**Describe the bug**
I am using following settings in my ```.yarntc.yml```:
```
globalFolder: d:/devel/.yarn
enableGlobalCache: true
```
I installed dependencies with ```yarn```, everything is ok. Then I am trying to lint the project:
```
yarn eslint src

Error: Couldn't find a suitable Node resolution for the specified unqualified path

Source path: /d:/gdrive/projects/devel/.yarn/cache/eslint-npm-6.7.2-932e9e7a3c-1.zip/node_modules/eslint/bin/eslint.js
Rejected resolution: /d:/gdrive/projects/devel/.yarn/cache/eslint-npm-6.7.2-932e9e7a3....
```
You can see. that path to the cache is invalid. According to my settings it shoud be:
```
/d:/devel/.yarn/cache/eslint-npm-6.7.2-932e9e7a3c-1.zip/node_modules/eslint/bin/eslint.js
```
**Environment if relevant (please complete the following information):**

 - OS: windows 10
 - Node 13.3.0
 - Yarn 2.0.0-rc19

**Comment by arcanis** [comment]
Can you try to set `/d:/` or `d:\` instead of `d:/`?

**Comment by zdm** [comment]
I tried /d: and d:\, results are the same.

**Comment by zdm** [comment]
It works only if ```globalFolder``` is relative.

**Comment by zdm** [comment]
I think I understood what is the problem. I am using same project directory both under windows and under vmware linux via vmware shared folders. So, when I run yarn under linux it created ```.pnp.js```, where all links to the packages are for linux file system, and project become unusable under windows.

I think, it will be better to store ``packageLocation``` in ```.pnp.js``` relative to the current yarn store folder.

**Comment by zdm** [comment]
Maybe this is also the root of the problem in the issue https://github.com/yarnpkg/berry/issues/645

**Comment by zdm** [comment]
Hmmm, the problem is not in vmare.
Now it creates such links ```packageLocation": "../../C:/Users/zdm/.yarn/global/cache/wrappy-npm-1.0.2-916de4d4b3-1.zip/node_modules/wrappy/",```.
So, the bug is definitely in how it stores paths to the packages in the global store.

**Comment by arcanis** [comment]
I'm almost positive this bug as been fixed (it was related to an invalid `__filename` usage), so I'm going to close the issue. Please reopen a new one if things still look fishy!
