### ISSUE TITLE
[Feature] yarn install --yes

### ISSUE THREAD

**Issue by Zamiell** [yarnpkg/berry#6451]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

### `yarn install` should have parity with `yarn init`

Currently, yarn `yarn init --yes`, for automatically saying yes to any prompts. This is a great feature and is really useful for CI/script environments specifically.

However, no such flag exists for `yarn install`.

### `yarn install` breaks in scripts/CI

Whenever I update the version of yarn in my "package.json" file and then run `yarn install`, it prompts me with a "y/n" dialog box, asking if I want to download the new version using corepack. However, this causes an infinite loop to happen in any script that runs `yarn install`, because it waits for user input, but the user input never comes.

Specifically, I have an update script that checks for a new version of yarn, and if there is, it automatically updates my package.json script, and then runs `yarn install`. This script has worked for years, but with the new "y\n" dialog box in the recent versions of yarn, this has broken my code.

## Describe the solution you'd like

A "--yes" flag would allow a script to pass that on the command line to bypass any end-user input in the same way that e.g. scripts do this when doing `yarn init`.

## Describe the drawbacks of your solution

Probably nothing besides the maintenance cost of adding another flag?

**Comment by merceyz** [comment]
That prompt is shown by Corepack, not Yarn.

Please open an issue with Corepack instead https://github.com/nodejs/corepack/issues.
