### ISSUE TITLE
[Feature] Allow install platform environment flag when postinstall scripts are disabled

### ISSUE THREAD

**Issue by Downchuck** [yarnpkg/berry#6463]
When fetching files to populate the yarn ".cache" it will use the current  platform - this is likely in part because there are many platform specific behaviors involved in creating the files.

When build scripts are disabled it would be nice to be able to fetch files into cache for a different platform, such as Python's pip can do with `--platform manylinux2014_x86_64`

Thus `yarn install --platform linux` or something of that nature, would grab the binary packages associated with linux even if run in windows. This assumes that post install scripts will not be run on dependencies, as there's no sense in trying to support those.

**Comment by arcanis** [comment]
[`supportefArchitectures`](https://yarnpkg.com/configuration/yarnrc#supportedArchitectures)

**Comment by Downchuck** [comment]
Anyone figured out if this can be passed as an environment variable? Complex types are not supported with the typical YARN_ env prefix style.
