### ISSUE TITLE
Doesn't work with @zeit/next-css

### ISSUE THREAD

**Issue by danteissaias** [yarnpkg/berry#649]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Doesn't work with `@zeit/next-css` package.

**To Reproduce**

* Install `react next react-dom @zeit/next-css`

* Create a `next.config.js` and put this in it:

```js
// next.config.js
const withCSS = require('@zeit/next-css')
module.exports = withCSS({
  /* config options here */
})
```

* Create a file at `pages/index.ts` and add this in it:

```js
export default () => <div>Hello world</div>
```

* Add a script to package.json that runs `next dev`

* Run that script

**Screenshots**

<img width="1179" alt="Screenshot 2019-12-26 at 19 08 03" src="https://user-images.githubusercontent.com/13090065/71487417-103acc80-2813-11ea-9e50-0c4489c2434c.png">

**Environment if relevant (please complete the following information):**

 - OS: MacOS
 - Node version v13.1.0
 - Yarn version 2.0.0-rc.19

**Comment by arcanis** [comment]
The error message clearly indicates that the problem comes from `next-css` which doesn't list `webpack` in its peer dependencies:

https://cdn.jsdelivr.net/npm/@zeit/next-css@1.0.1/package.json

**Comment by danteissaias** [comment]
Is the only solution to open an issue externally or fork and patch and use my own fork? Or is there a way to fix this by running some form of yarn command.

**Comment by arcanis** [comment]
You can use the [`packageExtensions`](https://next.yarnpkg.com/configuration/yarnrc#packageExtensions) setting to fix the problem locally, and if you get the chance to open a PR it'll be appreciated by people encountering this problem in the future 🙂

**Comment by danteissaias** [comment]
This is possible to fix with package extension, closing this issue.
