### ISSUE TITLE
Metadata cache key changes

### ISSUE THREAD

**Issue by drodil** [yarnpkg/berry#6508]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When I locally run `yarn install`, the `__metadata.cacheKey` in `yarn.lock` gets value of `10`. Once I push the change ro Github and CI runs it with `--immutable`, the key changes to `10c0` thus failing the build.

### To reproduce

Run install for this project: https://github.com/drodil/backstage-plugin-qeta

### Environment

```shell
Node 18
Yarn 4.5.0
```

### Additional context

I am not sure where the cache key comes from so probably it can be fixed with some configuration but not sure either if immutable install should change it?

**Comment by clemyan** [comment]
When you upgrade Yarn from v3 to v4, it automatically sets the `compressionLevel` config as part of the migration.

Based on your commit history, you have removed that config without running an install to update the lockfile.

**Comment by drodil** [comment]
I actually encountered this same issue with Yarn1 -> Yarn4 migration. CI for some reason gets the compression level of zero while locally it's mixed. Forcing the compression level to some value in `.yarnrc.yml` fixes the issue.
