### ISSUE TITLE
[Bug?]:Running yarn install or yarn add shows no response

### ISSUE THREAD

**Issue by mizi-lin** [yarnpkg/berry#6520]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Running yarn install or yarn add shows no response, similar to a timeout; occasionally, the command executes after waiting for a while.
However, running yarn upgrade-interactive responds quickly, and installing packages after selection works normally.
I suspect that when running yarn install or yarn add, it might be accessing certain special interfaces that are very slow.
Yes, I am in China.

### To reproduce

none

### Environment

```shell
System:
    OS: macOS 13.0
    CPU: (12) arm64 Apple M2 Max
  Binaries:
    Node: 20.14.0 - /private/var/folders/jn/q4y0c6gn69l8_ykzv1p7pmtr0000gn/T/xfs-54934e25/node
    Yarn: 4.5.0 - /private/var/folders/jn/q4y0c6gn69l8_ykzv1p7pmtr0000gn/T/xfs-54934e25/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
```

**Comment by BasixKOR** [comment]
Could you try disabling telemetry as shown by #6271?

**Comment by mizi-lin** [comment]
use `yarn dedupe` can install , 3q
