### ISSUE TITLE
[Bug] YARN_HOME environment variable

### ISSUE THREAD

**Issue by hackers267** [yarnpkg/berry#653]
- [ ] When I use 'yarn install', the console "Usage Error: Unrecognized or legacy configuration settings found: home - run "yarn config -v" to see the list of settings supported in Yarn (in <environment>)"

**Describe the bug**

I use the `yarn install`, but the bug is like up; Then I use the `yarn config -v', the output includes: "➤ YN0034: Invalid configuration key "home" in <environment>", and `process.env' includes "YARN_HOME: 'C:\\Users\\<user_name>\\AppData\\Local\\Yarn\\bin'"

**To Reproduce**

run 'yarn install'

IMPORTANT: We strongly prefer reproductions that use Sherlock. Please check our documentation for more information: https://next.yarnpkg.com/advanced/sherlock

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: [e.g. OSX, Linux, Windows, ...]
 - Node version [e.g. 8.15.0, 10.15.1, ...]
 - Yarn version [e.g. 2.0.0-rc1, ...]
-Yarn: v1-> v1.21.1
-Yarn: v2->2.0.0-rc.19
-node: v12.14.0
-OS: windows10 19356
**Additional context**

**Comment by arcanis** [comment]
This isn't a bug, the `YARN_` environnement values are reserved for the Yarn settings. Why do you use `YARN_HOME`?

**Comment by hackers267** [comment]
I don't know why the "process.env" has the "YARN_HOME", the yarn v1, I use the scoop to install. Could this be the cause?

**Comment by arcanis** [comment]
Possibly. What's the value of `YARN_HOME`?

**Comment by arcanis** [comment]
Did you find the reason for `YARN_HOME`?

**Comment by matthias-ccri** [comment]
Also ran into this. There's another software product called "yarn" related to Apache Hadoop.
```
$ echo $YARN_HOME
/opt/devel/tools/hadoop
```

Is there a way to sidestep this error message? Everybody at my company has `YARN_HOME` set, from a boilerplate bashrc, so this will make it harder to adopt yarn 2.

**Comment by arcanis** [comment]
If we know where the variable comes from then yes, we can make an exception
for known keys (we already have a few). Those are in Configuration.ts, if
you wish to open a PR (I'm not in front of my computer right now).

**Comment by matthias-ccri** [comment]
Sure, I've started a PR here: https://github.com/yarnpkg/berry/pull/3005

**Comment by bbrzoska** [comment]
Another one of those is `YARN_CACHE` which is set by one of the Github Actions automatically. Spent some time trying to understand what's going on.

**Comment by bbrzoska** [comment]
It would be great if Yarn would return a better error for this. For example, instead of

```
➤ YN0034: Invalid configuration key "cache" in <environment>
```

it could be something like:

```
➤ YN0034: Invalid configuration key "cache" in <environment>. Did you accidentally set the YARN_CACHE environment variable?
```

Cause I spent like an hour debugging the problem and found out the reason is that I've created an env variable (for my own use) that's called YARN_CACHE. I had no idea that yarn will complain for env variables that are private? Perhaps yarn shouldn't even be enumerating the whole `env`... just care about its own stuff and emit a warning, rather than a hard error?

**Comment by avandax** [comment]
`YN0034: Invalid configuration key "path" in <environment>`

**Comment by prafed** [comment]
> This isn't a bug, the `YARN_` environnement values are reserved for the Yarn settings. Why do you use `YARN_HOME`?

OMG! Thank you... I was outputing a custom ENV variable form Github Actions with the prefix of "yarn_*" and I was getting some really weird errors!

Turns out you should not name your exports with "YARN_*" as that conflicts ..

**Comment by mzvast** [comment]
I encounter the same issue, I fixed it by unset related env
```bash
unset $(printenv | grep '^YARN_' | cut -d= -f1)
```

**Comment by ssuvorov** [comment]
Gosh! So misleading. 
I named an env variable YARN_PRIVATE_MB_REPO_AUTH=... and got this error:
`YN0034: Invalid configuration key "privateMbRepoAuth" in <environment>`
As mentioned above, don't start your variables with YARN_

👎 However in the docs https://yarnpkg.com/configuration/yarnrc#npmAuthIdent
> Finally, note that most settings can also be defined through environment variables (at least for the simpler ones; arrays and objects aren't supported yet). To do this, just prefix the names and write them in snake case: YARN_CACHE_FOLDER will set the cache folder (such values will overwrite any that might have been defined in the RC files - use them sparingly).

Just prefix the name and then writing "YARN_" explains us exactly the opposite. That we should name variables with YARN_
