### ISSUE TITLE
[Bug?]: the 'postinstall' script is not executed when running 'yarn install'

### ISSUE THREAD

**Issue by YaoHuiJi** [yarnpkg/berry#6544]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

The 'postinstall' script is not automatically executed when running 'yarn install',  but 'yarn run postinstall' works

package.json
```
"scripts": {
		"postinstall": "echo '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@'",
	},
```

.yarnrc.yml
```
nodeLinker: node-modules
enableScripts: true
yarnPath: .yarn/releases/yarn-4.4.1.cjs
```

yarn install
```
➤ YN0000: · Yarn 4.4.1
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 494ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ eslint is listed by your project with version 9.10.0 (pc6ea3), which doesn't satisfy what eslint-plugin-import and other dependencies request (but they have non-overlapping ranges!).
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 4s 987ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 1s 410ms
➤ YN0000: · Done with warnings in 7s 66ms
```

yarn run postinstall
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

```

### To reproduce

run 'yarn install'

### Environment

 System:
    OS: macOS 13.6.1
    CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
  Binaries:
    Node: 20.10.0 - /private/var/folders/4w/69gblgzx3111pg1w3t6whsgm0000gn/T/xfs-c44d8ae0/node
    Yarn: 4.4.1 - /private/var/folders/4w/69gblgzx3111pg1w3t6whsgm0000gn/T/xfs-c44d8ae0/yarn
    npm: 10.2.3 - /usr/local/bin/npm
  npmPackages:
    jest: ^29.6.3 => 29.7.0

**Comment by clemyan** [comment]
Output of build scripts are hidden unless it failed or [`enableInlineBuilds`](https://yarnpkg.com/configuration/yarnrc#enableInlineBuilds) is set.

Also, build scripts are not run on every install. A package's build script is only run if:

- it was just added to the project
- one of its dependencies (direct or transitive) changed, or
- the script failed the last time it ran

**Comment by Nantris** [comment]
What about when I define a `postinstall` in my own project though? That doesn't seem to run reliably either.

**Comment by clemyan** [comment]
The conditions I wrote above still apply. A `postinstall` script of a workspace runs only if the workspace itself satisfies one of three.

**Comment by ClementValot** [comment]
Note: It appears like the behavior is different on Windows and MacOS, just tested on two machines with the same config: 

```
yarn 
rm -rf node_modules/some-package
yarn 
```
On the second `yarn`, `postinstall` is triggered on Windows, but not on MacOS. 

@clemyan what do you think?
