### ISSUE TITLE
[Bug]: enableGlobalCache doesn't work properly

### ISSUE THREAD

**Issue by sequencerr** [yarnpkg/berry#6562]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

enableGlobalCache: false
set custom global cache dir,
yarn install,
stores cache both to global dir and to the user defined one.

### To reproduce

`YARN_CACHE_FOLDER="$XDG_CACHE_HOME/yarn" YARN_ENABLE_GLOBAL_CACHE=false yarn`

### Environment

OS: Linux 6.10 Debian GNU/Linux 12 (bookworm)
Yarn: 4.5.1 - /tmp/xfs-b8d0ec6c/yarn

type yarn
yarn is hashed (/home/###/.local/bin/yarn)

**Comment by arcanis** [comment]
`YARN_ENABLE_GLOBAL_CACHE` is misnamed, and actually controls whether Yarn use the local cache or not. Whether it uses the global folder as well as the local cache is controlled by a different setting, [`enableMirror`](https://yarnpkg.com/configuration/yarnrc#enableMirror).
