### ISSUE TITLE
[Bug]: yarn dlx duplicates os release version

### ISSUE THREAD

**Issue by sequencerr** [yarnpkg/berry#6563]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

yarn dlx duplicates os release version.
I see x2 `12 (bookworm)`

### To reproduce

`yarn dlx -q envinfo --preset jest`
`OS: Linux 6.10 Debian GNU/Linux 12 (bookworm) 12 (bookworm)`

### Environment

.

**Comment by arcanis** [comment]
I don't understand this bug report.

**Comment by sequencerr** [comment]
Hello. Is printing `12 (bookworm) 12 (bookworm)` intended?
