### ISSUE TITLE
[Bug?]: selective binary by OS and Node version

### ISSUE THREAD

**Issue by rtritto** [yarnpkg/berry#6565]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

After `uWebSockets.js` is installed, all OS and Node versions are built.

### To reproduce

- `yarn init -y`
- `yarn set version berry`
- `yarn add uWebSockets.js@github:uNetworking/uWebSockets.js#v20.49.0`
- open directory `/.yarn/unplugged/uWebSockets.js-https-<HASH>/node_modules/uWebSockets.js`
- `.node` files are 24 (_uws_darwin_*_, _uws_linux_*_, _uws_win32_*_)

### Expected
In directory `/.yarn/unplugged/uWebSockets.js-https-<HASH>/node_modules/uWebSockets.js` there is only 1 file filtered by OS and Node version

### Environment

System:
  OS: Windows 11 10.0.22631
Binaries:
  Node: 22.9.0 - ~\AppData\Local\Temp\xfs-7275780b\node.CMD
  Yarn: 4.5.1 - ~\AppData\Local\Temp\xfs-7275780b\yarn.CMD
  npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD

### Additional context

Related comment https://github.com/uNetworking/uWebSockets.js/issues/1112#issuecomment-2426338659

**Comment by larixer** [comment]
@rtritto Have you tried to specify `supportedArchitectures` in `.yarnrc.yml`?
https://yarnpkg.com/configuration/yarnrc#supportedArchitectures

**Comment by rtritto** [comment]
There is a way to autodetect? In the CI, I'm using Windows and Linux.

**Comment by larixer** [comment]
@rtritto It's not an issue in Yarn Berry or any other package manager. The issue is how `uNetworking/uWebSockets.js` is distributed. They don't use `os` and `cpu` fields of `package.json` and instead distribute all platform specific files in a single package:
https://github.com/uNetworking/uWebSockets.js/tree/v20.49.0
