### ISSUE TITLE
[Bug?]: Installing any project with Yarn is a virus

### ISSUE THREAD

**Issue by fulldecent** [yarnpkg/berry#6599]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

The documentation for how to install some project with Yarn Berry is at 

https://yarnpkg.com/getting-started/install#updating-yarn

and relevant part:

```sh
yarn set version stable
```

This results in the project.json file being updated so that every other person using the project must also use Yarn.

That is the definition of a computer virus.

At a minimum, that side effect should be disclosed in that documentation.

### To reproduce

https://yarnpkg.com/getting-started/install#updating-yarn

### Environment

```shell
System:
    OS: macOS 15.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 22.11.0 - /private/var/folders/02/1n_qs97x3f17c9csq1rppqqw0000gn/T/xfs-c1acffbf/node
    Yarn: 4.5.1 - /private/var/folders/02/1n_qs97x3f17c9csq1rppqqw0000gn/T/xfs-c1acffbf/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
```

**Comment by arcanis** [comment]
> That is the definition of a computer virus

That is not the definition of a computer virus
