### ISSUE TITLE
[yarn audit] Getting error when run "yarn audit"

### ISSUE THREAD

**Issue by kientrant1** [yarnpkg/berry#6607]
I'm using yarn version 4.1.0. When run "yarn audit", I get this error message:

`Usage Error: Couldn't find a script named "audit".`
`$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] [--require #0] <scriptName>`

Is there any way to resolve this issue?

**Comment by clemyan** [comment]
You are probably looking for [`yarn npm audit`](https://yarnpkg.com/cli/npm/audit)

**Comment by kientrant1** [comment]
Thanks @clemyan. It's thing that I'm looking. This also supports to ignore some packages in [Settings (.yarnrc.yml)](https://yarnpkg.com/configuration/yarnrc#npmAuditIgnoreAdvisories)
