### ISSUE TITLE
[Compatibility] generate typescript patch for `typescript@5.7.2`

### ISSUE THREAD

**Issue by davidfiala** [yarnpkg/berry#6624]
I'd like to kindly request an updated PNP patch for `typescript@5.7.2`

@merceyz usually appears to take on this toil task themselves. Thank you! 🙏

---

Forward looking:

Looking at the history of these patches, I don't see many functional changes in recent patches. Just version number bumps, I think.

Is there any specific reason that we need to fail-closed when a new version (alpha, beta, rc, or release) of typescript is released?

Is there anything users can manually do on their repos to make a best-effort attempt to use the highest available patch, even if the vesion number isn't recognized?

**Comment by merceyz** [comment]
I created a release with the updated patch about 2 weeks ago: https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F4.5.2

I've created one for Yarn v3 now in case that's what you were referring to: https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F3.8.7

> Looking at the history of these patches, I don't see many functional changes in recent patches. Just version number bumps, I think.

If it was just that, it would've been automated a long time ago.

> Is there any specific reason that we need to fail-closed when a new version (alpha, beta, rc, or release) of typescript is released?

Sometimes upstream changes their code such that the patch doesn't apply any more (merge conflict) so it has to be rebased.

> Is there anything users can manually do on their repos to make a best-effort attempt to use the highest available patch, even if the vesion number isn't recognized?

No, that's done by default, take a look at the SemVer ranges in https://github.com/yarnpkg/berry/blob/aa557feba4b2b115f5dd317bafb084ac99c95d46/packages/plugin-compat/extra/typescript/gen-typescript-patch.js#L25-L314
