### ISSUE TITLE
[Bug?]: All packages returning 404 for registry registry.yarnpkg.com

### ISSUE THREAD

**Issue by johnshroff** [yarnpkg/berry#6627]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

It appears that all packages are returning 404s from the registry https://registry.yarnpkg.com.  Here is an example:
![Image](https://github.com/user-attachments/assets/0d3eeb5b-6ec1-49c9-8fe4-754afac99221)

This is happening on every package I try.  In the browser I get this:
{"error":"Not found"}

It started about an hour ago.

### To reproduce

run `yarn add turbo`

### Environment

```shell
System:
  OS: macOS 14.5
Binaries:
  Node: 22.6.0
  Yarn: 4.1.0
  Nom: 10.8.2
```

**Comment by garrylachman** [comment]
here too....

**Comment by rohaquinlop** [comment]
Same here

```
0.213 yarn install v1.22.22
0.258 [1/4] Resolving packages...
0.466 [2/4] Fetching packages...
1.128 error Error: https://registry.yarnpkg.com/@testing-library/jest-dom/-/jest-dom-5.17.0.tgz: Request failed "404 Not Found"
1.128     at ResponseError.ExtendableBuiltin (/opt/yarn-v1.22.22/lib/cli.js:696:66)
1.128     at new ResponseError (/opt/yarn-v1.22.22/lib/cli.js:802:124)
1.128     at Request.<anonymous> (/opt/yarn-v1.22.22/lib/cli.js:66750:16)
1.128     at Request.emit (node:events:513:28)
1.128     at module.exports.Request.onRequestResponse (/opt/yarn-v1.22.22/lib/cli.js:142287:10)
1.128     at ClientRequest.emit (node:events:513:28)
1.128     at HTTPParser.parserOnIncomingClient (node:_http_client:710:27)
1.128     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
1.128     at TLSSocket.socketOnData (node:_http_client:552:22)
1.128     at TLSSocket.emit (node:events:513:28)
1.128 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by garrylachman** [comment]
looks like its back alive...

**Comment by NoahvdAa** [comment]
Probably caused by [the scheduled maintenance at NPM](https://status.npmjs.org/incidents/px35z3dmcjgm)?

> We will be conducting a scheduled infrastructure upgrade that may temporarily impact publishing and certain website functionalities. While some features will remain operational, like installations and search, minor inefficiencies may occur. Normal operations are expected to resume following the maintenance window.
