### ISSUE TITLE
[Feature] Support for `.yaml` extension

### ISSUE THREAD

**Issue by RomainLanz** [yarnpkg/berry#6638]
Hey there! 👋🏻 

Currently, Yarn only supports the `.yml` extension for configuration files and scaffolds the `.editorconfig` file with support for `.yml` and not `.yaml`. However, according to the [YAML FAQ](https://yaml.org/faq.html), the `.yaml` extension is recommended and should be used when possible.

I would like to propose that Yarn:

1. Allow configuration files with the `.yaml` extension in addition to `.yml`.
2. Scaffold `.editorconfig` with support for the `.yaml` extension.

**Comment by arcanis** [comment]
Duplicate with #3535
