### ISSUE TITLE
[Feature] Make gen_enforced_field fixable

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/berry#68]
> **Update** The rule itself got implemented in #120, but it isn't fixable yet.

**Describe the user story**

I'm a project owner and I'd like to enforce that all the packages within my repository are private.

**Describe the solution you'd like**

The package constraints should expose a `gen_workspace_field_requirement` predicate that would instruct the constraint engine to make sure that a specific field from the `package.json` contains a specific value.

**Describe the drawbacks of your solution**

I don't think there is many drawbacks. The main one would be cluttering the code, but I think this might be a common enough use case to warrant it (I'd be happy to use it on this very repository, for example).

**Describe alternatives you've considered**

We could let it to our users to write their own rules (together with something like `eslint`). That could get relatively complex to setup though, and given that the constraints plugin already do very similar tasks it would make more sense to support it there imo.

**Comment by bgotink** [comment]
Some usecases where I'd like to use this:

- enforce `sideEffects` property to be set to allow webpack to treeshake entire packages
- enforce consistent `version` values throughout the repo, as we work similar to angular where every package in a repo has the same version
- enforce that a property is set that our UX team uses to parse package files automatically and link our packages to the corresponding components on their side
