### ISSUE TITLE
[Bug] Remove question mark from URL in v2

### ISSUE THREAD

**Issue by Haroenv** [yarnpkg/berry#694]
- [x] I'd be willing to implement a fix

**Describe the bug**

URLs now are like: https://next.yarnpkg.com/package/?@wavevision/class-name

in V1 the URL is https://next.yarnpkg.com/package/@wavevision/class-name

This breaks file URLs, since they assumed the query string wasn't set yet: https://next.yarnpkg.com/package?%40wavevision%2Fclass-name&files

**To Reproduce**

Go to any package detail URL, see the extra ?
**Additional context**

Any change from v1 to v2 will be a _Breaking_ change if the URL is changed, so this needs to be fixed :)

**Comment by arcanis** [comment]
Yep! It was initially a `?` because the website was deployed through GitHub Pages which don't support that, but moving back to a regular `/` is all good for me. Can I ask you to look into it?
