### ISSUE TITLE
Write new documentation pages.

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/berry#7]
**Describe the user story**

I'm a Yarn user and I want to learn more about its inner working.

**Describe the solution you'd like**

The missing pages from the [documentation](docs) should be implemented.

**Comment by nickbalestra** [comment]
Before I open a new issues I thought was worth posting it here about "improving current documentation pages" as well.
Specifically, we have a [migration page](https://yarnpkg.github.io/berry/advanced/migration) and could be good to add some sort of troubleshooting guide.

Here few example I was thinking of:
- Undeclared peer dependency issues
- Accessing  in-zip path from scripts via `yarn node` (ie to set up git hooks)

In relation to documentation perhaps we could also improve the contributing page in berry by borrowing some content from https://yarnpkg.com/en/org/contributing/ and enriching it.

What are your thoughts in this direction?

**Comment by arcanis** [comment]
Yup I agree. Mentioning the `good first issue` and `help wanted` tags in the contributing guide in particular is something I didn't think before but would make a ton of sense 👍

**Comment by onigoetz** [comment]
I'd like to help on this, is there a list of pages that are missing ?

**Comment by arcanis** [comment]
*(One problem is that the website is currently broken; waiting for https://github.com/gatsbyjs/gatsby/pull/14208 and https://github.com/gatsbyjs/gatsby/pull/14209 to be merged and released before I can fix it. As a short term fix you can set `pnpFallbackMode: all` in the `.yarnrc` file and it should work after a fresh `yarn install`)*

We were starting to discuss it with @olingern: it would be good to write a "Migrating from v1" page within the "Getting started" section. There's already one in the "Advanced" section but it's more a troubleshooting page than an actual guide.

Apart from I think that we would benefit from a page detailing the TypeScript workflow (in Advanced, likely). It's already covered a bit with the "PnPify" page, but there are more options that we should list , such as ts-loader and fork-ts-checker-webpack-plugin (and make it easy to figure out which one to use depending on the case) cc @johnnyreilly

The "Contributing" page could be improved a bit; in particular to explain how to rebuild the website (it's just a `yarn develop` in `packages/gatsby`; one trick is that it requires a `yarn install` before because there are native dependencies that need to be built).

Finally I'd really like us to work a bit on the package page. It's currently hidden (it should be https://yarnpkg.github.io/berry/package?webpack but it seems broken at the moment; that's how hidden it is 😅). Ideally we should have the same features as on the current website (particularly the [package listing view](https://yarnpkg.com/en/package/lodash?files) which is super-useful for us as maintainers) cc @Haroenv

**Comment by johnnyreilly** [comment]
> Apart from I think that we would benefit from a page detailing the TypeScript workflow (in Advanced, likely). It's already covered a bit with the "PnPify" page, but there are more options that we should list , such as ts-loader and fork-ts-checker-webpack-plugin (and make it easy to figure out which one to use depending on the case) cc @johnnyreilly

Yup, as discussed in https://github.com/arcanis/pnp-webpack-plugin/pull/10 I'm putting together some examples of how to work TypeScript / webpack with yarn PnP.  Once I've got them in a good state I'd be happy to use that as a basis to provide some documentation. 

Docs are the most important onboarding feature 😁

**Comment by arcanis** [comment]
Lots of pages have been added since I opened this issue. Closing for now!
