### ISSUE TITLE
[Bug] cache didn't use `cacheFolder`

### ISSUE THREAD

**Issue by bluelovers** [yarnpkg/berry#708]
- [ ] I'd be willing to implement a fix

**Describe the bug**

cache didn't use config `cacheFolder`

it save cache at `C:\Users\User\AppData\Local\Yarn\Berry\cache`

**To Reproduce**

The _minimal_ information needed to reproduce your issue (ideally a package.json with a single dep). Note that bugs without minimal reproductions might be closed.

IMPORTANT: We strongly prefer reproductions that use Sherlock. Please check our documentation for more information: https://next.yarnpkg.com/advanced/sherlock

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: [e.g. OSX, Linux, Windows, ...]
 - Node version [e.g. 8.15.0, 10.15.1, ...]
 - Yarn version [e.g. 2.0.0-rc1, ...]

**Additional context**

**Comment by arcanis** [comment]
Sorry, this issue is quite below the bar I set for the ones I investigate. Please read the instructions carefully and provide me a way to reproduce your issue.
