### ISSUE TITLE
How to get workspaces in given directory

### ISSUE THREAD

**Issue by futagoza** [yarnpkg/berry#712]
I've been using [get-yarn-workspaces](https://github.com/viewstools/yarn-workspaces-cra-crna/tree/master/get-yarn-workspaces) to get a list of my workspaces (for various custom scripts), but going forward I thought I should make my own package that I can easily update if required.

There are 3 ways I can proceed with this:

1. Copy/paste get-yarn-workspaces and update
2. Run `yarn -s workspaces info` via the child_process module (see [this post](https://github.com/viewstools/yarn-workspaces-cra-crna/issues/28#issuecomment-452160613))
3. Use an official API

I decided to start with 3 and fall back to 2 if it doesn't work.

Looking at `@yarnpkg/core` I found `WorkspaceFetcher` but glancing at the code I get the impression this gets information (or something else) of a _known_ workspace passed by arguments, am I right?

If so, can you tell me how I can use the official API to simply return a list of workspaces like the get-yarn-workspaces package does.

**Comment by arcanis** [comment]
Hey! This is what listing the workspaces would look like with the core functions:

```ts
const {getPluginConfiguration} = require(`@yarnpkg/cli`);
const {Configuration, Project, structUtils} = require(`@yarnpkg/core`);

async function main() {
    const cwd = process.cwd();

    const configuration = await Configuration.find(cwd, getPluginConfiguration());
    const {project} = await Project.find(configuration, cwd);

    for (const workspace of project.workspaces) {
        console.log(structUtils.prettyLocator(configuration, workspace.locator));
    }
}

main().catch(error => {
    process.exitCode = 1;
    console.error(error.stack);
});
```

**Comment by futagoza** [comment]
Thank you @arcanis, will try this tomorrow when I get home 👍

**Comment by arcanis** [comment]
Closing for now, feel free to reopen if it doesn't work 🙂
