### ISSUE TITLE
API usage examples

### ISSUE THREAD

**Issue by sarpik** [yarnpkg/berry#713]
Hello, I'm trying to use `@yarnpkg/core` to programatically install dependencies & run some yarn scripts.

I haven't found much information about using the API - is this a work-in-progress, or am I just looking the wrong way? Thanks!

**Comment by arcanis** [comment]
Hey! The API documentation hasn't been written yet as we were focusing on the CLI, but you can check how plugins work to get an idea how the API works.

**Comment by sarpik** [comment]
@arcanis aight will do, thanks! & best of luck with the v2 - looks spicy

**Comment by Randgalt** [comment]
@arcanis can you point to any sample code at all? I spent many hours trying to configure things and it's hunt-and-guess. Any simple starter code would be appreciated.
