### ISSUE TITLE
[Bug] The n_m linker doesn't support running `yarn install` outside of the root dir

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/berry#714]
**Describe the bug**

Running `yarn install` within a subdirectory of a project will cause errors, because the package location map stores the path relative to the root (which is a good thing) but doesn't resolve them back when reading the file.

**To Reproduce**

Run `YARN_NODE_LINKER=node-modules yarn install` in the `packages` directory.

**Additional context**

**Comment by larixer** [comment]
Fixed by: #717
