### ISSUE TITLE
[Feature] wildcard packageExtensions, easier v1 -> v2 migration

### ISSUE THREAD

**Issue by andreialecu** [yarnpkg/berry#729]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

I've been experimenting with migrating a project from yarnv1 to yarnv2 and had a pretty bad time with dependencies. :)

I ended up with a huge `yarnrc.yml` file in order to patch missing dependencies in almost every package. I realize this is a problem with the specific packages themselves, but I feel that getting them all fixed won't happen very soon and it's a very common issue that will hurt v2/berry adoption.

**Describe the solution you'd like**

I feel like allowing wildcards in `packageExtensions` might alleviate some of the pain, but I'm not sure if there are any downsides from a performance perspective.

For example, a ton of dependencies in an **Angular** project don't reference `rxjs` as a dependency, but use types from it. Even core angular packages like `@angular/cdk`, or `@angular/material` are missing dependencies such as `rxjs` or `@angular/platform-browser`. Most third party angular components miss things like `@angular/core` or `@angular/forms`

I suggest the possibility of allowing wildcards in `packageExtensions` so it is possible to do this:

```
packageExtensions:
  # all packages get rxjs as a peer dependency
  "*@*":
    peerDependencies:
      rxjs: "*"
  # or packages starting with @angular/* get rxjs as a peer dependency
  "@angular/*@*":
     peerDependencies:
       rxjs: "*"
  # or packages starting with ng* get a list of peer dependencies
  "ng*@*":
    peerDependencies:
       "@angular/core": "*"
       "@angular/forms": "*"
```

Even if some dependencies end up in packages that don't need them, this shouldn't be a problem.

An alternative idea would be to allow some sort of `lax` mode (as opposed to strict), in which a list of **all** packages automatically get added as `peerDependencies` available to every single package, esentially resulting in behavior similar to yarn v1/npm. Perhaps via a flag in `yarnrc.yml` (`strict: false`). In this case packages could steal dependencies from others, just like pre v2 would. I'm not sure what the drawback would be, or why it wasn't considered before.

**Describe the drawbacks of your solution**

Not sure if there would be performance implications of that, or if it's even feasible to implement, but it would probably make migration to berry much easier.

I understand that the purpose of berry is to be strict about dependencies, but I feel adoption will be greatly impacted if easier workarounds aren't available.

**Describe alternatives you've considered**

The alternative is to keep running or building projects by trial and error to see which deps are missing until finally none are. I'll attach how my `yarnrc.yml` file ended up looking, at the bottom, for context. This took quite a long time to get right.

**Additional context**

```
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"
packageExtensions:
  webpack-dev-server@*:
    peerDependencies:
      webpack-cli: "*"
  webpack@*:
    peerDependencies:
      webpack-cli: "*"
  "@ngtools/webpack@*":
    peerDependencies:
      "@angular/core": "*"
  apollo-angular@*:
    peerDependencies:
      graphql: "*"
  apollo-angular-link@*:
    peerDependencies:
      rxjs: "*"
      apollo-utilities: "*"
  apollo-angular-link-http@*:
    peerDependencies:
      rxjs: "*"
      apollo-utilities: "*"
  apollo-angular-link-http-common@*:
    peerDependencies:
      rxjs: "*"
      apollo-utilities: "*"
  apollo-angular-link-http-batch@*:
    peerDependencies:
      rxjs: "*"
      apollo-utilities: "*"
  "@nicky-lenaers/ngx-scroll-to@*":
    peerDependencies:
      rxjs: "*"
  angular2-signaturepad@*:
    peerDependencies:
      "@angular/core": "*"
  ng2-ui-switch@*:
    peerDependencies:
      "@angular/core": "*"
      "@angular/forms": "*"
  ng-pick-datetime@*:
    peerDependencies:
      rxjs: "*"
      "@angular/common": "*"
      "@angular/core": "*"
      "@angular/animations": "*"
      "@angular/forms": "*"
  "@angular/cdk@*":
    peerDependencies:
      rxjs: "*"
  "@angular/material@*":
    peerDependencies:
      rxjs: "*"
      "@angular/platform-browser": "*"
  ngx-bootstrap@*:
    peerDependencies:
      rxjs: "*"
      "@angular/core": "*"
      "@angular/animations": "*"
      "@angular/forms": "*"
  "@angular/platform-browser@*":
    peerDependencies:
      "@angular/animations/browser": "*"
      "@angular/animations": "*"
  "@agm/core@*":
    peerDependencies:
      rxjs: "*"
  "@handsontable/angular@*":
    peerDependencies:
      "@angular/core": "*"
  "@ngx-loading-bar/core@*":
    peerDependencies:
      rxjs: "*"
      "@angular/core": "*"
      "@angular/common": "*"
  "@ngx-loading-bar/http-client@*":
    peerDependencies:
      rxjs: "*"
      "@angular/core": "*"
      "@angular/common": "*"
  mydatepicker@*:
    peerDependencies:
      "@angular/core": "*"
      "@angular/forms": "*"
      "@angular/common": "*"
  angular2-text-mask@*:
    peerDependencies:
      "@angular/core": "*"
      "@angular/forms": "*"
  "@zerohouse/router-tab@*":
    peerDependencies:
      "rxjs": "*"
  sass-loader@*:
    peerDependencies:
      sass: "*"
```

**Comment by arcanis** [comment]
Hey! So there was a reason I didn't implement glob patterns: I wanted problematic dependencies to be explicitly referenced. The reason for this is that we have a [compatibility plugin](https://github.com/yarnpkg/berry/tree/master/packages/plugin-compat), and I think it would make sense to ship a set of default extensions - at least as a first step, until we can remove them. In order to populate the initial dataset I was toying with the idea of building "analytics" of package extensions (opt-in), which would require to have explicit names to be efficient.

> In this case packages could steal dependencies from others, just like pre v2 would. I'm not sure what the drawback would be, or why it wasn't considered before.

I considered it, but it would have huge technical drawbacks. Packages that list peer dependencies are computationally very heavy because they require post-resolution passes and, even worse, need to be instantiated exactly once for each set of dependencies they have. In this context, adding peer dependencies to everything would cause Yarn to instantiate all packages as many time as they are found in the dependency tree, causing huge starting time / memory consumption issues.

**Comment by arcanis** [comment]
Started implementing the builtin package extensions in #733 - you're very welcome to help us by contributing to this list!

Closing this issue for now as I think I've explained why the "wildcard" strategy isn't the most efficient and provided an alternative.
