### ISSUE TITLE
[Bug] yarn constraints fix doesn't do anything if one unfixable error is found

### ISSUE THREAD

**Issue by bgotink** [yarnpkg/berry#73]
**Describe the bug**

If there's at least one unfixable error in the contstraints, the entire `yarn constraints fix` command is useless: it runs but doesn't change any of the package manifests.

**To Reproduce**

Run `yarn constraints fix` in master, hit `yes` a couple of times, notice nothing has changed after the command completes.

This is caused by the return in the `if (result.invalidDependencies)` block:

https://github.com/yarnpkg/berry/blob/4c62861c900f5cf04cab6672ba92bdf019b9cff5/packages/plugin-constraints/sources/commands/constraints/fix.ts#L104

**Comment by arcanis** [comment]
Fixed in #74!
