### ISSUE TITLE
[Bug] VSCode pnpify is a no-op (workspaces)

### ISSUE THREAD

**Issue by milesj** [yarnpkg/berry#750]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I run `yarn pnpify --sdk` and it outputs "Nothing to do.".

**To Reproduce**

https://github.com/milesj/build-tool-config/pull/10

**Screenshots**

<img width="353" alt="Screen Shot 2020-01-24 at 21 38 19" src="https://user-images.githubusercontent.com/143744/73116829-df24e900-3ef1-11ea-86ce-d86bdef7a3bc.png">

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version 10.18
 - Yarn version 2.0.0-rc1

**Additional context**

I have this in `.vscode/settings.json`.

```
{
  "files.exclude": {
    "node_modules/@milesj/build-tools/**/configs/": true,
    "node_modules/@milesj/build-tools/**/dotfiles/": true,
    "node_modules/@milesj/build-tools/**/scripts/": true,
    "packages/core/**/configs/": true,
    "packages/core/**/dotfiles/": true,
    "packages/core/**/scripts/": true,
    "**/.vscode/": true,
    "**/node_modules/": true,
    "**/.eslintrc.js": true,
    "**/.eslintignore": true,
    "**/.prettierignore": true,
    "**/prettier.config.js": true,
    "**/test.log": true,
    "**/tsconfig.eslint.json": true,
    "**/yarn-error.log": true,
    "**/babel.config.js": true,
    "**/jest.config.js": true,
    "**/*.tsbuildinfo": true,
    "packages/core/configs": true,
    "packages/core/scripts": true,
    "packages/core/templates": true,
    "**/*.d.ts": true,
    "**/*.d.ts.map": true
  }
}
```

**Comment by deini** [comment]
👋 It is expecting prettier, typescript, and eslint as dependencies at the root level.

**Comment by milesj** [comment]
@deini Perhaps it should also look through workspace packages, because that is not apparent at all.

**Comment by milesj** [comment]
Did that and installed all the SDKs, set the TS version in VSCode, yet the TS imports still won't resolve.
<img width="639" alt="Screen Shot 2020-01-24 at 22 09 53" src="https://user-images.githubusercontent.com/143744/73117164-447ad900-3ef6-11ea-938a-8238143b9e27.png">

**Comment by larixer** [comment]
@milesj Yarn 2 is strict about dependencies. Your package `@milesj/build-tool-config` located in `packages/config` does not declare dependency on `@beemo/core`, but uses it. If you add `@beemo/core` to `packages/config/package.json` dependencies, run `yarn` and restart VS Code the problem will be gone. We need to add TypeScript watch support to v2 `compat` plugin, thats why the VS Code restart step is required for now

**Comment by bodinsamuel** [comment]
+1 on this

As stated Typescript is most probably installed globally, but not required by Typescript so yarn should not assume this, in my opinion. (e.g: you can have mixed codebase).
This is even more clear with stylelint, in monorepo UI/design can be (will be) in a separate workspace.

**Comment by larixer** [comment]
Closing issue, since I have answered the author on its original issue. @bodinsamuel Please open a new issue, since your issue is different
