### ISSUE TITLE
[Bug] initial install with @yarnpkg/plugin-node-modules never end

### ISSUE THREAD

**Issue by sasurau4** [yarnpkg/berry#751]
- [ ] I'd be willing to implement a fix

**Describe the bug**

When enabled `plugin-node-modules`, the initial install never end.
The command of yarn install is success after quit the initial install command with ctrl + c.

**To Reproduce**

1. `mkdir berry-try`
2. `cd berry-try`
3. `yarn init`
4. `echo 'nodeLinker: node-modules' > .yarnrc.yml` 
5. `yarn install`

**Screenshots**

![node_and_実行時間_bash_-_Google_検索](https://user-images.githubusercontent.com/13580199/73117148-7aff3500-3f84-11ea-96ac-70bb2830d44f.png)

**Environment if relevant (please complete the following information):**

 - OS: OSX 10.15.2 
 - Node version: v12.14.0
 - Yarn version: 2.0.0-rc.27

**Comment by larixer** [comment]
Opened PR #753 with one way to fix it
