### ISSUE TITLE
[Bug] module is not defined in yarn-berry.js

### ISSUE THREAD

**Issue by aduh95** [yarnpkg/berry#757]
- [x] I'd be willing to implement a fix

**Describe the bug**

`policies set-version` fails when loading from EMS package.

**To Reproduce**

Using Node.js 13:

```shell
$ mkdir empty-dir
$ cd empty-dir
$ echo '{ "type": "module" } ' > package.json
$ yarn policies set-version 2
$ yarn --version
ReferenceError: module is not defined
    at file://.../empty-dir/.yarn/releases/yarn-berry.js:2:1
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:164:24)
```

**Environment if relevant (please complete the following information):**

 - OS: [e.g. OSX, Linux, Windows, ...] any
 - Node version [e.g. 8.15.0, 10.15.1, ...] >=13.2.0
 - Yarn version [e.g. 2.0.0-rc1, ...] 2

**Additional context**

As of Node.js 12 LTS, package author can add a `type` field in the `package.json` to ask node to treat `.js` files as ESM. This feature was unflagged in Node.js 13.2.0.

Refs: https://nodejs.org/api/esm.html#esm_package_json_type_field

**Solutions I can think of**

* Use `.cjs` extension
* Add a `package.json` in the `.yarn` folder:

```json
{ "type": "commonjs" }
```

**Comment by aduh95** [comment]
Related #758

**Comment by avindra** [comment]
Can this be reopened?

I'm able to reproduce the error on Node 14 using the original steps as described by @aduh95

**Comment by avindra** [comment]
I guess we don't need to reopen it. I can see https://github.com/yarnpkg/berry/issues/985 is also open, so we can just use that issue.

(Making the comment to link the issues)
