### ISSUE TITLE
[Bug] Internal Error: Assertion failed - when running yarn commands on new project

### ISSUE THREAD

**Issue by admmasters** [yarnpkg/berry#759]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Trying to run a yarn command is yielding the error:
"Internal Error: Assertion failed: The package should have been detected as part of the project"
e.g. yarn add lodash

**To Reproduce**

1) Create a new folder
2) run ``yarn init`
3) run ``yarn add lodash`
4) Observer error "Internal Error: Assertion failed: The package should have been detected as part of the project
**package.json:**
{
  "name": "yarn2-typescript"
}

**Environment if relevant (please complete the following information):**

Node 12.13.1
OSX 10.15.2
Yarn 2.0.0-rc.27

**Additional context**

I am trying to use a private repository: https://***/artifactory/api/npm/npm-virtual/
.yarnrc.yml has contents:
npmRegistryServer: "https://packages.dns.ad.zopa.com/artifactory/api/npm/npm-virtual"

**Comment by admmasters** [comment]
Believe this is related to there being no lock file initially.

**Comment by andrew-boyarshin** [comment]
#755 :)

**Comment by admmasters** [comment]
Closing as duplicate

**Comment by dzucconi** [comment]
Just a note for people landing here from searching that error message when initializing a new project:

`touch yarn.lock` and go about adding normally.

**Comment by cnmade** [comment]
This works `touch yarn.lock and go about adding normally.`

I can not believe you still not fix this problem ... 

Very much good experience. thanks
