### ISSUE TITLE
[Bug] Wrong placeholder for npmAlwaysAuth in docs

### ISSUE THREAD

**Issue by eugenesaenko** [yarnpkg/berry#761]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Wrong placeholder for `npmAlwaysAuth` in docs.

**To Reproduce**

Read the doc.

**Screenshots**

![image](https://api.monosnap.com/file/download?id=5TqrEclEjwDesZarISORPio8Csd6Bm)

**Comment by arcanis** [comment]
Fixed in master
