### ISSUE TITLE
[Feature] Automatically create `ypx` as alias to `yarn dlx`

### ISSUE THREAD

**Issue by bondz** [yarnpkg/berry#767]
- [x] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Typing `yarn dlx` or, - as discussed in a separate issue of switching the package name to `berry` which would make the command - `berry dlx` is significantly longer to type than npx.

**Describe the solution you'd like**

The installer should automatically create an alias to `yarn dlx` or `berry dlx` called `ypx` (preferred) as users would only make a mental note that `y` is `yarn`.

This would make it a bit easier to onboard users ala

`ypx create-react-app my-app`
`ypx serve build`

**Describe the drawbacks of your solution**

If the package name eventually becomes `berry`, this might be confusing for users who might assume `ypx` is a v1 feature.

**Describe alternatives you've considered**

`ydx`, `bdx`, might be better alternatives.

**Comment by arcanis** [comment]
Would be nice, but Yarn aims to be shipped as a single JS file, which makes it impossible to add other binary names.

**Comment by Daniel15** [comment]
@arcanis It should be possible to do this for any system-wide Yarn installations though, right?

**Comment by arcanis** [comment]
Yes but then there are additional concerns in term of confusion if some commands only work in some environments (especially if used within scripts, etc). I'd prefer to only recommend the namespaced command, and let users define shell aliases as they please.

**Comment by sebinsua** [comment]
It seems important that the name contain the letter `d` for download and `x` for execute since this has meant to imply that the command is unsafe. Therefore, I would prefer the name `ydx`.

**Comment by arcanis** [comment]
Going to close this, as we don't have plans to provide other binaries for the time being.
