### ISSUE TITLE
[Feature] A command to set yarn version that works on both v1 and v2

### ISSUE THREAD

**Issue by dtinth** [yarnpkg/berry#773]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

If I write a tutorial, and want to ensure readers have a consistent version of Yarn, then ideally there should be a command to set the version of Yarn that **works on both v1 and v2**.

Current situations:

- **yarn policies set-version** works on v1 but not v2:

	```
	$ yarn policies set-version 2
	Resolving berry to a url...
	Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
	Saving it into /private/tmp/yarnwow/.yarn/releases/yarn-berry.js...
	Updating /private/tmp/yarnwow/.yarnrc...
	Done!

	$ yarn policies set-version 2
	Usage Error: Couldn't find a script named "policies".
	```

- **yarn set version** works on v2 but not v1:

	```
	$ yarn set version 1
	➤ YN0000: Selecting the highest release amongst 1.21.1 and 17 others
	➤ YN0000: Downloading https://github.com/yarnpkg/yarn/releases/download/v1.21.1/yarn-1.21.1.js
	➤ YN0000: Saving the new release in .yarn/releases/yarn-1.21.1.js
	➤ YN0000: Done in 11.3s

	$ yarn set version 1
	yarn run v1.16.0
	error Command "set" not found.
	```

**Describe the solution you'd like**

Make either or both of `yarn set version` and `yarn policies set-version` work consistently on both v1 and v2.

This command should be idempotent, that is if I run the previous command again, it should work without compatibility issues such as `Couldn't find a script named "policies"` or `Command "set" not found`.

Tutorial authors will be able to write this:

> We’ll be using Yarn v2 in this project. Run `yarn policies set-version berry`. This will download the Yarn binary so that you can check it in to your project, effectively making sure everyone is using the same yarn version.

instead of:

> We’ll be using Yarn v2 in this project. First, check your yarn version by running `yarn --version`. If it says `1.xx.x`, run `yarn policies set-version berry`. Otherwise, if you’re already on v2, run `yarn set version berry`. This will download the Yarn binary so that you can check it in to your project, effectively making sure everyone is using the same yarn version.

**Describe the drawbacks of your solution**

- Making `yarn set version` work in Yarn 1 — this will introduce breaking change for v1 users if there is a script named "set"
- Making `yarn policies set-version` work in Yarn v2 — this means the command `policies` will still not be usable
- Making both work — multiple ways to achieve the same thing

I would prefer having `yarn policies set-version` work in v2.

**Describe alternatives you've considered**

Publish an npm package `set-yarn-version` that checks the installed Yarn version and runs the appropriate command. Then tutorial authors can tell people to use `npx` to install yarn:

> We’ll be using Yarn v2 in this project. Run `npx set-yarn-version berry`. This will download the Yarn binary so that you can check it in to your project, effectively making sure everyone is using the same yarn version.

**Additional context**

This is similar to #472 but it’s a feature request instead of a bug.

**Comment by arcanis** [comment]
> Making `yarn set version` work in Yarn 1 — this will introduce breaking change for v1 users if there is a script named "set"

One option is to make it a special case in the CLI and only support `set version` (so `yarn set whatever` would still call the user script). It's still technically breaking, but unlikely any more than when we introduced `yarn create` or `yarn unplug`.

**Comment by paul-soporan** [comment]
Closing this, as now both `yarn set version` and `yarn policies set-version` work in both versions. (The latter will be removed in the next major)
