### ISSUE TITLE
[Bug] Resolve github project

### ISSUE THREAD

**Issue by yovanoc** [yarnpkg/berry#777]
Hello I can't find any information about how to use https://github.com/yarnpkg/berry/tree/master/packages/plugin-github

so I get this, it's a bug or I made a mistake?

![image](https://user-images.githubusercontent.com/7302317/73133612-8fe2d380-402b-11ea-87b1-f4c8008d175c.png)

![image](https://user-images.githubusercontent.com/7302317/73133610-89545c00-402b-11ea-82b7-d509486d9cd6.png)

**Comment by arcanis** [comment]
It's a bug - the regex is missing support for `.`. Fix incoming.
