### ISSUE TITLE
[Feature] Make Migration Guide more prominent

### ISSUE THREAD

**Issue by accidentaldeveloper** [yarnpkg/berry#785]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

The migration guide is not particularly easy to find, somewhat buried in the "Advanced" menu. I believe that this is arguably one of the most important pages right now.

I now notice that there is a message and link to it on the "Installation" page but I did not see it at first. The text is gray on white, making it appear, if anything, less important.

![image](https://user-images.githubusercontent.com/5819232/73147949-ee3d9f80-4087-11ea-8ecb-5990726c074a.png)

**Describe the solution you'd like**

The migration guide should be placed in a prominent location on the documentation site. The "alert" message should be made more visible and important

**Describe the drawbacks of your solution**

Not sure? Should lead to more people seeing and contributing to the guide.

**Describe alternatives you've considered**

Posting links to the migration guide on social media and elsewhere
- This will help but some people will go directly to the documentation site.

**Comment by accidentaldeveloper** [comment]
Could also be useful to link from this error message to the migration guide, or other instructions for resolving the error:
> A package is trying to access another package without the second one being listed as a dependency of the first one

Even better is somehow automating the fix!

**Comment by abhijithvijayan** [comment]
- please list out what all to ignore in `.gitignore`
- also, maybe list installation for basic plugins like `@yarnpkg/plugin-workspace-tools` to migrate `yarn workspaces run <script>` to `yarn workspaces foreach run <script>` as yarn was throwing `unknown command` and not showing the plugin info

**Comment by arcanis** [comment]
@abhijithvijayan gitignore is here, but we can add a link to it from the migration guide:
https://yarnpkg.com/advanced/qa#which-files-should-be-gitignored

We also could see to setup Algolia on the documentation to better find information.

**Comment by Ayc0** [comment]
@accidentaldeveloper what do you think of my proposal?
https://github.com/yarnpkg/berry/pull/878

**Comment by merceyz** [comment]
Closing as it's now located under the [Getting Started](https://yarnpkg.com/getting-started) tab and there is a notice at the top of the [Installation](https://yarnpkg.com/getting-started/install) page
