### ISSUE TITLE
[Question/Bug] missing warnigns / console.log/info from scripts

### ISSUE THREAD

**Issue by DanielRuf** [yarnpkg/berry#788]
- [ ] I'd be willing to implement a fix

**Describe the bug**

It seems with yarn berry we do not get any console.log / info from scripts. Is there some way to display them? For exampel warnings form linters ar enot shown anymore (eslint) but errors. Same for normal scirpts.

**To Reproduce**

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: Linux
 - Node version 10.16.0
 - Yarn version 2.0.0-rc.27

**Additional context**

**Comment by arcanis** [comment]
I see logs properly on my side - do you have an exact repro, that we can be sure we're on the same page?

**Comment by DanielRuf** [comment]
In your terminal? I see none expect the errors in `fish`.

I tried `yarn run test:lint` for https://github.com/bitExpert/mattermost-client-node

![grafik](https://user-images.githubusercontent.com/827205/73159984-1a890880-40e8-11ea-9d66-ce377125fb1b.png)


I miss some `verbose` option for yarn v2 commands to make it easier to reproduce.

**Comment by DanielRuf** [comment]
Normally there should be also warnings, not just errors.

**Comment by DanielRuf** [comment]
Hm, seems it comes form eslint. Seems they do not log the warnings anymore. Very interesting.

**Comment by DanielRuf** [comment]
> I miss some `verbose` option for yarn v2 commands to make it easier to reproduce.

Is there some info about this?
