### ISSUE TITLE
[Feature] Setup Danger and autoclose

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/berry#792]
**Describe the user story**

I want to make sure our repository doesn't end up in the same state as the 1.x issue tracker, where noone dares to look at the problems because it's not even clear whether they (still) exist.

**Describe the solution you'd like**

Bugs without automated reproduction (Sherlock) should be autoclosed after a period of time (a month?). Bugs with the `reproducible` tag will be exempted from this as we'll be able to periodically run a bot to check whether they are still relevant.

**Describe the drawbacks of your solution**

It's always a bit awkward when a bot closes an issue for inactivity, and can get spammy when it's done too late and in a single batch. Hence why I'd like to start quickly.

**Comment by paul-soporan** [comment]
This has been set up in https://github.com/yarnpkg/berry/commit/5edd34f0d67b9a2a3b6d092246e07d7943eda808. We know that the sudden wave of stale issues can be a bit frustrating in some cases, but this only happens once (when we first set it up). We'll be working on filtering issues that are still relevant, so you can be sure that your issue (if still relevant) won't be suddenly closed and forever forgotten.
Please don't take your frustration on the bot and ping us instead if something goes wrong with the bot. 🤖
