### ISSUE TITLE
[Question]: Use patch: protocol to modify package.json dependencies before resolution

### ISSUE THREAD

**Issue by bradleyayers** [yarnpkg/berry#794]
Is it possible to use the patch: protocol to modify a dependencies in `package.json`, such that the patch is applied before the package.json is considered so that it can affect resolution. I've tried but it doesn't seem to modify the resolution.

I thought I might be able to use it to work around YN0002 e.g.

```
➤ YN0002: │ @gatsbyjs/relay-compiler@npm:2.0.0-printer-fix.4 [e0506] doesn't provide @babel/core@^7.0.0 requested by babel-preset-fbjs@npm:3.2.0
```

**Comment by arcanis** [comment]
Yes and no, patches occur during fetching by which point the resolution has already been done in most cases (`git:` and `file:` dependencies being a notable exception).

The best way to fix the problem you mention is to use [`packageExtensions`](https://yarnpkg.com/configuration/yarnrc#packageExtensions). In the case you link it'd probably also be a good fit for the plugin-compat!

https://github.com/yarnpkg/berry/blob/master/packages/plugin-compat/sources/extensions.ts

**Comment by bradleyayers** [comment]
Ah `packageExtensions` is exactly what I was after, thanks!
