### ISSUE TITLE
[Bug] ~/.yarnrc is ignored

### ISSUE THREAD

**Issue by bgotink** [yarnpkg/berry#80]
**Describe the bug**

Configuration specified by the user in their `~/.yarnrc` is ignored by berry

**To Reproduce**

```bash
# setup
echo "lastUpdateCheck $(date +%s)" >> ~/.yarnrc
cd /tmp

# yarn v1
yarn config list
# notice the line
#   lastUpdateCheck:
#    1555780695

# berry
echo 'yarn-path "/path/to/my/clone/of/berry/scripts/run-yarn.js"' > .yarnrc
yarn config --why
# notice the line
#   lastUpdateCheck          <default>              null
```

**Comment by arcanis** [comment]
This is because you're in `/tmp`. The logic currently (by design) only traverse the directories upwards (no special treatment for HOME or XDG, for example). From my observations it wasn't always clear what yarnrc files were actually used on the v1.

Do you think it's more confusing than not?

**Comment by bgotink** [comment]
It's different than v1, so unexpected for me.

I'm one of those special people that care about file system case sensitivity. I've run into issues here in the past, especially with git being case sensitive and hfs/hfs+/apfs being case insensitive. Long story short, my projects are all contained in a case sensitive apfs partition mounted under `/Volumes/Workspaces`.

Apart from that tomfoolery I do believe a user-centric rc file has a valid usecase. It's the perfect location to store credentials. I would also put some configuration here when building on docker containers, e.g. to put the cache in a persisted volume because otherwise there's no point to having a cache.
