### ISSUE TITLE
[Bug] Seems like my dependencies devDeps are being checked

### ISSUE THREAD

**Issue by hipstersmoothie** [yarnpkg/berry#804]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Some dep in my tree depends on a package with some devDep warnings. I really don't want to be bothered by warnings for devdeps.

**To Reproduce**

Install `json-fixer`.

**Screenshots**

![Screen Shot 2020-01-27 at 10 39 54 AM](https://user-images.githubusercontent.com/1192452/73203267-92a7fc00-40f1-11ea-80d5-e374394bcced.png)

**Environment if relevant (please complete the following information):**

 - OS: osx
 - Node version 10.17.0
 - Yarn version 2.0.0-rc.27

**Comment by arcanis** [comment]
`eslint-config-kentcdodds` was a regular dependency in json-fixer@1.3.1. Upgrade to 1.4.0:

https://cdn.jsdelivr.net/npm/json-fixer@1.3.1/package.json
