### ISSUE TITLE
[Bug] PnPify in Visual Studio Code does not support "Go to Definition"

### ISSUE THREAD

**Issue by dallonf** [yarnpkg/berry#806]
- [ ] I'd be willing to implement a fix

**Describe the bug**

When using the PnPify workflow in Visual Studio Code, attempting to "Go to Definition" of a dependency results in VS Code attempting, and failing, to open a source file from inside a zipped package in the cache:

```
Unable to open 'index.d.ts': Unable to read file (Error: File not found (c:\Users\dallo\devroot\tmp\my-app\.yarn\cache\@types-react-npm-16.9.19-21809ae185-1.zip\node_modules\@types\react\index.d.ts)).
```

**To Reproduce**

(This isn't exactly _minimal_ since I don't think Create React App is part of the issue, but it's at least very simple to reproduce, and I don't have time to figure out how to create a project without a template right now. Would appreciate anyone with more context helping break it down a little more)

1. Create an app with Create React App as described in the [CRA docs](https://create-react-app.dev/docs/getting-started#creating-a-typescript-app):
```
npx create-react-app my-app --template typescript
```
2. Follow the instructions to enable PnPify in Visual Studio Code: https://yarnpkg.com/advanced/editor-sdks#vscode
3. In `App.tsx`, try to "Go to Definition" on the React package.

**Screenshots**

![image](https://user-images.githubusercontent.com/346300/73215403-abc4a300-4119-11ea-8f71-d9e18b2c1a9f.png)

**Environment if relevant (please complete the following information):**

 - OS: Windows 10, build 18362.592
 - Node v13.7.0
 - Yarn v2.0.0-rc.27

**Additional context**

Looks like the root of the issue is that it's trying to go inside a zip file.

**Comment by arcanis** [comment]
Yes, this is a known issue - there is an [open ticket](https://github.com/microsoft/vscode/issues/75559) on the VSCode tracker to fix it, we can't do it on our side (I've experimented with it already, we even have a zip extension in this very repository, but without the right hooks it's fairly useless).

My best advice is to upvote the VSCode issue to help their team prioritize it 🙂

**Comment by skeate** [comment]
This is also an issue with `$$virtual`, but a bit worse because `$$virtual` doesn't actually exist, so even if my editor could just open files inside a zip, it would still fail to find it.

I'm not sure why some things are resolving to `$$virtual` and others aren't; the closest thing to docs I found is this line:

> Due to a particularity in how Yarn installs packages which list peer dependencies, some packages will be mapped to multiple virtual directories that don't actually exist on the filesystem. This settings tells Yarn where to put them. Note that the folder name *must* be $$virtual.

from [here](https://yarnpkg.com/configuration/yarnrc)

**Comment by arcanis** [comment]
@skeate explanation about virtual packages is here: https://yarnpkg.com/advanced/lexicon#virtual-package

**Comment by skeate** [comment]
Thanks for that link, though it's a little hard to understand without an example given. But I don't want to derail this issue with a tangent.

Do you agree that it's an issue, or should editors be able to access `$$virtual` somehow?

Also, aside for anyone else finding this thread who wants a fix _now_: [`yarn unplug <pkg>`](https://yarnpkg.com/advanced/editor-sdks#caveat)

**Comment by dallonf** [comment]
My mistake, I missed the "caveat" section in the docs on Editor SDKs. Should this issue be closed?

**Comment by arcanis** [comment]
> Do you agree that it's an issue, or should editors be able to access `$$virtual` somehow?

It's an issue in that I don't expect editors to support the `$$virtual` file pattern as their encoding is a bit of a Yarn implementation detail, but I can't find any better tool we can use at the moment.

Closing this issue as there's nothing actionable on our side at the moment (for people reaching this, please upvote https://github.com/microsoft/vscode/issues/75559 to show your interest to the VSCode team).
