### ISSUE TITLE
[Bug] website front-end need responsive improvements 

### ISSUE THREAD

**Issue by juanpicado** [yarnpkg/berry#808]
- [x] I'd be willing to implement a fix

**Describe the bug**

Home hero does not fit in the screen

**To Reproduce**

Use iPhone 8 (😊) or some mobile device with small/medium screen 

**Screenshots**

![Screen Shot 2020-01-27 at 11 05 10 PM](https://user-images.githubusercontent.com/558752/73218538-6eccd080-415a-11ea-99b6-0c800a05b3a6.png)

**Environment if relevant (please complete the following information):**

 - OS: iOS, Android (Honor X8)

**Additional context**

There is some values for responsive at `packages/gatsby/src/components/responsive.js`

```
export const ifMobile = () => `@media (max-width: 760px)`;
export const ifDesktop = () => `@media (min-width: 761px)`;
```

I wonder whether this can be improved in order to work with multiple sizes. I was taking a look and this might need re-work, any insights is also welcome.

**Comment by arcanis** [comment]
Yep the mobile home (and navigation menu) are not my the frontend work I'm the most proud of 😅

**Comment by juanpicado** [comment]
:) I am open to take it, almost never do front on open source.

**Comment by arcanis** [comment]
That would be awesome 🙏

**Comment by arcanis** [comment]
I'll close this one as there's been a lot of improvements here and it should already be a much better experience 👍
