### ISSUE TITLE
[Bug] `yarn install` with the node-modules plugin hangs indefinitely 

### ISSUE THREAD

**Issue by fson** [yarnpkg/berry#820]
**Describe the bug**

Running `yarn install` the first time in a project with node-modules plugin enabled (`nodeLinker: node-modules` set) results in the command displaying a progress bar and hanging indefinitely after it prints "Done with warnings".

**To Reproduce**

`package.json`:
```json
{
  "dependencies": {
    "react": "~16.9.0"
  }
}
```
`.yarnrc.yml`:
```yaml
nodeLinker: node-modules
```

Run `yarn install`.

**Screenshots**

<img width="730" alt="Screen Shot 2020-01-28 at 16 32 10" src="https://user-images.githubusercontent.com/497214/73272870-c404f280-41eb-11ea-9cb9-0ad314c72384.png">

**Environment if relevant (please complete the following information):**

 - OS: macOS 10.15.2
 - Node version v12.13.0
 - Yarn version 2.0.0-rc.27

**Additional context**

N/A

**Comment by arcanis** [comment]
Fixed in master (#753), you can use `yarn set version from sources` to try it.
