### ISSUE TITLE
[Bug] Typescript compiler can't resolve dependencies with yarn@berry

### ISSUE THREAD

**Issue by winseros** [yarnpkg/berry#834]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Typescript compiler can't resolve neither `node_modules` dependency nor workspace one if `yarn@berry` is in use. The same setup works with `yarn@1`

**To Reproduce**

I created [an example repo](https://github.com/winseros/yarn_berry_typescript_issues) that contains two packages: a working setup using `yarn@1` and the same but not working setup using `yarn@berry`.

**Environment if relevant:**

 - OS: [Windows 10]
 - Node version [v12.13.0]
 - Yarn version [1.21.1 and 2.0.0-rc.27]

**Comment by larixer** [comment]
@winseros Sometimes it is enough to have full error message to understand whats wrong, could you please attach screen shot with error message?

**Comment by winseros** [comment]
Oh, I finally made it work in console. Had to explicitly include all the required `devDependencies` into all the interested workspaces.

Console build now works, though IDE (latest WebStorm)  still can't recognize anything. But this is not a matter of this ticket.

Closing it. Thank you.
