### ISSUE TITLE
[Feature] Make peerDependency types available to Typescript

### ISSUE THREAD

**Issue by sparebytes** [yarnpkg/berry#838]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

I'm using Typescript Project References with a single root tsconfig which references all my projects.

In order to compile some of my workspace packages with Typescript, I must copy many of their peerDependencies into their devDependencies, even when my root package.json lists those already. This leads to busy-work and bloated package.json files.

**Example 1**: I have a workspace package called `my-typeorm-utils` that lists "typeorm" as a peerDependency but in order to compile I must list it as a devDependency even though my root package.json lists it as a dependency.

**Example 2**: I use `@storybook/react` across many workspace packages and list it as a peerDependency in all. In order to compile all the stories, I must also list it as devDependency. Upon doing that I find I now must list `babel-loader` and `@babel/core` as devDependencies. Once again I find I need to add `webpack` and on it goes.

**Describe the solution you'd like**

Ideally Typescript (or any other build tool) would somehow know to use the matching dependency or devDependency provided by the root workspace package.json.

**Describe the drawbacks of your solution**

- Not sure how you would limit it to just build tools.

**Describe alternatives you've considered**

One alternative that wouldn't be so turn-key and would add complexity to yarn's internals is something I'm calling **Virtual Dependencies**. I'll detail that idea in a follow-up comment

**Comment by sparebytes** [comment]
**Proposal 2: Virtual Packages**

Virtual Packages would only serve group a bunch of related packages together. A consumer of a virtual package would inherit the virtual package's dependencies almost as-if they were listed directly in the consumer's package.json itself.

Example:
```jsonc
// packages/virtual-storybook-react
{
  "name": "@my/virtual-storybook-react",
  "private": true,
  "dependencies": {
    "@storybook/react": "*"
  },
  "devDependencies": {
    "@babel/core": "*",
    "@storybook/react": "*",
    "babel-loader": "*",
    "webpack": "*"
  }
}

// packages/react-components
{
  "name": "@my/react-components-a",
  "virtualDependencies": {
    "@my/storybook-react": "workspace:*"
  }
}
// Becomes:
{
  "name": "@my/react-components-a",
  "dependencies": {
    "@storybook/react": "*"
  },
  "devDependencies": {
    "@babel/core": "*",
    "@storybook/react": "*",
    "babel-loader": "*",
    "webpack": "*"
  }
}
```

Of course any dependency range listed in the consumer package.json file would take precedent over the range given in a virtual package.

**Comment by arcanis** [comment]
Interestingly we already have something entirely different we call virtual packages :p But more to the point:

- The first proposal you describe looks very similar to [`pnpFallbackMode`](https://yarnpkg.com/configuration/yarnrc#pnpFallbackMode), which allows packages to access the dependencies declared at the top level. By default this fallback is disabled for workspaces as we assume the errors are actionable (and we prefer to enforce explicit links).

- The second proposal looks very much like ... spreads. It would be nice if we could do something like `dependencies: {...require('./deps-shared'), foo: '1.0.0'}`. For now it's impossible because the manifest must remain JSON (otherwise Node cannot locate the `main` and `type` fields), but maybe in the future once the Loader spec will have been shipped for long enough ... ?

**Comment by sparebytes** [comment]
I tried different values for `pnpFallbackMode` but it didn't seem to have an effect, at least with my setup.

Introducing a JS file that alters the package.json would need to be done carefully because it wouldn't be able to rely on any absolute dependencies.

I think it makes sense for the so-called "spreads" to be referenced very much like existing packages. This way existing tooling around resolvers, fetchers, and linkers can be used. EG:
1. Via a new property on package.json
    * `{ "virtualDependencies":  { "shared-dependencies": "1.0.0" }}`
    * `{ "virtualDependencies":  { "shared-dependencies": "file:./my-package" }}`
    * `{ "virtualDependencies":  { "shared-dependencies": "workspace:*" }}`
2. Via the existing properties on package.json
    * `{ "dependencies":     { "shared-dependencies": merge:1.0.0" }}`
    * `{ "dependencies":     { "...shared-dependencies": "1.0.0" }}`
    * `{ "peerDependencies": { "...shared-dependencies": "file:./my-package" }}`
    * `{ "devDependencies":  { "...shared-dependencies": "workspace:*" }}`

The first verison has the benefit of a very simple mapping. Dependencies, peerDependencies and devDependencies of the virtual dependency are merged into the dependencies, peerDependencies and devDependencies of the consumer respectively.

The second version would take more consideration and I'm not totally sure of the benefits. It would require some new type of notation or protocol. Also, if the spread can be listed under dependencies, peerDependencies or devDependencies, then you have decide how the DependencyTypes of the spread are mapped into the consumer. See the table below for how it might work.

| shared-dependencies package.json DependencyType |  Placement of `"shared-dependencies": "*"` inside consumer package.json              |  Destination DependencyType |
|--------------------|------------------------|------------------|
| **dependency**     |  **dependency**        |  dependency      |
| dependency         |  **peerDependency**    |  peerDependency  |
| dependency         |  **devDependency**     |  devDependency   |
| **peerDependency** |  dependency            |  peerDependency  |
| **peerDependency** |  **peerDependency**    |  peerDependency  |
| peerDependency     |  devDependency         |  ???             |
| **devDependency**  |  dependency            |  devDependency   |
| **devDependency**  |  peerDependency        |  devDependency   |
| **devDependency**  |  **devDependency**     |  devDependency   |

P.S. My first instinct was to call it something like bundled but that name already has baggage too.

**Comment by yacinehmito** [comment]
Specifying them in the root `package.json` seem to be some sort of a "hack" to avoid repeating the dependencies. If you isolate your workspace it will stop working.
Repeating peer dependencies in dev dependencies is the usual way to do it; however, as you stated, if comes at a cost:

> This leads to busy-work and bloated package.json files.

I don't really have a solution for the bloated `package.json` files. However I'd argue that it's not that big of a deal.
The busy-work on the other hand can be solved with constraints: you could define a rule that states that any package that appear as dev dependency in the root `package.json` and as a peer dependency in workspace `X` must also appear as dev dependency in workspace `X`.

**Comment by 0x80** [comment]
I am developing a package that has code depending on peer dependency types. I have duplicated the peer dependency as as a dev-dependency in package.json but TS still won't let me import the types.

I've tried the following:

```
import type { Timestamp } from "firebase";
```

```
/// <reference types="firebase" />
```

What am I missing?

**Comment by merceyz** [comment]
Closing as PnP is strict on purpose, if you want it to be more relaxed you can use [`pnpMode: loose`](https://yarnpkg.com/configuration/yarnrc/#pnpMode) but if you end up isolating your workspaces you'll run into issues (https://github.com/yarnpkg/berry/issues/838#issuecomment-581152350).
