### ISSUE TITLE
[Bug] CPU Usage when working with workspaces

### ISSUE THREAD

**Issue by joshmeads** [yarnpkg/berry#840]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Whenever I'm working with yarn workspaces I get very high CPU usage. Even after closing all yarn commands, VSCode, etc. I've tried multiple restarts but it keeps happening. Could this be to do with pnpify?

**To Reproduce**

Unsure - appears to be whenever working with workspaces. Last came up while testing an empty repo the following issue: https://github.com/yarnpkg/berry/issues/839

**Screenshots**

CPU is the number after ?

<img width="1809" alt="Screenshot 2020-01-29 at 4 18 29 PM" src="https://user-images.githubusercontent.com/8870827/73412164-a3589d80-42bc-11ea-9302-91fbae2b56ec.png">

![Screenshot 2020-01-29 at 5 22 04 PM](https://user-images.githubusercontent.com/8870827/73412172-a5baf780-42bc-11ea-80f9-dba6a7cec6f2.png)

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version: 13.7.0
 - Yarn version: 2.0.0-rc.27

**Comment by sparebytes** [comment]
I actually had a similar issue on Windows when I was playing with this back in December. On a few occasions closing VSCode wasn't enough. I remember zombie node processes that continued to run.

It seemed to happy consistently when I was editing a package.json and would hit ctrl+space to for the version number lookup like this. When I opened VSCode's process explorer I noticed a ton of `CMD` executions of NPM.

![image](https://user-images.githubusercontent.com/16328067/73412662-f50a2380-42ce-11ea-8a5f-11db9a11a829.png)

I had done some weird stuff to get prettier working so I have a feeling this is related to #822

**Comment by larixer** [comment]
@joshmeads @sparebytes Have you tried to regenerate sdk? E.g.:
`yarn pnpify --sdk`
The yarn v2 does not use in memory node_modules fs (which might be CPU bound) for TypeScript support in the latest editor SDK:
https://github.com/yarnpkg/berry/blob/b0c9d687a783f72161f78a2b4e4b1a516c283171/packages/yarnpkg-pnpify/sources/generateSdk.ts#L11

But if you generated SDK with older pnpify version you will have imports of `@yarnpkg/pnpify` inside `.vscode/pnpify/typescript/lib/tsserver.js` which will result in building in-memory node_modules fs and might hit CPU hard (at the moment, I'm working to reduce CPU usage for in-memory node_modules fs).

**Comment by andreialecu** [comment]
I've also seen this exact same problem. I can confirm that it disappeared after moving back to yarn v1.

**Comment by merceyz** [comment]
This was fixed in https://github.com/yarnpkg/berry/pull/800.
Try updating and running `yarn pnpify --sdk` again
