### ISSUE TITLE
[Bug] typescript 2 patching breaks install

### ISSUE THREAD

**Issue by TrySound** [yarnpkg/berry#857]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I have typescript 2 somewhere deep in my dependencies which is not used but added there accidentally. And it's the only thing which breaks yarn install.

**To Reproduce**

Install `cloudinary@1.19.0`

**Screenshots**

![image](https://user-images.githubusercontent.com/5635476/73523016-f8122a80-441a-11ea-8317-8db027710619.png)

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version 12.10.0
 - Yarn version 2.0.0-rc28

**Comment by spech66** [comment]
As a temporary workaround you can set your typescript dependencies to 3 for alle packages via package.json

```
  "resolutions": {
    "typescript": "^3.0.0"
  },
```
