### ISSUE TITLE
[Bug] : Issue with folder permission when using with create-react-app

### ISSUE THREAD

**Issue by revathskumar** [yarnpkg/berry#862]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Running create react app with command `npm init react-app react-web` or `npx create-react-app react-web` created folders with `777` only those which copied from default CRA template.

Also tried with custom template and any folder copied from the template is with permission 777.
Also noted that the permission issue is only for folders and not the files inside those.

**To Reproduce**

1. Install yarn v2
2. `npm init react-app react-web` or `npx create-react-app react-web`

The _minimal_ information needed to reproduce your issue (ideally a package.json with a single dep). Note that bugs without minimal reproductions might be closed.

IMPORTANT: We strongly prefer reproductions that use Sherlock. Please check our documentation for more information: https://next.yarnpkg.com/advanced/sherlock

**Screenshots**
![Screenshot from 2020-01-31 20-50-57](https://user-images.githubusercontent.com/463904/73552205-b9429b80-443f-11ea-8182-e8f918533d9c.png)

Files inside the public folder
![image](https://user-images.githubusercontent.com/463904/73552776-c1e7a180-4440-11ea-8229-62101de12b14.png)

**Environment if relevant (please complete the following information):**

 - OS: Ubuntu 18.04 LTS
 - Node version: 13.3.0 
 - Yarn version: 2.0.0-rc.27

**Additional context**

**Comment by arcanis** [comment]
Interestingly any folder copied from the archives seem to be chmod 0o777 - for example that's the case of the `.yarn/unplugged` directory content too. The files are 644 as expected.
