### ISSUE TITLE
Remote install script

### ISSUE THREAD

**Issue by js-kyle** [yarnpkg/berry#866]
Hi,

I currently install Yarn 1 on TravisCI using the below steps

```
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $v
  - export PATH=$HOME/.yarn/bin:$PATH
```

Does Yarn 2 have a similar remote install script? The above throws as error as it does not allow rc versions passed by `--version`. I have tried changing the script, but I can't find where the Yarn 2 tarball files are hosted, as these links now redirect to legacy Yarn

**Comment by arcanis** [comment]
We don't at the moment, and I don't think we will (we now recommend keeping Yarn 1.x as the global binary, and using `yarn set version` to set the Yarn version on a per-project basis).

**Comment by xPaw** [comment]
> we now recommend keeping Yarn 1.x as the global binary

The website docs switched to v2 and it doesn't seem to have any of the old install methods listed: https://yarnpkg.com/getting-started/install

I've [had to change the url](https://github.com/thelounge/thelounge.github.io/commit/84343c2fb37edfd8f281fae6ba3609cca79dfbbe) to the legacy site in our documentation. We've been recommending yarn over npm as it causes less issues for casual users.

**Comment by arcanis** [comment]
> The website docs switched to v2 and it doesn't seem to have any of the old install methods listed: https://yarnpkg.com/getting-started/install

The website still needs to be updated to account for the change of plan outline in https://github.com/yarnpkg/berry/issues/766#issuecomment-580658470

**Comment by ruslanchek** [comment]
> We don't at the moment, and I don't think we will (we now recommend keeping Yarn 1.x as the global binary, and using `yarn set version` to set the Yarn version on a per-project basis).

It's not working 
`yarn run v1.21.1
error Command "set" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by arcanis** [comment]
Use `yarn policies set-version [...]` for now. The `yarn set version [...]` alias will be added in a 1.22 release that will contain a few helpers to simplify the transition.

**Comment by ruslanchek** [comment]
> Use `yarn policies set-version [...]` for now. The `yarn set version [...]` alias will be added in a 1.22 release that will contain a few helpers to simplify the transition.

Thanks! But I'm currently on a night build which is 1.22.0xx

**Comment by js-kyle** [comment]
```
$ yarn --version
$ 1.21.1
$ yarn policies set-version 2.0.0-rc.27
Resolving 2.0.0-rc.27 to a url...
error An unexpected error occurred: "Release not found: 2.0.0-rc.27".
```

I cannot seem to use that suggested method
