### ISSUE TITLE
[Feature] Yarn wrapper

### ISSUE THREAD

**Issue by artemy-osipov** [yarnpkg/berry#868]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Recommended way to install yarn is `yarn set version berry`. This command installs the required version of yarn in the .yarn/releases directory and set a path to it through `.yarnrc.yml`. As I understand it, yarn classic will consider this setting and delegate each command to the downloaded yarn. In this case it would be nice to use project's yarn directly without having to install yarn classic. This will make it easier for developers to start working with the project, and will also make it easier to set up CI, since only runtime in the form of NodeJs will be needed.

**Describe the solution you'd like**

After executing `yarn set version berry`, a yarn wrapper is created in the root directory of the project. As a result, instead of running commands via the global yarn classic, you can use the wrapper which, by analogy with yarn classic, will delegate execution to yarn from .yarn/releases.

project directory:
<pre>
project
├── .yarn
│  └── releases
│    └── yarn-rc.js
├── src
│  └── ...
├── package.json
├── yarn.lock
├── <b>yarnw</b>
├── <b>yarnw.bat</b>
</pre>

run wrapper:
```
./yarnw --version
./yarnw add [package] --dev
```

**Describe the drawbacks of your solution**

Additional files in the project directory. For Windows it is necessary to create a similar wrapper `yarnw.bat`

**Additional context**

This concept is quite widespread in the JVM ecosystem for package managers.
- [gradle](https://docs.gradle.org/current/userguide/gradle_wrapper.html)
- [maven](https://github.com/takari/maven-wrapper)

**Comment by arcanis** [comment]
Honestly I think for most of our users (including me 😄) typing `yarn` became kind of an automatism and this different workflow would be very annoying to learn (especially since `./` isn't close from `yarn` on most keyboards).

Note that for CI, you can do `./yarn/releases/*.js install` just fine 🙂

**Comment by artemy-osipov** [comment]
I periodically return to the JS ecosystem and am very glad to see it evolving. Berry is really a next-gen package manager, but unfortunately some outdated (in my opinion) concepts remain the same. Some of them are
- the main manifest of the project is still static package.json. You cannot add comments, dynamically change content, add code without wrapping it in strings.
- need some global package to work with the project

I agree that in the second case it is a matter of habits, but without an alternative, habits cannot be changed. The letters y, a, r, n are also not so close on the keyboard 😉

**Comment by bgotink** [comment]
I really like the idea of repositories that work standalone, without requiring any software that's not available by default on a modern OS (i.e. a shell, curl, tar and other basic commands).
The idea that you just need to clone and you're ready to go—regardless of whether your system has yarn or even node installed—is powerful for contributors old and new. 

That being said, I'm not sure if this belongs in yarn itself per se. This could be built as a plugin.

As to typing `yarn` vs `./yarnw`&hellip; It's not just a matter of typing those extra characters, it's also the fact that this yarn wrapper is only present in one location, so you could end up having to run `../../../yarnw add -D typescript` to install typescript in a workspace.
On the other hand, you could write a function into your shells's RC file that looks for a `yarnw` file and falls back to the global yarn command if not found.

**Comment by bgotink** [comment]
I've created a small script that reads the location of the yarn release from `.yarnrc` or `.yarnrc.yml` and runs that with node. It uses `nvm` if a `.nvmrc` file is found, so the correct version of node is always used.

We've been using it in private projects for a while now, mostly to skip the `npm i -g yarn` step in our CI. As a developer I still just use `yarn` instead of this script.

The wrapper can be found here: https://gist.github.com/bgotink/6e56bbee5f1657b72aaf6c409486e8c4

This could be extended to e.g. download nvm if it isn't found, but the current solution fits our usecase so I'm not currently looking to extend the script.

**Comment by merceyz** [comment]
Closing as the solution from @bgotink solves this request, but if you want to invoke v2 directly without the global yarn you can always use `node ./<path-to-yarn>`
