### ISSUE TITLE
Yarn 2.x installation is incomplete

### ISSUE THREAD

**Issue by rlaferla** [yarnpkg/berry#880]
The website says to install Yarn 2.x:

`npm install -g yarn@berry`

but this does not create an executable "yarn".  It simply puts a yarn.js in node_modules.   To fix it, you need to copy yarn.js to a folder on your path like "/usr/local/bin/yarn" (without .js)

**Comment by paul-soporan** [comment]
You aren't supposed to install Yarn 2 globally anymore, so there's no need for it to be in your path. Check the installation guide for more details: https://yarnpkg.com/getting-started/install
