### ISSUE TITLE
[Bug] Error using `2.0.0-rc.27`: `The "listener" argument must be of type Function. Received type object`

### ISSUE THREAD

**Issue by lili2311** [yarnpkg/berry#890]
- [ ] I'd be willing to implement a fix

Unable to install `yarn` locally after following this https://next.yarnpkg.com/getting-started/install
Error:
```
 yarn set version berry
➤ YN0000: Found matching release with rc
➤ YN0000: Downloading https://github.com/yarnpkg/berry/raw/master/packages/yarnpkg-cli/bin/yarn.js
➤ YN0001: GotError: The "listener" argument must be of type Function. Received type object
    at m (/Users/lili/.nvm/versions/node/v10.8.0/lib/node_modules/yarn/bin/yarn.js:18:301283)
    at ClientRequest.once (events.js:288:11)
    at new ClientRequest (_http_client.js:141:10)
    at Object.request (https.js:272:10)
    at m (/Users/lili/.nvm/versions/node/v10.8.0/lib/node_modules/yarn/bin/yarn.js:18:301252)
➤ YN0000: Failed with errors in 0.02s
```

**To Reproduce**
- After installing `yarn` globally with `npm i -g yarn@berry`
- go into a new empty project dir
- then run `yarn set version berry` as per instructions

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OSX
 - Node version `10.8.0`
 - Yarn version  `2.0.0-rc.27`

**Additional context**

The same error occurs when trying to add a dep in an existing project (older yarn) or any other command really

**Comment by EugeneZ** [comment]
I had the same problem and realized I had accidentally installed node 10.**0**.0 instead of node 10.**19**.0 using nvm. Whoops! **Upgrading** to 10.19.0 solved this problem for me. Hope that helps!

**Comment by paul-soporan** [comment]
Even though we technically support Node 10+, tests only run on the latest versions of the supported Node majors (at the time of writing this, they are Node 10, Node 12, and Node 14). The other problem is that Yarn uses Got for all network requests, so we are implicitly only supporting Node versions that are supported by the Got version we're using, which, at the time of writing this, only supports Node versions satisfying this range: `>=10.19.0`.

I think it would be a good idea to show a warning when we detect an unsupported Node version.
