### ISSUE TITLE
[Bug]: Installing Yarn 2

### ISSUE THREAD

**Issue by JamesVanWaza** [yarnpkg/berry#900]
**Describe the bug**
Even after running `npm install -g yarn@berry` it still shows as `version 1.21.1`

I also tried running `yarn set version` but no luck. 

**Environment if relevant (please complete the following information):**

 - OS: [**macOS Catalina 10.15.2**]
 - Node version [**v12.14.1**]
 - Yarn version [**1.21.1**]

**Comment by juanpicado** [comment]
I have the same issue before, please ensure you have not installed before with brew. If is that the case run 

brew uninstall yarn 

Then try again installing via npm, it did works for me.

**Comment by DRoet** [comment]
`yarn set version berry` also doesn't work **yet** in yarn v1.21.x since it is an unreleased alias. You should be using `yarn policies set-version berry`

**Comment by JamesVanWaza** [comment]
@juanpicado @DRoet, no luck even after installing from npm. 

<img width="1679" alt="Screen Shot 2020-05-17 at 3 34 00 PM" src="https://user-images.githubusercontent.com/4000076/82158130-ed599500-9853-11ea-8f5a-93ffa15cbc7d.png">

**Comment by JamesVanWaza** [comment]
@juanpicado @DRoet after trying multiple times, I was able to get the right version of `1.22.4`

Much appreciated.

**Comment by juanpicado** [comment]
What actually solve this ? 🤔

**Comment by JamesVanWaza** [comment]
I did `which yarn` then it showed the path then I removed the path and run `brew install yarn` which worked.
