### ISSUE TITLE
[Bug] yarn set version 2.0.0 raises an error

### ISSUE THREAD

**Issue by danielleadams** [yarnpkg/berry#907]
- [x] I'd be willing to implement a fix

**Describe the bug**

I am reinstalling yarn fresh on my local machine, and I followed the steps on the documentation to use yarn 2 and switch between versions. When I run `yarn set version 2.0.0`, I receive an "No matching release error".

```bash
➤ YN0001: Error: No matching release found for version 2.0.0.
    at /Users/danielle.adams/Code/heroku/node-js-getting-started/.yarn/releases/yarn-rc.js:24:162418
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.start (/Users/danielle.adams/Code/heroku/node-js-getting-started/.yarn/releases/yarn-rc.js:24:44856)
    at async h.execute (/Users/danielle.adams/Code/heroku/node-js-getting-started/.yarn/releases/yarn-rc.js:24:161928)
    at async h.validateAndExecute (/Users/danielle.adams/Code/heroku/node-js-getting-started/.yarn/releases/yarn-rc.js:24:40434)
    at async c.run (/Users/danielle.adams/Code/heroku/node-js-getting-started/.yarn/releases/yarn-rc.js:36:533800)
    at async c.runExit (/Users/danielle.adams/Code/heroku/node-js-getting-started/.yarn/releases/yarn-rc.js:36:533934)
➤ YN0000: Failed with errors in 0.76s
```

Documentation: https://yarnpkg.com/getting-started/usage#upgrading-yarn-itself

**To Reproduce**

1. `npm uninstall -g yarn`
2. `npm install -g yarn@berry`
3. `yarn set version 2.0.0`

**Screenshots**

<img width="1168" alt="Screen Shot 2020-02-06 at 12 22 57 PM" src="https://user-images.githubusercontent.com/6271256/73961910-7703d900-48db-11ea-87f0-622e2d0a5e6f.png">

**Environment if relevant (please complete the following information):**

 - OS: macOS
 - Node 13.8.0
 - Yarn 2.0.0-rc.27

**Additional context**

I'd like to understand how I can detect a yarn version from someone's source code (ie. engines in a `package.json`) and set it for that remote environment (like a build on Heroku). Thanks in advance.

**Comment by AlexandreLoub** [comment]
up

**Comment by memark** [comment]
I also have this problem.

Btw @danielleadams, from your screenshots it looks like you are using Node 13.8.0 (not 12.13.1).

**Comment by danielleadams** [comment]
Thanks @memark! Yeah, looks like I was flipping around shells... I'll edit that.

**Comment by arcanis** [comment]
Hm can you try `2` (rather than `2.0.0`)?

**Comment by memark** [comment]
@arcanis That worked for me, ty!

```
➜ yarn set version 2.0.0
Resolving 2.0.0 to a url...
error An unexpected error occurred: "Release not found: 2.0.0".
info If you think this is a bug, please open a bug report with the information provided in "/Users/memark/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/policies for documentation about this command.

~
➜ yarn set version 2
Resolving 2 to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
Saving it into /Users/memark/.yarn/releases/yarn-berry.js...
Updating /Users/memark/.yarnrc.yml...
Done!

~
➜ yarn --version
2.0.0-rc.30
```

**Comment by memark** [comment]
I get that this is probably a temporary condition (while yarn 2 is in RC), but I still think it would make sense to update this page
https://yarnpkg.com/getting-started/usage#upgrading-yarn-itself
since most people will probably follow it (like I did).
