### ISSUE TITLE
[Bug] yarn `patch:` protocol cannot add dependencies to a package.json

### ISSUE THREAD

**Issue by cspotcode** [yarnpkg/berry#922]
- [ ] I'd be willing to implement a fix

**Describe the bug**

It is not possible to use yarn 2's `patch:` protocol to add a new dependency to a package.json.

I tried patching `gh`'s package.json to add a missing dependency.  If I unplug `gh` and inspect the package.json, I see that the dependency was added.  However, `yarn why` does not reflect the addition, and `yarn run gh` still fails as if the dependency was not added.  (In this particular case, I'm patching `gh` to add a missing dependency)

**To Reproduce**

https://github.com/cspotcode/repros/tree/yarn-2-patch-bug

**Environment if relevant (please complete the following information):**

 - OS: Linux
 - Node version v12.15.0
 - Yarn version 2.0.0-rc.28

**Comment by merceyz** [comment]
You need to use `packageExtensions` to "patch" that. The patch protocol can't really affect `package.json`
https://yarnpkg.com/configuration/yarnrc#packageExtensions

**Comment by cspotcode** [comment]
@merceyz Thanks, I didn't know about that.  It did the trick.
