### ISSUE TITLE
[Feature] Merge Yarn v1 and v2 sites?

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/berry#924]
- [x] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

Now that it seems like Yarn v1 and v2 will coexist side-by-side, perhaps we should consider merging/unifying the two sites together. A lot of the core concepts and commands are the same across both versions. We can highlight what's changed between v1 and v2

**Comment by arcanis** [comment]
The main issue is the command options and slightly different behaviours (plus the old-style configuration). I'm a bit worried unifying them too much would make things more confusing ... 🤔

Maybe something we could do would be to add links pointing to the classic documentation on the relevant modern documentation counterparts? Like "if you're using Yarn 1.x, check doc at {url}"?

**Comment by arcanis** [comment]
Closing, as the new website now has a banner pointing to the old one
