### ISSUE TITLE
[Bug] Yarn 2 PnP and peer dependencies in Jest tests in workspace

### ISSUE THREAD

**Issue by kirill-konshin** [yarnpkg/berry#943]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Peer dependencies of packages cannot be found when running Jest tests in workspace.

**To Reproduce**

I have created following minimal setup: https://github.com/kirill-konshin/yarn-berry-bug

Steps to reproduce:

```bash
$ git clone https://github.com/kirill-konshin/yarn-berry-bug.git
$ yarn
$ cd ws
$ yarn test
```

Output:

```
xxx@xxx ws % yarn test
 FAIL  src/index.test.js
  ● Test suite failed to run

    Cannot find module 'react' from 'index.js'

    However, Jest was able to find:
        './Router.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      at Resolver.resolveModule (../.yarn/cache/jest-resolve-npm-25.1.0-2276a075e4-2.zip/node_modules/jest-resolve/build/index.js:276:11)
      at Object.<anonymous> (../.yarn/cache/create-react-class-npm-15.6.3-ae38dfa180-2.zip/node_modules/create-react-class/index.js:11:13)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.293s
Ran all test suites.
```

It looks like in the following setup require of `react-router` causes require of `react` in that module which can't be found. Works perfect without PNP. Adding [jest-pnp-resolver](https://github.com/arcanis/jest-pnp-resolver) does not help.

**Environment if relevant (please complete the following information):**

 - OS: Mac
 - Node version: 12.11.1
 - Yarn version: 2.0.0-rc.29

**Comment by kirill-konshin** [comment]
I dug the issue a bit more and found out that the problem specifically reproduces with old versions like `react-router@3.2.5` whereas `react-router-dom@5.1.2` works well.

I've updated my test repo: https://github.com/kirill-konshin/yarn-berry-bug

Here's the `package.json` files of both for reference (and some other packages where I found same issue):

- https://unpkg.com/react-router@3.2.5/package.json
- https://unpkg.com/react-router-dom@5.1.2/package.json
- https://unpkg.com/react-dates@18.0.2/package.json

I tried to patch the dependencies of `react-router` by adding following to `.yarnrc.yml`:

```yml
packageExtensions:
  "react-router@*":
    peerDependencies:
      react: ">=15"
```

Produced zero effect...

I've added doctor, zero results:

```
dis@xxx pnp % yarn doctor
➤ YN0000: Found 2 package(s) to process
➤ YN0000: For a grand total of 1 file(s) to validate

➤ YN0000: ┌ /pnp/package.json
➤ YN0000: └ Completed in 0.19s

➤ YN0000: ┌ /pnp/ws/package.json
➤ YN0000: └ Completed in 0.22s

➤ YN0000: Done in 0.42s
```

Worst part of the issue is that error is totally misleading, it does not give information even about the package where the error occurred.

Out of curiosity I've added `nodeLinker: node-modules`, it failed with same error. I deleted `.yarn/cache` and `.yarn/unplugged`, reinstalled, and only then it worked.

**Comment by kirill-konshin** [comment]
The only thing that really solves the problem (but in a quite dirty way) is adding this to `jest.config.js`:

```js
exports.moduleNameMapper = {
    "^react$": require.resolve('react')
};
```

But this should not be needed...

**Comment by arcanis** [comment]
Jest is "lying" and hiding the error that Yarn throws. It becomes very visible if you run your application with `YARN_DEBUG_LEVEL=1` in your environment:

![image](https://user-images.githubusercontent.com/1037931/74576460-28190c00-4f8b-11ea-92a0-2e7283158553.png)

As you can see, the true error is:

```
error: Error: A package is trying to access another package without the second one being listed as a dependency of the first one

Required package: react (via "react")
Required by: create-react-class@npm:15.6.3 (via /home/arcanis/yarn-berry-bug/.yarn/cache/create-react-class-npm-15.6.3-ae38dfa180-2.zip/node_modules/create-react-class/)
```

By looking into the sources for [`create-react-class`](https://cdn.jsdelivr.net/npm/create-react-class@15.6.3/package.json), we can see that they forgot to list the `react` peer dependency, hence why the resolution fails. Adding a `packageExtensions` entry fixes the issue:

```yaml
packageExtensions:
    "create-react-class@*":
        peerDependencies:
            react: "*"
```

![image](https://user-images.githubusercontent.com/1037931/74576538-91991a80-4f8b-11ea-862c-b5641c2fbc58.png)

**Comment by kirill-konshin** [comment]
Thank you so much! It worked like charm.

With additional debug output problem is obvious, thanks for sharing the knowledge.

**Comment by SimenB** [comment]
Hey @kirill-konshin could you open up an issue in Jest for this so we don't forget? We should improve our error message to bubble this information up, similar to what Node itself provides in newer releases

**Comment by kirill-konshin** [comment]
Done https://github.com/facebook/jest/issues/9594
