### ISSUE TITLE
[Bug] Syntax error in `.yarnrc.yml` causes a fallback to yarn classic

### ISSUE THREAD

**Issue by rkistner** [yarnpkg/berry#952]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Syntax errors in `.yarnrc.yml` causes a fallback to yarn classic, instead of displaying the error.

(This is technically a bug in yarn classic, but affects yarn berry.)

**To Reproduce**

1. Make a syntax error in `.yarnrc.yml`, such as:

```yml
packageExtensions:
  @babel/core@*: # should be surrouned in "quotes"
    #  ...
```

2. Run `yarn`.

Expected output:

```
Usage Error: Parse error when loading .yarnrc.yml; please check it's proper Yaml (in particular, make sure you list the colons after each key name)
```

Actual output:

```
yarn install v1.22.0
[1/5] Validating package.json...
...
```

**Environment if relevant (please complete the following information):**

 - OS: Ubuntu
 - Node version 12.13.0
 - Yarn version 1.22.0 installed globally; 2.0.0-rc.29 locally.

**Additional context**

A workaround is to not use the global yarn classic at all, and instead using the local yarn directly. I do this using direnv, but there are also alternatives such as proposed in #868.

**Comment by arcanis** [comment]
Fixed and released in 1.22.4
