### ISSUE TITLE
[Feature] Project-wide binaries

### ISSUE THREAD

**Issue by bgotink** [yarnpkg/berry#953]
- [x] I'd be willing to implement this feature
- [x] This feature can already be implemented through a plugin

**Describe the user story**

As a developer with projects containing multiple packages, it's annoying that I have to know what folder I'm in to run certain binaries that apply project-wide (e.g. the angular CLI's `ng` or typescript's `tsc`)

**Describe the solution you'd like**

A new kind of dependency meta that developers can use to make the binaries of a certain top-level dependency available throughout the entire project, regardless of whether the binary is invoked from within a workspace that doesn't list that package as dependency.

**Describe the drawbacks of your solution**

This could lead to confusion if a workspace includes a (different version of) a binary that's also available project-wide.

**Describe alternatives you've considered**

This could be implemented in a plugin.

**Comment by arcanis** [comment]
Two things might help:

- `yarn run -T tsc` will run tsc from the top-level
- You can define a script in any workspace that can be called from any other by adding a `:` in its name. This is for example what we do in this repository to share the [`build:compile`](https://github.com/yarnpkg/berry/blob/master/package.json#L62) task. You could for example define a script called `g:tsc` that would call the global tsc.

Overall I think those two tools are enough for the core, what do you think? More complex ones can use the `makeScriptEnv` hook to inject other global binaries if needed.

**Comment by bgotink** [comment]
Both of these work fine for running e.g. `ng` from the command line, although `yarn run -T ng` is imo a lot less ergonomic than `yarn ng` and `yarn :ng` requires knowledge of the top-level run-scripts which can quickly lead to confusion if you're working in multiple workspaces managed by different people.

I also wanted to call the top-level `ng` binary from within run-scripts in every project, but I of course forgot about `run -T` being available there as well. Ergonomics are less important for the content of run-scripts, so this doesn't really bother me at all.

Let's close this issue then :) If I find that having to run `yarn :ng`, `yarn :tsc` etc. in our repos at work is too confusing, I'll be sure to provide further feedback.
