### ISSUE TITLE
[Bug] TypeScript 3.1.6 Patch - Cannot apply hunk

### ISSUE THREAD

**Issue by nemisj** [yarnpkg/berry#974]
- [ ] I'd be willing to implement a fix

**Describe the bug**

When trying to use yarn2 for installing packages inside angular project getting error on typescript install.

**To Reproduce**

Extract package.json and package-lock.json into folder. Set yarn to version 2 and run `yarn`

[typescript-broken.zip](https://github.com/yarnpkg/berry/files/4230817/typescript-broken.zip)

**Screenshots**

![Screenshot_20200220_140822](https://user-images.githubusercontent.com/182848/74936481-80686780-53ea-11ea-87c0-f452d0914420.png)

**Environment if relevant (please complete the following information):**

 - OS: [Linux(Fedora)]
 - Node version [10.16.0, 12.16.1]
 - Yarn version [2.0.0-rc29]

**Comment by merceyz** [comment]
The typescript patch is no longer applied to that version since https://github.com/yarnpkg/berry/pull/1557, which means that version of typescript doesn't support PnP.
