### ISSUE TITLE
[Bug] `yarn workspaces foreach` gives success exit code even if a child command fails

### ISSUE THREAD

**Issue by amaranth** [yarnpkg/berry#977]
- [ ] I'd be willing to implement a fix

**Describe the bug**

When running commands on child workspaces with `yarn workspaces foreach` no matter their exit code the top level foreach command gives an exit code of `0`. It looks like child commands failing only propagates to the foreach command when you use a topological sort and a dependency fails which prevents another workspace from running. This prevents using foreach in a precommit hook to run lints or tests as the hook always succeeds.

**To Reproduce**

The easiest way is to clone the repo at https://github.com/amaranth/yarn-foreach-error and run the commands shown in the README.md file. Otherwise setup a project with workspaces, make a script in one of them that fails, and observe that `yarn workspaces foreach -v run test` gives a 0 exit code.

**Environment if relevant (please complete the following information):**

 - OS: macOS 10.15.3
 - Node version: v10.19.0
 - Yarn version: 2.0.0-rc.29

**Comment by merceyz** [comment]
Fixed in https://github.com/yarnpkg/berry/pull/1019

**Comment by tsapko3628** [comment]
I have same issue now

**Comment by merceyz** [comment]
@tsapko3628 Open a new issue with a reproduction please
