### ISSUE TITLE
[Bug]  Link step when installing on a moderately sized monorepo is taking a very long time

### ISSUE THREAD

**Issue by TomCaserta** [yarnpkg/berry#989]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Yarn takes upwards of 9 minutes in the `link step` phase of a monorepo install. In one case it took 39 
 minutes.

During this time no logs or other useful information is output.

Related to the problems @haggholm had in #818

**To Reproduce**
I am sure this is going to be a pain to reproduce however in my case:

- Have a monorepo with 19 different packages, some depending on each other in their peerDeps and devDeps 
- Run `yarn`

I am attempting to create a non-private monorepo where this can be reproduced on.

**Screenshots**
<img width="741" alt="Screen Shot 2020-02-23 at 8 55 55 PM" src="https://user-images.githubusercontent.com/592309/75118963-13213480-567f-11ea-9d7b-a365c9656669.png">

<img width="1247" alt="Screen Shot 2020-02-23 at 8 56 33 PM" src="https://user-images.githubusercontent.com/592309/75118965-174d5200-567f-11ea-83ad-98d484aac8bd.png">

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version: 11.0.1
 - Yarn version: Running from source 

**Additional context**

I found the traverse method found on this line frequently is taking a long amount of time:

https://github.com/yarnpkg/berry/blob/8b8483bc95f3e39e597c77087e61dc2c2fc21447/packages/yarnpkg-core/sources/Project.ts#L1141

It seemed to hang when processing a package that had a dependency on a common package in my monorepo.

Changing `traverse(resolution, new Set(seenPackages));` to `traverse(resolution, seenPackages);` speeds everything up, taking only 46seconds, but of course this is fundamentally changing what this method is doing. I don't have enough knowledge about what exactly this is trying to do to try and fix it myself.

Feel free to reach out for further information though or other ways of debugging what's going wrong here. I'll also try and create a reproduction repository.

**Comment by TomCaserta** [comment]
Thinking of things that could fix this.

So I presume (and understand from the description) that this method `getBuildHash` is attempting to create a hash of all dependencies for a package with a build script in order to understand if they need to be rebuilt?

From what I can see the traverse method is going through each package even if it's visited them before due to another package. Once a hash is calculated for a particular package and its dependencies, do you think that it could be put in a map so the next time it visits that package it doesn't need to traverse them again? It would result in a different hash to what is currently generated however from my understanding it would result in the same outcome, if any dependencies change a package is rebuilt?

**Comment by BYK** [comment]
>Changing traverse(resolution, new Set(seenPackages)); to traverse(resolution, seenPackages); speeds everything up, taking only 46seconds, but of course this is fundamentally changing what this method is doing. 

@TomCaserta reading the code myself, it looks like `seenPackages` is not modified inside the loop so maybe we can do the following:

```js
      const traverse = (locatorHash: LocatorHash, seenPackages: Set<string> = new Set()) => {
        hash.update(locatorHash);

        if (seenPackages.has(locatorHash))
            return;

        const pkg = this.storedPackages.get(locatorHash);
        if (!pkg)
          throw new Error(`Assertion failed: The package should have been registered`);

        const seenPackagesForDeps = new Set(seenPackages);
        seenPackagesForDeps.add(locatorHash);
        for (const dependency of pkg.dependencies.values()) {
          const resolution = this.storedResolutions.get(dependency.descriptorHash);
          if (!resolution)
            throw new Error(`Assertion failed: The resolution (${structUtils.prettyDescriptor(this.configuration, dependency)}) should have been registered`);

          const buildHash = nextBState.get(resolution);
          if (typeof buildHash !== `undefined`)
            hash.update(buildHash);

          traverse(resolution, seenPackagesForDeps);
        }
      };
```

This may speed things up a bit depending on the structure but it seems like the real solution here is to either use immutablejs sets or resort back to plain old JS objects instead of `Set`s as they are much cheaper to clone.

**Comment by arcanis** [comment]
Hmm .. I think we can even avoid all clones by doing something like this:

```ts
      const traverse = (locatorHash: LocatorHash, seenPackages: Set<string> = new Set()) => {
        seenPackages.add(locatorHash);

        for (const dependency of pkg.dependencies.values()) {
          // ...
        }

        seenPackages.delete(locatorHash);
      };
```

Can someone try that?

**Comment by arcanis** [comment]
Even better, instead of computing the build hash through `digest(A, B, C)` (assuming that `A` depends on `B` which depends on `C`), we should instead compute it via `digest(A, digest(B, digest(C)))`. This would allow us to cache in memory the intermediary results, so we'd never need to traverse the same package twice.

**Comment by TomCaserta** [comment]
> ```ts
> .delete(locatorHash);
> ```

Just tried it out and it doesn't improve much to be honest, it's still taking 8 minutes on the link step.

![Screen Shot 2020-02-24 at 11 16 32 AM](https://user-images.githubusercontent.com/592309/75144392-1e17ab80-56f7-11ea-9a5d-597663bbbd6b.png)

![Screen Shot 2020-02-24 at 11 16 43 AM](https://user-images.githubusercontent.com/592309/75144408-24a62300-56f7-11ea-815b-4af998eeaada.png)

I don't think the problem is actually with the cloning of the set. I think my change I posted in the original post only worked because it actually was not visiting all of the packages it should. I think your comment about `digest(A, digest(B, digest(C))` would be the best optio. I'll give it a try to see the results.

**Comment by TomCaserta** [comment]
Just got some time. I made what I think is a naive approach here: https://github.com/yarnpkg/berry/compare/master...TomCaserta:fix/989-long-link-step 

It just attempts to cache the build hashes and retrieve them again when visiting the same dependency. I wasn't too sure on the purpose of `globalHash` so more than likely my usage of this is incorrect though. Let me know your thoughts.

In it's current form this improves the link step reducing the amount of time it takes to ~1 minute.

**Comment by arcanis** [comment]
I think this should be fixed with the latest improvements in master! (cf #1040) I'll go ahead and close it, we can open another issue if there's something else to do.
