### ISSUE TITLE
[Bug] yarn add fails by specifying the remote URL

### ISSUE THREAD

**Issue by flymans** [yarnpkg/berry#994]
- [ ] I'd be willing to implement a fix

**Describe the bug**

After calling `yarn add <git remote url>` error is thrown: `Invalid descriptor`.
For example:
```
yarn add https://github.com/fancyapps/fancybox
Internal Error: Invalid descriptor (https://github.com/fancyapps/fancybox)
    at Object.parseDescriptor (/mnt/c/Users/pas/dev/admin-app/.yarn/releases/yarn-sources.js:48444:26)
    at /mnt/c/Users/pas/dev/admin-app/.yarn/releases/yarn-sources.js:84576:31
    at Array.map (<anonymous>)
    at AddCommand.execute (/mnt/c/Users/pas/dev/admin-app/.yarn/releases/yarn-sources.js:84571:60)
    at async AddCommand.validateAndExecute (/mnt/c/Users/pas/dev/admin-app/.yarn/releases/yarn-sources.js:55036:26)
    at async Cli.run (/mnt/c/Users/pas/dev/admin-app/.yarn/releases/yarn-sources.js:51907:24)
    at async Cli.runExit (/mnt/c/Users/pas/dev/admin-app/.yarn/releases/yarn-sources.js:51916:28)
```

**To Reproduce**
yarn add `<git remote URL>` e.g.:
`yarn add https://github.com/fancyapps/fancybox`

**Environment if relevant (please complete the following information):**

 - Node version v12.13.0
 - Yarn version 2.0.0-rc.29.git.20200223.fbd94ea8

**Comment by arcanis** [comment]
Manually specify the package name: `yarn add fancybox@fancyapps/fancybox`

**Comment by flymans** [comment]
The problem is, I still can't add dependency from my gitlab private repository.
The same error - Invalid descriptor.

**Comment by arcanis** [comment]
Invalid descriptor is a syntax error. If you don't print the command line, I can't tell you more than that 🙂

**Comment by flymans** [comment]
`yarn add git+ssh://<git remote URL>#semver:^3.2.0`     
```
Internal Error: Invalid descriptor
    at Object.parseDescriptor (.yarn\releases\yarn-sources.js:44115:26)
    at .yarn\releases\yarn-sources.js:83566:31
    at Array.map (<anonymous>)
    at AddCommand.execute (.yarn\releases\yarn-sources.js:83561:60)
    at async AddCommand.validateAndExecute (.yarn\releases\yarn-sources.js:50708:26)
    at async Cli.run (.yarn\releases\yarn-sources.js:47579:24)
    at async Cli.runExit (.yarn\releases\yarn-sources.js:47588:28)
```

**Comment by glow-mdsol** [comment]
Looks like the specific issue arises here:
https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/sources/structUtils.ts#L194-L196
The regex doesn't seem to match any of the patterns in the docs.  

I cheated by using `npm` followed by `yarn install` but it still seemed unable to resolve the pattern.  I gave up and went back to v1.23

**Comment by arcanis** [comment]
You're missing the package name:

```
yarn add <package name>@git+ssh://<git remote URL>#semver:^3.2.0
```

We only infer the package name from local directories at the moment.

**Comment by Sogl** [comment]
My installation freezes:
```
laradock@3edd7fd0dc0c:/var/www/sogl$ yarn add lightGallery@github:sachinchoolur/lightGallery -D
➤ YN0000: ┌ Resolution step
➤ YN0013: │ lightGallery@https://github.com/sachinchoolur/lightGallery.git#commit=f691d0096a4ee00641e1a3be22d4101e715f3ff3 can't be found in the cache 
➤ YN0013: │ lightGallery@https://github.com/sachinchoolur/lightGallery.git#commit=f691d0096a4ee00641e1a3be22d4101e715f3ff3 can't be found in the cache 
➤ YN0000: ⠼ unicode-property-aliases-ecmascript@npm:^1.0.4
```

Also add commant don't support `--verbose` option...

The Macintosh is warming up a lot, but nothing happens...

**Comment by ChidoYo** [comment]
I have tried the above sample but I'm getting the following error:
`error Can't add "<package-name>": invalid package version "1.0"`
My package is on my company's GitLab repo.  The version on the package.json is 1.0.   
Do I need to make the version number contain three digits?
